Begin
Comparing:  code/Tyg3R_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  9
code/551100kk_1_1/B.cpp.tk                          |  13
code/551100kk_2_1/C.cpp.tk                          |  80
code/achan1058_0_1/Q-A.cpp.tk                       |  12
code/achan1058_1_1/source.cpp.tk                    |  22
code/achan1058_2_1/source.cpp.tk                    |  34
code/alanubi_0_1/a.cpp.tk                           |  13
code/alanubi_1_1/b.cpp.tk                           |  13
code/alanubi_2_1/c.cpp.tk                           |  49
code/AntiForest_0_1/q1.cpp.tk                       |  27
code/AntiForest_1_1/q2.cpp.tk                       |  7
code/AntiForest_2_1/q3.cpp.tk                       |  106
code/apiad_0_1/A.cpp.tk                             |  13
code/apiad_1_1/B.cpp.tk                             |  17
code/apiad_2_1/C.cpp.tk                             |  191
code/azaky_0_1/A.cpp.tk                             |  18
code/azaky_1_1/B.cpp.tk                             |  19
code/azaky_2_1/C.cpp.tk                             |  316
code/azariamuh_0_1/standing.cpp.tk                  |  29
code/azariamuh_1_1/pancake.cpp.tk                   |  42
code/azariamuh_2_1/dijkstra.cpp.tk                  |  191
code/bmerry_0_1/a.cpp.tk                            |  35
code/bmerry_1_1/b.cpp.tk                            |  33
code/bmerry_2_1/c.cpp.tk                            |  187
code/climpet_0_1/A.cpp.tk                           |  21
code/climpet_1_1/B.cpp.tk                           |  18
code/climpet_2_1/C.cpp.tk                           |  159
code/ctzsm_0_1/A.cpp.tk                             |  11
code/ctzsm_1_1/B.cpp.tk                             |  13
code/ctzsm_2_1/C.cpp.tk                             |  334
code/DanilC_0_1/problem.cpp.tk                      |  22
code/DanilC_1_1/problemB.cpp.tk                     |  33
code/DanilC_2_1/problemC.cpp.tk                     |  58
code/DEGwer_0_1/A.cpp.tk                            |  13
code/DEGwer_1_1/B.cpp.tk                            |  12
code/DEGwer_2_1/C.cpp.tk                            |  75
code/dmute_0_1/a.cpp.tk                             |  7
code/dmute_1_1/b.cpp.tk                             |  14
code/dmute_2_1/c2.cpp.tk                            |  63
code/fagu_0_1/A.cpp.tk                              |  4
code/fagu_1_1/B.cpp.tk                              |  4
code/fagu_2_1/C.cpp.tk                              |  232
code/FatalEagle_0_1/main.cpp.tk                     |  10
code/FatalEagle_1_1/main.cpp.tk                     |  14
code/FatalEagle_2_1/main.cpp.tk                     |  106
code/fullpower_0_1/A.cpp.tk                         |  14
code/fullpower_1_1/B.cpp.tk                         |  26
code/fullpower_2_1/C.cpp.tk                         |  75
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  12
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  12
code/ICastro_2_1/Dijkstra.cpp.tk                    |  102
code/ilackthatsuperpower_0_1/a.cpp.tk               |  42
code/ilackthatsuperpower_1_1/b.cpp.tk               |  39
code/ilackthatsuperpower_2_1/c.cpp.tk               |  62
code/iridescent_0_1/A.cpp.tk                        |  9
code/iridescent_1_1/B.cpp.tk                        |  11
code/iridescent_2_1/C.cpp.tk                        |  320
code/ishraq_0_1/main.cpp.tk                         |  12
code/ishraq_1_1/main.cpp.tk                         |  13
code/ishraq_2_1/main.cpp.tk                         |  60
code/JayXon_0_1/A.cpp.tk                            |  7
code/JayXon_1_1/B.cpp.tk                            |  15
code/JayXon_2_1/C.cpp.tk                            |  19
code/Josse_0_1/A.cpp.tk                             |  14
code/Josse_1_1/B.cpp.tk                             |  13
code/Josse_2_1/C.cpp.tk                             |  48
code/kcm1700_0_1/a.cpp.tk                           |  11
code/kcm1700_1_1/b.cpp.tk                           |  11
code/kcm1700_2_1/c.cpp.tk                           |  73
code/kevinsogo_0_1/a.cpp.tk                         |  12
code/kevinsogo_1_1/b.cpp.tk                         |  13
code/kevinsogo_2_1/c.cpp.tk                         |  74
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  13
code/LazyAnna_0_1/1.cpp.tk                          |  13
code/LazyAnna_1_1/2-1.cpp.tk                        |  13
code/LazyAnna_2_1/3.cpp.tk                          |  68
code/Merkurev_0_1/A.cpp.tk                          |  16
code/Merkurev_1_1/B.cpp.tk                          |  18
code/Merkurev_2_1/C.cpp.tk                          |  37
code/mezei_0_1/main.cpp.tk                          |  15
code/mezei_1_1/main.cpp.tk                          |  10
code/mezei_2_1/main.cpp.tk                          |  38
code/Mister_0_1/a.cpp.tk                            |  8
code/Mister_1_1/b.cpp.tk                            |  9
code/Mister_2_1/c.cpp.tk                            |  76
code/namonakiacc_0_1/cpp.cpp.tk                     |  14
code/namonakiacc_1_1/cpp.cpp.tk                     |  17
code/namonakiacc_2_1/cpp.cpp.tk                     |  78
code/Nicolas16_0_1/main.cpp.tk                      |  4
code/Nicolas16_1_1/main.cpp.tk                      |  4
code/Nicolas16_2_1/main.cpp.tk                      |  41
code/pandamonium_0_1/a.cpp.tk                       |  8
code/pandamonium_1_1/b.cpp.tk                       |  26
code/pandamonium_2_1/c.cpp.tk                       |  85
code/pflueger_0_1/A.cpp.tk                          |  22
code/pflueger_1_1/B.cpp.tk                          |  12
code/pflueger_2_1/C.cpp.tk                          |  49
code/ponyopoppo_0_1/A.cpp.tk                        |  10
code/ponyopoppo_1_1/B.cpp.tk                        |  12
code/ponyopoppo_2_1/C.cpp.tk                        |  73
code/Ragnar_0_1/A.cpp.tk                            |  13
code/Ragnar_1_1/B-2.cpp.tk                          |  13
code/Ragnar_2_1/C.cpp.tk                            |  47
code/saffah_0_1/t.cpp.tk                            |  16
code/saffah_1_1/t.cpp.tk                            |  20
code/saffah_2_1/t.cpp.tk                            |  67
code/SamanSami_0_1/A.cpp.tk                         |  2
code/SamanSami_1_1/B.cpp.tk                         |  12
code/SamanSami_2_1/C.cpp.tk                         |  6
code/Savlik_0_1/code.cpp.tk                         |  11
code/Savlik_1_1/code.cpp.tk                         |  9
code/Savlik_2_1/code.cpp.tk                         |  33
code/shik_0_1/pa.cpp.tk                             |  36
code/shik_1_1/pb.cpp.tk                             |  33
code/shik_2_1/pc.cpp.tk                             |  114
code/simsa.st_0_1/A.cpp.tk                          |  13
code/simsa.st_1_1/B.cpp.tk                          |  14
code/simsa.st_2_1/C.cpp.tk                          |  43
code/SovietUnion_0_1/A.cpp.tk                       |  12
code/SovietUnion_1_1/B.cpp.tk                       |  14
code/SovietUnion_2_1/C.cpp.tk                       |  39
code/tailed_0_1/A.cpp.tk                            |  15
code/tailed_1_1/B.cpp.tk                            |  11
code/tailed_2_1/C.cpp.tk                            |  177
code/TheNatural_0_1/A.cpp.tk                        |  13
code/TheNatural_1_1/B.cpp.tk                        |  13
code/TheNatural_2_1/C.cpp.tk                        |  146
code/TrueBamboo_0_1/test.cpp.tk                     |  10
code/TrueBamboo_1_1/test.cpp.tk                     |  12
code/TrueBamboo_2_1/test.cpp.tk                     |  27
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  14
code/tur.turczyn_2_1/C.cpp.tk                       |  208
code/Tyg3R_0_1/A.cpp.tk                             |  17
code/Tyg3R_1_1/B.cpp.tk                             |  27
code/Tyg3R_2_1/C.cpp.tk                             |  22110
code/UminchuR_0_1/main.cpp.tk                       |  14
code/UminchuR_1_1/main.cpp.tk                       |  19
code/UminchuR_2_1/main.cpp.tk                       |  77
code/wo..._0_1/a.cpp.tk                             |  13
code/wo..._1_1/b.cpp.tk                             |  13
code/wo..._2_1/c.cpp.tk                             |  103
code/yswtt_0_1/A.cpp.tk                             |  7
code/yswtt_1_1/B.cpp.tk                             |  12
code/yswtt_2_1/C.cpp.tk                             |  53
code/ZhSh_0_1/a.cpp.tk                              |  22
code/ZhSh_1_1/b.cpp.tk                              |  33
code/ZhSh_2_1/c.cpp.tk                              |  271
