Begin
Comparing:  code/saffah_0_1/t.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  48
code/551100kk_1_1/B.cpp.tk                          |  34
code/551100kk_2_1/C.cpp.tk                          |  51
code/achan1058_0_1/Q-A.cpp.tk                       |  28
code/achan1058_1_1/source.cpp.tk                    |  30
code/achan1058_2_1/source.cpp.tk                    |  47
code/alanubi_0_1/a.cpp.tk                           |  40
code/alanubi_1_1/b.cpp.tk                           |  50
code/alanubi_2_1/c.cpp.tk                           |  89
code/AntiForest_0_1/q1.cpp.tk                       |  67
code/AntiForest_1_1/q2.cpp.tk                       |  30
code/AntiForest_2_1/q3.cpp.tk                       |  92
code/apiad_0_1/A.cpp.tk                             |  40
code/apiad_1_1/B.cpp.tk                             |  39
code/apiad_2_1/C.cpp.tk                             |  36
code/azaky_0_1/A.cpp.tk                             |  63
code/azaky_1_1/B.cpp.tk                             |  46
code/azaky_2_1/C.cpp.tk                             |  74
code/azariamuh_0_1/standing.cpp.tk                  |  38
code/azariamuh_1_1/pancake.cpp.tk                   |  54
code/azariamuh_2_1/dijkstra.cpp.tk                  |  37
code/bmerry_0_1/a.cpp.tk                            |  51
code/bmerry_1_1/b.cpp.tk                            |  44
code/bmerry_2_1/c.cpp.tk                            |  47
code/climpet_0_1/A.cpp.tk                           |  22
code/climpet_1_1/B.cpp.tk                           |  28
code/climpet_2_1/C.cpp.tk                           |  43
code/ctzsm_0_1/A.cpp.tk                             |  55
code/ctzsm_1_1/B.cpp.tk                             |  29
code/ctzsm_2_1/C.cpp.tk                             |  75
code/DanilC_0_1/problem.cpp.tk                      |  26
code/DanilC_1_1/problemB.cpp.tk                     |  45
code/DanilC_2_1/problemC.cpp.tk                     |  80
code/DEGwer_0_1/A.cpp.tk                            |  27
code/DEGwer_1_1/B.cpp.tk                            |  30
code/DEGwer_2_1/C.cpp.tk                            |  35
code/dmute_0_1/a.cpp.tk                             |  23
code/dmute_1_1/b.cpp.tk                             |  48
code/dmute_2_1/c2.cpp.tk                            |  53
code/fagu_0_1/A.cpp.tk                              |  12
code/fagu_1_1/B.cpp.tk                              |  12
code/fagu_2_1/C.cpp.tk                              |  42
code/FatalEagle_0_1/main.cpp.tk                     |  36
code/FatalEagle_1_1/main.cpp.tk                     |  32
code/FatalEagle_2_1/main.cpp.tk                     |  118
code/fullpower_0_1/A.cpp.tk                         |  29
code/fullpower_1_1/B.cpp.tk                         |  31
code/fullpower_2_1/C.cpp.tk                         |  65
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  12
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  18
code/ICastro_2_1/Dijkstra.cpp.tk                    |  94
code/ilackthatsuperpower_0_1/a.cpp.tk               |  69
code/ilackthatsuperpower_1_1/b.cpp.tk               |  68
code/ilackthatsuperpower_2_1/c.cpp.tk               |  92
code/iridescent_0_1/A.cpp.tk                        |  15
code/iridescent_1_1/B.cpp.tk                        |  21
code/iridescent_2_1/C.cpp.tk                        |  27
code/ishraq_0_1/main.cpp.tk                         |  75
code/ishraq_1_1/main.cpp.tk                         |  69
code/ishraq_2_1/main.cpp.tk                         |  107
code/JayXon_0_1/A.cpp.tk                            |  29
code/JayXon_1_1/B.cpp.tk                            |  16
code/JayXon_2_1/C.cpp.tk                            |  29
code/Josse_0_1/A.cpp.tk                             |  18
code/Josse_1_1/B.cpp.tk                             |  25
code/Josse_2_1/C.cpp.tk                             |  62
code/kcm1700_0_1/a.cpp.tk                           |  67
code/kcm1700_1_1/b.cpp.tk                           |  63
code/kcm1700_2_1/c.cpp.tk                           |  69
code/kevinsogo_0_1/a.cpp.tk                         |  105
code/kevinsogo_1_1/b.cpp.tk                         |  78
code/kevinsogo_2_1/c.cpp.tk                         |  78
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  15
code/LazyAnna_1_1/2-1.cpp.tk                        |  14
code/LazyAnna_2_1/3.cpp.tk                          |  29
code/Merkurev_0_1/A.cpp.tk                          |  53
code/Merkurev_1_1/B.cpp.tk                          |  43
code/Merkurev_2_1/C.cpp.tk                          |  41
code/mezei_0_1/main.cpp.tk                          |  28
code/mezei_1_1/main.cpp.tk                          |  22
code/mezei_2_1/main.cpp.tk                          |  61
code/Mister_0_1/a.cpp.tk                            |  59
code/Mister_1_1/b.cpp.tk                            |  58
code/Mister_2_1/c.cpp.tk                            |  42
code/namonakiacc_0_1/cpp.cpp.tk                     |  38
code/namonakiacc_1_1/cpp.cpp.tk                     |  45
code/namonakiacc_2_1/cpp.cpp.tk                     |  73
code/Nicolas16_0_1/main.cpp.tk                      |  14
code/Nicolas16_1_1/main.cpp.tk                      |  11
code/Nicolas16_2_1/main.cpp.tk                      |  60
code/pandamonium_0_1/a.cpp.tk                       |  25
code/pandamonium_1_1/b.cpp.tk                       |  37
code/pandamonium_2_1/c.cpp.tk                       |  35
code/pflueger_0_1/A.cpp.tk                          |  18
code/pflueger_1_1/B.cpp.tk                          |  16
code/pflueger_2_1/C.cpp.tk                          |  40
code/ponyopoppo_0_1/A.cpp.tk                        |  31
code/ponyopoppo_1_1/B.cpp.tk                        |  23
code/ponyopoppo_2_1/C.cpp.tk                        |  100
code/Ragnar_0_1/A.cpp.tk                            |  28
code/Ragnar_1_1/B-2.cpp.tk                          |  21
code/Ragnar_2_1/C.cpp.tk                            |  31
code/saffah_0_1/t.cpp.tk                            |  3152
code/saffah_1_1/t.cpp.tk                            |  116
code/saffah_2_1/t.cpp.tk                            |  107
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  13
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  36
code/Savlik_1_1/code.cpp.tk                         |  16
code/Savlik_2_1/code.cpp.tk                         |  47
code/shik_0_1/pa.cpp.tk                             |  95
code/shik_1_1/pb.cpp.tk                             |  61
code/shik_2_1/pc.cpp.tk                             |  101
code/simsa.st_0_1/A.cpp.tk                          |  37
code/simsa.st_1_1/B.cpp.tk                          |  88
code/simsa.st_2_1/C.cpp.tk                          |  103
code/SovietUnion_0_1/A.cpp.tk                       |  28
code/SovietUnion_1_1/B.cpp.tk                       |  35
code/SovietUnion_2_1/C.cpp.tk                       |  53
code/tailed_0_1/A.cpp.tk                            |  39
code/tailed_1_1/B.cpp.tk                            |  17
code/tailed_2_1/C.cpp.tk                            |  38
code/TheNatural_0_1/A.cpp.tk                        |  32
code/TheNatural_1_1/B.cpp.tk                        |  17
code/TheNatural_2_1/C.cpp.tk                        |  20
code/TrueBamboo_0_1/test.cpp.tk                     |  18
code/TrueBamboo_1_1/test.cpp.tk                     |  21
code/TrueBamboo_2_1/test.cpp.tk                     |  39
code/tur.turczyn_0_1/A.cpp.tk                       |  14
code/tur.turczyn_1_1/B.cpp.tk                       |  20
code/tur.turczyn_2_1/C.cpp.tk                       |  28
code/Tyg3R_0_1/A.cpp.tk                             |  21
code/Tyg3R_1_1/B.cpp.tk                             |  39
code/Tyg3R_2_1/C.cpp.tk                             |  44
code/UminchuR_0_1/main.cpp.tk                       |  39
code/UminchuR_1_1/main.cpp.tk                       |  50
code/UminchuR_2_1/main.cpp.tk                       |  64
code/wo..._0_1/a.cpp.tk                             |  37
code/wo..._1_1/b.cpp.tk                             |  37
code/wo..._2_1/c.cpp.tk                             |  70
code/yswtt_0_1/A.cpp.tk                             |  38
code/yswtt_1_1/B.cpp.tk                             |  22
code/yswtt_2_1/C.cpp.tk                             |  38
code/ZhSh_0_1/a.cpp.tk                              |  13
code/ZhSh_1_1/b.cpp.tk                              |  54
code/ZhSh_2_1/c.cpp.tk                              |  68
