Begin
Comparing:  code/kevinsogo_1_1/b.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  24
code/551100kk_1_1/B.cpp.tk                          |  46
code/551100kk_2_1/C.cpp.tk                          |  53
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  36
code/achan1058_2_1/source.cpp.tk                    |  72
code/alanubi_0_1/a.cpp.tk                           |  36
code/alanubi_1_1/b.cpp.tk                           |  57
code/alanubi_2_1/c.cpp.tk                           |  101
code/AntiForest_0_1/q1.cpp.tk                       |  31
code/AntiForest_1_1/q2.cpp.tk                       |  16
code/AntiForest_2_1/q3.cpp.tk                       |  73
code/apiad_0_1/A.cpp.tk                             |  23
code/apiad_1_1/B.cpp.tk                             |  40
code/apiad_2_1/C.cpp.tk                             |  33
code/azaky_0_1/A.cpp.tk                             |  26
code/azaky_1_1/B.cpp.tk                             |  59
code/azaky_2_1/C.cpp.tk                             |  71
code/azariamuh_0_1/standing.cpp.tk                  |  24
code/azariamuh_1_1/pancake.cpp.tk                   |  49
code/azariamuh_2_1/dijkstra.cpp.tk                  |  30
code/bmerry_0_1/a.cpp.tk                            |  46
code/bmerry_1_1/b.cpp.tk                            |  64
code/bmerry_2_1/c.cpp.tk                            |  61
code/climpet_0_1/A.cpp.tk                           |  31
code/climpet_1_1/B.cpp.tk                           |  47
code/climpet_2_1/C.cpp.tk                           |  65
code/ctzsm_0_1/A.cpp.tk                             |  25
code/ctzsm_1_1/B.cpp.tk                             |  43
code/ctzsm_2_1/C.cpp.tk                             |  87
code/DanilC_0_1/problem.cpp.tk                      |  33
code/DanilC_1_1/problemB.cpp.tk                     |  66
code/DanilC_2_1/problemC.cpp.tk                     |  130
code/DEGwer_0_1/A.cpp.tk                            |  35
code/DEGwer_1_1/B.cpp.tk                            |  50
code/DEGwer_2_1/C.cpp.tk                            |  37
code/dmute_0_1/a.cpp.tk                             |  18
code/dmute_1_1/b.cpp.tk                             |  53
code/dmute_2_1/c2.cpp.tk                            |  63
code/fagu_0_1/A.cpp.tk                              |  12
code/fagu_1_1/B.cpp.tk                              |  13
code/fagu_2_1/C.cpp.tk                              |  42
code/FatalEagle_0_1/main.cpp.tk                     |  28
code/FatalEagle_1_1/main.cpp.tk                     |  51
code/FatalEagle_2_1/main.cpp.tk                     |  183
code/fullpower_0_1/A.cpp.tk                         |  36
code/fullpower_1_1/B.cpp.tk                         |  45
code/fullpower_2_1/C.cpp.tk                         |  90
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  13
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  33
code/ICastro_2_1/Dijkstra.cpp.tk                    |  100
code/ilackthatsuperpower_0_1/a.cpp.tk               |  92
code/ilackthatsuperpower_1_1/b.cpp.tk               |  96
code/ilackthatsuperpower_2_1/c.cpp.tk               |  128
code/iridescent_0_1/A.cpp.tk                        |  13
code/iridescent_1_1/B.cpp.tk                        |  36
code/iridescent_2_1/C.cpp.tk                        |  29
code/ishraq_0_1/main.cpp.tk                         |  37
code/ishraq_1_1/main.cpp.tk                         |  52
code/ishraq_2_1/main.cpp.tk                         |  97
code/JayXon_0_1/A.cpp.tk                            |  8
code/JayXon_1_1/B.cpp.tk                            |  26
code/JayXon_2_1/C.cpp.tk                            |  41
code/Josse_0_1/A.cpp.tk                             |  18
code/Josse_1_1/B.cpp.tk                             |  38
code/Josse_2_1/C.cpp.tk                             |  92
code/kcm1700_0_1/a.cpp.tk                           |  52
code/kcm1700_1_1/b.cpp.tk                           |  69
code/kcm1700_2_1/c.cpp.tk                           |  83
code/kevinsogo_0_1/a.cpp.tk                         |  142
code/kevinsogo_1_1/b.cpp.tk                         |  5331
code/kevinsogo_2_1/c.cpp.tk                         |  104
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  15
code/LazyAnna_0_1/1.cpp.tk                          |  14
code/LazyAnna_1_1/2-1.cpp.tk                        |  23
code/LazyAnna_2_1/3.cpp.tk                          |  39
code/Merkurev_0_1/A.cpp.tk                          |  49
code/Merkurev_1_1/B.cpp.tk                          |  58
code/Merkurev_2_1/C.cpp.tk                          |  55
code/mezei_0_1/main.cpp.tk                          |  31
code/mezei_1_1/main.cpp.tk                          |  37
code/mezei_2_1/main.cpp.tk                          |  75
code/Mister_0_1/a.cpp.tk                            |  47
code/Mister_1_1/b.cpp.tk                            |  60
code/Mister_2_1/c.cpp.tk                            |  46
code/namonakiacc_0_1/cpp.cpp.tk                     |  34
code/namonakiacc_1_1/cpp.cpp.tk                     |  50
code/namonakiacc_2_1/cpp.cpp.tk                     |  74
code/Nicolas16_0_1/main.cpp.tk                      |  15
code/Nicolas16_1_1/main.cpp.tk                      |  13
code/Nicolas16_2_1/main.cpp.tk                      |  76
code/pandamonium_0_1/a.cpp.tk                       |  20
code/pandamonium_1_1/b.cpp.tk                       |  51
code/pandamonium_2_1/c.cpp.tk                       |  34
code/pflueger_0_1/A.cpp.tk                          |  15
code/pflueger_1_1/B.cpp.tk                          |  26
code/pflueger_2_1/C.cpp.tk                          |  59
code/ponyopoppo_0_1/A.cpp.tk                        |  21
code/ponyopoppo_1_1/B.cpp.tk                        |  45
code/ponyopoppo_2_1/C.cpp.tk                        |  144
code/Ragnar_0_1/A.cpp.tk                            |  26
code/Ragnar_1_1/B-2.cpp.tk                          |  46
code/Ragnar_2_1/C.cpp.tk                            |  43
code/saffah_0_1/t.cpp.tk                            |  62
code/saffah_1_1/t.cpp.tk                            |  72
code/saffah_2_1/t.cpp.tk                            |  92
code/SamanSami_0_1/A.cpp.tk                         |  4
code/SamanSami_1_1/B.cpp.tk                         |  24
code/SamanSami_2_1/C.cpp.tk                         |  11
code/Savlik_0_1/code.cpp.tk                         |  16
code/Savlik_1_1/code.cpp.tk                         |  31
code/Savlik_2_1/code.cpp.tk                         |  70
code/shik_0_1/pa.cpp.tk                             |  66
code/shik_1_1/pb.cpp.tk                             |  71
code/shik_2_1/pc.cpp.tk                             |  104
code/simsa.st_0_1/A.cpp.tk                          |  25
code/simsa.st_1_1/B.cpp.tk                          |  78
code/simsa.st_2_1/C.cpp.tk                          |  104
code/SovietUnion_0_1/A.cpp.tk                       |  27
code/SovietUnion_1_1/B.cpp.tk                       |  47
code/SovietUnion_2_1/C.cpp.tk                       |  69
code/tailed_0_1/A.cpp.tk                            |  16
code/tailed_1_1/B.cpp.tk                            |  40
code/tailed_2_1/C.cpp.tk                            |  45
code/TheNatural_0_1/A.cpp.tk                        |  17
code/TheNatural_1_1/B.cpp.tk                        |  30
code/TheNatural_2_1/C.cpp.tk                        |  22
code/TrueBamboo_0_1/test.cpp.tk                     |  19
code/TrueBamboo_1_1/test.cpp.tk                     |  36
code/TrueBamboo_2_1/test.cpp.tk                     |  49
code/tur.turczyn_0_1/A.cpp.tk                       |  17
code/tur.turczyn_1_1/B.cpp.tk                       |  40
code/tur.turczyn_2_1/C.cpp.tk                       |  40
code/Tyg3R_0_1/A.cpp.tk                             |  18
code/Tyg3R_1_1/B.cpp.tk                             |  31
code/Tyg3R_2_1/C.cpp.tk                             |  28
code/UminchuR_0_1/main.cpp.tk                       |  42
code/UminchuR_1_1/main.cpp.tk                       |  77
code/UminchuR_2_1/main.cpp.tk                       |  97
code/wo..._0_1/a.cpp.tk                             |  37
code/wo..._1_1/b.cpp.tk                             |  45
code/wo..._2_1/c.cpp.tk                             |  81
code/yswtt_0_1/A.cpp.tk                             |  13
code/yswtt_1_1/B.cpp.tk                             |  35
code/yswtt_2_1/C.cpp.tk                             |  45
code/ZhSh_0_1/a.cpp.tk                              |  14
code/ZhSh_1_1/b.cpp.tk                              |  104
code/ZhSh_2_1/c.cpp.tk                              |  85
