Begin
Comparing:  code/yswtt_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  14
code/551100kk_1_1/B.cpp.tk                          |  70
code/551100kk_2_1/C.cpp.tk                          |  38
code/achan1058_0_1/Q-A.cpp.tk                       |  10
code/achan1058_1_1/source.cpp.tk                    |  27
code/achan1058_2_1/source.cpp.tk                    |  40
code/alanubi_0_1/a.cpp.tk                           |  31
code/alanubi_1_1/b.cpp.tk                           |  56
code/alanubi_2_1/c.cpp.tk                           |  123
code/AntiForest_0_1/q1.cpp.tk                       |  14
code/AntiForest_1_1/q2.cpp.tk                       |  6
code/AntiForest_2_1/q3.cpp.tk                       |  53
code/apiad_0_1/A.cpp.tk                             |  14
code/apiad_1_1/B.cpp.tk                             |  25
code/apiad_2_1/C.cpp.tk                             |  26
code/azaky_0_1/A.cpp.tk                             |  13
code/azaky_1_1/B.cpp.tk                             |  24
code/azaky_2_1/C.cpp.tk                             |  43
code/azariamuh_0_1/standing.cpp.tk                  |  11
code/azariamuh_1_1/pancake.cpp.tk                   |  26
code/azariamuh_2_1/dijkstra.cpp.tk                  |  18
code/bmerry_0_1/a.cpp.tk                            |  63
code/bmerry_1_1/b.cpp.tk                            |  142
code/bmerry_2_1/c.cpp.tk                            |  80
code/climpet_0_1/A.cpp.tk                           |  76
code/climpet_1_1/B.cpp.tk                           |  150
code/climpet_2_1/C.cpp.tk                           |  123
code/ctzsm_0_1/A.cpp.tk                             |  51
code/ctzsm_1_1/B.cpp.tk                             |  104
code/ctzsm_2_1/C.cpp.tk                             |  149
code/DanilC_0_1/problem.cpp.tk                      |  75
code/DanilC_1_1/problemB.cpp.tk                     |  205
code/DanilC_2_1/problemC.cpp.tk                     |  167
code/DEGwer_0_1/A.cpp.tk                            |  48
code/DEGwer_1_1/B.cpp.tk                            |  62
code/DEGwer_2_1/C.cpp.tk                            |  44
code/dmute_0_1/a.cpp.tk                             |  26
code/dmute_1_1/b.cpp.tk                             |  56
code/dmute_2_1/c2.cpp.tk                            |  82
code/fagu_0_1/A.cpp.tk                              |  16
code/fagu_1_1/B.cpp.tk                              |  18
code/fagu_2_1/C.cpp.tk                              |  35
code/FatalEagle_0_1/main.cpp.tk                     |  28
code/FatalEagle_1_1/main.cpp.tk                     |  75
code/FatalEagle_2_1/main.cpp.tk                     |  257
code/fullpower_0_1/A.cpp.tk                         |  52
code/fullpower_1_1/B.cpp.tk                         |  99
code/fullpower_2_1/C.cpp.tk                         |  141
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  75
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  157
code/ICastro_2_1/Dijkstra.cpp.tk                    |  113
code/ilackthatsuperpower_0_1/a.cpp.tk               |  103
code/ilackthatsuperpower_1_1/b.cpp.tk               |  129
code/ilackthatsuperpower_2_1/c.cpp.tk               |  136
code/iridescent_0_1/A.cpp.tk                        |  55
code/iridescent_1_1/B.cpp.tk                        |  164
code/iridescent_2_1/C.cpp.tk                        |  119
code/ishraq_0_1/main.cpp.tk                         |  10
code/ishraq_1_1/main.cpp.tk                         |  26
code/ishraq_2_1/main.cpp.tk                         |  53
code/JayXon_0_1/A.cpp.tk                            |  17
code/JayXon_1_1/B.cpp.tk                            |  58
code/JayXon_2_1/C.cpp.tk                            |  30
code/Josse_0_1/A.cpp.tk                             |  38
code/Josse_1_1/B.cpp.tk                             |  102
code/Josse_2_1/C.cpp.tk                             |  121
code/kcm1700_0_1/a.cpp.tk                           |  30
code/kcm1700_1_1/b.cpp.tk                           |  84
code/kcm1700_2_1/c.cpp.tk                           |  95
code/kevinsogo_0_1/a.cpp.tk                         |  14
code/kevinsogo_1_1/b.cpp.tk                         |  26
code/kevinsogo_2_1/c.cpp.tk                         |  57
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  10
code/LazyAnna_0_1/1.cpp.tk                          |  60
code/LazyAnna_1_1/2-1.cpp.tk                        |  153
code/LazyAnna_2_1/3.cpp.tk                          |  48
code/Merkurev_0_1/A.cpp.tk                          |  43
code/Merkurev_1_1/B.cpp.tk                          |  70
code/Merkurev_2_1/C.cpp.tk                          |  82
code/mezei_0_1/main.cpp.tk                          |  40
code/mezei_1_1/main.cpp.tk                          |  61
code/mezei_2_1/main.cpp.tk                          |  84
code/Mister_0_1/a.cpp.tk                            |  68
code/Mister_1_1/b.cpp.tk                            |  134
code/Mister_2_1/c.cpp.tk                            |  97
code/namonakiacc_0_1/cpp.cpp.tk                     |  19
code/namonakiacc_1_1/cpp.cpp.tk                     |  27
code/namonakiacc_2_1/cpp.cpp.tk                     |  45
code/Nicolas16_0_1/main.cpp.tk                      |  15
code/Nicolas16_1_1/main.cpp.tk                      |  14
code/Nicolas16_2_1/main.cpp.tk                      |  101
code/pandamonium_0_1/a.cpp.tk                       |  27
code/pandamonium_1_1/b.cpp.tk                       |  89
code/pandamonium_2_1/c.cpp.tk                       |  46
code/pflueger_0_1/A.cpp.tk                          |  60
code/pflueger_1_1/B.cpp.tk                          |  103
code/pflueger_2_1/C.cpp.tk                          |  111
code/ponyopoppo_0_1/A.cpp.tk                        |  20
code/ponyopoppo_1_1/B.cpp.tk                        |  74
code/ponyopoppo_2_1/C.cpp.tk                        |  89
code/Ragnar_0_1/A.cpp.tk                            |  17
code/Ragnar_1_1/B-2.cpp.tk                          |  56
code/Ragnar_2_1/C.cpp.tk                            |  67
code/saffah_0_1/t.cpp.tk                            |  14
code/saffah_1_1/t.cpp.tk                            |  21
code/saffah_2_1/t.cpp.tk                            |  48
code/SamanSami_0_1/A.cpp.tk                         |  25
code/SamanSami_1_1/B.cpp.tk                         |  81
code/SamanSami_2_1/C.cpp.tk                         |  6
code/Savlik_0_1/code.cpp.tk                         |  18
code/Savlik_1_1/code.cpp.tk                         |  12
code/Savlik_2_1/code.cpp.tk                         |  51
code/shik_0_1/pa.cpp.tk                             |  37
code/shik_1_1/pb.cpp.tk                             |  43
code/shik_2_1/pc.cpp.tk                             |  76
code/simsa.st_0_1/A.cpp.tk                          |  10
code/simsa.st_1_1/B.cpp.tk                          |  21
code/simsa.st_2_1/C.cpp.tk                          |  49
code/SovietUnion_0_1/A.cpp.tk                       |  62
code/SovietUnion_1_1/B.cpp.tk                       |  134
code/SovietUnion_2_1/C.cpp.tk                       |  67
code/tailed_0_1/A.cpp.tk                            |  43
code/tailed_1_1/B.cpp.tk                            |  81
code/tailed_2_1/C.cpp.tk                            |  36
code/TheNatural_0_1/A.cpp.tk                        |  56
code/TheNatural_1_1/B.cpp.tk                        |  78
code/TheNatural_2_1/C.cpp.tk                        |  44
code/TrueBamboo_0_1/test.cpp.tk                     |  17
code/TrueBamboo_1_1/test.cpp.tk                     |  49
code/TrueBamboo_2_1/test.cpp.tk                     |  40
code/tur.turczyn_0_1/A.cpp.tk                       |  19
code/tur.turczyn_1_1/B.cpp.tk                       |  26
code/tur.turczyn_2_1/C.cpp.tk                       |  30
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  23
code/Tyg3R_2_1/C.cpp.tk                             |  21
code/UminchuR_0_1/main.cpp.tk                       |  17
code/UminchuR_1_1/main.cpp.tk                       |  60
code/UminchuR_2_1/main.cpp.tk                       |  46
code/wo..._0_1/a.cpp.tk                             |  50
code/wo..._1_1/b.cpp.tk                             |  54
code/wo..._2_1/c.cpp.tk                             |  110
code/yswtt_0_1/A.cpp.tk                             |  100
code/yswtt_1_1/B.cpp.tk                             |  7746
code/yswtt_2_1/C.cpp.tk                             |  137
code/ZhSh_0_1/a.cpp.tk                              |  106
code/ZhSh_1_1/b.cpp.tk                              |  146
code/ZhSh_2_1/c.cpp.tk                              |  112
