Begin
Comparing:  code/azariamuh_2_1/dijkstra.cpp.tk
code/00/test.cpp.tk                                 |  15
code/01/test.cpp.tk                                 |  15
code/551100kk_0_1/A.cpp.tk                          |  19
code/551100kk_1_1/B.cpp.tk                          |  29
code/551100kk_2_1/C.cpp.tk                          |  107
code/achan1058_0_1/Q-A.cpp.tk                       |  14
code/achan1058_1_1/source.cpp.tk                    |  32
code/achan1058_2_1/source.cpp.tk                    |  82
code/alanubi_0_1/a.cpp.tk                           |  18
code/alanubi_1_1/b.cpp.tk                           |  26
code/alanubi_2_1/c.cpp.tk                           |  100
code/AntiForest_0_1/q1.cpp.tk                       |  36
code/AntiForest_1_1/q2.cpp.tk                       |  21
code/AntiForest_2_1/q3.cpp.tk                       |  131
code/apiad_0_1/A.cpp.tk                             |  22
code/apiad_1_1/B.cpp.tk                             |  41
code/apiad_2_1/C.cpp.tk                             |  64
code/azaky_0_1/A.cpp.tk                             |  41
code/azaky_1_1/B.cpp.tk                             |  46
code/azaky_2_1/C.cpp.tk                             |  344
code/azariamuh_0_1/standing.cpp.tk                  |  44
code/azariamuh_1_1/pancake.cpp.tk                   |  59
code/azariamuh_2_1/dijkstra.cpp.tk                  |  31565
code/bmerry_0_1/a.cpp.tk                            |  62
code/bmerry_1_1/b.cpp.tk                            |  69
code/bmerry_2_1/c.cpp.tk                            |  100
code/climpet_0_1/A.cpp.tk                           |  34
code/climpet_1_1/B.cpp.tk                           |  37
code/climpet_2_1/C.cpp.tk                           |  89
code/ctzsm_0_1/A.cpp.tk                             |  28
code/ctzsm_1_1/B.cpp.tk                             |  35
code/ctzsm_2_1/C.cpp.tk                             |  369
code/DanilC_0_1/problem.cpp.tk                      |  35
code/DanilC_1_1/problemB.cpp.tk                     |  51
code/DanilC_2_1/problemC.cpp.tk                     |  129
code/DEGwer_0_1/A.cpp.tk                            |  28
code/DEGwer_1_1/B.cpp.tk                            |  29
code/DEGwer_2_1/C.cpp.tk                            |  111
code/dmute_0_1/a.cpp.tk                             |  17
code/dmute_1_1/b.cpp.tk                             |  26
code/dmute_2_1/c2.cpp.tk                            |  132
code/fagu_0_1/A.cpp.tk                              |  15
code/fagu_1_1/B.cpp.tk                              |  17
code/fagu_2_1/C.cpp.tk                              |  99
code/FatalEagle_0_1/main.cpp.tk                     |  27
code/FatalEagle_1_1/main.cpp.tk                     |  36
code/FatalEagle_2_1/main.cpp.tk                     |  188
code/fullpower_0_1/A.cpp.tk                         |  32
code/fullpower_1_1/B.cpp.tk                         |  36
code/fullpower_2_1/C.cpp.tk                         |  139
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  13
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  20
code/ICastro_2_1/Dijkstra.cpp.tk                    |  153
code/ilackthatsuperpower_0_1/a.cpp.tk               |  96
code/ilackthatsuperpower_1_1/b.cpp.tk               |  99
code/ilackthatsuperpower_2_1/c.cpp.tk               |  161
code/iridescent_0_1/A.cpp.tk                        |  12
code/iridescent_1_1/B.cpp.tk                        |  17
code/iridescent_2_1/C.cpp.tk                        |  75
code/ishraq_0_1/main.cpp.tk                         |  19
code/ishraq_1_1/main.cpp.tk                         |  25
code/ishraq_2_1/main.cpp.tk                         |  134
code/JayXon_0_1/A.cpp.tk                            |  10
code/JayXon_1_1/B.cpp.tk                            |  26
code/JayXon_2_1/C.cpp.tk                            |  60
code/Josse_0_1/A.cpp.tk                             |  16
code/Josse_1_1/B.cpp.tk                             |  21
code/Josse_2_1/C.cpp.tk                             |  102
code/kcm1700_0_1/a.cpp.tk                           |  15
code/kcm1700_1_1/b.cpp.tk                           |  23
code/kcm1700_2_1/c.cpp.tk                           |  95
code/kevinsogo_0_1/a.cpp.tk                         |  20
code/kevinsogo_1_1/b.cpp.tk                         |  23
code/kevinsogo_2_1/c.cpp.tk                         |  99
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  36
code/LazyAnna_0_1/1.cpp.tk                          |  14
code/LazyAnna_1_1/2-1.cpp.tk                        |  21
code/LazyAnna_2_1/3.cpp.tk                          |  72
code/Merkurev_0_1/A.cpp.tk                          |  24
code/Merkurev_1_1/B.cpp.tk                          |  53
code/Merkurev_2_1/C.cpp.tk                          |  51
code/mezei_0_1/main.cpp.tk                          |  26
