Begin
Comparing:  code/Tyg3R_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  20
code/551100kk_1_1/B.cpp.tk                          |  37
code/551100kk_2_1/C.cpp.tk                          |  60
code/achan1058_0_1/Q-A.cpp.tk                       |  21
code/achan1058_1_1/source.cpp.tk                    |  46
code/achan1058_2_1/source.cpp.tk                    |  72
code/alanubi_0_1/a.cpp.tk                           |  15
code/alanubi_1_1/b.cpp.tk                           |  29
code/alanubi_2_1/c.cpp.tk                           |  76
code/AntiForest_0_1/q1.cpp.tk                       |  49
code/AntiForest_1_1/q2.cpp.tk                       |  24
code/AntiForest_2_1/q3.cpp.tk                       |  143
code/apiad_0_1/A.cpp.tk                             |  27
code/apiad_1_1/B.cpp.tk                             |  37
code/apiad_2_1/C.cpp.tk                             |  44
code/azaky_0_1/A.cpp.tk                             |  44
code/azaky_1_1/B.cpp.tk                             |  69
code/azaky_2_1/C.cpp.tk                             |  87
code/azariamuh_0_1/standing.cpp.tk                  |  33
code/azariamuh_1_1/pancake.cpp.tk                   |  89
code/azariamuh_2_1/dijkstra.cpp.tk                  |  40
code/bmerry_0_1/a.cpp.tk                            |  55
code/bmerry_1_1/b.cpp.tk                            |  62
code/bmerry_2_1/c.cpp.tk                            |  68
code/climpet_0_1/A.cpp.tk                           |  29
code/climpet_1_1/B.cpp.tk                           |  34
code/climpet_2_1/C.cpp.tk                           |  63
code/ctzsm_0_1/A.cpp.tk                             |  21
code/ctzsm_1_1/B.cpp.tk                             |  33
code/ctzsm_2_1/C.cpp.tk                             |  106
code/DanilC_0_1/problem.cpp.tk                      |  33
code/DanilC_1_1/problemB.cpp.tk                     |  61
code/DanilC_2_1/problemC.cpp.tk                     |  124
code/DEGwer_0_1/A.cpp.tk                            |  27
code/DEGwer_1_1/B.cpp.tk                            |  34
code/DEGwer_2_1/C.cpp.tk                            |  42
code/dmute_0_1/a.cpp.tk                             |  15
code/dmute_1_1/b.cpp.tk                             |  29
code/dmute_2_1/c2.cpp.tk                            |  57
code/fagu_0_1/A.cpp.tk                              |  11
code/fagu_1_1/B.cpp.tk                              |  15
code/fagu_2_1/C.cpp.tk                              |  61
code/FatalEagle_0_1/main.cpp.tk                     |  20
code/FatalEagle_1_1/main.cpp.tk                     |  29
code/FatalEagle_2_1/main.cpp.tk                     |  187
code/fullpower_0_1/A.cpp.tk                         |  30
code/fullpower_1_1/B.cpp.tk                         |  42
code/fullpower_2_1/C.cpp.tk                         |  92
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  12
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  24
code/ICastro_2_1/Dijkstra.cpp.tk                    |  140
code/ilackthatsuperpower_0_1/a.cpp.tk               |  97
code/ilackthatsuperpower_1_1/b.cpp.tk               |  97
code/ilackthatsuperpower_2_1/c.cpp.tk               |  138
code/iridescent_0_1/A.cpp.tk                        |  12
code/iridescent_1_1/B.cpp.tk                        |  27
code/iridescent_2_1/C.cpp.tk                        |  28
code/ishraq_0_1/main.cpp.tk                         |  23
code/ishraq_1_1/main.cpp.tk                         |  34
code/ishraq_2_1/main.cpp.tk                         |  114
code/JayXon_0_1/A.cpp.tk                            |  9
code/JayXon_1_1/B.cpp.tk                            |  27
code/JayXon_2_1/C.cpp.tk                            |  42
code/Josse_0_1/A.cpp.tk                             |  14
code/Josse_1_1/B.cpp.tk                             |  28
code/Josse_2_1/C.cpp.tk                             |  93
code/kcm1700_0_1/a.cpp.tk                           |  14
code/kcm1700_1_1/b.cpp.tk                           |  33
code/kcm1700_2_1/c.cpp.tk                           |  80
code/kevinsogo_0_1/a.cpp.tk                         |  26
code/kevinsogo_1_1/b.cpp.tk                         |  28
code/kevinsogo_2_1/c.cpp.tk                         |  97
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  14
code/LazyAnna_0_1/1.cpp.tk                          |  12
code/LazyAnna_1_1/2-1.cpp.tk                        |  20
code/LazyAnna_2_1/3.cpp.tk                          |  42
code/Merkurev_0_1/A.cpp.tk                          |  23
code/Merkurev_1_1/B.cpp.tk                          |  43
code/Merkurev_2_1/C.cpp.tk                          |  48
code/mezei_0_1/main.cpp.tk                          |  24
code/mezei_1_1/main.cpp.tk                          |  22
code/mezei_2_1/main.cpp.tk                          |  74
code/Mister_0_1/a.cpp.tk                            |  16
code/Mister_1_1/b.cpp.tk                            |  25
code/Mister_2_1/c.cpp.tk                            |  44
code/namonakiacc_0_1/cpp.cpp.tk                     |  28
code/namonakiacc_1_1/cpp.cpp.tk                     |  40
code/namonakiacc_2_1/cpp.cpp.tk                     |  79
code/Nicolas16_0_1/main.cpp.tk                      |  10
code/Nicolas16_1_1/main.cpp.tk                      |  9
code/Nicolas16_2_1/main.cpp.tk                      |  76
code/pandamonium_0_1/a.cpp.tk                       |  16
code/pandamonium_1_1/b.cpp.tk                       |  48
code/pandamonium_2_1/c.cpp.tk                       |  32
code/pflueger_0_1/A.cpp.tk                          |  11
code/pflueger_1_1/B.cpp.tk                          |  24
code/pflueger_2_1/C.cpp.tk                          |  61
code/ponyopoppo_0_1/A.cpp.tk                        |  14
code/ponyopoppo_1_1/B.cpp.tk                        |  30
code/ponyopoppo_2_1/C.cpp.tk                        |  152
code/Ragnar_0_1/A.cpp.tk                            |  18
code/Ragnar_1_1/B-2.cpp.tk                          |  30
code/Ragnar_2_1/C.cpp.tk                            |  43
code/saffah_0_1/t.cpp.tk                            |  31
code/saffah_1_1/t.cpp.tk                            |  51
code/saffah_2_1/t.cpp.tk                            |  130
code/SamanSami_0_1/A.cpp.tk                         |  4
code/SamanSami_1_1/B.cpp.tk                         |  21
code/SamanSami_2_1/C.cpp.tk                         |  13
code/Savlik_0_1/code.cpp.tk                         |  19
code/Savlik_1_1/code.cpp.tk                         |  31
code/Savlik_2_1/code.cpp.tk                         |  72
code/shik_0_1/pa.cpp.tk                             |  95
code/shik_1_1/pb.cpp.tk                             |  81
code/shik_2_1/pc.cpp.tk                             |  143
code/simsa.st_0_1/A.cpp.tk                          |  28
code/simsa.st_1_1/B.cpp.tk                          |  36
code/simsa.st_2_1/C.cpp.tk                          |  109
code/SovietUnion_0_1/A.cpp.tk                       |  24
code/SovietUnion_1_1/B.cpp.tk                       |  32
code/SovietUnion_2_1/C.cpp.tk                       |  84
code/tailed_0_1/A.cpp.tk                            |  11
code/tailed_1_1/B.cpp.tk                            |  22
code/tailed_2_1/C.cpp.tk                            |  47
code/TheNatural_0_1/A.cpp.tk                        |  16
code/TheNatural_1_1/B.cpp.tk                        |  20
code/TheNatural_2_1/C.cpp.tk                        |  25
code/TrueBamboo_0_1/test.cpp.tk                     |  17
code/TrueBamboo_1_1/test.cpp.tk                     |  29
code/TrueBamboo_2_1/test.cpp.tk                     |  56
code/tur.turczyn_0_1/A.cpp.tk                       |  12
code/tur.turczyn_1_1/B.cpp.tk                       |  33
code/tur.turczyn_2_1/C.cpp.tk                       |  27
code/Tyg3R_0_1/A.cpp.tk                             |  39
code/Tyg3R_1_1/B.cpp.tk                             |  4924
code/Tyg3R_2_1/C.cpp.tk                             |  58
code/UminchuR_0_1/main.cpp.tk                       |  24
code/UminchuR_1_1/main.cpp.tk                       |  41
code/UminchuR_2_1/main.cpp.tk                       |  72
code/wo..._0_1/a.cpp.tk                             |  25
code/wo..._1_1/b.cpp.tk                             |  28
code/wo..._2_1/c.cpp.tk                             |  81
code/yswtt_0_1/A.cpp.tk                             |  10
code/yswtt_1_1/B.cpp.tk                             |  29
code/yswtt_2_1/C.cpp.tk                             |  41
code/ZhSh_0_1/a.cpp.tk                              |  10
code/ZhSh_1_1/b.cpp.tk                              |  78
code/ZhSh_2_1/c.cpp.tk                              |  98
