Begin
Comparing:  code/azariamuh_1_1/pancake.cpp.tk
code/00/test.cpp.tk                                 |  23
code/01/test.cpp.tk                                 |  23
code/551100kk_0_1/A.cpp.tk                          |  33
code/551100kk_1_1/B.cpp.tk                          |  56
code/551100kk_2_1/C.cpp.tk                          |  92
code/achan1058_0_1/Q-A.cpp.tk                       |  25
code/achan1058_1_1/source.cpp.tk                    |  57
code/achan1058_2_1/source.cpp.tk                    |  99
code/alanubi_0_1/a.cpp.tk                           |  24
code/alanubi_1_1/b.cpp.tk                           |  45
code/alanubi_2_1/c.cpp.tk                           |  109
code/AntiForest_0_1/q1.cpp.tk                       |  69
code/AntiForest_1_1/q2.cpp.tk                       |  30
code/AntiForest_2_1/q3.cpp.tk                       |  148
code/apiad_0_1/A.cpp.tk                             |  38
code/apiad_1_1/B.cpp.tk                             |  63
code/apiad_2_1/C.cpp.tk                             |  104
code/azaky_0_1/A.cpp.tk                             |  55
code/azaky_1_1/B.cpp.tk                             |  76
code/azaky_2_1/C.cpp.tk                             |  138
code/azariamuh_0_1/standing.cpp.tk                  |  68
code/azariamuh_1_1/pancake.cpp.tk                   |  26096
code/azariamuh_2_1/dijkstra.cpp.tk                  |  67
code/bmerry_0_1/a.cpp.tk                            |  77
code/bmerry_1_1/b.cpp.tk                            |  86
code/bmerry_2_1/c.cpp.tk                            |  137
code/climpet_0_1/A.cpp.tk                           |  40
code/climpet_1_1/B.cpp.tk                           |  45
code/climpet_2_1/C.cpp.tk                           |  109
code/ctzsm_0_1/A.cpp.tk                             |  34
code/ctzsm_1_1/B.cpp.tk                             |  61
code/ctzsm_2_1/C.cpp.tk                             |  171
code/DanilC_0_1/problem.cpp.tk                      |  45
code/DanilC_1_1/problemB.cpp.tk                     |  78
code/DanilC_2_1/problemC.cpp.tk                     |  182
code/DEGwer_0_1/A.cpp.tk                            |  47
code/DEGwer_1_1/B.cpp.tk                            |  51
code/DEGwer_2_1/C.cpp.tk                            |  67
code/dmute_0_1/a.cpp.tk                             |  34
code/dmute_1_1/b.cpp.tk                             |  45
code/dmute_2_1/c2.cpp.tk                            |  112
code/fagu_0_1/A.cpp.tk                              |  27
code/fagu_1_1/B.cpp.tk                              |  33
code/fagu_2_1/C.cpp.tk                              |  122
code/FatalEagle_0_1/main.cpp.tk                     |  36
code/FatalEagle_1_1/main.cpp.tk                     |  46
code/FatalEagle_2_1/main.cpp.tk                     |  434
code/fullpower_0_1/A.cpp.tk                         |  51
code/fullpower_1_1/B.cpp.tk                         |  136
code/fullpower_2_1/C.cpp.tk                         |  165
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  15
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  26
code/ICastro_2_1/Dijkstra.cpp.tk                    |  204
code/ilackthatsuperpower_0_1/a.cpp.tk               |  125
code/ilackthatsuperpower_1_1/b.cpp.tk               |  122
code/ilackthatsuperpower_2_1/c.cpp.tk               |  180
code/iridescent_0_1/A.cpp.tk                        |  15
code/iridescent_1_1/B.cpp.tk                        |  29
code/iridescent_2_1/C.cpp.tk                        |  50
code/ishraq_0_1/main.cpp.tk                         |  36
code/ishraq_1_1/main.cpp.tk                         |  59
code/ishraq_2_1/main.cpp.tk                         |  176
code/JayXon_0_1/A.cpp.tk                            |  12
code/JayXon_1_1/B.cpp.tk                            |  47
code/JayXon_2_1/C.cpp.tk                            |  52
code/Josse_0_1/A.cpp.tk                             |  19
code/Josse_1_1/B.cpp.tk                             |  30
code/Josse_2_1/C.cpp.tk                             |  140
code/kcm1700_0_1/a.cpp.tk                           |  23
code/kcm1700_1_1/b.cpp.tk                           |  44
code/kcm1700_2_1/c.cpp.tk                           |  158
code/kevinsogo_0_1/a.cpp.tk                         |  37
code/kevinsogo_1_1/b.cpp.tk                         |  41
code/kevinsogo_2_1/c.cpp.tk                         |  304
code/ksun48_0_1/A.cpp.tk                            |  5
code/ksun48_1_1/B.cpp.tk                            |  5
code/ksun48_2_1/C.cpp.tk                            |  22
code/LazyAnna_0_1/1.cpp.tk                          |  18
code/LazyAnna_1_1/2-1.cpp.tk                        |  27
code/LazyAnna_2_1/3.cpp.tk                          |  70
code/Merkurev_0_1/A.cpp.tk                          |  39
code/Merkurev_1_1/B.cpp.tk                          |  71
code/Merkurev_2_1/C.cpp.tk                          |  100
code/mezei_0_1/main.cpp.tk                          |  44
code/mezei_1_1/main.cpp.tk                          |  37
code/mezei_2_1/main.cpp.tk                          |  106
code/Mister_0_1/a.cpp.tk                            |  25
code/Mister_1_1/b.cpp.tk                            |  40
code/Mister_2_1/c.cpp.tk                            |  78
code/namonakiacc_0_1/cpp.cpp.tk                     |  66
code/namonakiacc_1_1/cpp.cpp.tk                     |  107
code/namonakiacc_2_1/cpp.cpp.tk                     |  196
code/Nicolas16_0_1/main.cpp.tk                      |  16
code/Nicolas16_1_1/main.cpp.tk                      |  15
code/Nicolas16_2_1/main.cpp.tk                      |  115
code/pandamonium_0_1/a.cpp.tk                       |  36
code/pandamonium_1_1/b.cpp.tk                       |  115
code/pandamonium_2_1/c.cpp.tk                       |  74
code/pflueger_0_1/A.cpp.tk                          |  15
code/pflueger_1_1/B.cpp.tk                          |  27
code/pflueger_2_1/C.cpp.tk                          |  98
code/ponyopoppo_0_1/A.cpp.tk                        |  26
code/ponyopoppo_1_1/B.cpp.tk                        |  43
code/ponyopoppo_2_1/C.cpp.tk                        |  198
code/Ragnar_0_1/A.cpp.tk                            |  26
code/Ragnar_1_1/B-2.cpp.tk                          |  41
code/Ragnar_2_1/C.cpp.tk                            |  59
code/saffah_0_1/t.cpp.tk                            |  38
code/saffah_1_1/t.cpp.tk                            |  72
code/saffah_2_1/t.cpp.tk                            |  171
code/SamanSami_0_1/A.cpp.tk                         |  5
code/SamanSami_1_1/B.cpp.tk                         |  27
code/SamanSami_2_1/C.cpp.tk                         |  17
code/Savlik_0_1/code.cpp.tk                         |  17
code/Savlik_1_1/code.cpp.tk                         |  33
code/Savlik_2_1/code.cpp.tk                         |  100
code/shik_0_1/pa.cpp.tk                             |  107
code/shik_1_1/pb.cpp.tk                             |  104
code/shik_2_1/pc.cpp.tk                             |  200
code/simsa.st_0_1/A.cpp.tk                          |  48
code/simsa.st_1_1/B.cpp.tk                          |  55
code/simsa.st_2_1/C.cpp.tk                          |  143
code/SovietUnion_0_1/A.cpp.tk                       |  37
code/SovietUnion_1_1/B.cpp.tk                       |  49
code/SovietUnion_2_1/C.cpp.tk                       |  113
code/tailed_0_1/A.cpp.tk                            |  17
code/tailed_1_1/B.cpp.tk                            |  30
code/tailed_2_1/C.cpp.tk                            |  65
code/TheNatural_0_1/A.cpp.tk                        |  20
code/TheNatural_1_1/B.cpp.tk                        |  26
code/TheNatural_2_1/C.cpp.tk                        |  40
code/TrueBamboo_0_1/test.cpp.tk                     |  27
code/TrueBamboo_1_1/test.cpp.tk                     |  40
code/TrueBamboo_2_1/test.cpp.tk                     |  73
code/tur.turczyn_0_1/A.cpp.tk                       |  19
code/tur.turczyn_1_1/B.cpp.tk                       |  42
code/tur.turczyn_2_1/C.cpp.tk                       |  44
code/Tyg3R_0_1/A.cpp.tk                             |  31
code/Tyg3R_1_1/B.cpp.tk                             |  79
code/Tyg3R_2_1/C.cpp.tk                             |  80
code/UminchuR_0_1/main.cpp.tk                       |  38
code/UminchuR_1_1/main.cpp.tk                       |  65
code/UminchuR_2_1/main.cpp.tk                       |  154
code/wo..._0_1/a.cpp.tk                             |  37
code/wo..._1_1/b.cpp.tk                             |  38
code/wo..._2_1/c.cpp.tk                             |  128
code/yswtt_0_1/A.cpp.tk                             |  11
code/yswtt_1_1/B.cpp.tk                             |  31
code/yswtt_2_1/C.cpp.tk                             |  53
code/ZhSh_0_1/a.cpp.tk                              |  14
code/ZhSh_1_1/b.cpp.tk                              |  96
code/ZhSh_2_1/c.cpp.tk                              |  157
