Begin
Comparing:  code/achan1058_0_1/Q-A.cpp.tk
code/00/test.cpp.tk                                 |  20
code/01/test.cpp.tk                                 |  20
code/551100kk_0_1/A.cpp.tk                          |  33
code/551100kk_1_1/B.cpp.tk                          |  35
code/551100kk_2_1/C.cpp.tk                          |  74
code/achan1058_0_1/Q-A.cpp.tk                       |  3051
code/achan1058_1_1/source.cpp.tk                    |  105
code/achan1058_2_1/source.cpp.tk                    |  138
code/alanubi_0_1/a.cpp.tk                           |  24
code/alanubi_1_1/b.cpp.tk                           |  28
code/alanubi_2_1/c.cpp.tk                           |  127
code/AntiForest_0_1/q1.cpp.tk                       |  62
code/AntiForest_1_1/q2.cpp.tk                       |  19
code/AntiForest_2_1/q3.cpp.tk                       |  116
code/apiad_0_1/A.cpp.tk                             |  79
code/apiad_1_1/B.cpp.tk                             |  46
code/apiad_2_1/C.cpp.tk                             |  53
code/azaky_0_1/A.cpp.tk                             |  49
code/azaky_1_1/B.cpp.tk                             |  47
code/azaky_2_1/C.cpp.tk                             |  106
code/azariamuh_0_1/standing.cpp.tk                  |  40
code/azariamuh_1_1/pancake.cpp.tk                   |  71
code/azariamuh_2_1/dijkstra.cpp.tk                  |  43
code/bmerry_0_1/a.cpp.tk                            |  77
code/bmerry_1_1/b.cpp.tk                            |  89
code/bmerry_2_1/c.cpp.tk                            |  94
code/climpet_0_1/A.cpp.tk                           |  51
code/climpet_1_1/B.cpp.tk                           |  59
code/climpet_2_1/C.cpp.tk                           |  90
code/ctzsm_0_1/A.cpp.tk                             |  32
code/ctzsm_1_1/B.cpp.tk                             |  30
code/ctzsm_2_1/C.cpp.tk                             |  124
code/DanilC_0_1/problem.cpp.tk                      |  63
code/DanilC_1_1/problemB.cpp.tk                     |  80
code/DanilC_2_1/problemC.cpp.tk                     |  174
code/DEGwer_0_1/A.cpp.tk                            |  34
code/DEGwer_1_1/B.cpp.tk                            |  35
code/DEGwer_2_1/C.cpp.tk                            |  55
code/dmute_0_1/a.cpp.tk                             |  25
code/dmute_1_1/b.cpp.tk                             |  27
code/dmute_2_1/c2.cpp.tk                            |  74
code/fagu_0_1/A.cpp.tk                              |  14
code/fagu_1_1/B.cpp.tk                              |  14
code/fagu_2_1/C.cpp.tk                              |  71
code/FatalEagle_0_1/main.cpp.tk                     |  33
code/FatalEagle_1_1/main.cpp.tk                     |  34
code/FatalEagle_2_1/main.cpp.tk                     |  189
code/fullpower_0_1/A.cpp.tk                         |  34
code/fullpower_1_1/B.cpp.tk                         |  43
code/fullpower_2_1/C.cpp.tk                         |  104
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  22
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  34
code/ICastro_2_1/Dijkstra.cpp.tk                    |  201
code/ilackthatsuperpower_0_1/a.cpp.tk               |  139
code/ilackthatsuperpower_1_1/b.cpp.tk               |  140
code/ilackthatsuperpower_2_1/c.cpp.tk               |  194
code/iridescent_0_1/A.cpp.tk                        |  31
code/iridescent_1_1/B.cpp.tk                        |  32
code/iridescent_2_1/C.cpp.tk                        |  39
code/ishraq_0_1/main.cpp.tk                         |  83
code/ishraq_1_1/main.cpp.tk                         |  39
code/ishraq_2_1/main.cpp.tk                         |  151
code/JayXon_0_1/A.cpp.tk                            |  18
code/JayXon_1_1/B.cpp.tk                            |  34
code/JayXon_2_1/C.cpp.tk                            |  59
code/Josse_0_1/A.cpp.tk                             |  32
code/Josse_1_1/B.cpp.tk                             |  40
code/Josse_2_1/C.cpp.tk                             |  119
code/kcm1700_0_1/a.cpp.tk                           |  18
code/kcm1700_1_1/b.cpp.tk                           |  25
code/kcm1700_2_1/c.cpp.tk                           |  82
code/kevinsogo_0_1/a.cpp.tk                         |  24
code/kevinsogo_1_1/b.cpp.tk                         |  28
code/kevinsogo_2_1/c.cpp.tk                         |  96
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  26
code/LazyAnna_0_1/1.cpp.tk                          |  20
code/LazyAnna_1_1/2-1.cpp.tk                        |  32
code/LazyAnna_2_1/3.cpp.tk                          |  62
code/Merkurev_0_1/A.cpp.tk                          |  26
code/Merkurev_1_1/B.cpp.tk                          |  48
code/Merkurev_2_1/C.cpp.tk                          |  50
code/mezei_0_1/main.cpp.tk                          |  29
code/mezei_1_1/main.cpp.tk                          |  24
code/mezei_2_1/main.cpp.tk                          |  94
code/Mister_0_1/a.cpp.tk                            |  23
code/Mister_1_1/b.cpp.tk                            |  22
code/Mister_2_1/c.cpp.tk                            |  51
code/namonakiacc_0_1/cpp.cpp.tk                     |  53
code/namonakiacc_1_1/cpp.cpp.tk                     |  58
code/namonakiacc_2_1/cpp.cpp.tk                     |  106
code/Nicolas16_0_1/main.cpp.tk                      |  14
code/Nicolas16_1_1/main.cpp.tk                      |  10
code/Nicolas16_2_1/main.cpp.tk                      |  87
code/pandamonium_0_1/a.cpp.tk                       |  26
code/pandamonium_1_1/b.cpp.tk                       |  50
code/pandamonium_2_1/c.cpp.tk                       |  37
code/pflueger_0_1/A.cpp.tk                          |  28
code/pflueger_1_1/B.cpp.tk                          |  36
code/pflueger_2_1/C.cpp.tk                          |  85
code/ponyopoppo_0_1/A.cpp.tk                        |  35
code/ponyopoppo_1_1/B.cpp.tk                        |  58
code/ponyopoppo_2_1/C.cpp.tk                        |  192
code/Ragnar_0_1/A.cpp.tk                            |  46
code/Ragnar_1_1/B-2.cpp.tk                          |  48
code/Ragnar_2_1/C.cpp.tk                            |  73
code/saffah_0_1/t.cpp.tk                            |  56
code/saffah_1_1/t.cpp.tk                            |  45
code/saffah_2_1/t.cpp.tk                            |  149
code/SamanSami_0_1/A.cpp.tk                         |  10
code/SamanSami_1_1/B.cpp.tk                         |  34
code/SamanSami_2_1/C.cpp.tk                         |  17
code/Savlik_0_1/code.cpp.tk                         |  23
code/Savlik_1_1/code.cpp.tk                         |  22
code/Savlik_2_1/code.cpp.tk                         |  105
code/shik_0_1/pa.cpp.tk                             |  117
code/shik_1_1/pb.cpp.tk                             |  96
code/shik_2_1/pc.cpp.tk                             |  165
code/simsa.st_0_1/A.cpp.tk                          |  29
code/simsa.st_1_1/B.cpp.tk                          |  39
code/simsa.st_2_1/C.cpp.tk                          |  117
code/SovietUnion_0_1/A.cpp.tk                       |  34
code/SovietUnion_1_1/B.cpp.tk                       |  36
code/SovietUnion_2_1/C.cpp.tk                       |  116
code/tailed_0_1/A.cpp.tk                            |  26
code/tailed_1_1/B.cpp.tk                            |  33
code/tailed_2_1/C.cpp.tk                            |  79
code/TheNatural_0_1/A.cpp.tk                        |  30
code/TheNatural_1_1/B.cpp.tk                        |  34
code/TheNatural_2_1/C.cpp.tk                        |  43
code/TrueBamboo_0_1/test.cpp.tk                     |  35
code/TrueBamboo_1_1/test.cpp.tk                     |  46
code/TrueBamboo_2_1/test.cpp.tk                     |  84
code/tur.turczyn_0_1/A.cpp.tk                       |  36
code/tur.turczyn_1_1/B.cpp.tk                       |  50
code/tur.turczyn_2_1/C.cpp.tk                       |  64
code/Tyg3R_0_1/A.cpp.tk                             |  46
code/Tyg3R_1_1/B.cpp.tk                             |  55
code/Tyg3R_2_1/C.cpp.tk                             |  69
code/UminchuR_0_1/main.cpp.tk                       |  56
code/UminchuR_1_1/main.cpp.tk                       |  57
code/UminchuR_2_1/main.cpp.tk                       |  94
code/wo..._0_1/a.cpp.tk                             |  25
code/wo..._1_1/b.cpp.tk                             |  29
code/wo..._2_1/c.cpp.tk                             |  89
code/yswtt_0_1/A.cpp.tk                             |  40
code/yswtt_1_1/B.cpp.tk                             |  34
code/yswtt_2_1/C.cpp.tk                             |  71
code/ZhSh_0_1/a.cpp.tk                              |  32
code/ZhSh_1_1/b.cpp.tk                              |  102
code/ZhSh_2_1/c.cpp.tk                              |  131
