Begin
Comparing:  code/AntiForest_1_1/q2.cpp.tk
code/00/test.cpp.tk                                 |  15
code/01/test.cpp.tk                                 |  15
code/551100kk_0_1/A.cpp.tk                          |  182
code/551100kk_1_1/B.cpp.tk                          |  205
code/551100kk_2_1/C.cpp.tk                          |  174
code/achan1058_0_1/Q-A.cpp.tk                       |  24
code/achan1058_1_1/source.cpp.tk                    |  70
code/achan1058_2_1/source.cpp.tk                    |  111
code/alanubi_0_1/a.cpp.tk                           |  36
code/alanubi_1_1/b.cpp.tk                           |  53
code/alanubi_2_1/c.cpp.tk                           |  122
code/AntiForest_0_1/q1.cpp.tk                       |  601
code/AntiForest_1_1/q2.cpp.tk                       |  1736
code/AntiForest_2_1/q3.cpp.tk                       |  583
code/apiad_0_1/A.cpp.tk                             |  55
code/apiad_1_1/B.cpp.tk                             |  93
code/apiad_2_1/C.cpp.tk                             |  79
code/azaky_0_1/A.cpp.tk                             |  112
code/azaky_1_1/B.cpp.tk                             |  119
code/azaky_2_1/C.cpp.tk                             |  191
code/azariamuh_0_1/standing.cpp.tk                  |  79
code/azariamuh_1_1/pancake.cpp.tk                   |  109
code/azariamuh_2_1/dijkstra.cpp.tk                  |  91
code/bmerry_0_1/a.cpp.tk                            |  98
code/bmerry_1_1/b.cpp.tk                            |  110
code/bmerry_2_1/c.cpp.tk                            |  111
code/climpet_0_1/A.cpp.tk                           |  54
code/climpet_1_1/B.cpp.tk                           |  62
code/climpet_2_1/C.cpp.tk                           |  85
code/ctzsm_0_1/A.cpp.tk                             |  234
code/ctzsm_1_1/B.cpp.tk                             |  259
code/ctzsm_2_1/C.cpp.tk                             |  335
code/DanilC_0_1/problem.cpp.tk                      |  45
code/DanilC_1_1/problemB.cpp.tk                     |  66
code/DanilC_2_1/problemC.cpp.tk                     |  175
code/DEGwer_0_1/A.cpp.tk                            |  57
code/DEGwer_1_1/B.cpp.tk                            |  58
code/DEGwer_2_1/C.cpp.tk                            |  68
code/dmute_0_1/a.cpp.tk                             |  43
code/dmute_1_1/b.cpp.tk                             |  42
code/dmute_2_1/c2.cpp.tk                            |  89
code/fagu_0_1/A.cpp.tk                              |  53
code/fagu_1_1/B.cpp.tk                              |  53
code/fagu_2_1/C.cpp.tk                              |  102
code/FatalEagle_0_1/main.cpp.tk                     |  130
code/FatalEagle_1_1/main.cpp.tk                     |  130
code/FatalEagle_2_1/main.cpp.tk                     |  282
code/fullpower_0_1/A.cpp.tk                         |  251
code/fullpower_1_1/B.cpp.tk                         |  181
code/fullpower_2_1/C.cpp.tk                         |  215
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  15
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  24
code/ICastro_2_1/Dijkstra.cpp.tk                    |  288
code/ilackthatsuperpower_0_1/a.cpp.tk               |  143
code/ilackthatsuperpower_1_1/b.cpp.tk               |  148
code/ilackthatsuperpower_2_1/c.cpp.tk               |  201
code/iridescent_0_1/A.cpp.tk                        |  12
code/iridescent_1_1/B.cpp.tk                        |  20
code/iridescent_2_1/C.cpp.tk                        |  27
code/ishraq_0_1/main.cpp.tk                         |  55
code/ishraq_1_1/main.cpp.tk                         |  68
code/ishraq_2_1/main.cpp.tk                         |  176
code/JayXon_0_1/A.cpp.tk                            |  10
code/JayXon_1_1/B.cpp.tk                            |  27
code/JayXon_2_1/C.cpp.tk                            |  55
code/Josse_0_1/A.cpp.tk                             |  17
code/Josse_1_1/B.cpp.tk                             |  26
code/Josse_2_1/C.cpp.tk                             |  130
code/kcm1700_0_1/a.cpp.tk                           |  46
code/kcm1700_1_1/b.cpp.tk                           |  51
code/kcm1700_2_1/c.cpp.tk                           |  110
code/kevinsogo_0_1/a.cpp.tk                         |  53
code/kevinsogo_1_1/b.cpp.tk                         |  52
code/kevinsogo_2_1/c.cpp.tk                         |  135
code/ksun48_0_1/A.cpp.tk                            |  21
code/ksun48_1_1/B.cpp.tk                            |  21
code/ksun48_2_1/C.cpp.tk                            |  35
code/LazyAnna_0_1/1.cpp.tk                          |  13
code/LazyAnna_1_1/2-1.cpp.tk                        |  19
code/LazyAnna_2_1/3.cpp.tk                          |  53
code/Merkurev_0_1/A.cpp.tk                          |  132
code/Merkurev_1_1/B.cpp.tk                          |  157
code/Merkurev_2_1/C.cpp.tk                          |  154
code/mezei_0_1/main.cpp.tk                          |  48
code/mezei_1_1/main.cpp.tk                          |  36
code/mezei_2_1/main.cpp.tk                          |  127
code/Mister_0_1/a.cpp.tk                            |  40
code/Mister_1_1/b.cpp.tk                            |  49
code/Mister_2_1/c.cpp.tk                            |  64
code/namonakiacc_0_1/cpp.cpp.tk                     |  119
code/namonakiacc_1_1/cpp.cpp.tk                     |  129
code/namonakiacc_2_1/cpp.cpp.tk                     |  176
code/Nicolas16_0_1/main.cpp.tk                      |  32
code/Nicolas16_1_1/main.cpp.tk                      |  31
code/Nicolas16_2_1/main.cpp.tk                      |  120
code/pandamonium_0_1/a.cpp.tk                       |  45
code/pandamonium_1_1/b.cpp.tk                       |  81
code/pandamonium_2_1/c.cpp.tk                       |  58
code/pflueger_0_1/A.cpp.tk                          |  13
code/pflueger_1_1/B.cpp.tk                          |  23
code/pflueger_2_1/C.cpp.tk                          |  70
code/ponyopoppo_0_1/A.cpp.tk                        |  20
code/ponyopoppo_1_1/B.cpp.tk                        |  40
code/ponyopoppo_2_1/C.cpp.tk                        |  225
code/Ragnar_0_1/A.cpp.tk                            |  36
code/Ragnar_1_1/B-2.cpp.tk                          |  50
code/Ragnar_2_1/C.cpp.tk                            |  74
code/saffah_0_1/t.cpp.tk                            |  74
code/saffah_1_1/t.cpp.tk                            |  112
code/saffah_2_1/t.cpp.tk                            |  249
code/SamanSami_0_1/A.cpp.tk                         |  8
code/SamanSami_1_1/B.cpp.tk                         |  19
code/SamanSami_2_1/C.cpp.tk                         |  23
code/Savlik_0_1/code.cpp.tk                         |  19
code/Savlik_1_1/code.cpp.tk                         |  34
code/Savlik_2_1/code.cpp.tk                         |  105
code/shik_0_1/pa.cpp.tk                             |  144
code/shik_1_1/pb.cpp.tk                             |  143
code/shik_2_1/pc.cpp.tk                             |  197
code/simsa.st_0_1/A.cpp.tk                          |  71
code/simsa.st_1_1/B.cpp.tk                          |  96
code/simsa.st_2_1/C.cpp.tk                          |  219
code/SovietUnion_0_1/A.cpp.tk                       |  278
code/SovietUnion_1_1/B.cpp.tk                       |  286
code/SovietUnion_2_1/C.cpp.tk                       |  219
code/tailed_0_1/A.cpp.tk                            |  13
code/tailed_1_1/B.cpp.tk                            |  19
code/tailed_2_1/C.cpp.tk                            |  55
code/TheNatural_0_1/A.cpp.tk                        |  19
code/TheNatural_1_1/B.cpp.tk                        |  21
code/TheNatural_2_1/C.cpp.tk                        |  33
code/TrueBamboo_0_1/test.cpp.tk                     |  48
code/TrueBamboo_1_1/test.cpp.tk                     |  57
code/TrueBamboo_2_1/test.cpp.tk                     |  109
code/tur.turczyn_0_1/A.cpp.tk                       |  35
code/tur.turczyn_1_1/B.cpp.tk                       |  54
code/tur.turczyn_2_1/C.cpp.tk                       |  53
code/Tyg3R_0_1/A.cpp.tk                             |  32
code/Tyg3R_1_1/B.cpp.tk                             |  70
code/Tyg3R_2_1/C.cpp.tk                             |  55
code/UminchuR_0_1/main.cpp.tk                       |  145
code/UminchuR_1_1/main.cpp.tk                       |  183
code/UminchuR_2_1/main.cpp.tk                       |  205
code/wo..._0_1/a.cpp.tk                             |  53
code/wo..._1_1/b.cpp.tk                             |  46
code/wo..._2_1/c.cpp.tk                             |  106
code/yswtt_0_1/A.cpp.tk                             |  10
code/yswtt_1_1/B.cpp.tk                             |  25
code/yswtt_2_1/C.cpp.tk                             |  50
code/ZhSh_0_1/a.cpp.tk                              |  12
code/ZhSh_1_1/b.cpp.tk                              |  89
code/ZhSh_2_1/c.cpp.tk                              |  124
