Begin
Comparing:  code/fullpower_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  39
code/551100kk_1_1/B.cpp.tk                          |  51
code/551100kk_2_1/C.cpp.tk                          |  55
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  17
code/achan1058_2_1/source.cpp.tk                    |  41
code/alanubi_0_1/a.cpp.tk                           |  45
code/alanubi_1_1/b.cpp.tk                           |  48
code/alanubi_2_1/c.cpp.tk                           |  97
code/AntiForest_0_1/q1.cpp.tk                       |  57
code/AntiForest_1_1/q2.cpp.tk                       |  43
code/AntiForest_2_1/q3.cpp.tk                       |  91
code/apiad_0_1/A.cpp.tk                             |  17
code/apiad_1_1/B.cpp.tk                             |  25
code/apiad_2_1/C.cpp.tk                             |  34
code/azaky_0_1/A.cpp.tk                             |  24
code/azaky_1_1/B.cpp.tk                             |  27
code/azaky_2_1/C.cpp.tk                             |  55
code/azariamuh_0_1/standing.cpp.tk                  |  16
code/azariamuh_1_1/pancake.cpp.tk                   |  29
code/azariamuh_2_1/dijkstra.cpp.tk                  |  21
code/bmerry_0_1/a.cpp.tk                            |  55
code/bmerry_1_1/b.cpp.tk                            |  62
code/bmerry_2_1/c.cpp.tk                            |  54
code/climpet_0_1/A.cpp.tk                           |  37
code/climpet_1_1/B.cpp.tk                           |  42
code/climpet_2_1/C.cpp.tk                           |  59
code/ctzsm_0_1/A.cpp.tk                             |  124
code/ctzsm_1_1/B.cpp.tk                             |  134
code/ctzsm_2_1/C.cpp.tk                             |  182
code/DanilC_0_1/problem.cpp.tk                      |  44
code/DanilC_1_1/problemB.cpp.tk                     |  57
code/DanilC_2_1/problemC.cpp.tk                     |  103
code/DEGwer_0_1/A.cpp.tk                            |  59
code/DEGwer_1_1/B.cpp.tk                            |  43
code/DEGwer_2_1/C.cpp.tk                            |  38
code/dmute_0_1/a.cpp.tk                             |  87
code/dmute_1_1/b.cpp.tk                             |  126
code/dmute_2_1/c2.cpp.tk                            |  136
code/fagu_0_1/A.cpp.tk                              |  18
code/fagu_1_1/B.cpp.tk                              |  18
code/fagu_2_1/C.cpp.tk                              |  43
code/FatalEagle_0_1/main.cpp.tk                     |  106
code/FatalEagle_1_1/main.cpp.tk                     |  128
code/FatalEagle_2_1/main.cpp.tk                     |  243
code/fullpower_0_1/A.cpp.tk                         |  17843
code/fullpower_1_1/B.cpp.tk                         |  207
code/fullpower_2_1/C.cpp.tk                         |  264
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  20
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  32
code/ICastro_2_1/Dijkstra.cpp.tk                    |  102
code/ilackthatsuperpower_0_1/a.cpp.tk               |  130
code/ilackthatsuperpower_1_1/b.cpp.tk               |  92
code/ilackthatsuperpower_2_1/c.cpp.tk               |  94
code/iridescent_0_1/A.cpp.tk                        |  31
code/iridescent_1_1/B.cpp.tk                        |  75
code/iridescent_2_1/C.cpp.tk                        |  45
code/ishraq_0_1/main.cpp.tk                         |  14
code/ishraq_1_1/main.cpp.tk                         |  22
code/ishraq_2_1/main.cpp.tk                         |  61
code/JayXon_0_1/A.cpp.tk                            |  30
code/JayXon_1_1/B.cpp.tk                            |  49
code/JayXon_2_1/C.cpp.tk                            |  28
code/Josse_0_1/A.cpp.tk                             |  20
code/Josse_1_1/B.cpp.tk                             |  34
code/Josse_2_1/C.cpp.tk                             |  90
code/kcm1700_0_1/a.cpp.tk                           |  73
code/kcm1700_1_1/b.cpp.tk                           |  93
code/kcm1700_2_1/c.cpp.tk                           |  94
code/kevinsogo_0_1/a.cpp.tk                         |  15
code/kevinsogo_1_1/b.cpp.tk                         |  20
code/kevinsogo_2_1/c.cpp.tk                         |  61
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  14
code/LazyAnna_0_1/1.cpp.tk                          |  25
code/LazyAnna_1_1/2-1.cpp.tk                        |  33
code/LazyAnna_2_1/3.cpp.tk                          |  33
code/Merkurev_0_1/A.cpp.tk                          |  235
code/Merkurev_1_1/B.cpp.tk                          |  121
code/Merkurev_2_1/C.cpp.tk                          |  146
code/mezei_0_1/main.cpp.tk                          |  108
code/mezei_1_1/main.cpp.tk                          |  63
code/mezei_2_1/main.cpp.tk                          |  104
code/Mister_0_1/a.cpp.tk                            |  41
code/Mister_1_1/b.cpp.tk                            |  55
code/Mister_2_1/c.cpp.tk                            |  62
code/namonakiacc_0_1/cpp.cpp.tk                     |  24
code/namonakiacc_1_1/cpp.cpp.tk                     |  26
code/namonakiacc_2_1/cpp.cpp.tk                     |  51
code/Nicolas16_0_1/main.cpp.tk                      |  50
code/Nicolas16_1_1/main.cpp.tk                      |  50
code/Nicolas16_2_1/main.cpp.tk                      |  159
code/pandamonium_0_1/a.cpp.tk                       |  88
code/pandamonium_1_1/b.cpp.tk                       |  98
code/pandamonium_2_1/c.cpp.tk                       |  89
code/pflueger_0_1/A.cpp.tk                          |  48
code/pflueger_1_1/B.cpp.tk                          |  49
code/pflueger_2_1/C.cpp.tk                          |  82
code/ponyopoppo_0_1/A.cpp.tk                        |  14
code/ponyopoppo_1_1/B.cpp.tk                        |  19
code/ponyopoppo_2_1/C.cpp.tk                        |  95
code/Ragnar_0_1/A.cpp.tk                            |  10
code/Ragnar_1_1/B-2.cpp.tk                          |  21
code/Ragnar_2_1/C.cpp.tk                            |  49
code/saffah_0_1/t.cpp.tk                            |  12
code/saffah_1_1/t.cpp.tk                            |  17
code/saffah_2_1/t.cpp.tk                            |  67
code/SamanSami_0_1/A.cpp.tk                         |  22
code/SamanSami_1_1/B.cpp.tk                         |  45
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  27
code/Savlik_1_1/code.cpp.tk                         |  13
code/Savlik_2_1/code.cpp.tk                         |  50
code/shik_0_1/pa.cpp.tk                             |  44
code/shik_1_1/pb.cpp.tk                             |  49
code/shik_2_1/pc.cpp.tk                             |  76
code/simsa.st_0_1/A.cpp.tk                          |  17
code/simsa.st_1_1/B.cpp.tk                          |  20
code/simsa.st_2_1/C.cpp.tk                          |  69
code/SovietUnion_0_1/A.cpp.tk                       |  120
code/SovietUnion_1_1/B.cpp.tk                       |  127
code/SovietUnion_2_1/C.cpp.tk                       |  75
code/tailed_0_1/A.cpp.tk                            |  30
code/tailed_1_1/B.cpp.tk                            |  39
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  71
code/TheNatural_1_1/B.cpp.tk                        |  58
code/TheNatural_2_1/C.cpp.tk                        |  39
code/TrueBamboo_0_1/test.cpp.tk                     |  44
code/TrueBamboo_1_1/test.cpp.tk                     |  35
code/TrueBamboo_2_1/test.cpp.tk                     |  53
code/tur.turczyn_0_1/A.cpp.tk                       |  10
code/tur.turczyn_1_1/B.cpp.tk                       |  17
code/tur.turczyn_2_1/C.cpp.tk                       |  20
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  15
code/Tyg3R_2_1/C.cpp.tk                             |  17
code/UminchuR_0_1/main.cpp.tk                       |  38
code/UminchuR_1_1/main.cpp.tk                       |  49
code/UminchuR_2_1/main.cpp.tk                       |  67
code/wo..._0_1/a.cpp.tk                             |  96
code/wo..._1_1/b.cpp.tk                             |  103
code/wo..._2_1/c.cpp.tk                             |  132
code/yswtt_0_1/A.cpp.tk                             |  22
code/yswtt_1_1/B.cpp.tk                             |  34
code/yswtt_2_1/C.cpp.tk                             |  39
code/ZhSh_0_1/a.cpp.tk                              |  25
code/ZhSh_1_1/b.cpp.tk                              |  69
code/ZhSh_2_1/c.cpp.tk                              |  67
