Begin
Comparing:  code/iridescent_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  19
code/551100kk_1_1/B.cpp.tk                          |  25
code/551100kk_2_1/C.cpp.tk                          |  43
code/achan1058_0_1/Q-A.cpp.tk                       |  17
code/achan1058_1_1/source.cpp.tk                    |  20
code/achan1058_2_1/source.cpp.tk                    |  32
code/alanubi_0_1/a.cpp.tk                           |  44
code/alanubi_1_1/b.cpp.tk                           |  39
code/alanubi_2_1/c.cpp.tk                           |  104
code/AntiForest_0_1/q1.cpp.tk                       |  10
code/AntiForest_1_1/q2.cpp.tk                       |  3
code/AntiForest_2_1/q3.cpp.tk                       |  38
code/apiad_0_1/A.cpp.tk                             |  17
code/apiad_1_1/B.cpp.tk                             |  13
code/apiad_2_1/C.cpp.tk                             |  24
code/azaky_0_1/A.cpp.tk                             |  11
code/azaky_1_1/B.cpp.tk                             |  13
code/azaky_2_1/C.cpp.tk                             |  33
code/azariamuh_0_1/standing.cpp.tk                  |  12
code/azariamuh_1_1/pancake.cpp.tk                   |  15
code/azariamuh_2_1/dijkstra.cpp.tk                  |  14
code/bmerry_0_1/a.cpp.tk                            |  93
code/bmerry_1_1/b.cpp.tk                            |  71
code/bmerry_2_1/c.cpp.tk                            |  70
code/climpet_0_1/A.cpp.tk                           |  60
code/climpet_1_1/B.cpp.tk                           |  53
code/climpet_2_1/C.cpp.tk                           |  77
code/ctzsm_0_1/A.cpp.tk                             |  38
code/ctzsm_1_1/B.cpp.tk                             |  34
code/ctzsm_2_1/C.cpp.tk                             |  73
code/DanilC_0_1/problem.cpp.tk                      |  51
code/DanilC_1_1/problemB.cpp.tk                     |  67
code/DanilC_2_1/problemC.cpp.tk                     |  77
code/DEGwer_0_1/A.cpp.tk                            |  53
code/DEGwer_1_1/B.cpp.tk                            |  80
code/DEGwer_2_1/C.cpp.tk                            |  34
code/dmute_0_1/a.cpp.tk                             |  54
code/dmute_1_1/b.cpp.tk                             |  77
code/dmute_2_1/c2.cpp.tk                            |  93
code/fagu_0_1/A.cpp.tk                              |  12
code/fagu_1_1/B.cpp.tk                              |  12
code/fagu_2_1/C.cpp.tk                              |  26
code/FatalEagle_0_1/main.cpp.tk                     |  58
code/FatalEagle_1_1/main.cpp.tk                     |  85
code/FatalEagle_2_1/main.cpp.tk                     |  187
code/fullpower_0_1/A.cpp.tk                         |  63
code/fullpower_1_1/B.cpp.tk                         |  118
code/fullpower_2_1/C.cpp.tk                         |  147
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  52
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  59
code/ICastro_2_1/Dijkstra.cpp.tk                    |  71
code/ilackthatsuperpower_0_1/a.cpp.tk               |  87
code/ilackthatsuperpower_1_1/b.cpp.tk               |  91
code/ilackthatsuperpower_2_1/c.cpp.tk               |  82
code/iridescent_0_1/A.cpp.tk                        |  4058
code/iridescent_1_1/B.cpp.tk                        |  165
code/iridescent_2_1/C.cpp.tk                        |  154
code/ishraq_0_1/main.cpp.tk                         |  16
code/ishraq_1_1/main.cpp.tk                         |  25
code/ishraq_2_1/main.cpp.tk                         |  34
code/JayXon_0_1/A.cpp.tk                            |  28
code/JayXon_1_1/B.cpp.tk                            |  49
code/JayXon_2_1/C.cpp.tk                            |  28
code/Josse_0_1/A.cpp.tk                             |  45
code/Josse_1_1/B.cpp.tk                             |  59
code/Josse_2_1/C.cpp.tk                             |  86
code/kcm1700_0_1/a.cpp.tk                           |  60
code/kcm1700_1_1/b.cpp.tk                           |  75
code/kcm1700_2_1/c.cpp.tk                           |  85
code/kevinsogo_0_1/a.cpp.tk                         |  9
code/kevinsogo_1_1/b.cpp.tk                         |  13
code/kevinsogo_2_1/c.cpp.tk                         |  38
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  8
code/LazyAnna_0_1/1.cpp.tk                          |  40
code/LazyAnna_1_1/2-1.cpp.tk                        |  55
code/LazyAnna_2_1/3.cpp.tk                          |  34
code/Merkurev_0_1/A.cpp.tk                          |  68
code/Merkurev_1_1/B.cpp.tk                          |  60
code/Merkurev_2_1/C.cpp.tk                          |  79
code/mezei_0_1/main.cpp.tk                          |  76
code/mezei_1_1/main.cpp.tk                          |  63
code/mezei_2_1/main.cpp.tk                          |  86
code/Mister_0_1/a.cpp.tk                            |  25
code/Mister_1_1/b.cpp.tk                            |  35
code/Mister_2_1/c.cpp.tk                            |  48
code/namonakiacc_0_1/cpp.cpp.tk                     |  29
code/namonakiacc_1_1/cpp.cpp.tk                     |  19
code/namonakiacc_2_1/cpp.cpp.tk                     |  36
code/Nicolas16_0_1/main.cpp.tk                      |  25
code/Nicolas16_1_1/main.cpp.tk                      |  25
code/Nicolas16_2_1/main.cpp.tk                      |  111
code/pandamonium_0_1/a.cpp.tk                       |  61
code/pandamonium_1_1/b.cpp.tk                       |  66
code/pandamonium_2_1/c.cpp.tk                       |  62
code/pflueger_0_1/A.cpp.tk                          |  169
code/pflueger_1_1/B.cpp.tk                          |  126
code/pflueger_2_1/C.cpp.tk                          |  108
code/ponyopoppo_0_1/A.cpp.tk                        |  27
code/ponyopoppo_1_1/B.cpp.tk                        |  21
code/ponyopoppo_2_1/C.cpp.tk                        |  61
code/Ragnar_0_1/A.cpp.tk                            |  20
code/Ragnar_1_1/B-2.cpp.tk                          |  28
code/Ragnar_2_1/C.cpp.tk                            |  99
code/saffah_0_1/t.cpp.tk                            |  13
code/saffah_1_1/t.cpp.tk                            |  10
code/saffah_2_1/t.cpp.tk                            |  36
code/SamanSami_0_1/A.cpp.tk                         |  44
code/SamanSami_1_1/B.cpp.tk                         |  103
code/SamanSami_2_1/C.cpp.tk                         |  4
code/Savlik_0_1/code.cpp.tk                         |  30
code/Savlik_1_1/code.cpp.tk                         |  7
code/Savlik_2_1/code.cpp.tk                         |  36
code/shik_0_1/pa.cpp.tk                             |  35
code/shik_1_1/pb.cpp.tk                             |  32
code/shik_2_1/pc.cpp.tk                             |  56
code/simsa.st_0_1/A.cpp.tk                          |  8
code/simsa.st_1_1/B.cpp.tk                          |  9
code/simsa.st_2_1/C.cpp.tk                          |  31
code/SovietUnion_0_1/A.cpp.tk                       |  48
code/SovietUnion_1_1/B.cpp.tk                       |  59
code/SovietUnion_2_1/C.cpp.tk                       |  46
code/tailed_0_1/A.cpp.tk                            |  84
code/tailed_1_1/B.cpp.tk                            |  85
code/tailed_2_1/C.cpp.tk                            |  41
code/TheNatural_0_1/A.cpp.tk                        |  92
code/TheNatural_1_1/B.cpp.tk                        |  99
code/TheNatural_2_1/C.cpp.tk                        |  60
code/TrueBamboo_0_1/test.cpp.tk                     |  26
code/TrueBamboo_1_1/test.cpp.tk                     |  29
code/TrueBamboo_2_1/test.cpp.tk                     |  36
code/tur.turczyn_0_1/A.cpp.tk                       |  28
code/tur.turczyn_1_1/B.cpp.tk                       |  25
code/tur.turczyn_2_1/C.cpp.tk                       |  31
code/Tyg3R_0_1/A.cpp.tk                             |  10
code/Tyg3R_1_1/B.cpp.tk                             |  12
code/Tyg3R_2_1/C.cpp.tk                             |  23
code/UminchuR_0_1/main.cpp.tk                       |  52
code/UminchuR_1_1/main.cpp.tk                       |  18
code/UminchuR_2_1/main.cpp.tk                       |  40
code/wo..._0_1/a.cpp.tk                             |  50
code/wo..._1_1/b.cpp.tk                             |  59
code/wo..._2_1/c.cpp.tk                             |  98
code/yswtt_0_1/A.cpp.tk                             |  96
code/yswtt_1_1/B.cpp.tk                             |  75
code/yswtt_2_1/C.cpp.tk                             |  94
code/ZhSh_0_1/a.cpp.tk                              |  86
code/ZhSh_1_1/b.cpp.tk                              |  93
code/ZhSh_2_1/c.cpp.tk                              |  86
