Begin
Comparing:  code/achan1058_2_1/source.cpp.tk
code/00/test.cpp.tk                                 |  20
code/01/test.cpp.tk                                 |  20
code/551100kk_0_1/A.cpp.tk                          |  20
code/551100kk_1_1/B.cpp.tk                          |  30
code/551100kk_2_1/C.cpp.tk                          |  75
code/achan1058_0_1/Q-A.cpp.tk                       |  22
code/achan1058_1_1/source.cpp.tk                    |  952
code/achan1058_2_1/source.cpp.tk                    |  101911
code/alanubi_0_1/a.cpp.tk                           |  17
code/alanubi_1_1/b.cpp.tk                           |  23
code/alanubi_2_1/c.cpp.tk                           |  125
code/AntiForest_0_1/q1.cpp.tk                       |  28
code/AntiForest_1_1/q2.cpp.tk                       |  14
code/AntiForest_2_1/q3.cpp.tk                       |  89
code/apiad_0_1/A.cpp.tk                             |  31
code/apiad_1_1/B.cpp.tk                             |  42
code/apiad_2_1/C.cpp.tk                             |  46
code/azaky_0_1/A.cpp.tk                             |  35
code/azaky_1_1/B.cpp.tk                             |  41
code/azaky_2_1/C.cpp.tk                             |  100
code/azariamuh_0_1/standing.cpp.tk                  |  22
code/azariamuh_1_1/pancake.cpp.tk                   |  44
code/azariamuh_2_1/dijkstra.cpp.tk                  |  40
code/bmerry_0_1/a.cpp.tk                            |  90
code/bmerry_1_1/b.cpp.tk                            |  101
code/bmerry_2_1/c.cpp.tk                            |  104
code/climpet_0_1/A.cpp.tk                           |  56
code/climpet_1_1/B.cpp.tk                           |  61
code/climpet_2_1/C.cpp.tk                           |  90
code/ctzsm_0_1/A.cpp.tk                             |  21
code/ctzsm_1_1/B.cpp.tk                             |  29
code/ctzsm_2_1/C.cpp.tk                             |  112
code/DanilC_0_1/problem.cpp.tk                      |  42
code/DanilC_1_1/problemB.cpp.tk                     |  60
code/DanilC_2_1/problemC.cpp.tk                     |  167
code/DEGwer_0_1/A.cpp.tk                            |  28
code/DEGwer_1_1/B.cpp.tk                            |  30
code/DEGwer_2_1/C.cpp.tk                            |  51
code/dmute_0_1/a.cpp.tk                             |  13
code/dmute_1_1/b.cpp.tk                             |  22
code/dmute_2_1/c2.cpp.tk                            |  64
code/fagu_0_1/A.cpp.tk                              |  28
code/fagu_1_1/B.cpp.tk                              |  28
code/fagu_2_1/C.cpp.tk                              |  73
code/FatalEagle_0_1/main.cpp.tk                     |  19
code/FatalEagle_1_1/main.cpp.tk                     |  29
code/FatalEagle_2_1/main.cpp.tk                     |  210
code/fullpower_0_1/A.cpp.tk                         |  32
code/fullpower_1_1/B.cpp.tk                         |  35
code/fullpower_2_1/C.cpp.tk                         |  97
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  16
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  26
code/ICastro_2_1/Dijkstra.cpp.tk                    |  184
code/ilackthatsuperpower_0_1/a.cpp.tk               |  124
code/ilackthatsuperpower_1_1/b.cpp.tk               |  130
code/ilackthatsuperpower_2_1/c.cpp.tk               |  183
code/iridescent_0_1/A.cpp.tk                        |  13
code/iridescent_1_1/B.cpp.tk                        |  17
code/iridescent_2_1/C.cpp.tk                        |  26
code/ishraq_0_1/main.cpp.tk                         |  16
code/ishraq_1_1/main.cpp.tk                         |  23
code/ishraq_2_1/main.cpp.tk                         |  118
code/JayXon_0_1/A.cpp.tk                            |  10
code/JayXon_1_1/B.cpp.tk                            |  26
code/JayXon_2_1/C.cpp.tk                            |  72
code/Josse_0_1/A.cpp.tk                             |  19
code/Josse_1_1/B.cpp.tk                             |  25
code/Josse_2_1/C.cpp.tk                             |  123
code/kcm1700_0_1/a.cpp.tk                           |  12
code/kcm1700_1_1/b.cpp.tk                           |  20
code/kcm1700_2_1/c.cpp.tk                           |  77
code/kevinsogo_0_1/a.cpp.tk                         |  19
code/kevinsogo_1_1/b.cpp.tk                         |  25
code/kevinsogo_2_1/c.cpp.tk                         |  82
code/ksun48_0_1/A.cpp.tk                            |  5
code/ksun48_1_1/B.cpp.tk                            |  5
code/ksun48_2_1/C.cpp.tk                            |  54
code/LazyAnna_0_1/1.cpp.tk                          |  12
code/LazyAnna_1_1/2-1.cpp.tk                        |  19
code/LazyAnna_2_1/3.cpp.tk                          |  53
code/Merkurev_0_1/A.cpp.tk                          |  20
code/Merkurev_1_1/B.cpp.tk                          |  46
code/Merkurev_2_1/C.cpp.tk                          |  48
code/mezei_0_1/main.cpp.tk                          |  22
code/mezei_1_1/main.cpp.tk                          |  20
code/mezei_2_1/main.cpp.tk                          |  90
code/Mister_0_1/a.cpp.tk                            |  18
code/Mister_1_1/b.cpp.tk                            |  19
code/Mister_2_1/c.cpp.tk                            |  45
code/namonakiacc_0_1/cpp.cpp.tk                     |  85
code/namonakiacc_1_1/cpp.cpp.tk                     |  91
code/namonakiacc_2_1/cpp.cpp.tk                     |  142
code/Nicolas16_0_1/main.cpp.tk                      |  9
code/Nicolas16_1_1/main.cpp.tk                      |  8
code/Nicolas16_2_1/main.cpp.tk                      |  131
code/pandamonium_0_1/a.cpp.tk                       |  16
code/pandamonium_1_1/b.cpp.tk                       |  49
code/pandamonium_2_1/c.cpp.tk                       |  32
code/pflueger_0_1/A.cpp.tk                          |  14
code/pflueger_1_1/B.cpp.tk                          |  24
code/pflueger_2_1/C.cpp.tk                          |  115
code/ponyopoppo_0_1/A.cpp.tk                        |  20
code/ponyopoppo_1_1/B.cpp.tk                        |  39
code/ponyopoppo_2_1/C.cpp.tk                        |  306
code/Ragnar_0_1/A.cpp.tk                            |  78
code/Ragnar_1_1/B-2.cpp.tk                          |  87
code/Ragnar_2_1/C.cpp.tk                            |  116
code/saffah_0_1/t.cpp.tk                            |  17
code/saffah_1_1/t.cpp.tk                            |  26
code/saffah_2_1/t.cpp.tk                            |  128
code/SamanSami_0_1/A.cpp.tk                         |  5
code/SamanSami_1_1/B.cpp.tk                         |  18
code/SamanSami_2_1/C.cpp.tk                         |  25
code/Savlik_0_1/code.cpp.tk                         |  17
code/Savlik_1_1/code.cpp.tk                         |  22
code/Savlik_2_1/code.cpp.tk                         |  113
code/shik_0_1/pa.cpp.tk                             |  98
code/shik_1_1/pb.cpp.tk                             |  101
code/shik_2_1/pc.cpp.tk                             |  150
code/simsa.st_0_1/A.cpp.tk                          |  18
code/simsa.st_1_1/B.cpp.tk                          |  24
code/simsa.st_2_1/C.cpp.tk                          |  128
code/SovietUnion_0_1/A.cpp.tk                       |  22
code/SovietUnion_1_1/B.cpp.tk                       |  26
code/SovietUnion_2_1/C.cpp.tk                       |  113
code/tailed_0_1/A.cpp.tk                            |  16
code/tailed_1_1/B.cpp.tk                            |  22
code/tailed_2_1/C.cpp.tk                            |  76
code/TheNatural_0_1/A.cpp.tk                        |  14
code/TheNatural_1_1/B.cpp.tk                        |  18
code/TheNatural_2_1/C.cpp.tk                        |  31
code/TrueBamboo_0_1/test.cpp.tk                     |  22
code/TrueBamboo_1_1/test.cpp.tk                     |  31
code/TrueBamboo_2_1/test.cpp.tk                     |  93
code/tur.turczyn_0_1/A.cpp.tk                       |  69
code/tur.turczyn_1_1/B.cpp.tk                       |  84
code/tur.turczyn_2_1/C.cpp.tk                       |  94
code/Tyg3R_0_1/A.cpp.tk                             |  23
code/Tyg3R_1_1/B.cpp.tk                             |  30
code/Tyg3R_2_1/C.cpp.tk                             |  32
code/UminchuR_0_1/main.cpp.tk                       |  78
code/UminchuR_1_1/main.cpp.tk                       |  88
code/UminchuR_2_1/main.cpp.tk                       |  125
code/wo..._0_1/a.cpp.tk                             |  18
code/wo..._1_1/b.cpp.tk                             |  25
code/wo..._2_1/c.cpp.tk                             |  88
code/yswtt_0_1/A.cpp.tk                             |  12
code/yswtt_1_1/B.cpp.tk                             |  22
code/yswtt_2_1/C.cpp.tk                             |  63
code/ZhSh_0_1/a.cpp.tk                              |  13
code/ZhSh_1_1/b.cpp.tk                              |  105
code/ZhSh_2_1/c.cpp.tk                              |  144
