Begin
Comparing:  code/Josse_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  15
code/551100kk_1_1/B.cpp.tk                          |  31
code/551100kk_2_1/C.cpp.tk                          |  39
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  22
code/achan1058_2_1/source.cpp.tk                    |  38
code/alanubi_0_1/a.cpp.tk                           |  58
code/alanubi_1_1/b.cpp.tk                           |  88
code/alanubi_2_1/c.cpp.tk                           |  171
code/AntiForest_0_1/q1.cpp.tk                       |  21
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  34
code/apiad_0_1/A.cpp.tk                             |  18
code/apiad_1_1/B.cpp.tk                             |  18
code/apiad_2_1/C.cpp.tk                             |  20
code/azaky_0_1/A.cpp.tk                             |  16
code/azaky_1_1/B.cpp.tk                             |  14
code/azaky_2_1/C.cpp.tk                             |  32
code/azariamuh_0_1/standing.cpp.tk                  |  18
code/azariamuh_1_1/pancake.cpp.tk                   |  16
code/azariamuh_2_1/dijkstra.cpp.tk                  |  15
code/bmerry_0_1/a.cpp.tk                            |  75
code/bmerry_1_1/b.cpp.tk                            |  96
code/bmerry_2_1/c.cpp.tk                            |  76
code/climpet_0_1/A.cpp.tk                           |  54
code/climpet_1_1/B.cpp.tk                           |  47
code/climpet_2_1/C.cpp.tk                           |  65
code/ctzsm_0_1/A.cpp.tk                             |  23
code/ctzsm_1_1/B.cpp.tk                             |  37
code/ctzsm_2_1/C.cpp.tk                             |  73
code/DanilC_0_1/problem.cpp.tk                      |  49
code/DanilC_1_1/problemB.cpp.tk                     |  67
code/DanilC_2_1/problemC.cpp.tk                     |  78
code/DEGwer_0_1/A.cpp.tk                            |  51
code/DEGwer_1_1/B.cpp.tk                            |  71
code/DEGwer_2_1/C.cpp.tk                            |  56
code/dmute_0_1/a.cpp.tk                             |  24
code/dmute_1_1/b.cpp.tk                             |  46
code/dmute_2_1/c2.cpp.tk                            |  80
code/fagu_0_1/A.cpp.tk                              |  27
code/fagu_1_1/B.cpp.tk                              |  27
code/fagu_2_1/C.cpp.tk                              |  42
code/FatalEagle_0_1/main.cpp.tk                     |  31
code/FatalEagle_1_1/main.cpp.tk                     |  82
code/FatalEagle_2_1/main.cpp.tk                     |  283
code/fullpower_0_1/A.cpp.tk                         |  33
code/fullpower_1_1/B.cpp.tk                         |  68
code/fullpower_2_1/C.cpp.tk                         |  87
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  44
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  45
code/ICastro_2_1/Dijkstra.cpp.tk                    |  70
code/ilackthatsuperpower_0_1/a.cpp.tk               |  91
code/ilackthatsuperpower_1_1/b.cpp.tk               |  80
code/ilackthatsuperpower_2_1/c.cpp.tk               |  92
code/iridescent_0_1/A.cpp.tk                        |  37
code/iridescent_1_1/B.cpp.tk                        |  49
code/iridescent_2_1/C.cpp.tk                        |  74
code/ishraq_0_1/main.cpp.tk                         |  20
code/ishraq_1_1/main.cpp.tk                         |  26
code/ishraq_2_1/main.cpp.tk                         |  41
code/JayXon_0_1/A.cpp.tk                            |  20
code/JayXon_1_1/B.cpp.tk                            |  64
code/JayXon_2_1/C.cpp.tk                            |  22
code/Josse_0_1/A.cpp.tk                             |  6079
code/Josse_1_1/B.cpp.tk                             |  414
code/Josse_2_1/C.cpp.tk                             |  348
code/kcm1700_0_1/a.cpp.tk                           |  39
code/kcm1700_1_1/b.cpp.tk                           |  72
code/kcm1700_2_1/c.cpp.tk                           |  79
code/kevinsogo_0_1/a.cpp.tk                         |  14
code/kevinsogo_1_1/b.cpp.tk                         |  16
code/kevinsogo_2_1/c.cpp.tk                         |  33
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  10
code/LazyAnna_0_1/1.cpp.tk                          |  34
code/LazyAnna_1_1/2-1.cpp.tk                        |  43
code/LazyAnna_2_1/3.cpp.tk                          |  38
code/Merkurev_0_1/A.cpp.tk                          |  56
code/Merkurev_1_1/B.cpp.tk                          |  103
code/Merkurev_2_1/C.cpp.tk                          |  69
code/mezei_0_1/main.cpp.tk                          |  41
code/mezei_1_1/main.cpp.tk                          |  67
code/mezei_2_1/main.cpp.tk                          |  102
code/Mister_0_1/a.cpp.tk                            |  22
code/Mister_1_1/b.cpp.tk                            |  35
code/Mister_2_1/c.cpp.tk                            |  40
code/namonakiacc_0_1/cpp.cpp.tk                     |  23
code/namonakiacc_1_1/cpp.cpp.tk                     |  20
code/namonakiacc_2_1/cpp.cpp.tk                     |  33
code/Nicolas16_0_1/main.cpp.tk                      |  14
code/Nicolas16_1_1/main.cpp.tk                      |  13
code/Nicolas16_2_1/main.cpp.tk                      |  89
code/pandamonium_0_1/a.cpp.tk                       |  22
code/pandamonium_1_1/b.cpp.tk                       |  93
code/pandamonium_2_1/c.cpp.tk                       |  52
code/pflueger_0_1/A.cpp.tk                          |  44
code/pflueger_1_1/B.cpp.tk                          |  89
code/pflueger_2_1/C.cpp.tk                          |  97
code/ponyopoppo_0_1/A.cpp.tk                        |  25
code/ponyopoppo_1_1/B.cpp.tk                        |  30
code/ponyopoppo_2_1/C.cpp.tk                        |  63
code/Ragnar_0_1/A.cpp.tk                            |  22
code/Ragnar_1_1/B-2.cpp.tk                          |  39
code/Ragnar_2_1/C.cpp.tk                            |  39
code/saffah_0_1/t.cpp.tk                            |  12
code/saffah_1_1/t.cpp.tk                            |  11
code/saffah_2_1/t.cpp.tk                            |  42
code/SamanSami_0_1/A.cpp.tk                         |  11
code/SamanSami_1_1/B.cpp.tk                         |  76
code/SamanSami_2_1/C.cpp.tk                         |  4
code/Savlik_0_1/code.cpp.tk                         |  30
code/Savlik_1_1/code.cpp.tk                         |  8
code/Savlik_2_1/code.cpp.tk                         |  38
code/shik_0_1/pa.cpp.tk                             |  33
code/shik_1_1/pb.cpp.tk                             |  33
code/shik_2_1/pc.cpp.tk                             |  54
code/simsa.st_0_1/A.cpp.tk                          |  12
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  37
code/SovietUnion_0_1/A.cpp.tk                       |  28
code/SovietUnion_1_1/B.cpp.tk                       |  35
code/SovietUnion_2_1/C.cpp.tk                       |  40
code/tailed_0_1/A.cpp.tk                            |  41
code/tailed_1_1/B.cpp.tk                            |  41
code/tailed_2_1/C.cpp.tk                            |  36
code/TheNatural_0_1/A.cpp.tk                        |  41
code/TheNatural_1_1/B.cpp.tk                        |  88
code/TheNatural_2_1/C.cpp.tk                        |  38
code/TrueBamboo_0_1/test.cpp.tk                     |  21
code/TrueBamboo_1_1/test.cpp.tk                     |  34
code/TrueBamboo_2_1/test.cpp.tk                     |  40
code/tur.turczyn_0_1/A.cpp.tk                       |  28
code/tur.turczyn_1_1/B.cpp.tk                       |  42
code/tur.turczyn_2_1/C.cpp.tk                       |  33
code/Tyg3R_0_1/A.cpp.tk                             |  16
code/Tyg3R_1_1/B.cpp.tk                             |  12
code/Tyg3R_2_1/C.cpp.tk                             |  27
code/UminchuR_0_1/main.cpp.tk                       |  31
code/UminchuR_1_1/main.cpp.tk                       |  21
code/UminchuR_2_1/main.cpp.tk                       |  41
code/wo..._0_1/a.cpp.tk                             |  59
code/wo..._1_1/b.cpp.tk                             |  90
code/wo..._2_1/c.cpp.tk                             |  119
code/yswtt_0_1/A.cpp.tk                             |  30
code/yswtt_1_1/B.cpp.tk                             |  42
code/yswtt_2_1/C.cpp.tk                             |  58
code/ZhSh_0_1/a.cpp.tk                              |  54
code/ZhSh_1_1/b.cpp.tk                              |  76
code/ZhSh_2_1/c.cpp.tk                              |  69
