Begin
Comparing:  code/pflueger_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  16
code/551100kk_1_1/B.cpp.tk                          |  42
code/551100kk_2_1/C.cpp.tk                          |  42
code/achan1058_0_1/Q-A.cpp.tk                       |  10
code/achan1058_1_1/source.cpp.tk                    |  22
code/achan1058_2_1/source.cpp.tk                    |  40
code/alanubi_0_1/a.cpp.tk                           |  58
code/alanubi_1_1/b.cpp.tk                           |  88
code/alanubi_2_1/c.cpp.tk                           |  186
code/AntiForest_0_1/q1.cpp.tk                       |  12
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  48
code/apiad_0_1/A.cpp.tk                             |  14
code/apiad_1_1/B.cpp.tk                             |  23
code/apiad_2_1/C.cpp.tk                             |  22
code/azaky_0_1/A.cpp.tk                             |  12
code/azaky_1_1/B.cpp.tk                             |  19
code/azaky_2_1/C.cpp.tk                             |  38
code/azariamuh_0_1/standing.cpp.tk                  |  10
code/azariamuh_1_1/pancake.cpp.tk                   |  20
code/azariamuh_2_1/dijkstra.cpp.tk                  |  24
code/bmerry_0_1/a.cpp.tk                            |  90
code/bmerry_1_1/b.cpp.tk                            |  176
code/bmerry_2_1/c.cpp.tk                            |  105
code/climpet_0_1/A.cpp.tk                           |  54
code/climpet_1_1/B.cpp.tk                           |  75
code/climpet_2_1/C.cpp.tk                           |  86
code/ctzsm_0_1/A.cpp.tk                             |  33
code/ctzsm_1_1/B.cpp.tk                             |  50
code/ctzsm_2_1/C.cpp.tk                             |  99
code/DanilC_0_1/problem.cpp.tk                      |  59
code/DanilC_1_1/problemB.cpp.tk                     |  90
code/DanilC_2_1/problemC.cpp.tk                     |  102
code/DEGwer_0_1/A.cpp.tk                            |  69
code/DEGwer_1_1/B.cpp.tk                            |  112
code/DEGwer_2_1/C.cpp.tk                            |  69
code/dmute_0_1/a.cpp.tk                             |  42
code/dmute_1_1/b.cpp.tk                             |  94
code/dmute_2_1/c2.cpp.tk                            |  123
code/fagu_0_1/A.cpp.tk                              |  27
code/fagu_1_1/B.cpp.tk                              |  28
code/fagu_2_1/C.cpp.tk                              |  47
code/FatalEagle_0_1/main.cpp.tk                     |  47
code/FatalEagle_1_1/main.cpp.tk                     |  133
code/FatalEagle_2_1/main.cpp.tk                     |  369
code/fullpower_0_1/A.cpp.tk                         |  71
code/fullpower_1_1/B.cpp.tk                         |  159
code/fullpower_2_1/C.cpp.tk                         |  172
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  49
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  82
code/ICastro_2_1/Dijkstra.cpp.tk                    |  85
code/ilackthatsuperpower_0_1/a.cpp.tk               |  103
code/ilackthatsuperpower_1_1/b.cpp.tk               |  122
code/ilackthatsuperpower_2_1/c.cpp.tk               |  104
code/iridescent_0_1/A.cpp.tk                        |  96
code/iridescent_1_1/B.cpp.tk                        |  259
code/iridescent_2_1/C.cpp.tk                        |  139
code/ishraq_0_1/main.cpp.tk                         |  10
code/ishraq_1_1/main.cpp.tk                         |  48
code/ishraq_2_1/main.cpp.tk                         |  57
code/JayXon_0_1/A.cpp.tk                            |  24
code/JayXon_1_1/B.cpp.tk                            |  104
code/JayXon_2_1/C.cpp.tk                            |  26
code/Josse_0_1/A.cpp.tk                             |  75
code/Josse_1_1/B.cpp.tk                             |  327
code/Josse_2_1/C.cpp.tk                             |  172
code/kcm1700_0_1/a.cpp.tk                           |  55
code/kcm1700_1_1/b.cpp.tk                           |  105
code/kcm1700_2_1/c.cpp.tk                           |  130
code/kevinsogo_0_1/a.cpp.tk                         |  10
code/kevinsogo_1_1/b.cpp.tk                         |  19
code/kevinsogo_2_1/c.cpp.tk                         |  43
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  39
code/LazyAnna_1_1/2-1.cpp.tk                        |  72
code/LazyAnna_2_1/3.cpp.tk                          |  43
code/Merkurev_0_1/A.cpp.tk                          |  69
code/Merkurev_1_1/B.cpp.tk                          |  137
code/Merkurev_2_1/C.cpp.tk                          |  105
code/mezei_0_1/main.cpp.tk                          |  73
code/mezei_1_1/main.cpp.tk                          |  233
code/mezei_2_1/main.cpp.tk                          |  129
code/Mister_0_1/a.cpp.tk                            |  29
code/Mister_1_1/b.cpp.tk                            |  61
code/Mister_2_1/c.cpp.tk                            |  64
code/namonakiacc_0_1/cpp.cpp.tk                     |  19
code/namonakiacc_1_1/cpp.cpp.tk                     |  23
code/namonakiacc_2_1/cpp.cpp.tk                     |  36
code/Nicolas16_0_1/main.cpp.tk                      |  23
code/Nicolas16_1_1/main.cpp.tk                      |  22
code/Nicolas16_2_1/main.cpp.tk                      |  145
code/pandamonium_0_1/a.cpp.tk                       |  48
code/pandamonium_1_1/b.cpp.tk                       |  159
code/pandamonium_2_1/c.cpp.tk                       |  72
code/pflueger_0_1/A.cpp.tk                          |  138
code/pflueger_1_1/B.cpp.tk                          |  8993
code/pflueger_2_1/C.cpp.tk                          |  159
code/ponyopoppo_0_1/A.cpp.tk                        |  19
code/ponyopoppo_1_1/B.cpp.tk                        |  32
code/ponyopoppo_2_1/C.cpp.tk                        |  70
code/Ragnar_0_1/A.cpp.tk                            |  19
code/Ragnar_1_1/B-2.cpp.tk                          |  44
code/Ragnar_2_1/C.cpp.tk                            |  82
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  12
code/saffah_2_1/t.cpp.tk                            |  43
code/SamanSami_0_1/A.cpp.tk                         |  41
code/SamanSami_1_1/B.cpp.tk                         |  383
code/SamanSami_2_1/C.cpp.tk                         |  6
code/Savlik_0_1/code.cpp.tk                         |  28
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  42
code/shik_0_1/pa.cpp.tk                             |  34
code/shik_1_1/pb.cpp.tk                             |  41
code/shik_2_1/pc.cpp.tk                             |  64
code/simsa.st_0_1/A.cpp.tk                          |  8
code/simsa.st_1_1/B.cpp.tk                          |  14
code/simsa.st_2_1/C.cpp.tk                          |  40
code/SovietUnion_0_1/A.cpp.tk                       |  42
code/SovietUnion_1_1/B.cpp.tk                       |  59
code/SovietUnion_2_1/C.cpp.tk                       |  45
code/tailed_0_1/A.cpp.tk                            |  79
code/tailed_1_1/B.cpp.tk                            |  120
code/tailed_2_1/C.cpp.tk                            |  41
code/TheNatural_0_1/A.cpp.tk                        |  90
code/TheNatural_1_1/B.cpp.tk                        |  126
code/TheNatural_2_1/C.cpp.tk                        |  68
code/TrueBamboo_0_1/test.cpp.tk                     |  25
code/TrueBamboo_1_1/test.cpp.tk                     |  41
code/TrueBamboo_2_1/test.cpp.tk                     |  46
code/tur.turczyn_0_1/A.cpp.tk                       |  18
code/tur.turczyn_1_1/B.cpp.tk                       |  38
code/tur.turczyn_2_1/C.cpp.tk                       |  34
code/Tyg3R_0_1/A.cpp.tk                             |  10
code/Tyg3R_1_1/B.cpp.tk                             |  17
code/Tyg3R_2_1/C.cpp.tk                             |  19
code/UminchuR_0_1/main.cpp.tk                       |  17
code/UminchuR_1_1/main.cpp.tk                       |  24
code/UminchuR_2_1/main.cpp.tk                       |  42
code/wo..._0_1/a.cpp.tk                             |  83
code/wo..._1_1/b.cpp.tk                             |  117
code/wo..._2_1/c.cpp.tk                             |  147
code/yswtt_0_1/A.cpp.tk                             |  59
code/yswtt_1_1/B.cpp.tk                             |  97
code/yswtt_2_1/C.cpp.tk                             |  79
code/ZhSh_0_1/a.cpp.tk                              |  62
code/ZhSh_1_1/b.cpp.tk                              |  137
code/ZhSh_2_1/c.cpp.tk                              |  101
