Begin
Comparing:  code/tailed_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  12
code/551100kk_1_1/B.cpp.tk                          |  18
code/551100kk_2_1/C.cpp.tk                          |  53
code/achan1058_0_1/Q-A.cpp.tk                       |  9
code/achan1058_1_1/source.cpp.tk                    |  19
code/achan1058_2_1/source.cpp.tk                    |  56
code/alanubi_0_1/a.cpp.tk                           |  10
code/alanubi_1_1/b.cpp.tk                           |  12
code/alanubi_2_1/c.cpp.tk                           |  61
code/AntiForest_0_1/q1.cpp.tk                       |  12
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  61
code/apiad_0_1/A.cpp.tk                             |  13
code/apiad_1_1/B.cpp.tk                             |  16
code/apiad_2_1/C.cpp.tk                             |  31
code/azaky_0_1/A.cpp.tk                             |  13
code/azaky_1_1/B.cpp.tk                             |  16
code/azaky_2_1/C.cpp.tk                             |  145
code/azariamuh_0_1/standing.cpp.tk                  |  10
code/azariamuh_1_1/pancake.cpp.tk                   |  21
code/azariamuh_2_1/dijkstra.cpp.tk                  |  152
code/bmerry_0_1/a.cpp.tk                            |  35
code/bmerry_1_1/b.cpp.tk                            |  37
code/bmerry_2_1/c.cpp.tk                            |  52
code/climpet_0_1/A.cpp.tk                           |  21
code/climpet_1_1/B.cpp.tk                           |  23
code/climpet_2_1/C.cpp.tk                           |  54
code/ctzsm_0_1/A.cpp.tk                             |  10
code/ctzsm_1_1/B.cpp.tk                             |  12
code/ctzsm_2_1/C.cpp.tk                             |  173
code/DanilC_0_1/problem.cpp.tk                      |  21
code/DanilC_1_1/problemB.cpp.tk                     |  31
code/DanilC_2_1/problemC.cpp.tk                     |  76
code/DEGwer_0_1/A.cpp.tk                            |  14
code/DEGwer_1_1/B.cpp.tk                            |  14
code/DEGwer_2_1/C.cpp.tk                            |  40
code/dmute_0_1/a.cpp.tk                             |  10
code/dmute_1_1/b.cpp.tk                             |  17
code/dmute_2_1/c2.cpp.tk                            |  43
code/fagu_0_1/A.cpp.tk                              |  5
code/fagu_1_1/B.cpp.tk                              |  5
code/fagu_2_1/C.cpp.tk                              |  45
code/FatalEagle_0_1/main.cpp.tk                     |  13
code/FatalEagle_1_1/main.cpp.tk                     |  21
code/FatalEagle_2_1/main.cpp.tk                     |  98
code/fullpower_0_1/A.cpp.tk                         |  18
code/fullpower_1_1/B.cpp.tk                         |  25
code/fullpower_2_1/C.cpp.tk                         |  67
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  9
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  13
code/ICastro_2_1/Dijkstra.cpp.tk                    |  74
code/ilackthatsuperpower_0_1/a.cpp.tk               |  59
code/ilackthatsuperpower_1_1/b.cpp.tk               |  59
code/ilackthatsuperpower_2_1/c.cpp.tk               |  87
code/iridescent_0_1/A.cpp.tk                        |  11
code/iridescent_1_1/B.cpp.tk                        |  16
code/iridescent_2_1/C.cpp.tk                        |  39
code/ishraq_0_1/main.cpp.tk                         |  9
code/ishraq_1_1/main.cpp.tk                         |  10
code/ishraq_2_1/main.cpp.tk                         |  53
code/JayXon_0_1/A.cpp.tk                            |  8
code/JayXon_1_1/B.cpp.tk                            |  16
code/JayXon_2_1/C.cpp.tk                            |  34
code/Josse_0_1/A.cpp.tk                             |  13
code/Josse_1_1/B.cpp.tk                             |  18
code/Josse_2_1/C.cpp.tk                             |  58
code/kcm1700_0_1/a.cpp.tk                           |  9
code/kcm1700_1_1/b.cpp.tk                           |  13
code/kcm1700_2_1/c.cpp.tk                           |  44
code/kevinsogo_0_1/a.cpp.tk                         |  8
code/kevinsogo_1_1/b.cpp.tk                         |  12
code/kevinsogo_2_1/c.cpp.tk                         |  44
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  26
code/LazyAnna_0_1/1.cpp.tk                          |  8
code/LazyAnna_1_1/2-1.cpp.tk                        |  11
code/LazyAnna_2_1/3.cpp.tk                          |  38
code/Merkurev_0_1/A.cpp.tk                          |  15
code/Merkurev_1_1/B.cpp.tk                          |  22
code/Merkurev_2_1/C.cpp.tk                          |  28
code/mezei_0_1/main.cpp.tk                          |  15
code/mezei_1_1/main.cpp.tk                          |  13
code/mezei_2_1/main.cpp.tk                          |  51
code/Mister_0_1/a.cpp.tk                            |  9
code/Mister_1_1/b.cpp.tk                            |  9
code/Mister_2_1/c.cpp.tk                            |  40
code/namonakiacc_0_1/cpp.cpp.tk                     |  15
code/namonakiacc_1_1/cpp.cpp.tk                     |  18
code/namonakiacc_2_1/cpp.cpp.tk                     |  52
code/Nicolas16_0_1/main.cpp.tk                      |  6
code/Nicolas16_1_1/main.cpp.tk                      |  5
code/Nicolas16_2_1/main.cpp.tk                      |  85
code/pandamonium_0_1/a.cpp.tk                       |  11
code/pandamonium_1_1/b.cpp.tk                       |  26
code/pandamonium_2_1/c.cpp.tk                       |  25
code/pflueger_0_1/A.cpp.tk                          |  13
code/pflueger_1_1/B.cpp.tk                          |  17
code/pflueger_2_1/C.cpp.tk                          |  57
code/ponyopoppo_0_1/A.cpp.tk                        |  13
code/ponyopoppo_1_1/B.cpp.tk                        |  24
code/ponyopoppo_2_1/C.cpp.tk                        |  102
code/Ragnar_0_1/A.cpp.tk                            |  13
code/Ragnar_1_1/B-2.cpp.tk                          |  16
code/Ragnar_2_1/C.cpp.tk                            |  34
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  11
code/saffah_2_1/t.cpp.tk                            |  56
code/SamanSami_0_1/A.cpp.tk                         |  4
code/SamanSami_1_1/B.cpp.tk                         |  12
code/SamanSami_2_1/C.cpp.tk                         |  9
code/Savlik_0_1/code.cpp.tk                         |  9
code/Savlik_1_1/code.cpp.tk                         |  9
code/Savlik_2_1/code.cpp.tk                         |  47
code/shik_0_1/pa.cpp.tk                             |  41
code/shik_1_1/pb.cpp.tk                             |  42
code/shik_2_1/pc.cpp.tk                             |  86
code/simsa.st_0_1/A.cpp.tk                          |  9
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  54
code/SovietUnion_0_1/A.cpp.tk                       |  11
code/SovietUnion_1_1/B.cpp.tk                       |  14
code/SovietUnion_2_1/C.cpp.tk                       |  50
code/tailed_0_1/A.cpp.tk                            |  15
code/tailed_1_1/B.cpp.tk                            |  18
code/tailed_2_1/C.cpp.tk                            |  50941
code/TheNatural_0_1/A.cpp.tk                        |  14
code/TheNatural_1_1/B.cpp.tk                        |  15
code/TheNatural_2_1/C.cpp.tk                        |  30
code/TrueBamboo_0_1/test.cpp.tk                     |  21
code/TrueBamboo_1_1/test.cpp.tk                     |  23
code/TrueBamboo_2_1/test.cpp.tk                     |  49
code/tur.turczyn_0_1/A.cpp.tk                       |  13
code/tur.turczyn_1_1/B.cpp.tk                       |  18
code/tur.turczyn_2_1/C.cpp.tk                       |  133
code/Tyg3R_0_1/A.cpp.tk                             |  10
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  133
code/UminchuR_0_1/main.cpp.tk                       |  17
code/UminchuR_1_1/main.cpp.tk                       |  19
code/UminchuR_2_1/main.cpp.tk                       |  47
code/wo..._0_1/a.cpp.tk                             |  12
code/wo..._1_1/b.cpp.tk                             |  15
code/wo..._2_1/c.cpp.tk                             |  63
code/yswtt_0_1/A.cpp.tk                             |  9
code/yswtt_1_1/B.cpp.tk                             |  14
code/yswtt_2_1/C.cpp.tk                             |  52
code/ZhSh_0_1/a.cpp.tk                              |  10
code/ZhSh_1_1/b.cpp.tk                              |  43
code/ZhSh_2_1/c.cpp.tk                              |  99
