Begin
Comparing:  code/ponyopoppo_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  29
code/551100kk_1_1/B.cpp.tk                          |  18
code/551100kk_2_1/C.cpp.tk                          |  32
code/achan1058_0_1/Q-A.cpp.tk                       |  16
code/achan1058_1_1/source.cpp.tk                    |  38
code/achan1058_2_1/source.cpp.tk                    |  57
code/alanubi_0_1/a.cpp.tk                           |  15
code/alanubi_1_1/b.cpp.tk                           |  18
code/alanubi_2_1/c.cpp.tk                           |  78
code/AntiForest_0_1/q1.cpp.tk                       |  63
code/AntiForest_1_1/q2.cpp.tk                       |  6
code/AntiForest_2_1/q3.cpp.tk                       |  47
code/apiad_0_1/A.cpp.tk                             |  24
code/apiad_1_1/B.cpp.tk                             |  22
code/apiad_2_1/C.cpp.tk                             |  31
code/azaky_0_1/A.cpp.tk                             |  36
code/azaky_1_1/B.cpp.tk                             |  24
code/azaky_2_1/C.cpp.tk                             |  52
code/azariamuh_0_1/standing.cpp.tk                  |  18
code/azariamuh_1_1/pancake.cpp.tk                   |  30
code/azariamuh_2_1/dijkstra.cpp.tk                  |  18
code/bmerry_0_1/a.cpp.tk                            |  56
code/bmerry_1_1/b.cpp.tk                            |  56
code/bmerry_2_1/c.cpp.tk                            |  59
code/climpet_0_1/A.cpp.tk                           |  35
code/climpet_1_1/B.cpp.tk                           |  42
code/climpet_2_1/C.cpp.tk                           |  56
code/ctzsm_0_1/A.cpp.tk                             |  26
code/ctzsm_1_1/B.cpp.tk                             |  17
code/ctzsm_2_1/C.cpp.tk                             |  61
code/DanilC_0_1/problem.cpp.tk                      |  34
code/DanilC_1_1/problemB.cpp.tk                     |  48
code/DanilC_2_1/problemC.cpp.tk                     |  100
code/DEGwer_0_1/A.cpp.tk                            |  20
code/DEGwer_1_1/B.cpp.tk                            |  22
code/DEGwer_2_1/C.cpp.tk                            |  23
code/dmute_0_1/a.cpp.tk                             |  10
code/dmute_1_1/b.cpp.tk                             |  17
code/dmute_2_1/c2.cpp.tk                            |  42
code/fagu_0_1/A.cpp.tk                              |  10
code/fagu_1_1/B.cpp.tk                              |  10
code/fagu_2_1/C.cpp.tk                              |  35
code/FatalEagle_0_1/main.cpp.tk                     |  17
code/FatalEagle_1_1/main.cpp.tk                     |  17
code/FatalEagle_2_1/main.cpp.tk                     |  124
code/fullpower_0_1/A.cpp.tk                         |  28
code/fullpower_1_1/B.cpp.tk                         |  27
code/fullpower_2_1/C.cpp.tk                         |  62
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  20
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  29
code/ICastro_2_1/Dijkstra.cpp.tk                    |  82
code/ilackthatsuperpower_0_1/a.cpp.tk               |  96
code/ilackthatsuperpower_1_1/b.cpp.tk               |  81
code/ilackthatsuperpower_2_1/c.cpp.tk               |  105
code/iridescent_0_1/A.cpp.tk                        |  27
code/iridescent_1_1/B.cpp.tk                        |  30
code/iridescent_2_1/C.cpp.tk                        |  31
code/ishraq_0_1/main.cpp.tk                         |  17
code/ishraq_1_1/main.cpp.tk                         |  18
code/ishraq_2_1/main.cpp.tk                         |  72
code/JayXon_0_1/A.cpp.tk                            |  27
code/JayXon_1_1/B.cpp.tk                            |  24
code/JayXon_2_1/C.cpp.tk                            |  29
code/Josse_0_1/A.cpp.tk                             |  30
code/Josse_1_1/B.cpp.tk                             |  39
code/Josse_2_1/C.cpp.tk                             |  83
code/kcm1700_0_1/a.cpp.tk                           |  15
code/kcm1700_1_1/b.cpp.tk                           |  16
code/kcm1700_2_1/c.cpp.tk                           |  43
code/kevinsogo_0_1/a.cpp.tk                         |  33
code/kevinsogo_1_1/b.cpp.tk                         |  24
code/kevinsogo_2_1/c.cpp.tk                         |  63
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  14
code/LazyAnna_0_1/1.cpp.tk                          |  21
code/LazyAnna_1_1/2-1.cpp.tk                        |  21
code/LazyAnna_2_1/3.cpp.tk                          |  39
code/Merkurev_0_1/A.cpp.tk                          |  26
code/Merkurev_1_1/B.cpp.tk                          |  27
code/Merkurev_2_1/C.cpp.tk                          |  36
code/mezei_0_1/main.cpp.tk                          |  20
code/mezei_1_1/main.cpp.tk                          |  15
code/mezei_2_1/main.cpp.tk                          |  45
code/Mister_0_1/a.cpp.tk                            |  13
code/Mister_1_1/b.cpp.tk                            |  14
code/Mister_2_1/c.cpp.tk                            |  27
code/namonakiacc_0_1/cpp.cpp.tk                     |  41
code/namonakiacc_1_1/cpp.cpp.tk                     |  37
code/namonakiacc_2_1/cpp.cpp.tk                     |  63
code/Nicolas16_0_1/main.cpp.tk                      |  7
code/Nicolas16_1_1/main.cpp.tk                      |  7
code/Nicolas16_2_1/main.cpp.tk                      |  49
code/pandamonium_0_1/a.cpp.tk                       |  11
code/pandamonium_1_1/b.cpp.tk                       |  28
code/pandamonium_2_1/c.cpp.tk                       |  20
code/pflueger_0_1/A.cpp.tk                          |  39
code/pflueger_1_1/B.cpp.tk                          |  29
code/pflueger_2_1/C.cpp.tk                          |  57
code/ponyopoppo_0_1/A.cpp.tk                        |  4265
code/ponyopoppo_1_1/B.cpp.tk                        |  81
code/ponyopoppo_2_1/C.cpp.tk                        |  118
code/Ragnar_0_1/A.cpp.tk                            |  50
code/Ragnar_1_1/B-2.cpp.tk                          |  62
code/Ragnar_2_1/C.cpp.tk                            |  53
code/saffah_0_1/t.cpp.tk                            |  27
code/saffah_1_1/t.cpp.tk                            |  15
code/saffah_2_1/t.cpp.tk                            |  60
code/SamanSami_0_1/A.cpp.tk                         |  8
code/SamanSami_1_1/B.cpp.tk                         |  24
code/SamanSami_2_1/C.cpp.tk                         |  9
code/Savlik_0_1/code.cpp.tk                         |  27
code/Savlik_1_1/code.cpp.tk                         |  17
code/Savlik_2_1/code.cpp.tk                         |  59
code/shik_0_1/pa.cpp.tk                             |  63
code/shik_1_1/pb.cpp.tk                             |  50
code/shik_2_1/pc.cpp.tk                             |  76
code/simsa.st_0_1/A.cpp.tk                          |  23
code/simsa.st_1_1/B.cpp.tk                          |  17
code/simsa.st_2_1/C.cpp.tk                          |  58
code/SovietUnion_0_1/A.cpp.tk                       |  16
code/SovietUnion_1_1/B.cpp.tk                       |  18
code/SovietUnion_2_1/C.cpp.tk                       |  56
code/tailed_0_1/A.cpp.tk                            |  43
code/tailed_1_1/B.cpp.tk                            |  32
code/tailed_2_1/C.cpp.tk                            |  51
code/TheNatural_0_1/A.cpp.tk                        |  35
code/TheNatural_1_1/B.cpp.tk                        |  20
code/TheNatural_2_1/C.cpp.tk                        |  26
code/TrueBamboo_0_1/test.cpp.tk                     |  17
code/TrueBamboo_1_1/test.cpp.tk                     |  24
code/TrueBamboo_2_1/test.cpp.tk                     |  40
code/tur.turczyn_0_1/A.cpp.tk                       |  60
code/tur.turczyn_1_1/B.cpp.tk                       |  73
code/tur.turczyn_2_1/C.cpp.tk                       |  61
code/Tyg3R_0_1/A.cpp.tk                             |  19
code/Tyg3R_1_1/B.cpp.tk                             |  17
code/Tyg3R_2_1/C.cpp.tk                             |  25
code/UminchuR_0_1/main.cpp.tk                       |  35
code/UminchuR_1_1/main.cpp.tk                       |  35
code/UminchuR_2_1/main.cpp.tk                       |  60
code/wo..._0_1/a.cpp.tk                             |  24
code/wo..._1_1/b.cpp.tk                             |  16
code/wo..._2_1/c.cpp.tk                             |  51
code/yswtt_0_1/A.cpp.tk                             |  42
code/yswtt_1_1/B.cpp.tk                             |  28
code/yswtt_2_1/C.cpp.tk                             |  42
code/ZhSh_0_1/a.cpp.tk                              |  45
code/ZhSh_1_1/b.cpp.tk                              |  69
code/ZhSh_2_1/c.cpp.tk                              |  73
