Begin
Comparing:  code/kevinsogo_0_1/a.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  76
code/551100kk_1_1/B.cpp.tk                          |  36
code/551100kk_2_1/C.cpp.tk                          |  49
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  34
code/achan1058_2_1/source.cpp.tk                    |  56
code/alanubi_0_1/a.cpp.tk                           |  41
code/alanubi_1_1/b.cpp.tk                           |  53
code/alanubi_2_1/c.cpp.tk                           |  88
code/AntiForest_0_1/q1.cpp.tk                       |  128
code/AntiForest_1_1/q2.cpp.tk                       |  21
code/AntiForest_2_1/q3.cpp.tk                       |  70
code/apiad_0_1/A.cpp.tk                             |  25
code/apiad_1_1/B.cpp.tk                             |  36
code/apiad_2_1/C.cpp.tk                             |  37
code/azaky_0_1/A.cpp.tk                             |  99
code/azaky_1_1/B.cpp.tk                             |  44
code/azaky_2_1/C.cpp.tk                             |  72
code/azariamuh_0_1/standing.cpp.tk                  |  34
code/azariamuh_1_1/pancake.cpp.tk                   |  51
code/azariamuh_2_1/dijkstra.cpp.tk                  |  30
code/bmerry_0_1/a.cpp.tk                            |  80
code/bmerry_1_1/b.cpp.tk                            |  54
code/bmerry_2_1/c.cpp.tk                            |  56
code/climpet_0_1/A.cpp.tk                           |  27
code/climpet_1_1/B.cpp.tk                           |  30
code/climpet_2_1/C.cpp.tk                           |  47
code/ctzsm_0_1/A.cpp.tk                             |  56
code/ctzsm_1_1/B.cpp.tk                             |  36
code/ctzsm_2_1/C.cpp.tk                             |  82
code/DanilC_0_1/problem.cpp.tk                      |  30
code/DanilC_1_1/problemB.cpp.tk                     |  45
code/DanilC_2_1/problemC.cpp.tk                     |  110
code/DEGwer_0_1/A.cpp.tk                            |  31
code/DEGwer_1_1/B.cpp.tk                            |  33
code/DEGwer_2_1/C.cpp.tk                            |  33
code/dmute_0_1/a.cpp.tk                             |  19
code/dmute_1_1/b.cpp.tk                             |  47
code/dmute_2_1/c2.cpp.tk                            |  54
code/fagu_0_1/A.cpp.tk                              |  13
code/fagu_1_1/B.cpp.tk                              |  12
code/fagu_2_1/C.cpp.tk                              |  46
code/FatalEagle_0_1/main.cpp.tk                     |  30
code/FatalEagle_1_1/main.cpp.tk                     |  32
code/FatalEagle_2_1/main.cpp.tk                     |  156
code/fullpower_0_1/A.cpp.tk                         |  33
code/fullpower_1_1/B.cpp.tk                         |  37
code/fullpower_2_1/C.cpp.tk                         |  75
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  12
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  18
code/ICastro_2_1/Dijkstra.cpp.tk                    |  115
code/ilackthatsuperpower_0_1/a.cpp.tk               |  95
code/ilackthatsuperpower_1_1/b.cpp.tk               |  86
code/ilackthatsuperpower_2_1/c.cpp.tk               |  118
code/iridescent_0_1/A.cpp.tk                        |  10
code/iridescent_1_1/B.cpp.tk                        |  19
code/iridescent_2_1/C.cpp.tk                        |  24
code/ishraq_0_1/main.cpp.tk                         |  46
code/ishraq_1_1/main.cpp.tk                         |  57
code/ishraq_2_1/main.cpp.tk                         |  111
code/JayXon_0_1/A.cpp.tk                            |  60
code/JayXon_1_1/B.cpp.tk                            |  20
code/JayXon_2_1/C.cpp.tk                            |  32
code/Josse_0_1/A.cpp.tk                             |  19
code/Josse_1_1/B.cpp.tk                             |  23
code/Josse_2_1/C.cpp.tk                             |  78
code/kcm1700_0_1/a.cpp.tk                           |  66
code/kcm1700_1_1/b.cpp.tk                           |  58
code/kcm1700_2_1/c.cpp.tk                           |  80
code/kevinsogo_0_1/a.cpp.tk                         |  3637
code/kevinsogo_1_1/b.cpp.tk                         |  172
code/kevinsogo_2_1/c.cpp.tk                         |  112
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  13
code/LazyAnna_0_1/1.cpp.tk                          |  24
code/LazyAnna_1_1/2-1.cpp.tk                        |  17
code/LazyAnna_2_1/3.cpp.tk                          |  33
code/Merkurev_0_1/A.cpp.tk                          |  57
code/Merkurev_1_1/B.cpp.tk                          |  47
code/Merkurev_2_1/C.cpp.tk                          |  48
code/mezei_0_1/main.cpp.tk                          |  32
code/mezei_1_1/main.cpp.tk                          |  21
code/mezei_2_1/main.cpp.tk                          |  61
code/Mister_0_1/a.cpp.tk                            |  58
code/Mister_1_1/b.cpp.tk                            |  55
code/Mister_2_1/c.cpp.tk                            |  41
code/namonakiacc_0_1/cpp.cpp.tk                     |  34
code/namonakiacc_1_1/cpp.cpp.tk                     |  47
code/namonakiacc_2_1/cpp.cpp.tk                     |  79
code/Nicolas16_0_1/main.cpp.tk                      |  14
code/Nicolas16_1_1/main.cpp.tk                      |  13
code/Nicolas16_2_1/main.cpp.tk                      |  66
code/pandamonium_0_1/a.cpp.tk                       |  21
code/pandamonium_1_1/b.cpp.tk                       |  44
code/pandamonium_2_1/c.cpp.tk                       |  34
code/pflueger_0_1/A.cpp.tk                          |  12
code/pflueger_1_1/B.cpp.tk                          |  17
code/pflueger_2_1/C.cpp.tk                          |  46
code/ponyopoppo_0_1/A.cpp.tk                        |  37
code/ponyopoppo_1_1/B.cpp.tk                        |  32
code/ponyopoppo_2_1/C.cpp.tk                        |  128
code/Ragnar_0_1/A.cpp.tk                            |  41
code/Ragnar_1_1/B-2.cpp.tk                          |  28
code/Ragnar_2_1/C.cpp.tk                            |  39
code/saffah_0_1/t.cpp.tk                            |  100
code/saffah_1_1/t.cpp.tk                            |  74
code/saffah_2_1/t.cpp.tk                            |  97
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  13
code/SamanSami_2_1/C.cpp.tk                         |  11
code/Savlik_0_1/code.cpp.tk                         |  45
code/Savlik_1_1/code.cpp.tk                         |  23
code/Savlik_2_1/code.cpp.tk                         |  59
code/shik_0_1/pa.cpp.tk                             |  166
code/shik_1_1/pb.cpp.tk                             |  69
code/shik_2_1/pc.cpp.tk                             |  110
code/simsa.st_0_1/A.cpp.tk                          |  31
code/simsa.st_1_1/B.cpp.tk                          |  61
code/simsa.st_2_1/C.cpp.tk                          |  103
code/SovietUnion_0_1/A.cpp.tk                       |  34
code/SovietUnion_1_1/B.cpp.tk                       |  31
code/SovietUnion_2_1/C.cpp.tk                       |  60
code/tailed_0_1/A.cpp.tk                            |  44
code/tailed_1_1/B.cpp.tk                            |  17
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  85
code/TheNatural_1_1/B.cpp.tk                        |  15
code/TheNatural_2_1/C.cpp.tk                        |  21
code/TrueBamboo_0_1/test.cpp.tk                     |  21
code/TrueBamboo_1_1/test.cpp.tk                     |  23
code/TrueBamboo_2_1/test.cpp.tk                     |  43
code/tur.turczyn_0_1/A.cpp.tk                       |  15
code/tur.turczyn_1_1/B.cpp.tk                       |  29
code/tur.turczyn_2_1/C.cpp.tk                       |  28
code/Tyg3R_0_1/A.cpp.tk                             |  19
code/Tyg3R_1_1/B.cpp.tk                             |  31
code/Tyg3R_2_1/C.cpp.tk                             |  33
code/UminchuR_0_1/main.cpp.tk                       |  40
code/UminchuR_1_1/main.cpp.tk                       |  63
code/UminchuR_2_1/main.cpp.tk                       |  75
code/wo..._0_1/a.cpp.tk                             |  37
code/wo..._1_1/b.cpp.tk                             |  35
code/wo..._2_1/c.cpp.tk                             |  73
code/yswtt_0_1/A.cpp.tk                             |  41
code/yswtt_1_1/B.cpp.tk                             |  22
code/yswtt_2_1/C.cpp.tk                             |  36
code/ZhSh_0_1/a.cpp.tk                              |  13
code/ZhSh_1_1/b.cpp.tk                              |  59
code/ZhSh_2_1/c.cpp.tk                              |  70
