Begin
Comparing:  code/namonakiacc_0_1/cpp.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  20
code/551100kk_1_1/B.cpp.tk                          |  22
code/551100kk_2_1/C.cpp.tk                          |  25
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  73
code/achan1058_2_1/source.cpp.tk                    |  84
code/alanubi_0_1/a.cpp.tk                           |  14
code/alanubi_1_1/b.cpp.tk                           |  19
code/alanubi_2_1/c.cpp.tk                           |  74
code/AntiForest_0_1/q1.cpp.tk                       |  31
code/AntiForest_1_1/q2.cpp.tk                       |  17
code/AntiForest_2_1/q3.cpp.tk                       |  43
code/apiad_0_1/A.cpp.tk                             |  34
code/apiad_1_1/B.cpp.tk                             |  33
code/apiad_2_1/C.cpp.tk                             |  34
code/azaky_0_1/A.cpp.tk                             |  33
code/azaky_1_1/B.cpp.tk                             |  34
code/azaky_2_1/C.cpp.tk                             |  53
code/azariamuh_0_1/standing.cpp.tk                  |  25
code/azariamuh_1_1/pancake.cpp.tk                   |  34
code/azariamuh_2_1/dijkstra.cpp.tk                  |  21
code/bmerry_0_1/a.cpp.tk                            |  56
code/bmerry_1_1/b.cpp.tk                            |  57
code/bmerry_2_1/c.cpp.tk                            |  59
code/climpet_0_1/A.cpp.tk                           |  60
code/climpet_1_1/B.cpp.tk                           |  60
code/climpet_2_1/C.cpp.tk                           |  71
code/ctzsm_0_1/A.cpp.tk                             |  16
code/ctzsm_1_1/B.cpp.tk                             |  21
code/ctzsm_2_1/C.cpp.tk                             |  48
code/DanilC_0_1/problem.cpp.tk                      |  19
code/DanilC_1_1/problemB.cpp.tk                     |  27
code/DanilC_2_1/problemC.cpp.tk                     |  60
code/DEGwer_0_1/A.cpp.tk                            |  20
code/DEGwer_1_1/B.cpp.tk                            |  22
code/DEGwer_2_1/C.cpp.tk                            |  21
code/dmute_0_1/a.cpp.tk                             |  36
code/dmute_1_1/b.cpp.tk                             |  17
code/dmute_2_1/c2.cpp.tk                            |  32
code/fagu_0_1/A.cpp.tk                              |  39
code/fagu_1_1/B.cpp.tk                              |  34
code/fagu_2_1/C.cpp.tk                              |  43
code/FatalEagle_0_1/main.cpp.tk                     |  21
code/FatalEagle_1_1/main.cpp.tk                     |  20
code/FatalEagle_2_1/main.cpp.tk                     |  81
code/fullpower_0_1/A.cpp.tk                         |  22
code/fullpower_1_1/B.cpp.tk                         |  25
code/fullpower_2_1/C.cpp.tk                         |  46
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  11
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  14
code/ICastro_2_1/Dijkstra.cpp.tk                    |  58
code/ilackthatsuperpower_0_1/a.cpp.tk               |  52
code/ilackthatsuperpower_1_1/b.cpp.tk               |  50
code/ilackthatsuperpower_2_1/c.cpp.tk               |  64
code/iridescent_0_1/A.cpp.tk                        |  12
code/iridescent_1_1/B.cpp.tk                        |  11
code/iridescent_2_1/C.cpp.tk                        |  14
code/ishraq_0_1/main.cpp.tk                         |  27
code/ishraq_1_1/main.cpp.tk                         |  24
code/ishraq_2_1/main.cpp.tk                         |  54
code/JayXon_0_1/A.cpp.tk                            |  9
code/JayXon_1_1/B.cpp.tk                            |  13
code/JayXon_2_1/C.cpp.tk                            |  19
code/Josse_0_1/A.cpp.tk                             |  12
code/Josse_1_1/B.cpp.tk                             |  13
code/Josse_2_1/C.cpp.tk                             |  51
code/kcm1700_0_1/a.cpp.tk                           |  20
code/kcm1700_1_1/b.cpp.tk                           |  19
code/kcm1700_2_1/c.cpp.tk                           |  33
code/kevinsogo_0_1/a.cpp.tk                         |  13
code/kevinsogo_1_1/b.cpp.tk                         |  16
code/kevinsogo_2_1/c.cpp.tk                         |  36
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  8
code/LazyAnna_0_1/1.cpp.tk                          |  7
code/LazyAnna_1_1/2-1.cpp.tk                        |  10
code/LazyAnna_2_1/3.cpp.tk                          |  20
code/Merkurev_0_1/A.cpp.tk                          |  21
code/Merkurev_1_1/B.cpp.tk                          |  27
code/Merkurev_2_1/C.cpp.tk                          |  28
code/mezei_0_1/main.cpp.tk                          |  18
code/mezei_1_1/main.cpp.tk                          |  15
code/mezei_2_1/main.cpp.tk                          |  38
code/Mister_0_1/a.cpp.tk                            |  14
code/Mister_1_1/b.cpp.tk                            |  16
code/Mister_2_1/c.cpp.tk                            |  22
code/namonakiacc_0_1/cpp.cpp.tk                     |  19090
code/namonakiacc_1_1/cpp.cpp.tk                     |  5445
code/namonakiacc_2_1/cpp.cpp.tk                     |  5345
code/Nicolas16_0_1/main.cpp.tk                      |  8
code/Nicolas16_1_1/main.cpp.tk                      |  7
code/Nicolas16_2_1/main.cpp.tk                      |  40
code/pandamonium_0_1/a.cpp.tk                       |  22
code/pandamonium_1_1/b.cpp.tk                       |  27
code/pandamonium_2_1/c.cpp.tk                       |  20
code/pflueger_0_1/A.cpp.tk                          |  8
code/pflueger_1_1/B.cpp.tk                          |  12
code/pflueger_2_1/C.cpp.tk                          |  31
code/ponyopoppo_0_1/A.cpp.tk                        |  14
code/ponyopoppo_1_1/B.cpp.tk                        |  18
code/ponyopoppo_2_1/C.cpp.tk                        |  54
code/Ragnar_0_1/A.cpp.tk                            |  44
code/Ragnar_1_1/B-2.cpp.tk                          |  46
code/Ragnar_2_1/C.cpp.tk                            |  53
code/saffah_0_1/t.cpp.tk                            |  15
code/saffah_1_1/t.cpp.tk                            |  20
code/saffah_2_1/t.cpp.tk                            |  48
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  11
code/SamanSami_2_1/C.cpp.tk                         |  6
code/Savlik_0_1/code.cpp.tk                         |  9
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  36
code/shik_0_1/pa.cpp.tk                             |  52
code/shik_1_1/pb.cpp.tk                             |  52
code/shik_2_1/pc.cpp.tk                             |  68
code/simsa.st_0_1/A.cpp.tk                          |  22
code/simsa.st_1_1/B.cpp.tk                          |  17
code/simsa.st_2_1/C.cpp.tk                          |  44
code/SovietUnion_0_1/A.cpp.tk                       |  17
code/SovietUnion_1_1/B.cpp.tk                       |  19
code/SovietUnion_2_1/C.cpp.tk                       |  36
code/tailed_0_1/A.cpp.tk                            |  12
code/tailed_1_1/B.cpp.tk                            |  12
code/tailed_2_1/C.cpp.tk                            |  22
code/TheNatural_0_1/A.cpp.tk                        |  11
code/TheNatural_1_1/B.cpp.tk                        |  14
code/TheNatural_2_1/C.cpp.tk                        |  16
code/TrueBamboo_0_1/test.cpp.tk                     |  12
code/TrueBamboo_1_1/test.cpp.tk                     |  14
code/TrueBamboo_2_1/test.cpp.tk                     |  25
code/tur.turczyn_0_1/A.cpp.tk                       |  67
code/tur.turczyn_1_1/B.cpp.tk                       |  64
code/tur.turczyn_2_1/C.cpp.tk                       |  66
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  12
code/Tyg3R_2_1/C.cpp.tk                             |  13
code/UminchuR_0_1/main.cpp.tk                       |  71
code/UminchuR_1_1/main.cpp.tk                       |  76
code/UminchuR_2_1/main.cpp.tk                       |  86
code/wo..._0_1/a.cpp.tk                             |  19
code/wo..._1_1/b.cpp.tk                             |  18
code/wo..._2_1/c.cpp.tk                             |  38
code/yswtt_0_1/A.cpp.tk                             |  7
code/yswtt_1_1/B.cpp.tk                             |  10
code/yswtt_2_1/C.cpp.tk                             |  19
code/ZhSh_0_1/a.cpp.tk                              |  10
code/ZhSh_1_1/b.cpp.tk                              |  54
code/ZhSh_2_1/c.cpp.tk                              |  60
