Begin
Comparing:  code/yswtt_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  11
code/551100kk_1_1/B.cpp.tk                          |  18
code/551100kk_2_1/C.cpp.tk                          |  38
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  16
code/achan1058_2_1/source.cpp.tk                    |  45
code/alanubi_0_1/a.cpp.tk                           |  17
code/alanubi_1_1/b.cpp.tk                           |  19
code/alanubi_2_1/c.cpp.tk                           |  79
code/AntiForest_0_1/q1.cpp.tk                       |  11
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  52
code/apiad_0_1/A.cpp.tk                             |  13
code/apiad_1_1/B.cpp.tk                             |  15
code/apiad_2_1/C.cpp.tk                             |  24
code/azaky_0_1/A.cpp.tk                             |  11
code/azaky_1_1/B.cpp.tk                             |  13
code/azaky_2_1/C.cpp.tk                             |  38
code/azariamuh_0_1/standing.cpp.tk                  |  12
code/azariamuh_1_1/pancake.cpp.tk                   |  17
code/azariamuh_2_1/dijkstra.cpp.tk                  |  21
code/bmerry_0_1/a.cpp.tk                            |  41
code/bmerry_1_1/b.cpp.tk                            |  43
code/bmerry_2_1/c.cpp.tk                            |  48
code/climpet_0_1/A.cpp.tk                           |  39
code/climpet_1_1/B.cpp.tk                           |  35
code/climpet_2_1/C.cpp.tk                           |  61
code/ctzsm_0_1/A.cpp.tk                             |  22
code/ctzsm_1_1/B.cpp.tk                             |  23
code/ctzsm_2_1/C.cpp.tk                             |  77
code/DanilC_0_1/problem.cpp.tk                      |  37
code/DanilC_1_1/problemB.cpp.tk                     |  44
code/DanilC_2_1/problemC.cpp.tk                     |  78
code/DEGwer_0_1/A.cpp.tk                            |  21
code/DEGwer_1_1/B.cpp.tk                            |  26
code/DEGwer_2_1/C.cpp.tk                            |  28
code/dmute_0_1/a.cpp.tk                             |  13
code/dmute_1_1/b.cpp.tk                             |  26
code/dmute_2_1/c2.cpp.tk                            |  52
code/fagu_0_1/A.cpp.tk                              |  6
code/fagu_1_1/B.cpp.tk                              |  6
code/fagu_2_1/C.cpp.tk                              |  25
code/FatalEagle_0_1/main.cpp.tk                     |  15
code/FatalEagle_1_1/main.cpp.tk                     |  29
code/FatalEagle_2_1/main.cpp.tk                     |  119
code/fullpower_0_1/A.cpp.tk                         |  22
code/fullpower_1_1/B.cpp.tk                         |  34
code/fullpower_2_1/C.cpp.tk                         |  89
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  24
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  26
code/ICastro_2_1/Dijkstra.cpp.tk                    |  72
code/ilackthatsuperpower_0_1/a.cpp.tk               |  63
code/ilackthatsuperpower_1_1/b.cpp.tk               |  60
code/ilackthatsuperpower_2_1/c.cpp.tk               |  89
code/iridescent_0_1/A.cpp.tk                        |  26
code/iridescent_1_1/B.cpp.tk                        |  44
code/iridescent_2_1/C.cpp.tk                        |  44
code/ishraq_0_1/main.cpp.tk                         |  8
code/ishraq_1_1/main.cpp.tk                         |  14
code/ishraq_2_1/main.cpp.tk                         |  41
code/JayXon_0_1/A.cpp.tk                            |  9
code/JayXon_1_1/B.cpp.tk                            |  22
code/JayXon_2_1/C.cpp.tk                            |  41
code/Josse_0_1/A.cpp.tk                             |  20
code/Josse_1_1/B.cpp.tk                             |  28
code/Josse_2_1/C.cpp.tk                             |  63
code/kcm1700_0_1/a.cpp.tk                           |  17
code/kcm1700_1_1/b.cpp.tk                           |  21
code/kcm1700_2_1/c.cpp.tk                           |  51
code/kevinsogo_0_1/a.cpp.tk                         |  9
code/kevinsogo_1_1/b.cpp.tk                         |  13
code/kevinsogo_2_1/c.cpp.tk                         |  37
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  24
code/LazyAnna_0_1/1.cpp.tk                          |  28
code/LazyAnna_1_1/2-1.cpp.tk                        |  28
code/LazyAnna_2_1/3.cpp.tk                          |  35
code/Merkurev_0_1/A.cpp.tk                          |  22
code/Merkurev_1_1/B.cpp.tk                          |  31
code/Merkurev_2_1/C.cpp.tk                          |  34
code/mezei_0_1/main.cpp.tk                          |  21
code/mezei_1_1/main.cpp.tk                          |  19
code/mezei_2_1/main.cpp.tk                          |  71
code/Mister_0_1/a.cpp.tk                            |  20
code/Mister_1_1/b.cpp.tk                            |  22
code/Mister_2_1/c.cpp.tk                            |  40
code/namonakiacc_0_1/cpp.cpp.tk                     |  13
code/namonakiacc_1_1/cpp.cpp.tk                     |  14
code/namonakiacc_2_1/cpp.cpp.tk                     |  39
code/Nicolas16_0_1/main.cpp.tk                      |  6
code/Nicolas16_1_1/main.cpp.tk                      |  6
code/Nicolas16_2_1/main.cpp.tk                      |  82
code/pandamonium_0_1/a.cpp.tk                       |  14
code/pandamonium_1_1/b.cpp.tk                       |  32
code/pandamonium_2_1/c.cpp.tk                       |  27
code/pflueger_0_1/A.cpp.tk                          |  41
code/pflueger_1_1/B.cpp.tk                          |  32
code/pflueger_2_1/C.cpp.tk                          |  81
code/ponyopoppo_0_1/A.cpp.tk                        |  11
code/ponyopoppo_1_1/B.cpp.tk                        |  16
code/ponyopoppo_2_1/C.cpp.tk                        |  98
code/Ragnar_0_1/A.cpp.tk                            |  12
code/Ragnar_1_1/B-2.cpp.tk                          |  15
code/Ragnar_2_1/C.cpp.tk                            |  39
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  10
code/saffah_2_1/t.cpp.tk                            |  50
code/SamanSami_0_1/A.cpp.tk                         |  8
code/SamanSami_1_1/B.cpp.tk                         |  28
code/SamanSami_2_1/C.cpp.tk                         |  11
code/Savlik_0_1/code.cpp.tk                         |  14
code/Savlik_1_1/code.cpp.tk                         |  7
code/Savlik_2_1/code.cpp.tk                         |  59
code/shik_0_1/pa.cpp.tk                             |  36
code/shik_1_1/pb.cpp.tk                             |  37
code/shik_2_1/pc.cpp.tk                             |  69
code/simsa.st_0_1/A.cpp.tk                          |  9
code/simsa.st_1_1/B.cpp.tk                          |  9
code/simsa.st_2_1/C.cpp.tk                          |  53
code/SovietUnion_0_1/A.cpp.tk                       |  26
code/SovietUnion_1_1/B.cpp.tk                       |  36
code/SovietUnion_2_1/C.cpp.tk                       |  61
code/tailed_0_1/A.cpp.tk                            |  19
code/tailed_1_1/B.cpp.tk                            |  24
code/tailed_2_1/C.cpp.tk                            |  52
code/TheNatural_0_1/A.cpp.tk                        |  24
code/TheNatural_1_1/B.cpp.tk                        |  28
code/TheNatural_2_1/C.cpp.tk                        |  27
code/TrueBamboo_0_1/test.cpp.tk                     |  12
code/TrueBamboo_1_1/test.cpp.tk                     |  18
code/TrueBamboo_2_1/test.cpp.tk                     |  47
code/tur.turczyn_0_1/A.cpp.tk                       |  11
code/tur.turczyn_1_1/B.cpp.tk                       |  15
code/tur.turczyn_2_1/C.cpp.tk                       |  24
code/Tyg3R_0_1/A.cpp.tk                             |  10
code/Tyg3R_1_1/B.cpp.tk                             |  12
code/Tyg3R_2_1/C.cpp.tk                             |  37
code/UminchuR_0_1/main.cpp.tk                       |  16
code/UminchuR_1_1/main.cpp.tk                       |  17
code/UminchuR_2_1/main.cpp.tk                       |  45
code/wo..._0_1/a.cpp.tk                             |  19
code/wo..._1_1/b.cpp.tk                             |  25
code/wo..._2_1/c.cpp.tk                             |  72
code/yswtt_0_1/A.cpp.tk                             |  34
code/yswtt_1_1/B.cpp.tk                             |  51
code/yswtt_2_1/C.cpp.tk                             |  55579
code/ZhSh_0_1/a.cpp.tk                              |  51
code/ZhSh_1_1/b.cpp.tk                              |  64
code/ZhSh_2_1/c.cpp.tk                              |  81
