Begin
Comparing:  code/pandamonium_1_1/b.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  18
code/551100kk_1_1/B.cpp.tk                          |  82
code/551100kk_2_1/C.cpp.tk                          |  54
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  19
code/achan1058_2_1/source.cpp.tk                    |  47
code/alanubi_0_1/a.cpp.tk                           |  57
code/alanubi_1_1/b.cpp.tk                           |  126
code/alanubi_2_1/c.cpp.tk                           |  163
code/AntiForest_0_1/q1.cpp.tk                       |  19
code/AntiForest_1_1/q2.cpp.tk                       |  10
code/AntiForest_2_1/q3.cpp.tk                       |  68
code/apiad_0_1/A.cpp.tk                             |  15
code/apiad_1_1/B.cpp.tk                             |  24
code/apiad_2_1/C.cpp.tk                             |  39
code/azaky_0_1/A.cpp.tk                             |  18
code/azaky_1_1/B.cpp.tk                             |  27
code/azaky_2_1/C.cpp.tk                             |  56
code/azariamuh_0_1/standing.cpp.tk                  |  14
code/azariamuh_1_1/pancake.cpp.tk                   |  50
code/azariamuh_2_1/dijkstra.cpp.tk                  |  23
code/bmerry_0_1/a.cpp.tk                            |  65
code/bmerry_1_1/b.cpp.tk                            |  109
code/bmerry_2_1/c.cpp.tk                            |  91
code/climpet_0_1/A.cpp.tk                           |  31
code/climpet_1_1/B.cpp.tk                           |  44
code/climpet_2_1/C.cpp.tk                           |  67
code/ctzsm_0_1/A.cpp.tk                             |  35
code/ctzsm_1_1/B.cpp.tk                             |  60
code/ctzsm_2_1/C.cpp.tk                             |  115
code/DanilC_0_1/problem.cpp.tk                      |  36
code/DanilC_1_1/problemB.cpp.tk                     |  64
code/DanilC_2_1/problemC.cpp.tk                     |  112
code/DEGwer_0_1/A.cpp.tk                            |  60
code/DEGwer_1_1/B.cpp.tk                            |  76
code/DEGwer_2_1/C.cpp.tk                            |  68
code/dmute_0_1/a.cpp.tk                             |  39
code/dmute_1_1/b.cpp.tk                             |  66
code/dmute_2_1/c2.cpp.tk                            |  119
code/fagu_0_1/A.cpp.tk                              |  36
code/fagu_1_1/B.cpp.tk                              |  36
code/fagu_2_1/C.cpp.tk                              |  75
code/FatalEagle_0_1/main.cpp.tk                     |  48
code/FatalEagle_1_1/main.cpp.tk                     |  104
code/FatalEagle_2_1/main.cpp.tk                     |  391
code/fullpower_0_1/A.cpp.tk                         |  74
code/fullpower_1_1/B.cpp.tk                         |  149
code/fullpower_2_1/C.cpp.tk                         |  171
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  18
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  39
code/ICastro_2_1/Dijkstra.cpp.tk                    |  96
code/ilackthatsuperpower_0_1/a.cpp.tk               |  94
code/ilackthatsuperpower_1_1/b.cpp.tk               |  109
code/ilackthatsuperpower_2_1/c.cpp.tk               |  116
code/iridescent_0_1/A.cpp.tk                        |  24
code/iridescent_1_1/B.cpp.tk                        |  45
code/iridescent_2_1/C.cpp.tk                        |  53
code/ishraq_0_1/main.cpp.tk                         |  12
code/ishraq_1_1/main.cpp.tk                         |  25
code/ishraq_2_1/main.cpp.tk                         |  73
code/JayXon_0_1/A.cpp.tk                            |  16
code/JayXon_1_1/B.cpp.tk                            |  68
code/JayXon_2_1/C.cpp.tk                            |  34
code/Josse_0_1/A.cpp.tk                             |  42
code/Josse_1_1/B.cpp.tk                             |  91
code/Josse_2_1/C.cpp.tk                             |  153
code/kcm1700_0_1/a.cpp.tk                           |  48
code/kcm1700_1_1/b.cpp.tk                           |  138
code/kcm1700_2_1/c.cpp.tk                           |  124
code/kevinsogo_0_1/a.cpp.tk                         |  14
code/kevinsogo_1_1/b.cpp.tk                         |  19
code/kevinsogo_2_1/c.cpp.tk                         |  122
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  14
code/LazyAnna_0_1/1.cpp.tk                          |  18
code/LazyAnna_1_1/2-1.cpp.tk                        |  34
code/LazyAnna_2_1/3.cpp.tk                          |  32
code/Merkurev_0_1/A.cpp.tk                          |  62
code/Merkurev_1_1/B.cpp.tk                          |  122
code/Merkurev_2_1/C.cpp.tk                          |  105
code/mezei_0_1/main.cpp.tk                          |  67
code/mezei_1_1/main.cpp.tk                          |  96
code/mezei_2_1/main.cpp.tk                          |  141
code/Mister_0_1/a.cpp.tk                            |  33
code/Mister_1_1/b.cpp.tk                            |  62
code/Mister_2_1/c.cpp.tk                            |  63
code/namonakiacc_0_1/cpp.cpp.tk                     |  22
code/namonakiacc_1_1/cpp.cpp.tk                     |  26
code/namonakiacc_2_1/cpp.cpp.tk                     |  72
code/Nicolas16_0_1/main.cpp.tk                      |  30
code/Nicolas16_1_1/main.cpp.tk                      |  29
code/Nicolas16_2_1/main.cpp.tk                      |  142
code/pandamonium_0_1/a.cpp.tk                       |  45
code/pandamonium_1_1/b.cpp.tk                       |  32046
code/pandamonium_2_1/c.cpp.tk                       |  79
code/pflueger_0_1/A.cpp.tk                          |  29
code/pflueger_1_1/B.cpp.tk                          |  84
code/pflueger_2_1/C.cpp.tk                          |  128
code/ponyopoppo_0_1/A.cpp.tk                        |  10
code/ponyopoppo_1_1/B.cpp.tk                        |  21
code/ponyopoppo_2_1/C.cpp.tk                        |  99
code/Ragnar_0_1/A.cpp.tk                            |  10
code/Ragnar_1_1/B-2.cpp.tk                          |  35
code/Ragnar_2_1/C.cpp.tk                            |  38
code/saffah_0_1/t.cpp.tk                            |  12
code/saffah_1_1/t.cpp.tk                            |  18
code/saffah_2_1/t.cpp.tk                            |  68
code/SamanSami_0_1/A.cpp.tk                         |  11
code/SamanSami_1_1/B.cpp.tk                         |  56
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  17
code/Savlik_1_1/code.cpp.tk                         |  13
code/Savlik_2_1/code.cpp.tk                         |  55
code/shik_0_1/pa.cpp.tk                             |  45
code/shik_1_1/pb.cpp.tk                             |  50
code/shik_2_1/pc.cpp.tk                             |  92
code/simsa.st_0_1/A.cpp.tk                          |  14
code/simsa.st_1_1/B.cpp.tk                          |  20
code/simsa.st_2_1/C.cpp.tk                          |  66
code/SovietUnion_0_1/A.cpp.tk                       |  43
code/SovietUnion_1_1/B.cpp.tk                       |  52
code/SovietUnion_2_1/C.cpp.tk                       |  55
code/tailed_0_1/A.cpp.tk                            |  17
code/tailed_1_1/B.cpp.tk                            |  28
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  37
code/TheNatural_1_1/B.cpp.tk                        |  66
code/TheNatural_2_1/C.cpp.tk                        |  34
code/TrueBamboo_0_1/test.cpp.tk                     |  22
code/TrueBamboo_1_1/test.cpp.tk                     |  33
code/TrueBamboo_2_1/test.cpp.tk                     |  49
code/tur.turczyn_0_1/A.cpp.tk                       |  8
code/tur.turczyn_1_1/B.cpp.tk                       |  16
code/tur.turczyn_2_1/C.cpp.tk                       |  22
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  20
code/Tyg3R_2_1/C.cpp.tk                             |  24
code/UminchuR_0_1/main.cpp.tk                       |  18
code/UminchuR_1_1/main.cpp.tk                       |  30
code/UminchuR_2_1/main.cpp.tk                       |  62
code/wo..._0_1/a.cpp.tk                             |  77
code/wo..._1_1/b.cpp.tk                             |  87
code/wo..._2_1/c.cpp.tk                             |  136
code/yswtt_0_1/A.cpp.tk                             |  16
code/yswtt_1_1/B.cpp.tk                             |  43
code/yswtt_2_1/C.cpp.tk                             |  41
code/ZhSh_0_1/a.cpp.tk                              |  17
code/ZhSh_1_1/b.cpp.tk                              |  68
code/ZhSh_2_1/c.cpp.tk                              |  82
