Begin
Comparing:  code/alanubi_1_1/b.cpp.tk
code/00/test.cpp.tk                                 |  59
code/01/test.cpp.tk                                 |  60
code/551100kk_0_1/A.cpp.tk                          |  28
code/551100kk_1_1/B.cpp.tk                          |  102
code/551100kk_2_1/C.cpp.tk                          |  100
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  31
code/achan1058_2_1/source.cpp.tk                    |  51
code/alanubi_0_1/a.cpp.tk                           |  312
code/alanubi_1_1/b.cpp.tk                           |  20904
code/alanubi_2_1/c.cpp.tk                           |  423
code/AntiForest_0_1/q1.cpp.tk                       |  33
code/AntiForest_1_1/q2.cpp.tk                       |  15
code/AntiForest_2_1/q3.cpp.tk                       |  85
code/apiad_0_1/A.cpp.tk                             |  25
code/apiad_1_1/B.cpp.tk                             |  39
code/apiad_2_1/C.cpp.tk                             |  48
code/azaky_0_1/A.cpp.tk                             |  33
code/azaky_1_1/B.cpp.tk                             |  58
code/azaky_2_1/C.cpp.tk                             |  80
code/azariamuh_0_1/standing.cpp.tk                  |  25
code/azariamuh_1_1/pancake.cpp.tk                   |  48
code/azariamuh_2_1/dijkstra.cpp.tk                  |  34
code/bmerry_0_1/a.cpp.tk                            |  99
code/bmerry_1_1/b.cpp.tk                            |  164
code/bmerry_2_1/c.cpp.tk                            |  126
code/climpet_0_1/A.cpp.tk                           |  51
code/climpet_1_1/B.cpp.tk                           |  96
code/climpet_2_1/C.cpp.tk                           |  101
code/ctzsm_0_1/A.cpp.tk                             |  69
code/ctzsm_1_1/B.cpp.tk                             |  207
code/ctzsm_2_1/C.cpp.tk                             |  175
code/DanilC_0_1/problem.cpp.tk                      |  58
code/DanilC_1_1/problemB.cpp.tk                     |  129
code/DanilC_2_1/problemC.cpp.tk                     |  135
code/DEGwer_0_1/A.cpp.tk                            |  124
code/DEGwer_1_1/B.cpp.tk                            |  216
code/DEGwer_2_1/C.cpp.tk                            |  135
code/dmute_0_1/a.cpp.tk                             |  56
code/dmute_1_1/b.cpp.tk                             |  133
code/dmute_2_1/c2.cpp.tk                            |  174
code/fagu_0_1/A.cpp.tk                              |  101
code/fagu_1_1/B.cpp.tk                              |  101
code/fagu_2_1/C.cpp.tk                              |  135
code/FatalEagle_0_1/main.cpp.tk                     |  86
code/FatalEagle_1_1/main.cpp.tk                     |  167
code/FatalEagle_2_1/main.cpp.tk                     |  578
code/fullpower_0_1/A.cpp.tk                         |  90
code/fullpower_1_1/B.cpp.tk                         |  161
code/fullpower_2_1/C.cpp.tk                         |  207
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  36
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  81
code/ICastro_2_1/Dijkstra.cpp.tk                    |  139
code/ilackthatsuperpower_0_1/a.cpp.tk               |  151
code/ilackthatsuperpower_1_1/b.cpp.tk               |  149
code/ilackthatsuperpower_2_1/c.cpp.tk               |  175
code/iridescent_0_1/A.cpp.tk                        |  37
code/iridescent_1_1/B.cpp.tk                        |  73
code/iridescent_2_1/C.cpp.tk                        |  102
code/ishraq_0_1/main.cpp.tk                         |  38
code/ishraq_1_1/main.cpp.tk                         |  71
code/ishraq_2_1/main.cpp.tk                         |  106
code/JayXon_0_1/A.cpp.tk                            |  23
code/JayXon_1_1/B.cpp.tk                            |  117
code/JayXon_2_1/C.cpp.tk                            |  38
code/Josse_0_1/A.cpp.tk                             |  97
code/Josse_1_1/B.cpp.tk                             |  185
code/Josse_2_1/C.cpp.tk                             |  269
code/kcm1700_0_1/a.cpp.tk                           |  106
code/kcm1700_1_1/b.cpp.tk                           |  350
code/kcm1700_2_1/c.cpp.tk                           |  212
code/kevinsogo_0_1/a.cpp.tk                         |  46
code/kevinsogo_1_1/b.cpp.tk                         |  61
code/kevinsogo_2_1/c.cpp.tk                         |  97
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  16
code/LazyAnna_0_1/1.cpp.tk                          |  33
code/LazyAnna_1_1/2-1.cpp.tk                        |  72
code/LazyAnna_2_1/3.cpp.tk                          |  46
code/Merkurev_0_1/A.cpp.tk                          |  119
code/Merkurev_1_1/B.cpp.tk                          |  263
code/Merkurev_2_1/C.cpp.tk                          |  174
code/mezei_0_1/main.cpp.tk                          |  88
code/mezei_1_1/main.cpp.tk                          |  149
code/mezei_2_1/main.cpp.tk                          |  273
code/Mister_0_1/a.cpp.tk                            |  89
code/Mister_1_1/b.cpp.tk                            |  153
code/Mister_2_1/c.cpp.tk                            |  111
code/namonakiacc_0_1/cpp.cpp.tk                     |  39
code/namonakiacc_1_1/cpp.cpp.tk                     |  46
code/namonakiacc_2_1/cpp.cpp.tk                     |  81
code/Nicolas16_0_1/main.cpp.tk                      |  47
code/Nicolas16_1_1/main.cpp.tk                      |  42
code/Nicolas16_2_1/main.cpp.tk                      |  223
code/pandamonium_0_1/a.cpp.tk                       |  57
code/pandamonium_1_1/b.cpp.tk                       |  310
code/pandamonium_2_1/c.cpp.tk                       |  124
code/pflueger_0_1/A.cpp.tk                          |  38
code/pflueger_1_1/B.cpp.tk                          |  117
code/pflueger_2_1/C.cpp.tk                          |  172
code/ponyopoppo_0_1/A.cpp.tk                        |  17
code/ponyopoppo_1_1/B.cpp.tk                        |  32
code/ponyopoppo_2_1/C.cpp.tk                        |  111
code/Ragnar_0_1/A.cpp.tk                            |  19
code/Ragnar_1_1/B-2.cpp.tk                          |  67
code/Ragnar_2_1/C.cpp.tk                            |  51
code/saffah_0_1/t.cpp.tk                            |  41
code/saffah_1_1/t.cpp.tk                            |  48
code/saffah_2_1/t.cpp.tk                            |  94
code/SamanSami_0_1/A.cpp.tk                         |  13
code/SamanSami_1_1/B.cpp.tk                         |  121
code/SamanSami_2_1/C.cpp.tk                         |  10
code/Savlik_0_1/code.cpp.tk                         |  24
code/Savlik_1_1/code.cpp.tk                         |  14
code/Savlik_2_1/code.cpp.tk                         |  68
code/shik_0_1/pa.cpp.tk                             |  71
code/shik_1_1/pb.cpp.tk                             |  73
code/shik_2_1/pc.cpp.tk                             |  115
code/simsa.st_0_1/A.cpp.tk                          |  25
code/simsa.st_1_1/B.cpp.tk                          |  67
code/simsa.st_2_1/C.cpp.tk                          |  102
code/SovietUnion_0_1/A.cpp.tk                       |  73
code/SovietUnion_1_1/B.cpp.tk                       |  101
code/SovietUnion_2_1/C.cpp.tk                       |  71
code/tailed_0_1/A.cpp.tk                            |  29
code/tailed_1_1/B.cpp.tk                            |  56
code/tailed_2_1/C.cpp.tk                            |  42
code/TheNatural_0_1/A.cpp.tk                        |  49
code/TheNatural_1_1/B.cpp.tk                        |  138
code/TheNatural_2_1/C.cpp.tk                        |  54
code/TrueBamboo_0_1/test.cpp.tk                     |  32
code/TrueBamboo_1_1/test.cpp.tk                     |  66
code/TrueBamboo_2_1/test.cpp.tk                     |  71
code/tur.turczyn_0_1/A.cpp.tk                       |  18
code/tur.turczyn_1_1/B.cpp.tk                       |  29
code/tur.turczyn_2_1/C.cpp.tk                       |  34
code/Tyg3R_0_1/A.cpp.tk                             |  15
code/Tyg3R_1_1/B.cpp.tk                             |  28
code/Tyg3R_2_1/C.cpp.tk                             |  32
code/UminchuR_0_1/main.cpp.tk                       |  45
code/UminchuR_1_1/main.cpp.tk                       |  70
code/UminchuR_2_1/main.cpp.tk                       |  86
code/wo..._0_1/a.cpp.tk                             |  267
code/wo..._1_1/b.cpp.tk                             |  225
code/wo..._2_1/c.cpp.tk                             |  293
code/yswtt_0_1/A.cpp.tk                             |  29
code/yswtt_1_1/B.cpp.tk                             |  71
code/yswtt_2_1/C.cpp.tk                             |  63
code/ZhSh_0_1/a.cpp.tk                              |  33
code/ZhSh_1_1/b.cpp.tk                              |  119
code/ZhSh_2_1/c.cpp.tk                              |  98
