Begin
Comparing:  code/551100kk_2_1/C.cpp.tk
code/00/test.cpp.tk                                 |  35
code/01/test.cpp.tk                                 |  35
code/551100kk_0_1/A.cpp.tk                          |  91
code/551100kk_1_1/B.cpp.tk                          |  116
code/551100kk_2_1/C.cpp.tk                          |  69932
code/achan1058_0_1/Q-A.cpp.tk                       |  17
code/achan1058_1_1/source.cpp.tk                    |  31
code/achan1058_2_1/source.cpp.tk                    |  98
code/alanubi_0_1/a.cpp.tk                           |  27
code/alanubi_1_1/b.cpp.tk                           |  50
code/alanubi_2_1/c.cpp.tk                           |  149
code/AntiForest_0_1/q1.cpp.tk                       |  44
code/AntiForest_1_1/q2.cpp.tk                       |  25
code/AntiForest_2_1/q3.cpp.tk                       |  496
code/apiad_0_1/A.cpp.tk                             |  30
code/apiad_1_1/B.cpp.tk                             |  37
code/apiad_2_1/C.cpp.tk                             |  97
code/azaky_0_1/A.cpp.tk                             |  32
code/azaky_1_1/B.cpp.tk                             |  40
code/azaky_2_1/C.cpp.tk                             |  150
code/azariamuh_0_1/standing.cpp.tk                  |  23
code/azariamuh_1_1/pancake.cpp.tk                   |  55
code/azariamuh_2_1/dijkstra.cpp.tk                  |  74
code/bmerry_0_1/a.cpp.tk                            |  77
code/bmerry_1_1/b.cpp.tk                            |  92
code/bmerry_2_1/c.cpp.tk                            |  124
code/climpet_0_1/A.cpp.tk                           |  37
code/climpet_1_1/B.cpp.tk                           |  44
code/climpet_2_1/C.cpp.tk                           |  113
code/ctzsm_0_1/A.cpp.tk                             |  38
code/ctzsm_1_1/B.cpp.tk                             |  45
code/ctzsm_2_1/C.cpp.tk                             |  202
code/DanilC_0_1/problem.cpp.tk                      |  40
code/DanilC_1_1/problemB.cpp.tk                     |  67
code/DanilC_2_1/problemC.cpp.tk                     |  175
code/DEGwer_0_1/A.cpp.tk                            |  39
code/DEGwer_1_1/B.cpp.tk                            |  48
code/DEGwer_2_1/C.cpp.tk                            |  437
code/dmute_0_1/a.cpp.tk                             |  21
code/dmute_1_1/b.cpp.tk                             |  35
code/dmute_2_1/c2.cpp.tk                            |  102
code/fagu_0_1/A.cpp.tk                              |  19
code/fagu_1_1/B.cpp.tk                              |  18
code/fagu_2_1/C.cpp.tk                              |  118
code/FatalEagle_0_1/main.cpp.tk                     |  44
code/FatalEagle_1_1/main.cpp.tk                     |  57
code/FatalEagle_2_1/main.cpp.tk                     |  312
code/fullpower_0_1/A.cpp.tk                         |  52
code/fullpower_1_1/B.cpp.tk                         |  67
code/fullpower_2_1/C.cpp.tk                         |  143
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  14
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  26
code/ICastro_2_1/Dijkstra.cpp.tk                    |  194
code/ilackthatsuperpower_0_1/a.cpp.tk               |  125
code/ilackthatsuperpower_1_1/b.cpp.tk               |  129
code/ilackthatsuperpower_2_1/c.cpp.tk               |  206
code/iridescent_0_1/A.cpp.tk                        |  22
code/iridescent_1_1/B.cpp.tk                        |  19
code/iridescent_2_1/C.cpp.tk                        |  96
code/ishraq_0_1/main.cpp.tk                         |  22
code/ishraq_1_1/main.cpp.tk                         |  27
code/ishraq_2_1/main.cpp.tk                         |  125
code/JayXon_0_1/A.cpp.tk                            |  14
code/JayXon_1_1/B.cpp.tk                            |  38
code/JayXon_2_1/C.cpp.tk                            |  73
code/Josse_0_1/A.cpp.tk                             |  24
code/Josse_1_1/B.cpp.tk                             |  39
code/Josse_2_1/C.cpp.tk                             |  156
code/kcm1700_0_1/a.cpp.tk                           |  22
code/kcm1700_1_1/b.cpp.tk                           |  35
code/kcm1700_2_1/c.cpp.tk                           |  124
code/kevinsogo_0_1/a.cpp.tk                         |  22
code/kevinsogo_1_1/b.cpp.tk                         |  28
code/kevinsogo_2_1/c.cpp.tk                         |  117
code/ksun48_0_1/A.cpp.tk                            |  5
code/ksun48_1_1/B.cpp.tk                            |  5
code/ksun48_2_1/C.cpp.tk                            |  68
code/LazyAnna_0_1/1.cpp.tk                          |  12
code/LazyAnna_1_1/2-1.cpp.tk                        |  21
code/LazyAnna_2_1/3.cpp.tk                          |  88
code/Merkurev_0_1/A.cpp.tk                          |  48
code/Merkurev_1_1/B.cpp.tk                          |  78
code/Merkurev_2_1/C.cpp.tk                          |  88
code/mezei_0_1/main.cpp.tk                          |  30
code/mezei_1_1/main.cpp.tk                          |  38
code/mezei_2_1/main.cpp.tk                          |  133
code/Mister_0_1/a.cpp.tk                            |  25
code/Mister_1_1/b.cpp.tk                            |  25
code/Mister_2_1/c.cpp.tk                            |  497
code/namonakiacc_0_1/cpp.cpp.tk                     |  30
code/namonakiacc_1_1/cpp.cpp.tk                     |  37
code/namonakiacc_2_1/cpp.cpp.tk                     |  160
code/Nicolas16_0_1/main.cpp.tk                      |  13
code/Nicolas16_1_1/main.cpp.tk                      |  12
code/Nicolas16_2_1/main.cpp.tk                      |  146
code/pandamonium_0_1/a.cpp.tk                       |  25
code/pandamonium_1_1/b.cpp.tk                       |  72
code/pandamonium_2_1/c.cpp.tk                       |  68
code/pflueger_0_1/A.cpp.tk                          |  14
code/pflueger_1_1/B.cpp.tk                          |  30
code/pflueger_2_1/C.cpp.tk                          |  132
code/ponyopoppo_0_1/A.cpp.tk                        |  15
code/ponyopoppo_1_1/B.cpp.tk                        |  34
code/ponyopoppo_2_1/C.cpp.tk                        |  226
code/Ragnar_0_1/A.cpp.tk                            |  19
code/Ragnar_1_1/B-2.cpp.tk                          |  33
code/Ragnar_2_1/C.cpp.tk                            |  74
code/saffah_0_1/t.cpp.tk                            |  23
code/saffah_1_1/t.cpp.tk                            |  28
code/saffah_2_1/t.cpp.tk                            |  149
code/SamanSami_0_1/A.cpp.tk                         |  5
code/SamanSami_1_1/B.cpp.tk                         |  26
code/SamanSami_2_1/C.cpp.tk                         |  21
code/Savlik_0_1/code.cpp.tk                         |  16
code/Savlik_1_1/code.cpp.tk                         |  22
code/Savlik_2_1/code.cpp.tk                         |  101
code/shik_0_1/pa.cpp.tk                             |  90
code/shik_1_1/pb.cpp.tk                             |  92
code/shik_2_1/pc.cpp.tk                             |  483
code/simsa.st_0_1/A.cpp.tk                          |  23
code/simsa.st_1_1/B.cpp.tk                          |  27
code/simsa.st_2_1/C.cpp.tk                          |  137
code/SovietUnion_0_1/A.cpp.tk                       |  42
code/SovietUnion_1_1/B.cpp.tk                       |  50
code/SovietUnion_2_1/C.cpp.tk                       |  138
code/tailed_0_1/A.cpp.tk                            |  13
code/tailed_1_1/B.cpp.tk                            |  20
code/tailed_2_1/C.cpp.tk                            |  98
code/TheNatural_0_1/A.cpp.tk                        |  17
code/TheNatural_1_1/B.cpp.tk                        |  28
code/TheNatural_2_1/C.cpp.tk                        |  69
code/TrueBamboo_0_1/test.cpp.tk                     |  35
code/TrueBamboo_1_1/test.cpp.tk                     |  58
code/TrueBamboo_2_1/test.cpp.tk                     |  112
code/tur.turczyn_0_1/A.cpp.tk                       |  17
code/tur.turczyn_1_1/B.cpp.tk                       |  27
code/tur.turczyn_2_1/C.cpp.tk                       |  70
code/Tyg3R_0_1/A.cpp.tk                             |  20
code/Tyg3R_1_1/B.cpp.tk                             |  33
code/Tyg3R_2_1/C.cpp.tk                             |  94
code/UminchuR_0_1/main.cpp.tk                       |  47
code/UminchuR_1_1/main.cpp.tk                       |  56
code/UminchuR_2_1/main.cpp.tk                       |  128
code/wo..._0_1/a.cpp.tk                             |  36
code/wo..._1_1/b.cpp.tk                             |  40
code/wo..._2_1/c.cpp.tk                             |  506
code/yswtt_0_1/A.cpp.tk                             |  13
code/yswtt_1_1/B.cpp.tk                             |  25
code/yswtt_2_1/C.cpp.tk                             |  67
code/ZhSh_0_1/a.cpp.tk                              |  11
code/ZhSh_1_1/b.cpp.tk                              |  83
code/ZhSh_2_1/c.cpp.tk                              |  272
