Begin
Comparing:  code/Merkurev_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  51
code/551100kk_1_1/B.cpp.tk                          |  60
code/551100kk_2_1/C.cpp.tk                          |  63
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  14
code/achan1058_2_1/source.cpp.tk                    |  27
code/alanubi_0_1/a.cpp.tk                           |  98
code/alanubi_1_1/b.cpp.tk                           |  80
code/alanubi_2_1/c.cpp.tk                           |  120
code/AntiForest_0_1/q1.cpp.tk                       |  68
code/AntiForest_1_1/q2.cpp.tk                       |  25
code/AntiForest_2_1/q3.cpp.tk                       |  70
code/apiad_0_1/A.cpp.tk                             |  17
code/apiad_1_1/B.cpp.tk                             |  20
code/apiad_2_1/C.cpp.tk                             |  34
code/azaky_0_1/A.cpp.tk                             |  23
code/azaky_1_1/B.cpp.tk                             |  25
code/azaky_2_1/C.cpp.tk                             |  47
code/azariamuh_0_1/standing.cpp.tk                  |  20
code/azariamuh_1_1/pancake.cpp.tk                   |  26
code/azariamuh_2_1/dijkstra.cpp.tk                  |  18
code/bmerry_0_1/a.cpp.tk                            |  104
code/bmerry_1_1/b.cpp.tk                            |  54
code/bmerry_2_1/c.cpp.tk                            |  56
code/climpet_0_1/A.cpp.tk                           |  52
code/climpet_1_1/B.cpp.tk                           |  43
code/climpet_2_1/C.cpp.tk                           |  63
code/ctzsm_0_1/A.cpp.tk                             |  75
code/ctzsm_1_1/B.cpp.tk                             |  83
code/ctzsm_2_1/C.cpp.tk                             |  123
code/DanilC_0_1/problem.cpp.tk                      |  59
code/DanilC_1_1/problemB.cpp.tk                     |  65
code/DanilC_2_1/problemC.cpp.tk                     |  75
code/DEGwer_0_1/A.cpp.tk                            |  84
code/DEGwer_1_1/B.cpp.tk                            |  55
code/DEGwer_2_1/C.cpp.tk                            |  38
code/dmute_0_1/a.cpp.tk                             |  92
code/dmute_1_1/b.cpp.tk                             |  159
code/dmute_2_1/c2.cpp.tk                            |  146
code/fagu_0_1/A.cpp.tk                              |  21
code/fagu_1_1/B.cpp.tk                              |  21
code/fagu_2_1/C.cpp.tk                              |  40
code/FatalEagle_0_1/main.cpp.tk                     |  309
code/FatalEagle_1_1/main.cpp.tk                     |  337
code/FatalEagle_2_1/main.cpp.tk                     |  270
code/fullpower_0_1/A.cpp.tk                         |  290
code/fullpower_1_1/B.cpp.tk                         |  203
code/fullpower_2_1/C.cpp.tk                         |  283
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  39
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  37
code/ICastro_2_1/Dijkstra.cpp.tk                    |  83
code/ilackthatsuperpower_0_1/a.cpp.tk               |  138
code/ilackthatsuperpower_1_1/b.cpp.tk               |  80
code/ilackthatsuperpower_2_1/c.cpp.tk               |  78
code/iridescent_0_1/A.cpp.tk                        |  42
code/iridescent_1_1/B.cpp.tk                        |  105
code/iridescent_2_1/C.cpp.tk                        |  65
code/ishraq_0_1/main.cpp.tk                         |  24
code/ishraq_1_1/main.cpp.tk                         |  41
code/ishraq_2_1/main.cpp.tk                         |  56
code/JayXon_0_1/A.cpp.tk                            |  43
code/JayXon_1_1/B.cpp.tk                            |  56
code/JayXon_2_1/C.cpp.tk                            |  20
code/Josse_0_1/A.cpp.tk                             |  42
code/Josse_1_1/B.cpp.tk                             |  46
code/Josse_2_1/C.cpp.tk                             |  84
code/kcm1700_0_1/a.cpp.tk                           |  167
code/kcm1700_1_1/b.cpp.tk                           |  142
code/kcm1700_2_1/c.cpp.tk                           |  118
code/kevinsogo_0_1/a.cpp.tk                         |  31
code/kevinsogo_1_1/b.cpp.tk                         |  34
code/kevinsogo_2_1/c.cpp.tk                         |  60
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  45
code/LazyAnna_1_1/2-1.cpp.tk                        |  42
code/LazyAnna_2_1/3.cpp.tk                          |  29
code/Merkurev_0_1/A.cpp.tk                          |  11709
code/Merkurev_1_1/B.cpp.tk                          |  303
code/Merkurev_2_1/C.cpp.tk                          |  343
code/mezei_0_1/main.cpp.tk                          |  166
code/mezei_1_1/main.cpp.tk                          |  76
code/mezei_2_1/main.cpp.tk                          |  113
code/Mister_0_1/a.cpp.tk                            |  63
code/Mister_1_1/b.cpp.tk                            |  78
code/Mister_2_1/c.cpp.tk                            |  80
code/namonakiacc_0_1/cpp.cpp.tk                     |  26
code/namonakiacc_1_1/cpp.cpp.tk                     |  24
code/namonakiacc_2_1/cpp.cpp.tk                     |  49
code/Nicolas16_0_1/main.cpp.tk                      |  68
code/Nicolas16_1_1/main.cpp.tk                      |  63
code/Nicolas16_2_1/main.cpp.tk                      |  191
code/pandamonium_0_1/a.cpp.tk                       |  94
code/pandamonium_1_1/b.cpp.tk                       |  104
code/pandamonium_2_1/c.cpp.tk                       |  91
code/pflueger_0_1/A.cpp.tk                          |  83
code/pflueger_1_1/B.cpp.tk                          |  61
code/pflueger_2_1/C.cpp.tk                          |  89
code/ponyopoppo_0_1/A.cpp.tk                        |  15
code/ponyopoppo_1_1/B.cpp.tk                        |  13
code/ponyopoppo_2_1/C.cpp.tk                        |  51
code/Ragnar_0_1/A.cpp.tk                            |  12
code/Ragnar_1_1/B-2.cpp.tk                          |  20
code/Ragnar_2_1/C.cpp.tk                            |  49
code/saffah_0_1/t.cpp.tk                            |  27
code/saffah_1_1/t.cpp.tk                            |  27
code/saffah_2_1/t.cpp.tk                            |  53
code/SamanSami_0_1/A.cpp.tk                         |  28
code/SamanSami_1_1/B.cpp.tk                         |  67
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  59
code/Savlik_1_1/code.cpp.tk                         |  8
code/Savlik_2_1/code.cpp.tk                         |  33
code/shik_0_1/pa.cpp.tk                             |  37
code/shik_1_1/pb.cpp.tk                             |  35
code/shik_2_1/pc.cpp.tk                             |  61
code/simsa.st_0_1/A.cpp.tk                          |  20
code/simsa.st_1_1/B.cpp.tk                          |  37
code/simsa.st_2_1/C.cpp.tk                          |  54
code/SovietUnion_0_1/A.cpp.tk                       |  85
code/SovietUnion_1_1/B.cpp.tk                       |  98
code/SovietUnion_2_1/C.cpp.tk                       |  57
code/tailed_0_1/A.cpp.tk                            |  41
code/tailed_1_1/B.cpp.tk                            |  52
code/tailed_2_1/C.cpp.tk                            |  32
code/TheNatural_0_1/A.cpp.tk                        |  124
code/TheNatural_1_1/B.cpp.tk                        |  88
code/TheNatural_2_1/C.cpp.tk                        |  49
code/TrueBamboo_0_1/test.cpp.tk                     |  43
code/TrueBamboo_1_1/test.cpp.tk                     |  37
code/TrueBamboo_2_1/test.cpp.tk                     |  46
code/tur.turczyn_0_1/A.cpp.tk                       |  11
code/tur.turczyn_1_1/B.cpp.tk                       |  15
code/tur.turczyn_2_1/C.cpp.tk                       |  17
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  23
code/UminchuR_0_1/main.cpp.tk                       |  94
code/UminchuR_1_1/main.cpp.tk                       |  100
code/UminchuR_2_1/main.cpp.tk                       |  86
code/wo..._0_1/a.cpp.tk                             |  123
code/wo..._1_1/b.cpp.tk                             |  116
code/wo..._2_1/c.cpp.tk                             |  159
code/yswtt_0_1/A.cpp.tk                             |  31
code/yswtt_1_1/B.cpp.tk                             |  35
code/yswtt_2_1/C.cpp.tk                             |  49
code/ZhSh_0_1/a.cpp.tk                              |  43
code/ZhSh_1_1/b.cpp.tk                              |  72
code/ZhSh_2_1/c.cpp.tk                              |  59
