Begin
Comparing:  code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  10
code/551100kk_1_1/B.cpp.tk                          |  23
code/551100kk_2_1/C.cpp.tk                          |  31
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  21
code/achan1058_2_1/source.cpp.tk                    |  36
code/alanubi_0_1/a.cpp.tk                           |  29
code/alanubi_1_1/b.cpp.tk                           |  56
code/alanubi_2_1/c.cpp.tk                           |  114
code/AntiForest_0_1/q1.cpp.tk                       |  11
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  43
code/apiad_0_1/A.cpp.tk                             |  12
code/apiad_1_1/B.cpp.tk                             |  20
code/apiad_2_1/C.cpp.tk                             |  21
code/azaky_0_1/A.cpp.tk                             |  13
code/azaky_1_1/B.cpp.tk                             |  22
code/azaky_2_1/C.cpp.tk                             |  40
code/azariamuh_0_1/standing.cpp.tk                  |  10
code/azariamuh_1_1/pancake.cpp.tk                   |  17
code/azariamuh_2_1/dijkstra.cpp.tk                  |  14
code/bmerry_0_1/a.cpp.tk                            |  55
code/bmerry_1_1/b.cpp.tk                            |  121
code/bmerry_2_1/c.cpp.tk                            |  69
code/climpet_0_1/A.cpp.tk                           |  45
code/climpet_1_1/B.cpp.tk                           |  119
code/climpet_2_1/C.cpp.tk                           |  90
code/ctzsm_0_1/A.cpp.tk                             |  29
code/ctzsm_1_1/B.cpp.tk                             |  71
code/ctzsm_2_1/C.cpp.tk                             |  116
code/DanilC_0_1/problem.cpp.tk                      |  51
code/DanilC_1_1/problemB.cpp.tk                     |  175
code/DanilC_2_1/problemC.cpp.tk                     |  117
code/DEGwer_0_1/A.cpp.tk                            |  44
code/DEGwer_1_1/B.cpp.tk                            |  68
code/DEGwer_2_1/C.cpp.tk                            |  38
code/dmute_0_1/a.cpp.tk                             |  22
code/dmute_1_1/b.cpp.tk                             |  46
code/dmute_2_1/c2.cpp.tk                            |  72
code/fagu_0_1/A.cpp.tk                              |  15
code/fagu_1_1/B.cpp.tk                              |  15
code/fagu_2_1/C.cpp.tk                              |  31
code/FatalEagle_0_1/main.cpp.tk                     |  26
code/FatalEagle_1_1/main.cpp.tk                     |  61
code/FatalEagle_2_1/main.cpp.tk                     |  218
code/fullpower_0_1/A.cpp.tk                         |  43
code/fullpower_1_1/B.cpp.tk                         |  80
code/fullpower_2_1/C.cpp.tk                         |  110
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  410
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  10103
code/ICastro_2_1/Dijkstra.cpp.tk                    |  194
code/ilackthatsuperpower_0_1/a.cpp.tk               |  91
code/ilackthatsuperpower_1_1/b.cpp.tk               |  104
code/ilackthatsuperpower_2_1/c.cpp.tk               |  118
code/iridescent_0_1/A.cpp.tk                        |  36
code/iridescent_1_1/B.cpp.tk                        |  68
code/iridescent_2_1/C.cpp.tk                        |  57
code/ishraq_0_1/main.cpp.tk                         |  7
code/ishraq_1_1/main.cpp.tk                         |  26
code/ishraq_2_1/main.cpp.tk                         |  45
code/JayXon_0_1/A.cpp.tk                            |  14
code/JayXon_1_1/B.cpp.tk                            |  48
code/JayXon_2_1/C.cpp.tk                            |  23
code/Josse_0_1/A.cpp.tk                             |  32
code/Josse_1_1/B.cpp.tk                             |  65
code/Josse_2_1/C.cpp.tk                             |  105
code/kcm1700_0_1/a.cpp.tk                           |  24
code/kcm1700_1_1/b.cpp.tk                           |  55
code/kcm1700_2_1/c.cpp.tk                           |  78
code/kevinsogo_0_1/a.cpp.tk                         |  9
code/kevinsogo_1_1/b.cpp.tk                         |  21
code/kevinsogo_2_1/c.cpp.tk                         |  40
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  9
code/LazyAnna_0_1/1.cpp.tk                          |  31
code/LazyAnna_1_1/2-1.cpp.tk                        |  121
code/LazyAnna_2_1/3.cpp.tk                          |  33
code/Merkurev_0_1/A.cpp.tk                          |  38
code/Merkurev_1_1/B.cpp.tk                          |  67
code/Merkurev_2_1/C.cpp.tk                          |  70
code/mezei_0_1/main.cpp.tk                          |  36
code/mezei_1_1/main.cpp.tk                          |  57
code/mezei_2_1/main.cpp.tk                          |  71
code/Mister_0_1/a.cpp.tk                            |  28
code/Mister_1_1/b.cpp.tk                            |  81
code/Mister_2_1/c.cpp.tk                            |  67
code/namonakiacc_0_1/cpp.cpp.tk                     |  20
code/namonakiacc_1_1/cpp.cpp.tk                     |  22
code/namonakiacc_2_1/cpp.cpp.tk                     |  38
code/Nicolas16_0_1/main.cpp.tk                      |  11
code/Nicolas16_1_1/main.cpp.tk                      |  11
code/Nicolas16_2_1/main.cpp.tk                      |  83
code/pandamonium_0_1/a.cpp.tk                       |  23
code/pandamonium_1_1/b.cpp.tk                       |  67
code/pandamonium_2_1/c.cpp.tk                       |  41
code/pflueger_0_1/A.cpp.tk                          |  35
code/pflueger_1_1/B.cpp.tk                          |  72
code/pflueger_2_1/C.cpp.tk                          |  86
code/ponyopoppo_0_1/A.cpp.tk                        |  16
code/ponyopoppo_1_1/B.cpp.tk                        |  27
code/ponyopoppo_2_1/C.cpp.tk                        |  69
code/Ragnar_0_1/A.cpp.tk                            |  18
code/Ragnar_1_1/B-2.cpp.tk                          |  37
code/Ragnar_2_1/C.cpp.tk                            |  41
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  15
code/saffah_2_1/t.cpp.tk                            |  43
code/SamanSami_0_1/A.cpp.tk                         |  16
code/SamanSami_1_1/B.cpp.tk                         |  69
code/SamanSami_2_1/C.cpp.tk                         |  6
code/Savlik_0_1/code.cpp.tk                         |  17
code/Savlik_1_1/code.cpp.tk                         |  9
code/Savlik_2_1/code.cpp.tk                         |  43
code/shik_0_1/pa.cpp.tk                             |  37
code/shik_1_1/pb.cpp.tk                             |  40
code/shik_2_1/pc.cpp.tk                             |  61
code/simsa.st_0_1/A.cpp.tk                          |  8
code/simsa.st_1_1/B.cpp.tk                          |  14
code/simsa.st_2_1/C.cpp.tk                          |  44
code/SovietUnion_0_1/A.cpp.tk                       |  38
code/SovietUnion_1_1/B.cpp.tk                       |  79
code/SovietUnion_2_1/C.cpp.tk                       |  51
code/tailed_0_1/A.cpp.tk                            |  23
code/tailed_1_1/B.cpp.tk                            |  44
code/tailed_2_1/C.cpp.tk                            |  28
code/TheNatural_0_1/A.cpp.tk                        |  40
code/TheNatural_1_1/B.cpp.tk                        |  67
code/TheNatural_2_1/C.cpp.tk                        |  31
code/TrueBamboo_0_1/test.cpp.tk                     |  12
code/TrueBamboo_1_1/test.cpp.tk                     |  26
code/TrueBamboo_2_1/test.cpp.tk                     |  32
code/tur.turczyn_0_1/A.cpp.tk                       |  15
code/tur.turczyn_1_1/B.cpp.tk                       |  28
code/tur.turczyn_2_1/C.cpp.tk                       |  24
code/Tyg3R_0_1/A.cpp.tk                             |  9
code/Tyg3R_1_1/B.cpp.tk                             |  15
code/Tyg3R_2_1/C.cpp.tk                             |  17
code/UminchuR_0_1/main.cpp.tk                       |  17
code/UminchuR_1_1/main.cpp.tk                       |  28
code/UminchuR_2_1/main.cpp.tk                       |  40
code/wo..._0_1/a.cpp.tk                             |  49
code/wo..._1_1/b.cpp.tk                             |  57
code/wo..._2_1/c.cpp.tk                             |  94
code/yswtt_0_1/A.cpp.tk                             |  39
code/yswtt_1_1/B.cpp.tk                             |  133
code/yswtt_2_1/C.cpp.tk                             |  55
code/ZhSh_0_1/a.cpp.tk                              |  41
code/ZhSh_1_1/b.cpp.tk                              |  125
code/ZhSh_2_1/c.cpp.tk                              |  71
