Begin
Comparing:  code/pflueger_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  11
code/551100kk_1_1/B.cpp.tk                          |  21
code/551100kk_2_1/C.cpp.tk                          |  51
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  16
code/achan1058_2_1/source.cpp.tk                    |  57
code/alanubi_0_1/a.cpp.tk                           |  21
code/alanubi_1_1/b.cpp.tk                           |  34
code/alanubi_2_1/c.cpp.tk                           |  99
code/AntiForest_0_1/q1.cpp.tk                       |  10
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  48
code/apiad_0_1/A.cpp.tk                             |  11
code/apiad_1_1/B.cpp.tk                             |  15
code/apiad_2_1/C.cpp.tk                             |  28
code/azaky_0_1/A.cpp.tk                             |  12
code/azaky_1_1/B.cpp.tk                             |  14
code/azaky_2_1/C.cpp.tk                             |  40
code/azariamuh_0_1/standing.cpp.tk                  |  8
code/azariamuh_1_1/pancake.cpp.tk                   |  20
code/azariamuh_2_1/dijkstra.cpp.tk                  |  24
code/bmerry_0_1/a.cpp.tk                            |  50
code/bmerry_1_1/b.cpp.tk                            |  64
code/bmerry_2_1/c.cpp.tk                            |  77
code/climpet_0_1/A.cpp.tk                           |  26
code/climpet_1_1/B.cpp.tk                           |  32
code/climpet_2_1/C.cpp.tk                           |  61
code/ctzsm_0_1/A.cpp.tk                             |  15
code/ctzsm_1_1/B.cpp.tk                             |  23
code/ctzsm_2_1/C.cpp.tk                             |  74
code/DanilC_0_1/problem.cpp.tk                      |  28
code/DanilC_1_1/problemB.cpp.tk                     |  45
code/DanilC_2_1/problemC.cpp.tk                     |  82
code/DEGwer_0_1/A.cpp.tk                            |  29
code/DEGwer_1_1/B.cpp.tk                            |  35
code/DEGwer_2_1/C.cpp.tk                            |  42
code/dmute_0_1/a.cpp.tk                             |  17
code/dmute_1_1/b.cpp.tk                             |  32
code/dmute_2_1/c2.cpp.tk                            |  86
code/fagu_0_1/A.cpp.tk                              |  11
code/fagu_1_1/B.cpp.tk                              |  11
code/fagu_2_1/C.cpp.tk                              |  34
code/FatalEagle_0_1/main.cpp.tk                     |  20
code/FatalEagle_1_1/main.cpp.tk                     |  43
code/FatalEagle_2_1/main.cpp.tk                     |  202
code/fullpower_0_1/A.cpp.tk                         |  31
code/fullpower_1_1/B.cpp.tk                         |  58
code/fullpower_2_1/C.cpp.tk                         |  113
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  16
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  27
code/ICastro_2_1/Dijkstra.cpp.tk                    |  80
code/ilackthatsuperpower_0_1/a.cpp.tk               |  65
code/ilackthatsuperpower_1_1/b.cpp.tk               |  67
code/ilackthatsuperpower_2_1/c.cpp.tk               |  94
code/iridescent_0_1/A.cpp.tk                        |  20
code/iridescent_1_1/B.cpp.tk                        |  36
code/iridescent_2_1/C.cpp.tk                        |  39
code/ishraq_0_1/main.cpp.tk                         |  6
code/ishraq_1_1/main.cpp.tk                         |  13
code/ishraq_2_1/main.cpp.tk                         |  46
code/JayXon_0_1/A.cpp.tk                            |  11
code/JayXon_1_1/B.cpp.tk                            |  49
code/JayXon_2_1/C.cpp.tk                            |  44
code/Josse_0_1/A.cpp.tk                             |  23
code/Josse_1_1/B.cpp.tk                             |  38
code/Josse_2_1/C.cpp.tk                             |  90
code/kcm1700_0_1/a.cpp.tk                           |  17
code/kcm1700_1_1/b.cpp.tk                           |  34
code/kcm1700_2_1/c.cpp.tk                           |  88
code/kevinsogo_0_1/a.cpp.tk                         |  7
code/kevinsogo_1_1/b.cpp.tk                         |  11
code/kevinsogo_2_1/c.cpp.tk                         |  53
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  68
code/LazyAnna_0_1/1.cpp.tk                          |  16
code/LazyAnna_1_1/2-1.cpp.tk                        |  26
code/LazyAnna_2_1/3.cpp.tk                          |  30
code/Merkurev_0_1/A.cpp.tk                          |  27
code/Merkurev_1_1/B.cpp.tk                          |  48
code/Merkurev_2_1/C.cpp.tk                          |  74
code/mezei_0_1/main.cpp.tk                          |  27
code/mezei_1_1/main.cpp.tk                          |  33
code/mezei_2_1/main.cpp.tk                          |  75
code/Mister_0_1/a.cpp.tk                            |  13
code/Mister_1_1/b.cpp.tk                            |  20
code/Mister_2_1/c.cpp.tk                            |  35
code/namonakiacc_0_1/cpp.cpp.tk                     |  14
code/namonakiacc_1_1/cpp.cpp.tk                     |  15
code/namonakiacc_2_1/cpp.cpp.tk                     |  61
code/Nicolas16_0_1/main.cpp.tk                      |  9
code/Nicolas16_1_1/main.cpp.tk                      |  9
code/Nicolas16_2_1/main.cpp.tk                      |  124
code/pandamonium_0_1/a.cpp.tk                       |  19
code/pandamonium_1_1/b.cpp.tk                       |  64
code/pandamonium_2_1/c.cpp.tk                       |  41
code/pflueger_0_1/A.cpp.tk                          |  23
code/pflueger_1_1/B.cpp.tk                          |  43
code/pflueger_2_1/C.cpp.tk                          |  110491
code/ponyopoppo_0_1/A.cpp.tk                        |  10
code/ponyopoppo_1_1/B.cpp.tk                        |  15
code/ponyopoppo_2_1/C.cpp.tk                        |  105
code/Ragnar_0_1/A.cpp.tk                            |  11
code/Ragnar_1_1/B-2.cpp.tk                          |  22
code/Ragnar_2_1/C.cpp.tk                            |  39
code/saffah_0_1/t.cpp.tk                            |  6
code/saffah_1_1/t.cpp.tk                            |  9
code/saffah_2_1/t.cpp.tk                            |  50
code/SamanSami_0_1/A.cpp.tk                         |  14
code/SamanSami_1_1/B.cpp.tk                         |  42
code/SamanSami_2_1/C.cpp.tk                         |  11
code/Savlik_0_1/code.cpp.tk                         |  12
code/Savlik_1_1/code.cpp.tk                         |  8
code/Savlik_2_1/code.cpp.tk                         |  50
code/shik_0_1/pa.cpp.tk                             |  37
code/shik_1_1/pb.cpp.tk                             |  38
code/shik_2_1/pc.cpp.tk                             |  66
code/simsa.st_0_1/A.cpp.tk                          |  7
code/simsa.st_1_1/B.cpp.tk                          |  9
code/simsa.st_2_1/C.cpp.tk                          |  53
code/SovietUnion_0_1/A.cpp.tk                       |  19
code/SovietUnion_1_1/B.cpp.tk                       |  25
code/SovietUnion_2_1/C.cpp.tk                       |  50
code/tailed_0_1/A.cpp.tk                            |  19
code/tailed_1_1/B.cpp.tk                            |  25
code/tailed_2_1/C.cpp.tk                            |  38
code/TheNatural_0_1/A.cpp.tk                        |  33
code/TheNatural_1_1/B.cpp.tk                        |  43
code/TheNatural_2_1/C.cpp.tk                        |  33
code/TrueBamboo_0_1/test.cpp.tk                     |  14
code/TrueBamboo_1_1/test.cpp.tk                     |  21
code/TrueBamboo_2_1/test.cpp.tk                     |  52
code/tur.turczyn_0_1/A.cpp.tk                       |  10
code/tur.turczyn_1_1/B.cpp.tk                       |  14
code/tur.turczyn_2_1/C.cpp.tk                       |  23
code/Tyg3R_0_1/A.cpp.tk                             |  8
code/Tyg3R_1_1/B.cpp.tk                             |  12
code/Tyg3R_2_1/C.cpp.tk                             |  23
code/UminchuR_0_1/main.cpp.tk                       |  17
code/UminchuR_1_1/main.cpp.tk                       |  18
code/UminchuR_2_1/main.cpp.tk                       |  53
code/wo..._0_1/a.cpp.tk                             |  28
code/wo..._1_1/b.cpp.tk                             |  41
code/wo..._2_1/c.cpp.tk                             |  88
code/yswtt_0_1/A.cpp.tk                             |  15
code/yswtt_1_1/B.cpp.tk                             |  28
code/yswtt_2_1/C.cpp.tk                             |  53
code/ZhSh_0_1/a.cpp.tk                              |  16
code/ZhSh_1_1/b.cpp.tk                              |  54
code/ZhSh_2_1/c.cpp.tk                              |  74
