Begin
Comparing:  code/simsa.st_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  24
code/551100kk_1_1/B.cpp.tk                          |  54
code/551100kk_2_1/C.cpp.tk                          |  56
code/achan1058_0_1/Q-A.cpp.tk                       |  18
code/achan1058_1_1/source.cpp.tk                    |  44
code/achan1058_2_1/source.cpp.tk                    |  76
code/alanubi_0_1/a.cpp.tk                           |  34
code/alanubi_1_1/b.cpp.tk                           |  77
code/alanubi_2_1/c.cpp.tk                           |  104
code/AntiForest_0_1/q1.cpp.tk                       |  73
code/AntiForest_1_1/q2.cpp.tk                       |  38
code/AntiForest_2_1/q3.cpp.tk                       |  110
code/apiad_0_1/A.cpp.tk                             |  24
code/apiad_1_1/B.cpp.tk                             |  74
code/apiad_2_1/C.cpp.tk                             |  41
code/azaky_0_1/A.cpp.tk                             |  71
code/azaky_1_1/B.cpp.tk                             |  127
code/azaky_2_1/C.cpp.tk                             |  122
code/azariamuh_0_1/standing.cpp.tk                  |  69
code/azariamuh_1_1/pancake.cpp.tk                   |  76
code/azariamuh_2_1/dijkstra.cpp.tk                  |  52
code/bmerry_0_1/a.cpp.tk                            |  51
code/bmerry_1_1/b.cpp.tk                            |  75
code/bmerry_2_1/c.cpp.tk                            |  59
code/climpet_0_1/A.cpp.tk                           |  30
code/climpet_1_1/B.cpp.tk                           |  89
code/climpet_2_1/C.cpp.tk                           |  56
code/ctzsm_0_1/A.cpp.tk                             |  27
code/ctzsm_1_1/B.cpp.tk                             |  48
code/ctzsm_2_1/C.cpp.tk                             |  97
code/DanilC_0_1/problem.cpp.tk                      |  32
code/DanilC_1_1/problemB.cpp.tk                     |  62
code/DanilC_2_1/problemC.cpp.tk                     |  152
code/DEGwer_0_1/A.cpp.tk                            |  41
code/DEGwer_1_1/B.cpp.tk                            |  78
code/DEGwer_2_1/C.cpp.tk                            |  45
code/dmute_0_1/a.cpp.tk                             |  18
code/dmute_1_1/b.cpp.tk                             |  43
code/dmute_2_1/c2.cpp.tk                            |  54
code/fagu_0_1/A.cpp.tk                              |  15
code/fagu_1_1/B.cpp.tk                              |  15
code/fagu_2_1/C.cpp.tk                              |  59
code/FatalEagle_0_1/main.cpp.tk                     |  32
code/FatalEagle_1_1/main.cpp.tk                     |  44
code/FatalEagle_2_1/main.cpp.tk                     |  175
code/fullpower_0_1/A.cpp.tk                         |  42
code/fullpower_1_1/B.cpp.tk                         |  52
code/fullpower_2_1/C.cpp.tk                         |  83
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  10
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  29
code/ICastro_2_1/Dijkstra.cpp.tk                    |  138
code/ilackthatsuperpower_0_1/a.cpp.tk               |  104
code/ilackthatsuperpower_1_1/b.cpp.tk               |  116
code/ilackthatsuperpower_2_1/c.cpp.tk               |  150
code/iridescent_0_1/A.cpp.tk                        |  11
code/iridescent_1_1/B.cpp.tk                        |  24
code/iridescent_2_1/C.cpp.tk                        |  18
code/ishraq_0_1/main.cpp.tk                         |  56
code/ishraq_1_1/main.cpp.tk                         |  69
code/ishraq_2_1/main.cpp.tk                         |  136
code/JayXon_0_1/A.cpp.tk                            |  7
code/JayXon_1_1/B.cpp.tk                            |  27
code/JayXon_2_1/C.cpp.tk                            |  46
code/Josse_0_1/A.cpp.tk                             |  16
code/Josse_1_1/B.cpp.tk                             |  68
code/Josse_2_1/C.cpp.tk                             |  100
code/kcm1700_0_1/a.cpp.tk                           |  41
code/kcm1700_1_1/b.cpp.tk                           |  57
code/kcm1700_2_1/c.cpp.tk                           |  83
code/kevinsogo_0_1/a.cpp.tk                         |  58
code/kevinsogo_1_1/b.cpp.tk                         |  91
code/kevinsogo_2_1/c.cpp.tk                         |  104
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  16
code/LazyAnna_0_1/1.cpp.tk                          |  12
code/LazyAnna_1_1/2-1.cpp.tk                        |  17
code/LazyAnna_2_1/3.cpp.tk                          |  42
code/Merkurev_0_1/A.cpp.tk                          |  61
code/Merkurev_1_1/B.cpp.tk                          |  66
code/Merkurev_2_1/C.cpp.tk                          |  50
code/mezei_0_1/main.cpp.tk                          |  35
code/mezei_1_1/main.cpp.tk                          |  38
code/mezei_2_1/main.cpp.tk                          |  83
code/Mister_0_1/a.cpp.tk                            |  37
code/Mister_1_1/b.cpp.tk                            |  52
code/Mister_2_1/c.cpp.tk                            |  43
code/namonakiacc_0_1/cpp.cpp.tk                     |  42
code/namonakiacc_1_1/cpp.cpp.tk                     |  78
code/namonakiacc_2_1/cpp.cpp.tk                     |  90
code/Nicolas16_0_1/main.cpp.tk                      |  17
code/Nicolas16_1_1/main.cpp.tk                      |  16
code/Nicolas16_2_1/main.cpp.tk                      |  77
code/pandamonium_0_1/a.cpp.tk                       |  20
code/pandamonium_1_1/b.cpp.tk                       |  61
code/pandamonium_2_1/c.cpp.tk                       |  27
code/pflueger_0_1/A.cpp.tk                          |  13
code/pflueger_1_1/B.cpp.tk                          |  24
code/pflueger_2_1/C.cpp.tk                          |  56
code/ponyopoppo_0_1/A.cpp.tk                        |  19
code/ponyopoppo_1_1/B.cpp.tk                        |  52
code/ponyopoppo_2_1/C.cpp.tk                        |  175
code/Ragnar_0_1/A.cpp.tk                            |  19
code/Ragnar_1_1/B-2.cpp.tk                          |  41
code/Ragnar_2_1/C.cpp.tk                            |  48
code/saffah_0_1/t.cpp.tk                            |  81
code/saffah_1_1/t.cpp.tk                            |  198
code/saffah_2_1/t.cpp.tk                            |  168
code/SamanSami_0_1/A.cpp.tk                         |  4
code/SamanSami_1_1/B.cpp.tk                         |  17
code/SamanSami_2_1/C.cpp.tk                         |  14
code/Savlik_0_1/code.cpp.tk                         |  15
code/Savlik_1_1/code.cpp.tk                         |  54
code/Savlik_2_1/code.cpp.tk                         |  77
code/shik_0_1/pa.cpp.tk                             |  93
code/shik_1_1/pb.cpp.tk                             |  109
code/shik_2_1/pc.cpp.tk                             |  137
code/simsa.st_0_1/A.cpp.tk                          |  43
code/simsa.st_1_1/B.cpp.tk                          |  3676
code/simsa.st_2_1/C.cpp.tk                          |  182
code/SovietUnion_0_1/A.cpp.tk                       |  28
code/SovietUnion_1_1/B.cpp.tk                       |  43
code/SovietUnion_2_1/C.cpp.tk                       |  81
code/tailed_0_1/A.cpp.tk                            |  13
code/tailed_1_1/B.cpp.tk                            |  30
code/tailed_2_1/C.cpp.tk                            |  45
code/TheNatural_0_1/A.cpp.tk                        |  12
code/TheNatural_1_1/B.cpp.tk                        |  22
code/TheNatural_2_1/C.cpp.tk                        |  21
code/TrueBamboo_0_1/test.cpp.tk                     |  21
code/TrueBamboo_1_1/test.cpp.tk                     |  39
code/TrueBamboo_2_1/test.cpp.tk                     |  56
code/tur.turczyn_0_1/A.cpp.tk                       |  17
code/tur.turczyn_1_1/B.cpp.tk                       |  38
code/tur.turczyn_2_1/C.cpp.tk                       |  34
code/Tyg3R_0_1/A.cpp.tk                             |  26
code/Tyg3R_1_1/B.cpp.tk                             |  41
code/Tyg3R_2_1/C.cpp.tk                             |  38
code/UminchuR_0_1/main.cpp.tk                       |  42
code/UminchuR_1_1/main.cpp.tk                       |  108
code/UminchuR_2_1/main.cpp.tk                       |  81
code/wo..._0_1/a.cpp.tk                             |  35
code/wo..._1_1/b.cpp.tk                             |  45
code/wo..._2_1/c.cpp.tk                             |  79
code/yswtt_0_1/A.cpp.tk                             |  10
code/yswtt_1_1/B.cpp.tk                             |  32
code/yswtt_2_1/C.cpp.tk                             |  37
code/ZhSh_0_1/a.cpp.tk                              |  11
code/ZhSh_1_1/b.cpp.tk                              |  81
code/ZhSh_2_1/c.cpp.tk                              |  89
