Begin
Comparing:  code/LazyAnna_1_1/2-1.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  10
code/551100kk_1_1/B.cpp.tk                          |  19
code/551100kk_2_1/C.cpp.tk                          |  27
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  18
code/achan1058_2_1/source.cpp.tk                    |  28
code/alanubi_0_1/a.cpp.tk                           |  30
code/alanubi_1_1/b.cpp.tk                           |  49
code/alanubi_2_1/c.cpp.tk                           |  103
code/AntiForest_0_1/q1.cpp.tk                       |  11
code/AntiForest_1_1/q2.cpp.tk                       |  3
code/AntiForest_2_1/q3.cpp.tk                       |  37
code/apiad_0_1/A.cpp.tk                             |  10
code/apiad_1_1/B.cpp.tk                             |  13
code/apiad_2_1/C.cpp.tk                             |  21
code/azaky_0_1/A.cpp.tk                             |  10
code/azaky_1_1/B.cpp.tk                             |  14
code/azaky_2_1/C.cpp.tk                             |  34
code/azariamuh_0_1/standing.cpp.tk                  |  10
code/azariamuh_1_1/pancake.cpp.tk                   |  19
code/azariamuh_2_1/dijkstra.cpp.tk                  |  17
code/bmerry_0_1/a.cpp.tk                            |  50
code/bmerry_1_1/b.cpp.tk                            |  70
code/bmerry_2_1/c.cpp.tk                            |  64
code/climpet_0_1/A.cpp.tk                           |  67
code/climpet_1_1/B.cpp.tk                           |  117
code/climpet_2_1/C.cpp.tk                           |  102
code/ctzsm_0_1/A.cpp.tk                             |  49
code/ctzsm_1_1/B.cpp.tk                             |  77
code/ctzsm_2_1/C.cpp.tk                             |  114
code/DanilC_0_1/problem.cpp.tk                      |  71
code/DanilC_1_1/problemB.cpp.tk                     |  175
code/DanilC_2_1/problemC.cpp.tk                     |  119
code/DEGwer_0_1/A.cpp.tk                            |  44
code/DEGwer_1_1/B.cpp.tk                            |  55
code/DEGwer_2_1/C.cpp.tk                            |  35
code/dmute_0_1/a.cpp.tk                             |  26
code/dmute_1_1/b.cpp.tk                             |  55
code/dmute_2_1/c2.cpp.tk                            |  78
code/fagu_0_1/A.cpp.tk                              |  13
code/fagu_1_1/B.cpp.tk                              |  16
code/fagu_2_1/C.cpp.tk                              |  27
code/FatalEagle_0_1/main.cpp.tk                     |  29
code/FatalEagle_1_1/main.cpp.tk                     |  65
code/FatalEagle_2_1/main.cpp.tk                     |  206
code/fullpower_0_1/A.cpp.tk                         |  43
code/fullpower_1_1/B.cpp.tk                         |  81
code/fullpower_2_1/C.cpp.tk                         |  120
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  58
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  123
code/ICastro_2_1/Dijkstra.cpp.tk                    |  81
code/ilackthatsuperpower_0_1/a.cpp.tk               |  87
code/ilackthatsuperpower_1_1/b.cpp.tk               |  89
code/ilackthatsuperpower_2_1/c.cpp.tk               |  99
code/iridescent_0_1/A.cpp.tk                        |  35
code/iridescent_1_1/B.cpp.tk                        |  68
code/iridescent_2_1/C.cpp.tk                        |  58
code/ishraq_0_1/main.cpp.tk                         |  9
code/ishraq_1_1/main.cpp.tk                         |  24
code/ishraq_2_1/main.cpp.tk                         |  38
code/JayXon_0_1/A.cpp.tk                            |  15
code/JayXon_1_1/B.cpp.tk                            |  54
code/JayXon_2_1/C.cpp.tk                            |  20
code/Josse_0_1/A.cpp.tk                             |  32
code/Josse_1_1/B.cpp.tk                             |  53
code/Josse_2_1/C.cpp.tk                             |  88
code/kcm1700_0_1/a.cpp.tk                           |  28
code/kcm1700_1_1/b.cpp.tk                           |  54
code/kcm1700_2_1/c.cpp.tk                           |  82
code/kevinsogo_0_1/a.cpp.tk                         |  9
code/kevinsogo_1_1/b.cpp.tk                         |  16
code/kevinsogo_2_1/c.cpp.tk                         |  40
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  10
code/LazyAnna_0_1/1.cpp.tk                          |  77
code/LazyAnna_1_1/2-1.cpp.tk                        |  10320
code/LazyAnna_2_1/3.cpp.tk                          |  47
code/Merkurev_0_1/A.cpp.tk                          |  42
code/Merkurev_1_1/B.cpp.tk                          |  63
code/Merkurev_2_1/C.cpp.tk                          |  71
code/mezei_0_1/main.cpp.tk                          |  43
code/mezei_1_1/main.cpp.tk                          |  48
code/mezei_2_1/main.cpp.tk                          |  66
code/Mister_0_1/a.cpp.tk                            |  44
code/Mister_1_1/b.cpp.tk                            |  71
code/Mister_2_1/c.cpp.tk                            |  85
code/namonakiacc_0_1/cpp.cpp.tk                     |  15
code/namonakiacc_1_1/cpp.cpp.tk                     |  16
code/namonakiacc_2_1/cpp.cpp.tk                     |  36
code/Nicolas16_0_1/main.cpp.tk                      |  18
code/Nicolas16_1_1/main.cpp.tk                      |  21
code/Nicolas16_2_1/main.cpp.tk                      |  92
code/pandamonium_0_1/a.cpp.tk                       |  27
code/pandamonium_1_1/b.cpp.tk                       |  59
code/pandamonium_2_1/c.cpp.tk                       |  44
code/pflueger_0_1/A.cpp.tk                          |  37
code/pflueger_1_1/B.cpp.tk                          |  66
code/pflueger_2_1/C.cpp.tk                          |  90
code/ponyopoppo_0_1/A.cpp.tk                        |  12
code/ponyopoppo_1_1/B.cpp.tk                        |  14
code/ponyopoppo_2_1/C.cpp.tk                        |  54
code/Ragnar_0_1/A.cpp.tk                            |  14
code/Ragnar_1_1/B-2.cpp.tk                          |  25
code/Ragnar_2_1/C.cpp.tk                            |  38
code/saffah_0_1/t.cpp.tk                            |  7
code/saffah_1_1/t.cpp.tk                            |  10
code/saffah_2_1/t.cpp.tk                            |  36
code/SamanSami_0_1/A.cpp.tk                         |  19
code/SamanSami_1_1/B.cpp.tk                         |  67
code/SamanSami_2_1/C.cpp.tk                         |  4
code/Savlik_0_1/code.cpp.tk                         |  19
code/Savlik_1_1/code.cpp.tk                         |  8
code/Savlik_2_1/code.cpp.tk                         |  37
code/shik_0_1/pa.cpp.tk                             |  29
code/shik_1_1/pb.cpp.tk                             |  30
code/shik_2_1/pc.cpp.tk                             |  51
code/simsa.st_0_1/A.cpp.tk                          |  9
code/simsa.st_1_1/B.cpp.tk                          |  10
code/simsa.st_2_1/C.cpp.tk                          |  33
code/SovietUnion_0_1/A.cpp.tk                       |  58
code/SovietUnion_1_1/B.cpp.tk                       |  88
code/SovietUnion_2_1/C.cpp.tk                       |  58
code/tailed_0_1/A.cpp.tk                            |  27
code/tailed_1_1/B.cpp.tk                            |  40
code/tailed_2_1/C.cpp.tk                            |  25
code/TheNatural_0_1/A.cpp.tk                        |  51
code/TheNatural_1_1/B.cpp.tk                        |  70
code/TheNatural_2_1/C.cpp.tk                        |  33
code/TrueBamboo_0_1/test.cpp.tk                     |  16
code/TrueBamboo_1_1/test.cpp.tk                     |  31
code/TrueBamboo_2_1/test.cpp.tk                     |  29
code/tur.turczyn_0_1/A.cpp.tk                       |  12
code/tur.turczyn_1_1/B.cpp.tk                       |  22
code/tur.turczyn_2_1/C.cpp.tk                       |  20
code/Tyg3R_0_1/A.cpp.tk                             |  10
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  20
code/UminchuR_0_1/main.cpp.tk                       |  13
code/UminchuR_1_1/main.cpp.tk                       |  19
code/UminchuR_2_1/main.cpp.tk                       |  38
code/wo..._0_1/a.cpp.tk                             |  47
code/wo..._1_1/b.cpp.tk                             |  63
code/wo..._2_1/c.cpp.tk                             |  100
code/yswtt_0_1/A.cpp.tk                             |  66
code/yswtt_1_1/B.cpp.tk                             |  131
code/yswtt_2_1/C.cpp.tk                             |  64
code/ZhSh_0_1/a.cpp.tk                              |  58
code/ZhSh_1_1/b.cpp.tk                              |  97
code/ZhSh_2_1/c.cpp.tk                              |  78
