Begin
Comparing:  code/Savlik_2_1/code.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  16
code/551100kk_1_1/B.cpp.tk                          |  27
code/551100kk_2_1/C.cpp.tk                          |  50
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  28
code/achan1058_2_1/source.cpp.tk                    |  72
code/alanubi_0_1/a.cpp.tk                           |  12
code/alanubi_1_1/b.cpp.tk                           |  17
code/alanubi_2_1/c.cpp.tk                           |  93
code/AntiForest_0_1/q1.cpp.tk                       |  17
code/AntiForest_1_1/q2.cpp.tk                       |  8
code/AntiForest_2_1/q3.cpp.tk                       |  61
code/apiad_0_1/A.cpp.tk                             |  19
code/apiad_1_1/B.cpp.tk                             |  27
code/apiad_2_1/C.cpp.tk                             |  33
code/azaky_0_1/A.cpp.tk                             |  20
code/azaky_1_1/B.cpp.tk                             |  26
code/azaky_2_1/C.cpp.tk                             |  82
code/azariamuh_0_1/standing.cpp.tk                  |  13
code/azariamuh_1_1/pancake.cpp.tk                   |  28
code/azariamuh_2_1/dijkstra.cpp.tk                  |  28
code/bmerry_0_1/a.cpp.tk                            |  49
code/bmerry_1_1/b.cpp.tk                            |  58
code/bmerry_2_1/c.cpp.tk                            |  59
code/climpet_0_1/A.cpp.tk                           |  33
code/climpet_1_1/B.cpp.tk                           |  38
code/climpet_2_1/C.cpp.tk                           |  63
code/ctzsm_0_1/A.cpp.tk                             |  15
code/ctzsm_1_1/B.cpp.tk                             |  22
code/ctzsm_2_1/C.cpp.tk                             |  95
code/DanilC_0_1/problem.cpp.tk                      |  33
code/DanilC_1_1/problemB.cpp.tk                     |  47
code/DanilC_2_1/problemC.cpp.tk                     |  131
code/DEGwer_0_1/A.cpp.tk                            |  21
code/DEGwer_1_1/B.cpp.tk                            |  24
code/DEGwer_2_1/C.cpp.tk                            |  35
code/dmute_0_1/a.cpp.tk                             |  9
code/dmute_1_1/b.cpp.tk                             |  18
code/dmute_2_1/c2.cpp.tk                            |  48
code/fagu_0_1/A.cpp.tk                              |  7
code/fagu_1_1/B.cpp.tk                              |  7
code/fagu_2_1/C.cpp.tk                              |  37
code/FatalEagle_0_1/main.cpp.tk                     |  14
code/FatalEagle_1_1/main.cpp.tk                     |  23
code/FatalEagle_2_1/main.cpp.tk                     |  159
code/fullpower_0_1/A.cpp.tk                         |  24
code/fullpower_1_1/B.cpp.tk                         |  30
code/fullpower_2_1/C.cpp.tk                         |  83
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  11
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  19
code/ICastro_2_1/Dijkstra.cpp.tk                    |  114
code/ilackthatsuperpower_0_1/a.cpp.tk               |  101
code/ilackthatsuperpower_1_1/b.cpp.tk               |  105
code/ilackthatsuperpower_2_1/c.cpp.tk               |  164
code/iridescent_0_1/A.cpp.tk                        |  10
code/iridescent_1_1/B.cpp.tk                        |  14
code/iridescent_2_1/C.cpp.tk                        |  18
code/ishraq_0_1/main.cpp.tk                         |  10
code/ishraq_1_1/main.cpp.tk                         |  16
code/ishraq_2_1/main.cpp.tk                         |  76
code/JayXon_0_1/A.cpp.tk                            |  8
code/JayXon_1_1/B.cpp.tk                            |  21
code/JayXon_2_1/C.cpp.tk                            |  56
code/Josse_0_1/A.cpp.tk                             |  13
code/Josse_1_1/B.cpp.tk                             |  17
code/Josse_2_1/C.cpp.tk                             |  101
code/kcm1700_0_1/a.cpp.tk                           |  9
code/kcm1700_1_1/b.cpp.tk                           |  15
code/kcm1700_2_1/c.cpp.tk                           |  50
code/kevinsogo_0_1/a.cpp.tk                         |  13
code/kevinsogo_1_1/b.cpp.tk                         |  18
code/kevinsogo_2_1/c.cpp.tk                         |  63
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  19
code/LazyAnna_0_1/1.cpp.tk                          |  9
code/LazyAnna_1_1/2-1.cpp.tk                        |  15
code/LazyAnna_2_1/3.cpp.tk                          |  46
code/Merkurev_0_1/A.cpp.tk                          |  15
code/Merkurev_1_1/B.cpp.tk                          |  33
code/Merkurev_2_1/C.cpp.tk                          |  35
code/mezei_0_1/main.cpp.tk                          |  17
code/mezei_1_1/main.cpp.tk                          |  16
code/mezei_2_1/main.cpp.tk                          |  84
code/Mister_0_1/a.cpp.tk                            |  13
code/Mister_1_1/b.cpp.tk                            |  15
code/Mister_2_1/c.cpp.tk                            |  31
code/namonakiacc_0_1/cpp.cpp.tk                     |  23
code/namonakiacc_1_1/cpp.cpp.tk                     |  28
code/namonakiacc_2_1/cpp.cpp.tk                     |  52
code/Nicolas16_0_1/main.cpp.tk                      |  6
code/Nicolas16_1_1/main.cpp.tk                      |  6
code/Nicolas16_2_1/main.cpp.tk                      |  73
code/pandamonium_0_1/a.cpp.tk                       |  11
code/pandamonium_1_1/b.cpp.tk                       |  36
code/pandamonium_2_1/c.cpp.tk                       |  22
code/pflueger_0_1/A.cpp.tk                          |  10
code/pflueger_1_1/B.cpp.tk                          |  16
code/pflueger_2_1/C.cpp.tk                          |  64
code/ponyopoppo_0_1/A.cpp.tk                        |  14
code/ponyopoppo_1_1/B.cpp.tk                        |  29
code/ponyopoppo_2_1/C.cpp.tk                        |  221
code/Ragnar_0_1/A.cpp.tk                            |  16
code/Ragnar_1_1/B-2.cpp.tk                          |  25
code/Ragnar_2_1/C.cpp.tk                            |  51
code/saffah_0_1/t.cpp.tk                            |  11
code/saffah_1_1/t.cpp.tk                            |  16
code/saffah_2_1/t.cpp.tk                            |  123
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  14
code/SamanSami_2_1/C.cpp.tk                         |  19
code/Savlik_0_1/code.cpp.tk                         |  14
code/Savlik_1_1/code.cpp.tk                         |  19
code/Savlik_2_1/code.cpp.tk                         |  58890
code/shik_0_1/pa.cpp.tk                             |  72
code/shik_1_1/pb.cpp.tk                             |  76
code/shik_2_1/pc.cpp.tk                             |  109
code/simsa.st_0_1/A.cpp.tk                          |  13
code/simsa.st_1_1/B.cpp.tk                          |  17
code/simsa.st_2_1/C.cpp.tk                          |  124
code/SovietUnion_0_1/A.cpp.tk                       |  17
code/SovietUnion_1_1/B.cpp.tk                       |  20
code/SovietUnion_2_1/C.cpp.tk                       |  102
code/tailed_0_1/A.cpp.tk                            |  10
code/tailed_1_1/B.cpp.tk                            |  16
code/tailed_2_1/C.cpp.tk                            |  43
code/TheNatural_0_1/A.cpp.tk                        |  11
code/TheNatural_1_1/B.cpp.tk                        |  13
code/TheNatural_2_1/C.cpp.tk                        |  24
code/TrueBamboo_0_1/test.cpp.tk                     |  18
code/TrueBamboo_1_1/test.cpp.tk                     |  28
code/TrueBamboo_2_1/test.cpp.tk                     |  75
code/tur.turczyn_0_1/A.cpp.tk                       |  16
code/tur.turczyn_1_1/B.cpp.tk                       |  26
code/tur.turczyn_2_1/C.cpp.tk                       |  32
code/Tyg3R_0_1/A.cpp.tk                             |  15
code/Tyg3R_1_1/B.cpp.tk                             |  20
code/Tyg3R_2_1/C.cpp.tk                             |  22
code/UminchuR_0_1/main.cpp.tk                       |  25
code/UminchuR_1_1/main.cpp.tk                       |  35
code/UminchuR_2_1/main.cpp.tk                       |  61
code/wo..._0_1/a.cpp.tk                             |  14
code/wo..._1_1/b.cpp.tk                             |  18
code/wo..._2_1/c.cpp.tk                             |  64
code/yswtt_0_1/A.cpp.tk                             |  8
code/yswtt_1_1/B.cpp.tk                             |  18
code/yswtt_2_1/C.cpp.tk                             |  56
code/ZhSh_0_1/a.cpp.tk                              |  10
code/ZhSh_1_1/b.cpp.tk                              |  68
code/ZhSh_2_1/c.cpp.tk                              |  89
