Begin
Comparing:  code/apiad_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  10
code/551100kk_1_1/B.cpp.tk                          |  14
code/551100kk_2_1/C.cpp.tk                          |  61
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  18
code/achan1058_2_1/source.cpp.tk                    |  30
code/alanubi_0_1/a.cpp.tk                           |  8
code/alanubi_1_1/b.cpp.tk                           |  14
code/alanubi_2_1/c.cpp.tk                           |  53
code/AntiForest_0_1/q1.cpp.tk                       |  17
code/AntiForest_1_1/q2.cpp.tk                       |  7
code/AntiForest_2_1/q3.cpp.tk                       |  90
code/apiad_0_1/A.cpp.tk                             |  414
code/apiad_1_1/B.cpp.tk                             |  417
code/apiad_2_1/C.cpp.tk                             |  46635
code/azaky_0_1/A.cpp.tk                             |  18
code/azaky_1_1/B.cpp.tk                             |  18
code/azaky_2_1/C.cpp.tk                             |  139
code/azariamuh_0_1/standing.cpp.tk                  |  10
code/azariamuh_1_1/pancake.cpp.tk                   |  36
code/azariamuh_2_1/dijkstra.cpp.tk                  |  28
code/bmerry_0_1/a.cpp.tk                            |  31
code/bmerry_1_1/b.cpp.tk                            |  33
code/bmerry_2_1/c.cpp.tk                            |  157
code/climpet_0_1/A.cpp.tk                           |  16
code/climpet_1_1/B.cpp.tk                           |  19
code/climpet_2_1/C.cpp.tk                           |  134
code/ctzsm_0_1/A.cpp.tk                             |  11
code/ctzsm_1_1/B.cpp.tk                             |  14
code/ctzsm_2_1/C.cpp.tk                             |  153
code/DanilC_0_1/problem.cpp.tk                      |  16
code/DanilC_1_1/problemB.cpp.tk                     |  29
code/DanilC_2_1/problemC.cpp.tk                     |  58
code/DEGwer_0_1/A.cpp.tk                            |  15
code/DEGwer_1_1/B.cpp.tk                            |  14
code/DEGwer_2_1/C.cpp.tk                            |  41
code/dmute_0_1/a.cpp.tk                             |  8
code/dmute_1_1/b.cpp.tk                             |  14
code/dmute_2_1/c2.cpp.tk                            |  54
code/fagu_0_1/A.cpp.tk                              |  9
code/fagu_1_1/B.cpp.tk                              |  8
code/fagu_2_1/C.cpp.tk                              |  169
code/FatalEagle_0_1/main.cpp.tk                     |  12
code/FatalEagle_1_1/main.cpp.tk                     |  14
code/FatalEagle_2_1/main.cpp.tk                     |  146
code/fullpower_0_1/A.cpp.tk                         |  19
code/fullpower_1_1/B.cpp.tk                         |  33
code/fullpower_2_1/C.cpp.tk                         |  70
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  6
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  10
code/ICastro_2_1/Dijkstra.cpp.tk                    |  77
code/ilackthatsuperpower_0_1/a.cpp.tk               |  42
code/ilackthatsuperpower_1_1/b.cpp.tk               |  39
code/ilackthatsuperpower_2_1/c.cpp.tk               |  67
code/iridescent_0_1/A.cpp.tk                        |  7
code/iridescent_1_1/B.cpp.tk                        |  8
code/iridescent_2_1/C.cpp.tk                        |  161
code/ishraq_0_1/main.cpp.tk                         |  9
code/ishraq_1_1/main.cpp.tk                         |  10
code/ishraq_2_1/main.cpp.tk                         |  50
code/JayXon_0_1/A.cpp.tk                            |  6
code/JayXon_1_1/B.cpp.tk                            |  16
code/JayXon_2_1/C.cpp.tk                            |  21
code/Josse_0_1/A.cpp.tk                             |  7
code/Josse_1_1/B.cpp.tk                             |  11
code/Josse_2_1/C.cpp.tk                             |  55
code/kcm1700_0_1/a.cpp.tk                           |  8
code/kcm1700_1_1/b.cpp.tk                           |  11
code/kcm1700_2_1/c.cpp.tk                           |  60
code/kevinsogo_0_1/a.cpp.tk                         |  9
code/kevinsogo_1_1/b.cpp.tk                         |  10
code/kevinsogo_2_1/c.cpp.tk                         |  89
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  7
code/LazyAnna_1_1/2-1.cpp.tk                        |  9
code/LazyAnna_2_1/3.cpp.tk                          |  43
code/Merkurev_0_1/A.cpp.tk                          |  16
code/Merkurev_1_1/B.cpp.tk                          |  20
code/Merkurev_2_1/C.cpp.tk                          |  41
code/mezei_0_1/main.cpp.tk                          |  15
code/mezei_1_1/main.cpp.tk                          |  12
code/mezei_2_1/main.cpp.tk                          |  45
code/Mister_0_1/a.cpp.tk                            |  8
code/Mister_1_1/b.cpp.tk                            |  10
code/Mister_2_1/c.cpp.tk                            |  50
code/namonakiacc_0_1/cpp.cpp.tk                     |  22
code/namonakiacc_1_1/cpp.cpp.tk                     |  24
code/namonakiacc_2_1/cpp.cpp.tk                     |  109
code/Nicolas16_0_1/main.cpp.tk                      |  4
code/Nicolas16_1_1/main.cpp.tk                      |  4
code/Nicolas16_2_1/main.cpp.tk                      |  46
code/pandamonium_0_1/a.cpp.tk                       |  9
code/pandamonium_1_1/b.cpp.tk                       |  30
code/pandamonium_2_1/c.cpp.tk                       |  33
code/pflueger_0_1/A.cpp.tk                          |  5
code/pflueger_1_1/B.cpp.tk                          |  9
code/pflueger_2_1/C.cpp.tk                          |  42
code/ponyopoppo_0_1/A.cpp.tk                        |  8
code/ponyopoppo_1_1/B.cpp.tk                        |  12
code/ponyopoppo_2_1/C.cpp.tk                        |  68
code/Ragnar_0_1/A.cpp.tk                            |  10
code/Ragnar_1_1/B-2.cpp.tk                          |  14
code/Ragnar_2_1/C.cpp.tk                            |  36
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  12
code/saffah_2_1/t.cpp.tk                            |  60
code/SamanSami_0_1/A.cpp.tk                         |  1
code/SamanSami_1_1/B.cpp.tk                         |  8
code/SamanSami_2_1/C.cpp.tk                         |  7
code/Savlik_0_1/code.cpp.tk                         |  5
code/Savlik_1_1/code.cpp.tk                         |  7
code/Savlik_2_1/code.cpp.tk                         |  38
code/shik_0_1/pa.cpp.tk                             |  37
code/shik_1_1/pb.cpp.tk                             |  36
code/shik_2_1/pc.cpp.tk                             |  85
code/simsa.st_0_1/A.cpp.tk                          |  9
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  48
code/SovietUnion_0_1/A.cpp.tk                       |  13
code/SovietUnion_1_1/B.cpp.tk                       |  16
code/SovietUnion_2_1/C.cpp.tk                       |  41
code/tailed_0_1/A.cpp.tk                            |  6
code/tailed_1_1/B.cpp.tk                            |  8
code/tailed_2_1/C.cpp.tk                            |  35
code/TheNatural_0_1/A.cpp.tk                        |  8
code/TheNatural_1_1/B.cpp.tk                        |  9
code/TheNatural_2_1/C.cpp.tk                        |  114
code/TrueBamboo_0_1/test.cpp.tk                     |  10
code/TrueBamboo_1_1/test.cpp.tk                     |  12
code/TrueBamboo_2_1/test.cpp.tk                     |  29
code/tur.turczyn_0_1/A.cpp.tk                       |  12
code/tur.turczyn_1_1/B.cpp.tk                       |  16
code/tur.turczyn_2_1/C.cpp.tk                       |  34
code/Tyg3R_0_1/A.cpp.tk                             |  7
code/Tyg3R_1_1/B.cpp.tk                             |  13
code/Tyg3R_2_1/C.cpp.tk                             |  139
code/UminchuR_0_1/main.cpp.tk                       |  17
code/UminchuR_1_1/main.cpp.tk                       |  21
code/UminchuR_2_1/main.cpp.tk                       |  61
code/wo..._0_1/a.cpp.tk                             |  15
code/wo..._1_1/b.cpp.tk                             |  13
code/wo..._2_1/c.cpp.tk                             |  144
code/yswtt_0_1/A.cpp.tk                             |  5
code/yswtt_1_1/B.cpp.tk                             |  10
code/yswtt_2_1/C.cpp.tk                             |  23
code/ZhSh_0_1/a.cpp.tk                              |  5
code/ZhSh_1_1/b.cpp.tk                              |  33
code/ZhSh_2_1/c.cpp.tk                              |  168
