Begin
Comparing:  code/ksun48_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  6
code/551100kk_1_1/B.cpp.tk                          |  9
code/551100kk_2_1/C.cpp.tk                          |  68
code/achan1058_0_1/Q-A.cpp.tk                       |  4
code/achan1058_1_1/source.cpp.tk                    |  9
code/achan1058_2_1/source.cpp.tk                    |  67
code/alanubi_0_1/a.cpp.tk                           |  6
code/alanubi_1_1/b.cpp.tk                           |  8
code/alanubi_2_1/c.cpp.tk                           |  48
code/AntiForest_0_1/q1.cpp.tk                       |  9
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  34
code/apiad_0_1/A.cpp.tk                             |  8
code/apiad_1_1/B.cpp.tk                             |  11
code/apiad_2_1/C.cpp.tk                             |  18
code/azaky_0_1/A.cpp.tk                             |  9
code/azaky_1_1/B.cpp.tk                             |  9
code/azaky_2_1/C.cpp.tk                             |  27
code/azariamuh_0_1/standing.cpp.tk                  |  6
code/azariamuh_1_1/pancake.cpp.tk                   |  9
code/azariamuh_2_1/dijkstra.cpp.tk                  |  22
code/bmerry_0_1/a.cpp.tk                            |  20
code/bmerry_1_1/b.cpp.tk                            |  22
code/bmerry_2_1/c.cpp.tk                            |  29
code/climpet_0_1/A.cpp.tk                           |  10
code/climpet_1_1/B.cpp.tk                           |  11
code/climpet_2_1/C.cpp.tk                           |  27
code/ctzsm_0_1/A.cpp.tk                             |  8
code/ctzsm_1_1/B.cpp.tk                             |  9
code/ctzsm_2_1/C.cpp.tk                             |  40
code/DanilC_0_1/problem.cpp.tk                      |  11
code/DanilC_1_1/problemB.cpp.tk                     |  21
code/DanilC_2_1/problemC.cpp.tk                     |  42
code/DEGwer_0_1/A.cpp.tk                            |  11
code/DEGwer_1_1/B.cpp.tk                            |  11
code/DEGwer_2_1/C.cpp.tk                            |  27
code/dmute_0_1/a.cpp.tk                             |  4
code/dmute_1_1/b.cpp.tk                             |  8
code/dmute_2_1/c2.cpp.tk                            |  41
code/fagu_0_1/A.cpp.tk                              |  4
code/fagu_1_1/B.cpp.tk                              |  4
code/fagu_2_1/C.cpp.tk                              |  18
code/FatalEagle_0_1/main.cpp.tk                     |  7
code/FatalEagle_1_1/main.cpp.tk                     |  10
code/FatalEagle_2_1/main.cpp.tk                     |  60
code/fullpower_0_1/A.cpp.tk                         |  13
code/fullpower_1_1/B.cpp.tk                         |  12
code/fullpower_2_1/C.cpp.tk                         |  47
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  4
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  7
code/ICastro_2_1/Dijkstra.cpp.tk                    |  45
code/ilackthatsuperpower_0_1/a.cpp.tk               |  27
code/ilackthatsuperpower_1_1/b.cpp.tk               |  27
code/ilackthatsuperpower_2_1/c.cpp.tk               |  59
code/iridescent_0_1/A.cpp.tk                        |  4
code/iridescent_1_1/B.cpp.tk                        |  5
code/iridescent_2_1/C.cpp.tk                        |  11
code/ishraq_0_1/main.cpp.tk                         |  5
code/ishraq_1_1/main.cpp.tk                         |  6
code/ishraq_2_1/main.cpp.tk                         |  29
code/JayXon_0_1/A.cpp.tk                            |  4
code/JayXon_1_1/B.cpp.tk                            |  8
code/JayXon_2_1/C.cpp.tk                            |  36
code/Josse_0_1/A.cpp.tk                             |  6
code/Josse_1_1/B.cpp.tk                             |  8
code/Josse_2_1/C.cpp.tk                             |  36
code/kcm1700_0_1/a.cpp.tk                           |  4
code/kcm1700_1_1/b.cpp.tk                           |  6
code/kcm1700_2_1/c.cpp.tk                           |  50
code/kevinsogo_0_1/a.cpp.tk                         |  5
code/kevinsogo_1_1/b.cpp.tk                         |  7
code/kevinsogo_2_1/c.cpp.tk                         |  23
code/ksun48_0_1/A.cpp.tk                            |  11
code/ksun48_1_1/B.cpp.tk                            |  11
code/ksun48_2_1/C.cpp.tk                            |  18589
code/LazyAnna_0_1/1.cpp.tk                          |  4
code/LazyAnna_1_1/2-1.cpp.tk                        |  7
code/LazyAnna_2_1/3.cpp.tk                          |  21
code/Merkurev_0_1/A.cpp.tk                          |  9
code/Merkurev_1_1/B.cpp.tk                          |  17
code/Merkurev_2_1/C.cpp.tk                          |  36
code/mezei_0_1/main.cpp.tk                          |  9
code/mezei_1_1/main.cpp.tk                          |  10
code/mezei_2_1/main.cpp.tk                          |  52
code/Mister_0_1/a.cpp.tk                            |  5
code/Mister_1_1/b.cpp.tk                            |  6
code/Mister_2_1/c.cpp.tk                            |  21
code/namonakiacc_0_1/cpp.cpp.tk                     |  9
code/namonakiacc_1_1/cpp.cpp.tk                     |  10
code/namonakiacc_2_1/cpp.cpp.tk                     |  75
code/Nicolas16_0_1/main.cpp.tk                      |  3
code/Nicolas16_1_1/main.cpp.tk                      |  3
code/Nicolas16_2_1/main.cpp.tk                      |  147
code/pandamonium_0_1/a.cpp.tk                       |  5
code/pandamonium_1_1/b.cpp.tk                       |  18
code/pandamonium_2_1/c.cpp.tk                       |  27
code/pflueger_0_1/A.cpp.tk                          |  4
code/pflueger_1_1/B.cpp.tk                          |  8
code/pflueger_2_1/C.cpp.tk                          |  174
code/ponyopoppo_0_1/A.cpp.tk                        |  6
code/ponyopoppo_1_1/B.cpp.tk                        |  7
code/ponyopoppo_2_1/C.cpp.tk                        |  70
code/Ragnar_0_1/A.cpp.tk                            |  6
code/Ragnar_1_1/B-2.cpp.tk                          |  7
code/Ragnar_2_1/C.cpp.tk                            |  19
code/saffah_0_1/t.cpp.tk                            |  5
code/saffah_1_1/t.cpp.tk                            |  6
code/saffah_2_1/t.cpp.tk                            |  35
code/SamanSami_0_1/A.cpp.tk                         |  1
code/SamanSami_1_1/B.cpp.tk                         |  5
code/SamanSami_2_1/C.cpp.tk                         |  10
code/Savlik_0_1/code.cpp.tk                         |  5
code/Savlik_1_1/code.cpp.tk                         |  5
code/Savlik_2_1/code.cpp.tk                         |  37
code/shik_0_1/pa.cpp.tk                             |  32
code/shik_1_1/pb.cpp.tk                             |  33
code/shik_2_1/pc.cpp.tk                             |  57
code/simsa.st_0_1/A.cpp.tk                          |  4
code/simsa.st_1_1/B.cpp.tk                          |  6
code/simsa.st_2_1/C.cpp.tk                          |  41
code/SovietUnion_0_1/A.cpp.tk                       |  8
code/SovietUnion_1_1/B.cpp.tk                       |  11
code/SovietUnion_2_1/C.cpp.tk                       |  38
code/tailed_0_1/A.cpp.tk                            |  6
code/tailed_1_1/B.cpp.tk                            |  6
code/tailed_2_1/C.cpp.tk                            |  44
code/TheNatural_0_1/A.cpp.tk                        |  5
code/TheNatural_1_1/B.cpp.tk                        |  6
code/TheNatural_2_1/C.cpp.tk                        |  18
code/TrueBamboo_0_1/test.cpp.tk                     |  9
code/TrueBamboo_1_1/test.cpp.tk                     |  11
code/TrueBamboo_2_1/test.cpp.tk                     |  45
code/tur.turczyn_0_1/A.cpp.tk                       |  5
code/tur.turczyn_1_1/B.cpp.tk                       |  8
code/tur.turczyn_2_1/C.cpp.tk                       |  19
code/Tyg3R_0_1/A.cpp.tk                             |  5
code/Tyg3R_1_1/B.cpp.tk                             |  6
code/Tyg3R_2_1/C.cpp.tk                             |  15
code/UminchuR_0_1/main.cpp.tk                       |  13
code/UminchuR_1_1/main.cpp.tk                       |  12
code/UminchuR_2_1/main.cpp.tk                       |  37
code/wo..._0_1/a.cpp.tk                             |  6
code/wo..._1_1/b.cpp.tk                             |  11
code/wo..._2_1/c.cpp.tk                             |  52
code/yswtt_0_1/A.cpp.tk                             |  5
code/yswtt_1_1/B.cpp.tk                             |  6
code/yswtt_2_1/C.cpp.tk                             |  39
code/ZhSh_0_1/a.cpp.tk                              |  4
code/ZhSh_1_1/b.cpp.tk                              |  23
code/ZhSh_2_1/c.cpp.tk                              |  42
