Begin
Comparing:  code/achan1058_0_1/Q-A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  19
code/551100kk_1_1/B.cpp.tk                          |  20
code/551100kk_2_1/C.cpp.tk                          |  42
code/achan1058_0_1/Q-A.cpp.tk                       |  2020
code/achan1058_1_1/source.cpp.tk                    |  65
code/achan1058_2_1/source.cpp.tk                    |  82
code/alanubi_0_1/a.cpp.tk                           |  14
code/alanubi_1_1/b.cpp.tk                           |  16
code/alanubi_2_1/c.cpp.tk                           |  70
code/AntiForest_0_1/q1.cpp.tk                       |  38
code/AntiForest_1_1/q2.cpp.tk                       |  11
code/AntiForest_2_1/q3.cpp.tk                       |  67
code/apiad_0_1/A.cpp.tk                             |  49
code/apiad_1_1/B.cpp.tk                             |  26
code/apiad_2_1/C.cpp.tk                             |  30
code/azaky_0_1/A.cpp.tk                             |  28
code/azaky_1_1/B.cpp.tk                             |  27
code/azaky_2_1/C.cpp.tk                             |  59
code/azariamuh_0_1/standing.cpp.tk                  |  24
code/azariamuh_1_1/pancake.cpp.tk                   |  42
code/azariamuh_2_1/dijkstra.cpp.tk                  |  24
code/bmerry_0_1/a.cpp.tk                            |  43
code/bmerry_1_1/b.cpp.tk                            |  50
code/bmerry_2_1/c.cpp.tk                            |  53
code/climpet_0_1/A.cpp.tk                           |  29
code/climpet_1_1/B.cpp.tk                           |  34
code/climpet_2_1/C.cpp.tk                           |  51
code/ctzsm_0_1/A.cpp.tk                             |  18
code/ctzsm_1_1/B.cpp.tk                             |  17
code/ctzsm_2_1/C.cpp.tk                             |  68
code/DanilC_0_1/problem.cpp.tk                      |  37
code/DanilC_1_1/problemB.cpp.tk                     |  46
code/DanilC_2_1/problemC.cpp.tk                     |  98
code/DEGwer_0_1/A.cpp.tk                            |  19
code/DEGwer_1_1/B.cpp.tk                            |  19
code/DEGwer_2_1/C.cpp.tk                            |  31
code/dmute_0_1/a.cpp.tk                             |  15
code/dmute_1_1/b.cpp.tk                             |  15
code/dmute_2_1/c2.cpp.tk                            |  41
code/fagu_0_1/A.cpp.tk                              |  8
code/fagu_1_1/B.cpp.tk                              |  8
code/fagu_2_1/C.cpp.tk                              |  41
code/FatalEagle_0_1/main.cpp.tk                     |  19
code/FatalEagle_1_1/main.cpp.tk                     |  19
code/FatalEagle_2_1/main.cpp.tk                     |  104
code/fullpower_0_1/A.cpp.tk                         |  19
code/fullpower_1_1/B.cpp.tk                         |  24
code/fullpower_2_1/C.cpp.tk                         |  58
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  12
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  19
code/ICastro_2_1/Dijkstra.cpp.tk                    |  110
code/ilackthatsuperpower_0_1/a.cpp.tk               |  79
code/ilackthatsuperpower_1_1/b.cpp.tk               |  80
code/ilackthatsuperpower_2_1/c.cpp.tk               |  109
code/iridescent_0_1/A.cpp.tk                        |  18
code/iridescent_1_1/B.cpp.tk                        |  19
code/iridescent_2_1/C.cpp.tk                        |  22
code/ishraq_0_1/main.cpp.tk                         |  52
code/ishraq_1_1/main.cpp.tk                         |  23
code/ishraq_2_1/main.cpp.tk                         |  89
code/JayXon_0_1/A.cpp.tk                            |  10
code/JayXon_1_1/B.cpp.tk                            |  19
code/JayXon_2_1/C.cpp.tk                            |  32
code/Josse_0_1/A.cpp.tk                             |  18
code/Josse_1_1/B.cpp.tk                             |  23
code/Josse_2_1/C.cpp.tk                             |  66
code/kcm1700_0_1/a.cpp.tk                           |  10
code/kcm1700_1_1/b.cpp.tk                           |  14
code/kcm1700_2_1/c.cpp.tk                           |  47
code/kevinsogo_0_1/a.cpp.tk                         |  14
code/kevinsogo_1_1/b.cpp.tk                         |  16
code/kevinsogo_2_1/c.cpp.tk                         |  54
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  14
code/LazyAnna_0_1/1.cpp.tk                          |  12
code/LazyAnna_1_1/2-1.cpp.tk                        |  18
code/LazyAnna_2_1/3.cpp.tk                          |  35
code/Merkurev_0_1/A.cpp.tk                          |  14
code/Merkurev_1_1/B.cpp.tk                          |  26
code/Merkurev_2_1/C.cpp.tk                          |  28
code/mezei_0_1/main.cpp.tk                          |  16
code/mezei_1_1/main.cpp.tk                          |  13
code/mezei_2_1/main.cpp.tk                          |  52
code/Mister_0_1/a.cpp.tk                            |  13
code/Mister_1_1/b.cpp.tk                            |  12
code/Mister_2_1/c.cpp.tk                            |  28
code/namonakiacc_0_1/cpp.cpp.tk                     |  30
code/namonakiacc_1_1/cpp.cpp.tk                     |  33
code/namonakiacc_2_1/cpp.cpp.tk                     |  61
code/Nicolas16_0_1/main.cpp.tk                      |  8
code/Nicolas16_1_1/main.cpp.tk                      |  6
code/Nicolas16_2_1/main.cpp.tk                      |  48
code/pandamonium_0_1/a.cpp.tk                       |  15
code/pandamonium_1_1/b.cpp.tk                       |  28
code/pandamonium_2_1/c.cpp.tk                       |  21
code/pflueger_0_1/A.cpp.tk                          |  16
code/pflueger_1_1/B.cpp.tk                          |  20
code/pflueger_2_1/C.cpp.tk                          |  47
code/ponyopoppo_0_1/A.cpp.tk                        |  21
code/ponyopoppo_1_1/B.cpp.tk                        |  34
code/ponyopoppo_2_1/C.cpp.tk                        |  107
code/Ragnar_0_1/A.cpp.tk                            |  27
code/Ragnar_1_1/B-2.cpp.tk                          |  28
code/Ragnar_2_1/C.cpp.tk                            |  41
code/saffah_0_1/t.cpp.tk                            |  34
code/saffah_1_1/t.cpp.tk                            |  27
code/saffah_2_1/t.cpp.tk                            |  83
code/SamanSami_0_1/A.cpp.tk                         |  5
code/SamanSami_1_1/B.cpp.tk                         |  20
code/SamanSami_2_1/C.cpp.tk                         |  9
code/Savlik_0_1/code.cpp.tk                         |  13
code/Savlik_1_1/code.cpp.tk                         |  12
code/Savlik_2_1/code.cpp.tk                         |  58
code/shik_0_1/pa.cpp.tk                             |  67
code/shik_1_1/pb.cpp.tk                             |  53
code/shik_2_1/pc.cpp.tk                             |  94
code/simsa.st_0_1/A.cpp.tk                          |  17
code/simsa.st_1_1/B.cpp.tk                          |  23
code/simsa.st_2_1/C.cpp.tk                          |  65
code/SovietUnion_0_1/A.cpp.tk                       |  19
code/SovietUnion_1_1/B.cpp.tk                       |  21
code/SovietUnion_2_1/C.cpp.tk                       |  65
code/tailed_0_1/A.cpp.tk                            |  15
code/tailed_1_1/B.cpp.tk                            |  19
code/tailed_2_1/C.cpp.tk                            |  46
code/TheNatural_0_1/A.cpp.tk                        |  17
code/TheNatural_1_1/B.cpp.tk                        |  20
code/TheNatural_2_1/C.cpp.tk                        |  24
code/TrueBamboo_0_1/test.cpp.tk                     |  20
code/TrueBamboo_1_1/test.cpp.tk                     |  26
code/TrueBamboo_2_1/test.cpp.tk                     |  47
code/tur.turczyn_0_1/A.cpp.tk                       |  21
code/tur.turczyn_1_1/B.cpp.tk                       |  29
code/tur.turczyn_2_1/C.cpp.tk                       |  37
code/Tyg3R_0_1/A.cpp.tk                             |  28
code/Tyg3R_1_1/B.cpp.tk                             |  33
code/Tyg3R_2_1/C.cpp.tk                             |  41
code/UminchuR_0_1/main.cpp.tk                       |  33
code/UminchuR_1_1/main.cpp.tk                       |  33
code/UminchuR_2_1/main.cpp.tk                       |  53
code/wo..._0_1/a.cpp.tk                             |  14
code/wo..._1_1/b.cpp.tk                             |  16
code/wo..._2_1/c.cpp.tk                             |  49
code/yswtt_0_1/A.cpp.tk                             |  24
code/yswtt_1_1/B.cpp.tk                             |  20
code/yswtt_2_1/C.cpp.tk                             |  41
code/ZhSh_0_1/a.cpp.tk                              |  19
code/ZhSh_1_1/b.cpp.tk                              |  58
code/ZhSh_2_1/c.cpp.tk                              |  72
