Begin
Comparing:  code/DEGwer_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  13
code/551100kk_1_1/B.cpp.tk                          |  25
code/551100kk_2_1/C.cpp.tk                          |  375
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  16
code/achan1058_2_1/source.cpp.tk                    |  44
code/alanubi_0_1/a.cpp.tk                           |  30
code/alanubi_1_1/b.cpp.tk                           |  57
code/alanubi_2_1/c.cpp.tk                           |  108
code/AntiForest_0_1/q1.cpp.tk                       |  16
code/AntiForest_1_1/q2.cpp.tk                       |  8
code/AntiForest_2_1/q3.cpp.tk                       |  518
code/apiad_0_1/A.cpp.tk                             |  14
code/apiad_1_1/B.cpp.tk                             |  21
code/apiad_2_1/C.cpp.tk                             |  48
code/azaky_0_1/A.cpp.tk                             |  18
code/azaky_1_1/B.cpp.tk                             |  22
code/azaky_2_1/C.cpp.tk                             |  94
code/azariamuh_0_1/standing.cpp.tk                  |  13
code/azariamuh_1_1/pancake.cpp.tk                   |  29
code/azariamuh_2_1/dijkstra.cpp.tk                  |  62
code/bmerry_0_1/a.cpp.tk                            |  54
code/bmerry_1_1/b.cpp.tk                            |  73
code/bmerry_2_1/c.cpp.tk                            |  87
code/climpet_0_1/A.cpp.tk                           |  22
code/climpet_1_1/B.cpp.tk                           |  30
code/climpet_2_1/C.cpp.tk                           |  68
code/ctzsm_0_1/A.cpp.tk                             |  21
code/ctzsm_1_1/B.cpp.tk                             |  34
code/ctzsm_2_1/C.cpp.tk                             |  124
code/DanilC_0_1/problem.cpp.tk                      |  26
code/DanilC_1_1/problemB.cpp.tk                     |  44
code/DanilC_2_1/problemC.cpp.tk                     |  89
code/DEGwer_0_1/A.cpp.tk                            |  209
code/DEGwer_1_1/B.cpp.tk                            |  220
code/DEGwer_2_1/C.cpp.tk                            |  25766
code/dmute_0_1/a.cpp.tk                             |  17
code/dmute_1_1/b.cpp.tk                             |  25
code/dmute_2_1/c2.cpp.tk                            |  71
code/fagu_0_1/A.cpp.tk                              |  25
code/fagu_1_1/B.cpp.tk                              |  25
code/fagu_2_1/C.cpp.tk                              |  93
code/FatalEagle_0_1/main.cpp.tk                     |  22
code/FatalEagle_1_1/main.cpp.tk                     |  42
code/FatalEagle_2_1/main.cpp.tk                     |  198
code/fullpower_0_1/A.cpp.tk                         |  28
code/fullpower_1_1/B.cpp.tk                         |  45
code/fullpower_2_1/C.cpp.tk                         |  85
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  11
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  21
code/ICastro_2_1/Dijkstra.cpp.tk                    |  114
code/ilackthatsuperpower_0_1/a.cpp.tk               |  66
code/ilackthatsuperpower_1_1/b.cpp.tk               |  69
code/ilackthatsuperpower_2_1/c.cpp.tk               |  106
code/iridescent_0_1/A.cpp.tk                        |  12
code/iridescent_1_1/B.cpp.tk                        |  17
code/iridescent_2_1/C.cpp.tk                        |  75
code/ishraq_0_1/main.cpp.tk                         |  12
code/ishraq_1_1/main.cpp.tk                         |  17
code/ishraq_2_1/main.cpp.tk                         |  73
code/JayXon_0_1/A.cpp.tk                            |  8
code/JayXon_1_1/B.cpp.tk                            |  35
code/JayXon_2_1/C.cpp.tk                            |  37
code/Josse_0_1/A.cpp.tk                             |  25
code/Josse_1_1/B.cpp.tk                             |  41
code/Josse_2_1/C.cpp.tk                             |  95
code/kcm1700_0_1/a.cpp.tk                           |  18
code/kcm1700_1_1/b.cpp.tk                           |  45
code/kcm1700_2_1/c.cpp.tk                           |  82
code/kevinsogo_0_1/a.cpp.tk                         |  11
code/kevinsogo_1_1/b.cpp.tk                         |  13
code/kevinsogo_2_1/c.cpp.tk                         |  55
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  21
code/LazyAnna_0_1/1.cpp.tk                          |  9
code/LazyAnna_1_1/2-1.cpp.tk                        |  19
code/LazyAnna_2_1/3.cpp.tk                          |  57
code/Merkurev_0_1/A.cpp.tk                          |  24
code/Merkurev_1_1/B.cpp.tk                          |  67
code/Merkurev_2_1/C.cpp.tk                          |  51
code/mezei_0_1/main.cpp.tk                          |  65
code/mezei_1_1/main.cpp.tk                          |  72
code/mezei_2_1/main.cpp.tk                          |  156
code/Mister_0_1/a.cpp.tk                            |  17
code/Mister_1_1/b.cpp.tk                            |  30
code/Mister_2_1/c.cpp.tk                            |  369
code/namonakiacc_0_1/cpp.cpp.tk                     |  19
code/namonakiacc_1_1/cpp.cpp.tk                     |  22
code/namonakiacc_2_1/cpp.cpp.tk                     |  56
code/Nicolas16_0_1/main.cpp.tk                      |  11
code/Nicolas16_1_1/main.cpp.tk                      |  11
code/Nicolas16_2_1/main.cpp.tk                      |  78
code/pandamonium_0_1/a.cpp.tk                       |  19
code/pandamonium_1_1/b.cpp.tk                       |  70
code/pandamonium_2_1/c.cpp.tk                       |  38
code/pflueger_0_1/A.cpp.tk                          |  11
code/pflueger_1_1/B.cpp.tk                          |  35
code/pflueger_2_1/C.cpp.tk                          |  81
code/ponyopoppo_0_1/A.cpp.tk                        |  7
code/ponyopoppo_1_1/B.cpp.tk                        |  15
code/ponyopoppo_2_1/C.cpp.tk                        |  120
code/Ragnar_0_1/A.cpp.tk                            |  11
code/Ragnar_1_1/B-2.cpp.tk                          |  23
code/Ragnar_2_1/C.cpp.tk                            |  43
code/saffah_0_1/t.cpp.tk                            |  11
code/saffah_1_1/t.cpp.tk                            |  16
code/saffah_2_1/t.cpp.tk                            |  79
code/SamanSami_0_1/A.cpp.tk                         |  4
code/SamanSami_1_1/B.cpp.tk                         |  29
code/SamanSami_2_1/C.cpp.tk                         |  13
code/Savlik_0_1/code.cpp.tk                         |  11
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  48
code/shik_0_1/pa.cpp.tk                             |  41
code/shik_1_1/pb.cpp.tk                             |  43
code/shik_2_1/pc.cpp.tk                             |  519
code/simsa.st_0_1/A.cpp.tk                          |  12
code/simsa.st_1_1/B.cpp.tk                          |  14
code/simsa.st_2_1/C.cpp.tk                          |  64
code/SovietUnion_0_1/A.cpp.tk                       |  21
code/SovietUnion_1_1/B.cpp.tk                       |  26
code/SovietUnion_2_1/C.cpp.tk                       |  67
code/tailed_0_1/A.cpp.tk                            |  9
code/tailed_1_1/B.cpp.tk                            |  13
code/tailed_2_1/C.cpp.tk                            |  54
code/TheNatural_0_1/A.cpp.tk                        |  14
code/TheNatural_1_1/B.cpp.tk                        |  30
code/TheNatural_2_1/C.cpp.tk                        |  50
code/TrueBamboo_0_1/test.cpp.tk                     |  16
code/TrueBamboo_1_1/test.cpp.tk                     |  24
code/TrueBamboo_2_1/test.cpp.tk                     |  69
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  15
code/tur.turczyn_2_1/C.cpp.tk                       |  49
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  16
code/Tyg3R_2_1/C.cpp.tk                             |  70
code/UminchuR_0_1/main.cpp.tk                       |  19
code/UminchuR_1_1/main.cpp.tk                       |  24
code/UminchuR_2_1/main.cpp.tk                       |  52
code/wo..._0_1/a.cpp.tk                             |  37
code/wo..._1_1/b.cpp.tk                             |  48
code/wo..._2_1/c.cpp.tk                             |  447
code/yswtt_0_1/A.cpp.tk                             |  9
code/yswtt_1_1/B.cpp.tk                             |  20
code/yswtt_2_1/C.cpp.tk                             |  35
code/ZhSh_0_1/a.cpp.tk                              |  10
code/ZhSh_1_1/b.cpp.tk                              |  45
code/ZhSh_2_1/c.cpp.tk                              |  199
