Begin
Comparing:  code/alanubi_2_1/c.cpp.tk
code/00/test.cpp.tk                                 |  42
code/01/test.cpp.tk                                 |  42
code/551100kk_0_1/A.cpp.tk                          |  20
code/551100kk_1_1/B.cpp.tk                          |  42
code/551100kk_2_1/C.cpp.tk                          |  71
code/achan1058_0_1/Q-A.cpp.tk                       |  13
code/achan1058_1_1/source.cpp.tk                    |  41
code/achan1058_2_1/source.cpp.tk                    |  76
code/alanubi_0_1/a.cpp.tk                           |  56
code/alanubi_1_1/b.cpp.tk                           |  96
code/alanubi_2_1/c.cpp.tk                           |  320196
code/AntiForest_0_1/q1.cpp.tk                       |  21
code/AntiForest_1_1/q2.cpp.tk                       |  9
code/AntiForest_2_1/q3.cpp.tk                       |  79
code/apiad_0_1/A.cpp.tk                             |  33
code/apiad_1_1/B.cpp.tk                             |  36
code/apiad_2_1/C.cpp.tk                             |  48
code/azaky_0_1/A.cpp.tk                             |  28
code/azaky_1_1/B.cpp.tk                             |  29
code/azaky_2_1/C.cpp.tk                             |  88
code/azariamuh_0_1/standing.cpp.tk                  |  18
code/azariamuh_1_1/pancake.cpp.tk                   |  28
code/azariamuh_2_1/dijkstra.cpp.tk                  |  29
code/bmerry_0_1/a.cpp.tk                            |  76
code/bmerry_1_1/b.cpp.tk                            |  103
code/bmerry_2_1/c.cpp.tk                            |  99
code/climpet_0_1/A.cpp.tk                           |  47
code/climpet_1_1/B.cpp.tk                           |  61
code/climpet_2_1/C.cpp.tk                           |  97
code/ctzsm_0_1/A.cpp.tk                             |  29
code/ctzsm_1_1/B.cpp.tk                             |  39
code/ctzsm_2_1/C.cpp.tk                             |  125
code/DanilC_0_1/problem.cpp.tk                      |  49
code/DanilC_1_1/problemB.cpp.tk                     |  78
code/DanilC_2_1/problemC.cpp.tk                     |  188
code/DEGwer_0_1/A.cpp.tk                            |  54
code/DEGwer_1_1/B.cpp.tk                            |  65
code/DEGwer_2_1/C.cpp.tk                            |  66
code/dmute_0_1/a.cpp.tk                             |  25
code/dmute_1_1/b.cpp.tk                             |  47
code/dmute_2_1/c2.cpp.tk                            |  110
code/fagu_0_1/A.cpp.tk                              |  33
code/fagu_1_1/B.cpp.tk                              |  33
code/fagu_2_1/C.cpp.tk                              |  60
code/FatalEagle_0_1/main.cpp.tk                     |  31
code/FatalEagle_1_1/main.cpp.tk                     |  70
code/FatalEagle_2_1/main.cpp.tk                     |  290
code/fullpower_0_1/A.cpp.tk                         |  43
code/fullpower_1_1/B.cpp.tk                         |  72
code/fullpower_2_1/C.cpp.tk                         |  139
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  24
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  40
code/ICastro_2_1/Dijkstra.cpp.tk                    |  116
code/ilackthatsuperpower_0_1/a.cpp.tk               |  124
code/ilackthatsuperpower_1_1/b.cpp.tk               |  126
code/ilackthatsuperpower_2_1/c.cpp.tk               |  165
code/iridescent_0_1/A.cpp.tk                        |  23
code/iridescent_1_1/B.cpp.tk                        |  36
code/iridescent_2_1/C.cpp.tk                        |  54
code/ishraq_0_1/main.cpp.tk                         |  18
code/ishraq_1_1/main.cpp.tk                         |  26
code/ishraq_2_1/main.cpp.tk                         |  76
code/JayXon_0_1/A.cpp.tk                            |  18
code/JayXon_1_1/B.cpp.tk                            |  53
code/JayXon_2_1/C.cpp.tk                            |  48
code/Josse_0_1/A.cpp.tk                             |  44
code/Josse_1_1/B.cpp.tk                             |  71
code/Josse_2_1/C.cpp.tk                             |  199
code/kcm1700_0_1/a.cpp.tk                           |  30
code/kcm1700_1_1/b.cpp.tk                           |  69
code/kcm1700_2_1/c.cpp.tk                           |  128
code/kevinsogo_0_1/a.cpp.tk                         |  18
code/kevinsogo_1_1/b.cpp.tk                         |  24
code/kevinsogo_2_1/c.cpp.tk                         |  74
code/ksun48_0_1/A.cpp.tk                            |  6
code/ksun48_1_1/B.cpp.tk                            |  6
code/ksun48_2_1/C.cpp.tk                            |  26
code/LazyAnna_0_1/1.cpp.tk                          |  20
code/LazyAnna_1_1/2-1.cpp.tk                        |  35
code/LazyAnna_2_1/3.cpp.tk                          |  53
code/Merkurev_0_1/A.cpp.tk                          |  41
code/Merkurev_1_1/B.cpp.tk                          |  92
code/Merkurev_2_1/C.cpp.tk                          |  87
code/mezei_0_1/main.cpp.tk                          |  40
code/mezei_1_1/main.cpp.tk                          |  63
code/mezei_2_1/main.cpp.tk                          |  140
code/Mister_0_1/a.cpp.tk                            |  28
code/Mister_1_1/b.cpp.tk                            |  44
code/Mister_2_1/c.cpp.tk                            |  60
code/namonakiacc_0_1/cpp.cpp.tk                     |  48
code/namonakiacc_1_1/cpp.cpp.tk                     |  53
code/namonakiacc_2_1/cpp.cpp.tk                     |  83
code/Nicolas16_0_1/main.cpp.tk                      |  15
code/Nicolas16_1_1/main.cpp.tk                      |  14
code/Nicolas16_2_1/main.cpp.tk                      |  130
code/pandamonium_0_1/a.cpp.tk                       |  26
code/pandamonium_1_1/b.cpp.tk                       |  94
code/pandamonium_2_1/c.cpp.tk                       |  52
code/pflueger_0_1/A.cpp.tk                          |  24
code/pflueger_1_1/B.cpp.tk                          |  57
code/pflueger_2_1/C.cpp.tk                          |  116
code/ponyopoppo_0_1/A.cpp.tk                        |  19
code/ponyopoppo_1_1/B.cpp.tk                        |  30
code/ponyopoppo_2_1/C.cpp.tk                        |  162
code/Ragnar_0_1/A.cpp.tk                            |  29
code/Ragnar_1_1/B-2.cpp.tk                          |  43
code/Ragnar_2_1/C.cpp.tk                            |  64
code/saffah_0_1/t.cpp.tk                            |  18
code/saffah_1_1/t.cpp.tk                            |  21
code/saffah_2_1/t.cpp.tk                            |  103
code/SamanSami_0_1/A.cpp.tk                         |  9
code/SamanSami_1_1/B.cpp.tk                         |  49
code/SamanSami_2_1/C.cpp.tk                         |  14
code/Savlik_0_1/code.cpp.tk                         |  22
code/Savlik_1_1/code.cpp.tk                         |  18
code/Savlik_2_1/code.cpp.tk                         |  94
code/shik_0_1/pa.cpp.tk                             |  75
code/shik_1_1/pb.cpp.tk                             |  78
code/shik_2_1/pc.cpp.tk                             |  117
code/simsa.st_0_1/A.cpp.tk                          |  15
code/simsa.st_1_1/B.cpp.tk                          |  22
code/simsa.st_2_1/C.cpp.tk                          |  99
code/SovietUnion_0_1/A.cpp.tk                       |  32
code/SovietUnion_1_1/B.cpp.tk                       |  40
code/SovietUnion_2_1/C.cpp.tk                       |  94
code/tailed_0_1/A.cpp.tk                            |  23
code/tailed_1_1/B.cpp.tk                            |  29
code/tailed_2_1/C.cpp.tk                            |  54
code/TheNatural_0_1/A.cpp.tk                        |  33
code/TheNatural_1_1/B.cpp.tk                        |  58
code/TheNatural_2_1/C.cpp.tk                        |  45
code/TrueBamboo_0_1/test.cpp.tk                     |  27
code/TrueBamboo_1_1/test.cpp.tk                     |  40
code/TrueBamboo_2_1/test.cpp.tk                     |  76
code/tur.turczyn_0_1/A.cpp.tk                       |  30
code/tur.turczyn_1_1/B.cpp.tk                       |  39
code/tur.turczyn_2_1/C.cpp.tk                       |  48
code/Tyg3R_0_1/A.cpp.tk                             |  14
code/Tyg3R_1_1/B.cpp.tk                             |  19
code/Tyg3R_2_1/C.cpp.tk                             |  29
code/UminchuR_0_1/main.cpp.tk                       |  40
code/UminchuR_1_1/main.cpp.tk                       |  47
code/UminchuR_2_1/main.cpp.tk                       |  76
code/wo..._0_1/a.cpp.tk                             |  63
code/wo..._1_1/b.cpp.tk                             |  66
code/wo..._2_1/c.cpp.tk                             |  141
code/yswtt_0_1/A.cpp.tk                             |  22
code/yswtt_1_1/B.cpp.tk                             |  37
code/yswtt_2_1/C.cpp.tk                             |  62
code/ZhSh_0_1/a.cpp.tk                              |  22
code/ZhSh_1_1/b.cpp.tk                              |  88
code/ZhSh_2_1/c.cpp.tk                              |  104
