Begin
Comparing:  code/ctzsm_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  14
code/551100kk_1_1/B.cpp.tk                          |  20
code/551100kk_2_1/C.cpp.tk                          |  54
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  14
code/achan1058_2_1/source.cpp.tk                    |  34
code/alanubi_0_1/a.cpp.tk                           |  15
code/alanubi_1_1/b.cpp.tk                           |  24
code/alanubi_2_1/c.cpp.tk                           |  69
code/AntiForest_0_1/q1.cpp.tk                       |  22
code/AntiForest_1_1/q2.cpp.tk                       |  14
code/AntiForest_2_1/q3.cpp.tk                       |  76
code/apiad_0_1/A.cpp.tk                             |  12
code/apiad_1_1/B.cpp.tk                             |  17
code/apiad_2_1/C.cpp.tk                             |  67
code/azaky_0_1/A.cpp.tk                             |  16
code/azaky_1_1/B.cpp.tk                             |  19
code/azaky_2_1/C.cpp.tk                             |  168
code/azariamuh_0_1/standing.cpp.tk                  |  9
code/azariamuh_1_1/pancake.cpp.tk                   |  25
code/azariamuh_2_1/dijkstra.cpp.tk                  |  72
code/bmerry_0_1/a.cpp.tk                            |  39
code/bmerry_1_1/b.cpp.tk                            |  46
code/bmerry_2_1/c.cpp.tk                            |  91
code/climpet_0_1/A.cpp.tk                           |  26
code/climpet_1_1/B.cpp.tk                           |  35
code/climpet_2_1/C.cpp.tk                           |  99
code/ctzsm_0_1/A.cpp.tk                             |  58
code/ctzsm_1_1/B.cpp.tk                             |  68
code/ctzsm_2_1/C.cpp.tk                             |  218464
code/DanilC_0_1/problem.cpp.tk                      |  28
code/DanilC_1_1/problemB.cpp.tk                     |  51
code/DanilC_2_1/problemC.cpp.tk                     |  84
code/DEGwer_0_1/A.cpp.tk                            |  21
code/DEGwer_1_1/B.cpp.tk                            |  22
code/DEGwer_2_1/C.cpp.tk                            |  43
code/dmute_0_1/a.cpp.tk                             |  13
code/dmute_1_1/b.cpp.tk                             |  22
code/dmute_2_1/c2.cpp.tk                            |  57
code/fagu_0_1/A.cpp.tk                              |  8
code/fagu_1_1/B.cpp.tk                              |  8
code/fagu_2_1/C.cpp.tk                              |  100
code/FatalEagle_0_1/main.cpp.tk                     |  25
code/FatalEagle_1_1/main.cpp.tk                     |  34
code/FatalEagle_2_1/main.cpp.tk                     |  168
code/fullpower_0_1/A.cpp.tk                         |  47
code/fullpower_1_1/B.cpp.tk                         |  42
code/fullpower_2_1/C.cpp.tk                         |  105
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  14
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  24
code/ICastro_2_1/Dijkstra.cpp.tk                    |  97
code/ilackthatsuperpower_0_1/a.cpp.tk               |  67
code/ilackthatsuperpower_1_1/b.cpp.tk               |  65
code/ilackthatsuperpower_2_1/c.cpp.tk               |  94
code/iridescent_0_1/A.cpp.tk                        |  9
code/iridescent_1_1/B.cpp.tk                        |  15
code/iridescent_2_1/C.cpp.tk                        |  102
code/ishraq_0_1/main.cpp.tk                         |  8
code/ishraq_1_1/main.cpp.tk                         |  12
code/ishraq_2_1/main.cpp.tk                         |  76
code/JayXon_0_1/A.cpp.tk                            |  8
code/JayXon_1_1/B.cpp.tk                            |  25
code/JayXon_2_1/C.cpp.tk                            |  26
code/Josse_0_1/A.cpp.tk                             |  12
code/Josse_1_1/B.cpp.tk                             |  19
code/Josse_2_1/C.cpp.tk                             |  77
code/kcm1700_0_1/a.cpp.tk                           |  13
code/kcm1700_1_1/b.cpp.tk                           |  23
code/kcm1700_2_1/c.cpp.tk                           |  62
code/kevinsogo_0_1/a.cpp.tk                         |  9
code/kevinsogo_1_1/b.cpp.tk                         |  11
code/kevinsogo_2_1/c.cpp.tk                         |  63
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  13
code/LazyAnna_1_1/2-1.cpp.tk                        |  23
code/LazyAnna_2_1/3.cpp.tk                          |  48
code/Merkurev_0_1/A.cpp.tk                          |  27
code/Merkurev_1_1/B.cpp.tk                          |  39
code/Merkurev_2_1/C.cpp.tk                          |  50
code/mezei_0_1/main.cpp.tk                          |  21
code/mezei_1_1/main.cpp.tk                          |  22
code/mezei_2_1/main.cpp.tk                          |  58
code/Mister_0_1/a.cpp.tk                            |  20
code/Mister_1_1/b.cpp.tk                            |  29
code/Mister_2_1/c.cpp.tk                            |  69
code/namonakiacc_0_1/cpp.cpp.tk                     |  14
code/namonakiacc_1_1/cpp.cpp.tk                     |  16
code/namonakiacc_2_1/cpp.cpp.tk                     |  52
code/Nicolas16_0_1/main.cpp.tk                      |  8
code/Nicolas16_1_1/main.cpp.tk                      |  8
code/Nicolas16_2_1/main.cpp.tk                      |  71
code/pandamonium_0_1/a.cpp.tk                       |  14
code/pandamonium_1_1/b.cpp.tk                       |  39
code/pandamonium_2_1/c.cpp.tk                       |  31
code/pflueger_0_1/A.cpp.tk                          |  10
code/pflueger_1_1/B.cpp.tk                          |  18
code/pflueger_2_1/C.cpp.tk                          |  52
code/ponyopoppo_0_1/A.cpp.tk                        |  7
code/ponyopoppo_1_1/B.cpp.tk                        |  14
code/ponyopoppo_2_1/C.cpp.tk                        |  96
code/Ragnar_0_1/A.cpp.tk                            |  8
code/Ragnar_1_1/B-2.cpp.tk                          |  14
code/Ragnar_2_1/C.cpp.tk                            |  36
code/saffah_0_1/t.cpp.tk                            |  8
code/saffah_1_1/t.cpp.tk                            |  12
code/saffah_2_1/t.cpp.tk                            |  72
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  16
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  8
code/Savlik_1_1/code.cpp.tk                         |  9
code/Savlik_2_1/code.cpp.tk                         |  51
code/shik_0_1/pa.cpp.tk                             |  39
code/shik_1_1/pb.cpp.tk                             |  41
code/shik_2_1/pc.cpp.tk                             |  95
code/simsa.st_0_1/A.cpp.tk                          |  10
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  71
code/SovietUnion_0_1/A.cpp.tk                       |  52
code/SovietUnion_1_1/B.cpp.tk                       |  58
code/SovietUnion_2_1/C.cpp.tk                       |  63
code/tailed_0_1/A.cpp.tk                            |  7
code/tailed_1_1/B.cpp.tk                            |  12
code/tailed_2_1/C.cpp.tk                            |  82
code/TheNatural_0_1/A.cpp.tk                        |  13
code/TheNatural_1_1/B.cpp.tk                        |  17
code/TheNatural_2_1/C.cpp.tk                        |  59
code/TrueBamboo_0_1/test.cpp.tk                     |  12
code/TrueBamboo_1_1/test.cpp.tk                     |  16
code/TrueBamboo_2_1/test.cpp.tk                     |  38
code/tur.turczyn_0_1/A.cpp.tk                       |  6
code/tur.turczyn_1_1/B.cpp.tk                       |  12
code/tur.turczyn_2_1/C.cpp.tk                       |  70
code/Tyg3R_0_1/A.cpp.tk                             |  8
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  111
code/UminchuR_0_1/main.cpp.tk                       |  19
code/UminchuR_1_1/main.cpp.tk                       |  26
code/UminchuR_2_1/main.cpp.tk                       |  58
code/wo..._0_1/a.cpp.tk                             |  22
code/wo..._1_1/b.cpp.tk                             |  24
code/wo..._2_1/c.cpp.tk                             |  91
code/yswtt_0_1/A.cpp.tk                             |  12
code/yswtt_1_1/B.cpp.tk                             |  25
code/yswtt_2_1/C.cpp.tk                             |  35
code/ZhSh_0_1/a.cpp.tk                              |  12
code/ZhSh_1_1/b.cpp.tk                              |  51
code/ZhSh_2_1/c.cpp.tk                              |  150
