Begin
Comparing:  code/azaky_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  17
code/551100kk_1_1/B.cpp.tk                          |  33
code/551100kk_2_1/C.cpp.tk                          |  46
code/achan1058_0_1/Q-A.cpp.tk                       |  12
code/achan1058_1_1/source.cpp.tk                    |  38
code/achan1058_2_1/source.cpp.tk                    |  67
code/alanubi_0_1/a.cpp.tk                           |  17
code/alanubi_1_1/b.cpp.tk                           |  36
code/alanubi_2_1/c.cpp.tk                           |  77
code/AntiForest_0_1/q1.cpp.tk                       |  46
code/AntiForest_1_1/q2.cpp.tk                       |  23
code/AntiForest_2_1/q3.cpp.tk                       |  88
code/apiad_0_1/A.cpp.tk                             |  24
code/apiad_1_1/B.cpp.tk                             |  42
code/apiad_2_1/C.cpp.tk                             |  38
code/azaky_0_1/A.cpp.tk                             |  864
code/azaky_1_1/B.cpp.tk                             |  12033
code/azaky_2_1/C.cpp.tk                             |  823
code/azariamuh_0_1/standing.cpp.tk                  |  45
code/azariamuh_1_1/pancake.cpp.tk                   |  53
code/azariamuh_2_1/dijkstra.cpp.tk                  |  38
code/bmerry_0_1/a.cpp.tk                            |  56
code/bmerry_1_1/b.cpp.tk                            |  67
code/bmerry_2_1/c.cpp.tk                            |  66
code/climpet_0_1/A.cpp.tk                           |  32
code/climpet_1_1/B.cpp.tk                           |  42
code/climpet_2_1/C.cpp.tk                           |  58
code/ctzsm_0_1/A.cpp.tk                             |  22
code/ctzsm_1_1/B.cpp.tk                             |  37
code/ctzsm_2_1/C.cpp.tk                             |  87
code/DanilC_0_1/problem.cpp.tk                      |  30
code/DanilC_1_1/problemB.cpp.tk                     |  53
code/DanilC_2_1/problemC.cpp.tk                     |  109
code/DEGwer_0_1/A.cpp.tk                            |  30
code/DEGwer_1_1/B.cpp.tk                            |  40
code/DEGwer_2_1/C.cpp.tk                            |  37
code/dmute_0_1/a.cpp.tk                             |  14
code/dmute_1_1/b.cpp.tk                             |  23
code/dmute_2_1/c2.cpp.tk                            |  47
code/fagu_0_1/A.cpp.tk                              |  17
code/fagu_1_1/B.cpp.tk                              |  17
code/fagu_2_1/C.cpp.tk                              |  52
code/FatalEagle_0_1/main.cpp.tk                     |  23
code/FatalEagle_1_1/main.cpp.tk                     |  30
code/FatalEagle_2_1/main.cpp.tk                     |  148
code/fullpower_0_1/A.cpp.tk                         |  30
code/fullpower_1_1/B.cpp.tk                         |  41
code/fullpower_2_1/C.cpp.tk                         |  73
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  10
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  22
code/ICastro_2_1/Dijkstra.cpp.tk                    |  119
code/ilackthatsuperpower_0_1/a.cpp.tk               |  90
code/ilackthatsuperpower_1_1/b.cpp.tk               |  94
code/ilackthatsuperpower_2_1/c.cpp.tk               |  126
code/iridescent_0_1/A.cpp.tk                        |  8
code/iridescent_1_1/B.cpp.tk                        |  16
code/iridescent_2_1/C.cpp.tk                        |  17
code/ishraq_0_1/main.cpp.tk                         |  19
code/ishraq_1_1/main.cpp.tk                         |  27
code/ishraq_2_1/main.cpp.tk                         |  86
code/JayXon_0_1/A.cpp.tk                            |  7
code/JayXon_1_1/B.cpp.tk                            |  19
code/JayXon_2_1/C.cpp.tk                            |  33
code/Josse_0_1/A.cpp.tk                             |  11
code/Josse_1_1/B.cpp.tk                             |  21
code/Josse_2_1/C.cpp.tk                             |  81
code/kcm1700_0_1/a.cpp.tk                           |  15
code/kcm1700_1_1/b.cpp.tk                           |  31
code/kcm1700_2_1/c.cpp.tk                           |  58
code/kevinsogo_0_1/a.cpp.tk                         |  23
code/kevinsogo_1_1/b.cpp.tk                         |  37
code/kevinsogo_2_1/c.cpp.tk                         |  73
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  8
code/LazyAnna_1_1/2-1.cpp.tk                        |  13
code/LazyAnna_2_1/3.cpp.tk                          |  33
code/Merkurev_0_1/A.cpp.tk                          |  24
code/Merkurev_1_1/B.cpp.tk                          |  46
code/Merkurev_2_1/C.cpp.tk                          |  40
code/mezei_0_1/main.cpp.tk                          |  26
code/mezei_1_1/main.cpp.tk                          |  29
code/mezei_2_1/main.cpp.tk                          |  76
code/Mister_0_1/a.cpp.tk                            |  15
code/Mister_1_1/b.cpp.tk                            |  22
code/Mister_2_1/c.cpp.tk                            |  36
code/namonakiacc_0_1/cpp.cpp.tk                     |  46
code/namonakiacc_1_1/cpp.cpp.tk                     |  58
code/namonakiacc_2_1/cpp.cpp.tk                     |  84
code/Nicolas16_0_1/main.cpp.tk                      |  10
code/Nicolas16_1_1/main.cpp.tk                      |  9
code/Nicolas16_2_1/main.cpp.tk                      |  66
code/pandamonium_0_1/a.cpp.tk                       |  16
code/pandamonium_1_1/b.cpp.tk                       |  43
code/pandamonium_2_1/c.cpp.tk                       |  23
code/pflueger_0_1/A.cpp.tk                          |  9
code/pflueger_1_1/B.cpp.tk                          |  16
code/pflueger_2_1/C.cpp.tk                          |  48
code/ponyopoppo_0_1/A.cpp.tk                        |  13
code/ponyopoppo_1_1/B.cpp.tk                        |  30
code/ponyopoppo_2_1/C.cpp.tk                        |  137
code/Ragnar_0_1/A.cpp.tk                            |  21
code/Ragnar_1_1/B-2.cpp.tk                          |  34
code/Ragnar_2_1/C.cpp.tk                            |  47
code/saffah_0_1/t.cpp.tk                            |  24
code/saffah_1_1/t.cpp.tk                            |  60
code/saffah_2_1/t.cpp.tk                            |  114
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  13
code/SamanSami_2_1/C.cpp.tk                         |  13
code/Savlik_0_1/code.cpp.tk                         |  12
code/Savlik_1_1/code.cpp.tk                         |  20
code/Savlik_2_1/code.cpp.tk                         |  61
code/shik_0_1/pa.cpp.tk                             |  79
code/shik_1_1/pb.cpp.tk                             |  81
code/shik_2_1/pc.cpp.tk                             |  113
code/simsa.st_0_1/A.cpp.tk                          |  26
code/simsa.st_1_1/B.cpp.tk                          |  68
code/simsa.st_2_1/C.cpp.tk                          |  108
code/SovietUnion_0_1/A.cpp.tk                       |  22
code/SovietUnion_1_1/B.cpp.tk                       |  36
code/SovietUnion_2_1/C.cpp.tk                       |  70
code/tailed_0_1/A.cpp.tk                            |  10
code/tailed_1_1/B.cpp.tk                            |  20
code/tailed_2_1/C.cpp.tk                            |  36
code/TheNatural_0_1/A.cpp.tk                        |  10
code/TheNatural_1_1/B.cpp.tk                        |  17
code/TheNatural_2_1/C.cpp.tk                        |  21
code/TrueBamboo_0_1/test.cpp.tk                     |  15
code/TrueBamboo_1_1/test.cpp.tk                     |  25
code/TrueBamboo_2_1/test.cpp.tk                     |  48
code/tur.turczyn_0_1/A.cpp.tk                       |  21
code/tur.turczyn_1_1/B.cpp.tk                       |  34
code/tur.turczyn_2_1/C.cpp.tk                       |  36
code/Tyg3R_0_1/A.cpp.tk                             |  15
code/Tyg3R_1_1/B.cpp.tk                             |  42
code/Tyg3R_2_1/C.cpp.tk                             |  27
code/UminchuR_0_1/main.cpp.tk                       |  40
code/UminchuR_1_1/main.cpp.tk                       |  61
code/UminchuR_2_1/main.cpp.tk                       |  76
code/wo..._0_1/a.cpp.tk                             |  22
code/wo..._1_1/b.cpp.tk                             |  24
code/wo..._2_1/c.cpp.tk                             |  61
code/yswtt_0_1/A.cpp.tk                             |  7
code/yswtt_1_1/B.cpp.tk                             |  19
code/yswtt_2_1/C.cpp.tk                             |  29
code/ZhSh_0_1/a.cpp.tk                              |  8
code/ZhSh_1_1/b.cpp.tk                              |  73
code/ZhSh_2_1/c.cpp.tk                              |  86
