Begin
Comparing:  code/551100kk_1_1/B.cpp.tk
code/00/test.cpp.tk                                 |  41
code/01/test.cpp.tk                                 |  41
code/551100kk_0_1/A.cpp.tk                          |  242
code/551100kk_1_1/B.cpp.tk                          |  13579
code/551100kk_2_1/C.cpp.tk                          |  285
code/achan1058_0_1/Q-A.cpp.tk                       |  19
code/achan1058_1_1/source.cpp.tk                    |  51
code/achan1058_2_1/source.cpp.tk                    |  104
code/alanubi_0_1/a.cpp.tk                           |  54
code/alanubi_1_1/b.cpp.tk                           |  118
code/alanubi_2_1/c.cpp.tk                           |  218
code/AntiForest_0_1/q1.cpp.tk                       |  95
code/AntiForest_1_1/q2.cpp.tk                       |  72
code/AntiForest_2_1/q3.cpp.tk                       |  152
code/apiad_0_1/A.cpp.tk                             |  41
code/apiad_1_1/B.cpp.tk                             |  62
code/apiad_2_1/C.cpp.tk                             |  62
code/azaky_0_1/A.cpp.tk                             |  43
code/azaky_1_1/B.cpp.tk                             |  70
code/azaky_2_1/C.cpp.tk                             |  125
code/azariamuh_0_1/standing.cpp.tk                  |  35
code/azariamuh_1_1/pancake.cpp.tk                   |  78
code/azariamuh_2_1/dijkstra.cpp.tk                  |  49
code/bmerry_0_1/a.cpp.tk                            |  96
code/bmerry_1_1/b.cpp.tk                            |  244
code/bmerry_2_1/c.cpp.tk                            |  117
code/climpet_0_1/A.cpp.tk                           |  55
code/climpet_1_1/B.cpp.tk                           |  72
code/climpet_2_1/C.cpp.tk                           |  104
code/ctzsm_0_1/A.cpp.tk                             |  68
code/ctzsm_1_1/B.cpp.tk                             |  116
code/ctzsm_2_1/C.cpp.tk                             |  190
code/DanilC_0_1/problem.cpp.tk                      |  54
code/DanilC_1_1/problemB.cpp.tk                     |  90
code/DanilC_2_1/problemC.cpp.tk                     |  246
code/DEGwer_0_1/A.cpp.tk                            |  68
code/DEGwer_1_1/B.cpp.tk                            |  86
code/DEGwer_2_1/C.cpp.tk                            |  80
code/dmute_0_1/a.cpp.tk                             |  52
code/dmute_1_1/b.cpp.tk                             |  87
code/dmute_2_1/c2.cpp.tk                            |  137
code/fagu_0_1/A.cpp.tk                              |  36
code/fagu_1_1/B.cpp.tk                              |  41
code/fagu_2_1/C.cpp.tk                              |  87
code/FatalEagle_0_1/main.cpp.tk                     |  93
code/FatalEagle_1_1/main.cpp.tk                     |  155
code/FatalEagle_2_1/main.cpp.tk                     |  454
code/fullpower_0_1/A.cpp.tk                         |  112
code/fullpower_1_1/B.cpp.tk                         |  186
code/fullpower_2_1/C.cpp.tk                         |  238
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  22
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  44
code/ICastro_2_1/Dijkstra.cpp.tk                    |  217
code/ilackthatsuperpower_0_1/a.cpp.tk               |  173
code/ilackthatsuperpower_1_1/b.cpp.tk               |  185
code/ilackthatsuperpower_2_1/c.cpp.tk               |  238
code/iridescent_0_1/A.cpp.tk                        |  28
code/iridescent_1_1/B.cpp.tk                        |  100
code/iridescent_2_1/C.cpp.tk                        |  65
code/ishraq_0_1/main.cpp.tk                         |  32
code/ishraq_1_1/main.cpp.tk                         |  53
code/ishraq_2_1/main.cpp.tk                         |  149
code/JayXon_0_1/A.cpp.tk                            |  22
code/JayXon_1_1/B.cpp.tk                            |  71
code/JayXon_2_1/C.cpp.tk                            |  83
code/Josse_0_1/A.cpp.tk                             |  43
code/Josse_1_1/B.cpp.tk                             |  82
code/Josse_2_1/C.cpp.tk                             |  225
code/kcm1700_0_1/a.cpp.tk                           |  51
code/kcm1700_1_1/b.cpp.tk                           |  197
code/kcm1700_2_1/c.cpp.tk                           |  148
code/kevinsogo_0_1/a.cpp.tk                         |  39
code/kevinsogo_1_1/b.cpp.tk                         |  57
code/kevinsogo_2_1/c.cpp.tk                         |  135
code/ksun48_0_1/A.cpp.tk                            |  10
code/ksun48_1_1/B.cpp.tk                            |  10
code/ksun48_2_1/C.cpp.tk                            |  28
code/LazyAnna_0_1/1.cpp.tk                          |  21
code/LazyAnna_1_1/2-1.cpp.tk                        |  35
code/LazyAnna_2_1/3.cpp.tk                          |  72
code/Merkurev_0_1/A.cpp.tk                          |  103
code/Merkurev_1_1/B.cpp.tk                          |  162
code/Merkurev_2_1/C.cpp.tk                          |  147
code/mezei_0_1/main.cpp.tk                          |  70
code/mezei_1_1/main.cpp.tk                          |  81
code/mezei_2_1/main.cpp.tk                          |  201
code/Mister_0_1/a.cpp.tk                            |  41
code/Mister_1_1/b.cpp.tk                            |  67
code/Mister_2_1/c.cpp.tk                            |  72
code/namonakiacc_0_1/cpp.cpp.tk                     |  56
code/namonakiacc_1_1/cpp.cpp.tk                     |  80
code/namonakiacc_2_1/cpp.cpp.tk                     |  110
code/Nicolas16_0_1/main.cpp.tk                      |  32
code/Nicolas16_1_1/main.cpp.tk                      |  29
code/Nicolas16_2_1/main.cpp.tk                      |  191
code/pandamonium_0_1/a.cpp.tk                       |  55
code/pandamonium_1_1/b.cpp.tk                       |  241
code/pandamonium_2_1/c.cpp.tk                       |  83
code/pflueger_0_1/A.cpp.tk                          |  42
code/pflueger_1_1/B.cpp.tk                          |  67
code/pflueger_2_1/C.cpp.tk                          |  137
code/ponyopoppo_0_1/A.cpp.tk                        |  22
code/ponyopoppo_1_1/B.cpp.tk                        |  100
code/ponyopoppo_2_1/C.cpp.tk                        |  265
code/Ragnar_0_1/A.cpp.tk                            |  26
code/Ragnar_1_1/B-2.cpp.tk                          |  80
code/Ragnar_2_1/C.cpp.tk                            |  80
code/saffah_0_1/t.cpp.tk                            |  34
code/saffah_1_1/t.cpp.tk                            |  49
code/saffah_2_1/t.cpp.tk                            |  164
code/SamanSami_0_1/A.cpp.tk                         |  14
code/SamanSami_1_1/B.cpp.tk                         |  62
code/SamanSami_2_1/C.cpp.tk                         |  21
code/Savlik_0_1/code.cpp.tk                         |  30
code/Savlik_1_1/code.cpp.tk                         |  35
code/Savlik_2_1/code.cpp.tk                         |  142
code/shik_0_1/pa.cpp.tk                             |  111
code/shik_1_1/pb.cpp.tk                             |  128
code/shik_2_1/pc.cpp.tk                             |  198
code/simsa.st_0_1/A.cpp.tk                          |  36
code/simsa.st_1_1/B.cpp.tk                          |  57
code/simsa.st_2_1/C.cpp.tk                          |  169
code/SovietUnion_0_1/A.cpp.tk                       |  81
code/SovietUnion_1_1/B.cpp.tk                       |  106
code/SovietUnion_2_1/C.cpp.tk                       |  167
code/tailed_0_1/A.cpp.tk                            |  26
code/tailed_1_1/B.cpp.tk                            |  68
code/tailed_2_1/C.cpp.tk                            |  84
code/TheNatural_0_1/A.cpp.tk                        |  50
code/TheNatural_1_1/B.cpp.tk                        |  109
code/TheNatural_2_1/C.cpp.tk                        |  58
code/TrueBamboo_0_1/test.cpp.tk                     |  89
code/TrueBamboo_1_1/test.cpp.tk                     |  234
code/TrueBamboo_2_1/test.cpp.tk                     |  152
code/tur.turczyn_0_1/A.cpp.tk                       |  23
code/tur.turczyn_1_1/B.cpp.tk                       |  42
code/tur.turczyn_2_1/C.cpp.tk                       |  54
code/Tyg3R_0_1/A.cpp.tk                             |  25
code/Tyg3R_1_1/B.cpp.tk                             |  48
code/Tyg3R_2_1/C.cpp.tk                             |  39
code/UminchuR_0_1/main.cpp.tk                       |  78
code/UminchuR_1_1/main.cpp.tk                       |  156
code/UminchuR_2_1/main.cpp.tk                       |  150
code/wo..._0_1/a.cpp.tk                             |  75
code/wo..._1_1/b.cpp.tk                             |  81
code/wo..._2_1/c.cpp.tk                             |  174
code/yswtt_0_1/A.cpp.tk                             |  19
code/yswtt_1_1/B.cpp.tk                             |  100
code/yswtt_2_1/C.cpp.tk                             |  79
code/ZhSh_0_1/a.cpp.tk                              |  20
code/ZhSh_1_1/b.cpp.tk                              |  125
code/ZhSh_2_1/c.cpp.tk                              |  127
