Begin
Comparing:  code/bmerry_1_1/b.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  12
code/551100kk_1_1/B.cpp.tk                          |  53
code/551100kk_2_1/C.cpp.tk                          |  43
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  38
code/achan1058_2_1/source.cpp.tk                    |  60
code/alanubi_0_1/a.cpp.tk                           |  22
code/alanubi_1_1/b.cpp.tk                           |  42
code/alanubi_2_1/c.cpp.tk                           |  111
code/AntiForest_0_1/q1.cpp.tk                       |  15
code/AntiForest_1_1/q2.cpp.tk                       |  8
code/AntiForest_2_1/q3.cpp.tk                       |  50
code/apiad_0_1/A.cpp.tk                             |  17
code/apiad_1_1/B.cpp.tk                             |  26
code/apiad_2_1/C.cpp.tk                             |  28
code/azaky_0_1/A.cpp.tk                             |  22
code/azaky_1_1/B.cpp.tk                             |  27
code/azaky_2_1/C.cpp.tk                             |  59
code/azariamuh_0_1/standing.cpp.tk                  |  10
code/azariamuh_1_1/pancake.cpp.tk                   |  23
code/azariamuh_2_1/dijkstra.cpp.tk                  |  21
code/bmerry_0_1/a.cpp.tk                            |  35496
code/bmerry_1_1/b.cpp.tk                            |  76176
code/bmerry_2_1/c.cpp.tk                            |  24761
code/climpet_0_1/A.cpp.tk                           |  36
code/climpet_1_1/B.cpp.tk                           |  48
code/climpet_2_1/C.cpp.tk                           |  61
code/ctzsm_0_1/A.cpp.tk                             |  17
code/ctzsm_1_1/B.cpp.tk                             |  34
code/ctzsm_2_1/C.cpp.tk                             |  86
code/DanilC_0_1/problem.cpp.tk                      |  33
code/DanilC_1_1/problemB.cpp.tk                     |  53
code/DanilC_2_1/problemC.cpp.tk                     |  104
code/DEGwer_0_1/A.cpp.tk                            |  34
code/DEGwer_1_1/B.cpp.tk                            |  49
code/DEGwer_2_1/C.cpp.tk                            |  48
code/dmute_0_1/a.cpp.tk                             |  13
code/dmute_1_1/b.cpp.tk                             |  24
code/dmute_2_1/c2.cpp.tk                            |  61
code/fagu_0_1/A.cpp.tk                              |  20
code/fagu_1_1/B.cpp.tk                              |  20
code/fagu_2_1/C.cpp.tk                              |  46
code/FatalEagle_0_1/main.cpp.tk                     |  18
code/FatalEagle_1_1/main.cpp.tk                     |  62
code/FatalEagle_2_1/main.cpp.tk                     |  212
code/fullpower_0_1/A.cpp.tk                         |  30
code/fullpower_1_1/B.cpp.tk                         |  55
code/fullpower_2_1/C.cpp.tk                         |  84
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  17
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  46
code/ICastro_2_1/Dijkstra.cpp.tk                    |  106
code/ilackthatsuperpower_0_1/a.cpp.tk               |  96
code/ilackthatsuperpower_1_1/b.cpp.tk               |  106
code/ilackthatsuperpower_2_1/c.cpp.tk               |  129
code/iridescent_0_1/A.cpp.tk                        |  16
code/iridescent_1_1/B.cpp.tk                        |  39
code/iridescent_2_1/C.cpp.tk                        |  37
code/ishraq_0_1/main.cpp.tk                         |  9
code/ishraq_1_1/main.cpp.tk                         |  17
code/ishraq_2_1/main.cpp.tk                         |  64
code/JayXon_0_1/A.cpp.tk                            |  9
code/JayXon_1_1/B.cpp.tk                            |  52
code/JayXon_2_1/C.cpp.tk                            |  33
code/Josse_0_1/A.cpp.tk                             |  28
code/Josse_1_1/B.cpp.tk                             |  52
code/Josse_2_1/C.cpp.tk                             |  115
code/kcm1700_0_1/a.cpp.tk                           |  14
code/kcm1700_1_1/b.cpp.tk                           |  64
code/kcm1700_2_1/c.cpp.tk                           |  65
code/kevinsogo_0_1/a.cpp.tk                         |  11
code/kevinsogo_1_1/b.cpp.tk                         |  15
code/kevinsogo_2_1/c.cpp.tk                         |  55
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  12
code/LazyAnna_1_1/2-1.cpp.tk                        |  25
code/LazyAnna_2_1/3.cpp.tk                          |  32
code/Merkurev_0_1/A.cpp.tk                          |  22
code/Merkurev_1_1/B.cpp.tk                          |  59
code/Merkurev_2_1/C.cpp.tk                          |  52
code/mezei_0_1/main.cpp.tk                          |  22
code/mezei_1_1/main.cpp.tk                          |  43
code/mezei_2_1/main.cpp.tk                          |  79
code/Mister_0_1/a.cpp.tk                            |  15
code/Mister_1_1/b.cpp.tk                            |  27
code/Mister_2_1/c.cpp.tk                            |  37
code/namonakiacc_0_1/cpp.cpp.tk                     |  31
code/namonakiacc_1_1/cpp.cpp.tk                     |  36
code/namonakiacc_2_1/cpp.cpp.tk                     |  59
code/Nicolas16_0_1/main.cpp.tk                      |  8
code/Nicolas16_1_1/main.cpp.tk                      |  8
code/Nicolas16_2_1/main.cpp.tk                      |  72
code/pandamonium_0_1/a.cpp.tk                       |  15
code/pandamonium_1_1/b.cpp.tk                       |  72
code/pandamonium_2_1/c.cpp.tk                       |  32
code/pflueger_0_1/A.cpp.tk                          |  18
code/pflueger_1_1/B.cpp.tk                          |  59
code/pflueger_2_1/C.cpp.tk                          |  81
code/ponyopoppo_0_1/A.cpp.tk                        |  12
code/ponyopoppo_1_1/B.cpp.tk                        |  36
code/ponyopoppo_2_1/C.cpp.tk                        |  116
code/Ragnar_0_1/A.cpp.tk                            |  21
code/Ragnar_1_1/B-2.cpp.tk                          |  42
code/Ragnar_2_1/C.cpp.tk                            |  47
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  14
code/saffah_2_1/t.cpp.tk                            |  76
code/SamanSami_0_1/A.cpp.tk                         |  9
code/SamanSami_1_1/B.cpp.tk                         |  50
code/SamanSami_2_1/C.cpp.tk                         |  11
code/Savlik_0_1/code.cpp.tk                         |  12
code/Savlik_1_1/code.cpp.tk                         |  14
code/Savlik_2_1/code.cpp.tk                         |  58
code/shik_0_1/pa.cpp.tk                             |  52
code/shik_1_1/pb.cpp.tk                             |  57
code/shik_2_1/pc.cpp.tk                             |  83
code/simsa.st_0_1/A.cpp.tk                          |  10
code/simsa.st_1_1/B.cpp.tk                          |  15
code/simsa.st_2_1/C.cpp.tk                          |  74
code/SovietUnion_0_1/A.cpp.tk                       |  20
code/SovietUnion_1_1/B.cpp.tk                       |  26
code/SovietUnion_2_1/C.cpp.tk                       |  63
code/tailed_0_1/A.cpp.tk                            |  14
code/tailed_1_1/B.cpp.tk                            |  27
code/tailed_2_1/C.cpp.tk                            |  32
code/TheNatural_0_1/A.cpp.tk                        |  21
code/TheNatural_1_1/B.cpp.tk                        |  51
code/TheNatural_2_1/C.cpp.tk                        |  27
code/TrueBamboo_0_1/test.cpp.tk                     |  14
code/TrueBamboo_1_1/test.cpp.tk                     |  45
code/TrueBamboo_2_1/test.cpp.tk                     |  47
code/tur.turczyn_0_1/A.cpp.tk                       |  19
code/tur.turczyn_1_1/B.cpp.tk                       |  29
code/tur.turczyn_2_1/C.cpp.tk                       |  31
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  16
code/Tyg3R_2_1/C.cpp.tk                             |  18
code/UminchuR_0_1/main.cpp.tk                       |  27
code/UminchuR_1_1/main.cpp.tk                       |  45
code/UminchuR_2_1/main.cpp.tk                       |  54
code/wo..._0_1/a.cpp.tk                             |  29
code/wo..._1_1/b.cpp.tk                             |  37
code/wo..._2_1/c.cpp.tk                             |  81
code/yswtt_0_1/A.cpp.tk                             |  14
code/yswtt_1_1/B.cpp.tk                             |  44
code/yswtt_2_1/C.cpp.tk                             |  37
code/ZhSh_0_1/a.cpp.tk                              |  16
code/ZhSh_1_1/b.cpp.tk                              |  70
code/ZhSh_2_1/c.cpp.tk                              |  85
