Begin
Comparing:  code/AntiForest_2_1/q3.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  19
code/551100kk_1_1/B.cpp.tk                          |  28
code/551100kk_2_1/C.cpp.tk                          |  252
code/achan1058_0_1/Q-A.cpp.tk                       |  10
code/achan1058_1_1/source.cpp.tk                    |  22
code/achan1058_2_1/source.cpp.tk                    |  47
code/alanubi_0_1/a.cpp.tk                           |  12
code/alanubi_1_1/b.cpp.tk                           |  19
code/alanubi_2_1/c.cpp.tk                           |  73
code/AntiForest_0_1/q1.cpp.tk                       |  55
code/AntiForest_1_1/q2.cpp.tk                       |  43
code/AntiForest_2_1/q3.cpp.tk                       |  78333
code/apiad_0_1/A.cpp.tk                             |  16
code/apiad_1_1/B.cpp.tk                             |  25
code/apiad_2_1/C.cpp.tk                             |  68
code/azaky_0_1/A.cpp.tk                             |  26
code/azaky_1_1/B.cpp.tk                             |  31
code/azaky_2_1/C.cpp.tk                             |  89
code/azariamuh_0_1/standing.cpp.tk                  |  18
code/azariamuh_1_1/pancake.cpp.tk                   |  37
code/azariamuh_2_1/dijkstra.cpp.tk                  |  41
code/bmerry_0_1/a.cpp.tk                            |  38
code/bmerry_1_1/b.cpp.tk                            |  44
code/bmerry_2_1/c.cpp.tk                            |  65
code/climpet_0_1/A.cpp.tk                           |  21
code/climpet_1_1/B.cpp.tk                           |  25
code/climpet_2_1/C.cpp.tk                           |  70
code/ctzsm_0_1/A.cpp.tk                             |  29
code/ctzsm_1_1/B.cpp.tk                             |  34
code/ctzsm_2_1/C.cpp.tk                             |  128
code/DanilC_0_1/problem.cpp.tk                      |  22
code/DanilC_1_1/problemB.cpp.tk                     |  40
code/DanilC_2_1/problemC.cpp.tk                     |  84
code/DEGwer_0_1/A.cpp.tk                            |  19
code/DEGwer_1_1/B.cpp.tk                            |  21
code/DEGwer_2_1/C.cpp.tk                            |  310
code/dmute_0_1/a.cpp.tk                             |  9
code/dmute_1_1/b.cpp.tk                             |  18
code/dmute_2_1/c2.cpp.tk                            |  51
code/fagu_0_1/A.cpp.tk                              |  8
code/fagu_1_1/B.cpp.tk                              |  8
code/fagu_2_1/C.cpp.tk                              |  63
code/FatalEagle_0_1/main.cpp.tk                     |  21
code/FatalEagle_1_1/main.cpp.tk                     |  30
code/FatalEagle_2_1/main.cpp.tk                     |  161
code/fullpower_0_1/A.cpp.tk                         |  39
code/fullpower_1_1/B.cpp.tk                         |  41
code/fullpower_2_1/C.cpp.tk                         |  97
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  8
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  15
code/ICastro_2_1/Dijkstra.cpp.tk                    |  103
code/ilackthatsuperpower_0_1/a.cpp.tk               |  64
code/ilackthatsuperpower_1_1/b.cpp.tk               |  63
code/ilackthatsuperpower_2_1/c.cpp.tk               |  102
code/iridescent_0_1/A.cpp.tk                        |  8
code/iridescent_1_1/B.cpp.tk                        |  11
code/iridescent_2_1/C.cpp.tk                        |  42
code/ishraq_0_1/main.cpp.tk                         |  13
code/ishraq_1_1/main.cpp.tk                         |  17
code/ishraq_2_1/main.cpp.tk                         |  72
code/JayXon_0_1/A.cpp.tk                            |  6
code/JayXon_1_1/B.cpp.tk                            |  19
code/JayXon_2_1/C.cpp.tk                            |  35
code/Josse_0_1/A.cpp.tk                             |  9
code/Josse_1_1/B.cpp.tk                             |  15
code/Josse_2_1/C.cpp.tk                             |  74
code/kcm1700_0_1/a.cpp.tk                           |  11
code/kcm1700_1_1/b.cpp.tk                           |  16
code/kcm1700_2_1/c.cpp.tk                           |  62
code/kevinsogo_0_1/a.cpp.tk                         |  12
code/kevinsogo_1_1/b.cpp.tk                         |  16
code/kevinsogo_2_1/c.cpp.tk                         |  72
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  16
code/LazyAnna_0_1/1.cpp.tk                          |  8
code/LazyAnna_1_1/2-1.cpp.tk                        |  12
code/LazyAnna_2_1/3.cpp.tk                          |  44
code/Merkurev_0_1/A.cpp.tk                          |  25
code/Merkurev_1_1/B.cpp.tk                          |  37
code/Merkurev_2_1/C.cpp.tk                          |  44
code/mezei_0_1/main.cpp.tk                          |  17
code/mezei_1_1/main.cpp.tk                          |  16
code/mezei_2_1/main.cpp.tk                          |  72
code/Mister_0_1/a.cpp.tk                            |  11
code/Mister_1_1/b.cpp.tk                            |  15
code/Mister_2_1/c.cpp.tk                            |  244
code/namonakiacc_0_1/cpp.cpp.tk                     |  21
code/namonakiacc_1_1/cpp.cpp.tk                     |  25
code/namonakiacc_2_1/cpp.cpp.tk                     |  181
code/Nicolas16_0_1/main.cpp.tk                      |  6
code/Nicolas16_1_1/main.cpp.tk                      |  6
code/Nicolas16_2_1/main.cpp.tk                      |  70
code/pandamonium_0_1/a.cpp.tk                       |  10
code/pandamonium_1_1/b.cpp.tk                       |  39
code/pandamonium_2_1/c.cpp.tk                       |  24
code/pflueger_0_1/A.cpp.tk                          |  9
code/pflueger_1_1/B.cpp.tk                          |  15
code/pflueger_2_1/C.cpp.tk                          |  56
code/ponyopoppo_0_1/A.cpp.tk                        |  9
code/ponyopoppo_1_1/B.cpp.tk                        |  19
code/ponyopoppo_2_1/C.cpp.tk                        |  127
code/Ragnar_0_1/A.cpp.tk                            |  11
code/Ragnar_1_1/B-2.cpp.tk                          |  17
code/Ragnar_2_1/C.cpp.tk                            |  38
code/saffah_0_1/t.cpp.tk                            |  17
code/saffah_1_1/t.cpp.tk                            |  22
code/saffah_2_1/t.cpp.tk                            |  85
code/SamanSami_0_1/A.cpp.tk                         |  2
code/SamanSami_1_1/B.cpp.tk                         |  12
code/SamanSami_2_1/C.cpp.tk                         |  10
code/Savlik_0_1/code.cpp.tk                         |  8
code/Savlik_1_1/code.cpp.tk                         |  12
code/Savlik_2_1/code.cpp.tk                         |  50
code/shik_0_1/pa.cpp.tk                             |  48
code/shik_1_1/pb.cpp.tk                             |  48
code/shik_2_1/pc.cpp.tk                             |  355
code/simsa.st_0_1/A.cpp.tk                          |  18
code/simsa.st_1_1/B.cpp.tk                          |  21
code/simsa.st_2_1/C.cpp.tk                          |  75
code/SovietUnion_0_1/A.cpp.tk                       |  33
code/SovietUnion_1_1/B.cpp.tk                       |  37
code/SovietUnion_2_1/C.cpp.tk                       |  72
code/tailed_0_1/A.cpp.tk                            |  8
code/tailed_1_1/B.cpp.tk                            |  12
code/tailed_2_1/C.cpp.tk                            |  50
code/TheNatural_0_1/A.cpp.tk                        |  10
code/TheNatural_1_1/B.cpp.tk                        |  13
code/TheNatural_2_1/C.cpp.tk                        |  41
code/TrueBamboo_0_1/test.cpp.tk                     |  14
code/TrueBamboo_1_1/test.cpp.tk                     |  18
code/TrueBamboo_2_1/test.cpp.tk                     |  52
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  16
code/tur.turczyn_2_1/C.cpp.tk                       |  39
code/Tyg3R_0_1/A.cpp.tk                             |  13
code/Tyg3R_1_1/B.cpp.tk                             |  31
code/Tyg3R_2_1/C.cpp.tk                             |  57
code/UminchuR_0_1/main.cpp.tk                       |  25
code/UminchuR_1_1/main.cpp.tk                       |  33
code/UminchuR_2_1/main.cpp.tk                       |  64
code/wo..._0_1/a.cpp.tk                             |  17
code/wo..._1_1/b.cpp.tk                             |  19
code/wo..._2_1/c.cpp.tk                             |  268
code/yswtt_0_1/A.cpp.tk                             |  6
code/yswtt_1_1/B.cpp.tk                             |  15
code/yswtt_2_1/C.cpp.tk                             |  39
code/ZhSh_0_1/a.cpp.tk                              |  7
code/ZhSh_1_1/b.cpp.tk                              |  48
code/ZhSh_2_1/c.cpp.tk                              |  152
