Begin
Comparing:  code/DanilC_0_1/problem.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  11
code/551100kk_1_1/B.cpp.tk                          |  16
code/551100kk_2_1/C.cpp.tk                          |  29
code/achan1058_0_1/Q-A.cpp.tk                       |  10
code/achan1058_1_1/source.cpp.tk                    |  20
code/achan1058_2_1/source.cpp.tk                    |  39
code/alanubi_0_1/a.cpp.tk                           |  23
code/alanubi_1_1/b.cpp.tk                           |  22
code/alanubi_2_1/c.cpp.tk                           |  78
code/AntiForest_0_1/q1.cpp.tk                       |  13
code/AntiForest_1_1/q2.cpp.tk                       |  5
code/AntiForest_2_1/q3.cpp.tk                       |  39
code/apiad_0_1/A.cpp.tk                             |  13
code/apiad_1_1/B.cpp.tk                             |  16
code/apiad_2_1/C.cpp.tk                             |  20
code/azaky_0_1/A.cpp.tk                             |  16
code/azaky_1_1/B.cpp.tk                             |  18
code/azaky_2_1/C.cpp.tk                             |  47
code/azariamuh_0_1/standing.cpp.tk                  |  11
code/azariamuh_1_1/pancake.cpp.tk                   |  19
code/azariamuh_2_1/dijkstra.cpp.tk                  |  16
code/bmerry_0_1/a.cpp.tk                            |  48
code/bmerry_1_1/b.cpp.tk                            |  51
code/bmerry_2_1/c.cpp.tk                            |  51
code/climpet_0_1/A.cpp.tk                           |  63
code/climpet_1_1/B.cpp.tk                           |  51
code/climpet_2_1/C.cpp.tk                           |  71
code/ctzsm_0_1/A.cpp.tk                             |  43
code/ctzsm_1_1/B.cpp.tk                             |  34
code/ctzsm_2_1/C.cpp.tk                             |  81
code/DanilC_0_1/problem.cpp.tk                      |  31909
code/DanilC_1_1/problemB.cpp.tk                     |  337
code/DanilC_2_1/problemC.cpp.tk                     |  244
code/DEGwer_0_1/A.cpp.tk                            |  29
code/DEGwer_1_1/B.cpp.tk                            |  29
code/DEGwer_2_1/C.cpp.tk                            |  26
code/dmute_0_1/a.cpp.tk                             |  20
code/dmute_1_1/b.cpp.tk                             |  36
code/dmute_2_1/c2.cpp.tk                            |  51
code/fagu_0_1/A.cpp.tk                              |  7
code/fagu_1_1/B.cpp.tk                              |  7
code/fagu_2_1/C.cpp.tk                              |  28
code/FatalEagle_0_1/main.cpp.tk                     |  24
code/FatalEagle_1_1/main.cpp.tk                     |  41
code/FatalEagle_2_1/main.cpp.tk                     |  137
code/fullpower_0_1/A.cpp.tk                         |  33
code/fullpower_1_1/B.cpp.tk                         |  52
code/fullpower_2_1/C.cpp.tk                         |  83
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  35
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  30
code/ICastro_2_1/Dijkstra.cpp.tk                    |  74
code/ilackthatsuperpower_0_1/a.cpp.tk               |  106
code/ilackthatsuperpower_1_1/b.cpp.tk               |  90
code/ilackthatsuperpower_2_1/c.cpp.tk               |  108
code/iridescent_0_1/A.cpp.tk                        |  18
code/iridescent_1_1/B.cpp.tk                        |  37
code/iridescent_2_1/C.cpp.tk                        |  31
code/ishraq_0_1/main.cpp.tk                         |  9
code/ishraq_1_1/main.cpp.tk                         |  16
code/ishraq_2_1/main.cpp.tk                         |  46
code/JayXon_0_1/A.cpp.tk                            |  13
code/JayXon_1_1/B.cpp.tk                            |  28
code/JayXon_2_1/C.cpp.tk                            |  26
code/Josse_0_1/A.cpp.tk                             |  21
code/Josse_1_1/B.cpp.tk                             |  27
code/Josse_2_1/C.cpp.tk                             |  72
code/kcm1700_0_1/a.cpp.tk                           |  24
code/kcm1700_1_1/b.cpp.tk                           |  28
code/kcm1700_2_1/c.cpp.tk                           |  55
code/kevinsogo_0_1/a.cpp.tk                         |  10
code/kevinsogo_1_1/b.cpp.tk                         |  12
code/kevinsogo_2_1/c.cpp.tk                         |  40
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  9
code/LazyAnna_0_1/1.cpp.tk                          |  44
code/LazyAnna_1_1/2-1.cpp.tk                        |  40
code/LazyAnna_2_1/3.cpp.tk                          |  40
code/Merkurev_0_1/A.cpp.tk                          |  34
code/Merkurev_1_1/B.cpp.tk                          |  38
code/Merkurev_2_1/C.cpp.tk                          |  44
code/mezei_0_1/main.cpp.tk                          |  36
code/mezei_1_1/main.cpp.tk                          |  26
code/mezei_2_1/main.cpp.tk                          |  55
code/Mister_0_1/a.cpp.tk                            |  38
code/Mister_1_1/b.cpp.tk                            |  33
code/Mister_2_1/c.cpp.tk                            |  55
code/namonakiacc_0_1/cpp.cpp.tk                     |  17
code/namonakiacc_1_1/cpp.cpp.tk                     |  19
code/namonakiacc_2_1/cpp.cpp.tk                     |  34
code/Nicolas16_0_1/main.cpp.tk                      |  10
code/Nicolas16_1_1/main.cpp.tk                      |  10
code/Nicolas16_2_1/main.cpp.tk                      |  70
code/pandamonium_0_1/a.cpp.tk                       |  21
code/pandamonium_1_1/b.cpp.tk                       |  36
code/pandamonium_2_1/c.cpp.tk                       |  26
code/pflueger_0_1/A.cpp.tk                          |  26
code/pflueger_1_1/B.cpp.tk                          |  30
code/pflueger_2_1/C.cpp.tk                          |  54
code/ponyopoppo_0_1/A.cpp.tk                        |  12
code/ponyopoppo_1_1/B.cpp.tk                        |  19
code/ponyopoppo_2_1/C.cpp.tk                        |  86
code/Ragnar_0_1/A.cpp.tk                            |  16
code/Ragnar_1_1/B-2.cpp.tk                          |  20
code/Ragnar_2_1/C.cpp.tk                            |  37
code/saffah_0_1/t.cpp.tk                            |  8
code/saffah_1_1/t.cpp.tk                            |  11
code/saffah_2_1/t.cpp.tk                            |  59
code/SamanSami_0_1/A.cpp.tk                         |  9
code/SamanSami_1_1/B.cpp.tk                         |  30
code/SamanSami_2_1/C.cpp.tk                         |  7
code/Savlik_0_1/code.cpp.tk                         |  20
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  50
code/shik_0_1/pa.cpp.tk                             |  48
code/shik_1_1/pb.cpp.tk                             |  49
code/shik_2_1/pc.cpp.tk                             |  71
code/simsa.st_0_1/A.cpp.tk                          |  10
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  53
code/SovietUnion_0_1/A.cpp.tk                       |  49
code/SovietUnion_1_1/B.cpp.tk                       |  71
code/SovietUnion_2_1/C.cpp.tk                       |  64
code/tailed_0_1/A.cpp.tk                            |  17
code/tailed_1_1/B.cpp.tk                            |  25
code/tailed_2_1/C.cpp.tk                            |  29
code/TheNatural_0_1/A.cpp.tk                        |  35
code/TheNatural_1_1/B.cpp.tk                        |  35
code/TheNatural_2_1/C.cpp.tk                        |  24
code/TrueBamboo_0_1/test.cpp.tk                     |  15
code/TrueBamboo_1_1/test.cpp.tk                     |  18
code/TrueBamboo_2_1/test.cpp.tk                     |  34
code/tur.turczyn_0_1/A.cpp.tk                       |  12
code/tur.turczyn_1_1/B.cpp.tk                       |  19
code/tur.turczyn_2_1/C.cpp.tk                       |  21
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  18
code/UminchuR_0_1/main.cpp.tk                       |  17
code/UminchuR_1_1/main.cpp.tk                       |  22
code/UminchuR_2_1/main.cpp.tk                       |  39
code/wo..._0_1/a.cpp.tk                             |  27
code/wo..._1_1/b.cpp.tk                             |  31
code/wo..._2_1/c.cpp.tk                             |  63
code/yswtt_0_1/A.cpp.tk                             |  41
code/yswtt_1_1/B.cpp.tk                             |  36
code/yswtt_2_1/C.cpp.tk                             |  47
code/ZhSh_0_1/a.cpp.tk                              |  53
code/ZhSh_1_1/b.cpp.tk                              |  77
code/ZhSh_2_1/c.cpp.tk                              |  83
