Begin
Comparing:  code/Savlik_0_1/code.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  55
code/551100kk_1_1/B.cpp.tk                          |  31
code/551100kk_2_1/C.cpp.tk                          |  42
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  30
code/achan1058_2_1/source.cpp.tk                    |  59
code/alanubi_0_1/a.cpp.tk                           |  94
code/alanubi_1_1/b.cpp.tk                           |  31
code/alanubi_2_1/c.cpp.tk                           |  126
code/AntiForest_0_1/q1.cpp.tk                       |  56
code/AntiForest_1_1/q2.cpp.tk                       |  9
code/AntiForest_2_1/q3.cpp.tk                       |  53
code/apiad_0_1/A.cpp.tk                             |  22
code/apiad_1_1/B.cpp.tk                             |  24
code/apiad_2_1/C.cpp.tk                             |  25
code/azaky_0_1/A.cpp.tk                             |  52
code/azaky_1_1/B.cpp.tk                             |  27
code/azaky_2_1/C.cpp.tk                             |  52
code/azariamuh_0_1/standing.cpp.tk                  |  27
code/azariamuh_1_1/pancake.cpp.tk                   |  26
code/azariamuh_2_1/dijkstra.cpp.tk                  |  24
code/bmerry_0_1/a.cpp.tk                            |  123
code/bmerry_1_1/b.cpp.tk                            |  64
code/bmerry_2_1/c.cpp.tk                            |  64
code/climpet_0_1/A.cpp.tk                           |  65
code/climpet_1_1/B.cpp.tk                           |  46
code/climpet_2_1/C.cpp.tk                           |  72
code/ctzsm_0_1/A.cpp.tk                             |  115
code/ctzsm_1_1/B.cpp.tk                             |  35
code/ctzsm_2_1/C.cpp.tk                             |  80
code/DanilC_0_1/problem.cpp.tk                      |  67
code/DanilC_1_1/problemB.cpp.tk                     |  61
code/DanilC_2_1/problemC.cpp.tk                     |  110
code/DEGwer_0_1/A.cpp.tk                            |  63
code/DEGwer_1_1/B.cpp.tk                            |  44
code/DEGwer_2_1/C.cpp.tk                            |  38
code/dmute_0_1/a.cpp.tk                             |  50
code/dmute_1_1/b.cpp.tk                             |  84
code/dmute_2_1/c2.cpp.tk                            |  85
code/fagu_0_1/A.cpp.tk                              |  13
code/fagu_1_1/B.cpp.tk                              |  13
code/fagu_2_1/C.cpp.tk                              |  34
code/FatalEagle_0_1/main.cpp.tk                     |  59
code/FatalEagle_1_1/main.cpp.tk                     |  96
code/FatalEagle_2_1/main.cpp.tk                     |  178
code/fullpower_0_1/A.cpp.tk                         |  64
code/fullpower_1_1/B.cpp.tk                         |  107
code/fullpower_2_1/C.cpp.tk                         |  145
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  44
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  34
code/ICastro_2_1/Dijkstra.cpp.tk                    |  97
code/ilackthatsuperpower_0_1/a.cpp.tk               |  113
code/ilackthatsuperpower_1_1/b.cpp.tk               |  103
code/ilackthatsuperpower_2_1/c.cpp.tk               |  112
code/iridescent_0_1/A.cpp.tk                        |  33
code/iridescent_1_1/B.cpp.tk                        |  81
code/iridescent_2_1/C.cpp.tk                        |  53
code/ishraq_0_1/main.cpp.tk                         |  13
code/ishraq_1_1/main.cpp.tk                         |  28
code/ishraq_2_1/main.cpp.tk                         |  56
code/JayXon_0_1/A.cpp.tk                            |  56
code/JayXon_1_1/B.cpp.tk                            |  41
code/JayXon_2_1/C.cpp.tk                            |  34
code/Josse_0_1/A.cpp.tk                             |  42
code/Josse_1_1/B.cpp.tk                             |  35
code/Josse_2_1/C.cpp.tk                             |  90
code/kcm1700_0_1/a.cpp.tk                           |  105
code/kcm1700_1_1/b.cpp.tk                           |  58
code/kcm1700_2_1/c.cpp.tk                           |  79
code/kevinsogo_0_1/a.cpp.tk                         |  48
code/kevinsogo_1_1/b.cpp.tk                         |  22
code/kevinsogo_2_1/c.cpp.tk                         |  50
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  15
code/LazyAnna_0_1/1.cpp.tk                          |  52
code/LazyAnna_1_1/2-1.cpp.tk                        |  36
code/LazyAnna_2_1/3.cpp.tk                          |  36
code/Merkurev_0_1/A.cpp.tk                          |  109
code/Merkurev_1_1/B.cpp.tk                          |  63
code/Merkurev_2_1/C.cpp.tk                          |  75
code/mezei_0_1/main.cpp.tk                          |  106
code/mezei_1_1/main.cpp.tk                          |  44
code/mezei_2_1/main.cpp.tk                          |  82
code/Mister_0_1/a.cpp.tk                            |  25
code/Mister_1_1/b.cpp.tk                            |  28
code/Mister_2_1/c.cpp.tk                            |  46
code/namonakiacc_0_1/cpp.cpp.tk                     |  29
code/namonakiacc_1_1/cpp.cpp.tk                     |  32
code/namonakiacc_2_1/cpp.cpp.tk                     |  47
code/Nicolas16_0_1/main.cpp.tk                      |  24
code/Nicolas16_1_1/main.cpp.tk                      |  23
code/Nicolas16_2_1/main.cpp.tk                      |  125
code/pandamonium_0_1/a.cpp.tk                       |  57
code/pandamonium_1_1/b.cpp.tk                       |  56
code/pandamonium_2_1/c.cpp.tk                       |  47
code/pflueger_0_1/A.cpp.tk                          |  84
code/pflueger_1_1/B.cpp.tk                          |  48
code/pflueger_2_1/C.cpp.tk                          |  79
code/ponyopoppo_0_1/A.cpp.tk                        |  31
code/ponyopoppo_1_1/B.cpp.tk                        |  26
code/ponyopoppo_2_1/C.cpp.tk                        |  110
code/Ragnar_0_1/A.cpp.tk                            |  72
code/Ragnar_1_1/B-2.cpp.tk                          |  31
code/Ragnar_2_1/C.cpp.tk                            |  61
code/saffah_0_1/t.cpp.tk                            |  31
code/saffah_1_1/t.cpp.tk                            |  16
code/saffah_2_1/t.cpp.tk                            |  68
code/SamanSami_0_1/A.cpp.tk                         |  22
code/SamanSami_1_1/B.cpp.tk                         |  54
code/SamanSami_2_1/C.cpp.tk                         |  11
code/Savlik_0_1/code.cpp.tk                         |  2842
code/Savlik_1_1/code.cpp.tk                         |  80
code/Savlik_2_1/code.cpp.tk                         |  69
code/shik_0_1/pa.cpp.tk                             |  85
code/shik_1_1/pb.cpp.tk                             |  57
code/shik_2_1/pc.cpp.tk                             |  78
code/simsa.st_0_1/A.cpp.tk                          |  13
code/simsa.st_1_1/B.cpp.tk                          |  17
code/simsa.st_2_1/C.cpp.tk                          |  73
code/SovietUnion_0_1/A.cpp.tk                       |  41
code/SovietUnion_1_1/B.cpp.tk                       |  55
code/SovietUnion_2_1/C.cpp.tk                       |  70
code/tailed_0_1/A.cpp.tk                            |  134
code/tailed_1_1/B.cpp.tk                            |  46
code/tailed_2_1/C.cpp.tk                            |  41
code/TheNatural_0_1/A.cpp.tk                        |  129
code/TheNatural_1_1/B.cpp.tk                        |  77
code/TheNatural_2_1/C.cpp.tk                        |  43
code/TrueBamboo_0_1/test.cpp.tk                     |  29
code/TrueBamboo_1_1/test.cpp.tk                     |  30
code/TrueBamboo_2_1/test.cpp.tk                     |  51
code/tur.turczyn_0_1/A.cpp.tk                       |  21
code/tur.turczyn_1_1/B.cpp.tk                       |  33
code/tur.turczyn_2_1/C.cpp.tk                       |  33
code/Tyg3R_0_1/A.cpp.tk                             |  29
code/Tyg3R_1_1/B.cpp.tk                             |  27
code/Tyg3R_2_1/C.cpp.tk                             |  31
code/UminchuR_0_1/main.cpp.tk                       |  31
code/UminchuR_1_1/main.cpp.tk                       |  38
code/UminchuR_2_1/main.cpp.tk                       |  61
code/wo..._0_1/a.cpp.tk                             |  53
code/wo..._1_1/b.cpp.tk                             |  56
code/wo..._2_1/c.cpp.tk                             |  97
code/yswtt_0_1/A.cpp.tk                             |  66
code/yswtt_1_1/B.cpp.tk                             |  29
code/yswtt_2_1/C.cpp.tk                             |  60
code/ZhSh_0_1/a.cpp.tk                              |  51
code/ZhSh_1_1/b.cpp.tk                              |  80
code/ZhSh_2_1/c.cpp.tk                              |  74
