Begin
Comparing:  code/Tyg3R_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  19
code/551100kk_1_1/B.cpp.tk                          |  26
code/551100kk_2_1/C.cpp.tk                          |  50
code/achan1058_0_1/Q-A.cpp.tk                       |  26
code/achan1058_1_1/source.cpp.tk                    |  44
code/achan1058_2_1/source.cpp.tk                    |  76
code/alanubi_0_1/a.cpp.tk                           |  26
code/alanubi_1_1/b.cpp.tk                           |  22
code/alanubi_2_1/c.cpp.tk                           |  80
code/AntiForest_0_1/q1.cpp.tk                       |  46
code/AntiForest_1_1/q2.cpp.tk                       |  15
code/AntiForest_2_1/q3.cpp.tk                       |  84
code/apiad_0_1/A.cpp.tk                             |  27
code/apiad_1_1/B.cpp.tk                             |  33
code/apiad_2_1/C.cpp.tk                             |  34
code/azaky_0_1/A.cpp.tk                             |  33
code/azaky_1_1/B.cpp.tk                             |  33
code/azaky_2_1/C.cpp.tk                             |  70
code/azariamuh_0_1/standing.cpp.tk                  |  34
code/azariamuh_1_1/pancake.cpp.tk                   |  48
code/azariamuh_2_1/dijkstra.cpp.tk                  |  31
code/bmerry_0_1/a.cpp.tk                            |  61
code/bmerry_1_1/b.cpp.tk                            |  64
code/bmerry_2_1/c.cpp.tk                            |  71
code/climpet_0_1/A.cpp.tk                           |  42
code/climpet_1_1/B.cpp.tk                           |  37
code/climpet_2_1/C.cpp.tk                           |  63
code/ctzsm_0_1/A.cpp.tk                             |  34
code/ctzsm_1_1/B.cpp.tk                             |  28
code/ctzsm_2_1/C.cpp.tk                             |  86
code/DanilC_0_1/problem.cpp.tk                      |  41
code/DanilC_1_1/problemB.cpp.tk                     |  55
code/DanilC_2_1/problemC.cpp.tk                     |  117
code/DEGwer_0_1/A.cpp.tk                            |  28
code/DEGwer_1_1/B.cpp.tk                            |  31
code/DEGwer_2_1/C.cpp.tk                            |  42
code/dmute_0_1/a.cpp.tk                             |  15
code/dmute_1_1/b.cpp.tk                             |  23
code/dmute_2_1/c2.cpp.tk                            |  52
code/fagu_0_1/A.cpp.tk                              |  9
code/fagu_1_1/B.cpp.tk                              |  9
code/fagu_2_1/C.cpp.tk                              |  49
code/FatalEagle_0_1/main.cpp.tk                     |  23
code/FatalEagle_1_1/main.cpp.tk                     |  29
code/FatalEagle_2_1/main.cpp.tk                     |  150
code/fullpower_0_1/A.cpp.tk                         |  30
code/fullpower_1_1/B.cpp.tk                         |  35
code/fullpower_2_1/C.cpp.tk                         |  77
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  20
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  24
code/ICastro_2_1/Dijkstra.cpp.tk                    |  140
code/ilackthatsuperpower_0_1/a.cpp.tk               |  100
code/ilackthatsuperpower_1_1/b.cpp.tk               |  99
code/ilackthatsuperpower_2_1/c.cpp.tk               |  131
code/iridescent_0_1/A.cpp.tk                        |  15
code/iridescent_1_1/B.cpp.tk                        |  21
code/iridescent_2_1/C.cpp.tk                        |  27
code/ishraq_0_1/main.cpp.tk                         |  39
code/ishraq_1_1/main.cpp.tk                         |  35
code/ishraq_2_1/main.cpp.tk                         |  107
code/JayXon_0_1/A.cpp.tk                            |  13
code/JayXon_1_1/B.cpp.tk                            |  26
code/JayXon_2_1/C.cpp.tk                            |  42
code/Josse_0_1/A.cpp.tk                             |  25
code/Josse_1_1/B.cpp.tk                             |  25
code/Josse_2_1/C.cpp.tk                             |  92
code/kcm1700_0_1/a.cpp.tk                           |  18
code/kcm1700_1_1/b.cpp.tk                           |  20
code/kcm1700_2_1/c.cpp.tk                           |  71
code/kevinsogo_0_1/a.cpp.tk                         |  22
code/kevinsogo_1_1/b.cpp.tk                         |  25
code/kevinsogo_2_1/c.cpp.tk                         |  70
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  17
code/LazyAnna_0_1/1.cpp.tk                          |  20
code/LazyAnna_1_1/2-1.cpp.tk                        |  22
code/LazyAnna_2_1/3.cpp.tk                          |  39
code/Merkurev_0_1/A.cpp.tk                          |  26
code/Merkurev_1_1/B.cpp.tk                          |  42
code/Merkurev_2_1/C.cpp.tk                          |  42
code/mezei_0_1/main.cpp.tk                          |  28
code/mezei_1_1/main.cpp.tk                          |  22
code/mezei_2_1/main.cpp.tk                          |  68
code/Mister_0_1/a.cpp.tk                            |  31
code/Mister_1_1/b.cpp.tk                            |  18
code/Mister_2_1/c.cpp.tk                            |  35
code/namonakiacc_0_1/cpp.cpp.tk                     |  38
code/namonakiacc_1_1/cpp.cpp.tk                     |  43
code/namonakiacc_2_1/cpp.cpp.tk                     |  64
code/Nicolas16_0_1/main.cpp.tk                      |  9
code/Nicolas16_1_1/main.cpp.tk                      |  9
code/Nicolas16_2_1/main.cpp.tk                      |  65
code/pandamonium_0_1/a.cpp.tk                       |  29
code/pandamonium_1_1/b.cpp.tk                       |  42
code/pandamonium_2_1/c.cpp.tk                       |  25
code/pflueger_0_1/A.cpp.tk                          |  26
code/pflueger_1_1/B.cpp.tk                          |  23
code/pflueger_2_1/C.cpp.tk                          |  63
code/ponyopoppo_0_1/A.cpp.tk                        |  23
code/ponyopoppo_1_1/B.cpp.tk                        |  37
code/ponyopoppo_2_1/C.cpp.tk                        |  142
code/Ragnar_0_1/A.cpp.tk                            |  31
code/Ragnar_1_1/B-2.cpp.tk                          |  32
code/Ragnar_2_1/C.cpp.tk                            |  44
code/saffah_0_1/t.cpp.tk                            |  24
code/saffah_1_1/t.cpp.tk                            |  32
code/saffah_2_1/t.cpp.tk                            |  98
code/SamanSami_0_1/A.cpp.tk                         |  9
code/SamanSami_1_1/B.cpp.tk                         |  22
code/SamanSami_2_1/C.cpp.tk                         |  12
code/Savlik_0_1/code.cpp.tk                         |  32
code/Savlik_1_1/code.cpp.tk                         |  34
code/Savlik_2_1/code.cpp.tk                         |  78
code/shik_0_1/pa.cpp.tk                             |  73
code/shik_1_1/pb.cpp.tk                             |  69
code/shik_2_1/pc.cpp.tk                             |  108
code/simsa.st_0_1/A.cpp.tk                          |  33
code/simsa.st_1_1/B.cpp.tk                          |  31
code/simsa.st_2_1/C.cpp.tk                          |  90
code/SovietUnion_0_1/A.cpp.tk                       |  21
code/SovietUnion_1_1/B.cpp.tk                       |  26
code/SovietUnion_2_1/C.cpp.tk                       |  77
code/tailed_0_1/A.cpp.tk                            |  44
code/tailed_1_1/B.cpp.tk                            |  21
code/tailed_2_1/C.cpp.tk                            |  48
code/TheNatural_0_1/A.cpp.tk                        |  20
code/TheNatural_1_1/B.cpp.tk                        |  20
code/TheNatural_2_1/C.cpp.tk                        |  28
code/TrueBamboo_0_1/test.cpp.tk                     |  21
code/TrueBamboo_1_1/test.cpp.tk                     |  25
code/TrueBamboo_2_1/test.cpp.tk                     |  54
code/tur.turczyn_0_1/A.cpp.tk                       |  21
code/tur.turczyn_1_1/B.cpp.tk                       |  31
code/tur.turczyn_2_1/C.cpp.tk                       |  33
code/Tyg3R_0_1/A.cpp.tk                             |  2466
code/Tyg3R_1_1/B.cpp.tk                             |  55
code/Tyg3R_2_1/C.cpp.tk                             |  50
code/UminchuR_0_1/main.cpp.tk                       |  32
code/UminchuR_1_1/main.cpp.tk                       |  39
code/UminchuR_2_1/main.cpp.tk                       |  67
code/wo..._0_1/a.cpp.tk                             |  21
code/wo..._1_1/b.cpp.tk                             |  25
code/wo..._2_1/c.cpp.tk                             |  70
code/yswtt_0_1/A.cpp.tk                             |  15
code/yswtt_1_1/B.cpp.tk                             |  22
code/yswtt_2_1/C.cpp.tk                             |  49
code/ZhSh_0_1/a.cpp.tk                              |  24
code/ZhSh_1_1/b.cpp.tk                              |  68
code/ZhSh_2_1/c.cpp.tk                              |  85
