Begin
Comparing:  code/ctzsm_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  82
code/551100kk_1_1/B.cpp.tk                          |  49
code/551100kk_2_1/C.cpp.tk                          |  61
code/achan1058_0_1/Q-A.cpp.tk                       |  9
code/achan1058_1_1/source.cpp.tk                    |  14
code/achan1058_2_1/source.cpp.tk                    |  34
code/alanubi_0_1/a.cpp.tk                           |  60
code/alanubi_1_1/b.cpp.tk                           |  58
code/alanubi_2_1/c.cpp.tk                           |  96
code/AntiForest_0_1/q1.cpp.tk                       |  100
code/AntiForest_1_1/q2.cpp.tk                       |  62
code/AntiForest_2_1/q3.cpp.tk                       |  102
code/apiad_0_1/A.cpp.tk                             |  36
code/apiad_1_1/B.cpp.tk                             |  21
code/apiad_2_1/C.cpp.tk                             |  30
code/azaky_0_1/A.cpp.tk                             |  57
code/azaky_1_1/B.cpp.tk                             |  29
code/azaky_2_1/C.cpp.tk                             |  55
code/azariamuh_0_1/standing.cpp.tk                  |  23
code/azariamuh_1_1/pancake.cpp.tk                   |  27
code/azariamuh_2_1/dijkstra.cpp.tk                  |  26
code/bmerry_0_1/a.cpp.tk                            |  63
code/bmerry_1_1/b.cpp.tk                            |  51
code/bmerry_2_1/c.cpp.tk                            |  50
code/climpet_0_1/A.cpp.tk                           |  78
code/climpet_1_1/B.cpp.tk                           |  60
code/climpet_2_1/C.cpp.tk                           |  83
code/ctzsm_0_1/A.cpp.tk                             |  7683
code/ctzsm_1_1/B.cpp.tk                             |  437
code/ctzsm_2_1/C.cpp.tk                             |  341
code/DanilC_0_1/problem.cpp.tk                      |  90
code/DanilC_1_1/problemB.cpp.tk                     |  82
code/DanilC_2_1/problemC.cpp.tk                     |  97
code/DEGwer_0_1/A.cpp.tk                            |  46
code/DEGwer_1_1/B.cpp.tk                            |  47
code/DEGwer_2_1/C.cpp.tk                            |  40
code/dmute_0_1/a.cpp.tk                             |  100
code/dmute_1_1/b.cpp.tk                             |  68
code/dmute_2_1/c2.cpp.tk                            |  86
code/fagu_0_1/A.cpp.tk                              |  21
code/fagu_1_1/B.cpp.tk                              |  21
code/fagu_2_1/C.cpp.tk                              |  43
code/FatalEagle_0_1/main.cpp.tk                     |  149
code/FatalEagle_1_1/main.cpp.tk                     |  137
code/FatalEagle_2_1/main.cpp.tk                     |  184
code/fullpower_0_1/A.cpp.tk                         |  192
code/fullpower_1_1/B.cpp.tk                         |  114
code/fullpower_2_1/C.cpp.tk                         |  162
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  45
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  34
code/ICastro_2_1/Dijkstra.cpp.tk                    |  108
code/ilackthatsuperpower_0_1/a.cpp.tk               |  102
code/ilackthatsuperpower_1_1/b.cpp.tk               |  74
code/ilackthatsuperpower_2_1/c.cpp.tk               |  90
code/iridescent_0_1/A.cpp.tk                        |  29
code/iridescent_1_1/B.cpp.tk                        |  45
code/iridescent_2_1/C.cpp.tk                        |  35
code/ishraq_0_1/main.cpp.tk                         |  32
code/ishraq_1_1/main.cpp.tk                         |  26
code/ishraq_2_1/main.cpp.tk                         |  52
code/JayXon_0_1/A.cpp.tk                            |  40
code/JayXon_1_1/B.cpp.tk                            |  33
code/JayXon_2_1/C.cpp.tk                            |  26
code/Josse_0_1/A.cpp.tk                             |  22
code/Josse_1_1/B.cpp.tk                             |  31
code/Josse_2_1/C.cpp.tk                             |  71
code/kcm1700_0_1/a.cpp.tk                           |  52
code/kcm1700_1_1/b.cpp.tk                           |  67
code/kcm1700_2_1/c.cpp.tk                           |  85
code/kevinsogo_0_1/a.cpp.tk                         |  38
code/kevinsogo_1_1/b.cpp.tk                         |  20
code/kevinsogo_2_1/c.cpp.tk                         |  48
code/ksun48_0_1/A.cpp.tk                            |  6
code/ksun48_1_1/B.cpp.tk                            |  6
code/ksun48_2_1/C.cpp.tk                            |  15
code/LazyAnna_0_1/1.cpp.tk                          |  68
code/LazyAnna_1_1/2-1.cpp.tk                        |  59
code/LazyAnna_2_1/3.cpp.tk                          |  47
code/Merkurev_0_1/A.cpp.tk                          |  96
code/Merkurev_1_1/B.cpp.tk                          |  144
code/Merkurev_2_1/C.cpp.tk                          |  112
code/mezei_0_1/main.cpp.tk                          |  69
code/mezei_1_1/main.cpp.tk                          |  47
code/mezei_2_1/main.cpp.tk                          |  90
code/Mister_0_1/a.cpp.tk                            |  147
code/Mister_1_1/b.cpp.tk                            |  88
code/Mister_2_1/c.cpp.tk                            |  119
code/namonakiacc_0_1/cpp.cpp.tk                     |  26
code/namonakiacc_1_1/cpp.cpp.tk                     |  27
code/namonakiacc_2_1/cpp.cpp.tk                     |  45
code/Nicolas16_0_1/main.cpp.tk                      |  32
code/Nicolas16_1_1/main.cpp.tk                      |  33
code/Nicolas16_2_1/main.cpp.tk                      |  116
code/pandamonium_0_1/a.cpp.tk                       |  108
code/pandamonium_1_1/b.cpp.tk                       |  70
code/pandamonium_2_1/c.cpp.tk                       |  74
code/pflueger_0_1/A.cpp.tk                          |  27
code/pflueger_1_1/B.cpp.tk                          |  35
code/pflueger_2_1/C.cpp.tk                          |  61
code/ponyopoppo_0_1/A.cpp.tk                        |  19
code/ponyopoppo_1_1/B.cpp.tk                        |  12
code/ponyopoppo_2_1/C.cpp.tk                        |  78
code/Ragnar_0_1/A.cpp.tk                            |  35
code/Ragnar_1_1/B-2.cpp.tk                          |  17
code/Ragnar_2_1/C.cpp.tk                            |  32
code/saffah_0_1/t.cpp.tk                            |  32
code/saffah_1_1/t.cpp.tk                            |  18
code/saffah_2_1/t.cpp.tk                            |  68
code/SamanSami_0_1/A.cpp.tk                         |  11
code/SamanSami_1_1/B.cpp.tk                         |  35
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  78
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  42
code/shik_0_1/pa.cpp.tk                             |  70
code/shik_1_1/pb.cpp.tk                             |  45
code/shik_2_1/pc.cpp.tk                             |  67
code/simsa.st_0_1/A.cpp.tk                          |  19
code/simsa.st_1_1/B.cpp.tk                          |  18
code/simsa.st_2_1/C.cpp.tk                          |  60
code/SovietUnion_0_1/A.cpp.tk                       |  335
code/SovietUnion_1_1/B.cpp.tk                       |  333
code/SovietUnion_2_1/C.cpp.tk                       |  97
code/tailed_0_1/A.cpp.tk                            |  134
code/tailed_1_1/B.cpp.tk                            |  26
code/tailed_2_1/C.cpp.tk                            |  27
code/TheNatural_0_1/A.cpp.tk                        |  60
code/TheNatural_1_1/B.cpp.tk                        |  42
code/TheNatural_2_1/C.cpp.tk                        |  24
code/TrueBamboo_0_1/test.cpp.tk                     |  27
code/TrueBamboo_1_1/test.cpp.tk                     |  26
code/TrueBamboo_2_1/test.cpp.tk                     |  44
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  14
code/tur.turczyn_2_1/C.cpp.tk                       |  19
code/Tyg3R_0_1/A.cpp.tk                             |  19
code/Tyg3R_1_1/B.cpp.tk                             |  15
code/Tyg3R_2_1/C.cpp.tk                             |  20
code/UminchuR_0_1/main.cpp.tk                       |  95
code/UminchuR_1_1/main.cpp.tk                       |  98
code/UminchuR_2_1/main.cpp.tk                       |  82
code/wo..._0_1/a.cpp.tk                             |  57
code/wo..._1_1/b.cpp.tk                             |  66
code/wo..._2_1/c.cpp.tk                             |  95
code/yswtt_0_1/A.cpp.tk                             |  110
code/yswtt_1_1/B.cpp.tk                             |  51
code/yswtt_2_1/C.cpp.tk                             |  58
code/ZhSh_0_1/a.cpp.tk                              |  77
code/ZhSh_1_1/b.cpp.tk                              |  90
code/ZhSh_2_1/c.cpp.tk                              |  79
