Begin
Comparing:  code/fagu_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  10
code/551100kk_1_1/B.cpp.tk                          |  18
code/551100kk_2_1/C.cpp.tk                          |  70
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  28
code/achan1058_2_1/source.cpp.tk                    |  49
code/alanubi_0_1/a.cpp.tk                           |  20
code/alanubi_1_1/b.cpp.tk                           |  38
code/alanubi_2_1/c.cpp.tk                           |  69
code/AntiForest_0_1/q1.cpp.tk                       |  20
code/AntiForest_1_1/q2.cpp.tk                       |  9
code/AntiForest_2_1/q3.cpp.tk                       |  84
code/apiad_0_1/A.cpp.tk                             |  16
code/apiad_1_1/B.cpp.tk                             |  25
code/apiad_2_1/C.cpp.tk                             |  151
code/azaky_0_1/A.cpp.tk                             |  20
code/azaky_1_1/B.cpp.tk                             |  24
code/azaky_2_1/C.cpp.tk                             |  171
code/azariamuh_0_1/standing.cpp.tk                  |  13
code/azariamuh_1_1/pancake.cpp.tk                   |  44
code/azariamuh_2_1/dijkstra.cpp.tk                  |  41
code/bmerry_0_1/a.cpp.tk                            |  43
code/bmerry_1_1/b.cpp.tk                            |  52
code/bmerry_2_1/c.cpp.tk                            |  183
code/climpet_0_1/A.cpp.tk                           |  22
code/climpet_1_1/B.cpp.tk                           |  26
code/climpet_2_1/C.cpp.tk                           |  146
code/ctzsm_0_1/A.cpp.tk                             |  15
code/ctzsm_1_1/B.cpp.tk                             |  26
code/ctzsm_2_1/C.cpp.tk                             |  201
code/DanilC_0_1/problem.cpp.tk                      |  21
code/DanilC_1_1/problemB.cpp.tk                     |  36
code/DanilC_2_1/problemC.cpp.tk                     |  79
code/DEGwer_0_1/A.cpp.tk                            |  24
code/DEGwer_1_1/B.cpp.tk                            |  27
code/DEGwer_2_1/C.cpp.tk                            |  70
code/dmute_0_1/a.cpp.tk                             |  13
code/dmute_1_1/b.cpp.tk                             |  16
code/dmute_2_1/c2.cpp.tk                            |  62
code/fagu_0_1/A.cpp.tk                              |  87
code/fagu_1_1/B.cpp.tk                              |  87
code/fagu_2_1/C.cpp.tk                              |  50709
code/FatalEagle_0_1/main.cpp.tk                     |  17
code/FatalEagle_1_1/main.cpp.tk                     |  25
code/FatalEagle_2_1/main.cpp.tk                     |  173
code/fullpower_0_1/A.cpp.tk                         |  23
code/fullpower_1_1/B.cpp.tk                         |  41
code/fullpower_2_1/C.cpp.tk                         |  77
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  7
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  13
code/ICastro_2_1/Dijkstra.cpp.tk                    |  108
code/ilackthatsuperpower_0_1/a.cpp.tk               |  55
code/ilackthatsuperpower_1_1/b.cpp.tk               |  56
code/ilackthatsuperpower_2_1/c.cpp.tk               |  81
code/iridescent_0_1/A.cpp.tk                        |  7
code/iridescent_1_1/B.cpp.tk                        |  9
code/iridescent_2_1/C.cpp.tk                        |  235
code/ishraq_0_1/main.cpp.tk                         |  11
code/ishraq_1_1/main.cpp.tk                         |  14
code/ishraq_2_1/main.cpp.tk                         |  79
code/JayXon_0_1/A.cpp.tk                            |  6
code/JayXon_1_1/B.cpp.tk                            |  23
code/JayXon_2_1/C.cpp.tk                            |  21
code/Josse_0_1/A.cpp.tk                             |  14
code/Josse_1_1/B.cpp.tk                             |  22
code/Josse_2_1/C.cpp.tk                             |  74
code/kcm1700_0_1/a.cpp.tk                           |  10
code/kcm1700_1_1/b.cpp.tk                           |  27
code/kcm1700_2_1/c.cpp.tk                           |  79
code/kevinsogo_0_1/a.cpp.tk                         |  11
code/kevinsogo_1_1/b.cpp.tk                         |  11
code/kevinsogo_2_1/c.cpp.tk                         |  100
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  6
code/LazyAnna_1_1/2-1.cpp.tk                        |  11
code/LazyAnna_2_1/3.cpp.tk                          |  67
code/Merkurev_0_1/A.cpp.tk                          |  18
code/Merkurev_1_1/B.cpp.tk                          |  45
code/Merkurev_2_1/C.cpp.tk                          |  54
code/mezei_0_1/main.cpp.tk                          |  19
code/mezei_1_1/main.cpp.tk                          |  25
code/mezei_2_1/main.cpp.tk                          |  68
code/Mister_0_1/a.cpp.tk                            |  11
code/Mister_1_1/b.cpp.tk                            |  17
code/Mister_2_1/c.cpp.tk                            |  64
code/namonakiacc_0_1/cpp.cpp.tk                     |  27
code/namonakiacc_1_1/cpp.cpp.tk                     |  32
code/namonakiacc_2_1/cpp.cpp.tk                     |  85
code/Nicolas16_0_1/main.cpp.tk                      |  9
code/Nicolas16_1_1/main.cpp.tk                      |  8
code/Nicolas16_2_1/main.cpp.tk                      |  58
code/pandamonium_0_1/a.cpp.tk                       |  14
code/pandamonium_1_1/b.cpp.tk                       |  57
code/pandamonium_2_1/c.cpp.tk                       |  41
code/pflueger_0_1/A.cpp.tk                          |  7
code/pflueger_1_1/B.cpp.tk                          |  18
code/pflueger_2_1/C.cpp.tk                          |  50
code/ponyopoppo_0_1/A.cpp.tk                        |  9
code/ponyopoppo_1_1/B.cpp.tk                        |  16
code/ponyopoppo_2_1/C.cpp.tk                        |  89
code/Ragnar_0_1/A.cpp.tk                            |  20
code/Ragnar_1_1/B-2.cpp.tk                          |  28
code/Ragnar_2_1/C.cpp.tk                            |  59
code/saffah_0_1/t.cpp.tk                            |  10
code/saffah_1_1/t.cpp.tk                            |  18
code/saffah_2_1/t.cpp.tk                            |  72
code/SamanSami_0_1/A.cpp.tk                         |  2
code/SamanSami_1_1/B.cpp.tk                         |  13
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  7
code/Savlik_1_1/code.cpp.tk                         |  13
code/Savlik_2_1/code.cpp.tk                         |  39
code/shik_0_1/pa.cpp.tk                             |  42
code/shik_1_1/pb.cpp.tk                             |  43
code/shik_2_1/pc.cpp.tk                             |  106
code/simsa.st_0_1/A.cpp.tk                          |  13
code/simsa.st_1_1/B.cpp.tk                          |  14
code/simsa.st_2_1/C.cpp.tk                          |  55
code/SovietUnion_0_1/A.cpp.tk                       |  16
code/SovietUnion_1_1/B.cpp.tk                       |  18
code/SovietUnion_2_1/C.cpp.tk                       |  44
code/tailed_0_1/A.cpp.tk                            |  7
code/tailed_1_1/B.cpp.tk                            |  10
code/tailed_2_1/C.cpp.tk                            |  49
code/TheNatural_0_1/A.cpp.tk                        |  8
code/TheNatural_1_1/B.cpp.tk                        |  15
code/TheNatural_2_1/C.cpp.tk                        |  149
code/TrueBamboo_0_1/test.cpp.tk                     |  12
code/TrueBamboo_1_1/test.cpp.tk                     |  15
code/TrueBamboo_2_1/test.cpp.tk                     |  32
code/tur.turczyn_0_1/A.cpp.tk                       |  13
code/tur.turczyn_1_1/B.cpp.tk                       |  20
code/tur.turczyn_2_1/C.cpp.tk                       |  41
code/Tyg3R_0_1/A.cpp.tk                             |  10
code/Tyg3R_1_1/B.cpp.tk                             |  19
code/Tyg3R_2_1/C.cpp.tk                             |  156
code/UminchuR_0_1/main.cpp.tk                       |  21
code/UminchuR_1_1/main.cpp.tk                       |  29
code/UminchuR_2_1/main.cpp.tk                       |  76
code/wo..._0_1/a.cpp.tk                             |  25
code/wo..._1_1/b.cpp.tk                             |  26
code/wo..._2_1/c.cpp.tk                             |  91
code/yswtt_0_1/A.cpp.tk                             |  5
code/yswtt_1_1/B.cpp.tk                             |  12
code/yswtt_2_1/C.cpp.tk                             |  25
code/ZhSh_0_1/a.cpp.tk                              |  6
code/ZhSh_1_1/b.cpp.tk                              |  40
code/ZhSh_2_1/c.cpp.tk                              |  282
