Begin
Comparing:  code/LazyAnna_0_1/1.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  19
code/551100kk_1_1/B.cpp.tk                          |  19
code/551100kk_2_1/C.cpp.tk                          |  24
code/achan1058_0_1/Q-A.cpp.tk                       |  10
code/achan1058_1_1/source.cpp.tk                    |  19
code/achan1058_2_1/source.cpp.tk                    |  31
code/alanubi_0_1/a.cpp.tk                           |  46
code/alanubi_1_1/b.cpp.tk                           |  35
code/alanubi_2_1/c.cpp.tk                           |  94
code/AntiForest_0_1/q1.cpp.tk                       |  29
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  40
code/apiad_0_1/A.cpp.tk                             |  12
code/apiad_1_1/B.cpp.tk                             |  12
code/apiad_2_1/C.cpp.tk                             |  26
code/azaky_0_1/A.cpp.tk                             |  17
code/azaky_1_1/B.cpp.tk                             |  14
code/azaky_2_1/C.cpp.tk                             |  32
code/azariamuh_0_1/standing.cpp.tk                  |  26
code/azariamuh_1_1/pancake.cpp.tk                   |  20
code/azariamuh_2_1/dijkstra.cpp.tk                  |  18
code/bmerry_0_1/a.cpp.tk                            |  87
code/bmerry_1_1/b.cpp.tk                            |  56
code/bmerry_2_1/c.cpp.tk                            |  59
code/climpet_0_1/A.cpp.tk                           |  161
code/climpet_1_1/B.cpp.tk                           |  86
code/climpet_2_1/C.cpp.tk                           |  112
code/ctzsm_0_1/A.cpp.tk                             |  85
code/ctzsm_1_1/B.cpp.tk                             |  61
code/ctzsm_2_1/C.cpp.tk                             |  102
code/DanilC_0_1/problem.cpp.tk                      |  125
code/DanilC_1_1/problemB.cpp.tk                     |  98
code/DanilC_2_1/problemC.cpp.tk                     |  97
code/DEGwer_0_1/A.cpp.tk                            |  45
code/DEGwer_1_1/B.cpp.tk                            |  44
code/DEGwer_2_1/C.cpp.tk                            |  26
code/dmute_0_1/a.cpp.tk                             |  33
code/dmute_1_1/b.cpp.tk                             |  64
code/dmute_2_1/c2.cpp.tk                            |  77
code/fagu_0_1/A.cpp.tk                              |  10
code/fagu_1_1/B.cpp.tk                              |  12
code/fagu_2_1/C.cpp.tk                              |  22
code/FatalEagle_0_1/main.cpp.tk                     |  37
code/FatalEagle_1_1/main.cpp.tk                     |  70
code/FatalEagle_2_1/main.cpp.tk                     |  167
code/fullpower_0_1/A.cpp.tk                         |  51
code/fullpower_1_1/B.cpp.tk                         |  86
code/fullpower_2_1/C.cpp.tk                         |  123
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  116
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  51
code/ICastro_2_1/Dijkstra.cpp.tk                    |  60
code/ilackthatsuperpower_0_1/a.cpp.tk               |  117
code/ilackthatsuperpower_1_1/b.cpp.tk               |  71
code/ilackthatsuperpower_2_1/c.cpp.tk               |  77
code/iridescent_0_1/A.cpp.tk                        |  42
code/iridescent_1_1/B.cpp.tk                        |  84
code/iridescent_2_1/C.cpp.tk                        |  60
code/ishraq_0_1/main.cpp.tk                         |  12
code/ishraq_1_1/main.cpp.tk                         |  27
code/ishraq_2_1/main.cpp.tk                         |  34
code/JayXon_0_1/A.cpp.tk                            |  25
code/JayXon_1_1/B.cpp.tk                            |  40
code/JayXon_2_1/C.cpp.tk                            |  19
code/Josse_0_1/A.cpp.tk                             |  41
code/Josse_1_1/B.cpp.tk                             |  44
code/Josse_2_1/C.cpp.tk                             |  74
code/kcm1700_0_1/a.cpp.tk                           |  52
code/kcm1700_1_1/b.cpp.tk                           |  48
code/kcm1700_2_1/c.cpp.tk                           |  72
code/kevinsogo_0_1/a.cpp.tk                         |  21
code/kevinsogo_1_1/b.cpp.tk                         |  17
code/kevinsogo_2_1/c.cpp.tk                         |  49
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  10
code/LazyAnna_0_1/1.cpp.tk                          |  4253
code/LazyAnna_1_1/2-1.cpp.tk                        |  113
code/LazyAnna_2_1/3.cpp.tk                          |  80
code/Merkurev_0_1/A.cpp.tk                          |  72
code/Merkurev_1_1/B.cpp.tk                          |  48
code/Merkurev_2_1/C.cpp.tk                          |  66
code/mezei_0_1/main.cpp.tk                          |  67
code/mezei_1_1/main.cpp.tk                          |  41
code/mezei_2_1/main.cpp.tk                          |  59
code/Mister_0_1/a.cpp.tk                            |  65
code/Mister_1_1/b.cpp.tk                            |  58
code/Mister_2_1/c.cpp.tk                            |  127
code/namonakiacc_0_1/cpp.cpp.tk                     |  16
code/namonakiacc_1_1/cpp.cpp.tk                     |  16
code/namonakiacc_2_1/cpp.cpp.tk                     |  42
code/Nicolas16_0_1/main.cpp.tk                      |  22
code/Nicolas16_1_1/main.cpp.tk                      |  26
code/Nicolas16_2_1/main.cpp.tk                      |  97
code/pandamonium_0_1/a.cpp.tk                       |  34
code/pandamonium_1_1/b.cpp.tk                       |  47
code/pandamonium_2_1/c.cpp.tk                       |  44
code/pflueger_0_1/A.cpp.tk                          |  79
code/pflueger_1_1/B.cpp.tk                          |  62
code/pflueger_2_1/C.cpp.tk                          |  84
code/ponyopoppo_0_1/A.cpp.tk                        |  22
code/ponyopoppo_1_1/B.cpp.tk                        |  14
code/ponyopoppo_2_1/C.cpp.tk                        |  47
code/Ragnar_0_1/A.cpp.tk                            |  21
code/Ragnar_1_1/B-2.cpp.tk                          |  21
code/Ragnar_2_1/C.cpp.tk                            |  43
code/saffah_0_1/t.cpp.tk                            |  12
code/saffah_1_1/t.cpp.tk                            |  10
code/saffah_2_1/t.cpp.tk                            |  35
code/SamanSami_0_1/A.cpp.tk                         |  24
code/SamanSami_1_1/B.cpp.tk                         |  66
code/SamanSami_2_1/C.cpp.tk                         |  3
code/Savlik_0_1/code.cpp.tk                         |  45
code/Savlik_1_1/code.cpp.tk                         |  7
code/Savlik_2_1/code.cpp.tk                         |  34
code/shik_0_1/pa.cpp.tk                             |  39
code/shik_1_1/pb.cpp.tk                             |  28
code/shik_2_1/pc.cpp.tk                             |  51
code/simsa.st_0_1/A.cpp.tk                          |  10
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  28
code/SovietUnion_0_1/A.cpp.tk                       |  101
code/SovietUnion_1_1/B.cpp.tk                       |  149
code/SovietUnion_2_1/C.cpp.tk                       |  85
code/tailed_0_1/A.cpp.tk                            |  47
code/tailed_1_1/B.cpp.tk                            |  48
code/tailed_2_1/C.cpp.tk                            |  28
code/TheNatural_0_1/A.cpp.tk                        |  91
code/TheNatural_1_1/B.cpp.tk                        |  74
code/TheNatural_2_1/C.cpp.tk                        |  42
code/TrueBamboo_0_1/test.cpp.tk                     |  17
code/TrueBamboo_1_1/test.cpp.tk                     |  21
code/TrueBamboo_2_1/test.cpp.tk                     |  28
code/tur.turczyn_0_1/A.cpp.tk                       |  14
code/tur.turczyn_1_1/B.cpp.tk                       |  17
code/tur.turczyn_2_1/C.cpp.tk                       |  19
code/Tyg3R_0_1/A.cpp.tk                             |  14
code/Tyg3R_1_1/B.cpp.tk                             |  13
code/Tyg3R_2_1/C.cpp.tk                             |  34
code/UminchuR_0_1/main.cpp.tk                       |  18
code/UminchuR_1_1/main.cpp.tk                       |  17
code/UminchuR_2_1/main.cpp.tk                       |  44
code/wo..._0_1/a.cpp.tk                             |  50
code/wo..._1_1/b.cpp.tk                             |  52
code/wo..._2_1/c.cpp.tk                             |  91
code/yswtt_0_1/A.cpp.tk                             |  114
code/yswtt_1_1/B.cpp.tk                             |  83
code/yswtt_2_1/C.cpp.tk                             |  110
code/ZhSh_0_1/a.cpp.tk                              |  142
code/ZhSh_1_1/b.cpp.tk                              |  114
code/ZhSh_2_1/c.cpp.tk                              |  103
