Begin
Comparing:  code/AntiForest_1_1/q2.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  117
code/551100kk_1_1/B.cpp.tk                          |  130
code/551100kk_2_1/C.cpp.tk                          |  107
code/achan1058_0_1/Q-A.cpp.tk                       |  14
code/achan1058_1_1/source.cpp.tk                    |  42
code/achan1058_2_1/source.cpp.tk                    |  64
code/alanubi_0_1/a.cpp.tk                           |  21
code/alanubi_1_1/b.cpp.tk                           |  31
code/alanubi_2_1/c.cpp.tk                           |  68
code/AntiForest_0_1/q1.cpp.tk                       |  393
code/AntiForest_1_1/q2.cpp.tk                       |  1148
code/AntiForest_2_1/q3.cpp.tk                       |  375
code/apiad_0_1/A.cpp.tk                             |  33
code/apiad_1_1/B.cpp.tk                             |  57
code/apiad_2_1/C.cpp.tk                             |  46
code/azaky_0_1/A.cpp.tk                             |  68
code/azaky_1_1/B.cpp.tk                             |  73
code/azaky_2_1/C.cpp.tk                             |  113
code/azariamuh_0_1/standing.cpp.tk                  |  49
code/azariamuh_1_1/pancake.cpp.tk                   |  66
code/azariamuh_2_1/dijkstra.cpp.tk                  |  55
code/bmerry_0_1/a.cpp.tk                            |  56
code/bmerry_1_1/b.cpp.tk                            |  63
code/bmerry_2_1/c.cpp.tk                            |  63
code/climpet_0_1/A.cpp.tk                           |  30
code/climpet_1_1/B.cpp.tk                           |  35
code/climpet_2_1/C.cpp.tk                           |  47
code/ctzsm_0_1/A.cpp.tk                             |  150
code/ctzsm_1_1/B.cpp.tk                             |  166
code/ctzsm_2_1/C.cpp.tk                             |  206
code/DanilC_0_1/problem.cpp.tk                      |  25
code/DanilC_1_1/problemB.cpp.tk                     |  37
code/DanilC_2_1/problemC.cpp.tk                     |  97
code/DEGwer_0_1/A.cpp.tk                            |  33
code/DEGwer_1_1/B.cpp.tk                            |  34
code/DEGwer_2_1/C.cpp.tk                            |  39
code/dmute_0_1/a.cpp.tk                             |  26
code/dmute_1_1/b.cpp.tk                             |  24
code/dmute_2_1/c2.cpp.tk                            |  51
code/fagu_0_1/A.cpp.tk                              |  32
code/fagu_1_1/B.cpp.tk                              |  33
code/fagu_2_1/C.cpp.tk                              |  59
code/FatalEagle_0_1/main.cpp.tk                     |  81
code/FatalEagle_1_1/main.cpp.tk                     |  81
code/FatalEagle_2_1/main.cpp.tk                     |  163
code/fullpower_0_1/A.cpp.tk                         |  161
code/fullpower_1_1/B.cpp.tk                         |  114
code/fullpower_2_1/C.cpp.tk                         |  130
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  8
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  13
code/ICastro_2_1/Dijkstra.cpp.tk                    |  161
code/ilackthatsuperpower_0_1/a.cpp.tk               |  80
code/ilackthatsuperpower_1_1/b.cpp.tk               |  83
code/ilackthatsuperpower_2_1/c.cpp.tk               |  112
code/iridescent_0_1/A.cpp.tk                        |  6
code/iridescent_1_1/B.cpp.tk                        |  11
code/iridescent_2_1/C.cpp.tk                        |  15
code/ishraq_0_1/main.cpp.tk                         |  34
code/ishraq_1_1/main.cpp.tk                         |  41
code/ishraq_2_1/main.cpp.tk                         |  103
code/JayXon_0_1/A.cpp.tk                            |  5
code/JayXon_1_1/B.cpp.tk                            |  15
code/JayXon_2_1/C.cpp.tk                            |  30
code/Josse_0_1/A.cpp.tk                             |  9
code/Josse_1_1/B.cpp.tk                             |  15
code/Josse_2_1/C.cpp.tk                             |  72
code/kcm1700_0_1/a.cpp.tk                           |  27
code/kcm1700_1_1/b.cpp.tk                           |  30
code/kcm1700_2_1/c.cpp.tk                           |  64
code/kevinsogo_0_1/a.cpp.tk                         |  32
code/kevinsogo_1_1/b.cpp.tk                         |  31
code/kevinsogo_2_1/c.cpp.tk                         |  78
code/ksun48_0_1/A.cpp.tk                            |  13
code/ksun48_1_1/B.cpp.tk                            |  13
code/ksun48_2_1/C.cpp.tk                            |  20
code/LazyAnna_0_1/1.cpp.tk                          |  7
code/LazyAnna_1_1/2-1.cpp.tk                        |  10
code/LazyAnna_2_1/3.cpp.tk                          |  29
code/Merkurev_0_1/A.cpp.tk                          |  83
code/Merkurev_1_1/B.cpp.tk                          |  97
code/Merkurev_2_1/C.cpp.tk                          |  95
code/mezei_0_1/main.cpp.tk                          |  28
code/mezei_1_1/main.cpp.tk                          |  21
code/mezei_2_1/main.cpp.tk                          |  72
code/Mister_0_1/a.cpp.tk                            |  24
code/Mister_1_1/b.cpp.tk                            |  29
code/Mister_2_1/c.cpp.tk                            |  36
code/namonakiacc_0_1/cpp.cpp.tk                     |  73
code/namonakiacc_1_1/cpp.cpp.tk                     |  79
code/namonakiacc_2_1/cpp.cpp.tk                     |  106
code/Nicolas16_0_1/main.cpp.tk                      |  19
code/Nicolas16_1_1/main.cpp.tk                      |  18
code/Nicolas16_2_1/main.cpp.tk                      |  68
code/pandamonium_0_1/a.cpp.tk                       |  27
code/pandamonium_1_1/b.cpp.tk                       |  47
code/pandamonium_2_1/c.cpp.tk                       |  34
code/pflueger_0_1/A.cpp.tk                          |  7
code/pflueger_1_1/B.cpp.tk                          |  12
code/pflueger_2_1/C.cpp.tk                          |  38
code/ponyopoppo_0_1/A.cpp.tk                        |  11
code/ponyopoppo_1_1/B.cpp.tk                        |  23
code/ponyopoppo_2_1/C.cpp.tk                        |  125
code/Ragnar_0_1/A.cpp.tk                            |  21
code/Ragnar_1_1/B-2.cpp.tk                          |  29
code/Ragnar_2_1/C.cpp.tk                            |  42
code/saffah_0_1/t.cpp.tk                            |  46
code/saffah_1_1/t.cpp.tk                            |  70
code/saffah_2_1/t.cpp.tk                            |  145
code/SamanSami_0_1/A.cpp.tk                         |  4
code/SamanSami_1_1/B.cpp.tk                         |  10
code/SamanSami_2_1/C.cpp.tk                         |  12
code/Savlik_0_1/code.cpp.tk                         |  11
code/Savlik_1_1/code.cpp.tk                         |  20
code/Savlik_2_1/code.cpp.tk                         |  57
code/shik_0_1/pa.cpp.tk                             |  84
code/shik_1_1/pb.cpp.tk                             |  82
code/shik_2_1/pc.cpp.tk                             |  114
code/simsa.st_0_1/A.cpp.tk                          |  44
code/simsa.st_1_1/B.cpp.tk                          |  60
code/simsa.st_2_1/C.cpp.tk                          |  129
code/SovietUnion_0_1/A.cpp.tk                       |  180
code/SovietUnion_1_1/B.cpp.tk                       |  185
code/SovietUnion_2_1/C.cpp.tk                       |  131
code/tailed_0_1/A.cpp.tk                            |  7
code/tailed_1_1/B.cpp.tk                            |  10
code/tailed_2_1/C.cpp.tk                            |  31
code/TheNatural_0_1/A.cpp.tk                        |  11
code/TheNatural_1_1/B.cpp.tk                        |  12
code/TheNatural_2_1/C.cpp.tk                        |  18
code/TrueBamboo_0_1/test.cpp.tk                     |  28
code/TrueBamboo_1_1/test.cpp.tk                     |  33
code/TrueBamboo_2_1/test.cpp.tk                     |  63
code/tur.turczyn_0_1/A.cpp.tk                       |  20
code/tur.turczyn_1_1/B.cpp.tk                       |  32
code/tur.turczyn_2_1/C.cpp.tk                       |  30
code/Tyg3R_0_1/A.cpp.tk                             |  19
code/Tyg3R_1_1/B.cpp.tk                             |  43
code/Tyg3R_2_1/C.cpp.tk                             |  32
code/UminchuR_0_1/main.cpp.tk                       |  90
code/UminchuR_1_1/main.cpp.tk                       |  114
code/UminchuR_2_1/main.cpp.tk                       |  125
code/wo..._0_1/a.cpp.tk                             |  31
code/wo..._1_1/b.cpp.tk                             |  27
code/wo..._2_1/c.cpp.tk                             |  60
code/yswtt_0_1/A.cpp.tk                             |  6
code/yswtt_1_1/B.cpp.tk                             |  14
code/yswtt_2_1/C.cpp.tk                             |  28
code/ZhSh_0_1/a.cpp.tk                              |  6
code/ZhSh_1_1/b.cpp.tk                              |  49
code/ZhSh_2_1/c.cpp.tk                              |  69
