Begin
Comparing:  code/bmerry_0_1/a.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  31
code/551100kk_1_1/B.cpp.tk                          |  20
code/551100kk_2_1/C.cpp.tk                          |  37
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  32
code/achan1058_2_1/source.cpp.tk                    |  57
code/alanubi_0_1/a.cpp.tk                           |  26
code/alanubi_1_1/b.cpp.tk                           |  27
code/alanubi_2_1/c.cpp.tk                           |  86
code/AntiForest_0_1/q1.cpp.tk                       |  23
code/AntiForest_1_1/q2.cpp.tk                       |  7
code/AntiForest_2_1/q3.cpp.tk                       |  46
code/apiad_0_1/A.cpp.tk                             |  18
code/apiad_1_1/B.cpp.tk                             |  22
code/apiad_2_1/C.cpp.tk                             |  27
code/azaky_0_1/A.cpp.tk                             |  39
code/azaky_1_1/B.cpp.tk                             |  24
code/azaky_2_1/C.cpp.tk                             |  56
code/azariamuh_0_1/standing.cpp.tk                  |  18
code/azariamuh_1_1/pancake.cpp.tk                   |  21
code/azariamuh_2_1/dijkstra.cpp.tk                  |  20
code/bmerry_0_1/a.cpp.tk                            |  66465
code/bmerry_1_1/b.cpp.tk                            |  37975
code/bmerry_2_1/c.cpp.tk                            |  26479
code/climpet_0_1/A.cpp.tk                           |  57
code/climpet_1_1/B.cpp.tk                           |  38
code/climpet_2_1/C.cpp.tk                           |  56
code/ctzsm_0_1/A.cpp.tk                             |  22
code/ctzsm_1_1/B.cpp.tk                             |  22
code/ctzsm_2_1/C.cpp.tk                             |  76
code/DanilC_0_1/problem.cpp.tk                      |  34
code/DanilC_1_1/problemB.cpp.tk                     |  42
code/DanilC_2_1/problemC.cpp.tk                     |  87
code/DEGwer_0_1/A.cpp.tk                            |  35
code/DEGwer_1_1/B.cpp.tk                            |  35
code/DEGwer_2_1/C.cpp.tk                            |  38
code/dmute_0_1/a.cpp.tk                             |  18
code/dmute_1_1/b.cpp.tk                             |  29
code/dmute_2_1/c2.cpp.tk                            |  55
code/fagu_0_1/A.cpp.tk                              |  15
code/fagu_1_1/B.cpp.tk                              |  15
code/fagu_2_1/C.cpp.tk                              |  39
code/FatalEagle_0_1/main.cpp.tk                     |  27
code/FatalEagle_1_1/main.cpp.tk                     |  40
code/FatalEagle_2_1/main.cpp.tk                     |  151
code/fullpower_0_1/A.cpp.tk                         |  28
code/fullpower_1_1/B.cpp.tk                         |  45
code/fullpower_2_1/C.cpp.tk                         |  81
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  38
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  23
code/ICastro_2_1/Dijkstra.cpp.tk                    |  95
code/ilackthatsuperpower_0_1/a.cpp.tk               |  89
code/ilackthatsuperpower_1_1/b.cpp.tk               |  88
code/ilackthatsuperpower_2_1/c.cpp.tk               |  113
code/iridescent_0_1/A.cpp.tk                        |  23
code/iridescent_1_1/B.cpp.tk                        |  31
code/iridescent_2_1/C.cpp.tk                        |  30
code/ishraq_0_1/main.cpp.tk                         |  10
code/ishraq_1_1/main.cpp.tk                         |  14
code/ishraq_2_1/main.cpp.tk                         |  57
code/JayXon_0_1/A.cpp.tk                            |  35
code/JayXon_1_1/B.cpp.tk                            |  28
code/JayXon_2_1/C.cpp.tk                            |  30
code/Josse_0_1/A.cpp.tk                             |  23
code/Josse_1_1/B.cpp.tk                             |  27
code/Josse_2_1/C.cpp.tk                             |  85
code/kcm1700_0_1/a.cpp.tk                           |  32
code/kcm1700_1_1/b.cpp.tk                           |  27
code/kcm1700_2_1/c.cpp.tk                           |  53
code/kevinsogo_0_1/a.cpp.tk                         |  18
code/kevinsogo_1_1/b.cpp.tk                         |  12
code/kevinsogo_2_1/c.cpp.tk                         |  51
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  22
code/LazyAnna_1_1/2-1.cpp.tk                        |  20
code/LazyAnna_2_1/3.cpp.tk                          |  30
code/Merkurev_0_1/A.cpp.tk                          |  43
code/Merkurev_1_1/B.cpp.tk                          |  40
code/Merkurev_2_1/C.cpp.tk                          |  41
code/mezei_0_1/main.cpp.tk                          |  38
code/mezei_1_1/main.cpp.tk                          |  26
code/mezei_2_1/main.cpp.tk                          |  63
code/Mister_0_1/a.cpp.tk                            |  13
code/Mister_1_1/b.cpp.tk                            |  16
code/Mister_2_1/c.cpp.tk                            |  34
code/namonakiacc_0_1/cpp.cpp.tk                     |  32
code/namonakiacc_1_1/cpp.cpp.tk                     |  34
code/namonakiacc_2_1/cpp.cpp.tk                     |  59
code/Nicolas16_0_1/main.cpp.tk                      |  9
code/Nicolas16_1_1/main.cpp.tk                      |  9
code/Nicolas16_2_1/main.cpp.tk                      |  71
code/pandamonium_0_1/a.cpp.tk                       |  19
code/pandamonium_1_1/b.cpp.tk                       |  44
code/pandamonium_2_1/c.cpp.tk                       |  28
code/pflueger_0_1/A.cpp.tk                          |  32
code/pflueger_1_1/B.cpp.tk                          |  33
code/pflueger_2_1/C.cpp.tk                          |  68
code/ponyopoppo_0_1/A.cpp.tk                        |  13
code/ponyopoppo_1_1/B.cpp.tk                        |  20
code/ponyopoppo_2_1/C.cpp.tk                        |  105
code/Ragnar_0_1/A.cpp.tk                            |  28
code/Ragnar_1_1/B-2.cpp.tk                          |  30
code/Ragnar_2_1/C.cpp.tk                            |  45
code/saffah_0_1/t.cpp.tk                            |  11
code/saffah_1_1/t.cpp.tk                            |  12
code/saffah_2_1/t.cpp.tk                            |  71
code/SamanSami_0_1/A.cpp.tk                         |  10
code/SamanSami_1_1/B.cpp.tk                         |  33
code/SamanSami_2_1/C.cpp.tk                         |  10
code/Savlik_0_1/code.cpp.tk                         |  27
code/Savlik_1_1/code.cpp.tk                         |  11
code/Savlik_2_1/code.cpp.tk                         |  53
code/shik_0_1/pa.cpp.tk                             |  57
code/shik_1_1/pb.cpp.tk                             |  52
code/shik_2_1/pc.cpp.tk                             |  78
code/simsa.st_0_1/A.cpp.tk                          |  11
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  69
code/SovietUnion_0_1/A.cpp.tk                       |  19
code/SovietUnion_1_1/B.cpp.tk                       |  23
code/SovietUnion_2_1/C.cpp.tk                       |  59
code/tailed_0_1/A.cpp.tk                            |  29
code/tailed_1_1/B.cpp.tk                            |  20
code/tailed_2_1/C.cpp.tk                            |  32
code/TheNatural_0_1/A.cpp.tk                        |  45
code/TheNatural_1_1/B.cpp.tk                        |  34
code/TheNatural_2_1/C.cpp.tk                        |  27
code/TrueBamboo_0_1/test.cpp.tk                     |  15
code/TrueBamboo_1_1/test.cpp.tk                     |  20
code/TrueBamboo_2_1/test.cpp.tk                     |  44
code/tur.turczyn_0_1/A.cpp.tk                       |  20
code/tur.turczyn_1_1/B.cpp.tk                       |  25
code/tur.turczyn_2_1/C.cpp.tk                       |  30
code/Tyg3R_0_1/A.cpp.tk                             |  12
code/Tyg3R_1_1/B.cpp.tk                             |  15
code/Tyg3R_2_1/C.cpp.tk                             |  21
code/UminchuR_0_1/main.cpp.tk                       |  30
code/UminchuR_1_1/main.cpp.tk                       |  33
code/UminchuR_2_1/main.cpp.tk                       |  53
code/wo..._0_1/a.cpp.tk                             |  28
code/wo..._1_1/b.cpp.tk                             |  28
code/wo..._2_1/c.cpp.tk                             |  69
code/yswtt_0_1/A.cpp.tk                             |  19
code/yswtt_1_1/B.cpp.tk                             |  21
code/yswtt_2_1/C.cpp.tk                             |  40
code/ZhSh_0_1/a.cpp.tk                              |  24
code/ZhSh_1_1/b.cpp.tk                              |  61
code/ZhSh_2_1/c.cpp.tk                              |  81
