Begin
Comparing:  code/apiad_2_1/C.cpp.tk
code/00/test.cpp.tk                                 |  17
code/01/test.cpp.tk                                 |  17
code/551100kk_0_1/A.cpp.tk                          |  18
code/551100kk_1_1/B.cpp.tk                          |  25
code/551100kk_2_1/C.cpp.tk                          |  102
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  31
code/achan1058_2_1/source.cpp.tk                    |  53
code/alanubi_0_1/a.cpp.tk                           |  15
code/alanubi_1_1/b.cpp.tk                           |  25
code/alanubi_2_1/c.cpp.tk                           |  96
code/AntiForest_0_1/q1.cpp.tk                       |  29
code/AntiForest_1_1/q2.cpp.tk                       |  12
code/AntiForest_2_1/q3.cpp.tk                       |  148
code/apiad_0_1/A.cpp.tk                             |  629
code/apiad_1_1/B.cpp.tk                             |  633
code/apiad_2_1/C.cpp.tk                             |  70042
code/azaky_0_1/A.cpp.tk                             |  31
code/azaky_1_1/B.cpp.tk                             |  32
code/azaky_2_1/C.cpp.tk                             |  223
code/azariamuh_0_1/standing.cpp.tk                  |  17
code/azariamuh_1_1/pancake.cpp.tk                   |  61
code/azariamuh_2_1/dijkstra.cpp.tk                  |  48
code/bmerry_0_1/a.cpp.tk                            |  54
code/bmerry_1_1/b.cpp.tk                            |  59
code/bmerry_2_1/c.cpp.tk                            |  250
code/climpet_0_1/A.cpp.tk                           |  30
code/climpet_1_1/B.cpp.tk                           |  35
code/climpet_2_1/C.cpp.tk                           |  213
code/ctzsm_0_1/A.cpp.tk                             |  20
code/ctzsm_1_1/B.cpp.tk                             |  25
code/ctzsm_2_1/C.cpp.tk                             |  249
code/DanilC_0_1/problem.cpp.tk                      |  29
code/DanilC_1_1/problemB.cpp.tk                     |  51
code/DanilC_2_1/problemC.cpp.tk                     |  106
code/DEGwer_0_1/A.cpp.tk                            |  27
code/DEGwer_1_1/B.cpp.tk                            |  25
code/DEGwer_2_1/C.cpp.tk                            |  68
code/dmute_0_1/a.cpp.tk                             |  15
code/dmute_1_1/b.cpp.tk                             |  24
code/dmute_2_1/c2.cpp.tk                            |  94
code/fagu_0_1/A.cpp.tk                              |  15
code/fagu_1_1/B.cpp.tk                              |  14
code/fagu_2_1/C.cpp.tk                              |  265
code/FatalEagle_0_1/main.cpp.tk                     |  21
code/FatalEagle_1_1/main.cpp.tk                     |  25
code/FatalEagle_2_1/main.cpp.tk                     |  249
code/fullpower_0_1/A.cpp.tk                         |  34
code/fullpower_1_1/B.cpp.tk                         |  56
code/fullpower_2_1/C.cpp.tk                         |  122
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  11
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  18
code/ICastro_2_1/Dijkstra.cpp.tk                    |  141
code/ilackthatsuperpower_0_1/a.cpp.tk               |  76
code/ilackthatsuperpower_1_1/b.cpp.tk               |  71
code/ilackthatsuperpower_2_1/c.cpp.tk               |  120
code/iridescent_0_1/A.cpp.tk                        |  12
code/iridescent_1_1/B.cpp.tk                        |  15
code/iridescent_2_1/C.cpp.tk                        |  248
code/ishraq_0_1/main.cpp.tk                         |  16
code/ishraq_1_1/main.cpp.tk                         |  18
code/ishraq_2_1/main.cpp.tk                         |  89
code/JayXon_0_1/A.cpp.tk                            |  10
code/JayXon_1_1/B.cpp.tk                            |  29
code/JayXon_2_1/C.cpp.tk                            |  38
code/Josse_0_1/A.cpp.tk                             |  13
code/Josse_1_1/B.cpp.tk                             |  20
code/Josse_2_1/C.cpp.tk                             |  98
code/kcm1700_0_1/a.cpp.tk                           |  15
code/kcm1700_1_1/b.cpp.tk                           |  19
code/kcm1700_2_1/c.cpp.tk                           |  102
code/kevinsogo_0_1/a.cpp.tk                         |  16
code/kevinsogo_1_1/b.cpp.tk                         |  18
code/kevinsogo_2_1/c.cpp.tk                         |  152
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  20
code/LazyAnna_0_1/1.cpp.tk                          |  13
code/LazyAnna_1_1/2-1.cpp.tk                        |  17
code/LazyAnna_2_1/3.cpp.tk                          |  73
code/Merkurev_0_1/A.cpp.tk                          |  29
code/Merkurev_1_1/B.cpp.tk                          |  35
code/Merkurev_2_1/C.cpp.tk                          |  70
code/mezei_0_1/main.cpp.tk                          |  26
code/mezei_1_1/main.cpp.tk                          |  21
code/mezei_2_1/main.cpp.tk                          |  79
code/Mister_0_1/a.cpp.tk                            |  15
code/Mister_1_1/b.cpp.tk                            |  18
code/Mister_2_1/c.cpp.tk                            |  84
code/namonakiacc_0_1/cpp.cpp.tk                     |  39
code/namonakiacc_1_1/cpp.cpp.tk                     |  41
code/namonakiacc_2_1/cpp.cpp.tk                     |  180
code/Nicolas16_0_1/main.cpp.tk                      |  8
code/Nicolas16_1_1/main.cpp.tk                      |  7
code/Nicolas16_2_1/main.cpp.tk                      |  82
code/pandamonium_0_1/a.cpp.tk                       |  16
code/pandamonium_1_1/b.cpp.tk                       |  52
code/pandamonium_2_1/c.cpp.tk                       |  57
code/pflueger_0_1/A.cpp.tk                          |  10
code/pflueger_1_1/B.cpp.tk                          |  17
code/pflueger_2_1/C.cpp.tk                          |  74
code/ponyopoppo_0_1/A.cpp.tk                        |  15
code/ponyopoppo_1_1/B.cpp.tk                        |  21
code/ponyopoppo_2_1/C.cpp.tk                        |  122
code/Ragnar_0_1/A.cpp.tk                            |  19
code/Ragnar_1_1/B-2.cpp.tk                          |  24
code/Ragnar_2_1/C.cpp.tk                            |  62
code/saffah_0_1/t.cpp.tk                            |  16
code/saffah_1_1/t.cpp.tk                            |  21
code/saffah_2_1/t.cpp.tk                            |  108
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  15
code/SamanSami_2_1/C.cpp.tk                         |  12
code/Savlik_0_1/code.cpp.tk                         |  10
code/Savlik_1_1/code.cpp.tk                         |  13
code/Savlik_2_1/code.cpp.tk                         |  68
code/shik_0_1/pa.cpp.tk                             |  66
code/shik_1_1/pb.cpp.tk                             |  64
code/shik_2_1/pc.cpp.tk                             |  147
code/simsa.st_0_1/A.cpp.tk                          |  17
code/simsa.st_1_1/B.cpp.tk                          |  19
code/simsa.st_2_1/C.cpp.tk                          |  85
code/SovietUnion_0_1/A.cpp.tk                       |  23
code/SovietUnion_1_1/B.cpp.tk                       |  28
code/SovietUnion_2_1/C.cpp.tk                       |  74
code/tailed_0_1/A.cpp.tk                            |  11
code/tailed_1_1/B.cpp.tk                            |  15
code/tailed_2_1/C.cpp.tk                            |  59
code/TheNatural_0_1/A.cpp.tk                        |  14
code/TheNatural_1_1/B.cpp.tk                        |  17
code/TheNatural_2_1/C.cpp.tk                        |  179
code/TrueBamboo_0_1/test.cpp.tk                     |  18
code/TrueBamboo_1_1/test.cpp.tk                     |  22
code/TrueBamboo_2_1/test.cpp.tk                     |  52
code/tur.turczyn_0_1/A.cpp.tk                       |  20
code/tur.turczyn_1_1/B.cpp.tk                       |  27
code/tur.turczyn_2_1/C.cpp.tk                       |  57
code/Tyg3R_0_1/A.cpp.tk                             |  13
code/Tyg3R_1_1/B.cpp.tk                             |  23
code/Tyg3R_2_1/C.cpp.tk                             |  216
code/UminchuR_0_1/main.cpp.tk                       |  29
code/UminchuR_1_1/main.cpp.tk                       |  37
code/UminchuR_2_1/main.cpp.tk                       |  105
code/wo..._0_1/a.cpp.tk                             |  25
code/wo..._1_1/b.cpp.tk                             |  23
code/wo..._2_1/c.cpp.tk                             |  232
code/yswtt_0_1/A.cpp.tk                             |  9
code/yswtt_1_1/B.cpp.tk                             |  18
code/yswtt_2_1/C.cpp.tk                             |  41
code/ZhSh_0_1/a.cpp.tk                              |  10
code/ZhSh_1_1/b.cpp.tk                              |  59
code/ZhSh_2_1/c.cpp.tk                              |  273
