Begin
Comparing:  code/azariamuh_0_1/standing.cpp.tk
code/00/test.cpp.tk                                 |  22
code/01/test.cpp.tk                                 |  22
code/551100kk_0_1/A.cpp.tk                          |  80
code/551100kk_1_1/B.cpp.tk                          |  54
code/551100kk_2_1/C.cpp.tk                          |  83
code/achan1058_0_1/Q-A.cpp.tk                       |  30
code/achan1058_1_1/source.cpp.tk                    |  65
code/achan1058_2_1/source.cpp.tk                    |  105
code/alanubi_0_1/a.cpp.tk                           |  43
code/alanubi_1_1/b.cpp.tk                           |  48
code/alanubi_2_1/c.cpp.tk                           |  154
code/AntiForest_0_1/q1.cpp.tk                       |  133
code/AntiForest_1_1/q2.cpp.tk                       |  48
code/AntiForest_2_1/q3.cpp.tk                       |  158
code/apiad_0_1/A.cpp.tk                             |  56
code/apiad_1_1/B.cpp.tk                             |  72
code/apiad_2_1/C.cpp.tk                             |  62
code/azaky_0_1/A.cpp.tk                             |  151
code/azaky_1_1/B.cpp.tk                             |  131
code/azaky_2_1/C.cpp.tk                             |  169
code/azariamuh_0_1/standing.cpp.tk                  |  5439
code/azariamuh_1_1/pancake.cpp.tk                   |  150
code/azariamuh_2_1/dijkstra.cpp.tk                  |  113
code/bmerry_0_1/a.cpp.tk                            |  121
code/bmerry_1_1/b.cpp.tk                            |  84
code/bmerry_2_1/c.cpp.tk                            |  99
code/climpet_0_1/A.cpp.tk                           |  68
code/climpet_1_1/B.cpp.tk                           |  56
code/climpet_2_1/C.cpp.tk                           |  95
code/ctzsm_0_1/A.cpp.tk                             |  54
code/ctzsm_1_1/B.cpp.tk                             |  61
code/ctzsm_2_1/C.cpp.tk                             |  143
code/DanilC_0_1/problem.cpp.tk                      |  56
code/DanilC_1_1/problemB.cpp.tk                     |  78
code/DanilC_2_1/problemC.cpp.tk                     |  157
code/DEGwer_0_1/A.cpp.tk                            |  62
code/DEGwer_1_1/B.cpp.tk                            |  62
code/DEGwer_2_1/C.cpp.tk                            |  68
code/dmute_0_1/a.cpp.tk                             |  56
code/dmute_1_1/b.cpp.tk                             |  52
code/dmute_2_1/c2.cpp.tk                            |  90
code/fagu_0_1/A.cpp.tk                              |  33
code/fagu_1_1/B.cpp.tk                              |  34
code/fagu_2_1/C.cpp.tk                              |  83
code/FatalEagle_0_1/main.cpp.tk                     |  62
code/FatalEagle_1_1/main.cpp.tk                     |  61
code/FatalEagle_2_1/main.cpp.tk                     |  228
code/fullpower_0_1/A.cpp.tk                         |  60
code/fullpower_1_1/B.cpp.tk                         |  76
code/fullpower_2_1/C.cpp.tk                         |  119
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  37
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  32
code/ICastro_2_1/Dijkstra.cpp.tk                    |  191
code/ilackthatsuperpower_0_1/a.cpp.tk               |  139
code/ilackthatsuperpower_1_1/b.cpp.tk               |  129
code/ilackthatsuperpower_2_1/c.cpp.tk               |  188
code/iridescent_0_1/A.cpp.tk                        |  22
code/iridescent_1_1/B.cpp.tk                        |  30
code/iridescent_2_1/C.cpp.tk                        |  44
code/ishraq_0_1/main.cpp.tk                         |  58
code/ishraq_1_1/main.cpp.tk                         |  58
code/ishraq_2_1/main.cpp.tk                         |  139
code/JayXon_0_1/A.cpp.tk                            |  54
code/JayXon_1_1/B.cpp.tk                            |  33
code/JayXon_2_1/C.cpp.tk                            |  54
code/Josse_0_1/A.cpp.tk                             |  39
code/Josse_1_1/B.cpp.tk                             |  31
code/Josse_2_1/C.cpp.tk                             |  126
code/kcm1700_0_1/a.cpp.tk                           |  59
code/kcm1700_1_1/b.cpp.tk                           |  45
code/kcm1700_2_1/c.cpp.tk                           |  112
code/kevinsogo_0_1/a.cpp.tk                         |  51
code/kevinsogo_1_1/b.cpp.tk                         |  49
code/kevinsogo_2_1/c.cpp.tk                         |  115
code/ksun48_0_1/A.cpp.tk                            |  6
code/ksun48_1_1/B.cpp.tk                            |  6
code/ksun48_2_1/C.cpp.tk                            |  28
code/LazyAnna_0_1/1.cpp.tk                          |  40
code/LazyAnna_1_1/2-1.cpp.tk                        |  32
code/LazyAnna_2_1/3.cpp.tk                          |  55
code/Merkurev_0_1/A.cpp.tk                          |  59
code/Merkurev_1_1/B.cpp.tk                          |  79
code/Merkurev_2_1/C.cpp.tk                          |  72
code/mezei_0_1/main.cpp.tk                          |  63
code/mezei_1_1/main.cpp.tk                          |  44
code/mezei_2_1/main.cpp.tk                          |  124
code/Mister_0_1/a.cpp.tk                            |  33
code/Mister_1_1/b.cpp.tk                            |  41
code/Mister_2_1/c.cpp.tk                            |  64
code/namonakiacc_0_1/cpp.cpp.tk                     |  99
code/namonakiacc_1_1/cpp.cpp.tk                     |  95
code/namonakiacc_2_1/cpp.cpp.tk                     |  124
code/Nicolas16_0_1/main.cpp.tk                      |  22
code/Nicolas16_1_1/main.cpp.tk                      |  21
code/Nicolas16_2_1/main.cpp.tk                      |  117
code/pandamonium_0_1/a.cpp.tk                       |  46
code/pandamonium_1_1/b.cpp.tk                       |  71
code/pandamonium_2_1/c.cpp.tk                       |  53
code/pflueger_0_1/A.cpp.tk                          |  42
code/pflueger_1_1/B.cpp.tk                          |  31
code/pflueger_2_1/C.cpp.tk                          |  84
code/ponyopoppo_0_1/A.cpp.tk                        |  31
code/ponyopoppo_1_1/B.cpp.tk                        |  36
code/ponyopoppo_2_1/C.cpp.tk                        |  186
code/Ragnar_0_1/A.cpp.tk                            |  45
code/Ragnar_1_1/B-2.cpp.tk                          |  42
code/Ragnar_2_1/C.cpp.tk                            |  61
code/saffah_0_1/t.cpp.tk                            |  56
code/saffah_1_1/t.cpp.tk                            |  115
code/saffah_2_1/t.cpp.tk                            |  204
code/SamanSami_0_1/A.cpp.tk                         |  11
code/SamanSami_1_1/B.cpp.tk                         |  32
code/SamanSami_2_1/C.cpp.tk                         |  18
code/Savlik_0_1/code.cpp.tk                         |  39
code/Savlik_1_1/code.cpp.tk                         |  28
code/Savlik_2_1/code.cpp.tk                         |  96
code/shik_0_1/pa.cpp.tk                             |  133
code/shik_1_1/pb.cpp.tk                             |  113
code/shik_2_1/pc.cpp.tk                             |  181
code/simsa.st_0_1/A.cpp.tk                          |  91
code/simsa.st_1_1/B.cpp.tk                          |  105
code/simsa.st_2_1/C.cpp.tk                          |  177
code/SovietUnion_0_1/A.cpp.tk                       |  49
code/SovietUnion_1_1/B.cpp.tk                       |  59
code/SovietUnion_2_1/C.cpp.tk                       |  121
code/tailed_0_1/A.cpp.tk                            |  44
code/tailed_1_1/B.cpp.tk                            |  33
code/tailed_2_1/C.cpp.tk                            |  67
code/TheNatural_0_1/A.cpp.tk                        |  42
code/TheNatural_1_1/B.cpp.tk                        |  36
code/TheNatural_2_1/C.cpp.tk                        |  40
code/TrueBamboo_0_1/test.cpp.tk                     |  35
code/TrueBamboo_1_1/test.cpp.tk                     |  36
code/TrueBamboo_2_1/test.cpp.tk                     |  73
code/tur.turczyn_0_1/A.cpp.tk                       |  38
code/tur.turczyn_1_1/B.cpp.tk                       |  41
code/tur.turczyn_2_1/C.cpp.tk                       |  43
code/Tyg3R_0_1/A.cpp.tk                             |  45
code/Tyg3R_1_1/B.cpp.tk                             |  64
code/Tyg3R_2_1/C.cpp.tk                             |  118
code/UminchuR_0_1/main.cpp.tk                       |  58
code/UminchuR_1_1/main.cpp.tk                       |  79
code/UminchuR_2_1/main.cpp.tk                       |  132
code/wo..._0_1/a.cpp.tk                             |  49
code/wo..._1_1/b.cpp.tk                             |  51
code/wo..._2_1/c.cpp.tk                             |  111
code/yswtt_0_1/A.cpp.tk                             |  28
code/yswtt_1_1/B.cpp.tk                             |  30
code/yswtt_2_1/C.cpp.tk                             |  80
code/ZhSh_0_1/a.cpp.tk                              |  48
code/ZhSh_1_1/b.cpp.tk                              |  98
code/ZhSh_2_1/c.cpp.tk                              |  124
