Begin
Comparing:  code/SovietUnion_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  43
code/551100kk_1_1/B.cpp.tk                          |  58
code/551100kk_2_1/C.cpp.tk                          |  61
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  15
code/achan1058_2_1/source.cpp.tk                    |  32
code/alanubi_0_1/a.cpp.tk                           |  45
code/alanubi_1_1/b.cpp.tk                           |  65
code/alanubi_2_1/c.cpp.tk                           |  106
code/AntiForest_0_1/q1.cpp.tk                       |  71
code/AntiForest_1_1/q2.cpp.tk                       |  58
code/AntiForest_2_1/q3.cpp.tk                       |  101
code/apiad_0_1/A.cpp.tk                             |  18
code/apiad_1_1/B.cpp.tk                             |  24
code/apiad_2_1/C.cpp.tk                             |  33
code/azaky_0_1/A.cpp.tk                             |  21
code/azaky_1_1/B.cpp.tk                             |  36
code/azaky_2_1/C.cpp.tk                             |  52
code/azariamuh_0_1/standing.cpp.tk                  |  18
code/azariamuh_1_1/pancake.cpp.tk                   |  31
code/azariamuh_2_1/dijkstra.cpp.tk                  |  19
code/bmerry_0_1/a.cpp.tk                            |  51
code/bmerry_1_1/b.cpp.tk                            |  62
code/bmerry_2_1/c.cpp.tk                            |  55
code/climpet_0_1/A.cpp.tk                           |  102
code/climpet_1_1/B.cpp.tk                           |  79
code/climpet_2_1/C.cpp.tk                           |  109
code/ctzsm_0_1/A.cpp.tk                             |  253
code/ctzsm_1_1/B.cpp.tk                             |  225
code/ctzsm_2_1/C.cpp.tk                             |  267
code/DanilC_0_1/problem.cpp.tk                      |  114
code/DanilC_1_1/problemB.cpp.tk                     |  127
code/DanilC_2_1/problemC.cpp.tk                     |  114
code/DEGwer_0_1/A.cpp.tk                            |  57
code/DEGwer_1_1/B.cpp.tk                            |  63
code/DEGwer_2_1/C.cpp.tk                            |  40
code/dmute_0_1/a.cpp.tk                             |  63
code/dmute_1_1/b.cpp.tk                             |  87
code/dmute_2_1/c2.cpp.tk                            |  101
code/fagu_0_1/A.cpp.tk                              |  19
code/fagu_1_1/B.cpp.tk                              |  19
code/fagu_2_1/C.cpp.tk                              |  38
code/FatalEagle_0_1/main.cpp.tk                     |  89
code/FatalEagle_1_1/main.cpp.tk                     |  108
code/FatalEagle_2_1/main.cpp.tk                     |  233
code/fullpower_0_1/A.cpp.tk                         |  151
code/fullpower_1_1/B.cpp.tk                         |  149
code/fullpower_2_1/C.cpp.tk                         |  186
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  60
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  70
code/ICastro_2_1/Dijkstra.cpp.tk                    |  91
code/ilackthatsuperpower_0_1/a.cpp.tk               |  117
code/ilackthatsuperpower_1_1/b.cpp.tk               |  77
code/ilackthatsuperpower_2_1/c.cpp.tk               |  90
code/iridescent_0_1/A.cpp.tk                        |  34
code/iridescent_1_1/B.cpp.tk                        |  73
code/iridescent_2_1/C.cpp.tk                        |  48
code/ishraq_0_1/main.cpp.tk                         |  15
code/ishraq_1_1/main.cpp.tk                         |  32
code/ishraq_2_1/main.cpp.tk                         |  53
code/JayXon_0_1/A.cpp.tk                            |  20
code/JayXon_1_1/B.cpp.tk                            |  44
code/JayXon_2_1/C.cpp.tk                            |  28
code/Josse_0_1/A.cpp.tk                             |  24
code/Josse_1_1/B.cpp.tk                             |  46
code/Josse_2_1/C.cpp.tk                             |  85
code/kcm1700_0_1/a.cpp.tk                           |  54
code/kcm1700_1_1/b.cpp.tk                           |  83
code/kcm1700_2_1/c.cpp.tk                           |  97
code/kevinsogo_0_1/a.cpp.tk                         |  15
code/kevinsogo_1_1/b.cpp.tk                         |  28
code/kevinsogo_2_1/c.cpp.tk                         |  59
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  14
code/LazyAnna_0_1/1.cpp.tk                          |  90
code/LazyAnna_1_1/2-1.cpp.tk                        |  82
code/LazyAnna_2_1/3.cpp.tk                          |  58
code/Merkurev_0_1/A.cpp.tk                          |  93
code/Merkurev_1_1/B.cpp.tk                          |  101
code/Merkurev_2_1/C.cpp.tk                          |  110
code/mezei_0_1/main.cpp.tk                          |  76
code/mezei_1_1/main.cpp.tk                          |  61
code/mezei_2_1/main.cpp.tk                          |  95
code/Mister_0_1/a.cpp.tk                            |  104
code/Mister_1_1/b.cpp.tk                            |  98
code/Mister_2_1/c.cpp.tk                            |  173
code/namonakiacc_0_1/cpp.cpp.tk                     |  23
code/namonakiacc_1_1/cpp.cpp.tk                     |  25
code/namonakiacc_2_1/cpp.cpp.tk                     |  50
code/Nicolas16_0_1/main.cpp.tk                      |  29
code/Nicolas16_1_1/main.cpp.tk                      |  29
code/Nicolas16_2_1/main.cpp.tk                      |  131
code/pandamonium_0_1/a.cpp.tk                       |  64
code/pandamonium_1_1/b.cpp.tk                       |  81
code/pandamonium_2_1/c.cpp.tk                       |  69
code/pflueger_0_1/A.cpp.tk                          |  38
code/pflueger_1_1/B.cpp.tk                          |  49
code/pflueger_2_1/C.cpp.tk                          |  77
code/ponyopoppo_0_1/A.cpp.tk                        |  9
code/ponyopoppo_1_1/B.cpp.tk                        |  20
code/ponyopoppo_2_1/C.cpp.tk                        |  74
code/Ragnar_0_1/A.cpp.tk                            |  11
code/Ragnar_1_1/B-2.cpp.tk                          |  27
code/Ragnar_2_1/C.cpp.tk                            |  35
code/saffah_0_1/t.cpp.tk                            |  17
code/saffah_1_1/t.cpp.tk                            |  27
code/saffah_2_1/t.cpp.tk                            |  58
code/SamanSami_0_1/A.cpp.tk                         |  14
code/SamanSami_1_1/B.cpp.tk                         |  54
code/SamanSami_2_1/C.cpp.tk                         |  6
code/Savlik_0_1/code.cpp.tk                         |  26
code/Savlik_1_1/code.cpp.tk                         |  9
code/Savlik_2_1/code.cpp.tk                         |  43
code/shik_0_1/pa.cpp.tk                             |  42
code/shik_1_1/pb.cpp.tk                             |  41
code/shik_2_1/pc.cpp.tk                             |  74
code/simsa.st_0_1/A.cpp.tk                          |  15
code/simsa.st_1_1/B.cpp.tk                          |  22
code/simsa.st_2_1/C.cpp.tk                          |  56
code/SovietUnion_0_1/A.cpp.tk                       |  422
code/SovietUnion_1_1/B.cpp.tk                       |  12193
code/SovietUnion_2_1/C.cpp.tk                       |  108
code/tailed_0_1/A.cpp.tk                            |  21
code/tailed_1_1/B.cpp.tk                            |  43
code/tailed_2_1/C.cpp.tk                            |  28
code/TheNatural_0_1/A.cpp.tk                        |  52
code/TheNatural_1_1/B.cpp.tk                        |  75
code/TheNatural_2_1/C.cpp.tk                        |  28
code/TrueBamboo_0_1/test.cpp.tk                     |  24
code/TrueBamboo_1_1/test.cpp.tk                     |  34
code/TrueBamboo_2_1/test.cpp.tk                     |  44
code/tur.turczyn_0_1/A.cpp.tk                       |  8
code/tur.turczyn_1_1/B.cpp.tk                       |  13
code/tur.turczyn_2_1/C.cpp.tk                       |  19
code/Tyg3R_0_1/A.cpp.tk                             |  10
code/Tyg3R_1_1/B.cpp.tk                             |  19
code/Tyg3R_2_1/C.cpp.tk                             |  19
code/UminchuR_0_1/main.cpp.tk                       |  35
code/UminchuR_1_1/main.cpp.tk                       |  49
code/UminchuR_2_1/main.cpp.tk                       |  65
code/wo..._0_1/a.cpp.tk                             |  64
code/wo..._1_1/b.cpp.tk                             |  78
code/wo..._2_1/c.cpp.tk                             |  108
code/yswtt_0_1/A.cpp.tk                             |  104
code/yswtt_1_1/B.cpp.tk                             |  106
code/yswtt_2_1/C.cpp.tk                             |  73
code/ZhSh_0_1/a.cpp.tk                              |  88
code/ZhSh_1_1/b.cpp.tk                              |  117
code/ZhSh_2_1/c.cpp.tk                              |  90
