Begin
Comparing:  code/AntiForest_0_1/q1.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  94
code/551100kk_1_1/B.cpp.tk                          |  73
code/551100kk_2_1/C.cpp.tk                          |  68
code/achan1058_0_1/Q-A.cpp.tk                       |  18
code/achan1058_1_1/source.cpp.tk                    |  30
code/achan1058_2_1/source.cpp.tk                    |  48
code/alanubi_0_1/a.cpp.tk                           |  24
code/alanubi_1_1/b.cpp.tk                           |  26
code/alanubi_2_1/c.cpp.tk                           |  61
code/AntiForest_0_1/q1.cpp.tk                       |  7594
code/AntiForest_1_1/q2.cpp.tk                       |  181
code/AntiForest_2_1/q3.cpp.tk                       |  188
code/apiad_0_1/A.cpp.tk                             |  42
code/apiad_1_1/B.cpp.tk                             |  35
code/apiad_2_1/C.cpp.tk                             |  41
code/azaky_0_1/A.cpp.tk                             |  100
code/azaky_1_1/B.cpp.tk                             |  56
code/azaky_2_1/C.cpp.tk                             |  87
code/azariamuh_0_1/standing.cpp.tk                  |  57
code/azariamuh_1_1/pancake.cpp.tk                   |  61
code/azariamuh_2_1/dijkstra.cpp.tk                  |  36
code/bmerry_0_1/a.cpp.tk                            |  66
code/bmerry_1_1/b.cpp.tk                            |  43
code/bmerry_2_1/c.cpp.tk                            |  53
code/climpet_0_1/A.cpp.tk                           |  27
code/climpet_1_1/B.cpp.tk                           |  26
code/climpet_2_1/C.cpp.tk                           |  43
code/ctzsm_0_1/A.cpp.tk                             |  96
code/ctzsm_1_1/B.cpp.tk                             |  78
code/ctzsm_2_1/C.cpp.tk                             |  124
code/DanilC_0_1/problem.cpp.tk                      |  25
code/DanilC_1_1/problemB.cpp.tk                     |  38
code/DanilC_2_1/problemC.cpp.tk                     |  76
code/DEGwer_0_1/A.cpp.tk                            |  26
code/DEGwer_1_1/B.cpp.tk                            |  25
code/DEGwer_2_1/C.cpp.tk                            |  31
code/dmute_0_1/a.cpp.tk                             |  26
code/dmute_1_1/b.cpp.tk                             |  34
code/dmute_2_1/c2.cpp.tk                            |  48
code/fagu_0_1/A.cpp.tk                              |  19
code/fagu_1_1/B.cpp.tk                              |  20
code/fagu_2_1/C.cpp.tk                              |  49
code/FatalEagle_0_1/main.cpp.tk                     |  49
code/FatalEagle_1_1/main.cpp.tk                     |  47
code/FatalEagle_2_1/main.cpp.tk                     |  142
code/fullpower_0_1/A.cpp.tk                         |  84
code/fullpower_1_1/B.cpp.tk                         |  65
code/fullpower_2_1/C.cpp.tk                         |  92
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  13
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  14
code/ICastro_2_1/Dijkstra.cpp.tk                    |  119
code/ilackthatsuperpower_0_1/a.cpp.tk               |  75
code/ilackthatsuperpower_1_1/b.cpp.tk               |  62
code/ilackthatsuperpower_2_1/c.cpp.tk               |  90
code/iridescent_0_1/A.cpp.tk                        |  7
code/iridescent_1_1/B.cpp.tk                        |  13
code/iridescent_2_1/C.cpp.tk                        |  21
code/ishraq_0_1/main.cpp.tk                         |  37
code/ishraq_1_1/main.cpp.tk                         |  33
code/ishraq_2_1/main.cpp.tk                         |  109
code/JayXon_0_1/A.cpp.tk                            |  43
code/JayXon_1_1/B.cpp.tk                            |  16
code/JayXon_2_1/C.cpp.tk                            |  25
code/Josse_0_1/A.cpp.tk                             |  19
code/Josse_1_1/B.cpp.tk                             |  15
code/Josse_2_1/C.cpp.tk                             |  60
code/kcm1700_0_1/a.cpp.tk                           |  27
code/kcm1700_1_1/b.cpp.tk                           |  23
code/kcm1700_2_1/c.cpp.tk                           |  60
code/kevinsogo_0_1/a.cpp.tk                         |  84
code/kevinsogo_1_1/b.cpp.tk                         |  26
code/kevinsogo_2_1/c.cpp.tk                         |  73
code/ksun48_0_1/A.cpp.tk                            |  6
code/ksun48_1_1/B.cpp.tk                            |  6
code/ksun48_2_1/C.cpp.tk                            |  15
code/LazyAnna_0_1/1.cpp.tk                          |  21
code/LazyAnna_1_1/2-1.cpp.tk                        |  13
code/LazyAnna_2_1/3.cpp.tk                          |  25
code/Merkurev_0_1/A.cpp.tk                          |  84
code/Merkurev_1_1/B.cpp.tk                          |  59
code/Merkurev_2_1/C.cpp.tk                          |  63
code/mezei_0_1/main.cpp.tk                          |  29
code/mezei_1_1/main.cpp.tk                          |  18
code/mezei_2_1/main.cpp.tk                          |  55
code/Mister_0_1/a.cpp.tk                            |  21
code/Mister_1_1/b.cpp.tk                            |  21
code/Mister_2_1/c.cpp.tk                            |  38
code/namonakiacc_0_1/cpp.cpp.tk                     |  53
code/namonakiacc_1_1/cpp.cpp.tk                     |  51
code/namonakiacc_2_1/cpp.cpp.tk                     |  88
code/Nicolas16_0_1/main.cpp.tk                      |  13
code/Nicolas16_1_1/main.cpp.tk                      |  11
code/Nicolas16_2_1/main.cpp.tk                      |  62
code/pandamonium_0_1/a.cpp.tk                       |  23
code/pandamonium_1_1/b.cpp.tk                       |  34
code/pandamonium_2_1/c.cpp.tk                       |  31
code/pflueger_0_1/A.cpp.tk                          |  10
code/pflueger_1_1/B.cpp.tk                          |  13
code/pflueger_2_1/C.cpp.tk                          |  38
code/ponyopoppo_0_1/A.cpp.tk                        |  40
code/ponyopoppo_1_1/B.cpp.tk                        |  21
code/ponyopoppo_2_1/C.cpp.tk                        |  89
code/Ragnar_0_1/A.cpp.tk                            |  32
code/Ragnar_1_1/B-2.cpp.tk                          |  21
code/Ragnar_2_1/C.cpp.tk                            |  30
code/saffah_0_1/t.cpp.tk                            |  42
code/saffah_1_1/t.cpp.tk                            |  53
code/saffah_2_1/t.cpp.tk                            |  106
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  12
code/SamanSami_2_1/C.cpp.tk                         |  9
code/Savlik_0_1/code.cpp.tk                         |  34
code/Savlik_1_1/code.cpp.tk                         |  15
code/Savlik_2_1/code.cpp.tk                         |  44
code/shik_0_1/pa.cpp.tk                             |  154
code/shik_1_1/pb.cpp.tk                             |  59
code/shik_2_1/pc.cpp.tk                             |  93
code/simsa.st_0_1/A.cpp.tk                          |  32
code/simsa.st_1_1/B.cpp.tk                          |  47
code/simsa.st_2_1/C.cpp.tk                          |  94
code/SovietUnion_0_1/A.cpp.tk                       |  90
code/SovietUnion_1_1/B.cpp.tk                       |  90
code/SovietUnion_2_1/C.cpp.tk                       |  76
code/tailed_0_1/A.cpp.tk                            |  34
code/tailed_1_1/B.cpp.tk                            |  12
code/tailed_2_1/C.cpp.tk                            |  30
code/TheNatural_0_1/A.cpp.tk                        |  62
code/TheNatural_1_1/B.cpp.tk                        |  14
code/TheNatural_2_1/C.cpp.tk                        |  22
code/TrueBamboo_0_1/test.cpp.tk                     |  23
code/TrueBamboo_1_1/test.cpp.tk                     |  22
code/TrueBamboo_2_1/test.cpp.tk                     |  43
code/tur.turczyn_0_1/A.cpp.tk                       |  15
code/tur.turczyn_1_1/B.cpp.tk                       |  21
code/tur.turczyn_2_1/C.cpp.tk                       |  21
code/Tyg3R_0_1/A.cpp.tk                             |  25
code/Tyg3R_1_1/B.cpp.tk                             |  38
code/Tyg3R_2_1/C.cpp.tk                             |  44
code/UminchuR_0_1/main.cpp.tk                       |  49
code/UminchuR_1_1/main.cpp.tk                       |  64
code/UminchuR_2_1/main.cpp.tk                       |  89
code/wo..._0_1/a.cpp.tk                             |  35
code/wo..._1_1/b.cpp.tk                             |  23
code/wo..._2_1/c.cpp.tk                             |  61
code/yswtt_0_1/A.cpp.tk                             |  27
code/yswtt_1_1/B.cpp.tk                             |  14
code/yswtt_2_1/C.cpp.tk                             |  30
code/ZhSh_0_1/a.cpp.tk                              |  12
code/ZhSh_1_1/b.cpp.tk                              |  45
code/ZhSh_2_1/c.cpp.tk                              |  60
