Begin
Comparing:  code/dmute_2_1/c2.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  12
code/551100kk_1_1/B.cpp.tk                          |  22
code/551100kk_2_1/C.cpp.tk                          |  37
code/achan1058_0_1/Q-A.cpp.tk                       |  5
code/achan1058_1_1/source.cpp.tk                    |  10
code/achan1058_2_1/source.cpp.tk                    |  26
code/alanubi_0_1/a.cpp.tk                           |  24
code/alanubi_1_1/b.cpp.tk                           |  34
code/alanubi_2_1/c.cpp.tk                           |  91
code/AntiForest_0_1/q1.cpp.tk                       |  12
code/AntiForest_1_1/q2.cpp.tk                       |  5
code/AntiForest_2_1/q3.cpp.tk                       |  42
code/apiad_0_1/A.cpp.tk                             |  11
code/apiad_1_1/B.cpp.tk                             |  14
code/apiad_2_1/C.cpp.tk                             |  35
code/azaky_0_1/A.cpp.tk                             |  12
code/azaky_1_1/B.cpp.tk                             |  14
code/azaky_2_1/C.cpp.tk                             |  44
code/azariamuh_0_1/standing.cpp.tk                  |  8
code/azariamuh_1_1/pancake.cpp.tk                   |  23
code/azariamuh_2_1/dijkstra.cpp.tk                  |  38
code/bmerry_0_1/a.cpp.tk                            |  39
code/bmerry_1_1/b.cpp.tk                            |  47
code/bmerry_2_1/c.cpp.tk                            |  74
code/climpet_0_1/A.cpp.tk                           |  20
code/climpet_1_1/B.cpp.tk                           |  24
code/climpet_2_1/C.cpp.tk                           |  50
code/ctzsm_0_1/A.cpp.tk                             |  21
code/ctzsm_1_1/B.cpp.tk                             |  28
code/ctzsm_2_1/C.cpp.tk                             |  81
code/DanilC_0_1/problem.cpp.tk                      |  25
code/DanilC_1_1/problemB.cpp.tk                     |  40
code/DanilC_2_1/problemC.cpp.tk                     |  58
code/DEGwer_0_1/A.cpp.tk                            |  29
code/DEGwer_1_1/B.cpp.tk                            |  29
code/DEGwer_2_1/C.cpp.tk                            |  36
code/dmute_0_1/a.cpp.tk                             |  34
code/dmute_1_1/b.cpp.tk                             |  53
code/dmute_2_1/c2.cpp.tk                            |  114181
code/fagu_0_1/A.cpp.tk                              |  10
code/fagu_1_1/B.cpp.tk                              |  10
code/fagu_2_1/C.cpp.tk                              |  40
code/FatalEagle_0_1/main.cpp.tk                     |  35
code/FatalEagle_1_1/main.cpp.tk                     |  57
code/FatalEagle_2_1/main.cpp.tk                     |  209
code/fullpower_0_1/A.cpp.tk                         |  53
code/fullpower_1_1/B.cpp.tk                         |  82
code/fullpower_2_1/C.cpp.tk                         |  292
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  12
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  20
code/ICastro_2_1/Dijkstra.cpp.tk                    |  76
code/ilackthatsuperpower_0_1/a.cpp.tk               |  53
code/ilackthatsuperpower_1_1/b.cpp.tk               |  51
code/ilackthatsuperpower_2_1/c.cpp.tk               |  68
code/iridescent_0_1/A.cpp.tk                        |  17
code/iridescent_1_1/B.cpp.tk                        |  33
code/iridescent_2_1/C.cpp.tk                        |  42
code/ishraq_0_1/main.cpp.tk                         |  9
code/ishraq_1_1/main.cpp.tk                         |  14
code/ishraq_2_1/main.cpp.tk                         |  52
code/JayXon_0_1/A.cpp.tk                            |  13
code/JayXon_1_1/B.cpp.tk                            |  32
code/JayXon_2_1/C.cpp.tk                            |  22
code/Josse_0_1/A.cpp.tk                             |  18
code/Josse_1_1/B.cpp.tk                             |  29
code/Josse_2_1/C.cpp.tk                             |  71
code/kcm1700_0_1/a.cpp.tk                           |  30
code/kcm1700_1_1/b.cpp.tk                           |  43
code/kcm1700_2_1/c.cpp.tk                           |  101
code/kevinsogo_0_1/a.cpp.tk                         |  8
code/kevinsogo_1_1/b.cpp.tk                         |  12
code/kevinsogo_2_1/c.cpp.tk                         |  87
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  15
code/LazyAnna_0_1/1.cpp.tk                          |  14
code/LazyAnna_1_1/2-1.cpp.tk                        |  22
code/LazyAnna_2_1/3.cpp.tk                          |  29
code/Merkurev_0_1/A.cpp.tk                          |  44
code/Merkurev_1_1/B.cpp.tk                          |  58
code/Merkurev_2_1/C.cpp.tk                          |  95
code/mezei_0_1/main.cpp.tk                          |  43
code/mezei_1_1/main.cpp.tk                          |  34
code/mezei_2_1/main.cpp.tk                          |  72
code/Mister_0_1/a.cpp.tk                            |  18
code/Mister_1_1/b.cpp.tk                            |  26
code/Mister_2_1/c.cpp.tk                            |  48
code/namonakiacc_0_1/cpp.cpp.tk                     |  13
code/namonakiacc_1_1/cpp.cpp.tk                     |  13
code/namonakiacc_2_1/cpp.cpp.tk                     |  472
code/Nicolas16_0_1/main.cpp.tk                      |  20
code/Nicolas16_1_1/main.cpp.tk                      |  20
code/Nicolas16_2_1/main.cpp.tk                      |  91
code/pandamonium_0_1/a.cpp.tk                       |  35
code/pandamonium_1_1/b.cpp.tk                       |  59
code/pandamonium_2_1/c.cpp.tk                       |  138
code/pflueger_0_1/A.cpp.tk                          |  22
code/pflueger_1_1/B.cpp.tk                          |  33
code/pflueger_2_1/C.cpp.tk                          |  85
code/ponyopoppo_0_1/A.cpp.tk                        |  7
code/ponyopoppo_1_1/B.cpp.tk                        |  9
code/ponyopoppo_2_1/C.cpp.tk                        |  64
code/Ragnar_0_1/A.cpp.tk                            |  7
code/Ragnar_1_1/B-2.cpp.tk                          |  13
code/Ragnar_2_1/C.cpp.tk                            |  27
code/saffah_0_1/t.cpp.tk                            |  8
code/saffah_1_1/t.cpp.tk                            |  11
code/saffah_2_1/t.cpp.tk                            |  45
code/SamanSami_0_1/A.cpp.tk                         |  9
code/SamanSami_1_1/B.cpp.tk                         |  30
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  13
code/Savlik_1_1/code.cpp.tk                         |  6
code/Savlik_2_1/code.cpp.tk                         |  34
code/shik_0_1/pa.cpp.tk                             |  29
code/shik_1_1/pb.cpp.tk                             |  30
code/shik_2_1/pc.cpp.tk                             |  59
code/simsa.st_0_1/A.cpp.tk                          |  7
code/simsa.st_1_1/B.cpp.tk                          |  9
code/simsa.st_2_1/C.cpp.tk                          |  42
code/SovietUnion_0_1/A.cpp.tk                       |  26
code/SovietUnion_1_1/B.cpp.tk                       |  32
code/SovietUnion_2_1/C.cpp.tk                       |  38
code/tailed_0_1/A.cpp.tk                            |  15
code/tailed_1_1/B.cpp.tk                            |  20
code/tailed_2_1/C.cpp.tk                            |  28
code/TheNatural_0_1/A.cpp.tk                        |  32
code/TheNatural_1_1/B.cpp.tk                        |  35
code/TheNatural_2_1/C.cpp.tk                        |  34
code/TrueBamboo_0_1/test.cpp.tk                     |  19
code/TrueBamboo_1_1/test.cpp.tk                     |  21
code/TrueBamboo_2_1/test.cpp.tk                     |  36
code/tur.turczyn_0_1/A.cpp.tk                       |  6
code/tur.turczyn_1_1/B.cpp.tk                       |  10
code/tur.turczyn_2_1/C.cpp.tk                       |  20
code/Tyg3R_0_1/A.cpp.tk                             |  6
code/Tyg3R_1_1/B.cpp.tk                             |  11
code/Tyg3R_2_1/C.cpp.tk                             |  26
code/UminchuR_0_1/main.cpp.tk                       |  12
code/UminchuR_1_1/main.cpp.tk                       |  16
code/UminchuR_2_1/main.cpp.tk                       |  154
code/wo..._0_1/a.cpp.tk                             |  34
code/wo..._1_1/b.cpp.tk                             |  49
code/wo..._2_1/c.cpp.tk                             |  119
code/yswtt_0_1/A.cpp.tk                             |  13
code/yswtt_1_1/B.cpp.tk                             |  20
code/yswtt_2_1/C.cpp.tk                             |  31
code/ZhSh_0_1/a.cpp.tk                              |  13
code/ZhSh_1_1/b.cpp.tk                              |  44
code/ZhSh_2_1/c.cpp.tk                              |  72
