Begin
Comparing:  code/551100kk_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  4562
code/551100kk_1_1/B.cpp.tk                          |  213
code/551100kk_2_1/C.cpp.tk                          |  188
code/achan1058_0_1/Q-A.cpp.tk                       |  13
code/achan1058_1_1/source.cpp.tk                    |  22
code/achan1058_2_1/source.cpp.tk                    |  53
code/alanubi_0_1/a.cpp.tk                           |  30
code/alanubi_1_1/b.cpp.tk                           |  27
code/alanubi_2_1/c.cpp.tk                           |  82
code/AntiForest_0_1/q1.cpp.tk                       |  106
code/AntiForest_1_1/q2.cpp.tk                       |  56
code/AntiForest_2_1/q3.cpp.tk                       |  82
code/apiad_0_1/A.cpp.tk                             |  69
code/apiad_1_1/B.cpp.tk                             |  29
code/apiad_2_1/C.cpp.tk                             |  35
code/azaky_0_1/A.cpp.tk                             |  131
code/azaky_1_1/B.cpp.tk                             |  32
code/azaky_2_1/C.cpp.tk                             |  64
code/azariamuh_0_1/standing.cpp.tk                  |  43
code/azariamuh_1_1/pancake.cpp.tk                   |  38
code/azariamuh_2_1/dijkstra.cpp.tk                  |  24
code/bmerry_0_1/a.cpp.tk                            |  115
code/bmerry_1_1/b.cpp.tk                            |  50
code/bmerry_2_1/c.cpp.tk                            |  51
code/climpet_0_1/A.cpp.tk                           |  32
code/climpet_1_1/B.cpp.tk                           |  31
code/climpet_2_1/C.cpp.tk                           |  52
code/ctzsm_0_1/A.cpp.tk                             |  95
code/ctzsm_1_1/B.cpp.tk                             |  53
code/ctzsm_2_1/C.cpp.tk                             |  101
code/DanilC_0_1/problem.cpp.tk                      |  30
code/DanilC_1_1/problemB.cpp.tk                     |  40
code/DanilC_2_1/problemC.cpp.tk                     |  116
code/DEGwer_0_1/A.cpp.tk                            |  38
code/DEGwer_1_1/B.cpp.tk                            |  31
code/DEGwer_2_1/C.cpp.tk                            |  34
code/dmute_0_1/a.cpp.tk                             |  64
code/dmute_1_1/b.cpp.tk                             |  44
code/dmute_2_1/c2.cpp.tk                            |  62
code/fagu_0_1/A.cpp.tk                              |  20
code/fagu_1_1/B.cpp.tk                              |  15
code/fagu_2_1/C.cpp.tk                              |  40
code/FatalEagle_0_1/main.cpp.tk                     |  84
code/FatalEagle_1_1/main.cpp.tk                     |  77
code/FatalEagle_2_1/main.cpp.tk                     |  184
code/fullpower_0_1/A.cpp.tk                         |  72
code/fullpower_1_1/B.cpp.tk                         |  90
code/fullpower_2_1/C.cpp.tk                         |  119
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  15
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  16
code/ICastro_2_1/Dijkstra.cpp.tk                    |  117
code/ilackthatsuperpower_0_1/a.cpp.tk               |  88
code/ilackthatsuperpower_1_1/b.cpp.tk               |  87
code/ilackthatsuperpower_2_1/c.cpp.tk               |  113
code/iridescent_0_1/A.cpp.tk                        |  18
code/iridescent_1_1/B.cpp.tk                        |  30
code/iridescent_2_1/C.cpp.tk                        |  26
code/ishraq_0_1/main.cpp.tk                         |  44
code/ishraq_1_1/main.cpp.tk                         |  21
code/ishraq_2_1/main.cpp.tk                         |  71
code/JayXon_0_1/A.cpp.tk                            |  233
code/JayXon_1_1/B.cpp.tk                            |  25
code/JayXon_2_1/C.cpp.tk                            |  42
code/Josse_0_1/A.cpp.tk                             |  16
code/Josse_1_1/B.cpp.tk                             |  19
code/Josse_2_1/C.cpp.tk                             |  83
code/kcm1700_0_1/a.cpp.tk                           |  67
code/kcm1700_1_1/b.cpp.tk                           |  35
code/kcm1700_2_1/c.cpp.tk                           |  67
code/kevinsogo_0_1/a.cpp.tk                         |  64
code/kevinsogo_1_1/b.cpp.tk                         |  27
code/kevinsogo_2_1/c.cpp.tk                         |  62
code/ksun48_0_1/A.cpp.tk                            |  6
code/ksun48_1_1/B.cpp.tk                            |  6
code/ksun48_2_1/C.cpp.tk                            |  15
code/LazyAnna_0_1/1.cpp.tk                          |  17
code/LazyAnna_1_1/2-1.cpp.tk                        |  16
code/LazyAnna_2_1/3.cpp.tk                          |  36
code/Merkurev_0_1/A.cpp.tk                          |  76
code/Merkurev_1_1/B.cpp.tk                          |  78
code/Merkurev_2_1/C.cpp.tk                          |  81
code/mezei_0_1/main.cpp.tk                          |  49
code/mezei_1_1/main.cpp.tk                          |  28
code/mezei_2_1/main.cpp.tk                          |  77
code/Mister_0_1/a.cpp.tk                            |  32
code/Mister_1_1/b.cpp.tk                            |  23
code/Mister_2_1/c.cpp.tk                            |  40
code/namonakiacc_0_1/cpp.cpp.tk                     |  43
code/namonakiacc_1_1/cpp.cpp.tk                     |  34
code/namonakiacc_2_1/cpp.cpp.tk                     |  56
code/Nicolas16_0_1/main.cpp.tk                      |  16
code/Nicolas16_1_1/main.cpp.tk                      |  15
code/Nicolas16_2_1/main.cpp.tk                      |  87
code/pandamonium_0_1/a.cpp.tk                       |  62
code/pandamonium_1_1/b.cpp.tk                       |  50
code/pandamonium_2_1/c.cpp.tk                       |  50
code/pflueger_0_1/A.cpp.tk                          |  21
code/pflueger_1_1/B.cpp.tk                          |  23
code/pflueger_2_1/C.cpp.tk                          |  58
code/ponyopoppo_0_1/A.cpp.tk                        |  27
code/ponyopoppo_1_1/B.cpp.tk                        |  26
code/ponyopoppo_2_1/C.cpp.tk                        |  132
code/Ragnar_0_1/A.cpp.tk                            |  32
code/Ragnar_1_1/B-2.cpp.tk                          |  23
code/Ragnar_2_1/C.cpp.tk                            |  40
code/saffah_0_1/t.cpp.tk                            |  37
code/saffah_1_1/t.cpp.tk                            |  22
code/saffah_2_1/t.cpp.tk                            |  85
code/SamanSami_0_1/A.cpp.tk                         |  9
code/SamanSami_1_1/B.cpp.tk                         |  22
code/SamanSami_2_1/C.cpp.tk                         |  11
code/Savlik_0_1/code.cpp.tk                         |  44
code/Savlik_1_1/code.cpp.tk                         |  16
code/Savlik_2_1/code.cpp.tk                         |  65
code/shik_0_1/pa.cpp.tk                             |  103
code/shik_1_1/pb.cpp.tk                             |  63
code/shik_2_1/pc.cpp.tk                             |  91
code/simsa.st_0_1/A.cpp.tk                          |  25
code/simsa.st_1_1/B.cpp.tk                          |  23
code/simsa.st_2_1/C.cpp.tk                          |  83
code/SovietUnion_0_1/A.cpp.tk                       |  79
code/SovietUnion_1_1/B.cpp.tk                       |  68
code/SovietUnion_2_1/C.cpp.tk                       |  95
code/tailed_0_1/A.cpp.tk                            |  42
code/tailed_1_1/B.cpp.tk                            |  22
code/tailed_2_1/C.cpp.tk                            |  46
code/TheNatural_0_1/A.cpp.tk                        |  161
code/TheNatural_1_1/B.cpp.tk                        |  28
code/TheNatural_2_1/C.cpp.tk                        |  24
code/TrueBamboo_0_1/test.cpp.tk                     |  63
code/TrueBamboo_1_1/test.cpp.tk                     |  57
code/TrueBamboo_2_1/test.cpp.tk                     |  72
code/tur.turczyn_0_1/A.cpp.tk                       |  19
code/tur.turczyn_1_1/B.cpp.tk                       |  20
code/tur.turczyn_2_1/C.cpp.tk                       |  27
code/Tyg3R_0_1/A.cpp.tk                             |  15
code/Tyg3R_1_1/B.cpp.tk                             |  22
code/Tyg3R_2_1/C.cpp.tk                             |  21
code/UminchuR_0_1/main.cpp.tk                       |  59
code/UminchuR_1_1/main.cpp.tk                       |  66
code/UminchuR_2_1/main.cpp.tk                       |  92
code/wo..._0_1/a.cpp.tk                             |  37
code/wo..._1_1/b.cpp.tk                             |  32
code/wo..._2_1/c.cpp.tk                             |  70
code/yswtt_0_1/A.cpp.tk                             |  40
code/yswtt_1_1/B.cpp.tk                             |  19
code/yswtt_2_1/C.cpp.tk                             |  39
code/ZhSh_0_1/a.cpp.tk                              |  14
code/ZhSh_1_1/b.cpp.tk                              |  64
code/ZhSh_2_1/c.cpp.tk                              |  65
