Begin
Comparing:  code/climpet_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  10
code/551100kk_1_1/B.cpp.tk                          |  17
code/551100kk_2_1/C.cpp.tk                          |  49
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  25
code/achan1058_2_1/source.cpp.tk                    |  46
code/alanubi_0_1/a.cpp.tk                           |  15
code/alanubi_1_1/b.cpp.tk                           |  21
code/alanubi_2_1/c.cpp.tk                           |  84
code/AntiForest_0_1/q1.cpp.tk                       |  12
code/AntiForest_1_1/q2.cpp.tk                       |  5
code/AntiForest_2_1/q3.cpp.tk                       |  67
code/apiad_0_1/A.cpp.tk                             |  15
code/apiad_1_1/B.cpp.tk                             |  19
code/apiad_2_1/C.cpp.tk                             |  92
code/azaky_0_1/A.cpp.tk                             |  16
code/azaky_1_1/B.cpp.tk                             |  19
code/azaky_2_1/C.cpp.tk                             |  106
code/azariamuh_0_1/standing.cpp.tk                  |  10
code/azariamuh_1_1/pancake.cpp.tk                   |  25
code/azariamuh_2_1/dijkstra.cpp.tk                  |  25
code/bmerry_0_1/a.cpp.tk                            |  43
code/bmerry_1_1/b.cpp.tk                            |  51
code/bmerry_2_1/c.cpp.tk                            |  122
code/climpet_0_1/A.cpp.tk                           |  1707
code/climpet_1_1/B.cpp.tk                           |  1716
code/climpet_2_1/C.cpp.tk                           |  106594
code/ctzsm_0_1/A.cpp.tk                             |  22
code/ctzsm_1_1/B.cpp.tk                             |  28
code/ctzsm_2_1/C.cpp.tk                             |  154
code/DanilC_0_1/problem.cpp.tk                      |  38
code/DanilC_1_1/problemB.cpp.tk                     |  62
code/DanilC_2_1/problemC.cpp.tk                     |  91
code/DEGwer_0_1/A.cpp.tk                            |  22
code/DEGwer_1_1/B.cpp.tk                            |  25
code/DEGwer_2_1/C.cpp.tk                            |  39
code/dmute_0_1/a.cpp.tk                             |  12
code/dmute_1_1/b.cpp.tk                             |  23
code/dmute_2_1/c2.cpp.tk                            |  56
code/fagu_0_1/A.cpp.tk                              |  10
code/fagu_1_1/B.cpp.tk                              |  10
code/fagu_2_1/C.cpp.tk                              |  115
code/FatalEagle_0_1/main.cpp.tk                     |  16
code/FatalEagle_1_1/main.cpp.tk                     |  29
code/FatalEagle_2_1/main.cpp.tk                     |  152
code/fullpower_0_1/A.cpp.tk                         |  23
code/fullpower_1_1/B.cpp.tk                         |  43
code/fullpower_2_1/C.cpp.tk                         |  81
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  20
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  29
code/ICastro_2_1/Dijkstra.cpp.tk                    |  84
code/ilackthatsuperpower_0_1/a.cpp.tk               |  83
code/ilackthatsuperpower_1_1/b.cpp.tk               |  83
code/ilackthatsuperpower_2_1/c.cpp.tk               |  108
code/iridescent_0_1/A.cpp.tk                        |  15
code/iridescent_1_1/B.cpp.tk                        |  24
code/iridescent_2_1/C.cpp.tk                        |  127
code/ishraq_0_1/main.cpp.tk                         |  7
code/ishraq_1_1/main.cpp.tk                         |  13
code/ishraq_2_1/main.cpp.tk                         |  49
code/JayXon_0_1/A.cpp.tk                            |  10
code/JayXon_1_1/B.cpp.tk                            |  26
code/JayXon_2_1/C.cpp.tk                            |  31
code/Josse_0_1/A.cpp.tk                             |  16
code/Josse_1_1/B.cpp.tk                             |  22
code/Josse_2_1/C.cpp.tk                             |  74
code/kcm1700_0_1/a.cpp.tk                           |  13
code/kcm1700_1_1/b.cpp.tk                           |  20
code/kcm1700_2_1/c.cpp.tk                           |  69
code/kevinsogo_0_1/a.cpp.tk                         |  8
code/kevinsogo_1_1/b.cpp.tk                         |  13
code/kevinsogo_2_1/c.cpp.tk                         |  58
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  22
code/LazyAnna_1_1/2-1.cpp.tk                        |  31
code/LazyAnna_2_1/3.cpp.tk                          |  48
code/Merkurev_0_1/A.cpp.tk                          |  20
code/Merkurev_1_1/B.cpp.tk                          |  32
code/Merkurev_2_1/C.cpp.tk                          |  49
code/mezei_0_1/main.cpp.tk                          |  20
code/mezei_1_1/main.cpp.tk                          |  20
code/mezei_2_1/main.cpp.tk                          |  53
code/Mister_0_1/a.cpp.tk                            |  17
code/Mister_1_1/b.cpp.tk                            |  25
code/Mister_2_1/c.cpp.tk                            |  55
code/namonakiacc_0_1/cpp.cpp.tk                     |  32
code/namonakiacc_1_1/cpp.cpp.tk                     |  35
code/namonakiacc_2_1/cpp.cpp.tk                     |  65
code/Nicolas16_0_1/main.cpp.tk                      |  6
code/Nicolas16_1_1/main.cpp.tk                      |  6
code/Nicolas16_2_1/main.cpp.tk                      |  64
code/pandamonium_0_1/a.cpp.tk                       |  13
code/pandamonium_1_1/b.cpp.tk                       |  37
code/pandamonium_2_1/c.cpp.tk                       |  30
code/pflueger_0_1/A.cpp.tk                          |  15
code/pflueger_1_1/B.cpp.tk                          |  24
code/pflueger_2_1/C.cpp.tk                          |  65
code/ponyopoppo_0_1/A.cpp.tk                        |  10
code/ponyopoppo_1_1/B.cpp.tk                        |  18
code/ponyopoppo_2_1/C.cpp.tk                        |  94
code/Ragnar_0_1/A.cpp.tk                            |  17
code/Ragnar_1_1/B-2.cpp.tk                          |  23
code/Ragnar_2_1/C.cpp.tk                            |  47
code/saffah_0_1/t.cpp.tk                            |  8
code/saffah_1_1/t.cpp.tk                            |  11
code/saffah_2_1/t.cpp.tk                            |  61
code/SamanSami_0_1/A.cpp.tk                         |  6
code/SamanSami_1_1/B.cpp.tk                         |  24
code/SamanSami_2_1/C.cpp.tk                         |  7
code/Savlik_0_1/code.cpp.tk                         |  11
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  50
code/shik_0_1/pa.cpp.tk                             |  46
code/shik_1_1/pb.cpp.tk                             |  47
code/shik_2_1/pc.cpp.tk                             |  86
code/simsa.st_0_1/A.cpp.tk                          |  9
code/simsa.st_1_1/B.cpp.tk                          |  10
code/simsa.st_2_1/C.cpp.tk                          |  53
code/SovietUnion_0_1/A.cpp.tk                       |  26
code/SovietUnion_1_1/B.cpp.tk                       |  37
code/SovietUnion_2_1/C.cpp.tk                       |  59
code/tailed_0_1/A.cpp.tk                            |  13
code/tailed_1_1/B.cpp.tk                            |  19
code/tailed_2_1/C.cpp.tk                            |  40
code/TheNatural_0_1/A.cpp.tk                        |  19
code/TheNatural_1_1/B.cpp.tk                        |  24
code/TheNatural_2_1/C.cpp.tk                        |  72
code/TrueBamboo_0_1/test.cpp.tk                     |  12
code/TrueBamboo_1_1/test.cpp.tk                     |  18
code/TrueBamboo_2_1/test.cpp.tk                     |  38
code/tur.turczyn_0_1/A.cpp.tk                       |  16
code/tur.turczyn_1_1/B.cpp.tk                       |  21
code/tur.turczyn_2_1/C.cpp.tk                       |  35
code/Tyg3R_0_1/A.cpp.tk                             |  9
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  81
code/UminchuR_0_1/main.cpp.tk                       |  22
code/UminchuR_1_1/main.cpp.tk                       |  26
code/UminchuR_2_1/main.cpp.tk                       |  65
code/wo..._0_1/a.cpp.tk                             |  20
code/wo..._1_1/b.cpp.tk                             |  24
code/wo..._2_1/c.cpp.tk                             |  76
code/yswtt_0_1/A.cpp.tk                             |  20
code/yswtt_1_1/B.cpp.tk                             |  33
code/yswtt_2_1/C.cpp.tk                             |  43
code/ZhSh_0_1/a.cpp.tk                              |  20
code/ZhSh_1_1/b.cpp.tk                              |  71
code/ZhSh_2_1/c.cpp.tk                              |  159
