Begin
Comparing:  code/ZhSh_2_1/c.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  7
code/551100kk_1_1/B.cpp.tk                          |  11
code/551100kk_2_1/C.cpp.tk                          |  91
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  19
code/achan1058_2_1/source.cpp.tk                    |  42
code/alanubi_0_1/a.cpp.tk                           |  8
code/alanubi_1_1/b.cpp.tk                           |  11
code/alanubi_2_1/c.cpp.tk                           |  52
code/AntiForest_0_1/q1.cpp.tk                       |  11
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  104
code/apiad_0_1/A.cpp.tk                             |  11
code/apiad_1_1/B.cpp.tk                             |  17
code/apiad_2_1/C.cpp.tk                             |  72
code/azaky_0_1/A.cpp.tk                             |  14
code/azaky_1_1/B.cpp.tk                             |  18
code/azaky_2_1/C.cpp.tk                             |  114
code/azariamuh_0_1/standing.cpp.tk                  |  8
code/azariamuh_1_1/pancake.cpp.tk                   |  25
code/azariamuh_2_1/dijkstra.cpp.tk                  |  48
code/bmerry_0_1/a.cpp.tk                            |  39
code/bmerry_1_1/b.cpp.tk                            |  43
code/bmerry_2_1/c.cpp.tk                            |  99
code/climpet_0_1/A.cpp.tk                           |  27
code/climpet_1_1/B.cpp.tk                           |  30
code/climpet_2_1/C.cpp.tk                           |  99
code/ctzsm_0_1/A.cpp.tk                             |  12
code/ctzsm_1_1/B.cpp.tk                             |  14
code/ctzsm_2_1/C.cpp.tk                             |  150
code/DanilC_0_1/problem.cpp.tk                      |  27
code/DanilC_1_1/problemB.cpp.tk                     |  38
code/DanilC_2_1/problemC.cpp.tk                     |  74
code/DEGwer_0_1/A.cpp.tk                            |  12
code/DEGwer_1_1/B.cpp.tk                            |  13
code/DEGwer_2_1/C.cpp.tk                            |  86
code/dmute_0_1/a.cpp.tk                             |  6
code/dmute_1_1/b.cpp.tk                             |  11
code/dmute_2_1/c2.cpp.tk                            |  48
code/fagu_0_1/A.cpp.tk                              |  5
code/fagu_1_1/B.cpp.tk                              |  5
code/fagu_2_1/C.cpp.tk                              |  139
code/FatalEagle_0_1/main.cpp.tk                     |  9
code/FatalEagle_1_1/main.cpp.tk                     |  14
code/FatalEagle_2_1/main.cpp.tk                     |  93
code/fullpower_0_1/A.cpp.tk                         |  15
code/fullpower_1_1/B.cpp.tk                         |  20
code/fullpower_2_1/C.cpp.tk                         |  68
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  10
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  13
code/ICastro_2_1/Dijkstra.cpp.tk                    |  91
code/ilackthatsuperpower_0_1/a.cpp.tk               |  66
code/ilackthatsuperpower_1_1/b.cpp.tk               |  66
code/ilackthatsuperpower_2_1/c.cpp.tk               |  96
code/iridescent_0_1/A.cpp.tk                        |  10
code/iridescent_1_1/B.cpp.tk                        |  14
code/iridescent_2_1/C.cpp.tk                        |  121
code/ishraq_0_1/main.cpp.tk                         |  7
code/ishraq_1_1/main.cpp.tk                         |  9
code/ishraq_2_1/main.cpp.tk                         |  66
code/JayXon_0_1/A.cpp.tk                            |  6
code/JayXon_1_1/B.cpp.tk                            |  14
code/JayXon_2_1/C.cpp.tk                            |  26
code/Josse_0_1/A.cpp.tk                             |  10
code/Josse_1_1/B.cpp.tk                             |  14
code/Josse_2_1/C.cpp.tk                             |  56
code/kcm1700_0_1/a.cpp.tk                           |  7
code/kcm1700_1_1/b.cpp.tk                           |  10
code/kcm1700_2_1/c.cpp.tk                           |  84
code/kevinsogo_0_1/a.cpp.tk                         |  7
code/kevinsogo_1_1/b.cpp.tk                         |  10
code/kevinsogo_2_1/c.cpp.tk                         |  46
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  11
code/LazyAnna_1_1/2-1.cpp.tk                        |  13
code/LazyAnna_2_1/3.cpp.tk                          |  81
code/Merkurev_0_1/A.cpp.tk                          |  11
code/Merkurev_1_1/B.cpp.tk                          |  20
code/Merkurev_2_1/C.cpp.tk                          |  23
code/mezei_0_1/main.cpp.tk                          |  11
code/mezei_1_1/main.cpp.tk                          |  10
code/mezei_2_1/main.cpp.tk                          |  38
code/Mister_0_1/a.cpp.tk                            |  10
code/Mister_1_1/b.cpp.tk                            |  11
code/Mister_2_1/c.cpp.tk                            |  92
code/namonakiacc_0_1/cpp.cpp.tk                     |  16
code/namonakiacc_1_1/cpp.cpp.tk                     |  21
code/namonakiacc_2_1/cpp.cpp.tk                     |  46
code/Nicolas16_0_1/main.cpp.tk                      |  4
code/Nicolas16_1_1/main.cpp.tk                      |  3
code/Nicolas16_2_1/main.cpp.tk                      |  46
code/pandamonium_0_1/a.cpp.tk                       |  7
code/pandamonium_1_1/b.cpp.tk                       |  26
code/pandamonium_2_1/c.cpp.tk                       |  17
code/pflueger_0_1/A.cpp.tk                          |  10
code/pflueger_1_1/B.cpp.tk                          |  17
code/pflueger_2_1/C.cpp.tk                          |  47
code/ponyopoppo_0_1/A.cpp.tk                        |  9
code/ponyopoppo_1_1/B.cpp.tk                        |  17
code/ponyopoppo_2_1/C.cpp.tk                        |  100
code/Ragnar_0_1/A.cpp.tk                            |  12
code/Ragnar_1_1/B-2.cpp.tk                          |  15
code/Ragnar_2_1/C.cpp.tk                            |  73
code/saffah_0_1/t.cpp.tk                            |  7
code/saffah_1_1/t.cpp.tk                            |  12
code/saffah_2_1/t.cpp.tk                            |  67
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  11
code/SamanSami_2_1/C.cpp.tk                         |  10
code/Savlik_0_1/code.cpp.tk                         |  7
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  42
code/shik_0_1/pa.cpp.tk                             |  39
code/shik_1_1/pb.cpp.tk                             |  41
code/shik_2_1/pc.cpp.tk                             |  130
code/simsa.st_0_1/A.cpp.tk                          |  8
code/simsa.st_1_1/B.cpp.tk                          |  9
code/simsa.st_2_1/C.cpp.tk                          |  53
code/SovietUnion_0_1/A.cpp.tk                       |  14
code/SovietUnion_1_1/B.cpp.tk                       |  17
code/SovietUnion_2_1/C.cpp.tk                       |  50
code/tailed_0_1/A.cpp.tk                            |  11
code/tailed_1_1/B.cpp.tk                            |  13
code/tailed_2_1/C.cpp.tk                            |  49
code/TheNatural_0_1/A.cpp.tk                        |  10
code/TheNatural_1_1/B.cpp.tk                        |  10
code/TheNatural_2_1/C.cpp.tk                        |  71
code/TrueBamboo_0_1/test.cpp.tk                     |  9
code/TrueBamboo_1_1/test.cpp.tk                     |  11
code/TrueBamboo_2_1/test.cpp.tk                     |  33
code/tur.turczyn_0_1/A.cpp.tk                       |  10
code/tur.turczyn_1_1/B.cpp.tk                       |  18
code/tur.turczyn_2_1/C.cpp.tk                       |  42
code/Tyg3R_0_1/A.cpp.tk                             |  8
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  93
code/UminchuR_0_1/main.cpp.tk                       |  16
code/UminchuR_1_1/main.cpp.tk                       |  20
code/UminchuR_2_1/main.cpp.tk                       |  45
code/wo..._0_1/a.cpp.tk                             |  11
code/wo..._1_1/b.cpp.tk                             |  12
code/wo..._2_1/c.cpp.tk                             |  107
code/yswtt_0_1/A.cpp.tk                             |  14
code/yswtt_1_1/B.cpp.tk                             |  17
code/yswtt_2_1/C.cpp.tk                             |  34
code/ZhSh_0_1/a.cpp.tk                              |  14
code/ZhSh_1_1/b.cpp.tk                              |  3191
code/ZhSh_2_1/c.cpp.tk                              |  271436
