Begin
Comparing:  code/Ragnar_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  21
code/551100kk_1_1/B.cpp.tk                          |  13
code/551100kk_2_1/C.cpp.tk                          |  24
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  125
code/achan1058_2_1/source.cpp.tk                    |  142
code/alanubi_0_1/a.cpp.tk                           |  9
code/alanubi_1_1/b.cpp.tk                           |  12
code/alanubi_2_1/c.cpp.tk                           |  71
code/AntiForest_0_1/q1.cpp.tk                       |  28
code/AntiForest_1_1/q2.cpp.tk                       |  8
code/AntiForest_2_1/q3.cpp.tk                       |  35
code/apiad_0_1/A.cpp.tk                             |  22
code/apiad_1_1/B.cpp.tk                             |  24
code/apiad_2_1/C.cpp.tk                             |  25
code/azaky_0_1/A.cpp.tk                             |  31
code/azaky_1_1/B.cpp.tk                             |  22
code/azaky_2_1/C.cpp.tk                             |  40
code/azariamuh_0_1/standing.cpp.tk                  |  15
code/azariamuh_1_1/pancake.cpp.tk                   |  19
code/azariamuh_2_1/dijkstra.cpp.tk                  |  15
code/bmerry_0_1/a.cpp.tk                            |  74
code/bmerry_1_1/b.cpp.tk                            |  64
code/bmerry_2_1/c.cpp.tk                            |  63
code/climpet_0_1/A.cpp.tk                           |  39
code/climpet_1_1/B.cpp.tk                           |  44
code/climpet_2_1/C.cpp.tk                           |  55
code/ctzsm_0_1/A.cpp.tk                             |  29
code/ctzsm_1_1/B.cpp.tk                             |  13
code/ctzsm_2_1/C.cpp.tk                             |  40
code/DanilC_0_1/problem.cpp.tk                      |  26
code/DanilC_1_1/problemB.cpp.tk                     |  34
code/DanilC_2_1/problemC.cpp.tk                     |  72
code/DEGwer_0_1/A.cpp.tk                            |  16
code/DEGwer_1_1/B.cpp.tk                            |  17
code/DEGwer_2_1/C.cpp.tk                            |  21
code/dmute_0_1/a.cpp.tk                             |  7
code/dmute_1_1/b.cpp.tk                             |  13
code/dmute_2_1/c2.cpp.tk                            |  28
code/fagu_0_1/A.cpp.tk                              |  44
code/fagu_1_1/B.cpp.tk                              |  44
code/fagu_2_1/C.cpp.tk                              |  58
code/FatalEagle_0_1/main.cpp.tk                     |  11
code/FatalEagle_1_1/main.cpp.tk                     |  15
code/FatalEagle_2_1/main.cpp.tk                     |  77
code/fullpower_0_1/A.cpp.tk                         |  13
code/fullpower_1_1/B.cpp.tk                         |  18
code/fullpower_2_1/C.cpp.tk                         |  39
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  12
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  19
code/ICastro_2_1/Dijkstra.cpp.tk                    |  59
code/ilackthatsuperpower_0_1/a.cpp.tk               |  65
code/ilackthatsuperpower_1_1/b.cpp.tk               |  65
code/ilackthatsuperpower_2_1/c.cpp.tk               |  81
code/iridescent_0_1/A.cpp.tk                        |  11
code/iridescent_1_1/B.cpp.tk                        |  16
code/iridescent_2_1/C.cpp.tk                        |  18
code/ishraq_0_1/main.cpp.tk                         |  8
code/ishraq_1_1/main.cpp.tk                         |  11
code/ishraq_2_1/main.cpp.tk                         |  40
code/JayXon_0_1/A.cpp.tk                            |  19
code/JayXon_1_1/B.cpp.tk                            |  15
code/JayXon_2_1/C.cpp.tk                            |  21
code/Josse_0_1/A.cpp.tk                             |  15
code/Josse_1_1/B.cpp.tk                             |  19
code/Josse_2_1/C.cpp.tk                             |  54
code/kcm1700_0_1/a.cpp.tk                           |  8
code/kcm1700_1_1/b.cpp.tk                           |  12
code/kcm1700_2_1/c.cpp.tk                           |  31
code/kevinsogo_0_1/a.cpp.tk                         |  23
code/kevinsogo_1_1/b.cpp.tk                         |  17
code/kevinsogo_2_1/c.cpp.tk                         |  33
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  9
code/LazyAnna_0_1/1.cpp.tk                          |  11
code/LazyAnna_1_1/2-1.cpp.tk                        |  14
code/LazyAnna_2_1/3.cpp.tk                          |  24
code/Merkurev_0_1/A.cpp.tk                          |  13
code/Merkurev_1_1/B.cpp.tk                          |  22
code/Merkurev_2_1/C.cpp.tk                          |  23
code/mezei_0_1/main.cpp.tk                          |  15
code/mezei_1_1/main.cpp.tk                          |  13
code/mezei_2_1/main.cpp.tk                          |  36
code/Mister_0_1/a.cpp.tk                            |  8
code/Mister_1_1/b.cpp.tk                            |  10
code/Mister_2_1/c.cpp.tk                            |  19
code/namonakiacc_0_1/cpp.cpp.tk                     |  71
code/namonakiacc_1_1/cpp.cpp.tk                     |  72
code/namonakiacc_2_1/cpp.cpp.tk                     |  83
code/Nicolas16_0_1/main.cpp.tk                      |  4
code/Nicolas16_1_1/main.cpp.tk                      |  4
code/Nicolas16_2_1/main.cpp.tk                      |  38
code/pandamonium_0_1/a.cpp.tk                       |  9
code/pandamonium_1_1/b.cpp.tk                       |  19
code/pandamonium_2_1/c.cpp.tk                       |  12
code/pflueger_0_1/A.cpp.tk                          |  15
code/pflueger_1_1/B.cpp.tk                          |  17
code/pflueger_2_1/C.cpp.tk                          |  37
code/ponyopoppo_0_1/A.cpp.tk                        |  29
code/ponyopoppo_1_1/B.cpp.tk                        |  28
code/ponyopoppo_2_1/C.cpp.tk                        |  73
code/Ragnar_0_1/A.cpp.tk                            |  10473
code/Ragnar_1_1/B-2.cpp.tk                          |  2672
code/Ragnar_2_1/C.cpp.tk                            |  1080
code/saffah_0_1/t.cpp.tk                            |  15
code/saffah_1_1/t.cpp.tk                            |  11
code/saffah_2_1/t.cpp.tk                            |  44
code/SamanSami_0_1/A.cpp.tk                         |  9
code/SamanSami_1_1/B.cpp.tk                         |  20
code/SamanSami_2_1/C.cpp.tk                         |  6
code/Savlik_0_1/code.cpp.tk                         |  39
code/Savlik_1_1/code.cpp.tk                         |  12
code/Savlik_2_1/code.cpp.tk                         |  39
code/shik_0_1/pa.cpp.tk                             |  58
code/shik_1_1/pb.cpp.tk                             |  46
code/shik_2_1/pc.cpp.tk                             |  61
code/simsa.st_0_1/A.cpp.tk                          |  11
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  40
code/SovietUnion_0_1/A.cpp.tk                       |  11
code/SovietUnion_1_1/B.cpp.tk                       |  13
code/SovietUnion_2_1/C.cpp.tk                       |  40
code/tailed_0_1/A.cpp.tk                            |  41
code/tailed_1_1/B.cpp.tk                            |  18
code/tailed_2_1/C.cpp.tk                            |  28
code/TheNatural_0_1/A.cpp.tk                        |  29
code/TheNatural_1_1/B.cpp.tk                        |  19
code/TheNatural_2_1/C.cpp.tk                        |  20
code/TrueBamboo_0_1/test.cpp.tk                     |  10
code/TrueBamboo_1_1/test.cpp.tk                     |  15
code/TrueBamboo_2_1/test.cpp.tk                     |  28
code/tur.turczyn_0_1/A.cpp.tk                       |  64
code/tur.turczyn_1_1/B.cpp.tk                       |  71
code/tur.turczyn_2_1/C.cpp.tk                       |  72
code/Tyg3R_0_1/A.cpp.tk                             |  14
code/Tyg3R_1_1/B.cpp.tk                             |  13
code/Tyg3R_2_1/C.cpp.tk                             |  17
code/UminchuR_0_1/main.cpp.tk                       |  64
code/UminchuR_1_1/main.cpp.tk                       |  66
code/UminchuR_2_1/main.cpp.tk                       |  83
code/wo..._0_1/a.cpp.tk                             |  10
code/wo..._1_1/b.cpp.tk                             |  13
code/wo..._2_1/c.cpp.tk                             |  34
code/yswtt_0_1/A.cpp.tk                             |  25
code/yswtt_1_1/B.cpp.tk                             |  15
code/yswtt_2_1/C.cpp.tk                             |  26
code/ZhSh_0_1/a.cpp.tk                              |  17
code/ZhSh_1_1/b.cpp.tk                              |  61
code/ZhSh_2_1/c.cpp.tk                              |  67
