Begin
Comparing:  code/JayXon_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  12
code/551100kk_1_1/B.cpp.tk                          |  30
code/551100kk_2_1/C.cpp.tk                          |  37
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  19
code/achan1058_2_1/source.cpp.tk                    |  31
code/alanubi_0_1/a.cpp.tk                           |  35
code/alanubi_1_1/b.cpp.tk                           |  62
code/alanubi_2_1/c.cpp.tk                           |  121
code/AntiForest_0_1/q1.cpp.tk                       |  11
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  43
code/apiad_0_1/A.cpp.tk                             |  11
code/apiad_1_1/B.cpp.tk                             |  16
code/apiad_2_1/C.cpp.tk                             |  27
code/azaky_0_1/A.cpp.tk                             |  11
code/azaky_1_1/B.cpp.tk                             |  16
code/azaky_2_1/C.cpp.tk                             |  42
code/azariamuh_0_1/standing.cpp.tk                  |  8
code/azariamuh_1_1/pancake.cpp.tk                   |  26
code/azariamuh_2_1/dijkstra.cpp.tk                  |  16
code/bmerry_0_1/a.cpp.tk                            |  54
code/bmerry_1_1/b.cpp.tk                            |  108
code/bmerry_2_1/c.cpp.tk                            |  73
code/climpet_0_1/A.cpp.tk                           |  30
code/climpet_1_1/B.cpp.tk                           |  43
code/climpet_2_1/C.cpp.tk                           |  61
code/ctzsm_0_1/A.cpp.tk                             |  21
code/ctzsm_1_1/B.cpp.tk                             |  37
code/ctzsm_2_1/C.cpp.tk                             |  94
code/DanilC_0_1/problem.cpp.tk                      |  37
code/DanilC_1_1/problemB.cpp.tk                     |  69
code/DanilC_2_1/problemC.cpp.tk                     |  92
code/DEGwer_0_1/A.cpp.tk                            |  47
code/DEGwer_1_1/B.cpp.tk                            |  61
code/DEGwer_2_1/C.cpp.tk                            |  47
code/dmute_0_1/a.cpp.tk                             |  30
code/dmute_1_1/b.cpp.tk                             |  49
code/dmute_2_1/c2.cpp.tk                            |  86
code/fagu_0_1/A.cpp.tk                              |  19
code/fagu_1_1/B.cpp.tk                              |  19
code/fagu_2_1/C.cpp.tk                              |  41
code/FatalEagle_0_1/main.cpp.tk                     |  29
code/FatalEagle_1_1/main.cpp.tk                     |  72
code/FatalEagle_2_1/main.cpp.tk                     |  298
code/fullpower_0_1/A.cpp.tk                         |  49
code/fullpower_1_1/B.cpp.tk                         |  93
code/fullpower_2_1/C.cpp.tk                         |  142
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  19
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  37
code/ICastro_2_1/Dijkstra.cpp.tk                    |  73
code/ilackthatsuperpower_0_1/a.cpp.tk               |  88
code/ilackthatsuperpower_1_1/b.cpp.tk               |  84
code/ilackthatsuperpower_2_1/c.cpp.tk               |  93
code/iridescent_0_1/A.cpp.tk                        |  23
code/iridescent_1_1/B.cpp.tk                        |  51
code/iridescent_2_1/C.cpp.tk                        |  52
code/ishraq_0_1/main.cpp.tk                         |  7
code/ishraq_1_1/main.cpp.tk                         |  17
code/ishraq_2_1/main.cpp.tk                         |  56
code/JayXon_0_1/A.cpp.tk                            |  35
code/JayXon_1_1/B.cpp.tk                            |  18584
code/JayXon_2_1/C.cpp.tk                            |  30
code/Josse_0_1/A.cpp.tk                             |  38
code/Josse_1_1/B.cpp.tk                             |  68
code/Josse_2_1/C.cpp.tk                             |  130
code/kcm1700_0_1/a.cpp.tk                           |  27
code/kcm1700_1_1/b.cpp.tk                           |  64
code/kcm1700_2_1/c.cpp.tk                           |  102
code/kevinsogo_0_1/a.cpp.tk                         |  9
code/kevinsogo_1_1/b.cpp.tk                         |  13
code/kevinsogo_2_1/c.cpp.tk                         |  74
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  8
code/LazyAnna_0_1/1.cpp.tk                          |  19
code/LazyAnna_1_1/2-1.cpp.tk                        |  40
code/LazyAnna_2_1/3.cpp.tk                          |  30
code/Merkurev_0_1/A.cpp.tk                          |  45
code/Merkurev_1_1/B.cpp.tk                          |  76
code/Merkurev_2_1/C.cpp.tk                          |  82
code/mezei_0_1/main.cpp.tk                          |  43
code/mezei_1_1/main.cpp.tk                          |  56
code/mezei_2_1/main.cpp.tk                          |  89
code/Mister_0_1/a.cpp.tk                            |  21
code/Mister_1_1/b.cpp.tk                            |  37
code/Mister_2_1/c.cpp.tk                            |  46
code/namonakiacc_0_1/cpp.cpp.tk                     |  14
code/namonakiacc_1_1/cpp.cpp.tk                     |  17
code/namonakiacc_2_1/cpp.cpp.tk                     |  52
code/Nicolas16_0_1/main.cpp.tk                      |  14
code/Nicolas16_1_1/main.cpp.tk                      |  14
code/Nicolas16_2_1/main.cpp.tk                      |  101
code/pandamonium_0_1/a.cpp.tk                       |  29
code/pandamonium_1_1/b.cpp.tk                       |  90
code/pandamonium_2_1/c.cpp.tk                       |  51
code/pflueger_0_1/A.cpp.tk                          |  28
code/pflueger_1_1/B.cpp.tk                          |  72
code/pflueger_2_1/C.cpp.tk                          |  129
code/ponyopoppo_0_1/A.cpp.tk                        |  11
code/ponyopoppo_1_1/B.cpp.tk                        |  19
code/ponyopoppo_2_1/C.cpp.tk                        |  70
code/Ragnar_0_1/A.cpp.tk                            |  11
code/Ragnar_1_1/B-2.cpp.tk                          |  34
code/Ragnar_2_1/C.cpp.tk                            |  33
code/saffah_0_1/t.cpp.tk                            |  6
code/saffah_1_1/t.cpp.tk                            |  10
code/saffah_2_1/t.cpp.tk                            |  46
code/SamanSami_0_1/A.cpp.tk                         |  11
code/SamanSami_1_1/B.cpp.tk                         |  66
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  17
code/Savlik_1_1/code.cpp.tk                         |  9
code/Savlik_2_1/code.cpp.tk                         |  43
code/shik_0_1/pa.cpp.tk                             |  36
code/shik_1_1/pb.cpp.tk                             |  40
code/shik_2_1/pc.cpp.tk                             |  70
code/simsa.st_0_1/A.cpp.tk                          |  8
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  45
code/SovietUnion_0_1/A.cpp.tk                       |  30
code/SovietUnion_1_1/B.cpp.tk                       |  37
code/SovietUnion_2_1/C.cpp.tk                       |  45
code/tailed_0_1/A.cpp.tk                            |  18
code/tailed_1_1/B.cpp.tk                            |  33
code/tailed_2_1/C.cpp.tk                            |  27
code/TheNatural_0_1/A.cpp.tk                        |  38
code/TheNatural_1_1/B.cpp.tk                        |  59
code/TheNatural_2_1/C.cpp.tk                        |  31
code/TrueBamboo_0_1/test.cpp.tk                     |  17
code/TrueBamboo_1_1/test.cpp.tk                     |  36
code/TrueBamboo_2_1/test.cpp.tk                     |  37
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  18
code/tur.turczyn_2_1/C.cpp.tk                       |  21
code/Tyg3R_0_1/A.cpp.tk                             |  8
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  18
code/UminchuR_0_1/main.cpp.tk                       |  13
code/UminchuR_1_1/main.cpp.tk                       |  21
code/UminchuR_2_1/main.cpp.tk                       |  45
code/wo..._0_1/a.cpp.tk                             |  49
code/wo..._1_1/b.cpp.tk                             |  66
code/wo..._2_1/c.cpp.tk                             |  111
code/yswtt_0_1/A.cpp.tk                             |  17
code/yswtt_1_1/B.cpp.tk                             |  37
code/yswtt_2_1/C.cpp.tk                             |  36
code/ZhSh_0_1/a.cpp.tk                              |  19
code/ZhSh_1_1/b.cpp.tk                              |  64
code/ZhSh_2_1/c.cpp.tk                              |  60
