Begin
Comparing:  code/ponyopoppo_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  16
code/551100kk_1_1/B.cpp.tk                          |  57
code/551100kk_2_1/C.cpp.tk                          |  45
code/achan1058_0_1/Q-A.cpp.tk                       |  17
code/achan1058_1_1/source.cpp.tk                    |  48
code/achan1058_2_1/source.cpp.tk                    |  81
code/alanubi_0_1/a.cpp.tk                           |  12
code/alanubi_1_1/b.cpp.tk                           |  23
code/alanubi_2_1/c.cpp.tk                           |  90
code/AntiForest_0_1/q1.cpp.tk                       |  23
code/AntiForest_1_1/q2.cpp.tk                       |  10
code/AntiForest_2_1/q3.cpp.tk                       |  65
code/apiad_0_1/A.cpp.tk                             |  21
code/apiad_1_1/B.cpp.tk                             |  41
code/apiad_2_1/C.cpp.tk                             |  30
code/azaky_0_1/A.cpp.tk                             |  22
code/azaky_1_1/B.cpp.tk                             |  37
code/azaky_2_1/C.cpp.tk                             |  72
code/azariamuh_0_1/standing.cpp.tk                  |  15
code/azariamuh_1_1/pancake.cpp.tk                   |  38
code/azariamuh_2_1/dijkstra.cpp.tk                  |  25
code/bmerry_0_1/a.cpp.tk                            |  55
code/bmerry_1_1/b.cpp.tk                            |  106
code/bmerry_2_1/c.cpp.tk                            |  64
code/climpet_0_1/A.cpp.tk                           |  36
code/climpet_1_1/B.cpp.tk                           |  52
code/climpet_2_1/C.cpp.tk                           |  63
code/ctzsm_0_1/A.cpp.tk                             |  13
code/ctzsm_1_1/B.cpp.tk                             |  42
code/ctzsm_2_1/C.cpp.tk                             |  81
code/DanilC_0_1/problem.cpp.tk                      |  35
code/DanilC_1_1/problemB.cpp.tk                     |  55
code/DanilC_2_1/problemC.cpp.tk                     |  162
code/DEGwer_0_1/A.cpp.tk                            |  22
code/DEGwer_1_1/B.cpp.tk                            |  31
code/DEGwer_2_1/C.cpp.tk                            |  31
code/dmute_0_1/a.cpp.tk                             |  8
code/dmute_1_1/b.cpp.tk                             |  17
code/dmute_2_1/c2.cpp.tk                            |  39
code/fagu_0_1/A.cpp.tk                              |  8
code/fagu_1_1/B.cpp.tk                              |  8
code/fagu_2_1/C.cpp.tk                              |  44
code/FatalEagle_0_1/main.cpp.tk                     |  13
code/FatalEagle_1_1/main.cpp.tk                     |  25
code/FatalEagle_2_1/main.cpp.tk                     |  164
code/fullpower_0_1/A.cpp.tk                         |  24
code/fullpower_1_1/B.cpp.tk                         |  33
code/fullpower_2_1/C.cpp.tk                         |  79
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  13
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  32
code/ICastro_2_1/Dijkstra.cpp.tk                    |  115
code/ilackthatsuperpower_0_1/a.cpp.tk               |  117
code/ilackthatsuperpower_1_1/b.cpp.tk               |  127
code/ilackthatsuperpower_2_1/c.cpp.tk               |  161
code/iridescent_0_1/A.cpp.tk                        |  14
code/iridescent_1_1/B.cpp.tk                        |  38
code/iridescent_2_1/C.cpp.tk                        |  20
code/ishraq_0_1/main.cpp.tk                         |  16
code/ishraq_1_1/main.cpp.tk                         |  25
code/ishraq_2_1/main.cpp.tk                         |  100
code/JayXon_0_1/A.cpp.tk                            |  8
code/JayXon_1_1/B.cpp.tk                            |  28
code/JayXon_2_1/C.cpp.tk                            |  48
code/Josse_0_1/A.cpp.tk                             |  24
code/Josse_1_1/B.cpp.tk                             |  40
code/Josse_2_1/C.cpp.tk                             |  116
code/kcm1700_0_1/a.cpp.tk                           |  9
code/kcm1700_1_1/b.cpp.tk                           |  32
code/kcm1700_2_1/c.cpp.tk                           |  57
code/kevinsogo_0_1/a.cpp.tk                         |  20
code/kevinsogo_1_1/b.cpp.tk                         |  33
code/kevinsogo_2_1/c.cpp.tk                         |  80
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  9
code/LazyAnna_1_1/2-1.cpp.tk                        |  16
code/LazyAnna_2_1/3.cpp.tk                          |  52
code/Merkurev_0_1/A.cpp.tk                          |  16
code/Merkurev_1_1/B.cpp.tk                          |  38
code/Merkurev_2_1/C.cpp.tk                          |  35
code/mezei_0_1/main.cpp.tk                          |  17
code/mezei_1_1/main.cpp.tk                          |  20
code/mezei_2_1/main.cpp.tk                          |  65
code/Mister_0_1/a.cpp.tk                            |  14
code/Mister_1_1/b.cpp.tk                            |  19
code/Mister_2_1/c.cpp.tk                            |  28
code/namonakiacc_0_1/cpp.cpp.tk                     |  31
code/namonakiacc_1_1/cpp.cpp.tk                     |  51
code/namonakiacc_2_1/cpp.cpp.tk                     |  66
code/Nicolas16_0_1/main.cpp.tk                      |  6
code/Nicolas16_1_1/main.cpp.tk                      |  6
code/Nicolas16_2_1/main.cpp.tk                      |  64
code/pandamonium_0_1/a.cpp.tk                       |  10
code/pandamonium_1_1/b.cpp.tk                       |  44
code/pandamonium_2_1/c.cpp.tk                       |  18
code/pflueger_0_1/A.cpp.tk                          |  19
code/pflueger_1_1/B.cpp.tk                          |  32
code/pflueger_2_1/C.cpp.tk                          |  60
code/ponyopoppo_0_1/A.cpp.tk                        |  55
code/ponyopoppo_1_1/B.cpp.tk                        |  9562
code/ponyopoppo_2_1/C.cpp.tk                        |  186
code/Ragnar_0_1/A.cpp.tk                            |  31
code/Ragnar_1_1/B-2.cpp.tk                          |  90
code/Ragnar_2_1/C.cpp.tk                            |  60
code/saffah_0_1/t.cpp.tk                            |  14
code/saffah_1_1/t.cpp.tk                            |  28
code/saffah_2_1/t.cpp.tk                            |  94
code/SamanSami_0_1/A.cpp.tk                         |  5
code/SamanSami_1_1/B.cpp.tk                         |  19
code/SamanSami_2_1/C.cpp.tk                         |  14
code/Savlik_0_1/code.cpp.tk                         |  14
code/Savlik_1_1/code.cpp.tk                         |  28
code/Savlik_2_1/code.cpp.tk                         |  86
code/shik_0_1/pa.cpp.tk                             |  106
code/shik_1_1/pb.cpp.tk                             |  126
code/shik_2_1/pc.cpp.tk                             |  155
code/simsa.st_0_1/A.cpp.tk                          |  16
code/simsa.st_1_1/B.cpp.tk                          |  33
code/simsa.st_2_1/C.cpp.tk                          |  102
code/SovietUnion_0_1/A.cpp.tk                       |  15
code/SovietUnion_1_1/B.cpp.tk                       |  26
code/SovietUnion_2_1/C.cpp.tk                       |  83
code/tailed_0_1/A.cpp.tk                            |  21
code/tailed_1_1/B.cpp.tk                            |  64
code/tailed_2_1/C.cpp.tk                            |  62
code/TheNatural_0_1/A.cpp.tk                        |  11
code/TheNatural_1_1/B.cpp.tk                        |  21
code/TheNatural_2_1/C.cpp.tk                        |  24
code/TrueBamboo_0_1/test.cpp.tk                     |  19
code/TrueBamboo_1_1/test.cpp.tk                     |  45
code/TrueBamboo_2_1/test.cpp.tk                     |  58
code/tur.turczyn_0_1/A.cpp.tk                       |  35
code/tur.turczyn_1_1/B.cpp.tk                       |  91
code/tur.turczyn_2_1/C.cpp.tk                       |  64
code/Tyg3R_0_1/A.cpp.tk                             |  20
code/Tyg3R_1_1/B.cpp.tk                             |  25
code/Tyg3R_2_1/C.cpp.tk                             |  23
code/UminchuR_0_1/main.cpp.tk                       |  30
code/UminchuR_1_1/main.cpp.tk                       |  107
code/UminchuR_2_1/main.cpp.tk                       |  69
code/wo..._0_1/a.cpp.tk                             |  13
code/wo..._1_1/b.cpp.tk                             |  18
code/wo..._2_1/c.cpp.tk                             |  59
code/yswtt_0_1/A.cpp.tk                             |  15
code/yswtt_1_1/B.cpp.tk                             |  64
code/yswtt_2_1/C.cpp.tk                             |  43
code/ZhSh_0_1/a.cpp.tk                              |  17
code/ZhSh_1_1/b.cpp.tk                              |  101
code/ZhSh_2_1/c.cpp.tk                              |  101
