Begin
Comparing:  code/azariamuh_1_1/pancake.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  19
code/551100kk_1_1/B.cpp.tk                          |  33
code/551100kk_2_1/C.cpp.tk                          |  53
code/achan1058_0_1/Q-A.cpp.tk                       |  15
code/achan1058_1_1/source.cpp.tk                    |  34
code/achan1058_2_1/source.cpp.tk                    |  57
code/alanubi_0_1/a.cpp.tk                           |  14
code/alanubi_1_1/b.cpp.tk                           |  26
code/alanubi_2_1/c.cpp.tk                           |  61
code/AntiForest_0_1/q1.cpp.tk                       |  42
code/AntiForest_1_1/q2.cpp.tk                       |  18
code/AntiForest_2_1/q3.cpp.tk                       |  88
code/apiad_0_1/A.cpp.tk                             |  22
code/apiad_1_1/B.cpp.tk                             |  38
code/apiad_2_1/C.cpp.tk                             |  62
code/azaky_0_1/A.cpp.tk                             |  32
code/azaky_1_1/B.cpp.tk                             |  46
code/azaky_2_1/C.cpp.tk                             |  79
code/azariamuh_0_1/standing.cpp.tk                  |  43
code/azariamuh_1_1/pancake.cpp.tk                   |  17358
code/azariamuh_2_1/dijkstra.cpp.tk                  |  40
code/bmerry_0_1/a.cpp.tk                            |  43
code/bmerry_1_1/b.cpp.tk                            |  49
code/bmerry_2_1/c.cpp.tk                            |  80
code/climpet_0_1/A.cpp.tk                           |  22
code/climpet_1_1/B.cpp.tk                           |  25
code/climpet_2_1/C.cpp.tk                           |  63
code/ctzsm_0_1/A.cpp.tk                             |  19
code/ctzsm_1_1/B.cpp.tk                             |  36
code/ctzsm_2_1/C.cpp.tk                             |  97
code/DanilC_0_1/problem.cpp.tk                      |  25
code/DanilC_1_1/problemB.cpp.tk                     |  45
code/DanilC_2_1/problemC.cpp.tk                     |  103
code/DEGwer_0_1/A.cpp.tk                            |  27
code/DEGwer_1_1/B.cpp.tk                            |  30
code/DEGwer_2_1/C.cpp.tk                            |  39
code/dmute_0_1/a.cpp.tk                             |  21
code/dmute_1_1/b.cpp.tk                             |  26
code/dmute_2_1/c2.cpp.tk                            |  65
code/fagu_0_1/A.cpp.tk                              |  17
code/fagu_1_1/B.cpp.tk                              |  20
code/fagu_2_1/C.cpp.tk                              |  72
code/FatalEagle_0_1/main.cpp.tk                     |  21
code/FatalEagle_1_1/main.cpp.tk                     |  26
code/FatalEagle_2_1/main.cpp.tk                     |  259
code/fullpower_0_1/A.cpp.tk                         |  29
code/fullpower_1_1/B.cpp.tk                         |  83
code/fullpower_2_1/C.cpp.tk                         |  95
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  8
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  15
code/ICastro_2_1/Dijkstra.cpp.tk                    |  111
code/ilackthatsuperpower_0_1/a.cpp.tk               |  71
code/ilackthatsuperpower_1_1/b.cpp.tk               |  69
code/ilackthatsuperpower_2_1/c.cpp.tk               |  101
code/iridescent_0_1/A.cpp.tk                        |  8
code/iridescent_1_1/B.cpp.tk                        |  17
code/iridescent_2_1/C.cpp.tk                        |  29
code/ishraq_0_1/main.cpp.tk                         |  21
code/ishraq_1_1/main.cpp.tk                         |  36
code/ishraq_2_1/main.cpp.tk                         |  103
code/JayXon_0_1/A.cpp.tk                            |  7
code/JayXon_1_1/B.cpp.tk                            |  27
code/JayXon_2_1/C.cpp.tk                            |  29
code/Josse_0_1/A.cpp.tk                             |  10
code/Josse_1_1/B.cpp.tk                             |  17
code/Josse_2_1/C.cpp.tk                             |  79
code/kcm1700_0_1/a.cpp.tk                           |  13
code/kcm1700_1_1/b.cpp.tk                           |  26
code/kcm1700_2_1/c.cpp.tk                           |  94
code/kevinsogo_0_1/a.cpp.tk                         |  22
code/kevinsogo_1_1/b.cpp.tk                         |  25
code/kevinsogo_2_1/c.cpp.tk                         |  184
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  10
code/LazyAnna_1_1/2-1.cpp.tk                        |  15
code/LazyAnna_2_1/3.cpp.tk                          |  40
code/Merkurev_0_1/A.cpp.tk                          |  23
code/Merkurev_1_1/B.cpp.tk                          |  42
code/Merkurev_2_1/C.cpp.tk                          |  59
code/mezei_0_1/main.cpp.tk                          |  26
code/mezei_1_1/main.cpp.tk                          |  22
code/mezei_2_1/main.cpp.tk                          |  60
code/Mister_0_1/a.cpp.tk                            |  14
code/Mister_1_1/b.cpp.tk                            |  24
code/Mister_2_1/c.cpp.tk                            |  45
code/namonakiacc_0_1/cpp.cpp.tk                     |  40
code/namonakiacc_1_1/cpp.cpp.tk                     |  66
code/namonakiacc_2_1/cpp.cpp.tk                     |  117
code/Nicolas16_0_1/main.cpp.tk                      |  9
code/Nicolas16_1_1/main.cpp.tk                      |  9
code/Nicolas16_2_1/main.cpp.tk                      |  66
code/pandamonium_0_1/a.cpp.tk                       |  21
code/pandamonium_1_1/b.cpp.tk                       |  69
code/pandamonium_2_1/c.cpp.tk                       |  44
code/pflueger_0_1/A.cpp.tk                          |  8
code/pflueger_1_1/B.cpp.tk                          |  15
code/pflueger_2_1/C.cpp.tk                          |  56
code/ponyopoppo_0_1/A.cpp.tk                        |  15
code/ponyopoppo_1_1/B.cpp.tk                        |  25
code/ponyopoppo_2_1/C.cpp.tk                        |  111
code/Ragnar_0_1/A.cpp.tk                            |  15
code/Ragnar_1_1/B-2.cpp.tk                          |  24
code/Ragnar_2_1/C.cpp.tk                            |  33
code/saffah_0_1/t.cpp.tk                            |  23
code/saffah_1_1/t.cpp.tk                            |  44
code/saffah_2_1/t.cpp.tk                            |  97
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  16
code/SamanSami_2_1/C.cpp.tk                         |  9
code/Savlik_0_1/code.cpp.tk                         |  10
code/Savlik_1_1/code.cpp.tk                         |  20
code/Savlik_2_1/code.cpp.tk                         |  56
code/shik_0_1/pa.cpp.tk                             |  61
code/shik_1_1/pb.cpp.tk                             |  60
code/shik_2_1/pc.cpp.tk                             |  116
code/simsa.st_0_1/A.cpp.tk                          |  29
code/simsa.st_1_1/B.cpp.tk                          |  33
code/simsa.st_2_1/C.cpp.tk                          |  82
code/SovietUnion_0_1/A.cpp.tk                       |  21
code/SovietUnion_1_1/B.cpp.tk                       |  28
code/SovietUnion_2_1/C.cpp.tk                       |  63
code/tailed_0_1/A.cpp.tk                            |  10
code/tailed_1_1/B.cpp.tk                            |  18
code/tailed_2_1/C.cpp.tk                            |  37
code/TheNatural_0_1/A.cpp.tk                        |  11
code/TheNatural_1_1/B.cpp.tk                        |  15
code/TheNatural_2_1/C.cpp.tk                        |  23
code/TrueBamboo_0_1/test.cpp.tk                     |  15
code/TrueBamboo_1_1/test.cpp.tk                     |  23
code/TrueBamboo_2_1/test.cpp.tk                     |  41
code/tur.turczyn_0_1/A.cpp.tk                       |  10
code/tur.turczyn_1_1/B.cpp.tk                       |  25
code/tur.turczyn_2_1/C.cpp.tk                       |  25
code/Tyg3R_0_1/A.cpp.tk                             |  18
code/Tyg3R_1_1/B.cpp.tk                             |  49
code/Tyg3R_2_1/C.cpp.tk                             |  48
code/UminchuR_0_1/main.cpp.tk                       |  22
code/UminchuR_1_1/main.cpp.tk                       |  38
code/UminchuR_2_1/main.cpp.tk                       |  91
code/wo..._0_1/a.cpp.tk                             |  22
code/wo..._1_1/b.cpp.tk                             |  22
code/wo..._2_1/c.cpp.tk                             |  74
code/yswtt_0_1/A.cpp.tk                             |  6
code/yswtt_1_1/B.cpp.tk                             |  18
code/yswtt_2_1/C.cpp.tk                             |  30
code/ZhSh_0_1/a.cpp.tk                              |  8
code/ZhSh_1_1/b.cpp.tk                              |  55
code/ZhSh_2_1/c.cpp.tk                              |  90
