Begin
Comparing:  code/kcm1700_1_1/b.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  27
code/551100kk_1_1/B.cpp.tk                          |  141
code/551100kk_2_1/C.cpp.tk                          |  54
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  31
code/achan1058_2_1/source.cpp.tk                    |  32
code/alanubi_0_1/a.cpp.tk                           |  142
code/alanubi_1_1/b.cpp.tk                           |  287
code/alanubi_2_1/c.cpp.tk                           |  244
code/AntiForest_0_1/q1.cpp.tk                       |  21
code/AntiForest_1_1/q2.cpp.tk                       |  12
code/AntiForest_2_1/q3.cpp.tk                       |  54
code/apiad_0_1/A.cpp.tk                             |  17
code/apiad_1_1/B.cpp.tk                             |  28
code/apiad_2_1/C.cpp.tk                             |  27
code/azaky_0_1/A.cpp.tk                             |  18
code/azaky_1_1/B.cpp.tk                             |  39
code/azaky_2_1/C.cpp.tk                             |  45
code/azariamuh_0_1/standing.cpp.tk                  |  17
code/azariamuh_1_1/pancake.cpp.tk                   |  38
code/azariamuh_2_1/dijkstra.cpp.tk                  |  22
code/bmerry_0_1/a.cpp.tk                            |  78
code/bmerry_1_1/b.cpp.tk                            |  196
code/bmerry_2_1/c.cpp.tk                            |  81
code/climpet_0_1/A.cpp.tk                           |  45
code/climpet_1_1/B.cpp.tk                           |  62
code/climpet_2_1/C.cpp.tk                           |  77
code/ctzsm_0_1/A.cpp.tk                             |  64
code/ctzsm_1_1/B.cpp.tk                             |  147
code/ctzsm_2_1/C.cpp.tk                             |  129
code/DanilC_0_1/problem.cpp.tk                      |  57
code/DanilC_1_1/problemB.cpp.tk                     |  95
code/DanilC_2_1/problemC.cpp.tk                     |  98
code/DEGwer_0_1/A.cpp.tk                            |  103
code/DEGwer_1_1/B.cpp.tk                            |  130
code/DEGwer_2_1/C.cpp.tk                            |  85
code/dmute_0_1/a.cpp.tk                             |  93
code/dmute_1_1/b.cpp.tk                             |  220
code/dmute_2_1/c2.cpp.tk                            |  172
code/fagu_0_1/A.cpp.tk                              |  61
code/fagu_1_1/B.cpp.tk                              |  63
code/fagu_2_1/C.cpp.tk                              |  76
code/FatalEagle_0_1/main.cpp.tk                     |  121
code/FatalEagle_1_1/main.cpp.tk                     |  226
code/FatalEagle_2_1/main.cpp.tk                     |  407
code/fullpower_0_1/A.cpp.tk                         |  138
code/fullpower_1_1/B.cpp.tk                         |  225
code/fullpower_2_1/C.cpp.tk                         |  250
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  32
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  62
code/ICastro_2_1/Dijkstra.cpp.tk                    |  81
code/ilackthatsuperpower_0_1/a.cpp.tk               |  115
code/ilackthatsuperpower_1_1/b.cpp.tk               |  126
code/ilackthatsuperpower_2_1/c.cpp.tk               |  101
code/iridescent_0_1/A.cpp.tk                        |  55
code/iridescent_1_1/B.cpp.tk                        |  194
code/iridescent_2_1/C.cpp.tk                        |  106
code/ishraq_0_1/main.cpp.tk                         |  26
code/ishraq_1_1/main.cpp.tk                         |  68
code/ishraq_2_1/main.cpp.tk                         |  59
code/JayXon_0_1/A.cpp.tk                            |  37
code/JayXon_1_1/B.cpp.tk                            |  96
code/JayXon_2_1/C.cpp.tk                            |  22
code/Josse_0_1/A.cpp.tk                             |  64
code/Josse_1_1/B.cpp.tk                             |  120
code/Josse_2_1/C.cpp.tk                             |  166
code/kcm1700_0_1/a.cpp.tk                           |  198
code/kcm1700_1_1/b.cpp.tk                           |  8488
code/kcm1700_2_1/c.cpp.tk                           |  172
code/kevinsogo_0_1/a.cpp.tk                         |  38
code/kevinsogo_1_1/b.cpp.tk                         |  54
code/kevinsogo_2_1/c.cpp.tk                         |  54
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  10
code/LazyAnna_0_1/1.cpp.tk                          |  34
code/LazyAnna_1_1/2-1.cpp.tk                        |  62
code/LazyAnna_2_1/3.cpp.tk                          |  35
code/Merkurev_0_1/A.cpp.tk                          |  168
code/Merkurev_1_1/B.cpp.tk                          |  210
code/Merkurev_2_1/C.cpp.tk                          |  183
code/mezei_0_1/main.cpp.tk                          |  161
code/mezei_1_1/main.cpp.tk                          |  148
code/mezei_2_1/main.cpp.tk                          |  216
code/Mister_0_1/a.cpp.tk                            |  113
code/Mister_1_1/b.cpp.tk                            |  197
code/Mister_2_1/c.cpp.tk                            |  99
code/namonakiacc_0_1/cpp.cpp.tk                     |  28
code/namonakiacc_1_1/cpp.cpp.tk                     |  35
code/namonakiacc_2_1/cpp.cpp.tk                     |  45
code/Nicolas16_0_1/main.cpp.tk                      |  75
code/Nicolas16_1_1/main.cpp.tk                      |  69
code/Nicolas16_2_1/main.cpp.tk                      |  228
code/pandamonium_0_1/a.cpp.tk                       |  111
code/pandamonium_1_1/b.cpp.tk                       |  281
code/pandamonium_2_1/c.cpp.tk                       |  121
code/pflueger_0_1/A.cpp.tk                          |  73
code/pflueger_1_1/B.cpp.tk                          |  111
code/pflueger_2_1/C.cpp.tk                          |  134
code/ponyopoppo_0_1/A.cpp.tk                        |  11
code/ponyopoppo_1_1/B.cpp.tk                        |  34
code/ponyopoppo_2_1/C.cpp.tk                        |  62
code/Ragnar_0_1/A.cpp.tk                            |  13
code/Ragnar_1_1/B-2.cpp.tk                          |  82
code/Ragnar_2_1/C.cpp.tk                            |  50
code/saffah_0_1/t.cpp.tk                            |  38
code/saffah_1_1/t.cpp.tk                            |  45
code/saffah_2_1/t.cpp.tk                            |  53
code/SamanSami_0_1/A.cpp.tk                         |  29
code/SamanSami_1_1/B.cpp.tk                         |  140
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  36
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  45
code/shik_0_1/pa.cpp.tk                             |  38
code/shik_1_1/pb.cpp.tk                             |  42
code/shik_2_1/pc.cpp.tk                             |  65
code/simsa.st_0_1/A.cpp.tk                          |  17
code/simsa.st_1_1/B.cpp.tk                          |  37
code/simsa.st_2_1/C.cpp.tk                          |  55
code/SovietUnion_0_1/A.cpp.tk                       |  78
code/SovietUnion_1_1/B.cpp.tk                       |  103
code/SovietUnion_2_1/C.cpp.tk                       |  46
code/tailed_0_1/A.cpp.tk                            |  37
code/tailed_1_1/B.cpp.tk                            |  96
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  93
code/TheNatural_1_1/B.cpp.tk                        |  362
code/TheNatural_2_1/C.cpp.tk                        |  51
code/TrueBamboo_0_1/test.cpp.tk                     |  38
code/TrueBamboo_1_1/test.cpp.tk                     |  163
code/TrueBamboo_2_1/test.cpp.tk                     |  50
code/tur.turczyn_0_1/A.cpp.tk                       |  11
code/tur.turczyn_1_1/B.cpp.tk                       |  17
code/tur.turczyn_2_1/C.cpp.tk                       |  21
code/Tyg3R_0_1/A.cpp.tk                             |  9
code/Tyg3R_1_1/B.cpp.tk                             |  26
code/Tyg3R_2_1/C.cpp.tk                             |  19
code/UminchuR_0_1/main.cpp.tk                       |  25
code/UminchuR_1_1/main.cpp.tk                       |  57
code/UminchuR_2_1/main.cpp.tk                       |  49
code/wo..._0_1/a.cpp.tk                             |  173
code/wo..._1_1/b.cpp.tk                             |  201
code/wo..._2_1/c.cpp.tk                             |  223
code/yswtt_0_1/A.cpp.tk                             |  33
code/yswtt_1_1/B.cpp.tk                             |  83
code/yswtt_2_1/C.cpp.tk                             |  54
code/ZhSh_0_1/a.cpp.tk                              |  36
code/ZhSh_1_1/b.cpp.tk                              |  95
code/ZhSh_2_1/c.cpp.tk                              |  65
