Begin
Comparing:  code/azaky_0_1/A.cpp.tk
code/00/test.cpp.tk                                 |  18
code/01/test.cpp.tk                                 |  18
code/551100kk_0_1/A.cpp.tk                          |  134
code/551100kk_1_1/B.cpp.tk                          |  36
code/551100kk_2_1/C.cpp.tk                          |  66
code/achan1058_0_1/Q-A.cpp.tk                       |  21
code/achan1058_1_1/source.cpp.tk                    |  56
code/achan1058_2_1/source.cpp.tk                    |  93
code/alanubi_0_1/a.cpp.tk                           |  31
code/alanubi_1_1/b.cpp.tk                           |  36
code/alanubi_2_1/c.cpp.tk                           |  129
code/AntiForest_0_1/q1.cpp.tk                       |  128
code/AntiForest_1_1/q2.cpp.tk                       |  35
code/AntiForest_2_1/q3.cpp.tk                       |  124
code/apiad_0_1/A.cpp.tk                             |  57
code/apiad_1_1/B.cpp.tk                             |  57
code/apiad_2_1/C.cpp.tk                             |  64
code/azaky_0_1/A.cpp.tk                             |  16203
code/azaky_1_1/B.cpp.tk                             |  1387
code/azaky_2_1/C.cpp.tk                             |  1365
code/azariamuh_0_1/standing.cpp.tk                  |  84
code/azariamuh_1_1/pancake.cpp.tk                   |  64
code/azariamuh_2_1/dijkstra.cpp.tk                  |  57
code/bmerry_0_1/a.cpp.tk                            |  154
code/bmerry_1_1/b.cpp.tk                            |  96
code/bmerry_2_1/c.cpp.tk                            |  102
code/climpet_0_1/A.cpp.tk                           |  54
code/climpet_1_1/B.cpp.tk                           |  56
code/climpet_2_1/C.cpp.tk                           |  83
code/ctzsm_0_1/A.cpp.tk                             |  71
code/ctzsm_1_1/B.cpp.tk                             |  41
code/ctzsm_2_1/C.cpp.tk                             |  128
code/DanilC_0_1/problem.cpp.tk                      |  47
code/DanilC_1_1/problemB.cpp.tk                     |  66
code/DanilC_2_1/problemC.cpp.tk                     |  149
code/DEGwer_0_1/A.cpp.tk                            |  38
code/DEGwer_1_1/B.cpp.tk                            |  36
code/DEGwer_2_1/C.cpp.tk                            |  53
code/dmute_0_1/a.cpp.tk                             |  38
code/dmute_1_1/b.cpp.tk                             |  28
code/dmute_2_1/c2.cpp.tk                            |  72
code/fagu_0_1/A.cpp.tk                              |  25
code/fagu_1_1/B.cpp.tk                              |  25
code/fagu_2_1/C.cpp.tk                              |  75
code/FatalEagle_0_1/main.cpp.tk                     |  45
code/FatalEagle_1_1/main.cpp.tk                     |  38
code/FatalEagle_2_1/main.cpp.tk                     |  187
code/fullpower_0_1/A.cpp.tk                         |  46
code/fullpower_1_1/B.cpp.tk                         |  49
code/fullpower_2_1/C.cpp.tk                         |  100
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  19
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  23
code/ICastro_2_1/Dijkstra.cpp.tk                    |  200
code/ilackthatsuperpower_0_1/a.cpp.tk               |  140
code/ilackthatsuperpower_1_1/b.cpp.tk               |  137
code/ilackthatsuperpower_2_1/c.cpp.tk               |  190
code/iridescent_0_1/A.cpp.tk                        |  12
code/iridescent_1_1/B.cpp.tk                        |  14
code/iridescent_2_1/C.cpp.tk                        |  25
code/ishraq_0_1/main.cpp.tk                         |  45
code/ishraq_1_1/main.cpp.tk                         |  34
code/ishraq_2_1/main.cpp.tk                         |  120
code/JayXon_0_1/A.cpp.tk                            |  106
code/JayXon_1_1/B.cpp.tk                            |  25
code/JayXon_2_1/C.cpp.tk                            |  51
code/Josse_0_1/A.cpp.tk                             |  20
code/Josse_1_1/B.cpp.tk                             |  20
code/Josse_2_1/C.cpp.tk                             |  116
code/kcm1700_0_1/a.cpp.tk                           |  35
code/kcm1700_1_1/b.cpp.tk                           |  26
code/kcm1700_2_1/c.cpp.tk                           |  78
code/kevinsogo_0_1/a.cpp.tk                         |  79
code/kevinsogo_1_1/b.cpp.tk                         |  28
code/kevinsogo_2_1/c.cpp.tk                         |  100
code/ksun48_0_1/A.cpp.tk                            |  7
code/ksun48_1_1/B.cpp.tk                            |  7
code/ksun48_2_1/C.cpp.tk                            |  22
code/LazyAnna_0_1/1.cpp.tk                          |  19
code/LazyAnna_1_1/2-1.cpp.tk                        |  18
code/LazyAnna_2_1/3.cpp.tk                          |  48
code/Merkurev_0_1/A.cpp.tk                          |  38
code/Merkurev_1_1/B.cpp.tk                          |  57
code/Merkurev_2_1/C.cpp.tk                          |  54
code/mezei_0_1/main.cpp.tk                          |  37
code/mezei_1_1/main.cpp.tk                          |  26
code/mezei_2_1/main.cpp.tk                          |  107
code/Mister_0_1/a.cpp.tk                            |  24
code/Mister_1_1/b.cpp.tk                            |  24
code/Mister_2_1/c.cpp.tk                            |  51
code/namonakiacc_0_1/cpp.cpp.tk                     |  79
code/namonakiacc_1_1/cpp.cpp.tk                     |  79
code/namonakiacc_2_1/cpp.cpp.tk                     |  126
code/Nicolas16_0_1/main.cpp.tk                      |  14
code/Nicolas16_1_1/main.cpp.tk                      |  13
code/Nicolas16_2_1/main.cpp.tk                      |  95
code/pandamonium_0_1/a.cpp.tk                       |  35
code/pandamonium_1_1/b.cpp.tk                       |  50
code/pandamonium_2_1/c.cpp.tk                       |  38
code/pflueger_0_1/A.cpp.tk                          |  12
code/pflueger_1_1/B.cpp.tk                          |  20
code/pflueger_2_1/C.cpp.tk                          |  70
code/ponyopoppo_0_1/A.cpp.tk                        |  35
code/ponyopoppo_1_1/B.cpp.tk                        |  33
code/ponyopoppo_2_1/C.cpp.tk                        |  197
code/Ragnar_0_1/A.cpp.tk                            |  50
code/Ragnar_1_1/B-2.cpp.tk                          |  39
code/Ragnar_2_1/C.cpp.tk                            |  70
code/saffah_0_1/t.cpp.tk                            |  52
code/saffah_1_1/t.cpp.tk                            |  60
code/saffah_2_1/t.cpp.tk                            |  180
code/SamanSami_0_1/A.cpp.tk                         |  4
code/SamanSami_1_1/B.cpp.tk                         |  16
code/SamanSami_2_1/C.cpp.tk                         |  21
code/Savlik_0_1/code.cpp.tk                         |  43
code/Savlik_1_1/code.cpp.tk                         |  22
code/Savlik_2_1/code.cpp.tk                         |  90
code/shik_0_1/pa.cpp.tk                             |  215
code/shik_1_1/pb.cpp.tk                             |  118
code/shik_2_1/pc.cpp.tk                             |  170
code/simsa.st_0_1/A.cpp.tk                          |  46
code/simsa.st_1_1/B.cpp.tk                          |  60
code/simsa.st_2_1/C.cpp.tk                          |  157
code/SovietUnion_0_1/A.cpp.tk                       |  50
code/SovietUnion_1_1/B.cpp.tk                       |  38
code/SovietUnion_2_1/C.cpp.tk                       |  109
code/tailed_0_1/A.cpp.tk                            |  43
code/tailed_1_1/B.cpp.tk                            |  18
code/tailed_2_1/C.cpp.tk                            |  53
code/TheNatural_0_1/A.cpp.tk                        |  58
code/TheNatural_1_1/B.cpp.tk                        |  16
code/TheNatural_2_1/C.cpp.tk                        |  34
code/TrueBamboo_0_1/test.cpp.tk                     |  32
code/TrueBamboo_1_1/test.cpp.tk                     |  28
code/TrueBamboo_2_1/test.cpp.tk                     |  73
code/tur.turczyn_0_1/A.cpp.tk                       |  41
code/tur.turczyn_1_1/B.cpp.tk                       |  44
code/tur.turczyn_2_1/C.cpp.tk                       |  52
code/Tyg3R_0_1/A.cpp.tk                             |  25
code/Tyg3R_1_1/B.cpp.tk                             |  45
code/Tyg3R_2_1/C.cpp.tk                             |  45
code/UminchuR_0_1/main.cpp.tk                       |  58
code/UminchuR_1_1/main.cpp.tk                       |  71
code/UminchuR_2_1/main.cpp.tk                       |  97
code/wo..._0_1/a.cpp.tk                             |  33
code/wo..._1_1/b.cpp.tk                             |  29
code/wo..._2_1/c.cpp.tk                             |  86
code/yswtt_0_1/A.cpp.tk                             |  39
code/yswtt_1_1/B.cpp.tk                             |  19
code/yswtt_2_1/C.cpp.tk                             |  45
code/ZhSh_0_1/a.cpp.tk                              |  16
code/ZhSh_1_1/b.cpp.tk                              |  89
code/ZhSh_2_1/c.cpp.tk                              |  123
