Begin
Comparing:  code/fagu_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  23
code/551100kk_1_1/B.cpp.tk                          |  54
code/551100kk_2_1/C.cpp.tk                          |  55
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  80
code/achan1058_2_1/source.cpp.tk                    |  95
code/alanubi_0_1/a.cpp.tk                           |  76
code/alanubi_1_1/b.cpp.tk                           |  155
code/alanubi_2_1/c.cpp.tk                           |  203
code/AntiForest_0_1/q1.cpp.tk                       |  35
code/AntiForest_1_1/q2.cpp.tk                       |  25
code/AntiForest_2_1/q3.cpp.tk                       |  52
code/apiad_0_1/A.cpp.tk                             |  38
code/apiad_1_1/B.cpp.tk                             |  42
code/apiad_2_1/C.cpp.tk                             |  42
code/azaky_0_1/A.cpp.tk                             |  32
code/azaky_1_1/B.cpp.tk                             |  38
code/azaky_2_1/C.cpp.tk                             |  59
code/azariamuh_0_1/standing.cpp.tk                  |  27
code/azariamuh_1_1/pancake.cpp.tk                   |  58
code/azariamuh_2_1/dijkstra.cpp.tk                  |  32
code/bmerry_0_1/a.cpp.tk                            |  82
code/bmerry_1_1/b.cpp.tk                            |  116
code/bmerry_2_1/c.cpp.tk                            |  96
code/climpet_0_1/A.cpp.tk                           |  48
code/climpet_1_1/B.cpp.tk                           |  61
code/climpet_2_1/C.cpp.tk                           |  69
code/ctzsm_0_1/A.cpp.tk                             |  39
code/ctzsm_1_1/B.cpp.tk                             |  79
code/ctzsm_2_1/C.cpp.tk                             |  87
code/DanilC_0_1/problem.cpp.tk                      |  29
code/DanilC_1_1/problemB.cpp.tk                     |  53
code/DanilC_2_1/problemC.cpp.tk                     |  79
code/DEGwer_0_1/A.cpp.tk                            |  80
code/DEGwer_1_1/B.cpp.tk                            |  96
code/DEGwer_2_1/C.cpp.tk                            |  89
code/dmute_0_1/a.cpp.tk                             |  79
code/dmute_1_1/b.cpp.tk                             |  50
code/dmute_2_1/c2.cpp.tk                            |  80
code/fagu_0_1/A.cpp.tk                              |  584
code/fagu_1_1/B.cpp.tk                              |  2134
code/fagu_2_1/C.cpp.tk                              |  470
code/FatalEagle_0_1/main.cpp.tk                     |  45
code/FatalEagle_1_1/main.cpp.tk                     |  82
code/FatalEagle_2_1/main.cpp.tk                     |  273
code/fullpower_0_1/A.cpp.tk                         |  50
code/fullpower_1_1/B.cpp.tk                         |  82
code/fullpower_2_1/C.cpp.tk                         |  94
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  18
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  32
code/ICastro_2_1/Dijkstra.cpp.tk                    |  91
code/ilackthatsuperpower_0_1/a.cpp.tk               |  89
code/ilackthatsuperpower_1_1/b.cpp.tk               |  91
code/ilackthatsuperpower_2_1/c.cpp.tk               |  103
code/iridescent_0_1/A.cpp.tk                        |  17
code/iridescent_1_1/B.cpp.tk                        |  31
code/iridescent_2_1/C.cpp.tk                        |  51
code/ishraq_0_1/main.cpp.tk                         |  13
code/ishraq_1_1/main.cpp.tk                         |  21
code/ishraq_2_1/main.cpp.tk                         |  51
code/JayXon_0_1/A.cpp.tk                            |  10
code/JayXon_1_1/B.cpp.tk                            |  54
code/JayXon_2_1/C.cpp.tk                            |  19
code/Josse_0_1/A.cpp.tk                             |  47
code/Josse_1_1/B.cpp.tk                             |  87
code/Josse_2_1/C.cpp.tk                             |  150
code/kcm1700_0_1/a.cpp.tk                           |  35
code/kcm1700_1_1/b.cpp.tk                           |  118
code/kcm1700_2_1/c.cpp.tk                           |  88
code/kevinsogo_0_1/a.cpp.tk                         |  15
code/kevinsogo_1_1/b.cpp.tk                         |  19
code/kevinsogo_2_1/c.cpp.tk                         |  42
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  18
code/LazyAnna_1_1/2-1.cpp.tk                        |  34
code/LazyAnna_2_1/3.cpp.tk                          |  25
code/Merkurev_0_1/A.cpp.tk                          |  48
code/Merkurev_1_1/B.cpp.tk                          |  145
code/Merkurev_2_1/C.cpp.tk                          |  83
code/mezei_0_1/main.cpp.tk                          |  64
code/mezei_1_1/main.cpp.tk                          |  97
code/mezei_2_1/main.cpp.tk                          |  192
code/Mister_0_1/a.cpp.tk                            |  32
code/Mister_1_1/b.cpp.tk                            |  66
code/Mister_2_1/c.cpp.tk                            |  49
code/namonakiacc_0_1/cpp.cpp.tk                     |  107
code/namonakiacc_1_1/cpp.cpp.tk                     |  123
code/namonakiacc_2_1/cpp.cpp.tk                     |  106
code/Nicolas16_0_1/main.cpp.tk                      |  35
code/Nicolas16_1_1/main.cpp.tk                      |  34
code/Nicolas16_2_1/main.cpp.tk                      |  117
code/pandamonium_0_1/a.cpp.tk                       |  79
code/pandamonium_1_1/b.cpp.tk                       |  136
code/pandamonium_2_1/c.cpp.tk                       |  64
code/pflueger_0_1/A.cpp.tk                          |  17
code/pflueger_1_1/B.cpp.tk                          |  56
code/pflueger_2_1/C.cpp.tk                          |  83
code/ponyopoppo_0_1/A.cpp.tk                        |  13
code/ponyopoppo_1_1/B.cpp.tk                        |  16
code/ponyopoppo_2_1/C.cpp.tk                        |  64
code/Ragnar_0_1/A.cpp.tk                            |  77
code/Ragnar_1_1/B-2.cpp.tk                          |  96
code/Ragnar_2_1/C.cpp.tk                            |  93
code/saffah_0_1/t.cpp.tk                            |  14
code/saffah_1_1/t.cpp.tk                            |  20
code/saffah_2_1/t.cpp.tk                            |  62
code/SamanSami_0_1/A.cpp.tk                         |  8
code/SamanSami_1_1/B.cpp.tk                         |  47
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  15
code/Savlik_1_1/code.cpp.tk                         |  11
code/Savlik_2_1/code.cpp.tk                         |  37
code/shik_0_1/pa.cpp.tk                             |  57
code/shik_1_1/pb.cpp.tk                             |  56
code/shik_2_1/pc.cpp.tk                             |  71
code/simsa.st_0_1/A.cpp.tk                          |  24
code/simsa.st_1_1/B.cpp.tk                          |  21
code/simsa.st_2_1/C.cpp.tk                          |  52
code/SovietUnion_0_1/A.cpp.tk                       |  40
code/SovietUnion_1_1/B.cpp.tk                       |  45
code/SovietUnion_2_1/C.cpp.tk                       |  45
code/tailed_0_1/A.cpp.tk                            |  16
code/tailed_1_1/B.cpp.tk                            |  22
code/tailed_2_1/C.cpp.tk                            |  29
code/TheNatural_0_1/A.cpp.tk                        |  34
code/TheNatural_1_1/B.cpp.tk                        |  65
code/TheNatural_2_1/C.cpp.tk                        |  32
code/TrueBamboo_0_1/test.cpp.tk                     |  17
code/TrueBamboo_1_1/test.cpp.tk                     |  29
code/TrueBamboo_2_1/test.cpp.tk                     |  41
code/tur.turczyn_0_1/A.cpp.tk                       |  42
code/tur.turczyn_1_1/B.cpp.tk                       |  47
code/tur.turczyn_2_1/C.cpp.tk                       |  50
code/Tyg3R_0_1/A.cpp.tk                             |  9
code/Tyg3R_1_1/B.cpp.tk                             |  22
code/Tyg3R_2_1/C.cpp.tk                             |  16
code/UminchuR_0_1/main.cpp.tk                       |  56
code/UminchuR_1_1/main.cpp.tk                       |  64
code/UminchuR_2_1/main.cpp.tk                       |  79
code/wo..._0_1/a.cpp.tk                             |  96
code/wo..._1_1/b.cpp.tk                             |  107
code/wo..._2_1/c.cpp.tk                             |  114
code/yswtt_0_1/A.cpp.tk                             |  13
code/yswtt_1_1/B.cpp.tk                             |  34
code/yswtt_2_1/C.cpp.tk                             |  32
code/ZhSh_0_1/a.cpp.tk                              |  14
code/ZhSh_1_1/b.cpp.tk                              |  64
code/ZhSh_2_1/c.cpp.tk                              |  67
