Begin
Comparing:  code/Merkurev_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  32
code/551100kk_1_1/B.cpp.tk                          |  58
code/551100kk_2_1/C.cpp.tk                          |  66
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  21
code/achan1058_2_1/source.cpp.tk                    |  47
code/alanubi_0_1/a.cpp.tk                           |  61
code/alanubi_1_1/b.cpp.tk                           |  117
code/alanubi_2_1/c.cpp.tk                           |  176
code/AntiForest_0_1/q1.cpp.tk                       |  32
code/AntiForest_1_1/q2.cpp.tk                       |  20
code/AntiForest_2_1/q3.cpp.tk                       |  70
code/apiad_0_1/A.cpp.tk                             |  16
code/apiad_1_1/B.cpp.tk                             |  28
code/apiad_2_1/C.cpp.tk                             |  28
code/azaky_0_1/A.cpp.tk                             |  23
code/azaky_1_1/B.cpp.tk                             |  32
code/azaky_2_1/C.cpp.tk                             |  56
code/azariamuh_0_1/standing.cpp.tk                  |  17
code/azariamuh_1_1/pancake.cpp.tk                   |  33
code/azariamuh_2_1/dijkstra.cpp.tk                  |  28
code/bmerry_0_1/a.cpp.tk                            |  62
code/bmerry_1_1/b.cpp.tk                            |  99
code/bmerry_2_1/c.cpp.tk                            |  73
code/climpet_0_1/A.cpp.tk                           |  37
code/climpet_1_1/B.cpp.tk                           |  49
code/climpet_2_1/C.cpp.tk                           |  66
code/ctzsm_0_1/A.cpp.tk                             |  75
code/ctzsm_1_1/B.cpp.tk                             |  116
code/ctzsm_2_1/C.cpp.tk                             |  120
code/DanilC_0_1/problem.cpp.tk                      |  41
code/DanilC_1_1/problemB.cpp.tk                     |  72
code/DanilC_2_1/problemC.cpp.tk                     |  111
code/DEGwer_0_1/A.cpp.tk                            |  66
code/DEGwer_1_1/B.cpp.tk                            |  84
code/DEGwer_2_1/C.cpp.tk                            |  71
code/dmute_0_1/a.cpp.tk                             |  55
code/dmute_1_1/b.cpp.tk                             |  90
code/dmute_2_1/c2.cpp.tk                            |  123
code/fagu_0_1/A.cpp.tk                              |  42
code/fagu_1_1/B.cpp.tk                              |  42
code/fagu_2_1/C.cpp.tk                              |  70
code/FatalEagle_0_1/main.cpp.tk                     |  246
code/FatalEagle_1_1/main.cpp.tk                     |  306
code/FatalEagle_2_1/main.cpp.tk                     |  330
code/fullpower_0_1/A.cpp.tk                         |  97
code/fullpower_1_1/B.cpp.tk                         |  135
code/fullpower_2_1/C.cpp.tk                         |  167
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  21
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  42
code/ICastro_2_1/Dijkstra.cpp.tk                    |  107
code/ilackthatsuperpower_0_1/a.cpp.tk               |  101
code/ilackthatsuperpower_1_1/b.cpp.tk               |  114
code/ilackthatsuperpower_2_1/c.cpp.tk               |  120
code/iridescent_0_1/A.cpp.tk                        |  24
code/iridescent_1_1/B.cpp.tk                        |  48
code/iridescent_2_1/C.cpp.tk                        |  55
code/ishraq_0_1/main.cpp.tk                         |  14
code/ishraq_1_1/main.cpp.tk                         |  29
code/ishraq_2_1/main.cpp.tk                         |  69
code/JayXon_0_1/A.cpp.tk                            |  18
code/JayXon_1_1/B.cpp.tk                            |  64
code/JayXon_2_1/C.cpp.tk                            |  32
code/Josse_0_1/A.cpp.tk                             |  50
code/Josse_1_1/B.cpp.tk                             |  89
code/Josse_2_1/C.cpp.tk                             |  148
code/kcm1700_0_1/a.cpp.tk                           |  54
code/kcm1700_1_1/b.cpp.tk                           |  115
code/kcm1700_2_1/c.cpp.tk                           |  106
code/kevinsogo_0_1/a.cpp.tk                         |  17
code/kevinsogo_1_1/b.cpp.tk                         |  25
code/kevinsogo_2_1/c.cpp.tk                         |  54
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  15
code/LazyAnna_0_1/1.cpp.tk                          |  19
code/LazyAnna_1_1/2-1.cpp.tk                        |  40
code/LazyAnna_2_1/3.cpp.tk                          |  33
code/Merkurev_0_1/A.cpp.tk                          |  195
code/Merkurev_1_1/B.cpp.tk                          |  27957
code/Merkurev_2_1/C.cpp.tk                          |  426
code/mezei_0_1/main.cpp.tk                          |  77
code/mezei_1_1/main.cpp.tk                          |  92
code/mezei_2_1/main.cpp.tk                          |  159
code/Mister_0_1/a.cpp.tk                            |  37
code/Mister_1_1/b.cpp.tk                            |  72
code/Mister_2_1/c.cpp.tk                            |  63
code/namonakiacc_0_1/cpp.cpp.tk                     |  24
code/namonakiacc_1_1/cpp.cpp.tk                     |  38
code/namonakiacc_2_1/cpp.cpp.tk                     |  44
code/Nicolas16_0_1/main.cpp.tk                      |  40
code/Nicolas16_1_1/main.cpp.tk                      |  37
code/Nicolas16_2_1/main.cpp.tk                      |  141
code/pandamonium_0_1/a.cpp.tk                       |  58
code/pandamonium_1_1/b.cpp.tk                       |  133
code/pandamonium_2_1/c.cpp.tk                       |  80
code/pflueger_0_1/A.cpp.tk                          |  31
code/pflueger_1_1/B.cpp.tk                          |  81
code/pflueger_2_1/C.cpp.tk                          |  103
code/ponyopoppo_0_1/A.cpp.tk                        |  10
code/ponyopoppo_1_1/B.cpp.tk                        |  21
code/ponyopoppo_2_1/C.cpp.tk                        |  103
code/Ragnar_0_1/A.cpp.tk                            |  13
code/Ragnar_1_1/B-2.cpp.tk                          |  35
code/Ragnar_2_1/C.cpp.tk                            |  41
code/saffah_0_1/t.cpp.tk                            |  15
code/saffah_1_1/t.cpp.tk                            |  21
code/saffah_2_1/t.cpp.tk                            |  71
code/SamanSami_0_1/A.cpp.tk                         |  12
code/SamanSami_1_1/B.cpp.tk                         |  71
code/SamanSami_2_1/C.cpp.tk                         |  9
code/Savlik_0_1/code.cpp.tk                         |  21
code/Savlik_1_1/code.cpp.tk                         |  23
code/Savlik_2_1/code.cpp.tk                         |  55
code/shik_0_1/pa.cpp.tk                             |  53
code/shik_1_1/pb.cpp.tk                             |  65
code/shik_2_1/pc.cpp.tk                             |  81
code/simsa.st_0_1/A.cpp.tk                          |  17
code/simsa.st_1_1/B.cpp.tk                          |  25
code/simsa.st_2_1/C.cpp.tk                          |  71
code/SovietUnion_0_1/A.cpp.tk                       |  55
code/SovietUnion_1_1/B.cpp.tk                       |  68
code/SovietUnion_2_1/C.cpp.tk                       |  67
code/tailed_0_1/A.cpp.tk                            |  20
code/tailed_1_1/B.cpp.tk                            |  33
code/tailed_2_1/C.cpp.tk                            |  33
code/TheNatural_0_1/A.cpp.tk                        |  42
code/TheNatural_1_1/B.cpp.tk                        |  76
code/TheNatural_2_1/C.cpp.tk                        |  36
code/TrueBamboo_0_1/test.cpp.tk                     |  29
code/TrueBamboo_1_1/test.cpp.tk                     |  46
code/TrueBamboo_2_1/test.cpp.tk                     |  59
code/tur.turczyn_0_1/A.cpp.tk                       |  10
code/tur.turczyn_1_1/B.cpp.tk                       |  20
code/tur.turczyn_2_1/C.cpp.tk                       |  25
code/Tyg3R_0_1/A.cpp.tk                             |  12
code/Tyg3R_1_1/B.cpp.tk                             |  18
code/Tyg3R_2_1/C.cpp.tk                             |  17
code/UminchuR_0_1/main.cpp.tk                       |  112
code/UminchuR_1_1/main.cpp.tk                       |  137
code/UminchuR_2_1/main.cpp.tk                       |  76
code/wo..._0_1/a.cpp.tk                             |  73
code/wo..._1_1/b.cpp.tk                             |  130
code/wo..._2_1/c.cpp.tk                             |  149
code/yswtt_0_1/A.cpp.tk                             |  18
code/yswtt_1_1/B.cpp.tk                             |  38
code/yswtt_2_1/C.cpp.tk                             |  43
code/ZhSh_0_1/a.cpp.tk                              |  20
code/ZhSh_1_1/b.cpp.tk                              |  90
code/ZhSh_2_1/c.cpp.tk                              |  69
