Begin
Comparing:  code/pandamonium_0_1/a.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  66
code/551100kk_1_1/B.cpp.tk                          |  49
code/551100kk_2_1/C.cpp.tk                          |  48
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  15
code/achan1058_2_1/source.cpp.tk                    |  36
code/alanubi_0_1/a.cpp.tk                           |  138
code/alanubi_1_1/b.cpp.tk                           |  62
code/alanubi_2_1/c.cpp.tk                           |  118
code/AntiForest_0_1/q1.cpp.tk                       |  30
code/AntiForest_1_1/q2.cpp.tk                       |  14
code/AntiForest_2_1/q3.cpp.tk                       |  48
code/apiad_0_1/A.cpp.tk                             |  57
code/apiad_1_1/B.cpp.tk                             |  22
code/apiad_2_1/C.cpp.tk                             |  31
code/azaky_0_1/A.cpp.tk                             |  36
code/azaky_1_1/B.cpp.tk                             |  26
code/azaky_2_1/C.cpp.tk                             |  48
code/azariamuh_0_1/standing.cpp.tk                  |  25
code/azariamuh_1_1/pancake.cpp.tk                   |  42
code/azariamuh_2_1/dijkstra.cpp.tk                  |  24
code/bmerry_0_1/a.cpp.tk                            |  75
code/bmerry_1_1/b.cpp.tk                            |  60
code/bmerry_2_1/c.cpp.tk                            |  56
code/climpet_0_1/A.cpp.tk                           |  46
code/climpet_1_1/B.cpp.tk                           |  42
code/climpet_2_1/C.cpp.tk                           |  68
code/ctzsm_0_1/A.cpp.tk                             |  139
code/ctzsm_1_1/B.cpp.tk                             |  75
code/ctzsm_2_1/C.cpp.tk                             |  110
code/DanilC_0_1/problem.cpp.tk                      |  56
code/DanilC_1_1/problemB.cpp.tk                     |  63
code/DanilC_2_1/problemC.cpp.tk                     |  88
code/DEGwer_0_1/A.cpp.tk                            |  81
code/DEGwer_1_1/B.cpp.tk                            |  63
code/DEGwer_2_1/C.cpp.tk                            |  48
code/dmute_0_1/a.cpp.tk                             |  1085
code/dmute_1_1/b.cpp.tk                             |  191
code/dmute_2_1/c2.cpp.tk                            |  187
code/fagu_0_1/A.cpp.tk                              |  76
code/fagu_1_1/B.cpp.tk                              |  57
code/fagu_2_1/C.cpp.tk                              |  53
code/FatalEagle_0_1/main.cpp.tk                     |  172
code/FatalEagle_1_1/main.cpp.tk                     |  170
code/FatalEagle_2_1/main.cpp.tk                     |  244
code/fullpower_0_1/A.cpp.tk                         |  174
code/fullpower_1_1/B.cpp.tk                         |  269
code/fullpower_2_1/C.cpp.tk                         |  278
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  29
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  35
code/ICastro_2_1/Dijkstra.cpp.tk                    |  87
code/ilackthatsuperpower_0_1/a.cpp.tk               |  105
code/ilackthatsuperpower_1_1/b.cpp.tk               |  103
code/ilackthatsuperpower_2_1/c.cpp.tk               |  87
code/iridescent_0_1/A.cpp.tk                        |  60
code/iridescent_1_1/B.cpp.tk                        |  112
code/iridescent_2_1/C.cpp.tk                        |  70
code/ishraq_0_1/main.cpp.tk                         |  36
code/ishraq_1_1/main.cpp.tk                         |  28
code/ishraq_2_1/main.cpp.tk                         |  47
code/JayXon_0_1/A.cpp.tk                            |  42
code/JayXon_1_1/B.cpp.tk                            |  59
code/JayXon_2_1/C.cpp.tk                            |  28
code/Josse_0_1/A.cpp.tk                             |  27
code/Josse_1_1/B.cpp.tk                             |  44
code/Josse_2_1/C.cpp.tk                             |  86
code/kcm1700_0_1/a.cpp.tk                           |  116
code/kcm1700_1_1/b.cpp.tk                           |  150
code/kcm1700_2_1/c.cpp.tk                           |  122
code/kevinsogo_0_1/a.cpp.tk                         |  18
code/kevinsogo_1_1/b.cpp.tk                         |  21
code/kevinsogo_2_1/c.cpp.tk                         |  49
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  34
code/LazyAnna_1_1/2-1.cpp.tk                        |  42
code/LazyAnna_2_1/3.cpp.tk                          |  33
code/Merkurev_0_1/A.cpp.tk                          |  152
code/Merkurev_1_1/B.cpp.tk                          |  144
code/Merkurev_2_1/C.cpp.tk                          |  151
code/mezei_0_1/main.cpp.tk                          |  180
code/mezei_1_1/main.cpp.tk                          |  97
code/mezei_2_1/main.cpp.tk                          |  147
code/Mister_0_1/a.cpp.tk                            |  66
code/Mister_1_1/b.cpp.tk                            |  65
code/Mister_2_1/c.cpp.tk                            |  75
code/namonakiacc_0_1/cpp.cpp.tk                     |  59
code/namonakiacc_1_1/cpp.cpp.tk                     |  38
code/namonakiacc_2_1/cpp.cpp.tk                     |  48
code/Nicolas16_0_1/main.cpp.tk                      |  70
code/Nicolas16_1_1/main.cpp.tk                      |  69
code/Nicolas16_2_1/main.cpp.tk                      |  214
code/pandamonium_0_1/a.cpp.tk                       |  4501
code/pandamonium_1_1/b.cpp.tk                       |  122
code/pandamonium_2_1/c.cpp.tk                       |  161
code/pflueger_0_1/A.cpp.tk                          |  82
code/pflueger_1_1/B.cpp.tk                          |  69
code/pflueger_2_1/C.cpp.tk                          |  101
code/ponyopoppo_0_1/A.cpp.tk                        |  9
code/ponyopoppo_1_1/B.cpp.tk                        |  13
code/ponyopoppo_2_1/C.cpp.tk                        |  76
code/Ragnar_0_1/A.cpp.tk                            |  14
code/Ragnar_1_1/B-2.cpp.tk                          |  20
code/Ragnar_2_1/C.cpp.tk                            |  56
code/saffah_0_1/t.cpp.tk                            |  20
code/saffah_1_1/t.cpp.tk                            |  20
code/saffah_2_1/t.cpp.tk                            |  64
code/SamanSami_0_1/A.cpp.tk                         |  31
code/SamanSami_1_1/B.cpp.tk                         |  70
code/SamanSami_2_1/C.cpp.tk                         |  7
code/Savlik_0_1/code.cpp.tk                         |  50
code/Savlik_1_1/code.cpp.tk                         |  9
code/Savlik_2_1/code.cpp.tk                         |  44
code/shik_0_1/pa.cpp.tk                             |  44
code/shik_1_1/pb.cpp.tk                             |  41
code/shik_2_1/pc.cpp.tk                             |  68
code/simsa.st_0_1/A.cpp.tk                          |  24
code/simsa.st_1_1/B.cpp.tk                          |  18
code/simsa.st_2_1/C.cpp.tk                          |  54
code/SovietUnion_0_1/A.cpp.tk                       |  140
code/SovietUnion_1_1/B.cpp.tk                       |  112
code/SovietUnion_2_1/C.cpp.tk                       |  56
code/tailed_0_1/A.cpp.tk                            |  51
code/tailed_1_1/B.cpp.tk                            |  52
code/tailed_2_1/C.cpp.tk                            |  40
code/TheNatural_0_1/A.cpp.tk                        |  111
code/TheNatural_1_1/B.cpp.tk                        |  103
code/TheNatural_2_1/C.cpp.tk                        |  49
code/TrueBamboo_0_1/test.cpp.tk                     |  70
code/TrueBamboo_1_1/test.cpp.tk                     |  37
code/TrueBamboo_2_1/test.cpp.tk                     |  52
code/tur.turczyn_0_1/A.cpp.tk                       |  11
code/tur.turczyn_1_1/B.cpp.tk                       |  13
code/tur.turczyn_2_1/C.cpp.tk                       |  20
code/Tyg3R_0_1/A.cpp.tk                             |  21
code/Tyg3R_1_1/B.cpp.tk                             |  17
code/Tyg3R_2_1/C.cpp.tk                             |  20
code/UminchuR_0_1/main.cpp.tk                       |  27
code/UminchuR_1_1/main.cpp.tk                       |  27
code/UminchuR_2_1/main.cpp.tk                       |  49
code/wo..._0_1/a.cpp.tk                             |  89
code/wo..._1_1/b.cpp.tk                             |  145
code/wo..._2_1/c.cpp.tk                             |  176
code/yswtt_0_1/A.cpp.tk                             |  49
code/yswtt_1_1/B.cpp.tk                             |  35
code/yswtt_2_1/C.cpp.tk                             |  49
code/ZhSh_0_1/a.cpp.tk                              |  36
code/ZhSh_1_1/b.cpp.tk                              |  75
code/ZhSh_2_1/c.cpp.tk                              |  64
