Begin
Comparing:  code/Mister_1_1/b.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  19
code/551100kk_1_1/B.cpp.tk                          |  48
code/551100kk_2_1/C.cpp.tk                          |  39
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  18
code/achan1058_2_1/source.cpp.tk                    |  34
code/alanubi_0_1/a.cpp.tk                           |  78
code/alanubi_1_1/b.cpp.tk                           |  132
code/alanubi_2_1/c.cpp.tk                           |  164
code/AntiForest_0_1/q1.cpp.tk                       |  22
code/AntiForest_1_1/q2.cpp.tk                       |  12
code/AntiForest_2_1/q3.cpp.tk                       |  53
code/apiad_0_1/A.cpp.tk                             |  18
code/apiad_1_1/B.cpp.tk                             |  27
code/apiad_2_1/C.cpp.tk                             |  26
code/azaky_0_1/A.cpp.tk                             |  18
code/azaky_1_1/B.cpp.tk                             |  30
code/azaky_2_1/C.cpp.tk                             |  47
code/azariamuh_0_1/standing.cpp.tk                  |  17
code/azariamuh_1_1/pancake.cpp.tk                   |  35
code/azariamuh_2_1/dijkstra.cpp.tk                  |  22
code/bmerry_0_1/a.cpp.tk                            |  50
code/bmerry_1_1/b.cpp.tk                            |  89
code/bmerry_2_1/c.cpp.tk                            |  64
code/climpet_0_1/A.cpp.tk                           |  58
code/climpet_1_1/B.cpp.tk                           |  95
code/climpet_2_1/C.cpp.tk                           |  98
code/ctzsm_0_1/A.cpp.tk                             |  93
code/ctzsm_1_1/B.cpp.tk                             |  233
code/ctzsm_2_1/C.cpp.tk                             |  178
code/DanilC_0_1/problem.cpp.tk                      |  72
code/DanilC_1_1/problemB.cpp.tk                     |  137
code/DanilC_2_1/problemC.cpp.tk                     |  143
code/DEGwer_0_1/A.cpp.tk                            |  68
code/DEGwer_1_1/B.cpp.tk                            |  80
code/DEGwer_2_1/C.cpp.tk                            |  60
code/dmute_0_1/a.cpp.tk                             |  52
code/dmute_1_1/b.cpp.tk                             |  143
code/dmute_2_1/c2.cpp.tk                            |  110
code/fagu_0_1/A.cpp.tk                              |  36
code/fagu_1_1/B.cpp.tk                              |  38
code/fagu_2_1/C.cpp.tk                              |  53
code/FatalEagle_0_1/main.cpp.tk                     |  70
code/FatalEagle_1_1/main.cpp.tk                     |  160
code/FatalEagle_2_1/main.cpp.tk                     |  286
code/fullpower_0_1/A.cpp.tk                         |  90
code/fullpower_1_1/B.cpp.tk                         |  137
code/fullpower_2_1/C.cpp.tk                         |  171
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  49
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  100
code/ICastro_2_1/Dijkstra.cpp.tk                    |  97
code/ilackthatsuperpower_0_1/a.cpp.tk               |  98
code/ilackthatsuperpower_1_1/b.cpp.tk               |  121
code/ilackthatsuperpower_2_1/c.cpp.tk               |  112
code/iridescent_0_1/A.cpp.tk                        |  28
code/iridescent_1_1/B.cpp.tk                        |  70
code/iridescent_2_1/C.cpp.tk                        |  60
code/ishraq_0_1/main.cpp.tk                         |  26
code/ishraq_1_1/main.cpp.tk                         |  50
code/ishraq_2_1/main.cpp.tk                         |  65
code/JayXon_0_1/A.cpp.tk                            |  20
code/JayXon_1_1/B.cpp.tk                            |  59
code/JayXon_2_1/C.cpp.tk                            |  26
code/Josse_0_1/A.cpp.tk                             |  35
code/Josse_1_1/B.cpp.tk                             |  80
code/Josse_2_1/C.cpp.tk                             |  112
code/kcm1700_0_1/a.cpp.tk                           |  117
code/kcm1700_1_1/b.cpp.tk                           |  214
code/kcm1700_2_1/c.cpp.tk                           |  141
code/kevinsogo_0_1/a.cpp.tk                         |  40
code/kevinsogo_1_1/b.cpp.tk                         |  52
code/kevinsogo_2_1/c.cpp.tk                         |  56
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  10
code/LazyAnna_0_1/1.cpp.tk                          |  47
code/LazyAnna_1_1/2-1.cpp.tk                        |  88
code/LazyAnna_2_1/3.cpp.tk                          |  44
code/Merkurev_0_1/A.cpp.tk                          |  101
code/Merkurev_1_1/B.cpp.tk                          |  142
code/Merkurev_2_1/C.cpp.tk                          |  122
code/mezei_0_1/main.cpp.tk                          |  84
code/mezei_1_1/main.cpp.tk                          |  84
code/mezei_2_1/main.cpp.tk                          |  127
code/Mister_0_1/a.cpp.tk                            |  218
code/Mister_1_1/b.cpp.tk                            |  7114
code/Mister_2_1/c.cpp.tk                            |  135
code/namonakiacc_0_1/cpp.cpp.tk                     |  26
code/namonakiacc_1_1/cpp.cpp.tk                     |  58
code/namonakiacc_2_1/cpp.cpp.tk                     |  46
code/Nicolas16_0_1/main.cpp.tk                      |  48
code/Nicolas16_1_1/main.cpp.tk                      |  42
code/Nicolas16_2_1/main.cpp.tk                      |  136
code/pandamonium_0_1/a.cpp.tk                       |  52
code/pandamonium_1_1/b.cpp.tk                       |  136
code/pandamonium_2_1/c.cpp.tk                       |  77
code/pflueger_0_1/A.cpp.tk                          |  32
code/pflueger_1_1/B.cpp.tk                          |  69
code/pflueger_2_1/C.cpp.tk                          |  86
code/ponyopoppo_0_1/A.cpp.tk                        |  10
code/ponyopoppo_1_1/B.cpp.tk                        |  20
code/ponyopoppo_2_1/C.cpp.tk                        |  72
code/Ragnar_0_1/A.cpp.tk                            |  11
code/Ragnar_1_1/B-2.cpp.tk                          |  27
code/Ragnar_2_1/C.cpp.tk                            |  36
code/saffah_0_1/t.cpp.tk                            |  39
code/saffah_1_1/t.cpp.tk                            |  43
code/saffah_2_1/t.cpp.tk                            |  56
code/SamanSami_0_1/A.cpp.tk                         |  13
code/SamanSami_1_1/B.cpp.tk                         |  60
code/SamanSami_2_1/C.cpp.tk                         |  6
code/Savlik_0_1/code.cpp.tk                         |  18
code/Savlik_1_1/code.cpp.tk                         |  24
code/Savlik_2_1/code.cpp.tk                         |  46
code/shik_0_1/pa.cpp.tk                             |  38
code/shik_1_1/pb.cpp.tk                             |  59
code/shik_2_1/pc.cpp.tk                             |  67
code/simsa.st_0_1/A.cpp.tk                          |  16
code/simsa.st_1_1/B.cpp.tk                          |  37
code/simsa.st_2_1/C.cpp.tk                          |  59
code/SovietUnion_0_1/A.cpp.tk                       |  106
code/SovietUnion_1_1/B.cpp.tk                       |  132
code/SovietUnion_2_1/C.cpp.tk                       |  62
code/tailed_0_1/A.cpp.tk                            |  21
code/tailed_1_1/B.cpp.tk                            |  37
code/tailed_2_1/C.cpp.tk                            |  26
code/TheNatural_0_1/A.cpp.tk                        |  44
code/TheNatural_1_1/B.cpp.tk                        |  58
code/TheNatural_2_1/C.cpp.tk                        |  29
code/TrueBamboo_0_1/test.cpp.tk                     |  18
code/TrueBamboo_1_1/test.cpp.tk                     |  28
code/TrueBamboo_2_1/test.cpp.tk                     |  36
code/tur.turczyn_0_1/A.cpp.tk                       |  11
code/tur.turczyn_1_1/B.cpp.tk                       |  18
code/tur.turczyn_2_1/C.cpp.tk                       |  21
code/Tyg3R_0_1/A.cpp.tk                             |  9
code/Tyg3R_1_1/B.cpp.tk                             |  21
code/Tyg3R_2_1/C.cpp.tk                             |  18
code/UminchuR_0_1/main.cpp.tk                       |  23
code/UminchuR_1_1/main.cpp.tk                       |  40
code/UminchuR_2_1/main.cpp.tk                       |  50
code/wo..._0_1/a.cpp.tk                             |  105
code/wo..._1_1/b.cpp.tk                             |  123
code/wo..._2_1/c.cpp.tk                             |  153
code/yswtt_0_1/A.cpp.tk                             |  50
code/yswtt_1_1/B.cpp.tk                             |  142
code/yswtt_2_1/C.cpp.tk                             |  62
code/ZhSh_0_1/a.cpp.tk                              |  57
code/ZhSh_1_1/b.cpp.tk                              |  134
code/ZhSh_2_1/c.cpp.tk                              |  79
