Begin
Comparing:  code/ilackthatsuperpower_0_1/a.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  14
code/551100kk_1_1/B.cpp.tk                          |  22
code/551100kk_2_1/C.cpp.tk                          |  39
code/achan1058_0_1/Q-A.cpp.tk                       |  10
code/achan1058_1_1/source.cpp.tk                    |  23
code/achan1058_2_1/source.cpp.tk                    |  49
code/alanubi_0_1/a.cpp.tk                           |  18
code/alanubi_1_1/b.cpp.tk                           |  25
code/alanubi_2_1/c.cpp.tk                           |  85
code/AntiForest_0_1/q1.cpp.tk                       |  17
code/AntiForest_1_1/q2.cpp.tk                       |  7
code/AntiForest_2_1/q3.cpp.tk                       |  50
code/apiad_0_1/A.cpp.tk                             |  13
code/apiad_1_1/B.cpp.tk                             |  19
code/apiad_2_1/C.cpp.tk                             |  24
code/azaky_0_1/A.cpp.tk                             |  21
code/azaky_1_1/B.cpp.tk                             |  23
code/azaky_2_1/C.cpp.tk                             |  58
code/azariamuh_0_1/standing.cpp.tk                  |  12
code/azariamuh_1_1/pancake.cpp.tk                   |  23
code/azariamuh_2_1/dijkstra.cpp.tk                  |  19
code/bmerry_0_1/a.cpp.tk                            |  53
code/bmerry_1_1/b.cpp.tk                            |  63
code/bmerry_2_1/c.cpp.tk                            |  59
code/climpet_0_1/A.cpp.tk                           |  41
code/climpet_1_1/B.cpp.tk                           |  45
code/climpet_2_1/C.cpp.tk                           |  67
code/ctzsm_0_1/A.cpp.tk                             |  22
code/ctzsm_1_1/B.cpp.tk                             |  25
code/ctzsm_2_1/C.cpp.tk                             |  82
code/DanilC_0_1/problem.cpp.tk                      |  44
code/DanilC_1_1/problemB.cpp.tk                     |  56
code/DanilC_2_1/problemC.cpp.tk                     |  107
code/DEGwer_0_1/A.cpp.tk                            |  26
code/DEGwer_1_1/B.cpp.tk                            |  28
code/DEGwer_2_1/C.cpp.tk                            |  30
code/dmute_0_1/a.cpp.tk                             |  15
code/dmute_1_1/b.cpp.tk                             |  26
code/dmute_2_1/c2.cpp.tk                            |  47
code/fagu_0_1/A.cpp.tk                              |  10
code/fagu_1_1/B.cpp.tk                              |  10
code/fagu_2_1/C.cpp.tk                              |  34
code/FatalEagle_0_1/main.cpp.tk                     |  20
code/FatalEagle_1_1/main.cpp.tk                     |  34
code/FatalEagle_2_1/main.cpp.tk                     |  155
code/fullpower_0_1/A.cpp.tk                         |  40
code/fullpower_1_1/B.cpp.tk                         |  42
code/fullpower_2_1/C.cpp.tk                         |  84
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  17
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  24
code/ICastro_2_1/Dijkstra.cpp.tk                    |  97
code/ilackthatsuperpower_0_1/a.cpp.tk               |  165443
code/ilackthatsuperpower_1_1/b.cpp.tk               |  73621
code/ilackthatsuperpower_2_1/c.cpp.tk               |  70400
code/iridescent_0_1/A.cpp.tk                        |  13
code/iridescent_1_1/B.cpp.tk                        |  24
code/iridescent_2_1/C.cpp.tk                        |  23
code/ishraq_0_1/main.cpp.tk                         |  9
code/ishraq_1_1/main.cpp.tk                         |  15
code/ishraq_2_1/main.cpp.tk                         |  61
code/JayXon_0_1/A.cpp.tk                            |  12
code/JayXon_1_1/B.cpp.tk                            |  28
code/JayXon_2_1/C.cpp.tk                            |  37
code/Josse_0_1/A.cpp.tk                             |  17
code/Josse_1_1/B.cpp.tk                             |  26
code/Josse_2_1/C.cpp.tk                             |  96
code/kcm1700_0_1/a.cpp.tk                           |  16
code/kcm1700_1_1/b.cpp.tk                           |  24
code/kcm1700_2_1/c.cpp.tk                           |  54
code/kevinsogo_0_1/a.cpp.tk                         |  13
code/kevinsogo_1_1/b.cpp.tk                         |  14
code/kevinsogo_2_1/c.cpp.tk                         |  51
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  10
code/LazyAnna_0_1/1.cpp.tk                          |  17
code/LazyAnna_1_1/2-1.cpp.tk                        |  21
code/LazyAnna_2_1/3.cpp.tk                          |  34
code/Merkurev_0_1/A.cpp.tk                          |  35
code/Merkurev_1_1/B.cpp.tk                          |  40
code/Merkurev_2_1/C.cpp.tk                          |  42
code/mezei_0_1/main.cpp.tk                          |  25
code/mezei_1_1/main.cpp.tk                          |  24
code/mezei_2_1/main.cpp.tk                          |  70
code/Mister_0_1/a.cpp.tk                            |  17
code/Mister_1_1/b.cpp.tk                            |  19
code/Mister_2_1/c.cpp.tk                            |  34
code/namonakiacc_0_1/cpp.cpp.tk                     |  19
code/namonakiacc_1_1/cpp.cpp.tk                     |  22
code/namonakiacc_2_1/cpp.cpp.tk                     |  41
code/Nicolas16_0_1/main.cpp.tk                      |  9
code/Nicolas16_1_1/main.cpp.tk                      |  8
code/Nicolas16_2_1/main.cpp.tk                      |  67
code/pandamonium_0_1/a.cpp.tk                       |  17
code/pandamonium_1_1/b.cpp.tk                       |  40
code/pandamonium_2_1/c.cpp.tk                       |  24
code/pflueger_0_1/A.cpp.tk                          |  15
code/pflueger_1_1/B.cpp.tk                          |  24
code/pflueger_2_1/C.cpp.tk                          |  55
code/ponyopoppo_0_1/A.cpp.tk                        |  15
code/ponyopoppo_1_1/B.cpp.tk                        |  27
code/ponyopoppo_2_1/C.cpp.tk                        |  130
code/Ragnar_0_1/A.cpp.tk                            |  16
code/Ragnar_1_1/B-2.cpp.tk                          |  24
code/Ragnar_2_1/C.cpp.tk                            |  42
code/saffah_0_1/t.cpp.tk                            |  10
code/saffah_1_1/t.cpp.tk                            |  13
code/saffah_2_1/t.cpp.tk                            |  88
code/SamanSami_0_1/A.cpp.tk                         |  6
code/SamanSami_1_1/B.cpp.tk                         |  22
code/SamanSami_2_1/C.cpp.tk                         |  11
code/Savlik_0_1/code.cpp.tk                         |  14
code/Savlik_1_1/code.cpp.tk                         |  15
code/Savlik_2_1/code.cpp.tk                         |  64
code/shik_0_1/pa.cpp.tk                             |  96
code/shik_1_1/pb.cpp.tk                             |  98
code/shik_2_1/pc.cpp.tk                             |  123
code/simsa.st_0_1/A.cpp.tk                          |  11
code/simsa.st_1_1/B.cpp.tk                          |  15
code/simsa.st_2_1/C.cpp.tk                          |  80
code/SovietUnion_0_1/A.cpp.tk                       |  25
code/SovietUnion_1_1/B.cpp.tk                       |  32
code/SovietUnion_2_1/C.cpp.tk                       |  72
code/tailed_0_1/A.cpp.tk                            |  13
code/tailed_1_1/B.cpp.tk                            |  19
code/tailed_2_1/C.cpp.tk                            |  35
code/TheNatural_0_1/A.cpp.tk                        |  21
code/TheNatural_1_1/B.cpp.tk                        |  24
code/TheNatural_2_1/C.cpp.tk                        |  23
code/TrueBamboo_0_1/test.cpp.tk                     |  16
code/TrueBamboo_1_1/test.cpp.tk                     |  22
code/TrueBamboo_2_1/test.cpp.tk                     |  45
code/tur.turczyn_0_1/A.cpp.tk                       |  13
code/tur.turczyn_1_1/B.cpp.tk                       |  21
code/tur.turczyn_2_1/C.cpp.tk                       |  23
code/Tyg3R_0_1/A.cpp.tk                             |  12
code/Tyg3R_1_1/B.cpp.tk                             |  17
code/Tyg3R_2_1/C.cpp.tk                             |  18
code/UminchuR_0_1/main.cpp.tk                       |  21
code/UminchuR_1_1/main.cpp.tk                       |  29
code/UminchuR_2_1/main.cpp.tk                       |  46
code/wo..._0_1/a.cpp.tk                             |  25
code/wo..._1_1/b.cpp.tk                             |  25
code/wo..._2_1/c.cpp.tk                             |  63
code/yswtt_0_1/A.cpp.tk                             |  16
code/yswtt_1_1/B.cpp.tk                             |  22
code/yswtt_2_1/C.cpp.tk                             |  36
code/ZhSh_0_1/a.cpp.tk                              |  17
code/ZhSh_1_1/b.cpp.tk                              |  82
code/ZhSh_2_1/c.cpp.tk                              |  92
