Begin
Comparing:  code/SamanSami_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  31
code/551100kk_1_1/B.cpp.tk                          |  41
code/551100kk_2_1/C.cpp.tk                          |  32
code/achan1058_0_1/Q-A.cpp.tk                       |  12
code/achan1058_1_1/source.cpp.tk                    |  25
code/achan1058_2_1/source.cpp.tk                    |  36
code/alanubi_0_1/a.cpp.tk                           |  64
code/alanubi_1_1/b.cpp.tk                           |  42
code/alanubi_2_1/c.cpp.tk                           |  122
code/AntiForest_0_1/q1.cpp.tk                       |  12
code/AntiForest_1_1/q2.cpp.tk                       |  7
code/AntiForest_2_1/q3.cpp.tk                       |  38
code/apiad_0_1/A.cpp.tk                             |  16
code/apiad_1_1/B.cpp.tk                             |  16
code/apiad_2_1/C.cpp.tk                             |  17
code/azaky_0_1/A.cpp.tk                             |  12
code/azaky_1_1/B.cpp.tk                             |  15
code/azaky_2_1/C.cpp.tk                             |  32
code/azariamuh_0_1/standing.cpp.tk                  |  18
code/azariamuh_1_1/pancake.cpp.tk                   |  17
code/azariamuh_2_1/dijkstra.cpp.tk                  |  18
code/bmerry_0_1/a.cpp.tk                            |  123
code/bmerry_1_1/b.cpp.tk                            |  120
code/bmerry_2_1/c.cpp.tk                            |  87
code/climpet_0_1/A.cpp.tk                           |  80
code/climpet_1_1/B.cpp.tk                           |  86
code/climpet_2_1/C.cpp.tk                           |  101
code/ctzsm_0_1/A.cpp.tk                             |  45
code/ctzsm_1_1/B.cpp.tk                             |  46
code/ctzsm_2_1/C.cpp.tk                             |  86
code/DanilC_0_1/problem.cpp.tk                      |  80
code/DanilC_1_1/problemB.cpp.tk                     |  76
code/DanilC_2_1/problemC.cpp.tk                     |  101
code/DEGwer_0_1/A.cpp.tk                            |  89
code/DEGwer_1_1/B.cpp.tk                            |  62
code/DEGwer_2_1/C.cpp.tk                            |  41
code/dmute_0_1/a.cpp.tk                             |  93
code/dmute_1_1/b.cpp.tk                             |  150
code/dmute_2_1/c2.cpp.tk                            |  152
code/fagu_0_1/A.cpp.tk                              |  18
code/fagu_1_1/B.cpp.tk                              |  19
code/fagu_2_1/C.cpp.tk                              |  27
code/FatalEagle_0_1/main.cpp.tk                     |  102
code/FatalEagle_1_1/main.cpp.tk                     |  157
code/FatalEagle_2_1/main.cpp.tk                     |  236
code/fullpower_0_1/A.cpp.tk                         |  140
code/fullpower_1_1/B.cpp.tk                         |  231
code/fullpower_2_1/C.cpp.tk                         |  260
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  60
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  76
code/ICastro_2_1/Dijkstra.cpp.tk                    |  102
code/ilackthatsuperpower_0_1/a.cpp.tk               |  116
code/ilackthatsuperpower_1_1/b.cpp.tk               |  125
code/ilackthatsuperpower_2_1/c.cpp.tk               |  88
code/iridescent_0_1/A.cpp.tk                        |  133
code/iridescent_1_1/B.cpp.tk                        |  258
code/iridescent_2_1/C.cpp.tk                        |  153
code/ishraq_0_1/main.cpp.tk                         |  13
code/ishraq_1_1/main.cpp.tk                         |  26
code/ishraq_2_1/main.cpp.tk                         |  36
code/JayXon_0_1/A.cpp.tk                            |  50
code/JayXon_1_1/B.cpp.tk                            |  74
code/JayXon_2_1/C.cpp.tk                            |  18
code/Josse_0_1/A.cpp.tk                             |  41
code/Josse_1_1/B.cpp.tk                             |  65
code/Josse_2_1/C.cpp.tk                             |  101
code/kcm1700_0_1/a.cpp.tk                           |  98
code/kcm1700_1_1/b.cpp.tk                           |  118
code/kcm1700_2_1/c.cpp.tk                           |  119
code/kevinsogo_0_1/a.cpp.tk                         |  8
code/kevinsogo_1_1/b.cpp.tk                         |  12
code/kevinsogo_2_1/c.cpp.tk                         |  30
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  9
code/LazyAnna_0_1/1.cpp.tk                          |  68
code/LazyAnna_1_1/2-1.cpp.tk                        |  91
code/LazyAnna_2_1/3.cpp.tk                          |  43
code/Merkurev_0_1/A.cpp.tk                          |  142
code/Merkurev_1_1/B.cpp.tk                          |  95
code/Merkurev_2_1/C.cpp.tk                          |  139
code/mezei_0_1/main.cpp.tk                          |  152
code/mezei_1_1/main.cpp.tk                          |  93
code/mezei_2_1/main.cpp.tk                          |  113
code/Mister_0_1/a.cpp.tk                            |  39
code/Mister_1_1/b.cpp.tk                            |  52
code/Mister_2_1/c.cpp.tk                            |  64
code/namonakiacc_0_1/cpp.cpp.tk                     |  25
code/namonakiacc_1_1/cpp.cpp.tk                     |  25
code/namonakiacc_2_1/cpp.cpp.tk                     |  32
code/Nicolas16_0_1/main.cpp.tk                      |  54
code/Nicolas16_1_1/main.cpp.tk                      |  54
code/Nicolas16_2_1/main.cpp.tk                      |  200
code/pandamonium_0_1/a.cpp.tk                       |  97
code/pandamonium_1_1/b.cpp.tk                       |  97
code/pandamonium_2_1/c.cpp.tk                       |  79
code/pflueger_0_1/A.cpp.tk                          |  173
code/pflueger_1_1/B.cpp.tk                          |  176
code/pflueger_2_1/C.cpp.tk                          |  226
code/ponyopoppo_0_1/A.cpp.tk                        |  24
code/ponyopoppo_1_1/B.cpp.tk                        |  22
code/ponyopoppo_2_1/C.cpp.tk                        |  60
code/Ragnar_0_1/A.cpp.tk                            |  44
code/Ragnar_1_1/B-2.cpp.tk                          |  51
code/Ragnar_2_1/C.cpp.tk                            |  141
code/saffah_0_1/t.cpp.tk                            |  8
code/saffah_1_1/t.cpp.tk                            |  9
code/saffah_2_1/t.cpp.tk                            |  52
code/SamanSami_0_1/A.cpp.tk                         |  447
code/SamanSami_1_1/B.cpp.tk                         |  396
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  61
code/Savlik_1_1/code.cpp.tk                         |  14
code/Savlik_2_1/code.cpp.tk                         |  39
code/shik_0_1/pa.cpp.tk                             |  31
code/shik_1_1/pb.cpp.tk                             |  32
code/shik_2_1/pc.cpp.tk                             |  47
code/simsa.st_0_1/A.cpp.tk                          |  12
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  38
code/SovietUnion_0_1/A.cpp.tk                       |  59
code/SovietUnion_1_1/B.cpp.tk                       |  74
code/SovietUnion_2_1/C.cpp.tk                       |  59
code/tailed_0_1/A.cpp.tk                            |  124
code/tailed_1_1/B.cpp.tk                            |  138
code/tailed_2_1/C.cpp.tk                            |  47
code/TheNatural_0_1/A.cpp.tk                        |  255
code/TheNatural_1_1/B.cpp.tk                        |  217
code/TheNatural_2_1/C.cpp.tk                        |  165
code/TrueBamboo_0_1/test.cpp.tk                     |  53
code/TrueBamboo_1_1/test.cpp.tk                     |  46
code/TrueBamboo_2_1/test.cpp.tk                     |  51
code/tur.turczyn_0_1/A.cpp.tk                       |  22
code/tur.turczyn_1_1/B.cpp.tk                       |  29
code/tur.turczyn_2_1/C.cpp.tk                       |  30
code/Tyg3R_0_1/A.cpp.tk                             |  18
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  19
code/UminchuR_0_1/main.cpp.tk                       |  22
code/UminchuR_1_1/main.cpp.tk                       |  23
code/UminchuR_2_1/main.cpp.tk                       |  40
code/wo..._0_1/a.cpp.tk                             |  79
code/wo..._1_1/b.cpp.tk                             |  86
code/wo..._2_1/c.cpp.tk                             |  119
code/yswtt_0_1/A.cpp.tk                             |  88
code/yswtt_1_1/B.cpp.tk                             |  103
code/yswtt_2_1/C.cpp.tk                             |  91
code/ZhSh_0_1/a.cpp.tk                              |  92
code/ZhSh_1_1/b.cpp.tk                              |  121
code/ZhSh_2_1/c.cpp.tk                              |  105
