Begin
Comparing:  code/ponyopoppo_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  14
code/551100kk_1_1/B.cpp.tk                          |  23
code/551100kk_2_1/C.cpp.tk                          |  53
code/achan1058_0_1/Q-A.cpp.tk                       |  10
code/achan1058_1_1/source.cpp.tk                    |  25
code/achan1058_2_1/source.cpp.tk                    |  90
code/alanubi_0_1/a.cpp.tk                           |  8
code/alanubi_1_1/b.cpp.tk                           |  13
code/alanubi_2_1/c.cpp.tk                           |  81
code/AntiForest_0_1/q1.cpp.tk                       |  17
code/AntiForest_1_1/q2.cpp.tk                       |  9
code/AntiForest_2_1/q3.cpp.tk                       |  75
code/apiad_0_1/A.cpp.tk                             |  16
code/apiad_1_1/B.cpp.tk                             |  23
code/apiad_2_1/C.cpp.tk                             |  30
code/azaky_0_1/A.cpp.tk                             |  22
code/azaky_1_1/B.cpp.tk                             |  27
code/azaky_2_1/C.cpp.tk                             |  80
code/azariamuh_0_1/standing.cpp.tk                  |  12
code/azariamuh_1_1/pancake.cpp.tk                   |  28
code/azariamuh_2_1/dijkstra.cpp.tk                  |  36
code/bmerry_0_1/a.cpp.tk                            |  49
code/bmerry_1_1/b.cpp.tk                            |  57
code/bmerry_2_1/c.cpp.tk                            |  57
code/climpet_0_1/A.cpp.tk                           |  26
code/climpet_1_1/B.cpp.tk                           |  31
code/climpet_2_1/C.cpp.tk                           |  56
code/ctzsm_0_1/A.cpp.tk                             |  14
code/ctzsm_1_1/B.cpp.tk                             |  19
code/ctzsm_2_1/C.cpp.tk                             |  91
code/DanilC_0_1/problem.cpp.tk                      |  28
code/DanilC_1_1/problemB.cpp.tk                     |  42
code/DanilC_2_1/problemC.cpp.tk                     |  129
code/DEGwer_0_1/A.cpp.tk                            |  17
code/DEGwer_1_1/B.cpp.tk                            |  18
code/DEGwer_2_1/C.cpp.tk                            |  45
code/dmute_0_1/a.cpp.tk                             |  7
code/dmute_1_1/b.cpp.tk                             |  12
code/dmute_2_1/c2.cpp.tk                            |  47
code/fagu_0_1/A.cpp.tk                              |  5
code/fagu_1_1/B.cpp.tk                              |  5
code/fagu_2_1/C.cpp.tk                              |  40
code/FatalEagle_0_1/main.cpp.tk                     |  12
code/FatalEagle_1_1/main.cpp.tk                     |  18
code/FatalEagle_2_1/main.cpp.tk                     |  145
code/fullpower_0_1/A.cpp.tk                         |  21
code/fullpower_1_1/B.cpp.tk                         |  21
code/fullpower_2_1/C.cpp.tk                         |  79
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  8
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  15
code/ICastro_2_1/Dijkstra.cpp.tk                    |  149
code/ilackthatsuperpower_0_1/a.cpp.tk               |  96
code/ilackthatsuperpower_1_1/b.cpp.tk               |  102
code/ilackthatsuperpower_2_1/c.cpp.tk               |  190
code/iridescent_0_1/A.cpp.tk                        |  7
code/iridescent_1_1/B.cpp.tk                        |  8
code/iridescent_2_1/C.cpp.tk                        |  14
code/ishraq_0_1/main.cpp.tk                         |  9
code/ishraq_1_1/main.cpp.tk                         |  13
code/ishraq_2_1/main.cpp.tk                         |  78
code/JayXon_0_1/A.cpp.tk                            |  6
code/JayXon_1_1/B.cpp.tk                            |  17
code/JayXon_2_1/C.cpp.tk                            |  61
code/Josse_0_1/A.cpp.tk                             |  9
code/Josse_1_1/B.cpp.tk                             |  12
code/Josse_2_1/C.cpp.tk                             |  92
code/kcm1700_0_1/a.cpp.tk                           |  6
code/kcm1700_1_1/b.cpp.tk                           |  10
code/kcm1700_2_1/c.cpp.tk                           |  45
code/kevinsogo_0_1/a.cpp.tk                         |  14
code/kevinsogo_1_1/b.cpp.tk                         |  17
code/kevinsogo_2_1/c.cpp.tk                         |  64
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  21
code/LazyAnna_0_1/1.cpp.tk                          |  6
code/LazyAnna_1_1/2-1.cpp.tk                        |  10
code/LazyAnna_2_1/3.cpp.tk                          |  40
code/Merkurev_0_1/A.cpp.tk                          |  11
code/Merkurev_1_1/B.cpp.tk                          |  31
code/Merkurev_2_1/C.cpp.tk                          |  27
code/mezei_0_1/main.cpp.tk                          |  12
code/mezei_1_1/main.cpp.tk                          |  12
code/mezei_2_1/main.cpp.tk                          |  79
code/Mister_0_1/a.cpp.tk                            |  12
code/Mister_1_1/b.cpp.tk                            |  11
code/Mister_2_1/c.cpp.tk                            |  28
code/namonakiacc_0_1/cpp.cpp.tk                     |  17
code/namonakiacc_1_1/cpp.cpp.tk                     |  24
code/namonakiacc_2_1/cpp.cpp.tk                     |  54
code/Nicolas16_0_1/main.cpp.tk                      |  5
code/Nicolas16_1_1/main.cpp.tk                      |  5
code/Nicolas16_2_1/main.cpp.tk                      |  69
code/pandamonium_0_1/a.cpp.tk                       |  9
code/pandamonium_1_1/b.cpp.tk                       |  32
code/pandamonium_2_1/c.cpp.tk                       |  16
code/pflueger_0_1/A.cpp.tk                          |  8
code/pflueger_1_1/B.cpp.tk                          |  13
code/pflueger_2_1/C.cpp.tk                          |  70
code/ponyopoppo_0_1/A.cpp.tk                        |  14
code/ponyopoppo_1_1/B.cpp.tk                        |  30
code/ponyopoppo_2_1/C.cpp.tk                        |  286230
code/Ragnar_0_1/A.cpp.tk                            |  14
code/Ragnar_1_1/B-2.cpp.tk                          |  22
code/Ragnar_2_1/C.cpp.tk                            |  50
code/saffah_0_1/t.cpp.tk                            |  11
code/saffah_1_1/t.cpp.tk                            |  16
code/saffah_2_1/t.cpp.tk                            |  127
code/SamanSami_0_1/A.cpp.tk                         |  2
code/SamanSami_1_1/B.cpp.tk                         |  8
code/SamanSami_2_1/C.cpp.tk                         |  31
code/Savlik_0_1/code.cpp.tk                         |  10
code/Savlik_1_1/code.cpp.tk                         |  18
code/Savlik_2_1/code.cpp.tk                         |  114
code/shik_0_1/pa.cpp.tk                             |  72
code/shik_1_1/pb.cpp.tk                             |  77
code/shik_2_1/pc.cpp.tk                             |  112
code/simsa.st_0_1/A.cpp.tk                          |  13
code/simsa.st_1_1/B.cpp.tk                          |  19
code/simsa.st_2_1/C.cpp.tk                          |  200
code/SovietUnion_0_1/A.cpp.tk                       |  13
code/SovietUnion_1_1/B.cpp.tk                       |  16
code/SovietUnion_2_1/C.cpp.tk                       |  157
code/tailed_0_1/A.cpp.tk                            |  8
code/tailed_1_1/B.cpp.tk                            |  12
code/tailed_2_1/C.cpp.tk                            |  47
code/TheNatural_0_1/A.cpp.tk                        |  6
code/TheNatural_1_1/B.cpp.tk                        |  7
code/TheNatural_2_1/C.cpp.tk                        |  26
code/TrueBamboo_0_1/test.cpp.tk                     |  14
code/TrueBamboo_1_1/test.cpp.tk                     |  21
code/TrueBamboo_2_1/test.cpp.tk                     |  97
code/tur.turczyn_0_1/A.cpp.tk                       |  14
code/tur.turczyn_1_1/B.cpp.tk                       |  24
code/tur.turczyn_2_1/C.cpp.tk                       |  33
code/Tyg3R_0_1/A.cpp.tk                             |  14
code/Tyg3R_1_1/B.cpp.tk                             |  20
code/Tyg3R_2_1/C.cpp.tk                             |  24
code/UminchuR_0_1/main.cpp.tk                       |  23
code/UminchuR_1_1/main.cpp.tk                       |  32
code/UminchuR_2_1/main.cpp.tk                       |  55
code/wo..._0_1/a.cpp.tk                             |  10
code/wo..._1_1/b.cpp.tk                             |  12
code/wo..._2_1/c.cpp.tk                             |  60
code/yswtt_0_1/A.cpp.tk                             |  7
code/yswtt_1_1/B.cpp.tk                             |  14
code/yswtt_2_1/C.cpp.tk                             |  44
code/ZhSh_0_1/a.cpp.tk                              |  7
code/ZhSh_1_1/b.cpp.tk                              |  60
code/ZhSh_2_1/c.cpp.tk                              |  107
