Begin
Comparing:  code/azariamuh_2_1/dijkstra.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  10
code/551100kk_1_1/B.cpp.tk                          |  17
code/551100kk_2_1/C.cpp.tk                          |  64
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  18
code/achan1058_2_1/source.cpp.tk                    |  47
code/alanubi_0_1/a.cpp.tk                           |  10
code/alanubi_1_1/b.cpp.tk                           |  15
code/alanubi_2_1/c.cpp.tk                           |  56
code/AntiForest_0_1/q1.cpp.tk                       |  21
code/AntiForest_1_1/q2.cpp.tk                       |  13
code/AntiForest_2_1/q3.cpp.tk                       |  78
code/apiad_0_1/A.cpp.tk                             |  12
code/apiad_1_1/B.cpp.tk                             |  24
code/apiad_2_1/C.cpp.tk                             |  38
code/azaky_0_1/A.cpp.tk                             |  24
code/azaky_1_1/B.cpp.tk                             |  27
code/azaky_2_1/C.cpp.tk                             |  218
code/azariamuh_0_1/standing.cpp.tk                  |  27
code/azariamuh_1_1/pancake.cpp.tk                   |  35
code/azariamuh_2_1/dijkstra.cpp.tk                  |  21003
code/bmerry_0_1/a.cpp.tk                            |  35
code/bmerry_1_1/b.cpp.tk                            |  39
code/bmerry_2_1/c.cpp.tk                            |  58
code/climpet_0_1/A.cpp.tk                           |  19
code/climpet_1_1/B.cpp.tk                           |  21
code/climpet_2_1/C.cpp.tk                           |  52
code/ctzsm_0_1/A.cpp.tk                             |  16
code/ctzsm_1_1/B.cpp.tk                             |  20
code/ctzsm_2_1/C.cpp.tk                             |  231
code/DanilC_0_1/problem.cpp.tk                      |  20
code/DanilC_1_1/problemB.cpp.tk                     |  29
code/DanilC_2_1/problemC.cpp.tk                     |  73
code/DEGwer_0_1/A.cpp.tk                            |  16
code/DEGwer_1_1/B.cpp.tk                            |  17
code/DEGwer_2_1/C.cpp.tk                            |  68
code/dmute_0_1/a.cpp.tk                             |  10
code/dmute_1_1/b.cpp.tk                             |  15
code/dmute_2_1/c2.cpp.tk                            |  80
code/fagu_0_1/A.cpp.tk                              |  9
code/fagu_1_1/B.cpp.tk                              |  10
code/fagu_2_1/C.cpp.tk                              |  59
code/FatalEagle_0_1/main.cpp.tk                     |  15
code/FatalEagle_1_1/main.cpp.tk                     |  21
code/FatalEagle_2_1/main.cpp.tk                     |  107
code/fullpower_0_1/A.cpp.tk                         |  18
code/fullpower_1_1/B.cpp.tk                         |  20
code/fullpower_2_1/C.cpp.tk                         |  82
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  7
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  11
code/ICastro_2_1/Dijkstra.cpp.tk                    |  84
code/ilackthatsuperpower_0_1/a.cpp.tk               |  54
code/ilackthatsuperpower_1_1/b.cpp.tk               |  55
code/ilackthatsuperpower_2_1/c.cpp.tk               |  91
code/iridescent_0_1/A.cpp.tk                        |  6
code/iridescent_1_1/B.cpp.tk                        |  9
code/iridescent_2_1/C.cpp.tk                        |  46
code/ishraq_0_1/main.cpp.tk                         |  11
code/ishraq_1_1/main.cpp.tk                         |  14
code/ishraq_2_1/main.cpp.tk                         |  79
code/JayXon_0_1/A.cpp.tk                            |  5
code/JayXon_1_1/B.cpp.tk                            |  15
code/JayXon_2_1/C.cpp.tk                            |  34
code/Josse_0_1/A.cpp.tk                             |  9
code/Josse_1_1/B.cpp.tk                             |  12
code/Josse_2_1/C.cpp.tk                             |  57
code/kcm1700_0_1/a.cpp.tk                           |  8
code/kcm1700_1_1/b.cpp.tk                           |  13
code/kcm1700_2_1/c.cpp.tk                           |  56
code/kevinsogo_0_1/a.cpp.tk                         |  11
code/kevinsogo_1_1/b.cpp.tk                         |  13
code/kevinsogo_2_1/c.cpp.tk                         |  57
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  20
code/LazyAnna_0_1/1.cpp.tk                          |  8
code/LazyAnna_1_1/2-1.cpp.tk                        |  12
code/LazyAnna_2_1/3.cpp.tk                          |  41
code/Merkurev_0_1/A.cpp.tk                          |  13
code/Merkurev_1_1/B.cpp.tk                          |  31
code/Merkurev_2_1/C.cpp.tk                          |  29
code/mezei_0_1/main.cpp.tk                          |  15
code/mezei_1_1/main.cpp.tk                          |  13
code/mezei_2_1/main.cpp.tk                          |  59
code/Mister_0_1/a.cpp.tk                            |  9
code/Mister_1_1/b.cpp.tk                            |  13
code/Mister_2_1/c.cpp.tk                            |  56
code/namonakiacc_0_1/cpp.cpp.tk                     |  22
code/namonakiacc_1_1/cpp.cpp.tk                     |  27
code/namonakiacc_2_1/cpp.cpp.tk                     |  61
code/Nicolas16_0_1/main.cpp.tk                      |  7
code/Nicolas16_1_1/main.cpp.tk                      |  7
code/Nicolas16_2_1/main.cpp.tk                      |  62
code/pandamonium_0_1/a.cpp.tk                       |  11
code/pandamonium_1_1/b.cpp.tk                       |  28
code/pandamonium_2_1/c.cpp.tk                       |  25
code/pflueger_0_1/A.cpp.tk                          |  6
code/pflueger_1_1/B.cpp.tk                          |  16
code/pflueger_2_1/C.cpp.tk                          |  58
code/ponyopoppo_0_1/A.cpp.tk                        |  7
code/ponyopoppo_1_1/B.cpp.tk                        |  15
code/ponyopoppo_2_1/C.cpp.tk                        |  122
code/Ragnar_0_1/A.cpp.tk                            |  10
code/Ragnar_1_1/B-2.cpp.tk                          |  14
code/Ragnar_2_1/C.cpp.tk                            |  32
code/saffah_0_1/t.cpp.tk                            |  13
code/saffah_1_1/t.cpp.tk                            |  20
code/saffah_2_1/t.cpp.tk                            |  75
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  9
code/SamanSami_2_1/C.cpp.tk                         |  16
code/Savlik_0_1/code.cpp.tk                         |  8
code/Savlik_1_1/code.cpp.tk                         |  11
code/Savlik_2_1/code.cpp.tk                         |  50
code/shik_0_1/pa.cpp.tk                             |  44
code/shik_1_1/pb.cpp.tk                             |  47
code/shik_2_1/pc.cpp.tk                             |  96
code/simsa.st_0_1/A.cpp.tk                          |  20
code/simsa.st_1_1/B.cpp.tk                          |  20
code/simsa.st_2_1/C.cpp.tk                          |  69
code/SovietUnion_0_1/A.cpp.tk                       |  12
code/SovietUnion_1_1/B.cpp.tk                       |  15
code/SovietUnion_2_1/C.cpp.tk                       |  53
code/tailed_0_1/A.cpp.tk                            |  8
code/tailed_1_1/B.cpp.tk                            |  10
code/tailed_2_1/C.cpp.tk                            |  247
code/TheNatural_0_1/A.cpp.tk                        |  9
code/TheNatural_1_1/B.cpp.tk                        |  11
code/TheNatural_2_1/C.cpp.tk                        |  38
code/TrueBamboo_0_1/test.cpp.tk                     |  9
code/TrueBamboo_1_1/test.cpp.tk                     |  12
code/TrueBamboo_2_1/test.cpp.tk                     |  44
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  15
code/tur.turczyn_2_1/C.cpp.tk                       |  212
code/Tyg3R_0_1/A.cpp.tk                             |  10
code/Tyg3R_1_1/B.cpp.tk                             |  19
code/Tyg3R_2_1/C.cpp.tk                             |  217
code/UminchuR_0_1/main.cpp.tk                       |  19
code/UminchuR_1_1/main.cpp.tk                       |  27
code/UminchuR_2_1/main.cpp.tk                       |  54
code/wo..._0_1/a.cpp.tk                             |  16
code/wo..._1_1/b.cpp.tk                             |  18
code/wo..._2_1/c.cpp.tk                             |  87
code/yswtt_0_1/A.cpp.tk                             |  6
code/yswtt_1_1/B.cpp.tk                             |  11
code/yswtt_2_1/C.cpp.tk                             |  32
code/ZhSh_0_1/a.cpp.tk                              |  6
code/ZhSh_1_1/b.cpp.tk                              |  43
code/ZhSh_2_1/c.cpp.tk                              |  144
