Begin
Comparing:  code/00/test.cpp.tk
code/00/test.cpp.tk                                 |  11432
code/01/test.cpp.tk                                 |  3959
code/551100kk_0_1/A.cpp.tk                          |  22
code/551100kk_1_1/B.cpp.tk                          |  46
code/551100kk_2_1/C.cpp.tk                          |  100
code/achan1058_0_1/Q-A.cpp.tk                       |  12
code/achan1058_1_1/source.cpp.tk                    |  28
code/achan1058_2_1/source.cpp.tk                    |  68
code/alanubi_0_1/a.cpp.tk                           |  43
code/alanubi_1_1/b.cpp.tk                           |  83
code/alanubi_2_1/c.cpp.tk                           |  253
code/AntiForest_0_1/q1.cpp.tk                       |  22
code/AntiForest_1_1/q2.cpp.tk                       |  7
code/AntiForest_2_1/q3.cpp.tk                       |  92
code/apiad_0_1/A.cpp.tk                             |  22
code/apiad_1_1/B.cpp.tk                             |  25
code/apiad_2_1/C.cpp.tk                             |  49
code/azaky_0_1/A.cpp.tk                             |  25
code/azaky_1_1/B.cpp.tk                             |  28
code/azaky_2_1/C.cpp.tk                             |  78
code/azariamuh_0_1/standing.cpp.tk                  |  17
code/azariamuh_1_1/pancake.cpp.tk                   |  35
code/azariamuh_2_1/dijkstra.cpp.tk                  |  28
code/bmerry_0_1/a.cpp.tk                            |  80
code/bmerry_1_1/b.cpp.tk                            |  111
code/bmerry_2_1/c.cpp.tk                            |  107
code/climpet_0_1/A.cpp.tk                           |  43
code/climpet_1_1/B.cpp.tk                           |  56
code/climpet_2_1/C.cpp.tk                           |  99
code/ctzsm_0_1/A.cpp.tk                             |  27
code/ctzsm_1_1/B.cpp.tk                             |  40
code/ctzsm_2_1/C.cpp.tk                             |  147
code/DanilC_0_1/problem.cpp.tk                      |  53
code/DanilC_1_1/problemB.cpp.tk                     |  99
code/DanilC_2_1/problemC.cpp.tk                     |  143
code/DEGwer_0_1/A.cpp.tk                            |  60
code/DEGwer_1_1/B.cpp.tk                            |  85
code/DEGwer_2_1/C.cpp.tk                            |  66
code/dmute_0_1/a.cpp.tk                             |  24
code/dmute_1_1/b.cpp.tk                             |  50
code/dmute_2_1/c2.cpp.tk                            |  117
code/fagu_0_1/A.cpp.tk                              |  27
code/fagu_1_1/B.cpp.tk                              |  27
code/fagu_2_1/C.cpp.tk                              |  64
code/FatalEagle_0_1/main.cpp.tk                     |  38
code/FatalEagle_1_1/main.cpp.tk                     |  78
code/FatalEagle_2_1/main.cpp.tk                     |  392
code/fullpower_0_1/A.cpp.tk                         |  53
code/fullpower_1_1/B.cpp.tk                         |  87
code/fullpower_2_1/C.cpp.tk                         |  151
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  27
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  49
code/ICastro_2_1/Dijkstra.cpp.tk                    |  131
code/ilackthatsuperpower_0_1/a.cpp.tk               |  171
code/ilackthatsuperpower_1_1/b.cpp.tk               |  171
code/ilackthatsuperpower_2_1/c.cpp.tk               |  237
code/iridescent_0_1/A.cpp.tk                        |  47
code/iridescent_1_1/B.cpp.tk                        |  38
code/iridescent_2_1/C.cpp.tk                        |  67
code/ishraq_0_1/main.cpp.tk                         |  14
code/ishraq_1_1/main.cpp.tk                         |  22
code/ishraq_2_1/main.cpp.tk                         |  91
code/JayXon_0_1/A.cpp.tk                            |  18
code/JayXon_1_1/B.cpp.tk                            |  67
code/JayXon_2_1/C.cpp.tk                            |  61
code/Josse_0_1/A.cpp.tk                             |  49
code/Josse_1_1/B.cpp.tk                             |  79
code/Josse_2_1/C.cpp.tk                             |  223
code/kcm1700_0_1/a.cpp.tk                           |  27
code/kcm1700_1_1/b.cpp.tk                           |  62
code/kcm1700_2_1/c.cpp.tk                           |  133
code/kevinsogo_0_1/a.cpp.tk                         |  15
code/kevinsogo_1_1/b.cpp.tk                         |  21
code/kevinsogo_2_1/c.cpp.tk                         |  101
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  21
code/LazyAnna_0_1/1.cpp.tk                          |  22
code/LazyAnna_1_1/2-1.cpp.tk                        |  40
code/LazyAnna_2_1/3.cpp.tk                          |  50
code/Merkurev_0_1/A.cpp.tk                          |  50
code/Merkurev_1_1/B.cpp.tk                          |  93
code/Merkurev_2_1/C.cpp.tk                          |  97
code/mezei_0_1/main.cpp.tk                          |  44
code/mezei_1_1/main.cpp.tk                          |  69
code/mezei_2_1/main.cpp.tk                          |  153
code/Mister_0_1/a.cpp.tk                            |  22
code/Mister_1_1/b.cpp.tk                            |  36
code/Mister_2_1/c.cpp.tk                            |  69
code/namonakiacc_0_1/cpp.cpp.tk                     |  25
code/namonakiacc_1_1/cpp.cpp.tk                     |  27
code/namonakiacc_2_1/cpp.cpp.tk                     |  80
code/Nicolas16_0_1/main.cpp.tk                      |  13
code/Nicolas16_1_1/main.cpp.tk                      |  13
code/Nicolas16_2_1/main.cpp.tk                      |  141
code/pandamonium_0_1/a.cpp.tk                       |  27
code/pandamonium_1_1/b.cpp.tk                       |  104
code/pandamonium_2_1/c.cpp.tk                       |  59
code/pflueger_0_1/A.cpp.tk                          |  24
code/pflueger_1_1/B.cpp.tk                          |  61
code/pflueger_2_1/C.cpp.tk                          |  135
code/ponyopoppo_0_1/A.cpp.tk                        |  15
code/ponyopoppo_1_1/B.cpp.tk                        |  25
code/ponyopoppo_2_1/C.cpp.tk                        |  181
code/Ragnar_0_1/A.cpp.tk                            |  18
code/Ragnar_1_1/B-2.cpp.tk                          |  37
code/Ragnar_2_1/C.cpp.tk                            |  58
code/saffah_0_1/t.cpp.tk                            |  15
code/saffah_1_1/t.cpp.tk                            |  17
code/saffah_2_1/t.cpp.tk                            |  120
code/SamanSami_0_1/A.cpp.tk                         |  10
code/SamanSami_1_1/B.cpp.tk                         |  55
code/SamanSami_2_1/C.cpp.tk                         |  16
code/Savlik_0_1/code.cpp.tk                         |  20
code/Savlik_1_1/code.cpp.tk                         |  15
code/Savlik_2_1/code.cpp.tk                         |  89
code/shik_0_1/pa.cpp.tk                             |  82
code/shik_1_1/pb.cpp.tk                             |  84
code/shik_2_1/pc.cpp.tk                             |  136
code/simsa.st_0_1/A.cpp.tk                          |  17
code/simsa.st_1_1/B.cpp.tk                          |  18
code/simsa.st_2_1/C.cpp.tk                          |  117
code/SovietUnion_0_1/A.cpp.tk                       |  34
code/SovietUnion_1_1/B.cpp.tk                       |  44
code/SovietUnion_2_1/C.cpp.tk                       |  97
code/tailed_0_1/A.cpp.tk                            |  21
code/tailed_1_1/B.cpp.tk                            |  30
code/tailed_2_1/C.cpp.tk                            |  50
code/TheNatural_0_1/A.cpp.tk                        |  36
code/TheNatural_1_1/B.cpp.tk                        |  62
code/TheNatural_2_1/C.cpp.tk                        |  48
code/TrueBamboo_0_1/test.cpp.tk                     |  26
code/TrueBamboo_1_1/test.cpp.tk                     |  43
code/TrueBamboo_2_1/test.cpp.tk                     |  73
code/tur.turczyn_0_1/A.cpp.tk                       |  15
code/tur.turczyn_1_1/B.cpp.tk                       |  22
code/tur.turczyn_2_1/C.cpp.tk                       |  32
code/Tyg3R_0_1/A.cpp.tk                             |  16
code/Tyg3R_1_1/B.cpp.tk                             |  28
code/Tyg3R_2_1/C.cpp.tk                             |  33
code/UminchuR_0_1/main.cpp.tk                       |  27
code/UminchuR_1_1/main.cpp.tk                       |  31
code/UminchuR_2_1/main.cpp.tk                       |  73
code/wo..._0_1/a.cpp.tk                             |  63
code/wo..._1_1/b.cpp.tk                             |  63
code/wo..._2_1/c.cpp.tk                             |  168
code/yswtt_0_1/A.cpp.tk                             |  19
code/yswtt_1_1/B.cpp.tk                             |  44
code/yswtt_2_1/C.cpp.tk                             |  77
code/ZhSh_0_1/a.cpp.tk                              |  21
code/ZhSh_1_1/b.cpp.tk                              |  97
code/ZhSh_2_1/c.cpp.tk                              |  113
