Begin
Comparing:  code/DanilC_2_1/problemC.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  14
code/551100kk_1_1/B.cpp.tk                          |  25
code/551100kk_2_1/C.cpp.tk                          |  49
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  27
code/achan1058_2_1/source.cpp.tk                    |  65
code/alanubi_0_1/a.cpp.tk                           |  12
code/alanubi_1_1/b.cpp.tk                           |  18
code/alanubi_2_1/c.cpp.tk                           |  111
code/AntiForest_0_1/q1.cpp.tk                       |  16
code/AntiForest_1_1/q2.cpp.tk                       |  8
code/AntiForest_2_1/q3.cpp.tk                       |  56
code/apiad_0_1/A.cpp.tk                             |  17
code/apiad_1_1/B.cpp.tk                             |  26
code/apiad_2_1/C.cpp.tk                             |  29
code/azaky_0_1/A.cpp.tk                             |  20
code/azaky_1_1/B.cpp.tk                             |  25
code/azaky_2_1/C.cpp.tk                             |  72
code/azariamuh_0_1/standing.cpp.tk                  |  12
code/azariamuh_1_1/pancake.cpp.tk                   |  31
code/azariamuh_2_1/dijkstra.cpp.tk                  |  22
code/bmerry_0_1/a.cpp.tk                            |  47
code/bmerry_1_1/b.cpp.tk                            |  60
code/bmerry_2_1/c.cpp.tk                            |  57
code/climpet_0_1/A.cpp.tk                           |  34
code/climpet_1_1/B.cpp.tk                           |  46
code/climpet_2_1/C.cpp.tk                           |  62
code/ctzsm_0_1/A.cpp.tk                             |  18
code/ctzsm_1_1/B.cpp.tk                             |  28
code/ctzsm_2_1/C.cpp.tk                             |  91
code/DanilC_0_1/problem.cpp.tk                      |  88
code/DanilC_1_1/problemB.cpp.tk                     |  153
code/DanilC_2_1/problemC.cpp.tk                     |  162079
code/DEGwer_0_1/A.cpp.tk                            |  22
code/DEGwer_1_1/B.cpp.tk                            |  25
code/DEGwer_2_1/C.cpp.tk                            |  36
code/dmute_0_1/a.cpp.tk                             |  11
code/dmute_1_1/b.cpp.tk                             |  18
code/dmute_2_1/c2.cpp.tk                            |  45
code/fagu_0_1/A.cpp.tk                              |  7
code/fagu_1_1/B.cpp.tk                              |  7
code/fagu_2_1/C.cpp.tk                              |  40
code/FatalEagle_0_1/main.cpp.tk                     |  14
code/FatalEagle_1_1/main.cpp.tk                     |  26
code/FatalEagle_2_1/main.cpp.tk                     |  172
code/fullpower_0_1/A.cpp.tk                         |  26
code/fullpower_1_1/B.cpp.tk                         |  36
code/fullpower_2_1/C.cpp.tk                         |  78
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  15
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  26
code/ICastro_2_1/Dijkstra.cpp.tk                    |  160
code/ilackthatsuperpower_0_1/a.cpp.tk               |  96
code/ilackthatsuperpower_1_1/b.cpp.tk               |  103
code/ilackthatsuperpower_2_1/c.cpp.tk               |  138
code/iridescent_0_1/A.cpp.tk                        |  10
code/iridescent_1_1/B.cpp.tk                        |  15
code/iridescent_2_1/C.cpp.tk                        |  18
code/ishraq_0_1/main.cpp.tk                         |  10
code/ishraq_1_1/main.cpp.tk                         |  15
code/ishraq_2_1/main.cpp.tk                         |  77
code/JayXon_0_1/A.cpp.tk                            |  9
code/JayXon_1_1/B.cpp.tk                            |  25
code/JayXon_2_1/C.cpp.tk                            |  43
code/Josse_0_1/A.cpp.tk                             |  13
code/Josse_1_1/B.cpp.tk                             |  20
code/Josse_2_1/C.cpp.tk                             |  97
code/kcm1700_0_1/a.cpp.tk                           |  10
code/kcm1700_1_1/b.cpp.tk                           |  18
code/kcm1700_2_1/c.cpp.tk                           |  53
code/kevinsogo_0_1/a.cpp.tk                         |  14
code/kevinsogo_1_1/b.cpp.tk                         |  17
code/kevinsogo_2_1/c.cpp.tk                         |  87
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  13
code/LazyAnna_0_1/1.cpp.tk                          |  13
code/LazyAnna_1_1/2-1.cpp.tk                        |  24
code/LazyAnna_2_1/3.cpp.tk                          |  43
code/Merkurev_0_1/A.cpp.tk                          |  17
code/Merkurev_1_1/B.cpp.tk                          |  36
code/Merkurev_2_1/C.cpp.tk                          |  39
code/mezei_0_1/main.cpp.tk                          |  19
code/mezei_1_1/main.cpp.tk                          |  19
code/mezei_2_1/main.cpp.tk                          |  66
code/Mister_0_1/a.cpp.tk                            |  17
code/Mister_1_1/b.cpp.tk                            |  24
code/Mister_2_1/c.cpp.tk                            |  43
code/namonakiacc_0_1/cpp.cpp.tk                     |  21
code/namonakiacc_1_1/cpp.cpp.tk                     |  29
code/namonakiacc_2_1/cpp.cpp.tk                     |  54
code/Nicolas16_0_1/main.cpp.tk                      |  7
code/Nicolas16_1_1/main.cpp.tk                      |  6
code/Nicolas16_2_1/main.cpp.tk                      |  65
code/pandamonium_0_1/a.cpp.tk                       |  12
code/pandamonium_1_1/b.cpp.tk                       |  42
code/pandamonium_2_1/c.cpp.tk                       |  25
code/pflueger_0_1/A.cpp.tk                          |  11
code/pflueger_1_1/B.cpp.tk                          |  20
code/pflueger_2_1/C.cpp.tk                          |  59
code/ponyopoppo_0_1/A.cpp.tk                        |  14
code/ponyopoppo_1_1/B.cpp.tk                        |  31
code/ponyopoppo_2_1/C.cpp.tk                        |  149
code/Ragnar_0_1/A.cpp.tk                            |  16
code/Ragnar_1_1/B-2.cpp.tk                          |  25
code/Ragnar_2_1/C.cpp.tk                            |  43
code/saffah_0_1/t.cpp.tk                            |  10
code/saffah_1_1/t.cpp.tk                            |  16
code/saffah_2_1/t.cpp.tk                            |  100
code/SamanSami_0_1/A.cpp.tk                         |  4
code/SamanSami_1_1/B.cpp.tk                         |  16
code/SamanSami_2_1/C.cpp.tk                         |  12
code/Savlik_0_1/code.cpp.tk                         |  12
code/Savlik_1_1/code.cpp.tk                         |  19
code/Savlik_2_1/code.cpp.tk                         |  76
code/shik_0_1/pa.cpp.tk                             |  60
code/shik_1_1/pb.cpp.tk                             |  65
code/shik_2_1/pc.cpp.tk                             |  103
code/simsa.st_0_1/A.cpp.tk                          |  12
code/simsa.st_1_1/B.cpp.tk                          |  18
code/simsa.st_2_1/C.cpp.tk                          |  87
code/SovietUnion_0_1/A.cpp.tk                       |  23
code/SovietUnion_1_1/B.cpp.tk                       |  27
code/SovietUnion_2_1/C.cpp.tk                       |  77
code/tailed_0_1/A.cpp.tk                            |  10
code/tailed_1_1/B.cpp.tk                            |  16
code/tailed_2_1/C.cpp.tk                            |  39
code/TheNatural_0_1/A.cpp.tk                        |  14
code/TheNatural_1_1/B.cpp.tk                        |  16
code/TheNatural_2_1/C.cpp.tk                        |  21
code/TrueBamboo_0_1/test.cpp.tk                     |  16
code/TrueBamboo_1_1/test.cpp.tk                     |  23
code/TrueBamboo_2_1/test.cpp.tk                     |  52
code/tur.turczyn_0_1/A.cpp.tk                       |  15
code/tur.turczyn_1_1/B.cpp.tk                       |  25
code/tur.turczyn_2_1/C.cpp.tk                       |  30
code/Tyg3R_0_1/A.cpp.tk                             |  13
code/Tyg3R_1_1/B.cpp.tk                             |  20
code/Tyg3R_2_1/C.cpp.tk                             |  20
code/UminchuR_0_1/main.cpp.tk                       |  22
code/UminchuR_1_1/main.cpp.tk                       |  33
code/UminchuR_2_1/main.cpp.tk                       |  56
code/wo..._0_1/a.cpp.tk                             |  16
code/wo..._1_1/b.cpp.tk                             |  18
code/wo..._2_1/c.cpp.tk                             |  59
code/yswtt_0_1/A.cpp.tk                             |  12
code/yswtt_1_1/B.cpp.tk                             |  29
code/yswtt_2_1/C.cpp.tk                             |  38
code/ZhSh_0_1/a.cpp.tk                              |  12
code/ZhSh_1_1/b.cpp.tk                              |  65
code/ZhSh_2_1/c.cpp.tk                              |  83
