Begin
Comparing:  code/551100kk_0_1/A.cpp.tk
code/00/test.cpp.tk                                 |  25
code/01/test.cpp.tk                                 |  25
code/551100kk_0_1/A.cpp.tk                          |  6872
code/551100kk_1_1/B.cpp.tk                          |  329
code/551100kk_2_1/C.cpp.tk                          |  297
code/achan1058_0_1/Q-A.cpp.tk                       |  23
code/achan1058_1_1/source.cpp.tk                    |  39
code/achan1058_2_1/source.cpp.tk                    |  93
code/alanubi_0_1/a.cpp.tk                           |  50
code/alanubi_1_1/b.cpp.tk                           |  47
code/alanubi_2_1/c.cpp.tk                           |  145
code/AntiForest_0_1/q1.cpp.tk                       |  166
code/AntiForest_1_1/q2.cpp.tk                       |  87
code/AntiForest_2_1/q3.cpp.tk                       |  139
code/apiad_0_1/A.cpp.tk                             |  109
code/apiad_1_1/B.cpp.tk                             |  50
code/apiad_2_1/C.cpp.tk                             |  61
code/azaky_0_1/A.cpp.tk                             |  204
code/azaky_1_1/B.cpp.tk                             |  54
code/azaky_2_1/C.cpp.tk                             |  114
code/azariamuh_0_1/standing.cpp.tk                  |  70
code/azariamuh_1_1/pancake.cpp.tk                   |  65
code/azariamuh_2_1/dijkstra.cpp.tk                  |  43
code/bmerry_0_1/a.cpp.tk                            |  185
code/bmerry_1_1/b.cpp.tk                            |  88
code/bmerry_2_1/c.cpp.tk                            |  91
code/climpet_0_1/A.cpp.tk                           |  56
code/climpet_1_1/B.cpp.tk                           |  55
code/climpet_2_1/C.cpp.tk                           |  91
code/ctzsm_0_1/A.cpp.tk                             |  151
code/ctzsm_1_1/B.cpp.tk                             |  86
code/ctzsm_2_1/C.cpp.tk                             |  175
code/DanilC_0_1/problem.cpp.tk                      |  53
code/DanilC_1_1/problemB.cpp.tk                     |  71
code/DanilC_2_1/problemC.cpp.tk                     |  202
code/DEGwer_0_1/A.cpp.tk                            |  63
code/DEGwer_1_1/B.cpp.tk                            |  53
code/DEGwer_2_1/C.cpp.tk                            |  60
code/dmute_0_1/a.cpp.tk                             |  100
code/dmute_1_1/b.cpp.tk                             |  73
code/dmute_2_1/c2.cpp.tk                            |  108
code/fagu_0_1/A.cpp.tk                              |  32
code/fagu_1_1/B.cpp.tk                              |  25
code/fagu_2_1/C.cpp.tk                              |  70
code/FatalEagle_0_1/main.cpp.tk                     |  133
code/FatalEagle_1_1/main.cpp.tk                     |  123
code/FatalEagle_2_1/main.cpp.tk                     |  314
code/fullpower_0_1/A.cpp.tk                         |  116
code/fullpower_1_1/B.cpp.tk                         |  146
code/fullpower_2_1/C.cpp.tk                         |  200
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  25
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  29
code/ICastro_2_1/Dijkstra.cpp.tk                    |  212
code/ilackthatsuperpower_0_1/a.cpp.tk               |  154
code/ilackthatsuperpower_1_1/b.cpp.tk               |  152
code/ilackthatsuperpower_2_1/c.cpp.tk               |  201
code/iridescent_0_1/A.cpp.tk                        |  30
code/iridescent_1_1/B.cpp.tk                        |  49
code/iridescent_2_1/C.cpp.tk                        |  44
code/ishraq_0_1/main.cpp.tk                         |  71
code/ishraq_1_1/main.cpp.tk                         |  37
code/ishraq_2_1/main.cpp.tk                         |  124
code/JayXon_0_1/A.cpp.tk                            |  355
code/JayXon_1_1/B.cpp.tk                            |  43
code/JayXon_2_1/C.cpp.tk                            |  74
code/Josse_0_1/A.cpp.tk                             |  28
code/Josse_1_1/B.cpp.tk                             |  33
code/Josse_2_1/C.cpp.tk                             |  146
code/kcm1700_0_1/a.cpp.tk                           |  105
code/kcm1700_1_1/b.cpp.tk                           |  58
code/kcm1700_2_1/c.cpp.tk                           |  115
code/kevinsogo_0_1/a.cpp.tk                         |  101
code/kevinsogo_1_1/b.cpp.tk                         |  46
code/kevinsogo_2_1/c.cpp.tk                         |  109
code/ksun48_0_1/A.cpp.tk                            |  10
code/ksun48_1_1/B.cpp.tk                            |  10
code/ksun48_2_1/C.cpp.tk                            |  27
code/LazyAnna_0_1/1.cpp.tk                          |  29
code/LazyAnna_1_1/2-1.cpp.tk                        |  28
code/LazyAnna_2_1/3.cpp.tk                          |  63
code/Merkurev_0_1/A.cpp.tk                          |  122
code/Merkurev_1_1/B.cpp.tk                          |  128
code/Merkurev_2_1/C.cpp.tk                          |  132
code/mezei_0_1/main.cpp.tk                          |  80
code/mezei_1_1/main.cpp.tk                          |  47
code/mezei_2_1/main.cpp.tk                          |  134
code/Mister_0_1/a.cpp.tk                            |  53
code/Mister_1_1/b.cpp.tk                            |  39
code/Mister_2_1/c.cpp.tk                            |  69
code/namonakiacc_0_1/cpp.cpp.tk                     |  71
code/namonakiacc_1_1/cpp.cpp.tk                     |  58
code/namonakiacc_2_1/cpp.cpp.tk                     |  98
code/Nicolas16_0_1/main.cpp.tk                      |  26
code/Nicolas16_1_1/main.cpp.tk                      |  25
code/Nicolas16_2_1/main.cpp.tk                      |  149
code/pandamonium_0_1/a.cpp.tk                       |  98
code/pandamonium_1_1/b.cpp.tk                       |  85
code/pandamonium_2_1/c.cpp.tk                       |  83
code/pflueger_0_1/A.cpp.tk                          |  34
code/pflueger_1_1/B.cpp.tk                          |  39
code/pflueger_2_1/C.cpp.tk                          |  101
code/ponyopoppo_0_1/A.cpp.tk                        |  44
code/ponyopoppo_1_1/B.cpp.tk                        |  44
code/ponyopoppo_2_1/C.cpp.tk                        |  231
code/Ragnar_0_1/A.cpp.tk                            |  52
code/Ragnar_1_1/B-2.cpp.tk                          |  40
code/Ragnar_2_1/C.cpp.tk                            |  70
code/saffah_0_1/t.cpp.tk                            |  60
code/saffah_1_1/t.cpp.tk                            |  38
code/saffah_2_1/t.cpp.tk                            |  153
code/SamanSami_0_1/A.cpp.tk                         |  15
code/SamanSami_1_1/B.cpp.tk                         |  37
code/SamanSami_2_1/C.cpp.tk                         |  21
code/Savlik_0_1/code.cpp.tk                         |  70
code/Savlik_1_1/code.cpp.tk                         |  28
code/Savlik_2_1/code.cpp.tk                         |  116
code/shik_0_1/pa.cpp.tk                             |  172
code/shik_1_1/pb.cpp.tk                             |  111
code/shik_2_1/pc.cpp.tk                             |  161
code/simsa.st_0_1/A.cpp.tk                          |  41
code/simsa.st_1_1/B.cpp.tk                          |  39
code/simsa.st_2_1/C.cpp.tk                          |  146
code/SovietUnion_0_1/A.cpp.tk                       |  125
code/SovietUnion_1_1/B.cpp.tk                       |  110
code/SovietUnion_2_1/C.cpp.tk                       |  162
code/tailed_0_1/A.cpp.tk                            |  66
code/tailed_1_1/B.cpp.tk                            |  37
code/tailed_2_1/C.cpp.tk                            |  79
code/TheNatural_0_1/A.cpp.tk                        |  247
code/TheNatural_1_1/B.cpp.tk                        |  47
code/TheNatural_2_1/C.cpp.tk                        |  42
code/TrueBamboo_0_1/test.cpp.tk                     |  101
code/TrueBamboo_1_1/test.cpp.tk                     |  93
code/TrueBamboo_2_1/test.cpp.tk                     |  123
code/tur.turczyn_0_1/A.cpp.tk                       |  31
code/tur.turczyn_1_1/B.cpp.tk                       |  36
code/tur.turczyn_2_1/C.cpp.tk                       |  47
code/Tyg3R_0_1/A.cpp.tk                             |  26
code/Tyg3R_1_1/B.cpp.tk                             |  38
code/Tyg3R_2_1/C.cpp.tk                             |  37
code/UminchuR_0_1/main.cpp.tk                       |  95
code/UminchuR_1_1/main.cpp.tk                       |  108
code/UminchuR_2_1/main.cpp.tk                       |  153
code/wo..._0_1/a.cpp.tk                             |  62
code/wo..._1_1/b.cpp.tk                             |  54
code/wo..._2_1/c.cpp.tk                             |  121
code/yswtt_0_1/A.cpp.tk                             |  63
code/yswtt_1_1/B.cpp.tk                             |  33
code/yswtt_2_1/C.cpp.tk                             |  68
code/ZhSh_0_1/a.cpp.tk                              |  24
code/ZhSh_1_1/b.cpp.tk                              |  111
code/ZhSh_2_1/c.cpp.tk                              |  116
