Begin
Comparing:  code/SovietUnion_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  64
code/551100kk_1_1/B.cpp.tk                          |  54
code/551100kk_2_1/C.cpp.tk                          |  63
code/achan1058_0_1/Q-A.cpp.tk                       |  9
code/achan1058_1_1/source.cpp.tk                    |  14
code/achan1058_2_1/source.cpp.tk                    |  31
code/alanubi_0_1/a.cpp.tk                           |  48
code/alanubi_1_1/b.cpp.tk                           |  57
code/alanubi_2_1/c.cpp.tk                           |  102
code/AntiForest_0_1/q1.cpp.tk                       |  89
code/AntiForest_1_1/q2.cpp.tk                       |  71
code/AntiForest_2_1/q3.cpp.tk                       |  110
code/apiad_0_1/A.cpp.tk                             |  44
code/apiad_1_1/B.cpp.tk                             |  19
code/apiad_2_1/C.cpp.tk                             |  32
code/azaky_0_1/A.cpp.tk                             |  37
code/azaky_1_1/B.cpp.tk                             |  27
code/azaky_2_1/C.cpp.tk                             |  52
code/azariamuh_0_1/standing.cpp.tk                  |  19
code/azariamuh_1_1/pancake.cpp.tk                   |  29
code/azariamuh_2_1/dijkstra.cpp.tk                  |  18
code/bmerry_0_1/a.cpp.tk                            |  50
code/bmerry_1_1/b.cpp.tk                            |  56
code/bmerry_2_1/c.cpp.tk                            |  53
code/climpet_0_1/A.cpp.tk                           |  88
code/climpet_1_1/B.cpp.tk                           |  69
code/climpet_2_1/C.cpp.tk                           |  95
code/ctzsm_0_1/A.cpp.tk                             |  319
code/ctzsm_1_1/B.cpp.tk                             |  241
code/ctzsm_2_1/C.cpp.tk                             |  292
code/DanilC_0_1/problem.cpp.tk                      |  97
code/DanilC_1_1/problemB.cpp.tk                     |  95
code/DanilC_2_1/problemC.cpp.tk                     |  109
code/DEGwer_0_1/A.cpp.tk                            |  56
code/DEGwer_1_1/B.cpp.tk                            |  53
code/DEGwer_2_1/C.cpp.tk                            |  39
code/dmute_0_1/a.cpp.tk                             |  105
code/dmute_1_1/b.cpp.tk                             |  82
code/dmute_2_1/c2.cpp.tk                            |  97
code/fagu_0_1/A.cpp.tk                              |  21
code/fagu_1_1/B.cpp.tk                              |  21
code/fagu_2_1/C.cpp.tk                              |  40
code/FatalEagle_0_1/main.cpp.tk                     |  103
code/FatalEagle_1_1/main.cpp.tk                     |  104
code/FatalEagle_2_1/main.cpp.tk                     |  226
code/fullpower_0_1/A.cpp.tk                         |  176
code/fullpower_1_1/B.cpp.tk                         |  152
code/fullpower_2_1/C.cpp.tk                         |  183
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  50
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  42
code/ICastro_2_1/Dijkstra.cpp.tk                    |  99
code/ilackthatsuperpower_0_1/a.cpp.tk               |  110
code/ilackthatsuperpower_1_1/b.cpp.tk               |  74
code/ilackthatsuperpower_2_1/c.cpp.tk               |  88
code/iridescent_0_1/A.cpp.tk                        |  35
code/iridescent_1_1/B.cpp.tk                        |  59
code/iridescent_2_1/C.cpp.tk                        |  43
code/ishraq_0_1/main.cpp.tk                         |  29
code/ishraq_1_1/main.cpp.tk                         |  27
code/ishraq_2_1/main.cpp.tk                         |  51
code/JayXon_0_1/A.cpp.tk                            |  24
code/JayXon_1_1/B.cpp.tk                            |  44
code/JayXon_2_1/C.cpp.tk                            |  26
code/Josse_0_1/A.cpp.tk                             |  25
code/Josse_1_1/B.cpp.tk                             |  41
code/Josse_2_1/C.cpp.tk                             |  84
code/kcm1700_0_1/a.cpp.tk                           |  57
code/kcm1700_1_1/b.cpp.tk                           |  77
code/kcm1700_2_1/c.cpp.tk                           |  92
code/kevinsogo_0_1/a.cpp.tk                         |  20
code/kevinsogo_1_1/b.cpp.tk                         |  20
code/kevinsogo_2_1/c.cpp.tk                         |  55
code/ksun48_0_1/A.cpp.tk                            |  5
code/ksun48_1_1/B.cpp.tk                            |  5
code/ksun48_2_1/C.cpp.tk                            |  13
code/LazyAnna_0_1/1.cpp.tk                          |  76
code/LazyAnna_1_1/2-1.cpp.tk                        |  66
code/LazyAnna_2_1/3.cpp.tk                          |  52
code/Merkurev_0_1/A.cpp.tk                          |  101
code/Merkurev_1_1/B.cpp.tk                          |  102
code/Merkurev_2_1/C.cpp.tk                          |  114
code/mezei_0_1/main.cpp.tk                          |  78
code/mezei_1_1/main.cpp.tk                          |  54
code/mezei_2_1/main.cpp.tk                          |  93
code/Mister_0_1/a.cpp.tk                            |  99
code/Mister_1_1/b.cpp.tk                            |  96
code/Mister_2_1/c.cpp.tk                            |  159
code/namonakiacc_0_1/cpp.cpp.tk                     |  25
code/namonakiacc_1_1/cpp.cpp.tk                     |  22
code/namonakiacc_2_1/cpp.cpp.tk                     |  48
code/Nicolas16_0_1/main.cpp.tk                      |  33
code/Nicolas16_1_1/main.cpp.tk                      |  33
code/Nicolas16_2_1/main.cpp.tk                      |  127
code/pandamonium_0_1/a.cpp.tk                       |  103
code/pandamonium_1_1/b.cpp.tk                       |  80
code/pandamonium_2_1/c.cpp.tk                       |  77
code/pflueger_0_1/A.cpp.tk                          |  34
code/pflueger_1_1/B.cpp.tk                          |  42
code/pflueger_2_1/C.cpp.tk                          |  70
code/ponyopoppo_0_1/A.cpp.tk                        |  9
code/ponyopoppo_1_1/B.cpp.tk                        |  13
code/ponyopoppo_2_1/C.cpp.tk                        |  71
code/Ragnar_0_1/A.cpp.tk                            |  11
code/Ragnar_1_1/B-2.cpp.tk                          |  19
code/Ragnar_2_1/C.cpp.tk                            |  34
code/saffah_0_1/t.cpp.tk                            |  17
code/saffah_1_1/t.cpp.tk                            |  18
code/saffah_2_1/t.cpp.tk                            |  58
code/SamanSami_0_1/A.cpp.tk                         |  14
code/SamanSami_1_1/B.cpp.tk                         |  48
code/SamanSami_2_1/C.cpp.tk                         |  7
code/Savlik_0_1/code.cpp.tk                         |  24
code/Savlik_1_1/code.cpp.tk                         |  9
code/Savlik_2_1/code.cpp.tk                         |  44
code/shik_0_1/pa.cpp.tk                             |  44
code/shik_1_1/pb.cpp.tk                             |  40
code/shik_2_1/pc.cpp.tk                             |  72
code/simsa.st_0_1/A.cpp.tk                          |  18
code/simsa.st_1_1/B.cpp.tk                          |  18
code/simsa.st_2_1/C.cpp.tk                          |  57
code/SovietUnion_0_1/A.cpp.tk                       |  8051
code/SovietUnion_1_1/B.cpp.tk                       |  527
code/SovietUnion_2_1/C.cpp.tk                       |  109
code/tailed_0_1/A.cpp.tk                            |  20
code/tailed_1_1/B.cpp.tk                            |  32
code/tailed_2_1/C.cpp.tk                            |  26
code/TheNatural_0_1/A.cpp.tk                        |  51
code/TheNatural_1_1/B.cpp.tk                        |  53
code/TheNatural_2_1/C.cpp.tk                        |  27
code/TrueBamboo_0_1/test.cpp.tk                     |  27
code/TrueBamboo_1_1/test.cpp.tk                     |  29
code/TrueBamboo_2_1/test.cpp.tk                     |  44
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  12
code/tur.turczyn_2_1/C.cpp.tk                       |  17
code/Tyg3R_0_1/A.cpp.tk                             |  9
code/Tyg3R_1_1/B.cpp.tk                             |  16
code/Tyg3R_2_1/C.cpp.tk                             |  19
code/UminchuR_0_1/main.cpp.tk                       |  40
code/UminchuR_1_1/main.cpp.tk                       |  46
code/UminchuR_2_1/main.cpp.tk                       |  67
code/wo..._0_1/a.cpp.tk                             |  65
code/wo..._1_1/b.cpp.tk                             |  73
code/wo..._2_1/c.cpp.tk                             |  103
code/yswtt_0_1/A.cpp.tk                             |  89
code/yswtt_1_1/B.cpp.tk                             |  59
code/yswtt_2_1/C.cpp.tk                             |  66
code/ZhSh_0_1/a.cpp.tk                              |  71
code/ZhSh_1_1/b.cpp.tk                              |  100
code/ZhSh_2_1/c.cpp.tk                              |  85
