Begin
Comparing:  code/TheNatural_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  20
code/551100kk_1_1/B.cpp.tk                          |  71
code/551100kk_2_1/C.cpp.tk                          |  39
code/achan1058_0_1/Q-A.cpp.tk                       |  9
code/achan1058_1_1/source.cpp.tk                    |  20
code/achan1058_2_1/source.cpp.tk                    |  28
code/alanubi_0_1/a.cpp.tk                           |  71
code/alanubi_1_1/b.cpp.tk                           |  99
code/alanubi_2_1/c.cpp.tk                           |  183
code/AntiForest_0_1/q1.cpp.tk                       |  13
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  42
code/apiad_0_1/A.cpp.tk                             |  14
code/apiad_1_1/B.cpp.tk                             |  17
code/apiad_2_1/C.cpp.tk                             |  21
code/azaky_0_1/A.cpp.tk                             |  10
code/azaky_1_1/B.cpp.tk                             |  19
code/azaky_2_1/C.cpp.tk                             |  32
code/azariamuh_0_1/standing.cpp.tk                  |  12
code/azariamuh_1_1/pancake.cpp.tk                   |  20
code/azariamuh_2_1/dijkstra.cpp.tk                  |  16
code/bmerry_0_1/a.cpp.tk                            |  84
code/bmerry_1_1/b.cpp.tk                            |  145
code/bmerry_2_1/c.cpp.tk                            |  79
code/climpet_0_1/A.cpp.tk                           |  52
code/climpet_1_1/B.cpp.tk                           |  62
code/climpet_2_1/C.cpp.tk                           |  84
code/ctzsm_0_1/A.cpp.tk                             |  38
code/ctzsm_1_1/B.cpp.tk                             |  59
code/ctzsm_2_1/C.cpp.tk                             |  90
code/DanilC_0_1/problem.cpp.tk                      |  64
code/DanilC_1_1/problemB.cpp.tk                     |  94
code/DanilC_2_1/problemC.cpp.tk                     |  80
code/DEGwer_0_1/A.cpp.tk                            |  81
code/DEGwer_1_1/B.cpp.tk                            |  101
code/DEGwer_2_1/C.cpp.tk                            |  54
code/dmute_0_1/a.cpp.tk                             |  63
code/dmute_1_1/b.cpp.tk                             |  116
code/dmute_2_1/c2.cpp.tk                            |  130
code/fagu_0_1/A.cpp.tk                              |  27
code/fagu_1_1/B.cpp.tk                              |  29
code/fagu_2_1/C.cpp.tk                              |  37
code/FatalEagle_0_1/main.cpp.tk                     |  68
code/FatalEagle_1_1/main.cpp.tk                     |  173
code/FatalEagle_2_1/main.cpp.tk                     |  329
code/fullpower_0_1/A.cpp.tk                         |  81
code/fullpower_1_1/B.cpp.tk                         |  167
code/fullpower_2_1/C.cpp.tk                         |  196
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  41
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  70
code/ICastro_2_1/Dijkstra.cpp.tk                    |  61
code/ilackthatsuperpower_0_1/a.cpp.tk               |  106
code/ilackthatsuperpower_1_1/b.cpp.tk               |  101
code/ilackthatsuperpower_2_1/c.cpp.tk               |  86
code/iridescent_0_1/A.cpp.tk                        |  65
code/iridescent_1_1/B.cpp.tk                        |  158
code/iridescent_2_1/C.cpp.tk                        |  114
code/ishraq_0_1/main.cpp.tk                         |  9
code/ishraq_1_1/main.cpp.tk                         |  34
code/ishraq_2_1/main.cpp.tk                         |  30
code/JayXon_0_1/A.cpp.tk                            |  30
code/JayXon_1_1/B.cpp.tk                            |  83
code/JayXon_2_1/C.cpp.tk                            |  18
code/Josse_0_1/A.cpp.tk                             |  64
code/Josse_1_1/B.cpp.tk                             |  126
code/Josse_2_1/C.cpp.tk                             |  144
code/kcm1700_0_1/a.cpp.tk                           |  69
code/kcm1700_1_1/b.cpp.tk                           |  338
code/kcm1700_2_1/c.cpp.tk                           |  114
code/kevinsogo_0_1/a.cpp.tk                         |  8
code/kevinsogo_1_1/b.cpp.tk                         |  22
code/kevinsogo_2_1/c.cpp.tk                         |  39
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  8
code/LazyAnna_0_1/1.cpp.tk                          |  44
code/LazyAnna_1_1/2-1.cpp.tk                        |  71
code/LazyAnna_2_1/3.cpp.tk                          |  31
code/Merkurev_0_1/A.cpp.tk                          |  94
code/Merkurev_1_1/B.cpp.tk                          |  125
code/Merkurev_2_1/C.cpp.tk                          |  116
code/mezei_0_1/main.cpp.tk                          |  100
code/mezei_1_1/main.cpp.tk                          |  96
code/mezei_2_1/main.cpp.tk                          |  119
code/Mister_0_1/a.cpp.tk                            |  30
code/Mister_1_1/b.cpp.tk                            |  50
code/Mister_2_1/c.cpp.tk                            |  61
code/namonakiacc_0_1/cpp.cpp.tk                     |  21
code/namonakiacc_1_1/cpp.cpp.tk                     |  22
code/namonakiacc_2_1/cpp.cpp.tk                     |  37
code/Nicolas16_0_1/main.cpp.tk                      |  31
code/Nicolas16_1_1/main.cpp.tk                      |  30
code/Nicolas16_2_1/main.cpp.tk                      |  166
code/pandamonium_0_1/a.cpp.tk                       |  73
code/pandamonium_1_1/b.cpp.tk                       |  123
code/pandamonium_2_1/c.cpp.tk                       |  86
code/pflueger_0_1/A.cpp.tk                          |  87
code/pflueger_1_1/B.cpp.tk                          |  120
code/pflueger_2_1/C.cpp.tk                          |  150
code/ponyopoppo_0_1/A.cpp.tk                        |  12
code/ponyopoppo_1_1/B.cpp.tk                        |  21
code/ponyopoppo_2_1/C.cpp.tk                        |  35
code/Ragnar_0_1/A.cpp.tk                            |  20
code/Ragnar_1_1/B-2.cpp.tk                          |  47
code/Ragnar_2_1/C.cpp.tk                            |  62
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  14
code/saffah_2_1/t.cpp.tk                            |  31
code/SamanSami_0_1/A.cpp.tk                         |  48
code/SamanSami_1_1/B.cpp.tk                         |  161
code/SamanSami_2_1/C.cpp.tk                         |  3
code/Savlik_0_1/code.cpp.tk                         |  42
code/Savlik_1_1/code.cpp.tk                         |  6
code/Savlik_2_1/code.cpp.tk                         |  31
code/shik_0_1/pa.cpp.tk                             |  28
code/shik_1_1/pb.cpp.tk                             |  28
code/shik_2_1/pc.cpp.tk                             |  50
code/simsa.st_0_1/A.cpp.tk                          |  8
code/simsa.st_1_1/B.cpp.tk                          |  12
code/simsa.st_2_1/C.cpp.tk                          |  25
code/SovietUnion_0_1/A.cpp.tk                       |  50
code/SovietUnion_1_1/B.cpp.tk                       |  85
code/SovietUnion_2_1/C.cpp.tk                       |  39
code/tailed_0_1/A.cpp.tk                            |  52
code/tailed_1_1/B.cpp.tk                            |  83
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  427
code/TheNatural_1_1/B.cpp.tk                        |  9774
code/TheNatural_2_1/C.cpp.tk                        |  191
code/TrueBamboo_0_1/test.cpp.tk                     |  32
code/TrueBamboo_1_1/test.cpp.tk                     |  77
code/TrueBamboo_2_1/test.cpp.tk                     |  46
code/tur.turczyn_0_1/A.cpp.tk                       |  13
code/tur.turczyn_1_1/B.cpp.tk                       |  19
code/tur.turczyn_2_1/C.cpp.tk                       |  21
code/Tyg3R_0_1/A.cpp.tk                             |  8
code/Tyg3R_1_1/B.cpp.tk                             |  16
code/Tyg3R_2_1/C.cpp.tk                             |  20
code/UminchuR_0_1/main.cpp.tk                       |  16
code/UminchuR_1_1/main.cpp.tk                       |  24
code/UminchuR_2_1/main.cpp.tk                       |  44
code/wo..._0_1/a.cpp.tk                             |  89
code/wo..._1_1/b.cpp.tk                             |  121
code/wo..._2_1/c.cpp.tk                             |  152
code/yswtt_0_1/A.cpp.tk                             |  45
code/yswtt_1_1/B.cpp.tk                             |  71
code/yswtt_2_1/C.cpp.tk                             |  60
code/ZhSh_0_1/a.cpp.tk                              |  49
code/ZhSh_1_1/b.cpp.tk                              |  98
code/ZhSh_2_1/c.cpp.tk                              |  62
