Begin
Comparing:  code/JayXon_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  296
code/551100kk_1_1/B.cpp.tk                          |  22
code/551100kk_2_1/C.cpp.tk                          |  31
code/achan1058_0_1/Q-A.cpp.tk                       |  9
code/achan1058_1_1/source.cpp.tk                    |  15
code/achan1058_2_1/source.cpp.tk                    |  27
code/alanubi_0_1/a.cpp.tk                           |  33
code/alanubi_1_1/b.cpp.tk                           |  27
code/alanubi_2_1/c.cpp.tk                           |  85
code/AntiForest_0_1/q1.cpp.tk                       |  67
code/AntiForest_1_1/q2.cpp.tk                       |  3
code/AntiForest_2_1/q3.cpp.tk                       |  32
code/apiad_0_1/A.cpp.tk                             |  23
code/apiad_1_1/B.cpp.tk                             |  14
code/apiad_2_1/C.cpp.tk                             |  22
code/azaky_0_1/A.cpp.tk                             |  130
code/azaky_1_1/B.cpp.tk                             |  12
code/azaky_2_1/C.cpp.tk                             |  33
code/azariamuh_0_1/standing.cpp.tk                  |  36
code/azariamuh_1_1/pancake.cpp.tk                   |  13
code/azariamuh_2_1/dijkstra.cpp.tk                  |  13
code/bmerry_0_1/a.cpp.tk                            |  160
code/bmerry_1_1/b.cpp.tk                            |  46
code/bmerry_2_1/c.cpp.tk                            |  46
code/climpet_0_1/A.cpp.tk                           |  42
code/climpet_1_1/B.cpp.tk                           |  36
code/climpet_2_1/C.cpp.tk                           |  54
code/ctzsm_0_1/A.cpp.tk                             |  60
code/ctzsm_1_1/B.cpp.tk                             |  26
code/ctzsm_2_1/C.cpp.tk                             |  68
code/DanilC_0_1/problem.cpp.tk                      |  41
code/DanilC_1_1/problemB.cpp.tk                     |  49
code/DanilC_2_1/problemC.cpp.tk                     |  70
code/DEGwer_0_1/A.cpp.tk                            |  47
code/DEGwer_1_1/B.cpp.tk                            |  26
code/DEGwer_2_1/C.cpp.tk                            |  25
code/dmute_0_1/a.cpp.tk                             |  49
code/dmute_1_1/b.cpp.tk                             |  68
code/dmute_2_1/c2.cpp.tk                            |  80
code/fagu_0_1/A.cpp.tk                              |  8
code/fagu_1_1/B.cpp.tk                              |  8
code/fagu_2_1/C.cpp.tk                              |  23
code/FatalEagle_0_1/main.cpp.tk                     |  68
code/FatalEagle_1_1/main.cpp.tk                     |  67
code/FatalEagle_2_1/main.cpp.tk                     |  142
code/fullpower_0_1/A.cpp.tk                         |  69
code/fullpower_1_1/B.cpp.tk                         |  96
code/fullpower_2_1/C.cpp.tk                         |  139
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  26
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  26
code/ICastro_2_1/Dijkstra.cpp.tk                    |  65
code/ilackthatsuperpower_0_1/a.cpp.tk               |  89
code/ilackthatsuperpower_1_1/b.cpp.tk               |  73
code/ilackthatsuperpower_2_1/c.cpp.tk               |  74
code/iridescent_0_1/A.cpp.tk                        |  32
code/iridescent_1_1/B.cpp.tk                        |  60
code/iridescent_2_1/C.cpp.tk                        |  43
code/ishraq_0_1/main.cpp.tk                         |  16
code/ishraq_1_1/main.cpp.tk                         |  13
code/ishraq_2_1/main.cpp.tk                         |  32
code/JayXon_0_1/A.cpp.tk                            |  3142
code/JayXon_1_1/B.cpp.tk                            |  83
code/JayXon_2_1/C.cpp.tk                            |  35
code/Josse_0_1/A.cpp.tk                             |  28
code/Josse_1_1/B.cpp.tk                             |  31
code/Josse_2_1/C.cpp.tk                             |  69
code/kcm1700_0_1/a.cpp.tk                           |  94
code/kcm1700_1_1/b.cpp.tk                           |  57
code/kcm1700_2_1/c.cpp.tk                           |  64
code/kevinsogo_0_1/a.cpp.tk                         |  62
code/kevinsogo_1_1/b.cpp.tk                         |  10
code/kevinsogo_2_1/c.cpp.tk                         |  33
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  9
code/LazyAnna_0_1/1.cpp.tk                          |  30
code/LazyAnna_1_1/2-1.cpp.tk                        |  28
code/LazyAnna_2_1/3.cpp.tk                          |  29
code/Merkurev_0_1/A.cpp.tk                          |  79
code/Merkurev_1_1/B.cpp.tk                          |  49
code/Merkurev_2_1/C.cpp.tk                          |  68
code/mezei_0_1/main.cpp.tk                          |  81
code/mezei_1_1/main.cpp.tk                          |  40
code/mezei_2_1/main.cpp.tk                          |  65
code/Mister_0_1/a.cpp.tk                            |  33
code/Mister_1_1/b.cpp.tk                            |  28
code/Mister_2_1/c.cpp.tk                            |  40
code/namonakiacc_0_1/cpp.cpp.tk                     |  24
code/namonakiacc_1_1/cpp.cpp.tk                     |  16
code/namonakiacc_2_1/cpp.cpp.tk                     |  34
code/Nicolas16_0_1/main.cpp.tk                      |  23
code/Nicolas16_1_1/main.cpp.tk                      |  23
code/Nicolas16_2_1/main.cpp.tk                      |  108
code/pandamonium_0_1/a.cpp.tk                       |  48
code/pandamonium_1_1/b.cpp.tk                       |  50
code/pandamonium_2_1/c.cpp.tk                       |  46
code/pflueger_0_1/A.cpp.tk                          |  44
code/pflueger_1_1/B.cpp.tk                          |  41
code/pflueger_2_1/C.cpp.tk                          |  69
code/ponyopoppo_0_1/A.cpp.tk                        |  32
code/ponyopoppo_1_1/B.cpp.tk                        |  13
code/ponyopoppo_2_1/C.cpp.tk                        |  53
code/Ragnar_0_1/A.cpp.tk                            |  37
code/Ragnar_1_1/B-2.cpp.tk                          |  18
code/Ragnar_2_1/C.cpp.tk                            |  42
code/saffah_0_1/t.cpp.tk                            |  27
code/saffah_1_1/t.cpp.tk                            |  8
code/saffah_2_1/t.cpp.tk                            |  37
code/SamanSami_0_1/A.cpp.tk                         |  19
code/SamanSami_1_1/B.cpp.tk                         |  39
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  57
code/Savlik_1_1/code.cpp.tk                         |  6
code/Savlik_2_1/code.cpp.tk                         |  39
code/shik_0_1/pa.cpp.tk                             |  91
code/shik_1_1/pb.cpp.tk                             |  35
code/shik_2_1/pc.cpp.tk                             |  55
code/simsa.st_0_1/A.cpp.tk                          |  14
code/simsa.st_1_1/B.cpp.tk                          |  7
code/simsa.st_2_1/C.cpp.tk                          |  32
code/SovietUnion_0_1/A.cpp.tk                       |  39
code/SovietUnion_1_1/B.cpp.tk                       |  39
code/SovietUnion_2_1/C.cpp.tk                       |  41
code/tailed_0_1/A.cpp.tk                            |  65
code/tailed_1_1/B.cpp.tk                            |  32
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  285
code/TheNatural_1_1/B.cpp.tk                        |  51
code/TheNatural_2_1/C.cpp.tk                        |  34
code/TrueBamboo_0_1/test.cpp.tk                     |  35
code/TrueBamboo_1_1/test.cpp.tk                     |  25
code/TrueBamboo_2_1/test.cpp.tk                     |  37
code/tur.turczyn_0_1/A.cpp.tk                       |  60
code/tur.turczyn_1_1/B.cpp.tk                       |  15
code/tur.turczyn_2_1/C.cpp.tk                       |  23
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  10
code/Tyg3R_2_1/C.cpp.tk                             |  20
code/UminchuR_0_1/main.cpp.tk                       |  23
code/UminchuR_1_1/main.cpp.tk                       |  16
code/UminchuR_2_1/main.cpp.tk                       |  34
code/wo..._0_1/a.cpp.tk                             |  58
code/wo..._1_1/b.cpp.tk                             |  44
code/wo..._2_1/c.cpp.tk                             |  76
code/yswtt_0_1/A.cpp.tk                             |  57
code/yswtt_1_1/B.cpp.tk                             |  27
code/yswtt_2_1/C.cpp.tk                             |  39
code/ZhSh_0_1/a.cpp.tk                              |  29
code/ZhSh_1_1/b.cpp.tk                              |  60
code/ZhSh_2_1/c.cpp.tk                              |  58
