Begin
Comparing:  code/ZhSh_1_1/b.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  13
code/551100kk_1_1/B.cpp.tk                          |  21
code/551100kk_2_1/C.cpp.tk                          |  34
code/achan1058_0_1/Q-A.cpp.tk                       |  9
code/achan1058_1_1/source.cpp.tk                    |  33
code/achan1058_2_1/source.cpp.tk                    |  58
code/alanubi_0_1/a.cpp.tk                           |  17
code/alanubi_1_1/b.cpp.tk                           |  26
code/alanubi_2_1/c.cpp.tk                           |  81
code/AntiForest_0_1/q1.cpp.tk                       |  14
code/AntiForest_1_1/q2.cpp.tk                       |  6
code/AntiForest_2_1/q3.cpp.tk                       |  50
code/apiad_0_1/A.cpp.tk                             |  16
code/apiad_1_1/B.cpp.tk                             |  23
code/apiad_2_1/C.cpp.tk                             |  25
code/azaky_0_1/A.cpp.tk                             |  18
code/azaky_1_1/B.cpp.tk                             |  26
code/azaky_2_1/C.cpp.tk                             |  52
code/azariamuh_0_1/standing.cpp.tk                  |  11
code/azariamuh_1_1/pancake.cpp.tk                   |  24
code/azariamuh_2_1/dijkstra.cpp.tk                  |  20
code/bmerry_0_1/a.cpp.tk                            |  51
code/bmerry_1_1/b.cpp.tk                            |  64
code/bmerry_2_1/c.cpp.tk                            |  60
code/climpet_0_1/A.cpp.tk                           |  49
code/climpet_1_1/B.cpp.tk                           |  57
code/climpet_2_1/C.cpp.tk                           |  77
code/ctzsm_0_1/A.cpp.tk                             |  26
code/ctzsm_1_1/B.cpp.tk                             |  32
code/ctzsm_2_1/C.cpp.tk                             |  86
code/DanilC_0_1/problem.cpp.tk                      |  45
code/DanilC_1_1/problemB.cpp.tk                     |  63
code/DanilC_2_1/problemC.cpp.tk                     |  104
code/DEGwer_0_1/A.cpp.tk                            |  25
code/DEGwer_1_1/B.cpp.tk                            |  37
code/DEGwer_2_1/C.cpp.tk                            |  27
code/dmute_0_1/a.cpp.tk                             |  15
code/dmute_1_1/b.cpp.tk                             |  30
code/dmute_2_1/c2.cpp.tk                            |  52
code/fagu_0_1/A.cpp.tk                              |  10
code/fagu_1_1/B.cpp.tk                              |  10
code/fagu_2_1/C.cpp.tk                              |  33
code/FatalEagle_0_1/main.cpp.tk                     |  19
code/FatalEagle_1_1/main.cpp.tk                     |  35
code/FatalEagle_2_1/main.cpp.tk                     |  161
code/fullpower_0_1/A.cpp.tk                         |  29
code/fullpower_1_1/B.cpp.tk                         |  47
code/fullpower_2_1/C.cpp.tk                         |  84
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  21
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  43
code/ICastro_2_1/Dijkstra.cpp.tk                    |  85
code/ilackthatsuperpower_0_1/a.cpp.tk               |  115
code/ilackthatsuperpower_1_1/b.cpp.tk               |  114
code/ilackthatsuperpower_2_1/c.cpp.tk               |  138
code/iridescent_0_1/A.cpp.tk                        |  20
code/iridescent_1_1/B.cpp.tk                        |  39
code/iridescent_2_1/C.cpp.tk                        |  30
code/ishraq_0_1/main.cpp.tk                         |  9
code/ishraq_1_1/main.cpp.tk                         |  20
code/ishraq_2_1/main.cpp.tk                         |  63
code/JayXon_0_1/A.cpp.tk                            |  11
code/JayXon_1_1/B.cpp.tk                            |  28
code/JayXon_2_1/C.cpp.tk                            |  34
code/Josse_0_1/A.cpp.tk                             |  20
code/Josse_1_1/B.cpp.tk                             |  36
code/Josse_2_1/C.cpp.tk                             |  91
code/kcm1700_0_1/a.cpp.tk                           |  15
code/kcm1700_1_1/b.cpp.tk                           |  27
code/kcm1700_2_1/c.cpp.tk                           |  60
code/kevinsogo_0_1/a.cpp.tk                         |  11
code/kevinsogo_1_1/b.cpp.tk                         |  23
code/kevinsogo_2_1/c.cpp.tk                         |  52
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  10
code/LazyAnna_0_1/1.cpp.tk                          |  23
code/LazyAnna_1_1/2-1.cpp.tk                        |  32
code/LazyAnna_2_1/3.cpp.tk                          |  37
code/Merkurev_0_1/A.cpp.tk                          |  25
code/Merkurev_1_1/B.cpp.tk                          |  47
code/Merkurev_2_1/C.cpp.tk                          |  44
code/mezei_0_1/main.cpp.tk                          |  24
code/mezei_1_1/main.cpp.tk                          |  26
code/mezei_2_1/main.cpp.tk                          |  60
code/Mister_0_1/a.cpp.tk                            |  24
code/Mister_1_1/b.cpp.tk                            |  36
code/Mister_2_1/c.cpp.tk                            |  43
code/namonakiacc_0_1/cpp.cpp.tk                     |  27
code/namonakiacc_1_1/cpp.cpp.tk                     |  30
code/namonakiacc_2_1/cpp.cpp.tk                     |  50
code/Nicolas16_0_1/main.cpp.tk                      |  8
code/Nicolas16_1_1/main.cpp.tk                      |  8
code/Nicolas16_2_1/main.cpp.tk                      |  70
code/pandamonium_0_1/a.cpp.tk                       |  16
code/pandamonium_1_1/b.cpp.tk                       |  40
code/pandamonium_2_1/c.cpp.tk                       |  27
code/pflueger_0_1/A.cpp.tk                          |  22
code/pflueger_1_1/B.cpp.tk                          |  43
code/pflueger_2_1/C.cpp.tk                          |  62
code/ponyopoppo_0_1/A.cpp.tk                        |  14
code/ponyopoppo_1_1/B.cpp.tk                        |  32
code/ponyopoppo_2_1/C.cpp.tk                        |  112
code/Ragnar_0_1/A.cpp.tk                            |  20
code/Ragnar_1_1/B-2.cpp.tk                          |  33
code/Ragnar_2_1/C.cpp.tk                            |  48
code/saffah_0_1/t.cpp.tk                            |  10
code/saffah_1_1/t.cpp.tk                            |  14
code/saffah_2_1/t.cpp.tk                            |  68
code/SamanSami_0_1/A.cpp.tk                         |  8
code/SamanSami_1_1/B.cpp.tk                         |  33
code/SamanSami_2_1/C.cpp.tk                         |  10
code/Savlik_0_1/code.cpp.tk                         |  14
code/Savlik_1_1/code.cpp.tk                         |  13
code/Savlik_2_1/code.cpp.tk                         |  61
code/shik_0_1/pa.cpp.tk                             |  60
code/shik_1_1/pb.cpp.tk                             |  62
code/shik_2_1/pc.cpp.tk                             |  88
code/simsa.st_0_1/A.cpp.tk                          |  10
code/simsa.st_1_1/B.cpp.tk                          |  16
code/simsa.st_2_1/C.cpp.tk                          |  69
code/SovietUnion_0_1/A.cpp.tk                       |  30
code/SovietUnion_1_1/B.cpp.tk                       |  43
code/SovietUnion_2_1/C.cpp.tk                       |  65
code/tailed_0_1/A.cpp.tk                            |  23
code/tailed_1_1/B.cpp.tk                            |  37
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  23
code/TheNatural_1_1/B.cpp.tk                        |  30
code/TheNatural_2_1/C.cpp.tk                        |  24
code/TrueBamboo_0_1/test.cpp.tk                     |  14
code/TrueBamboo_1_1/test.cpp.tk                     |  23
code/TrueBamboo_2_1/test.cpp.tk                     |  41
code/tur.turczyn_0_1/A.cpp.tk                       |  18
code/tur.turczyn_1_1/B.cpp.tk                       |  30
code/tur.turczyn_2_1/C.cpp.tk                       |  34
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  19
code/Tyg3R_2_1/C.cpp.tk                             |  17
code/UminchuR_0_1/main.cpp.tk                       |  25
code/UminchuR_1_1/main.cpp.tk                       |  35
code/UminchuR_2_1/main.cpp.tk                       |  54
code/wo..._0_1/a.cpp.tk                             |  26
code/wo..._1_1/b.cpp.tk                             |  32
code/wo..._2_1/c.cpp.tk                             |  64
code/yswtt_0_1/A.cpp.tk                             |  42
code/yswtt_1_1/B.cpp.tk                             |  43
code/yswtt_2_1/C.cpp.tk                             |  49
code/ZhSh_0_1/a.cpp.tk                              |  49
code/ZhSh_1_1/b.cpp.tk                              |  92343
code/ZhSh_2_1/c.cpp.tk                              |  6156
