Begin
Comparing:  code/mezei_1_1/main.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  21
code/551100kk_1_1/B.cpp.tk                          |  53
code/551100kk_2_1/C.cpp.tk                          |  55
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  16
code/achan1058_2_1/source.cpp.tk                    |  31
code/alanubi_0_1/a.cpp.tk                           |  67
code/alanubi_1_1/b.cpp.tk                           |  113
code/alanubi_2_1/c.cpp.tk                           |  199
code/AntiForest_0_1/q1.cpp.tk                       |  17
code/AntiForest_1_1/q2.cpp.tk                       |  8
code/AntiForest_2_1/q3.cpp.tk                       |  51
code/apiad_0_1/A.cpp.tk                             |  16
code/apiad_1_1/B.cpp.tk                             |  26
code/apiad_2_1/C.cpp.tk                             |  27
code/azaky_0_1/A.cpp.tk                             |  17
code/azaky_1_1/B.cpp.tk                             |  33
code/azaky_2_1/C.cpp.tk                             |  44
code/azariamuh_0_1/standing.cpp.tk                  |  16
code/azariamuh_1_1/pancake.cpp.tk                   |  29
code/azariamuh_2_1/dijkstra.cpp.tk                  |  20
code/bmerry_0_1/a.cpp.tk                            |  68
code/bmerry_1_1/b.cpp.tk                            |  125
code/bmerry_2_1/c.cpp.tk                            |  79
code/climpet_0_1/A.cpp.tk                           |  37
code/climpet_1_1/B.cpp.tk                           |  57
code/climpet_2_1/C.cpp.tk                           |  68
code/ctzsm_0_1/A.cpp.tk                             |  44
code/ctzsm_1_1/B.cpp.tk                             |  75
code/ctzsm_2_1/C.cpp.tk                             |  116
code/DanilC_0_1/problem.cpp.tk                      |  48
code/DanilC_1_1/problemB.cpp.tk                     |  87
code/DanilC_2_1/problemC.cpp.tk                     |  92
code/DEGwer_0_1/A.cpp.tk                            |  149
code/DEGwer_1_1/B.cpp.tk                            |  197
code/DEGwer_2_1/C.cpp.tk                            |  129
code/dmute_0_1/a.cpp.tk                             |  63
code/dmute_1_1/b.cpp.tk                             |  103
code/dmute_2_1/c2.cpp.tk                            |  127
code/fagu_0_1/A.cpp.tk                              |  49
code/fagu_1_1/B.cpp.tk                              |  49
code/fagu_2_1/C.cpp.tk                              |  66
code/FatalEagle_0_1/main.cpp.tk                     |  68
code/FatalEagle_1_1/main.cpp.tk                     |  144
code/FatalEagle_2_1/main.cpp.tk                     |  373
code/fullpower_0_1/A.cpp.tk                         |  90
code/fullpower_1_1/B.cpp.tk                         |  173
code/fullpower_2_1/C.cpp.tk                         |  176
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  27
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  63
code/ICastro_2_1/Dijkstra.cpp.tk                    |  73
code/ilackthatsuperpower_0_1/a.cpp.tk               |  103
code/ilackthatsuperpower_1_1/b.cpp.tk               |  119
code/ilackthatsuperpower_2_1/c.cpp.tk               |  111
code/iridescent_0_1/A.cpp.tk                        |  43
code/iridescent_1_1/B.cpp.tk                        |  95
code/iridescent_2_1/C.cpp.tk                        |  79
code/ishraq_0_1/main.cpp.tk                         |  14
code/ishraq_1_1/main.cpp.tk                         |  46
code/ishraq_2_1/main.cpp.tk                         |  48
code/JayXon_0_1/A.cpp.tk                            |  24
code/JayXon_1_1/B.cpp.tk                            |  77
code/JayXon_2_1/C.cpp.tk                            |  22
code/Josse_0_1/A.cpp.tk                             |  56
code/Josse_1_1/B.cpp.tk                             |  348
code/Josse_2_1/C.cpp.tk                             |  161
code/kcm1700_0_1/a.cpp.tk                           |  82
code/kcm1700_1_1/b.cpp.tk                           |  143
code/kcm1700_2_1/c.cpp.tk                           |  131
code/kevinsogo_0_1/a.cpp.tk                         |  14
code/kevinsogo_1_1/b.cpp.tk                         |  27
code/kevinsogo_2_1/c.cpp.tk                         |  46
code/ksun48_0_1/A.cpp.tk                            |  6
code/ksun48_1_1/B.cpp.tk                            |  6
code/ksun48_2_1/C.cpp.tk                            |  13
code/LazyAnna_0_1/1.cpp.tk                          |  28
code/LazyAnna_1_1/2-1.cpp.tk                        |  50
code/LazyAnna_2_1/3.cpp.tk                          |  31
code/Merkurev_0_1/A.cpp.tk                          |  88
code/Merkurev_1_1/B.cpp.tk                          |  163
code/Merkurev_2_1/C.cpp.tk                          |  120
code/mezei_0_1/main.cpp.tk                          |  340
code/mezei_1_1/main.cpp.tk                          |  9403
code/mezei_2_1/main.cpp.tk                          |  370
code/Mister_0_1/a.cpp.tk                            |  39
code/Mister_1_1/b.cpp.tk                            |  76
code/Mister_2_1/c.cpp.tk                            |  67
code/namonakiacc_0_1/cpp.cpp.tk                     |  22
code/namonakiacc_1_1/cpp.cpp.tk                     |  29
code/namonakiacc_2_1/cpp.cpp.tk                     |  41
code/Nicolas16_0_1/main.cpp.tk                      |  43
code/Nicolas16_1_1/main.cpp.tk                      |  44
code/Nicolas16_2_1/main.cpp.tk                      |  165
code/pandamonium_0_1/a.cpp.tk                       |  69
code/pandamonium_1_1/b.cpp.tk                       |  184
code/pandamonium_2_1/c.cpp.tk                       |  92
code/pflueger_0_1/A.cpp.tk                          |  52
code/pflueger_1_1/B.cpp.tk                          |  230
code/pflueger_2_1/C.cpp.tk                          |  119
code/ponyopoppo_0_1/A.cpp.tk                        |  9
code/ponyopoppo_1_1/B.cpp.tk                        |  19
code/ponyopoppo_2_1/C.cpp.tk                        |  64
code/Ragnar_0_1/A.cpp.tk                            |  12
code/Ragnar_1_1/B-2.cpp.tk                          |  41
code/Ragnar_2_1/C.cpp.tk                            |  39
code/saffah_0_1/t.cpp.tk                            |  14
code/saffah_1_1/t.cpp.tk                            |  23
code/saffah_2_1/t.cpp.tk                            |  46
code/SamanSami_0_1/A.cpp.tk                         |  20
code/SamanSami_1_1/B.cpp.tk                         |  97
code/SamanSami_2_1/C.cpp.tk                         |  6
code/Savlik_0_1/code.cpp.tk                         |  26
code/Savlik_1_1/code.cpp.tk                         |  12
code/Savlik_2_1/code.cpp.tk                         |  41
code/shik_0_1/pa.cpp.tk                             |  37
code/shik_1_1/pb.cpp.tk                             |  41
code/shik_2_1/pc.cpp.tk                             |  61
code/simsa.st_0_1/A.cpp.tk                          |  13
code/simsa.st_1_1/B.cpp.tk                          |  24
code/simsa.st_2_1/C.cpp.tk                          |  48
code/SovietUnion_0_1/A.cpp.tk                       |  53
code/SovietUnion_1_1/B.cpp.tk                       |  74
code/SovietUnion_2_1/C.cpp.tk                       |  47
code/tailed_0_1/A.cpp.tk                            |  26
code/tailed_1_1/B.cpp.tk                            |  58
code/tailed_2_1/C.cpp.tk                            |  31
code/TheNatural_0_1/A.cpp.tk                        |  62
code/TheNatural_1_1/B.cpp.tk                        |  98
code/TheNatural_2_1/C.cpp.tk                        |  43
code/TrueBamboo_0_1/test.cpp.tk                     |  29
code/TrueBamboo_1_1/test.cpp.tk                     |  46
code/TrueBamboo_2_1/test.cpp.tk                     |  51
code/tur.turczyn_0_1/A.cpp.tk                       |  10
code/tur.turczyn_1_1/B.cpp.tk                       |  16
code/tur.turczyn_2_1/C.cpp.tk                       |  18
code/Tyg3R_0_1/A.cpp.tk                             |  10
code/Tyg3R_1_1/B.cpp.tk                             |  15
code/Tyg3R_2_1/C.cpp.tk                             |  17
code/UminchuR_0_1/main.cpp.tk                       |  19
code/UminchuR_1_1/main.cpp.tk                       |  33
code/UminchuR_2_1/main.cpp.tk                       |  47
code/wo..._0_1/a.cpp.tk                             |  89
code/wo..._1_1/b.cpp.tk                             |  112
code/wo..._2_1/c.cpp.tk                             |  157
code/yswtt_0_1/A.cpp.tk                             |  26
code/yswtt_1_1/B.cpp.tk                             |  56
code/yswtt_2_1/C.cpp.tk                             |  43
code/ZhSh_0_1/a.cpp.tk                              |  28
code/ZhSh_1_1/b.cpp.tk                              |  81
code/ZhSh_2_1/c.cpp.tk                              |  60
