Begin
Comparing:  code/DEGwer_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  21
code/551100kk_1_1/B.cpp.tk                          |  51
code/551100kk_2_1/C.cpp.tk                          |  63
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  26
code/achan1058_2_1/source.cpp.tk                    |  47
code/alanubi_0_1/a.cpp.tk                           |  65
code/alanubi_1_1/b.cpp.tk                           |  157
code/alanubi_2_1/c.cpp.tk                           |  194
code/AntiForest_0_1/q1.cpp.tk                       |  23
code/AntiForest_1_1/q2.cpp.tk                       |  13
code/AntiForest_2_1/q3.cpp.tk                       |  65
code/apiad_0_1/A.cpp.tk                             |  19
code/apiad_1_1/B.cpp.tk                             |  33
code/apiad_2_1/C.cpp.tk                             |  32
code/azaky_0_1/A.cpp.tk                             |  23
code/azaky_1_1/B.cpp.tk                             |  44
code/azaky_2_1/C.cpp.tk                             |  59
code/azariamuh_0_1/standing.cpp.tk                  |  23
code/azariamuh_1_1/pancake.cpp.tk                   |  39
code/azariamuh_2_1/dijkstra.cpp.tk                  |  25
code/bmerry_0_1/a.cpp.tk                            |  82
code/bmerry_1_1/b.cpp.tk                            |  128
code/bmerry_2_1/c.cpp.tk                            |  97
code/climpet_0_1/A.cpp.tk                           |  43
code/climpet_1_1/B.cpp.tk                           |  75
code/climpet_2_1/C.cpp.tk                           |  80
code/ctzsm_0_1/A.cpp.tk                             |  43
code/ctzsm_1_1/B.cpp.tk                             |  85
code/ctzsm_2_1/C.cpp.tk                             |  115
code/DanilC_0_1/problem.cpp.tk                      |  50
code/DanilC_1_1/problemB.cpp.tk                     |  93
code/DanilC_2_1/problemC.cpp.tk                     |  110
code/DEGwer_0_1/A.cpp.tk                            |  1122
code/DEGwer_1_1/B.cpp.tk                            |  10804
code/DEGwer_2_1/C.cpp.tk                            |  386
code/dmute_0_1/a.cpp.tk                             |  40
code/dmute_1_1/b.cpp.tk                             |  82
code/dmute_2_1/c2.cpp.tk                            |  103
code/fagu_0_1/A.cpp.tk                              |  47
code/fagu_1_1/B.cpp.tk                              |  47
code/fagu_2_1/C.cpp.tk                              |  70
code/FatalEagle_0_1/main.cpp.tk                     |  49
code/FatalEagle_1_1/main.cpp.tk                     |  106
code/FatalEagle_2_1/main.cpp.tk                     |  361
code/fullpower_0_1/A.cpp.tk                         |  58
code/fullpower_1_1/B.cpp.tk                         |  120
code/fullpower_2_1/C.cpp.tk                         |  139
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  30
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  68
code/ICastro_2_1/Dijkstra.cpp.tk                    |  103
code/ilackthatsuperpower_0_1/a.cpp.tk               |  111
code/ilackthatsuperpower_1_1/b.cpp.tk               |  115
code/ilackthatsuperpower_2_1/c.cpp.tk               |  127
code/iridescent_0_1/A.cpp.tk                        |  50
code/iridescent_1_1/B.cpp.tk                        |  125
code/iridescent_2_1/C.cpp.tk                        |  70
code/ishraq_0_1/main.cpp.tk                         |  18
code/ishraq_1_1/main.cpp.tk                         |  86
code/ishraq_2_1/main.cpp.tk                         |  65
code/JayXon_0_1/A.cpp.tk                            |  15
code/JayXon_1_1/B.cpp.tk                            |  80
code/JayXon_2_1/C.cpp.tk                            |  31
code/Josse_0_1/A.cpp.tk                             |  54
code/Josse_1_1/B.cpp.tk                             |  150
code/Josse_2_1/C.cpp.tk                             |  157
code/kcm1700_0_1/a.cpp.tk                           |  46
code/kcm1700_1_1/b.cpp.tk                           |  118
code/kcm1700_2_1/c.cpp.tk                           |  133
code/kevinsogo_0_1/a.cpp.tk                         |  20
code/kevinsogo_1_1/b.cpp.tk                         |  35
code/kevinsogo_2_1/c.cpp.tk                         |  53
code/ksun48_0_1/A.cpp.tk                            |  7
code/ksun48_1_1/B.cpp.tk                            |  7
code/ksun48_2_1/C.cpp.tk                            |  14
code/LazyAnna_0_1/1.cpp.tk                          |  27
code/LazyAnna_1_1/2-1.cpp.tk                        |  53
code/LazyAnna_2_1/3.cpp.tk                          |  33
code/Merkurev_0_1/A.cpp.tk                          |  59
code/Merkurev_1_1/B.cpp.tk                          |  137
code/Merkurev_2_1/C.cpp.tk                          |  102
code/mezei_0_1/main.cpp.tk                          |  142
code/mezei_1_1/main.cpp.tk                          |  191
code/mezei_2_1/main.cpp.tk                          |  232
code/Mister_0_1/a.cpp.tk                            |  35
code/Mister_1_1/b.cpp.tk                            |  69
code/Mister_2_1/c.cpp.tk                            |  63
code/namonakiacc_0_1/cpp.cpp.tk                     |  32
code/namonakiacc_1_1/cpp.cpp.tk                     |  38
code/namonakiacc_2_1/cpp.cpp.tk                     |  52
code/Nicolas16_0_1/main.cpp.tk                      |  24
code/Nicolas16_1_1/main.cpp.tk                      |  23
code/Nicolas16_2_1/main.cpp.tk                      |  130
code/pandamonium_0_1/a.cpp.tk                       |  43
code/pandamonium_1_1/b.cpp.tk                       |  138
code/pandamonium_2_1/c.cpp.tk                       |  72
code/pflueger_0_1/A.cpp.tk                          |  34
code/pflueger_1_1/B.cpp.tk                          |  101
code/pflueger_2_1/C.cpp.tk                          |  118
code/ponyopoppo_0_1/A.cpp.tk                        |  12
code/ponyopoppo_1_1/B.cpp.tk                        |  26
code/ponyopoppo_2_1/C.cpp.tk                        |  91
code/Ragnar_0_1/A.cpp.tk                            |  16
code/Ragnar_1_1/B-2.cpp.tk                          |  56
code/Ragnar_2_1/C.cpp.tk                            |  38
code/saffah_0_1/t.cpp.tk                            |  18
code/saffah_1_1/t.cpp.tk                            |  29
code/saffah_2_1/t.cpp.tk                            |  64
code/SamanSami_0_1/A.cpp.tk                         |  12
code/SamanSami_1_1/B.cpp.tk                         |  146
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  22
code/Savlik_1_1/code.cpp.tk                         |  15
code/Savlik_2_1/code.cpp.tk                         |  57
code/shik_0_1/pa.cpp.tk                             |  51
code/shik_1_1/pb.cpp.tk                             |  54
code/shik_2_1/pc.cpp.tk                             |  80
code/simsa.st_0_1/A.cpp.tk                          |  19
code/simsa.st_1_1/B.cpp.tk                          |  45
code/simsa.st_2_1/C.cpp.tk                          |  64
code/SovietUnion_0_1/A.cpp.tk                       |  50
code/SovietUnion_1_1/B.cpp.tk                       |  71
code/SovietUnion_2_1/C.cpp.tk                       |  58
code/tailed_0_1/A.cpp.tk                            |  19
code/tailed_1_1/B.cpp.tk                            |  76
code/tailed_2_1/C.cpp.tk                            |  31
code/TheNatural_0_1/A.cpp.tk                        |  41
code/TheNatural_1_1/B.cpp.tk                        |  99
code/TheNatural_2_1/C.cpp.tk                        |  33
code/TrueBamboo_0_1/test.cpp.tk                     |  27
code/TrueBamboo_1_1/test.cpp.tk                     |  54
code/TrueBamboo_2_1/test.cpp.tk                     |  54
code/tur.turczyn_0_1/A.cpp.tk                       |  13
code/tur.turczyn_1_1/B.cpp.tk                       |  22
code/tur.turczyn_2_1/C.cpp.tk                       |  23
code/Tyg3R_0_1/A.cpp.tk                             |  13
code/Tyg3R_1_1/B.cpp.tk                             |  22
code/Tyg3R_2_1/C.cpp.tk                             |  18
code/UminchuR_0_1/main.cpp.tk                       |  28
code/UminchuR_1_1/main.cpp.tk                       |  49
code/UminchuR_2_1/main.cpp.tk                       |  60
code/wo..._0_1/a.cpp.tk                             |  93
code/wo..._1_1/b.cpp.tk                             |  124
code/wo..._2_1/c.cpp.tk                             |  145
code/yswtt_0_1/A.cpp.tk                             |  26
code/yswtt_1_1/B.cpp.tk                             |  52
code/yswtt_2_1/C.cpp.tk                             |  56
code/ZhSh_0_1/a.cpp.tk                              |  28
code/ZhSh_1_1/b.cpp.tk                              |  111
code/ZhSh_2_1/c.cpp.tk                              |  69
