Begin
Comparing:  code/tailed_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  18
code/551100kk_1_1/B.cpp.tk                          |  52
code/551100kk_2_1/C.cpp.tk                          |  35
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  52
code/achan1058_2_1/source.cpp.tk                    |  53
code/alanubi_0_1/a.cpp.tk                           |  41
code/alanubi_1_1/b.cpp.tk                           |  51
code/alanubi_2_1/c.cpp.tk                           |  114
code/AntiForest_0_1/q1.cpp.tk                       |  14
code/AntiForest_1_1/q2.cpp.tk                       |  5
code/AntiForest_2_1/q3.cpp.tk                       |  51
code/apiad_0_1/A.cpp.tk                             |  16
code/apiad_1_1/B.cpp.tk                             |  30
code/apiad_2_1/C.cpp.tk                             |  25
code/azaky_0_1/A.cpp.tk                             |  15
code/azaky_1_1/B.cpp.tk                             |  30
code/azaky_2_1/C.cpp.tk                             |  47
code/azariamuh_0_1/standing.cpp.tk                  |  14
code/azariamuh_1_1/pancake.cpp.tk                   |  32
code/azariamuh_2_1/dijkstra.cpp.tk                  |  21
code/bmerry_0_1/a.cpp.tk                            |  67
code/bmerry_1_1/b.cpp.tk                            |  101
code/bmerry_2_1/c.cpp.tk                            |  73
code/climpet_0_1/A.cpp.tk                           |  54
code/climpet_1_1/B.cpp.tk                           |  65
code/climpet_2_1/C.cpp.tk                           |  84
code/ctzsm_0_1/A.cpp.tk                             |  30
code/ctzsm_1_1/B.cpp.tk                             |  89
code/ctzsm_2_1/C.cpp.tk                             |  85
code/DanilC_0_1/problem.cpp.tk                      |  59
code/DanilC_1_1/problemB.cpp.tk                     |  79
code/DanilC_2_1/problemC.cpp.tk                     |  112
code/DEGwer_0_1/A.cpp.tk                            |  52
code/DEGwer_1_1/B.cpp.tk                            |  96
code/DEGwer_2_1/C.cpp.tk                            |  34
code/dmute_0_1/a.cpp.tk                             |  42
code/dmute_1_1/b.cpp.tk                             |  94
code/dmute_2_1/c2.cpp.tk                            |  94
code/fagu_0_1/A.cpp.tk                              |  13
code/fagu_1_1/B.cpp.tk                              |  13
code/fagu_2_1/C.cpp.tk                              |  34
code/FatalEagle_0_1/main.cpp.tk                     |  48
code/FatalEagle_1_1/main.cpp.tk                     |  88
code/FatalEagle_2_1/main.cpp.tk                     |  236
code/fullpower_0_1/A.cpp.tk                         |  66
code/fullpower_1_1/B.cpp.tk                         |  127
code/fullpower_2_1/C.cpp.tk                         |  158
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  36
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  63
code/ICastro_2_1/Dijkstra.cpp.tk                    |  77
code/ilackthatsuperpower_0_1/a.cpp.tk               |  107
code/ilackthatsuperpower_1_1/b.cpp.tk               |  104
code/ilackthatsuperpower_2_1/c.cpp.tk               |  108
code/iridescent_0_1/A.cpp.tk                        |  75
code/iridescent_1_1/B.cpp.tk                        |  272
code/iridescent_2_1/C.cpp.tk                        |  95
code/ishraq_0_1/main.cpp.tk                         |  12
code/ishraq_1_1/main.cpp.tk                         |  88
code/ishraq_2_1/main.cpp.tk                         |  60
code/JayXon_0_1/A.cpp.tk                            |  23
code/JayXon_1_1/B.cpp.tk                            |  60
code/JayXon_2_1/C.cpp.tk                            |  31
code/Josse_0_1/A.cpp.tk                             |  39
code/Josse_1_1/B.cpp.tk                             |  96
code/Josse_2_1/C.cpp.tk                             |  109
code/kcm1700_0_1/a.cpp.tk                           |  45
code/kcm1700_1_1/b.cpp.tk                           |  110
code/kcm1700_2_1/c.cpp.tk                           |  105
code/kevinsogo_0_1/a.cpp.tk                         |  14
code/kevinsogo_1_1/b.cpp.tk                         |  36
code/kevinsogo_2_1/c.cpp.tk                         |  55
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  35
code/LazyAnna_1_1/2-1.cpp.tk                        |  53
code/LazyAnna_2_1/3.cpp.tk                          |  48
code/Merkurev_0_1/A.cpp.tk                          |  68
code/Merkurev_1_1/B.cpp.tk                          |  69
code/Merkurev_2_1/C.cpp.tk                          |  84
code/mezei_0_1/main.cpp.tk                          |  69
code/mezei_1_1/main.cpp.tk                          |  72
code/mezei_2_1/main.cpp.tk                          |  77
code/Mister_0_1/a.cpp.tk                            |  27
code/Mister_1_1/b.cpp.tk                            |  41
code/Mister_2_1/c.cpp.tk                            |  50
code/namonakiacc_0_1/cpp.cpp.tk                     |  24
code/namonakiacc_1_1/cpp.cpp.tk                     |  32
code/namonakiacc_2_1/cpp.cpp.tk                     |  46
code/Nicolas16_0_1/main.cpp.tk                      |  24
code/Nicolas16_1_1/main.cpp.tk                      |  24
code/Nicolas16_2_1/main.cpp.tk                      |  124
code/pandamonium_0_1/a.cpp.tk                       |  45
code/pandamonium_1_1/b.cpp.tk                       |  68
code/pandamonium_2_1/c.cpp.tk                       |  58
code/pflueger_0_1/A.cpp.tk                          |  93
code/pflueger_1_1/B.cpp.tk                          |  146
code/pflueger_2_1/C.cpp.tk                          |  116
code/ponyopoppo_0_1/A.cpp.tk                        |  29
code/ponyopoppo_1_1/B.cpp.tk                        |  84
code/ponyopoppo_2_1/C.cpp.tk                        |  100
code/Ragnar_0_1/A.cpp.tk                            |  25
code/Ragnar_1_1/B-2.cpp.tk                          |  216
code/Ragnar_2_1/C.cpp.tk                            |  95
code/saffah_0_1/t.cpp.tk                            |  12
code/saffah_1_1/t.cpp.tk                            |  23
code/saffah_2_1/t.cpp.tk                            |  50
code/SamanSami_0_1/A.cpp.tk                         |  38
code/SamanSami_1_1/B.cpp.tk                         |  188
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  31
code/Savlik_1_1/code.cpp.tk                         |  15
code/Savlik_2_1/code.cpp.tk                         |  58
code/shik_0_1/pa.cpp.tk                             |  49
code/shik_1_1/pb.cpp.tk                             |  58
code/shik_2_1/pc.cpp.tk                             |  79
code/simsa.st_0_1/A.cpp.tk                          |  13
code/simsa.st_1_1/B.cpp.tk                          |  22
code/simsa.st_2_1/C.cpp.tk                          |  56
code/SovietUnion_0_1/A.cpp.tk                       |  39
code/SovietUnion_1_1/B.cpp.tk                       |  62
code/SovietUnion_2_1/C.cpp.tk                       |  55
code/tailed_0_1/A.cpp.tk                            |  170
code/tailed_1_1/B.cpp.tk                            |  6168
code/tailed_2_1/C.cpp.tk                            |  56
code/TheNatural_0_1/A.cpp.tk                        |  91
code/TheNatural_1_1/B.cpp.tk                        |  103
code/TheNatural_2_1/C.cpp.tk                        |  60
code/TrueBamboo_0_1/test.cpp.tk                     |  29
code/TrueBamboo_1_1/test.cpp.tk                     |  81
code/TrueBamboo_2_1/test.cpp.tk                     |  47
code/tur.turczyn_0_1/A.cpp.tk                       |  24
code/tur.turczyn_1_1/B.cpp.tk                       |  54
code/tur.turczyn_2_1/C.cpp.tk                       |  43
code/Tyg3R_0_1/A.cpp.tk                             |  13
code/Tyg3R_1_1/B.cpp.tk                             |  22
code/Tyg3R_2_1/C.cpp.tk                             |  22
code/UminchuR_0_1/main.cpp.tk                       |  25
code/UminchuR_1_1/main.cpp.tk                       |  71
code/UminchuR_2_1/main.cpp.tk                       |  60
code/wo..._0_1/a.cpp.tk                             |  60
code/wo..._1_1/b.cpp.tk                             |  83
code/wo..._2_1/c.cpp.tk                             |  100
code/yswtt_0_1/A.cpp.tk                             |  56
code/yswtt_1_1/B.cpp.tk                             |  93
code/yswtt_2_1/C.cpp.tk                             |  73
code/ZhSh_0_1/a.cpp.tk                              |  59
code/ZhSh_1_1/b.cpp.tk                              |  153
code/ZhSh_2_1/c.cpp.tk                              |  106
