Begin
Comparing:  code/Mister_2_1/c.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  10
code/551100kk_1_1/B.cpp.tk                          |  14
code/551100kk_2_1/C.cpp.tk                          |  294
code/achan1058_0_1/Q-A.cpp.tk                       |  5
code/achan1058_1_1/source.cpp.tk                    |  9
code/achan1058_2_1/source.cpp.tk                    |  25
code/alanubi_0_1/a.cpp.tk                           |  19
code/alanubi_1_1/b.cpp.tk                           |  29
code/alanubi_2_1/c.cpp.tk                           |  65
code/AntiForest_0_1/q1.cpp.tk                       |  13
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  280
code/apiad_0_1/A.cpp.tk                             |  11
code/apiad_1_1/B.cpp.tk                             |  14
code/apiad_2_1/C.cpp.tk                             |  41
code/azaky_0_1/A.cpp.tk                             |  12
code/azaky_1_1/B.cpp.tk                             |  15
code/azaky_2_1/C.cpp.tk                             |  67
code/azariamuh_0_1/standing.cpp.tk                  |  8
code/azariamuh_1_1/pancake.cpp.tk                   |  21
code/azariamuh_2_1/dijkstra.cpp.tk                  |  35
code/bmerry_0_1/a.cpp.tk                            |  33
code/bmerry_1_1/b.cpp.tk                            |  38
code/bmerry_2_1/c.cpp.tk                            |  58
code/climpet_0_1/A.cpp.tk                           |  34
code/climpet_1_1/B.cpp.tk                           |  37
code/climpet_2_1/C.cpp.tk                           |  66
code/ctzsm_0_1/A.cpp.tk                             |  39
code/ctzsm_1_1/B.cpp.tk                             |  43
code/ctzsm_2_1/C.cpp.tk                             |  134
code/DanilC_0_1/problem.cpp.tk                      |  37
code/DanilC_1_1/problemB.cpp.tk                     |  57
code/DanilC_2_1/problemC.cpp.tk                     |  74
code/DEGwer_0_1/A.cpp.tk                            |  23
code/DEGwer_1_1/B.cpp.tk                            |  23
code/DEGwer_2_1/C.cpp.tk                            |  254
code/dmute_0_1/a.cpp.tk                             |  18
code/dmute_1_1/b.cpp.tk                             |  33
code/dmute_2_1/c2.cpp.tk                            |  64
code/fagu_0_1/A.cpp.tk                              |  9
code/fagu_1_1/B.cpp.tk                              |  8
code/fagu_2_1/C.cpp.tk                              |  57
code/FatalEagle_0_1/main.cpp.tk                     |  25
code/FatalEagle_1_1/main.cpp.tk                     |  35
code/FatalEagle_2_1/main.cpp.tk                     |  163
code/fullpower_0_1/A.cpp.tk                         |  31
code/fullpower_1_1/B.cpp.tk                         |  46
code/fullpower_2_1/C.cpp.tk                         |  127
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  22
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  26
code/ICastro_2_1/Dijkstra.cpp.tk                    |  106
code/ilackthatsuperpower_0_1/a.cpp.tk               |  51
code/ilackthatsuperpower_1_1/b.cpp.tk               |  45
code/ilackthatsuperpower_2_1/c.cpp.tk               |  63
code/iridescent_0_1/A.cpp.tk                        |  12
code/iridescent_1_1/B.cpp.tk                        |  22
code/iridescent_2_1/C.cpp.tk                        |  53
code/ishraq_0_1/main.cpp.tk                         |  8
code/ishraq_1_1/main.cpp.tk                         |  13
code/ishraq_2_1/main.cpp.tk                         |  55
code/JayXon_0_1/A.cpp.tk                            |  9
code/JayXon_1_1/B.cpp.tk                            |  23
code/JayXon_2_1/C.cpp.tk                            |  17
code/Josse_0_1/A.cpp.tk                             |  12
code/Josse_1_1/B.cpp.tk                             |  21
code/Josse_2_1/C.cpp.tk                             |  58
code/kcm1700_0_1/a.cpp.tk                           |  22
code/kcm1700_1_1/b.cpp.tk                           |  33
code/kcm1700_2_1/c.cpp.tk                           |  66
code/kevinsogo_0_1/a.cpp.tk                         |  9
code/kevinsogo_1_1/b.cpp.tk                         |  12
code/kevinsogo_2_1/c.cpp.tk                         |  68
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  32
code/LazyAnna_1_1/2-1.cpp.tk                        |  33
code/LazyAnna_2_1/3.cpp.tk                          |  47
code/Merkurev_0_1/A.cpp.tk                          |  33
code/Merkurev_1_1/B.cpp.tk                          |  39
code/Merkurev_2_1/C.cpp.tk                          |  50
code/mezei_0_1/main.cpp.tk                          |  28
code/mezei_1_1/main.cpp.tk                          |  24
code/mezei_2_1/main.cpp.tk                          |  50
code/Mister_0_1/a.cpp.tk                            |  36
code/Mister_1_1/b.cpp.tk                            |  42
code/Mister_2_1/c.cpp.tk                            |  60669
code/namonakiacc_0_1/cpp.cpp.tk                     |  12
code/namonakiacc_1_1/cpp.cpp.tk                     |  14
code/namonakiacc_2_1/cpp.cpp.tk                     |  61
code/Nicolas16_0_1/main.cpp.tk                      |  12
code/Nicolas16_1_1/main.cpp.tk                      |  11
code/Nicolas16_2_1/main.cpp.tk                      |  77
code/pandamonium_0_1/a.cpp.tk                       |  19
code/pandamonium_1_1/b.cpp.tk                       |  42
code/pandamonium_2_1/c.cpp.tk                       |  43
code/pflueger_0_1/A.cpp.tk                          |  13
code/pflueger_1_1/B.cpp.tk                          |  22
code/pflueger_2_1/C.cpp.tk                          |  46
code/ponyopoppo_0_1/A.cpp.tk                        |  6
code/ponyopoppo_1_1/B.cpp.tk                        |  9
code/ponyopoppo_2_1/C.cpp.tk                        |  54
code/Ragnar_0_1/A.cpp.tk                            |  7
code/Ragnar_1_1/B-2.cpp.tk                          |  11
code/Ragnar_2_1/C.cpp.tk                            |  31
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  11
code/saffah_2_1/t.cpp.tk                            |  62
code/SamanSami_0_1/A.cpp.tk                         |  5
code/SamanSami_1_1/B.cpp.tk                         |  20
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  9
code/Savlik_1_1/code.cpp.tk                         |  6
code/Savlik_2_1/code.cpp.tk                         |  29
code/shik_0_1/pa.cpp.tk                             |  26
code/shik_1_1/pb.cpp.tk                             |  28
code/shik_2_1/pc.cpp.tk                             |  297
code/simsa.st_0_1/A.cpp.tk                          |  9
code/simsa.st_1_1/B.cpp.tk                          |  9
code/simsa.st_2_1/C.cpp.tk                          |  39
code/SovietUnion_0_1/A.cpp.tk                       |  55
code/SovietUnion_1_1/B.cpp.tk                       |  73
code/SovietUnion_2_1/C.cpp.tk                       |  43
code/tailed_0_1/A.cpp.tk                            |  9
code/tailed_1_1/B.cpp.tk                            |  14
code/tailed_2_1/C.cpp.tk                            |  37
code/TheNatural_0_1/A.cpp.tk                        |  19
code/TheNatural_1_1/B.cpp.tk                        |  22
code/TheNatural_2_1/C.cpp.tk                        |  39
code/TrueBamboo_0_1/test.cpp.tk                     |  10
code/TrueBamboo_1_1/test.cpp.tk                     |  12
code/TrueBamboo_2_1/test.cpp.tk                     |  25
code/tur.turczyn_0_1/A.cpp.tk                       |  5
code/tur.turczyn_1_1/B.cpp.tk                       |  9
code/tur.turczyn_2_1/C.cpp.tk                       |  32
code/Tyg3R_0_1/A.cpp.tk                             |  6
code/Tyg3R_1_1/B.cpp.tk                             |  12
code/Tyg3R_2_1/C.cpp.tk                             |  48
code/UminchuR_0_1/main.cpp.tk                       |  12
code/UminchuR_1_1/main.cpp.tk                       |  16
code/UminchuR_2_1/main.cpp.tk                       |  53
code/wo..._0_1/a.cpp.tk                             |  29
code/wo..._1_1/b.cpp.tk                             |  32
code/wo..._2_1/c.cpp.tk                             |  293
code/yswtt_0_1/A.cpp.tk                             |  24
code/yswtt_1_1/B.cpp.tk                             |  32
code/yswtt_2_1/C.cpp.tk                             |  35
code/ZhSh_0_1/a.cpp.tk                              |  23
code/ZhSh_1_1/b.cpp.tk                              |  49
code/ZhSh_2_1/c.cpp.tk                              |  152
