Begin
Comparing:  code/tur.turczyn_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  14
code/551100kk_1_1/B.cpp.tk                          |  14
code/551100kk_2_1/C.cpp.tk                          |  25
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  141
code/achan1058_2_1/source.cpp.tk                    |  156
code/alanubi_0_1/a.cpp.tk                           |  11
code/alanubi_1_1/b.cpp.tk                           |  13
code/alanubi_2_1/c.cpp.tk                           |  84
code/AntiForest_0_1/q1.cpp.tk                       |  16
code/AntiForest_1_1/q2.cpp.tk                       |  8
code/AntiForest_2_1/q3.cpp.tk                       |  34
code/apiad_0_1/A.cpp.tk                             |  34
code/apiad_1_1/B.cpp.tk                             |  28
code/apiad_2_1/C.cpp.tk                             |  32
code/azaky_0_1/A.cpp.tk                             |  32
code/azaky_1_1/B.cpp.tk                             |  29
code/azaky_2_1/C.cpp.tk                             |  52
code/azariamuh_0_1/standing.cpp.tk                  |  15
code/azariamuh_1_1/pancake.cpp.tk                   |  16
code/azariamuh_2_1/dijkstra.cpp.tk                  |  15
code/bmerry_0_1/a.cpp.tk                            |  68
code/bmerry_1_1/b.cpp.tk                            |  68
code/bmerry_2_1/c.cpp.tk                            |  69
code/climpet_0_1/A.cpp.tk                           |  51
code/climpet_1_1/B.cpp.tk                           |  50
code/climpet_2_1/C.cpp.tk                           |  61
code/ctzsm_0_1/A.cpp.tk                             |  10
code/ctzsm_1_1/B.cpp.tk                             |  11
code/ctzsm_2_1/C.cpp.tk                             |  41
code/DanilC_0_1/problem.cpp.tk                      |  26
code/DanilC_1_1/problemB.cpp.tk                     |  33
code/DanilC_2_1/problemC.cpp.tk                     |  81
code/DEGwer_0_1/A.cpp.tk                            |  15
code/DEGwer_1_1/B.cpp.tk                            |  16
code/DEGwer_2_1/C.cpp.tk                            |  20
code/dmute_0_1/a.cpp.tk                             |  14
code/dmute_1_1/b.cpp.tk                             |  12
code/dmute_2_1/c2.cpp.tk                            |  29
code/fagu_0_1/A.cpp.tk                              |  28
code/fagu_1_1/B.cpp.tk                              |  28
code/fagu_2_1/C.cpp.tk                              |  42
code/FatalEagle_0_1/main.cpp.tk                     |  15
code/FatalEagle_1_1/main.cpp.tk                     |  13
code/FatalEagle_2_1/main.cpp.tk                     |  77
code/fullpower_0_1/A.cpp.tk                         |  15
code/fullpower_1_1/B.cpp.tk                         |  17
code/fullpower_2_1/C.cpp.tk                         |  40
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  18
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  21
code/ICastro_2_1/Dijkstra.cpp.tk                    |  58
code/ilackthatsuperpower_0_1/a.cpp.tk               |  65
code/ilackthatsuperpower_1_1/b.cpp.tk               |  65
code/ilackthatsuperpower_2_1/c.cpp.tk               |  81
code/iridescent_0_1/A.cpp.tk                        |  21
code/iridescent_1_1/B.cpp.tk                        |  20
code/iridescent_2_1/C.cpp.tk                        |  23
code/ishraq_0_1/main.cpp.tk                         |  17
code/ishraq_1_1/main.cpp.tk                         |  11
code/ishraq_2_1/main.cpp.tk                         |  42
code/JayXon_0_1/A.cpp.tk                            |  38
code/JayXon_1_1/B.cpp.tk                            |  15
code/JayXon_2_1/C.cpp.tk                            |  22
code/Josse_0_1/A.cpp.tk                             |  25
code/Josse_1_1/B.cpp.tk                             |  27
code/Josse_2_1/C.cpp.tk                             |  64
code/kcm1700_0_1/a.cpp.tk                           |  14
code/kcm1700_1_1/b.cpp.tk                           |  12
code/kcm1700_2_1/c.cpp.tk                           |  29
code/kevinsogo_0_1/a.cpp.tk                         |  10
code/kevinsogo_1_1/b.cpp.tk                         |  13
code/kevinsogo_2_1/c.cpp.tk                         |  34
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  9
code/LazyAnna_0_1/1.cpp.tk                          |  10
code/LazyAnna_1_1/2-1.cpp.tk                        |  15
code/LazyAnna_2_1/3.cpp.tk                          |  29
code/Merkurev_0_1/A.cpp.tk                          |  14
code/Merkurev_1_1/B.cpp.tk                          |  19
code/Merkurev_2_1/C.cpp.tk                          |  23
code/mezei_0_1/main.cpp.tk                          |  12
code/mezei_1_1/main.cpp.tk                          |  12
code/mezei_2_1/main.cpp.tk                          |  33
code/Mister_0_1/a.cpp.tk                            |  14
code/Mister_1_1/b.cpp.tk                            |  11
code/Mister_2_1/c.cpp.tk                            |  18
code/namonakiacc_0_1/cpp.cpp.tk                     |  127
code/namonakiacc_1_1/cpp.cpp.tk                     |  118
code/namonakiacc_2_1/cpp.cpp.tk                     |  130
code/Nicolas16_0_1/main.cpp.tk                      |  5
code/Nicolas16_1_1/main.cpp.tk                      |  5
code/Nicolas16_2_1/main.cpp.tk                      |  35
code/pandamonium_0_1/a.cpp.tk                       |  8
code/pandamonium_1_1/b.cpp.tk                       |  18
code/pandamonium_2_1/c.cpp.tk                       |  13
code/pflueger_0_1/A.cpp.tk                          |  20
code/pflueger_1_1/B.cpp.tk                          |  20
code/pflueger_2_1/C.cpp.tk                          |  40
code/ponyopoppo_0_1/A.cpp.tk                        |  45
code/ponyopoppo_1_1/B.cpp.tk                        |  38
code/ponyopoppo_2_1/C.cpp.tk                        |  87
code/Ragnar_0_1/A.cpp.tk                            |  84
code/Ragnar_1_1/B-2.cpp.tk                          |  86
code/Ragnar_2_1/C.cpp.tk                            |  96
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  9
code/saffah_2_1/t.cpp.tk                            |  42
code/SamanSami_0_1/A.cpp.tk                         |  5
code/SamanSami_1_1/B.cpp.tk                         |  16
code/SamanSami_2_1/C.cpp.tk                         |  7
code/Savlik_0_1/code.cpp.tk                         |  12
code/Savlik_1_1/code.cpp.tk                         |  13
code/Savlik_2_1/code.cpp.tk                         |  46
code/shik_0_1/pa.cpp.tk                             |  49
code/shik_1_1/pb.cpp.tk                             |  50
code/shik_2_1/pc.cpp.tk                             |  64
code/simsa.st_0_1/A.cpp.tk                          |  14
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  43
code/SovietUnion_0_1/A.cpp.tk                       |  10
code/SovietUnion_1_1/B.cpp.tk                       |  11
code/SovietUnion_2_1/C.cpp.tk                       |  43
code/tailed_0_1/A.cpp.tk                            |  21
code/tailed_1_1/B.cpp.tk                            |  21
code/tailed_2_1/C.cpp.tk                            |  36
code/TheNatural_0_1/A.cpp.tk                        |  13
code/TheNatural_1_1/B.cpp.tk                        |  15
code/TheNatural_2_1/C.cpp.tk                        |  22
code/TrueBamboo_0_1/test.cpp.tk                     |  14
code/TrueBamboo_1_1/test.cpp.tk                     |  19
code/TrueBamboo_2_1/test.cpp.tk                     |  32
code/tur.turczyn_0_1/A.cpp.tk                       |  6583
code/tur.turczyn_1_1/B.cpp.tk                       |  1168
code/tur.turczyn_2_1/C.cpp.tk                       |  1137
code/Tyg3R_0_1/A.cpp.tk                             |  12
code/Tyg3R_1_1/B.cpp.tk                             |  10
code/Tyg3R_2_1/C.cpp.tk                             |  16
code/UminchuR_0_1/main.cpp.tk                       |  87
code/UminchuR_1_1/main.cpp.tk                       |  84
code/UminchuR_2_1/main.cpp.tk                       |  97
code/wo..._0_1/a.cpp.tk                             |  11
code/wo..._1_1/b.cpp.tk                             |  12
code/wo..._2_1/c.cpp.tk                             |  35
code/yswtt_0_1/A.cpp.tk                             |  18
code/yswtt_1_1/B.cpp.tk                             |  20
code/yswtt_2_1/C.cpp.tk                             |  32
code/ZhSh_0_1/a.cpp.tk                              |  23
code/ZhSh_1_1/b.cpp.tk                              |  68
code/ZhSh_2_1/c.cpp.tk                              |  75
