Begin
Comparing:  code/kcm1700_0_1/a.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  73
code/551100kk_1_1/B.cpp.tk                          |  47
code/551100kk_2_1/C.cpp.tk                          |  44
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  15
code/achan1058_2_1/source.cpp.tk                    |  27
code/alanubi_0_1/a.cpp.tk                           |  149
code/alanubi_1_1/b.cpp.tk                           |  115
code/alanubi_2_1/c.cpp.tk                           |  145
code/AntiForest_0_1/q1.cpp.tk                       |  35
code/AntiForest_1_1/q2.cpp.tk                       |  14
code/AntiForest_2_1/q3.cpp.tk                       |  49
code/apiad_0_1/A.cpp.tk                             |  29
code/apiad_1_1/B.cpp.tk                             |  20
code/apiad_2_1/C.cpp.tk                             |  27
code/azaky_0_1/A.cpp.tk                             |  34
code/azaky_1_1/B.cpp.tk                             |  26
code/azaky_2_1/C.cpp.tk                             |  43
code/azariamuh_0_1/standing.cpp.tk                  |  35
code/azariamuh_1_1/pancake.cpp.tk                   |  26
code/azariamuh_2_1/dijkstra.cpp.tk                  |  19
code/bmerry_0_1/a.cpp.tk                            |  127
code/bmerry_1_1/b.cpp.tk                            |  59
code/bmerry_2_1/c.cpp.tk                            |  59
code/climpet_0_1/A.cpp.tk                           |  67
code/climpet_1_1/B.cpp.tk                           |  44
code/climpet_2_1/C.cpp.tk                           |  66
code/ctzsm_0_1/A.cpp.tk                             |  68
code/ctzsm_1_1/B.cpp.tk                             |  76
code/ctzsm_2_1/C.cpp.tk                             |  105
code/DanilC_0_1/problem.cpp.tk                      |  70
code/DanilC_1_1/problemB.cpp.tk                     |  66
code/DanilC_2_1/problemC.cpp.tk                     |  73
code/DEGwer_0_1/A.cpp.tk                            |  107
code/DEGwer_1_1/B.cpp.tk                            |  71
code/DEGwer_2_1/C.cpp.tk                            |  44
code/dmute_0_1/a.cpp.tk                             |  113
code/dmute_1_1/b.cpp.tk                             |  235
code/dmute_2_1/c2.cpp.tk                            |  160
code/fagu_0_1/A.cpp.tk                              |  29
code/fagu_1_1/B.cpp.tk                              |  26
code/fagu_2_1/C.cpp.tk                              |  39
code/FatalEagle_0_1/main.cpp.tk                     |  170
code/FatalEagle_1_1/main.cpp.tk                     |  188
code/FatalEagle_2_1/main.cpp.tk                     |  243
code/fullpower_0_1/A.cpp.tk                         |  148
code/fullpower_1_1/B.cpp.tk                         |  203
code/fullpower_2_1/C.cpp.tk                         |  247
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  53
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  39
code/ICastro_2_1/Dijkstra.cpp.tk                    |  74
code/ilackthatsuperpower_0_1/a.cpp.tk               |  105
code/ilackthatsuperpower_1_1/b.cpp.tk               |  92
code/ilackthatsuperpower_2_1/c.cpp.tk               |  75
code/iridescent_0_1/A.cpp.tk                        |  61
code/iridescent_1_1/B.cpp.tk                        |  135
code/iridescent_2_1/C.cpp.tk                        |  92
code/ishraq_0_1/main.cpp.tk                         |  43
code/ishraq_1_1/main.cpp.tk                         |  60
code/ishraq_2_1/main.cpp.tk                         |  55
code/JayXon_0_1/A.cpp.tk                            |  84
code/JayXon_1_1/B.cpp.tk                            |  56
code/JayXon_2_1/C.cpp.tk                            |  21
code/Josse_0_1/A.cpp.tk                             |  48
code/Josse_1_1/B.cpp.tk                             |  53
code/Josse_2_1/C.cpp.tk                             |  78
code/kcm1700_0_1/a.cpp.tk                           |  4386
code/kcm1700_1_1/b.cpp.tk                           |  278
code/kcm1700_2_1/c.cpp.tk                           |  146
code/kevinsogo_0_1/a.cpp.tk                         |  60
code/kevinsogo_1_1/b.cpp.tk                         |  59
code/kevinsogo_2_1/c.cpp.tk                         |  49
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  8
code/LazyAnna_0_1/1.cpp.tk                          |  55
code/LazyAnna_1_1/2-1.cpp.tk                        |  46
code/LazyAnna_2_1/3.cpp.tk                          |  29
code/Merkurev_0_1/A.cpp.tk                          |  274
code/Merkurev_1_1/B.cpp.tk                          |  139
code/Merkurev_2_1/C.cpp.tk                          |  160
code/mezei_0_1/main.cpp.tk                          |  218
code/mezei_1_1/main.cpp.tk                          |  116
code/mezei_2_1/main.cpp.tk                          |  149
code/Mister_0_1/a.cpp.tk                            |  179
code/Mister_1_1/b.cpp.tk                            |  149
code/Mister_2_1/c.cpp.tk                            |  90
code/namonakiacc_0_1/cpp.cpp.tk                     |  42
code/namonakiacc_1_1/cpp.cpp.tk                     |  29
code/namonakiacc_2_1/cpp.cpp.tk                     |  46
code/Nicolas16_0_1/main.cpp.tk                      |  77
code/Nicolas16_1_1/main.cpp.tk                      |  70
code/Nicolas16_2_1/main.cpp.tk                      |  206
code/pandamonium_0_1/a.cpp.tk                       |  118
code/pandamonium_1_1/b.cpp.tk                       |  133
code/pandamonium_2_1/c.cpp.tk                       |  105
code/pflueger_0_1/A.cpp.tk                          |  117
code/pflueger_1_1/B.cpp.tk                          |  82
code/pflueger_2_1/C.cpp.tk                          |  91
code/ponyopoppo_0_1/A.cpp.tk                        |  14
code/ponyopoppo_1_1/B.cpp.tk                        |  12
code/ponyopoppo_2_1/C.cpp.tk                        |  48
code/Ragnar_0_1/A.cpp.tk                            |  13
code/Ragnar_1_1/B-2.cpp.tk                          |  21
code/Ragnar_2_1/C.cpp.tk                            |  52
code/saffah_0_1/t.cpp.tk                            |  57
code/saffah_1_1/t.cpp.tk                            |  51
code/saffah_2_1/t.cpp.tk                            |  51
code/SamanSami_0_1/A.cpp.tk                         |  33
code/SamanSami_1_1/B.cpp.tk                         |  86
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  87
code/Savlik_1_1/code.cpp.tk                         |  7
code/Savlik_2_1/code.cpp.tk                         |  31
code/shik_0_1/pa.cpp.tk                             |  39
code/shik_1_1/pb.cpp.tk                             |  36
code/shik_2_1/pc.cpp.tk                             |  58
code/simsa.st_0_1/A.cpp.tk                          |  23
code/simsa.st_1_1/B.cpp.tk                          |  38
code/simsa.st_2_1/C.cpp.tk                          |  53
code/SovietUnion_0_1/A.cpp.tk                       |  79
code/SovietUnion_1_1/B.cpp.tk                       |  96
code/SovietUnion_2_1/C.cpp.tk                       |  41
code/tailed_0_1/A.cpp.tk                            |  48
code/tailed_1_1/B.cpp.tk                            |  57
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  203
code/TheNatural_1_1/B.cpp.tk                        |  109
code/TheNatural_2_1/C.cpp.tk                        |  51
code/TrueBamboo_0_1/test.cpp.tk                     |  44
code/TrueBamboo_1_1/test.cpp.tk                     |  35
code/TrueBamboo_2_1/test.cpp.tk                     |  42
code/tur.turczyn_0_1/A.cpp.tk                       |  19
code/tur.turczyn_1_1/B.cpp.tk                       |  15
code/tur.turczyn_2_1/C.cpp.tk                       |  17
code/Tyg3R_0_1/A.cpp.tk                             |  13
code/Tyg3R_1_1/B.cpp.tk                             |  15
code/Tyg3R_2_1/C.cpp.tk                             |  25
code/UminchuR_0_1/main.cpp.tk                       |  34
code/UminchuR_1_1/main.cpp.tk                       |  38
code/UminchuR_2_1/main.cpp.tk                       |  54
code/wo..._0_1/a.cpp.tk                             |  138
code/wo..._1_1/b.cpp.tk                             |  159
code/wo..._2_1/c.cpp.tk                             |  190
code/yswtt_0_1/A.cpp.tk                             |  38
code/yswtt_1_1/B.cpp.tk                             |  41
code/yswtt_2_1/C.cpp.tk                             |  60
code/ZhSh_0_1/a.cpp.tk                              |  58
code/ZhSh_1_1/b.cpp.tk                              |  74
code/ZhSh_2_1/c.cpp.tk                              |  58
