Begin
Comparing:  code/iridescent_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  11
code/551100kk_1_1/B.cpp.tk                          |  23
code/551100kk_2_1/C.cpp.tk                          |  93
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  13
code/achan1058_2_1/source.cpp.tk                    |  26
code/alanubi_0_1/a.cpp.tk                           |  36
code/alanubi_1_1/b.cpp.tk                           |  44
code/alanubi_2_1/c.cpp.tk                           |  101
code/AntiForest_0_1/q1.cpp.tk                       |  13
code/AntiForest_1_1/q2.cpp.tk                       |  3
code/AntiForest_2_1/q3.cpp.tk                       |  85
code/apiad_0_1/A.cpp.tk                             |  12
code/apiad_1_1/B.cpp.tk                             |  12
code/apiad_2_1/C.cpp.tk                             |  265
code/azaky_0_1/A.cpp.tk                             |  10
code/azaky_1_1/B.cpp.tk                             |  12
code/azaky_2_1/C.cpp.tk                             |  269
code/azariamuh_0_1/standing.cpp.tk                  |  11
code/azariamuh_1_1/pancake.cpp.tk                   |  29
code/azariamuh_2_1/dijkstra.cpp.tk                  |  49
code/bmerry_0_1/a.cpp.tk                            |  54
code/bmerry_1_1/b.cpp.tk                            |  67
code/bmerry_2_1/c.cpp.tk                            |  286
code/climpet_0_1/A.cpp.tk                           |  34
code/climpet_1_1/B.cpp.tk                           |  35
code/climpet_2_1/C.cpp.tk                           |  260
code/ctzsm_0_1/A.cpp.tk                             |  18
code/ctzsm_1_1/B.cpp.tk                             |  25
code/ctzsm_2_1/C.cpp.tk                             |  322
code/DanilC_0_1/problem.cpp.tk                      |  38
code/DanilC_1_1/problemB.cpp.tk                     |  56
code/DanilC_2_1/problemC.cpp.tk                     |  59
code/DEGwer_0_1/A.cpp.tk                            |  38
code/DEGwer_1_1/B.cpp.tk                            |  44
code/DEGwer_2_1/C.cpp.tk                            |  91
code/dmute_0_1/a.cpp.tk                             |  24
code/dmute_1_1/b.cpp.tk                             |  47
code/dmute_2_1/c2.cpp.tk                            |  92
code/fagu_0_1/A.cpp.tk                              |  14
code/fagu_1_1/B.cpp.tk                              |  15
code/fagu_2_1/C.cpp.tk                              |  379
code/FatalEagle_0_1/main.cpp.tk                     |  27
code/FatalEagle_1_1/main.cpp.tk                     |  65
code/FatalEagle_2_1/main.cpp.tk                     |  233
code/fullpower_0_1/A.cpp.tk                         |  35
code/fullpower_1_1/B.cpp.tk                         |  81
code/fullpower_2_1/C.cpp.tk                         |  114
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  29
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  35
code/ICastro_2_1/Dijkstra.cpp.tk                    |  76
code/ilackthatsuperpower_0_1/a.cpp.tk               |  58
code/ilackthatsuperpower_1_1/b.cpp.tk               |  57
code/ilackthatsuperpower_2_1/c.cpp.tk               |  66
code/iridescent_0_1/A.cpp.tk                        |  59
code/iridescent_1_1/B.cpp.tk                        |  109
code/iridescent_2_1/C.cpp.tk                        |  20316
code/ishraq_0_1/main.cpp.tk                         |  8
code/ishraq_1_1/main.cpp.tk                         |  16
code/ishraq_2_1/main.cpp.tk                         |  42
code/JayXon_0_1/A.cpp.tk                            |  15
code/JayXon_1_1/B.cpp.tk                            |  44
code/JayXon_2_1/C.cpp.tk                            |  18
code/Josse_0_1/A.cpp.tk                             |  41
code/Josse_1_1/B.cpp.tk                             |  60
code/Josse_2_1/C.cpp.tk                             |  90
code/kcm1700_0_1/a.cpp.tk                           |  38
code/kcm1700_1_1/b.cpp.tk                           |  57
code/kcm1700_2_1/c.cpp.tk                           |  96
code/kevinsogo_0_1/a.cpp.tk                         |  9
code/kevinsogo_1_1/b.cpp.tk                         |  12
code/kevinsogo_2_1/c.cpp.tk                         |  48
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  9
code/LazyAnna_0_1/1.cpp.tk                          |  26
code/LazyAnna_1_1/2-1.cpp.tk                        |  35
code/LazyAnna_2_1/3.cpp.tk                          |  83
code/Merkurev_0_1/A.cpp.tk                          |  44
code/Merkurev_1_1/B.cpp.tk                          |  57
code/Merkurev_2_1/C.cpp.tk                          |  82
code/mezei_0_1/main.cpp.tk                          |  44
code/mezei_1_1/main.cpp.tk                          |  46
code/mezei_2_1/main.cpp.tk                          |  86
code/Mister_0_1/a.cpp.tk                            |  18
code/Mister_1_1/b.cpp.tk                            |  29
code/Mister_2_1/c.cpp.tk                            |  92
code/namonakiacc_0_1/cpp.cpp.tk                     |  13
code/namonakiacc_1_1/cpp.cpp.tk                     |  16
code/namonakiacc_2_1/cpp.cpp.tk                     |  56
code/Nicolas16_0_1/main.cpp.tk                      |  12
code/Nicolas16_1_1/main.cpp.tk                      |  12
code/Nicolas16_2_1/main.cpp.tk                      |  79
code/pandamonium_0_1/a.cpp.tk                       |  27
code/pandamonium_1_1/b.cpp.tk                       |  59
code/pandamonium_2_1/c.cpp.tk                       |  59
code/pflueger_0_1/A.cpp.tk                          |  64
code/pflueger_1_1/B.cpp.tk                          |  74
code/pflueger_2_1/C.cpp.tk                          |  83
code/ponyopoppo_0_1/A.cpp.tk                        |  12
code/ponyopoppo_1_1/B.cpp.tk                        |  11
code/ponyopoppo_2_1/C.cpp.tk                        |  49
code/Ragnar_0_1/A.cpp.tk                            |  12
code/Ragnar_1_1/B-2.cpp.tk                          |  22
code/Ragnar_2_1/C.cpp.tk                            |  83
code/saffah_0_1/t.cpp.tk                            |  10
code/saffah_1_1/t.cpp.tk                            |  12
code/saffah_2_1/t.cpp.tk                            |  47
code/SamanSami_0_1/A.cpp.tk                         |  19
code/SamanSami_1_1/B.cpp.tk                         |  68
code/SamanSami_2_1/C.cpp.tk                         |  4
code/Savlik_0_1/code.cpp.tk                         |  22
code/Savlik_1_1/code.cpp.tk                         |  6
code/Savlik_2_1/code.cpp.tk                         |  26
code/shik_0_1/pa.cpp.tk                             |  22
code/shik_1_1/pb.cpp.tk                             |  21
code/shik_2_1/pc.cpp.tk                             |  97
code/simsa.st_0_1/A.cpp.tk                          |  7
code/simsa.st_1_1/B.cpp.tk                          |  7
code/simsa.st_2_1/C.cpp.tk                          |  26
code/SovietUnion_0_1/A.cpp.tk                       |  24
code/SovietUnion_1_1/B.cpp.tk                       |  32
code/SovietUnion_2_1/C.cpp.tk                       |  32
code/tailed_0_1/A.cpp.tk                            |  36
code/tailed_1_1/B.cpp.tk                            |  41
code/tailed_2_1/C.cpp.tk                            |  62
code/TheNatural_0_1/A.cpp.tk                        |  52
code/TheNatural_1_1/B.cpp.tk                        |  67
code/TheNatural_2_1/C.cpp.tk                        |  252
code/TrueBamboo_0_1/test.cpp.tk                     |  16
code/TrueBamboo_1_1/test.cpp.tk                     |  24
code/TrueBamboo_2_1/test.cpp.tk                     |  28
code/tur.turczyn_0_1/A.cpp.tk                       |  12
code/tur.turczyn_1_1/B.cpp.tk                       |  15
code/tur.turczyn_2_1/C.cpp.tk                       |  58
code/Tyg3R_0_1/A.cpp.tk                             |  9
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  396
code/UminchuR_0_1/main.cpp.tk                       |  12
code/UminchuR_1_1/main.cpp.tk                       |  12
code/UminchuR_2_1/main.cpp.tk                       |  63
code/wo..._0_1/a.cpp.tk                             |  40
code/wo..._1_1/b.cpp.tk                             |  50
code/wo..._2_1/c.cpp.tk                             |  148
code/yswtt_0_1/A.cpp.tk                             |  30
code/yswtt_1_1/B.cpp.tk                             |  61
code/yswtt_2_1/C.cpp.tk                             |  66
code/ZhSh_0_1/a.cpp.tk                              |  37
code/ZhSh_1_1/b.cpp.tk                              |  54
code/ZhSh_2_1/c.cpp.tk                              |  383
