Begin
Comparing:  code/TrueBamboo_1_1/test.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  38
code/551100kk_1_1/B.cpp.tk                          |  145
code/551100kk_2_1/C.cpp.tk                          |  84
code/achan1058_0_1/Q-A.cpp.tk                       |  13
code/achan1058_1_1/source.cpp.tk                    |  42
code/achan1058_2_1/source.cpp.tk                    |  58
code/alanubi_0_1/a.cpp.tk                           |  27
code/alanubi_1_1/b.cpp.tk                           |  47
code/alanubi_2_1/c.cpp.tk                           |  112
code/AntiForest_0_1/q1.cpp.tk                       |  21
code/AntiForest_1_1/q2.cpp.tk                       |  11
code/AntiForest_2_1/q3.cpp.tk                       |  58
code/apiad_0_1/A.cpp.tk                             |  18
code/apiad_1_1/B.cpp.tk                             |  32
code/apiad_2_1/C.cpp.tk                             |  30
code/azaky_0_1/A.cpp.tk                             |  18
code/azaky_1_1/B.cpp.tk                             |  31
code/azaky_2_1/C.cpp.tk                             |  61
code/azariamuh_0_1/standing.cpp.tk                  |  14
code/azariamuh_1_1/pancake.cpp.tk                   |  34
code/azariamuh_2_1/dijkstra.cpp.tk                  |  21
code/bmerry_0_1/a.cpp.tk                            |  56
code/bmerry_1_1/b.cpp.tk                            |  131
code/bmerry_2_1/c.cpp.tk                            |  70
code/climpet_0_1/A.cpp.tk                           |  33
code/climpet_1_1/B.cpp.tk                           |  43
code/climpet_2_1/C.cpp.tk                           |  61
code/ctzsm_0_1/A.cpp.tk                             |  23
code/ctzsm_1_1/B.cpp.tk                             |  74
code/ctzsm_2_1/C.cpp.tk                             |  86
code/DanilC_0_1/problem.cpp.tk                      |  34
code/DanilC_1_1/problemB.cpp.tk                     |  55
code/DanilC_2_1/problemC.cpp.tk                     |  127
code/DEGwer_0_1/A.cpp.tk                            |  43
code/DEGwer_1_1/B.cpp.tk                            |  57
code/DEGwer_2_1/C.cpp.tk                            |  46
code/dmute_0_1/a.cpp.tk                             |  23
code/dmute_1_1/b.cpp.tk                             |  45
code/dmute_2_1/c2.cpp.tk                            |  78
code/fagu_0_1/A.cpp.tk                              |  14
code/fagu_1_1/B.cpp.tk                              |  14
code/fagu_2_1/C.cpp.tk                              |  41
code/FatalEagle_0_1/main.cpp.tk                     |  33
code/FatalEagle_1_1/main.cpp.tk                     |  82
code/FatalEagle_2_1/main.cpp.tk                     |  249
code/fullpower_0_1/A.cpp.tk                         |  47
code/fullpower_1_1/B.cpp.tk                         |  73
code/fullpower_2_1/C.cpp.tk                         |  114
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  14
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  29
code/ICastro_2_1/Dijkstra.cpp.tk                    |  109
code/ilackthatsuperpower_0_1/a.cpp.tk               |  96
code/ilackthatsuperpower_1_1/b.cpp.tk               |  101
code/ilackthatsuperpower_2_1/c.cpp.tk               |  124
code/iridescent_0_1/A.cpp.tk                        |  19
code/iridescent_1_1/B.cpp.tk                        |  97
code/iridescent_2_1/C.cpp.tk                        |  42
code/ishraq_0_1/main.cpp.tk                         |  13
code/ishraq_1_1/main.cpp.tk                         |  32
code/ishraq_2_1/main.cpp.tk                         |  70
code/JayXon_0_1/A.cpp.tk                            |  14
code/JayXon_1_1/B.cpp.tk                            |  50
code/JayXon_2_1/C.cpp.tk                            |  41
code/Josse_0_1/A.cpp.tk                             |  28
code/Josse_1_1/B.cpp.tk                             |  47
code/Josse_2_1/C.cpp.tk                             |  122
code/kcm1700_0_1/a.cpp.tk                           |  24
code/kcm1700_1_1/b.cpp.tk                           |  147
code/kcm1700_2_1/c.cpp.tk                           |  76
code/kevinsogo_0_1/a.cpp.tk                         |  15
code/kevinsogo_1_1/b.cpp.tk                         |  27
code/kevinsogo_2_1/c.cpp.tk                         |  59
code/ksun48_0_1/A.cpp.tk                            |  10
code/ksun48_1_1/B.cpp.tk                            |  10
code/ksun48_2_1/C.cpp.tk                            |  19
code/LazyAnna_0_1/1.cpp.tk                          |  14
code/LazyAnna_1_1/2-1.cpp.tk                        |  32
code/LazyAnna_2_1/3.cpp.tk                          |  43
code/Merkurev_0_1/A.cpp.tk                          |  40
code/Merkurev_1_1/B.cpp.tk                          |  75
code/Merkurev_2_1/C.cpp.tk                          |  66
code/mezei_0_1/main.cpp.tk                          |  40
code/mezei_1_1/main.cpp.tk                          |  44
code/mezei_2_1/main.cpp.tk                          |  109
code/Mister_0_1/a.cpp.tk                            |  18
code/Mister_1_1/b.cpp.tk                            |  24
code/Mister_2_1/c.cpp.tk                            |  35
code/namonakiacc_0_1/cpp.cpp.tk                     |  24
code/namonakiacc_1_1/cpp.cpp.tk                     |  31
code/namonakiacc_2_1/cpp.cpp.tk                     |  53
code/Nicolas16_0_1/main.cpp.tk                      |  14
code/Nicolas16_1_1/main.cpp.tk                      |  14
code/Nicolas16_2_1/main.cpp.tk                      |  94
code/pandamonium_0_1/a.cpp.tk                       |  25
code/pandamonium_1_1/b.cpp.tk                       |  63
code/pandamonium_2_1/c.cpp.tk                       |  40
code/pflueger_0_1/A.cpp.tk                          |  26
code/pflueger_1_1/B.cpp.tk                          |  41
code/pflueger_2_1/C.cpp.tk                          |  79
code/ponyopoppo_0_1/A.cpp.tk                        |  16
code/ponyopoppo_1_1/B.cpp.tk                        |  49
code/ponyopoppo_2_1/C.cpp.tk                        |  130
code/Ragnar_0_1/A.cpp.tk                            |  18
code/Ragnar_1_1/B-2.cpp.tk                          |  70
code/Ragnar_2_1/C.cpp.tk                            |  47
code/saffah_0_1/t.cpp.tk                            |  13
code/saffah_1_1/t.cpp.tk                            |  22
code/saffah_2_1/t.cpp.tk                            |  72
code/SamanSami_0_1/A.cpp.tk                         |  10
code/SamanSami_1_1/B.cpp.tk                         |  47
code/SamanSami_2_1/C.cpp.tk                         |  10
code/Savlik_0_1/code.cpp.tk                         |  18
code/Savlik_1_1/code.cpp.tk                         |  18
code/Savlik_2_1/code.cpp.tk                         |  81
code/shik_0_1/pa.cpp.tk                             |  58
code/shik_1_1/pb.cpp.tk                             |  64
code/shik_2_1/pc.cpp.tk                             |  89
code/simsa.st_0_1/A.cpp.tk                          |  15
code/simsa.st_1_1/B.cpp.tk                          |  25
code/simsa.st_2_1/C.cpp.tk                          |  77
code/SovietUnion_0_1/A.cpp.tk                       |  26
code/SovietUnion_1_1/B.cpp.tk                       |  39
code/SovietUnion_2_1/C.cpp.tk                       |  79
code/tailed_0_1/A.cpp.tk                            |  18
code/tailed_1_1/B.cpp.tk                            |  65
code/tailed_2_1/C.cpp.tk                            |  62
code/TheNatural_0_1/A.cpp.tk                        |  45
code/TheNatural_1_1/B.cpp.tk                        |  78
code/TheNatural_2_1/C.cpp.tk                        |  38
code/TrueBamboo_0_1/test.cpp.tk                     |  251
code/TrueBamboo_1_1/test.cpp.tk                     |  8924
code/TrueBamboo_2_1/test.cpp.tk                     |  152
code/tur.turczyn_0_1/A.cpp.tk                       |  17
code/tur.turczyn_1_1/B.cpp.tk                       |  27
code/tur.turczyn_2_1/C.cpp.tk                       |  32
code/Tyg3R_0_1/A.cpp.tk                             |  14
code/Tyg3R_1_1/B.cpp.tk                             |  22
code/Tyg3R_2_1/C.cpp.tk                             |  20
code/UminchuR_0_1/main.cpp.tk                       |  27
code/UminchuR_1_1/main.cpp.tk                       |  68
code/UminchuR_2_1/main.cpp.tk                       |  65
code/wo..._0_1/a.cpp.tk                             |  32
code/wo..._1_1/b.cpp.tk                             |  56
code/wo..._2_1/c.cpp.tk                             |  90
code/yswtt_0_1/A.cpp.tk                             |  14
code/yswtt_1_1/B.cpp.tk                             |  44
code/yswtt_2_1/C.cpp.tk                             |  42
code/ZhSh_0_1/a.cpp.tk                              |  15
code/ZhSh_1_1/b.cpp.tk                              |  77
code/ZhSh_2_1/c.cpp.tk                              |  68
