Begin
Comparing:  code/alanubi_1_1/b.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  16
code/551100kk_1_1/B.cpp.tk                          |  63
code/551100kk_2_1/C.cpp.tk                          |  60
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  18
code/achan1058_2_1/source.cpp.tk                    |  28
code/alanubi_0_1/a.cpp.tk                           |  203
code/alanubi_1_1/b.cpp.tk                           |  13901
code/alanubi_2_1/c.cpp.tk                           |  266
code/AntiForest_0_1/q1.cpp.tk                       |  19
code/AntiForest_1_1/q2.cpp.tk                       |  9
code/AntiForest_2_1/q3.cpp.tk                       |  49
code/apiad_0_1/A.cpp.tk                             |  14
code/apiad_1_1/B.cpp.tk                             |  23
code/apiad_2_1/C.cpp.tk                             |  27
code/azaky_0_1/A.cpp.tk                             |  19
code/azaky_1_1/B.cpp.tk                             |  34
code/azaky_2_1/C.cpp.tk                             |  44
code/azariamuh_0_1/standing.cpp.tk                  |  14
code/azariamuh_1_1/pancake.cpp.tk                   |  28
code/azariamuh_2_1/dijkstra.cpp.tk                  |  19
code/bmerry_0_1/a.cpp.tk                            |  59
code/bmerry_1_1/b.cpp.tk                            |  100
code/bmerry_2_1/c.cpp.tk                            |  75
code/climpet_0_1/A.cpp.tk                           |  29
code/climpet_1_1/B.cpp.tk                           |  58
code/climpet_2_1/C.cpp.tk                           |  59
code/ctzsm_0_1/A.cpp.tk                             |  43
code/ctzsm_1_1/B.cpp.tk                             |  132
code/ctzsm_2_1/C.cpp.tk                             |  104
code/DanilC_0_1/problem.cpp.tk                      |  34
code/DanilC_1_1/problemB.cpp.tk                     |  78
code/DanilC_2_1/problemC.cpp.tk                     |  77
code/DEGwer_0_1/A.cpp.tk                            |  78
code/DEGwer_1_1/B.cpp.tk                            |  138
code/DEGwer_2_1/C.cpp.tk                            |  85
code/dmute_0_1/a.cpp.tk                             |  35
code/dmute_1_1/b.cpp.tk                             |  84
code/dmute_2_1/c2.cpp.tk                            |  106
code/fagu_0_1/A.cpp.tk                              |  65
code/fagu_1_1/B.cpp.tk                              |  65
code/fagu_2_1/C.cpp.tk                              |  84
code/FatalEagle_0_1/main.cpp.tk                     |  53
code/FatalEagle_1_1/main.cpp.tk                     |  105
code/FatalEagle_2_1/main.cpp.tk                     |  358
code/fullpower_0_1/A.cpp.tk                         |  55
code/fullpower_1_1/B.cpp.tk                         |  100
code/fullpower_2_1/C.cpp.tk                         |  124
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  22
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  50
code/ICastro_2_1/Dijkstra.cpp.tk                    |  77
code/ilackthatsuperpower_0_1/a.cpp.tk               |  89
code/ilackthatsuperpower_1_1/b.cpp.tk               |  88
code/ilackthatsuperpower_2_1/c.cpp.tk               |  101
code/iridescent_0_1/A.cpp.tk                        |  22
code/iridescent_1_1/B.cpp.tk                        |  45
code/iridescent_2_1/C.cpp.tk                        |  63
code/ishraq_0_1/main.cpp.tk                         |  23
code/ishraq_1_1/main.cpp.tk                         |  44
code/ishraq_2_1/main.cpp.tk                         |  61
code/JayXon_0_1/A.cpp.tk                            |  14
code/JayXon_1_1/B.cpp.tk                            |  73
code/JayXon_2_1/C.cpp.tk                            |  21
code/Josse_0_1/A.cpp.tk                             |  61
code/Josse_1_1/B.cpp.tk                             |  118
code/Josse_2_1/C.cpp.tk                             |  166
code/kcm1700_0_1/a.cpp.tk                           |  67
code/kcm1700_1_1/b.cpp.tk                           |  227
code/kcm1700_2_1/c.cpp.tk                           |  131
code/kevinsogo_0_1/a.cpp.tk                         |  28
code/kevinsogo_1_1/b.cpp.tk                         |  37
code/kevinsogo_2_1/c.cpp.tk                         |  55
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  9
code/LazyAnna_0_1/1.cpp.tk                          |  20
code/LazyAnna_1_1/2-1.cpp.tk                        |  44
code/LazyAnna_2_1/3.cpp.tk                          |  26
code/Merkurev_0_1/A.cpp.tk                          |  74
code/Merkurev_1_1/B.cpp.tk                          |  167
code/Merkurev_2_1/C.cpp.tk                          |  108
code/mezei_0_1/main.cpp.tk                          |  55
code/mezei_1_1/main.cpp.tk                          |  94
code/mezei_2_1/main.cpp.tk                          |  170
code/Mister_0_1/a.cpp.tk                            |  57
code/Mister_1_1/b.cpp.tk                            |  97
code/Mister_2_1/c.cpp.tk                            |  67
code/namonakiacc_0_1/cpp.cpp.tk                     |  22
code/namonakiacc_1_1/cpp.cpp.tk                     |  26
code/namonakiacc_2_1/cpp.cpp.tk                     |  46
code/Nicolas16_0_1/main.cpp.tk                      |  29
code/Nicolas16_1_1/main.cpp.tk                      |  26
code/Nicolas16_2_1/main.cpp.tk                      |  137
code/pandamonium_0_1/a.cpp.tk                       |  36
code/pandamonium_1_1/b.cpp.tk                       |  198
code/pandamonium_2_1/c.cpp.tk                       |  77
code/pflueger_0_1/A.cpp.tk                          |  23
code/pflueger_1_1/B.cpp.tk                          |  73
code/pflueger_2_1/C.cpp.tk                          |  105
code/ponyopoppo_0_1/A.cpp.tk                        |  9
code/ponyopoppo_1_1/B.cpp.tk                        |  19
code/ponyopoppo_2_1/C.cpp.tk                        |  60
code/Ragnar_0_1/A.cpp.tk                            |  10
code/Ragnar_1_1/B-2.cpp.tk                          |  41
code/Ragnar_2_1/C.cpp.tk                            |  29
code/saffah_0_1/t.cpp.tk                            |  25
code/saffah_1_1/t.cpp.tk                            |  30
code/saffah_2_1/t.cpp.tk                            |  52
code/SamanSami_0_1/A.cpp.tk                         |  8
code/SamanSami_1_1/B.cpp.tk                         |  76
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  14
code/Savlik_1_1/code.cpp.tk                         |  8
code/Savlik_2_1/code.cpp.tk                         |  37
code/shik_0_1/pa.cpp.tk                             |  40
code/shik_1_1/pb.cpp.tk                             |  41
code/shik_2_1/pc.cpp.tk                             |  64
code/simsa.st_0_1/A.cpp.tk                          |  15
code/simsa.st_1_1/B.cpp.tk                          |  42
code/simsa.st_2_1/C.cpp.tk                          |  58
code/SovietUnion_0_1/A.cpp.tk                       |  45
code/SovietUnion_1_1/B.cpp.tk                       |  63
code/SovietUnion_2_1/C.cpp.tk                       |  39
code/tailed_0_1/A.cpp.tk                            |  17
code/tailed_1_1/B.cpp.tk                            |  34
code/tailed_2_1/C.cpp.tk                            |  24
code/TheNatural_0_1/A.cpp.tk                        |  30
code/TheNatural_1_1/B.cpp.tk                        |  87
code/TheNatural_2_1/C.cpp.tk                        |  32
code/TrueBamboo_0_1/test.cpp.tk                     |  19
code/TrueBamboo_1_1/test.cpp.tk                     |  40
code/TrueBamboo_2_1/test.cpp.tk                     |  41
code/tur.turczyn_0_1/A.cpp.tk                       |  10
code/tur.turczyn_1_1/B.cpp.tk                       |  16
code/tur.turczyn_2_1/C.cpp.tk                       |  19
code/Tyg3R_0_1/A.cpp.tk                             |  8
code/Tyg3R_1_1/B.cpp.tk                             |  17
code/Tyg3R_2_1/C.cpp.tk                             |  18
code/UminchuR_0_1/main.cpp.tk                       |  27
code/UminchuR_1_1/main.cpp.tk                       |  42
code/UminchuR_2_1/main.cpp.tk                       |  49
code/wo..._0_1/a.cpp.tk                             |  173
code/wo..._1_1/b.cpp.tk                             |  144
code/wo..._2_1/c.cpp.tk                             |  183
code/yswtt_0_1/A.cpp.tk                             |  17
code/yswtt_1_1/B.cpp.tk                             |  44
code/yswtt_2_1/C.cpp.tk                             |  37
code/ZhSh_0_1/a.cpp.tk                              |  20
code/ZhSh_1_1/b.cpp.tk                              |  70
code/ZhSh_2_1/c.cpp.tk                              |  55
