Begin
Comparing:  code/ICastro_0_1/Standing_Ovation.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  15
code/551100kk_1_1/B.cpp.tk                          |  17
code/551100kk_2_1/C.cpp.tk                          |  24
code/achan1058_0_1/Q-A.cpp.tk                       |  9
code/achan1058_1_1/source.cpp.tk                    |  21
code/achan1058_2_1/source.cpp.tk                    |  35
code/alanubi_0_1/a.cpp.tk                           |  43
code/alanubi_1_1/b.cpp.tk                           |  35
code/alanubi_2_1/c.cpp.tk                           |  102
code/AntiForest_0_1/q1.cpp.tk                       |  16
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  33
code/apiad_0_1/A.cpp.tk                             |  15
code/apiad_1_1/B.cpp.tk                             |  13
code/apiad_2_1/C.cpp.tk                             |  19
code/azaky_0_1/A.cpp.tk                             |  17
code/azaky_1_1/B.cpp.tk                             |  15
code/azaky_2_1/C.cpp.tk                             |  36
code/azariamuh_0_1/standing.cpp.tk                  |  23
code/azariamuh_1_1/pancake.cpp.tk                   |  15
code/azariamuh_2_1/dijkstra.cpp.tk                  |  14
code/bmerry_0_1/a.cpp.tk                            |  138
code/bmerry_1_1/b.cpp.tk                            |  67
code/bmerry_2_1/c.cpp.tk                            |  68
code/climpet_0_1/A.cpp.tk                           |  192
code/climpet_1_1/B.cpp.tk                           |  82
code/climpet_2_1/C.cpp.tk                           |  94
code/ctzsm_0_1/A.cpp.tk                             |  53
code/ctzsm_1_1/B.cpp.tk                             |  56
code/ctzsm_2_1/C.cpp.tk                             |  98
code/DanilC_0_1/problem.cpp.tk                      |  93
code/DanilC_1_1/problemB.cpp.tk                     |  115
code/DanilC_2_1/problemC.cpp.tk                     |  101
code/DEGwer_0_1/A.cpp.tk                            |  42
code/DEGwer_1_1/B.cpp.tk                            |  45
code/DEGwer_2_1/C.cpp.tk                            |  30
code/dmute_0_1/a.cpp.tk                             |  28
code/dmute_1_1/b.cpp.tk                             |  49
code/dmute_2_1/c2.cpp.tk                            |  61
code/fagu_0_1/A.cpp.tk                              |  11
code/fagu_1_1/B.cpp.tk                              |  12
code/fagu_2_1/C.cpp.tk                              |  24
code/FatalEagle_0_1/main.cpp.tk                     |  34
code/FatalEagle_1_1/main.cpp.tk                     |  60
code/FatalEagle_2_1/main.cpp.tk                     |  157
code/fullpower_0_1/A.cpp.tk                         |  38
code/fullpower_1_1/B.cpp.tk                         |  67
code/fullpower_2_1/C.cpp.tk                         |  93
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  4809
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  579
code/ICastro_2_1/Dijkstra.cpp.tk                    |  203
code/ilackthatsuperpower_0_1/a.cpp.tk               |  105
code/ilackthatsuperpower_1_1/b.cpp.tk               |  88
code/ilackthatsuperpower_2_1/c.cpp.tk               |  97
code/iridescent_0_1/A.cpp.tk                        |  47
code/iridescent_1_1/B.cpp.tk                        |  69
code/iridescent_2_1/C.cpp.tk                        |  59
code/ishraq_0_1/main.cpp.tk                         |  11
code/ishraq_1_1/main.cpp.tk                         |  22
code/ishraq_2_1/main.cpp.tk                         |  32
code/JayXon_0_1/A.cpp.tk                            |  21
code/JayXon_1_1/B.cpp.tk                            |  37
code/JayXon_2_1/C.cpp.tk                            |  23
code/Josse_0_1/A.cpp.tk                             |  48
code/Josse_1_1/B.cpp.tk                             |  45
code/Josse_2_1/C.cpp.tk                             |  88
code/kcm1700_0_1/a.cpp.tk                           |  48
code/kcm1700_1_1/b.cpp.tk                           |  40
code/kcm1700_2_1/c.cpp.tk                           |  63
code/kevinsogo_0_1/a.cpp.tk                         |  10
code/kevinsogo_1_1/b.cpp.tk                         |  14
code/kevinsogo_2_1/c.cpp.tk                         |  33
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  8
code/LazyAnna_0_1/1.cpp.tk                          |  107
code/LazyAnna_1_1/2-1.cpp.tk                        |  83
code/LazyAnna_2_1/3.cpp.tk                          |  40
code/Merkurev_0_1/A.cpp.tk                          |  57
code/Merkurev_1_1/B.cpp.tk                          |  49
code/Merkurev_2_1/C.cpp.tk                          |  56
code/mezei_0_1/main.cpp.tk                          |  51
code/mezei_1_1/main.cpp.tk                          |  36
code/mezei_2_1/main.cpp.tk                          |  60
code/Mister_0_1/a.cpp.tk                            |  42
code/Mister_1_1/b.cpp.tk                            |  56
code/Mister_2_1/c.cpp.tk                            |  79
code/namonakiacc_0_1/cpp.cpp.tk                     |  24
code/namonakiacc_1_1/cpp.cpp.tk                     |  20
code/namonakiacc_2_1/cpp.cpp.tk                     |  31
code/Nicolas16_0_1/main.cpp.tk                      |  11
code/Nicolas16_1_1/main.cpp.tk                      |  11
code/Nicolas16_2_1/main.cpp.tk                      |  75
code/pandamonium_0_1/a.cpp.tk                       |  27
code/pandamonium_1_1/b.cpp.tk                       |  46
code/pandamonium_2_1/c.cpp.tk                       |  35
code/pflueger_0_1/A.cpp.tk                          |  68
code/pflueger_1_1/B.cpp.tk                          |  63
code/pflueger_2_1/C.cpp.tk                          |  76
code/ponyopoppo_0_1/A.cpp.tk                        |  18
code/ponyopoppo_1_1/B.cpp.tk                        |  17
code/ponyopoppo_2_1/C.cpp.tk                        |  57
code/Ragnar_0_1/A.cpp.tk                            |  21
code/Ragnar_1_1/B-2.cpp.tk                          |  26
code/Ragnar_2_1/C.cpp.tk                            |  44
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  8
code/saffah_2_1/t.cpp.tk                            |  39
code/SamanSami_0_1/A.cpp.tk                         |  18
code/SamanSami_1_1/B.cpp.tk                         |  68
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  35
code/Savlik_1_1/code.cpp.tk                         |  6
code/Savlik_2_1/code.cpp.tk                         |  38
code/shik_0_1/pa.cpp.tk                             |  36
code/shik_1_1/pb.cpp.tk                             |  34
code/shik_2_1/pc.cpp.tk                             |  55
code/simsa.st_0_1/A.cpp.tk                          |  11
code/simsa.st_1_1/B.cpp.tk                          |  8
code/simsa.st_2_1/C.cpp.tk                          |  34
code/SovietUnion_0_1/A.cpp.tk                       |  62
code/SovietUnion_1_1/B.cpp.tk                       |  94
code/SovietUnion_2_1/C.cpp.tk                       |  56
code/tailed_0_1/A.cpp.tk                            |  61
code/tailed_1_1/B.cpp.tk                            |  40
code/tailed_2_1/C.cpp.tk                            |  30
code/TheNatural_0_1/A.cpp.tk                        |  59
code/TheNatural_1_1/B.cpp.tk                        |  62
code/TheNatural_2_1/C.cpp.tk                        |  36
code/TrueBamboo_0_1/test.cpp.tk                     |  16
code/TrueBamboo_1_1/test.cpp.tk                     |  19
code/TrueBamboo_2_1/test.cpp.tk                     |  28
code/tur.turczyn_0_1/A.cpp.tk                       |  22
code/tur.turczyn_1_1/B.cpp.tk                       |  21
code/tur.turczyn_2_1/C.cpp.tk                       |  25
code/Tyg3R_0_1/A.cpp.tk                             |  13
code/Tyg3R_1_1/B.cpp.tk                             |  13
code/Tyg3R_2_1/C.cpp.tk                             |  30
code/UminchuR_0_1/main.cpp.tk                       |  36
code/UminchuR_1_1/main.cpp.tk                       |  20
code/UminchuR_2_1/main.cpp.tk                       |  41
code/wo..._0_1/a.cpp.tk                             |  43
code/wo..._1_1/b.cpp.tk                             |  46
code/wo..._2_1/c.cpp.tk                             |  80
code/yswtt_0_1/A.cpp.tk                             |  64
code/yswtt_1_1/B.cpp.tk                             |  90
code/yswtt_2_1/C.cpp.tk                             |  84
code/ZhSh_0_1/a.cpp.tk                              |  109
code/ZhSh_1_1/b.cpp.tk                              |  92
code/ZhSh_2_1/c.cpp.tk                              |  82
