Begin
Comparing:  code/Mister_0_1/a.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  36
code/551100kk_1_1/B.cpp.tk                          |  37
code/551100kk_2_1/C.cpp.tk                          |  49
code/achan1058_0_1/Q-A.cpp.tk                       |  10
code/achan1058_1_1/source.cpp.tk                    |  17
code/achan1058_2_1/source.cpp.tk                    |  42
code/alanubi_0_1/a.cpp.tk                           |  78
code/alanubi_1_1/b.cpp.tk                           |  101
code/alanubi_2_1/c.cpp.tk                           |  129
code/AntiForest_0_1/q1.cpp.tk                       |  28
code/AntiForest_1_1/q2.cpp.tk                       |  13
code/AntiForest_2_1/q3.cpp.tk                       |  54
code/apiad_0_1/A.cpp.tk                             |  27
code/apiad_1_1/B.cpp.tk                             |  24
code/apiad_2_1/C.cpp.tk                             |  30
code/azaky_0_1/A.cpp.tk                             |  23
code/azaky_1_1/B.cpp.tk                             |  26
code/azaky_2_1/C.cpp.tk                             |  53
code/azariamuh_0_1/standing.cpp.tk                  |  18
code/azariamuh_1_1/pancake.cpp.tk                   |  29
code/azariamuh_2_1/dijkstra.cpp.tk                  |  21
code/bmerry_0_1/a.cpp.tk                            |  51
code/bmerry_1_1/b.cpp.tk                            |  64
code/bmerry_2_1/c.cpp.tk                            |  57
code/climpet_0_1/A.cpp.tk                           |  90
code/climpet_1_1/B.cpp.tk                           |  72
code/climpet_2_1/C.cpp.tk                           |  92
code/ctzsm_0_1/A.cpp.tk                             |  202
code/ctzsm_1_1/B.cpp.tk                             |  114
code/ctzsm_2_1/C.cpp.tk                             |  161
code/DanilC_0_1/problem.cpp.tk                      |  108
code/DanilC_1_1/problemB.cpp.tk                     |  99
code/DanilC_2_1/problemC.cpp.tk                     |  123
code/DEGwer_0_1/A.cpp.tk                            |  53
code/DEGwer_1_1/B.cpp.tk                            |  54
code/DEGwer_2_1/C.cpp.tk                            |  46
code/dmute_0_1/a.cpp.tk                             |  61
code/dmute_1_1/b.cpp.tk                             |  134
code/dmute_2_1/c2.cpp.tk                            |  103
code/fagu_0_1/A.cpp.tk                              |  28
code/fagu_1_1/B.cpp.tk                              |  25
code/fagu_2_1/C.cpp.tk                              |  45
code/FatalEagle_0_1/main.cpp.tk                     |  76
code/FatalEagle_1_1/main.cpp.tk                     |  93
code/FatalEagle_2_1/main.cpp.tk                     |  220
code/fullpower_0_1/A.cpp.tk                         |  90
code/fullpower_1_1/B.cpp.tk                         |  112
code/fullpower_2_1/C.cpp.tk                         |  167
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  49
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  46
code/ICastro_2_1/Dijkstra.cpp.tk                    |  101
code/ilackthatsuperpower_0_1/a.cpp.tk               |  111
code/ilackthatsuperpower_1_1/b.cpp.tk               |  80
code/ilackthatsuperpower_2_1/c.cpp.tk               |  91
code/iridescent_0_1/A.cpp.tk                        |  27
code/iridescent_1_1/B.cpp.tk                        |  58
code/iridescent_2_1/C.cpp.tk                        |  47
code/ishraq_0_1/main.cpp.tk                         |  38
code/ishraq_1_1/main.cpp.tk                         |  44
code/ishraq_2_1/main.cpp.tk                         |  66
code/JayXon_0_1/A.cpp.tk                            |  30
code/JayXon_1_1/B.cpp.tk                            |  45
code/JayXon_2_1/C.cpp.tk                            |  32
code/Josse_0_1/A.cpp.tk                             |  28
code/Josse_1_1/B.cpp.tk                             |  45
code/Josse_2_1/C.cpp.tk                             |  90
code/kcm1700_0_1/a.cpp.tk                           |  185
code/kcm1700_1_1/b.cpp.tk                           |  164
code/kcm1700_2_1/c.cpp.tk                           |  125
code/kevinsogo_0_1/a.cpp.tk                         |  54
code/kevinsogo_1_1/b.cpp.tk                         |  52
code/kevinsogo_2_1/c.cpp.tk                         |  55
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  71
code/LazyAnna_1_1/2-1.cpp.tk                        |  72
code/LazyAnna_2_1/3.cpp.tk                          |  59
code/Merkurev_0_1/A.cpp.tk                          |  109
code/Merkurev_1_1/B.cpp.tk                          |  99
code/Merkurev_2_1/C.cpp.tk                          |  108
code/mezei_0_1/main.cpp.tk                          |  82
code/mezei_1_1/main.cpp.tk                          |  58
code/mezei_2_1/main.cpp.tk                          |  107
code/Mister_0_1/a.cpp.tk                            |  4151
code/Mister_1_1/b.cpp.tk                            |  285
code/Mister_2_1/c.cpp.tk                            |  152
code/namonakiacc_0_1/cpp.cpp.tk                     |  32
code/namonakiacc_1_1/cpp.cpp.tk                     |  27
code/namonakiacc_2_1/cpp.cpp.tk                     |  50
code/Nicolas16_0_1/main.cpp.tk                      |  45
code/Nicolas16_1_1/main.cpp.tk                      |  40
code/Nicolas16_2_1/main.cpp.tk                      |  130
code/pandamonium_0_1/a.cpp.tk                       |  71
code/pandamonium_1_1/b.cpp.tk                       |  96
code/pandamonium_2_1/c.cpp.tk                       |  75
code/pflueger_0_1/A.cpp.tk                          |  38
code/pflueger_1_1/B.cpp.tk                          |  44
code/pflueger_2_1/C.cpp.tk                          |  74
code/ponyopoppo_0_1/A.cpp.tk                        |  13
code/ponyopoppo_1_1/B.cpp.tk                        |  18
code/ponyopoppo_2_1/C.cpp.tk                        |  102
code/Ragnar_0_1/A.cpp.tk                            |  12
code/Ragnar_1_1/B-2.cpp.tk                          |  20
code/Ragnar_2_1/C.cpp.tk                            |  39
code/saffah_0_1/t.cpp.tk                            |  52
code/saffah_1_1/t.cpp.tk                            |  46
code/saffah_2_1/t.cpp.tk                            |  65
code/SamanSami_0_1/A.cpp.tk                         |  13
code/SamanSami_1_1/B.cpp.tk                         |  40
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  21
code/Savlik_1_1/code.cpp.tk                         |  11
code/Savlik_2_1/code.cpp.tk                         |  54
code/shik_0_1/pa.cpp.tk                             |  44
code/shik_1_1/pb.cpp.tk                             |  45
code/shik_2_1/pc.cpp.tk                             |  75
code/simsa.st_0_1/A.cpp.tk                          |  29
code/simsa.st_1_1/B.cpp.tk                          |  35
code/simsa.st_2_1/C.cpp.tk                          |  77
code/SovietUnion_0_1/A.cpp.tk                       |  144
code/SovietUnion_1_1/B.cpp.tk                       |  186
code/SovietUnion_2_1/C.cpp.tk                       |  91
code/tailed_0_1/A.cpp.tk                            |  32
code/tailed_1_1/B.cpp.tk                            |  32
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  45
code/TheNatural_1_1/B.cpp.tk                        |  46
code/TheNatural_2_1/C.cpp.tk                        |  29
code/TrueBamboo_0_1/test.cpp.tk                     |  30
code/TrueBamboo_1_1/test.cpp.tk                     |  27
code/TrueBamboo_2_1/test.cpp.tk                     |  46
code/tur.turczyn_0_1/A.cpp.tk                       |  19
code/tur.turczyn_1_1/B.cpp.tk                       |  18
code/tur.turczyn_2_1/C.cpp.tk                       |  24
code/Tyg3R_0_1/A.cpp.tk                             |  24
code/Tyg3R_1_1/B.cpp.tk                             |  17
code/Tyg3R_2_1/C.cpp.tk                             |  21
code/UminchuR_0_1/main.cpp.tk                       |  31
code/UminchuR_1_1/main.cpp.tk                       |  34
code/UminchuR_2_1/main.cpp.tk                       |  54
code/wo..._0_1/a.cpp.tk                             |  89
code/wo..._1_1/b.cpp.tk                             |  108
code/wo..._2_1/c.cpp.tk                             |  134
code/yswtt_0_1/A.cpp.tk                             |  83
code/yswtt_1_1/B.cpp.tk                             |  94
code/yswtt_2_1/C.cpp.tk                             |  75
code/ZhSh_0_1/a.cpp.tk                              |  104
code/ZhSh_1_1/b.cpp.tk                              |  116
code/ZhSh_2_1/c.cpp.tk                              |  94
