Begin
Comparing:  code/AntiForest_2_1/q3.cpp.tk
code/00/test.cpp.tk                                 |  25
code/01/test.cpp.tk                                 |  25
code/551100kk_0_1/A.cpp.tk                          |  32
code/551100kk_1_1/B.cpp.tk                          |  48
code/551100kk_2_1/C.cpp.tk                          |  392
code/achan1058_0_1/Q-A.cpp.tk                       |  18
code/achan1058_1_1/source.cpp.tk                    |  39
code/achan1058_2_1/source.cpp.tk                    |  83
code/alanubi_0_1/a.cpp.tk                           |  21
code/alanubi_1_1/b.cpp.tk                           |  33
code/alanubi_2_1/c.cpp.tk                           |  129
code/AntiForest_0_1/q1.cpp.tk                       |  88
code/AntiForest_1_1/q2.cpp.tk                       |  68
code/AntiForest_2_1/q3.cpp.tk                       |  117616
code/apiad_0_1/A.cpp.tk                             |  29
code/apiad_1_1/B.cpp.tk                             |  43
code/apiad_2_1/C.cpp.tk                             |  112
code/azaky_0_1/A.cpp.tk                             |  45
code/azaky_1_1/B.cpp.tk                             |  53
code/azaky_2_1/C.cpp.tk                             |  152
code/azariamuh_0_1/standing.cpp.tk                  |  30
code/azariamuh_1_1/pancake.cpp.tk                   |  63
code/azariamuh_2_1/dijkstra.cpp.tk                  |  69
code/bmerry_0_1/a.cpp.tk                            |  68
code/bmerry_1_1/b.cpp.tk                            |  78
code/bmerry_2_1/c.cpp.tk                            |  112
code/climpet_0_1/A.cpp.tk                           |  38
code/climpet_1_1/B.cpp.tk                           |  45
code/climpet_2_1/C.cpp.tk                           |  119
code/ctzsm_0_1/A.cpp.tk                             |  47
code/ctzsm_1_1/B.cpp.tk                             |  57
code/ctzsm_2_1/C.cpp.tk                             |  217
code/DanilC_0_1/problem.cpp.tk                      |  40
code/DanilC_1_1/problemB.cpp.tk                     |  70
code/DanilC_2_1/problemC.cpp.tk                     |  149
code/DEGwer_0_1/A.cpp.tk                            |  33
code/DEGwer_1_1/B.cpp.tk                            |  36
code/DEGwer_2_1/C.cpp.tk                            |  476
code/dmute_0_1/a.cpp.tk                             |  16
code/dmute_1_1/b.cpp.tk                             |  31
code/dmute_2_1/c2.cpp.tk                            |  89
code/fagu_0_1/A.cpp.tk                              |  13
code/fagu_1_1/B.cpp.tk                              |  13
code/fagu_2_1/C.cpp.tk                              |  106
code/FatalEagle_0_1/main.cpp.tk                     |  36
code/FatalEagle_1_1/main.cpp.tk                     |  51
code/FatalEagle_2_1/main.cpp.tk                     |  277
code/fullpower_0_1/A.cpp.tk                         |  65
code/fullpower_1_1/B.cpp.tk                         |  70
code/fullpower_2_1/C.cpp.tk                         |  165
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  14
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  26
code/ICastro_2_1/Dijkstra.cpp.tk                    |  187
code/ilackthatsuperpower_0_1/a.cpp.tk               |  113
code/ilackthatsuperpower_1_1/b.cpp.tk               |  113
code/ilackthatsuperpower_2_1/c.cpp.tk               |  181
code/iridescent_0_1/A.cpp.tk                        |  14
code/iridescent_1_1/B.cpp.tk                        |  19
code/iridescent_2_1/C.cpp.tk                        |  69
code/ishraq_0_1/main.cpp.tk                         |  23
code/ishraq_1_1/main.cpp.tk                         |  29
code/ishraq_2_1/main.cpp.tk                         |  125
code/JayXon_0_1/A.cpp.tk                            |  12
code/JayXon_1_1/B.cpp.tk                            |  33
code/JayXon_2_1/C.cpp.tk                            |  62
code/Josse_0_1/A.cpp.tk                             |  17
code/Josse_1_1/B.cpp.tk                             |  27
code/Josse_2_1/C.cpp.tk                             |  130
code/kcm1700_0_1/a.cpp.tk                           |  19
code/kcm1700_1_1/b.cpp.tk                           |  28
code/kcm1700_2_1/c.cpp.tk                           |  107
code/kevinsogo_0_1/a.cpp.tk                         |  22
code/kevinsogo_1_1/b.cpp.tk                         |  27
code/kevinsogo_2_1/c.cpp.tk                         |  125
code/ksun48_0_1/A.cpp.tk                            |  6
code/ksun48_1_1/B.cpp.tk                            |  6
code/ksun48_2_1/C.cpp.tk                            |  29
code/LazyAnna_0_1/1.cpp.tk                          |  15
code/LazyAnna_1_1/2-1.cpp.tk                        |  22
code/LazyAnna_2_1/3.cpp.tk                          |  76
code/Merkurev_0_1/A.cpp.tk                          |  43
code/Merkurev_1_1/B.cpp.tk                          |  64
code/Merkurev_2_1/C.cpp.tk                          |  76
code/mezei_0_1/main.cpp.tk                          |  29
code/mezei_1_1/main.cpp.tk                          |  29
code/mezei_2_1/main.cpp.tk                          |  124
code/Mister_0_1/a.cpp.tk                            |  20
code/Mister_1_1/b.cpp.tk                            |  26
code/Mister_2_1/c.cpp.tk                            |  377
code/namonakiacc_0_1/cpp.cpp.tk                     |  37
code/namonakiacc_1_1/cpp.cpp.tk                     |  43
code/namonakiacc_2_1/cpp.cpp.tk                     |  288
code/Nicolas16_0_1/main.cpp.tk                      |  11
code/Nicolas16_1_1/main.cpp.tk                      |  11
code/Nicolas16_2_1/main.cpp.tk                      |  122
code/pandamonium_0_1/a.cpp.tk                       |  18
code/pandamonium_1_1/b.cpp.tk                       |  66
code/pandamonium_2_1/c.cpp.tk                       |  42
code/pflueger_0_1/A.cpp.tk                          |  15
code/pflueger_1_1/B.cpp.tk                          |  26
code/pflueger_2_1/C.cpp.tk                          |  97
code/ponyopoppo_0_1/A.cpp.tk                        |  16
code/ponyopoppo_1_1/B.cpp.tk                        |  33
code/ponyopoppo_2_1/C.cpp.tk                        |  221
code/Ragnar_0_1/A.cpp.tk                            |  20
code/Ragnar_1_1/B-2.cpp.tk                          |  30
code/Ragnar_2_1/C.cpp.tk                            |  66
code/saffah_0_1/t.cpp.tk                            |  28
code/saffah_1_1/t.cpp.tk                            |  38
code/saffah_2_1/t.cpp.tk                            |  150
code/SamanSami_0_1/A.cpp.tk                         |  4
code/SamanSami_1_1/B.cpp.tk                         |  21
code/SamanSami_2_1/C.cpp.tk                         |  18
code/Savlik_0_1/code.cpp.tk                         |  15
code/Savlik_1_1/code.cpp.tk                         |  20
code/Savlik_2_1/code.cpp.tk                         |  91
code/shik_0_1/pa.cpp.tk                             |  86
code/shik_1_1/pb.cpp.tk                             |  85
code/shik_2_1/pc.cpp.tk                             |  558
code/simsa.st_0_1/A.cpp.tk                          |  30
code/simsa.st_1_1/B.cpp.tk                          |  35
code/simsa.st_2_1/C.cpp.tk                          |  132
code/SovietUnion_0_1/A.cpp.tk                       |  54
code/SovietUnion_1_1/B.cpp.tk                       |  61
code/SovietUnion_2_1/C.cpp.tk                       |  125
code/tailed_0_1/A.cpp.tk                            |  14
code/tailed_1_1/B.cpp.tk                            |  21
code/tailed_2_1/C.cpp.tk                            |  84
code/TheNatural_0_1/A.cpp.tk                        |  18
code/TheNatural_1_1/B.cpp.tk                        |  23
code/TheNatural_2_1/C.cpp.tk                        |  68
code/TrueBamboo_0_1/test.cpp.tk                     |  25
code/TrueBamboo_1_1/test.cpp.tk                     |  32
code/TrueBamboo_2_1/test.cpp.tk                     |  90
code/tur.turczyn_0_1/A.cpp.tk                       |  17
code/tur.turczyn_1_1/B.cpp.tk                       |  29
code/tur.turczyn_2_1/C.cpp.tk                       |  65
code/Tyg3R_0_1/A.cpp.tk                             |  22
code/Tyg3R_1_1/B.cpp.tk                             |  51
code/Tyg3R_2_1/C.cpp.tk                             |  93
code/UminchuR_0_1/main.cpp.tk                       |  43
code/UminchuR_1_1/main.cpp.tk                       |  57
code/UminchuR_2_1/main.cpp.tk                       |  111
code/wo..._0_1/a.cpp.tk                             |  30
code/wo..._1_1/b.cpp.tk                             |  33
code/wo..._2_1/c.cpp.tk                             |  420
code/yswtt_0_1/A.cpp.tk                             |  11
code/yswtt_1_1/B.cpp.tk                             |  26
code/yswtt_2_1/C.cpp.tk                             |  68
code/ZhSh_0_1/a.cpp.tk                              |  13
code/ZhSh_1_1/b.cpp.tk                              |  85
code/ZhSh_2_1/c.cpp.tk                              |  253
