Begin
Comparing:  code/wo..._2_1/c.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  12
code/551100kk_1_1/B.cpp.tk                          |  24
code/551100kk_2_1/C.cpp.tk                          |  189
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  13
code/achan1058_2_1/source.cpp.tk                    |  36
code/alanubi_0_1/a.cpp.tk                           |  29
code/alanubi_1_1/b.cpp.tk                           |  51
code/alanubi_2_1/c.cpp.tk                           |  105
code/AntiForest_0_1/q1.cpp.tk                       |  13
code/AntiForest_1_1/q2.cpp.tk                       |  5
code/AntiForest_2_1/q3.cpp.tk                       |  197
code/apiad_0_1/A.cpp.tk                             |  12
code/apiad_1_1/B.cpp.tk                             |  16
code/apiad_2_1/C.cpp.tk                             |  82
code/azaky_0_1/A.cpp.tk                             |  13
code/azaky_1_1/B.cpp.tk                             |  16
code/azaky_2_1/C.cpp.tk                             |  64
code/azariamuh_0_1/standing.cpp.tk                  |  9
code/azariamuh_1_1/pancake.cpp.tk                   |  23
code/azariamuh_2_1/dijkstra.cpp.tk                  |  33
code/bmerry_0_1/a.cpp.tk                            |  43
code/bmerry_1_1/b.cpp.tk                            |  54
code/bmerry_2_1/c.cpp.tk                            |  65
code/climpet_0_1/A.cpp.tk                           |  22
code/climpet_1_1/B.cpp.tk                           |  27
code/climpet_2_1/C.cpp.tk                           |  59
code/ctzsm_0_1/A.cpp.tk                             |  20
code/ctzsm_1_1/B.cpp.tk                             |  30
code/ctzsm_2_1/C.cpp.tk                             |  114
code/DanilC_0_1/problem.cpp.tk                      |  27
code/DanilC_1_1/problemB.cpp.tk                     |  48
code/DanilC_2_1/problemC.cpp.tk                     |  71
code/DEGwer_0_1/A.cpp.tk                            |  30
code/DEGwer_1_1/B.cpp.tk                            |  36
code/DEGwer_2_1/C.cpp.tk                            |  197
code/dmute_0_1/a.cpp.tk                             |  27
code/dmute_1_1/b.cpp.tk                             |  55
code/dmute_2_1/c2.cpp.tk                            |  103
code/fagu_0_1/A.cpp.tk                              |  13
code/fagu_1_1/B.cpp.tk                              |  13
code/fagu_2_1/C.cpp.tk                              |  52
code/FatalEagle_0_1/main.cpp.tk                     |  30
code/FatalEagle_1_1/main.cpp.tk                     |  53
code/FatalEagle_2_1/main.cpp.tk                     |  269
code/fullpower_0_1/A.cpp.tk                         |  43
code/fullpower_1_1/B.cpp.tk                         |  68
code/fullpower_2_1/C.cpp.tk                         |  149
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  13
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  24
code/ICastro_2_1/Dijkstra.cpp.tk                    |  79
code/ilackthatsuperpower_0_1/a.cpp.tk               |  64
code/ilackthatsuperpower_1_1/b.cpp.tk               |  62
code/ilackthatsuperpower_2_1/c.cpp.tk               |  86
code/iridescent_0_1/A.cpp.tk                        |  15
code/iridescent_1_1/B.cpp.tk                        |  27
code/iridescent_2_1/C.cpp.tk                        |  55
code/ishraq_0_1/main.cpp.tk                         |  10
code/ishraq_1_1/main.cpp.tk                         |  16
code/ishraq_2_1/main.cpp.tk                         |  67
code/JayXon_0_1/A.cpp.tk                            |  11
code/JayXon_1_1/B.cpp.tk                            |  36
code/JayXon_2_1/C.cpp.tk                            |  28
code/Josse_0_1/A.cpp.tk                             |  23
code/Josse_1_1/B.cpp.tk                             |  37
code/Josse_2_1/C.cpp.tk                             |  92
code/kcm1700_0_1/a.cpp.tk                           |  31
code/kcm1700_1_1/b.cpp.tk                           |  49
code/kcm1700_2_1/c.cpp.tk                           |  83
code/kevinsogo_0_1/a.cpp.tk                         |  11
code/kevinsogo_1_1/b.cpp.tk                         |  14
code/kevinsogo_2_1/c.cpp.tk                         |  63
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  18
code/LazyAnna_0_1/1.cpp.tk                          |  14
code/LazyAnna_1_1/2-1.cpp.tk                        |  25
code/LazyAnna_2_1/3.cpp.tk                          |  38
code/Merkurev_0_1/A.cpp.tk                          |  41
code/Merkurev_1_1/B.cpp.tk                          |  60
code/Merkurev_2_1/C.cpp.tk                          |  69
code/mezei_0_1/main.cpp.tk                          |  36
code/mezei_1_1/main.cpp.tk                          |  36
code/mezei_2_1/main.cpp.tk                          |  84
code/Mister_0_1/a.cpp.tk                            |  21
code/Mister_1_1/b.cpp.tk                            |  31
code/Mister_2_1/c.cpp.tk                            |  186
code/namonakiacc_0_1/cpp.cpp.tk                     |  14
code/namonakiacc_1_1/cpp.cpp.tk                     |  16
code/namonakiacc_2_1/cpp.cpp.tk                     |  69
code/Nicolas16_0_1/main.cpp.tk                      |  17
code/Nicolas16_1_1/main.cpp.tk                      |  15
code/Nicolas16_2_1/main.cpp.tk                      |  105
code/pandamonium_0_1/a.cpp.tk                       |  28
code/pandamonium_1_1/b.cpp.tk                       |  59
code/pandamonium_2_1/c.cpp.tk                       |  56
code/pflueger_0_1/A.cpp.tk                          |  17
code/pflueger_1_1/B.cpp.tk                          |  34
code/pflueger_2_1/C.cpp.tk                          |  76
code/ponyopoppo_0_1/A.cpp.tk                        |  7
code/ponyopoppo_1_1/B.cpp.tk                        |  13
code/ponyopoppo_2_1/C.cpp.tk                        |  82
code/Ragnar_0_1/A.cpp.tk                            |  8
code/Ragnar_1_1/B-2.cpp.tk                          |  18
code/Ragnar_2_1/C.cpp.tk                            |  34
code/saffah_0_1/t.cpp.tk                            |  10
code/saffah_1_1/t.cpp.tk                            |  12
code/saffah_2_1/t.cpp.tk                            |  56
code/SamanSami_0_1/A.cpp.tk                         |  6
code/SamanSami_1_1/B.cpp.tk                         |  31
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  12
code/Savlik_1_1/code.cpp.tk                         |  8
code/Savlik_2_1/code.cpp.tk                         |  42
code/shik_0_1/pa.cpp.tk                             |  32
code/shik_1_1/pb.cpp.tk                             |  34
code/shik_2_1/pc.cpp.tk                             |  207
code/simsa.st_0_1/A.cpp.tk                          |  9
code/simsa.st_1_1/B.cpp.tk                          |  12
code/simsa.st_2_1/C.cpp.tk                          |  54
code/SovietUnion_0_1/A.cpp.tk                       |  23
code/SovietUnion_1_1/B.cpp.tk                       |  30
code/SovietUnion_2_1/C.cpp.tk                       |  46
code/tailed_0_1/A.cpp.tk                            |  12
code/tailed_1_1/B.cpp.tk                            |  18
code/tailed_2_1/C.cpp.tk                            |  37
code/TheNatural_0_1/A.cpp.tk                        |  25
code/TheNatural_1_1/B.cpp.tk                        |  36
code/TheNatural_2_1/C.cpp.tk                        |  43
code/TrueBamboo_0_1/test.cpp.tk                     |  16
code/TrueBamboo_1_1/test.cpp.tk                     |  21
code/TrueBamboo_2_1/test.cpp.tk                     |  39
code/tur.turczyn_0_1/A.cpp.tk                       |  7
code/tur.turczyn_1_1/B.cpp.tk                       |  11
code/tur.turczyn_2_1/C.cpp.tk                       |  29
code/Tyg3R_0_1/A.cpp.tk                             |  8
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  41
code/UminchuR_0_1/main.cpp.tk                       |  14
code/UminchuR_1_1/main.cpp.tk                       |  19
code/UminchuR_2_1/main.cpp.tk                       |  50
code/wo..._0_1/a.cpp.tk                             |  40
code/wo..._1_1/b.cpp.tk                             |  60
code/wo..._2_1/c.cpp.tk                             |  155362
code/yswtt_0_1/A.cpp.tk                             |  11
code/yswtt_1_1/B.cpp.tk                             |  23
code/yswtt_2_1/C.cpp.tk                             |  39
code/ZhSh_0_1/a.cpp.tk                              |  13
code/ZhSh_1_1/b.cpp.tk                              |  48
code/ZhSh_2_1/c.cpp.tk                              |  118
