Begin
Comparing:  code/pflueger_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  26
code/551100kk_1_1/B.cpp.tk                          |  45
code/551100kk_2_1/C.cpp.tk                          |  33
code/achan1058_0_1/Q-A.cpp.tk                       |  14
code/achan1058_1_1/source.cpp.tk                    |  30
code/achan1058_2_1/source.cpp.tk                    |  45
code/alanubi_0_1/a.cpp.tk                           |  101
code/alanubi_1_1/b.cpp.tk                           |  49
code/alanubi_2_1/c.cpp.tk                           |  131
code/AntiForest_0_1/q1.cpp.tk                       |  17
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  49
code/apiad_0_1/A.cpp.tk                             |  16
code/apiad_1_1/B.cpp.tk                             |  19
code/apiad_2_1/C.cpp.tk                             |  22
code/azaky_0_1/A.cpp.tk                             |  13
code/azaky_1_1/B.cpp.tk                             |  18
code/azaky_2_1/C.cpp.tk                             |  37
code/azariamuh_0_1/standing.cpp.tk                  |  28
code/azariamuh_1_1/pancake.cpp.tk                   |  19
code/azariamuh_2_1/dijkstra.cpp.tk                  |  17
code/bmerry_0_1/a.cpp.tk                            |  133
code/bmerry_1_1/b.cpp.tk                            |  91
code/bmerry_2_1/c.cpp.tk                            |  81
code/climpet_0_1/A.cpp.tk                           |  100
code/climpet_1_1/B.cpp.tk                           |  71
code/climpet_2_1/C.cpp.tk                           |  94
code/ctzsm_0_1/A.cpp.tk                             |  42
code/ctzsm_1_1/B.cpp.tk                             |  45
code/ctzsm_2_1/C.cpp.tk                             |  89
code/DanilC_0_1/problem.cpp.tk                      |  89
code/DanilC_1_1/problemB.cpp.tk                     |  78
code/DanilC_2_1/problemC.cpp.tk                     |  97
code/DEGwer_0_1/A.cpp.tk                            |  90
code/DEGwer_1_1/B.cpp.tk                            |  66
code/DEGwer_2_1/C.cpp.tk                            |  37
code/dmute_0_1/a.cpp.tk                             |  84
code/dmute_1_1/b.cpp.tk                             |  146
code/dmute_2_1/c2.cpp.tk                            |  139
code/fagu_0_1/A.cpp.tk                              |  14
code/fagu_1_1/B.cpp.tk                              |  14
code/fagu_2_1/C.cpp.tk                              |  29
code/FatalEagle_0_1/main.cpp.tk                     |  93
code/FatalEagle_1_1/main.cpp.tk                     |  160
code/FatalEagle_2_1/main.cpp.tk                     |  227
code/fullpower_0_1/A.cpp.tk                         |  113
code/fullpower_1_1/B.cpp.tk                         |  203
code/fullpower_2_1/C.cpp.tk                         |  234
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  76
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  67
code/ICastro_2_1/Dijkstra.cpp.tk                    |  84
code/ilackthatsuperpower_0_1/a.cpp.tk               |  117
code/ilackthatsuperpower_1_1/b.cpp.tk               |  114
code/ilackthatsuperpower_2_1/c.cpp.tk               |  88
code/iridescent_0_1/A.cpp.tk                        |  193
code/iridescent_1_1/B.cpp.tk                        |  293
code/iridescent_2_1/C.cpp.tk                        |  184
code/ishraq_0_1/main.cpp.tk                         |  18
code/ishraq_1_1/main.cpp.tk                         |  37
code/ishraq_2_1/main.cpp.tk                         |  40
code/JayXon_0_1/A.cpp.tk                            |  43
code/JayXon_1_1/B.cpp.tk                            |  68
code/JayXon_2_1/C.cpp.tk                            |  27
code/Josse_0_1/A.cpp.tk                             |  61
code/Josse_1_1/B.cpp.tk                             |  77
code/Josse_2_1/C.cpp.tk                             |  103
code/kcm1700_0_1/a.cpp.tk                           |  133
code/kcm1700_1_1/b.cpp.tk                           |  116
code/kcm1700_2_1/c.cpp.tk                           |  112
code/kevinsogo_0_1/a.cpp.tk                         |  12
code/kevinsogo_1_1/b.cpp.tk                         |  20
code/kevinsogo_2_1/c.cpp.tk                         |  40
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  10
code/LazyAnna_0_1/1.cpp.tk                          |  78
code/LazyAnna_1_1/2-1.cpp.tk                        |  69
code/LazyAnna_2_1/3.cpp.tk                          |  46
code/Merkurev_0_1/A.cpp.tk                          |  156
code/Merkurev_1_1/B.cpp.tk                          |  93
code/Merkurev_2_1/C.cpp.tk                          |  117
code/mezei_0_1/main.cpp.tk                          |  166
code/mezei_1_1/main.cpp.tk                          |  89
code/mezei_2_1/main.cpp.tk                          |  124
code/Mister_0_1/a.cpp.tk                            |  42
code/Mister_1_1/b.cpp.tk                            |  47
code/Mister_2_1/c.cpp.tk                            |  61
code/namonakiacc_0_1/cpp.cpp.tk                     |  26
code/namonakiacc_1_1/cpp.cpp.tk                     |  26
code/namonakiacc_2_1/cpp.cpp.tk                     |  40
code/Nicolas16_0_1/main.cpp.tk                      |  46
code/Nicolas16_1_1/main.cpp.tk                      |  46
code/Nicolas16_2_1/main.cpp.tk                      |  194
code/pandamonium_0_1/a.cpp.tk                       |  96
code/pandamonium_1_1/b.cpp.tk                       |  92
code/pandamonium_2_1/c.cpp.tk                       |  74
code/pflueger_0_1/A.cpp.tk                          |  3213
code/pflueger_1_1/B.cpp.tk                          |  213
code/pflueger_2_1/C.cpp.tk                          |  143
code/ponyopoppo_0_1/A.cpp.tk                        |  45
code/ponyopoppo_1_1/B.cpp.tk                        |  31
code/ponyopoppo_2_1/C.cpp.tk                        |  77
code/Ragnar_0_1/A.cpp.tk                            |  31
code/Ragnar_1_1/B-2.cpp.tk                          |  40
code/Ragnar_2_1/C.cpp.tk                            |  132
code/saffah_0_1/t.cpp.tk                            |  17
code/saffah_1_1/t.cpp.tk                            |  14
code/saffah_2_1/t.cpp.tk                            |  40
code/SamanSami_0_1/A.cpp.tk                         |  66
code/SamanSami_1_1/B.cpp.tk                         |  179
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  86
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  48
code/shik_0_1/pa.cpp.tk                             |  32
code/shik_1_1/pb.cpp.tk                             |  34
code/shik_2_1/pc.cpp.tk                             |  58
code/simsa.st_0_1/A.cpp.tk                          |  20
code/simsa.st_1_1/B.cpp.tk                          |  14
code/simsa.st_2_1/C.cpp.tk                          |  39
code/SovietUnion_0_1/A.cpp.tk                       |  55
code/SovietUnion_1_1/B.cpp.tk                       |  77
code/SovietUnion_2_1/C.cpp.tk                       |  54
code/tailed_0_1/A.cpp.tk                            |  107
code/tailed_1_1/B.cpp.tk                            |  126
code/tailed_2_1/C.cpp.tk                            |  58
code/TheNatural_0_1/A.cpp.tk                        |  189
code/TheNatural_1_1/B.cpp.tk                        |  157
code/TheNatural_2_1/C.cpp.tk                        |  89
code/TrueBamboo_0_1/test.cpp.tk                     |  57
code/TrueBamboo_1_1/test.cpp.tk                     |  46
code/TrueBamboo_2_1/test.cpp.tk                     |  55
code/tur.turczyn_0_1/A.cpp.tk                       |  32
code/tur.turczyn_1_1/B.cpp.tk                       |  35
code/tur.turczyn_2_1/C.cpp.tk                       |  35
code/Tyg3R_0_1/A.cpp.tk                             |  22
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  50
code/UminchuR_0_1/main.cpp.tk                       |  25
code/UminchuR_1_1/main.cpp.tk                       |  27
code/UminchuR_2_1/main.cpp.tk                       |  51
code/wo..._0_1/a.cpp.tk                             |  81
code/wo..._1_1/b.cpp.tk                             |  93
code/wo..._2_1/c.cpp.tk                             |  132
code/yswtt_0_1/A.cpp.tk                             |  107
code/yswtt_1_1/B.cpp.tk                             |  93
code/yswtt_2_1/C.cpp.tk                             |  150
code/ZhSh_0_1/a.cpp.tk                              |  257
code/ZhSh_1_1/b.cpp.tk                              |  122
code/ZhSh_2_1/c.cpp.tk                              |  103
