Begin
Comparing:  code/apiad_0_1/A.cpp.tk
code/00/test.cpp.tk                                 |  18
code/01/test.cpp.tk                                 |  18
code/551100kk_0_1/A.cpp.tk                          |  76
code/551100kk_1_1/B.cpp.tk                          |  39
code/551100kk_2_1/C.cpp.tk                          |  67
code/achan1058_0_1/Q-A.cpp.tk                       |  35
code/achan1058_1_1/source.cpp.tk                    |  52
code/achan1058_2_1/source.cpp.tk                    |  88
code/alanubi_0_1/a.cpp.tk                           |  29
code/alanubi_1_1/b.cpp.tk                           |  32
code/alanubi_2_1/c.cpp.tk                           |  155
code/AntiForest_0_1/q1.cpp.tk                       |  63
code/AntiForest_1_1/q2.cpp.tk                       |  21
code/AntiForest_2_1/q3.cpp.tk                       |  89
code/apiad_0_1/A.cpp.tk                             |  14829
code/apiad_1_1/B.cpp.tk                             |  1596
code/apiad_2_1/C.cpp.tk                             |  1402
code/azaky_0_1/A.cpp.tk                             |  64
code/azaky_1_1/B.cpp.tk                             |  48
code/azaky_2_1/C.cpp.tk                             |  106
code/azariamuh_0_1/standing.cpp.tk                  |  36
code/azariamuh_1_1/pancake.cpp.tk                   |  51
code/azariamuh_2_1/dijkstra.cpp.tk                  |  34
code/bmerry_0_1/a.cpp.tk                            |  83
code/bmerry_1_1/b.cpp.tk                            |  82
code/bmerry_2_1/c.cpp.tk                            |  91
code/climpet_0_1/A.cpp.tk                           |  55
code/climpet_1_1/B.cpp.tk                           |  56
code/climpet_2_1/C.cpp.tk                           |  86
code/ctzsm_0_1/A.cpp.tk                             |  52
code/ctzsm_1_1/B.cpp.tk                             |  34
code/ctzsm_2_1/C.cpp.tk                             |  117
code/DanilC_0_1/problem.cpp.tk                      |  44
code/DanilC_1_1/problemB.cpp.tk                     |  60
code/DanilC_2_1/problemC.cpp.tk                     |  147
code/DEGwer_0_1/A.cpp.tk                            |  38
code/DEGwer_1_1/B.cpp.tk                            |  38
code/DEGwer_2_1/C.cpp.tk                            |  48
code/dmute_0_1/a.cpp.tk                             |  72
code/dmute_1_1/b.cpp.tk                             |  35
code/dmute_2_1/c2.cpp.tk                            |  72
code/fagu_0_1/A.cpp.tk                              |  34
code/fagu_1_1/B.cpp.tk                              |  30
code/fagu_2_1/C.cpp.tk                              |  65
code/FatalEagle_0_1/main.cpp.tk                     |  45
code/FatalEagle_1_1/main.cpp.tk                     |  37
code/FatalEagle_2_1/main.cpp.tk                     |  181
code/fullpower_0_1/A.cpp.tk                         |  41
code/fullpower_1_1/B.cpp.tk                         |  50
code/fullpower_2_1/C.cpp.tk                         |  103
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  20
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  25
code/ICastro_2_1/Dijkstra.cpp.tk                    |  144
code/ilackthatsuperpower_0_1/a.cpp.tk               |  105
code/ilackthatsuperpower_1_1/b.cpp.tk               |  102
code/ilackthatsuperpower_2_1/c.cpp.tk               |  147
code/iridescent_0_1/A.cpp.tk                        |  19
code/iridescent_1_1/B.cpp.tk                        |  22
code/iridescent_2_1/C.cpp.tk                        |  32
code/ishraq_0_1/main.cpp.tk                         |  93
code/ishraq_1_1/main.cpp.tk                         |  29
code/ishraq_2_1/main.cpp.tk                         |  109
code/JayXon_0_1/A.cpp.tk                            |  22
code/JayXon_1_1/B.cpp.tk                            |  27
code/JayXon_2_1/C.cpp.tk                            |  50
code/Josse_0_1/A.cpp.tk                             |  25
code/Josse_1_1/B.cpp.tk                             |  27
code/Josse_2_1/C.cpp.tk                             |  113
code/kcm1700_0_1/a.cpp.tk                           |  32
code/kcm1700_1_1/b.cpp.tk                           |  29
code/kcm1700_2_1/c.cpp.tk                           |  74
code/kevinsogo_0_1/a.cpp.tk                         |  25
code/kevinsogo_1_1/b.cpp.tk                         |  28
code/kevinsogo_2_1/c.cpp.tk                         |  85
code/ksun48_0_1/A.cpp.tk                            |  6
code/ksun48_1_1/B.cpp.tk                            |  6
code/ksun48_2_1/C.cpp.tk                            |  21
code/LazyAnna_0_1/1.cpp.tk                          |  15
code/LazyAnna_1_1/2-1.cpp.tk                        |  20
code/LazyAnna_2_1/3.cpp.tk                          |  49
code/Merkurev_0_1/A.cpp.tk                          |  34
code/Merkurev_1_1/B.cpp.tk                          |  50
code/Merkurev_2_1/C.cpp.tk                          |  54
code/mezei_0_1/main.cpp.tk                          |  39
code/mezei_1_1/main.cpp.tk                          |  31
code/mezei_2_1/main.cpp.tk                          |  92
code/Mister_0_1/a.cpp.tk                            |  29
code/Mister_1_1/b.cpp.tk                            |  27
code/Mister_2_1/c.cpp.tk                            |  53
code/namonakiacc_0_1/cpp.cpp.tk                     |  88
code/namonakiacc_1_1/cpp.cpp.tk                     |  75
code/namonakiacc_2_1/cpp.cpp.tk                     |  115
code/Nicolas16_0_1/main.cpp.tk                      |  12
code/Nicolas16_1_1/main.cpp.tk                      |  11
code/Nicolas16_2_1/main.cpp.tk                      |  94
code/pandamonium_0_1/a.cpp.tk                       |  60
code/pandamonium_1_1/b.cpp.tk                       |  49
code/pandamonium_2_1/c.cpp.tk                       |  53
code/pflueger_0_1/A.cpp.tk                          |  16
code/pflueger_1_1/B.cpp.tk                          |  25
code/pflueger_2_1/C.cpp.tk                          |  73
code/ponyopoppo_0_1/A.cpp.tk                        |  24
code/ponyopoppo_1_1/B.cpp.tk                        |  34
code/ponyopoppo_2_1/C.cpp.tk                        |  155
code/Ragnar_0_1/A.cpp.tk                            |  36
code/Ragnar_1_1/B-2.cpp.tk                          |  41
code/Ragnar_2_1/C.cpp.tk                            |  64
code/saffah_0_1/t.cpp.tk                            |  36
code/saffah_1_1/t.cpp.tk                            |  29
code/saffah_2_1/t.cpp.tk                            |  125
code/SamanSami_0_1/A.cpp.tk                         |  6
code/SamanSami_1_1/B.cpp.tk                         |  22
code/SamanSami_2_1/C.cpp.tk                         |  15
code/Savlik_0_1/code.cpp.tk                         |  20
code/Savlik_1_1/code.cpp.tk                         |  19
code/Savlik_2_1/code.cpp.tk                         |  95
code/shik_0_1/pa.cpp.tk                             |  101
code/shik_1_1/pb.cpp.tk                             |  92
code/shik_2_1/pc.cpp.tk                             |  143
code/simsa.st_0_1/A.cpp.tk                          |  31
code/simsa.st_1_1/B.cpp.tk                          |  26
code/simsa.st_2_1/C.cpp.tk                          |  109
code/SovietUnion_0_1/A.cpp.tk                       |  68
code/SovietUnion_1_1/B.cpp.tk                       |  40
code/SovietUnion_2_1/C.cpp.tk                       |  99
code/tailed_0_1/A.cpp.tk                            |  21
code/tailed_1_1/B.cpp.tk                            |  21
code/tailed_2_1/C.cpp.tk                            |  56
code/TheNatural_0_1/A.cpp.tk                        |  23
code/TheNatural_1_1/B.cpp.tk                        |  25
code/TheNatural_2_1/C.cpp.tk                        |  35
code/TrueBamboo_0_1/test.cpp.tk                     |  34
code/TrueBamboo_1_1/test.cpp.tk                     |  31
code/TrueBamboo_2_1/test.cpp.tk                     |  69
code/tur.turczyn_0_1/A.cpp.tk                       |  48
code/tur.turczyn_1_1/B.cpp.tk                       |  48
code/tur.turczyn_2_1/C.cpp.tk                       |  58
code/Tyg3R_0_1/A.cpp.tk                             |  23
code/Tyg3R_1_1/B.cpp.tk                             |  33
code/Tyg3R_2_1/C.cpp.tk                             |  38
code/UminchuR_0_1/main.cpp.tk                       |  58
code/UminchuR_1_1/main.cpp.tk                       |  62
code/UminchuR_2_1/main.cpp.tk                       |  98
code/wo..._0_1/a.cpp.tk                             |  31
code/wo..._1_1/b.cpp.tk                             |  34
code/wo..._2_1/c.cpp.tk                             |  87
code/yswtt_0_1/A.cpp.tk                             |  18
code/yswtt_1_1/B.cpp.tk                             |  23
code/yswtt_2_1/C.cpp.tk                             |  54
code/ZhSh_0_1/a.cpp.tk                              |  20
code/ZhSh_1_1/b.cpp.tk                              |  88
code/ZhSh_2_1/c.cpp.tk                              |  108
