Begin
Comparing:  code/JayXon_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  13
code/551100kk_1_1/B.cpp.tk                          |  20
code/551100kk_2_1/C.cpp.tk                          |  45
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  17
code/achan1058_2_1/source.cpp.tk                    |  58
code/alanubi_0_1/a.cpp.tk                           |  8
code/alanubi_1_1/b.cpp.tk                           |  12
code/alanubi_2_1/c.cpp.tk                           |  64
code/AntiForest_0_1/q1.cpp.tk                       |  12
code/AntiForest_1_1/q2.cpp.tk                       |  5
code/AntiForest_2_1/q3.cpp.tk                       |  53
code/apiad_0_1/A.cpp.tk                             |  14
code/apiad_1_1/B.cpp.tk                             |  17
code/apiad_2_1/C.cpp.tk                             |  24
code/azaky_0_1/A.cpp.tk                             |  14
code/azaky_1_1/B.cpp.tk                             |  16
code/azaky_2_1/C.cpp.tk                             |  46
code/azariamuh_0_1/standing.cpp.tk                  |  9
code/azariamuh_1_1/pancake.cpp.tk                   |  19
code/azariamuh_2_1/dijkstra.cpp.tk                  |  24
code/bmerry_0_1/a.cpp.tk                            |  37
code/bmerry_1_1/b.cpp.tk                            |  42
code/bmerry_2_1/c.cpp.tk                            |  45
code/climpet_0_1/A.cpp.tk                           |  23
code/climpet_1_1/B.cpp.tk                           |  26
code/climpet_2_1/C.cpp.tk                           |  48
code/ctzsm_0_1/A.cpp.tk                             |  12
code/ctzsm_1_1/B.cpp.tk                             |  15
code/ctzsm_2_1/C.cpp.tk                             |  64
code/DanilC_0_1/problem.cpp.tk                      |  22
code/DanilC_1_1/problemB.cpp.tk                     |  33
code/DanilC_2_1/problemC.cpp.tk                     |  94
code/DEGwer_0_1/A.cpp.tk                            |  14
code/DEGwer_1_1/B.cpp.tk                            |  16
code/DEGwer_2_1/C.cpp.tk                            |  33
code/dmute_0_1/a.cpp.tk                             |  8
code/dmute_1_1/b.cpp.tk                             |  14
code/dmute_2_1/c2.cpp.tk                            |  41
code/fagu_0_1/A.cpp.tk                              |  4
code/fagu_1_1/B.cpp.tk                              |  4
code/fagu_2_1/C.cpp.tk                              |  25
code/FatalEagle_0_1/main.cpp.tk                     |  11
code/FatalEagle_1_1/main.cpp.tk                     |  18
code/FatalEagle_2_1/main.cpp.tk                     |  116
code/fullpower_0_1/A.cpp.tk                         |  17
code/fullpower_1_1/B.cpp.tk                         |  21
code/fullpower_2_1/C.cpp.tk                         |  66
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  8
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  13
code/ICastro_2_1/Dijkstra.cpp.tk                    |  92
code/ilackthatsuperpower_0_1/a.cpp.tk               |  71
code/ilackthatsuperpower_1_1/b.cpp.tk               |  75
code/ilackthatsuperpower_2_1/c.cpp.tk               |  123
code/iridescent_0_1/A.cpp.tk                        |  9
code/iridescent_1_1/B.cpp.tk                        |  9
code/iridescent_2_1/C.cpp.tk                        |  14
code/ishraq_0_1/main.cpp.tk                         |  8
code/ishraq_1_1/main.cpp.tk                         |  11
code/ishraq_2_1/main.cpp.tk                         |  55
code/JayXon_0_1/A.cpp.tk                            |  10
code/JayXon_1_1/B.cpp.tk                            |  19
code/JayXon_2_1/C.cpp.tk                            |  42220
code/Josse_0_1/A.cpp.tk                             |  9
code/Josse_1_1/B.cpp.tk                             |  12
code/Josse_2_1/C.cpp.tk                             |  68
code/kcm1700_0_1/a.cpp.tk                           |  7
code/kcm1700_1_1/b.cpp.tk                           |  10
code/kcm1700_2_1/c.cpp.tk                           |  38
code/kevinsogo_0_1/a.cpp.tk                         |  8
code/kevinsogo_1_1/b.cpp.tk                         |  12
code/kevinsogo_2_1/c.cpp.tk                         |  45
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  24
code/LazyAnna_0_1/1.cpp.tk                          |  6
code/LazyAnna_1_1/2-1.cpp.tk                        |  10
code/LazyAnna_2_1/3.cpp.tk                          |  29
code/Merkurev_0_1/A.cpp.tk                          |  11
code/Merkurev_1_1/B.cpp.tk                          |  24
code/Merkurev_2_1/C.cpp.tk                          |  25
code/mezei_0_1/main.cpp.tk                          |  10
code/mezei_1_1/main.cpp.tk                          |  11
code/mezei_2_1/main.cpp.tk                          |  63
code/Mister_0_1/a.cpp.tk                            |  10
code/Mister_1_1/b.cpp.tk                            |  10
code/Mister_2_1/c.cpp.tk                            |  23
code/namonakiacc_0_1/cpp.cpp.tk                     |  14
code/namonakiacc_1_1/cpp.cpp.tk                     |  16
code/namonakiacc_2_1/cpp.cpp.tk                     |  42
code/Nicolas16_0_1/main.cpp.tk                      |  3
code/Nicolas16_1_1/main.cpp.tk                      |  3
code/Nicolas16_2_1/main.cpp.tk                      |  64
code/pandamonium_0_1/a.cpp.tk                       |  10
code/pandamonium_1_1/b.cpp.tk                       |  29
code/pandamonium_2_1/c.cpp.tk                       |  17
code/pflueger_0_1/A.cpp.tk                          |  7
code/pflueger_1_1/B.cpp.tk                          |  12
code/pflueger_2_1/C.cpp.tk                          |  74
code/ponyopoppo_0_1/A.cpp.tk                        |  8
code/ponyopoppo_1_1/B.cpp.tk                        |  21
code/ponyopoppo_2_1/C.cpp.tk                        |  152
code/Ragnar_0_1/A.cpp.tk                            |  10
code/Ragnar_1_1/B-2.cpp.tk                          |  15
code/Ragnar_2_1/C.cpp.tk                            |  31
code/saffah_0_1/t.cpp.tk                            |  8
code/saffah_1_1/t.cpp.tk                            |  11
code/saffah_2_1/t.cpp.tk                            |  70
code/SamanSami_0_1/A.cpp.tk                         |  2
code/SamanSami_1_1/B.cpp.tk                         |  10
code/SamanSami_2_1/C.cpp.tk                         |  19
code/Savlik_0_1/code.cpp.tk                         |  9
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  72
code/shik_0_1/pa.cpp.tk                             |  51
code/shik_1_1/pb.cpp.tk                             |  52
code/shik_2_1/pc.cpp.tk                             |  86
code/simsa.st_0_1/A.cpp.tk                          |  10
code/simsa.st_1_1/B.cpp.tk                          |  12
code/simsa.st_2_1/C.cpp.tk                          |  79
code/SovietUnion_0_1/A.cpp.tk                       |  13
code/SovietUnion_1_1/B.cpp.tk                       |  16
code/SovietUnion_2_1/C.cpp.tk                       |  69
code/tailed_0_1/A.cpp.tk                            |  8
code/tailed_1_1/B.cpp.tk                            |  11
code/tailed_2_1/C.cpp.tk                            |  39
code/TheNatural_0_1/A.cpp.tk                        |  7
code/TheNatural_1_1/B.cpp.tk                        |  9
code/TheNatural_2_1/C.cpp.tk                        |  20
code/TrueBamboo_0_1/test.cpp.tk                     |  12
code/TrueBamboo_1_1/test.cpp.tk                     |  18
code/TrueBamboo_2_1/test.cpp.tk                     |  60
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  15
code/tur.turczyn_2_1/C.cpp.tk                       |  25
code/Tyg3R_0_1/A.cpp.tk                             |  10
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  16
code/UminchuR_0_1/main.cpp.tk                       |  19
code/UminchuR_1_1/main.cpp.tk                       |  22
code/UminchuR_2_1/main.cpp.tk                       |  44
code/wo..._0_1/a.cpp.tk                             |  9
code/wo..._1_1/b.cpp.tk                             |  14
code/wo..._2_1/c.cpp.tk                             |  54
code/yswtt_0_1/A.cpp.tk                             |  7
code/yswtt_1_1/B.cpp.tk                             |  13
code/yswtt_2_1/C.cpp.tk                             |  46
code/ZhSh_0_1/a.cpp.tk                              |  6
code/ZhSh_1_1/b.cpp.tk                              |  48
code/ZhSh_2_1/c.cpp.tk                              |  69
