Begin
Comparing:  code/Savlik_1_1/code.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  21
code/551100kk_1_1/B.cpp.tk                          |  35
code/551100kk_2_1/C.cpp.tk                          |  60
code/achan1058_0_1/Q-A.cpp.tk                       |  13
code/achan1058_1_1/source.cpp.tk                    |  48
code/achan1058_2_1/source.cpp.tk                    |  94
code/alanubi_0_1/a.cpp.tk                           |  14
code/alanubi_1_1/b.cpp.tk                           |  21
code/alanubi_2_1/c.cpp.tk                           |  114
code/AntiForest_0_1/q1.cpp.tk                       |  34
code/AntiForest_1_1/q2.cpp.tk                       |  18
code/AntiForest_2_1/q3.cpp.tk                       |  85
code/apiad_0_1/A.cpp.tk                             |  26
code/apiad_1_1/B.cpp.tk                             |  51
code/apiad_2_1/C.cpp.tk                             |  40
code/azaky_0_1/A.cpp.tk                             |  32
code/azaky_1_1/B.cpp.tk                             |  51
code/azaky_2_1/C.cpp.tk                             |  93
code/azariamuh_0_1/standing.cpp.tk                  |  23
code/azariamuh_1_1/pancake.cpp.tk                   |  57
code/azariamuh_2_1/dijkstra.cpp.tk                  |  36
code/bmerry_0_1/a.cpp.tk                            |  65
code/bmerry_1_1/b.cpp.tk                            |  86
code/bmerry_2_1/c.cpp.tk                            |  76
code/climpet_0_1/A.cpp.tk                           |  38
code/climpet_1_1/B.cpp.tk                           |  49
code/climpet_2_1/C.cpp.tk                           |  72
code/ctzsm_0_1/A.cpp.tk                             |  21
code/ctzsm_1_1/B.cpp.tk                             |  34
code/ctzsm_2_1/C.cpp.tk                             |  101
code/DanilC_0_1/problem.cpp.tk                      |  40
code/DanilC_1_1/problemB.cpp.tk                     |  64
code/DanilC_2_1/problemC.cpp.tk                     |  189
code/DEGwer_0_1/A.cpp.tk                            |  30
code/DEGwer_1_1/B.cpp.tk                            |  38
code/DEGwer_2_1/C.cpp.tk                            |  44
code/dmute_0_1/a.cpp.tk                             |  12
code/dmute_1_1/b.cpp.tk                             |  18
code/dmute_2_1/c2.cpp.tk                            |  48
code/fagu_0_1/A.cpp.tk                              |  12
code/fagu_1_1/B.cpp.tk                              |  13
code/fagu_2_1/C.cpp.tk                              |  65
code/FatalEagle_0_1/main.cpp.tk                     |  18
code/FatalEagle_1_1/main.cpp.tk                     |  49
code/FatalEagle_2_1/main.cpp.tk                     |  198
code/fullpower_0_1/A.cpp.tk                         |  36
code/fullpower_1_1/B.cpp.tk                         |  39
code/fullpower_2_1/C.cpp.tk                         |  86
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  11
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  25
code/ICastro_2_1/Dijkstra.cpp.tk                    |  171
code/ilackthatsuperpower_0_1/a.cpp.tk               |  133
code/ilackthatsuperpower_1_1/b.cpp.tk               |  212
code/ilackthatsuperpower_2_1/c.cpp.tk               |  182
code/iridescent_0_1/A.cpp.tk                        |  11
code/iridescent_1_1/B.cpp.tk                        |  14
code/iridescent_2_1/C.cpp.tk                        |  19
code/ishraq_0_1/main.cpp.tk                         |  19
code/ishraq_1_1/main.cpp.tk                         |  29
code/ishraq_2_1/main.cpp.tk                         |  121
code/JayXon_0_1/A.cpp.tk                            |  8
code/JayXon_1_1/B.cpp.tk                            |  26
code/JayXon_2_1/C.cpp.tk                            |  50
code/Josse_0_1/A.cpp.tk                             |  15
code/Josse_1_1/B.cpp.tk                             |  23
code/Josse_2_1/C.cpp.tk                             |  120
code/kcm1700_0_1/a.cpp.tk                           |  11
code/kcm1700_1_1/b.cpp.tk                           |  21
code/kcm1700_2_1/c.cpp.tk                           |  75
code/kevinsogo_0_1/a.cpp.tk                         |  32
code/kevinsogo_1_1/b.cpp.tk                         |  44
code/kevinsogo_2_1/c.cpp.tk                         |  96
code/ksun48_0_1/A.cpp.tk                            |  7
code/ksun48_1_1/B.cpp.tk                            |  7
code/ksun48_2_1/C.cpp.tk                            |  19
code/LazyAnna_0_1/1.cpp.tk                          |  10
code/LazyAnna_1_1/2-1.cpp.tk                        |  17
code/LazyAnna_2_1/3.cpp.tk                          |  53
code/Merkurev_0_1/A.cpp.tk                          |  20
code/Merkurev_1_1/B.cpp.tk                          |  79
code/Merkurev_2_1/C.cpp.tk                          |  47
code/mezei_0_1/main.cpp.tk                          |  24
code/mezei_1_1/main.cpp.tk                          |  25
code/mezei_2_1/main.cpp.tk                          |  74
code/Mister_0_1/a.cpp.tk                            |  17
code/Mister_1_1/b.cpp.tk                            |  43
code/Mister_2_1/c.cpp.tk                            |  40
code/namonakiacc_0_1/cpp.cpp.tk                     |  37
code/namonakiacc_1_1/cpp.cpp.tk                     |  102
code/namonakiacc_2_1/cpp.cpp.tk                     |  81
code/Nicolas16_0_1/main.cpp.tk                      |  10
code/Nicolas16_1_1/main.cpp.tk                      |  10
code/Nicolas16_2_1/main.cpp.tk                      |  70
code/pandamonium_0_1/a.cpp.tk                       |  14
code/pandamonium_1_1/b.cpp.tk                       |  51
code/pandamonium_2_1/c.cpp.tk                       |  23
code/pflueger_0_1/A.cpp.tk                          |  12
code/pflueger_1_1/B.cpp.tk                          |  21
code/pflueger_2_1/C.cpp.tk                          |  62
code/ponyopoppo_0_1/A.cpp.tk                        |  25
code/ponyopoppo_1_1/B.cpp.tk                        |  56
code/ponyopoppo_2_1/C.cpp.tk                        |  210
code/Ragnar_0_1/A.cpp.tk                            |  29
code/Ragnar_1_1/B-2.cpp.tk                          |  47
code/Ragnar_2_1/C.cpp.tk                            |  66
code/saffah_0_1/t.cpp.tk                            |  22
code/saffah_1_1/t.cpp.tk                            |  45
code/saffah_2_1/t.cpp.tk                            |  127
code/SamanSami_0_1/A.cpp.tk                         |  6
code/SamanSami_1_1/B.cpp.tk                         |  20
code/SamanSami_2_1/C.cpp.tk                         |  19
code/Savlik_0_1/code.cpp.tk                         |  88
code/Savlik_1_1/code.cpp.tk                         |  2234
code/Savlik_2_1/code.cpp.tk                         |  105
code/shik_0_1/pa.cpp.tk                             |  93
code/shik_1_1/pb.cpp.tk                             |  136
code/shik_2_1/pc.cpp.tk                             |  136
code/simsa.st_0_1/A.cpp.tk                          |  21
code/simsa.st_1_1/B.cpp.tk                          |  66
code/simsa.st_2_1/C.cpp.tk                          |  134
code/SovietUnion_0_1/A.cpp.tk                       |  20
code/SovietUnion_1_1/B.cpp.tk                       |  25
code/SovietUnion_2_1/C.cpp.tk                       |  99
code/tailed_0_1/A.cpp.tk                            |  14
code/tailed_1_1/B.cpp.tk                            |  23
code/tailed_2_1/C.cpp.tk                            |  50
code/TheNatural_0_1/A.cpp.tk                        |  11
code/TheNatural_1_1/B.cpp.tk                        |  15
code/TheNatural_2_1/C.cpp.tk                        |  26
code/TrueBamboo_0_1/test.cpp.tk                     |  21
code/TrueBamboo_1_1/test.cpp.tk                     |  33
code/TrueBamboo_2_1/test.cpp.tk                     |  65
code/tur.turczyn_0_1/A.cpp.tk                       |  28
code/tur.turczyn_1_1/B.cpp.tk                       |  62
code/tur.turczyn_2_1/C.cpp.tk                       |  49
code/Tyg3R_0_1/A.cpp.tk                             |  37
code/Tyg3R_1_1/B.cpp.tk                             |  48
code/Tyg3R_2_1/C.cpp.tk                             |  34
code/UminchuR_0_1/main.cpp.tk                       |  40
code/UminchuR_1_1/main.cpp.tk                       |  73
code/UminchuR_2_1/main.cpp.tk                       |  84
code/wo..._0_1/a.cpp.tk                             |  16
code/wo..._1_1/b.cpp.tk                             |  19
code/wo..._2_1/c.cpp.tk                             |  70
code/yswtt_0_1/A.cpp.tk                             |  9
code/yswtt_1_1/B.cpp.tk                             |  23
code/yswtt_2_1/C.cpp.tk                             |  39
code/ZhSh_0_1/a.cpp.tk                              |  11
code/ZhSh_1_1/b.cpp.tk                              |  85
code/ZhSh_2_1/c.cpp.tk                              |  115
