Begin
Comparing:  code/SamanSami_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  18
code/551100kk_1_1/B.cpp.tk                          |  44
code/551100kk_2_1/C.cpp.tk                          |  42
code/achan1058_0_1/Q-A.cpp.tk                       |  10
code/achan1058_1_1/source.cpp.tk                    |  26
code/achan1058_2_1/source.cpp.tk                    |  33
code/alanubi_0_1/a.cpp.tk                           |  61
code/alanubi_1_1/b.cpp.tk                           |  101
code/alanubi_2_1/c.cpp.tk                           |  179
code/AntiForest_0_1/q1.cpp.tk                       |  12
code/AntiForest_1_1/q2.cpp.tk                       |  4
code/AntiForest_2_1/q3.cpp.tk                       |  44
code/apiad_0_1/A.cpp.tk                             |  14
code/apiad_1_1/B.cpp.tk                             |  15
code/apiad_2_1/C.cpp.tk                             |  23
code/azaky_0_1/A.cpp.tk                             |  11
code/azaky_1_1/B.cpp.tk                             |  17
code/azaky_2_1/C.cpp.tk                             |  33
code/azariamuh_0_1/standing.cpp.tk                  |  12
code/azariamuh_1_1/pancake.cpp.tk                   |  24
code/azariamuh_2_1/dijkstra.cpp.tk                  |  15
code/bmerry_0_1/a.cpp.tk                            |  95
code/bmerry_1_1/b.cpp.tk                            |  165
code/bmerry_2_1/c.cpp.tk                            |  107
code/climpet_0_1/A.cpp.tk                           |  57
code/climpet_1_1/B.cpp.tk                           |  69
code/climpet_2_1/C.cpp.tk                           |  94
code/ctzsm_0_1/A.cpp.tk                             |  35
code/ctzsm_1_1/B.cpp.tk                             |  59
code/ctzsm_2_1/C.cpp.tk                             |  98
code/DanilC_0_1/problem.cpp.tk                      |  64
code/DanilC_1_1/problemB.cpp.tk                     |  96
code/DanilC_2_1/problemC.cpp.tk                     |  91
code/DEGwer_0_1/A.cpp.tk                            |  78
code/DEGwer_1_1/B.cpp.tk                            |  175
code/DEGwer_2_1/C.cpp.tk                            |  63
code/dmute_0_1/a.cpp.tk                             |  48
code/dmute_1_1/b.cpp.tk                             |  104
code/dmute_2_1/c2.cpp.tk                            |  126
code/fagu_0_1/A.cpp.tk                              |  26
code/fagu_1_1/B.cpp.tk                              |  26
code/fagu_2_1/C.cpp.tk                              |  38
code/FatalEagle_0_1/main.cpp.tk                     |  52
code/FatalEagle_1_1/main.cpp.tk                     |  152
code/FatalEagle_2_1/main.cpp.tk                     |  387
code/fullpower_0_1/A.cpp.tk                         |  70
code/fullpower_1_1/B.cpp.tk                         |  166
code/fullpower_2_1/C.cpp.tk                         |  182
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  53
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  84
code/ICastro_2_1/Dijkstra.cpp.tk                    |  82
code/ilackthatsuperpower_0_1/a.cpp.tk               |  106
code/ilackthatsuperpower_1_1/b.cpp.tk               |  110
code/ilackthatsuperpower_2_1/c.cpp.tk               |  97
code/iridescent_0_1/A.cpp.tk                        |  84
code/iridescent_1_1/B.cpp.tk                        |  424
code/iridescent_2_1/C.cpp.tk                        |  136
code/ishraq_0_1/main.cpp.tk                         |  8
code/ishraq_1_1/main.cpp.tk                         |  89
code/ishraq_2_1/main.cpp.tk                         |  37
code/JayXon_0_1/A.cpp.tk                            |  25
code/JayXon_1_1/B.cpp.tk                            |  106
code/JayXon_2_1/C.cpp.tk                            |  22
code/Josse_0_1/A.cpp.tk                             |  66
code/Josse_1_1/B.cpp.tk                             |  124
code/Josse_2_1/C.cpp.tk                             |  154
code/kcm1700_0_1/a.cpp.tk                           |  61
code/kcm1700_1_1/b.cpp.tk                           |  145
code/kcm1700_2_1/c.cpp.tk                           |  128
code/kevinsogo_0_1/a.cpp.tk                         |  8
code/kevinsogo_1_1/b.cpp.tk                         |  20
code/kevinsogo_2_1/c.cpp.tk                         |  39
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  8
code/LazyAnna_0_1/1.cpp.tk                          |  45
code/LazyAnna_1_1/2-1.cpp.tk                        |  79
code/LazyAnna_2_1/3.cpp.tk                          |  32
code/Merkurev_0_1/A.cpp.tk                          |  79
code/Merkurev_1_1/B.cpp.tk                          |  136
code/Merkurev_2_1/C.cpp.tk                          |  119
code/mezei_0_1/main.cpp.tk                          |  82
code/mezei_1_1/main.cpp.tk                          |  111
code/mezei_2_1/main.cpp.tk                          |  126
code/Mister_0_1/a.cpp.tk                            |  30
code/Mister_1_1/b.cpp.tk                            |  59
code/Mister_2_1/c.cpp.tk                            |  63
code/namonakiacc_0_1/cpp.cpp.tk                     |  20
code/namonakiacc_1_1/cpp.cpp.tk                     |  24
code/namonakiacc_2_1/cpp.cpp.tk                     |  36
code/Nicolas16_0_1/main.cpp.tk                      |  22
code/Nicolas16_1_1/main.cpp.tk                      |  22
code/Nicolas16_2_1/main.cpp.tk                      |  139
code/pandamonium_0_1/a.cpp.tk                       |  54
code/pandamonium_1_1/b.cpp.tk                       |  117
code/pandamonium_2_1/c.cpp.tk                       |  81
code/pflueger_0_1/A.cpp.tk                          |  121
code/pflueger_1_1/B.cpp.tk                          |  427
code/pflueger_2_1/C.cpp.tk                          |  168
code/ponyopoppo_0_1/A.cpp.tk                        |  17
code/ponyopoppo_1_1/B.cpp.tk                        |  20
code/ponyopoppo_2_1/C.cpp.tk                        |  49
code/Ragnar_0_1/A.cpp.tk                            |  24
code/Ragnar_1_1/B-2.cpp.tk                          |  57
code/Ragnar_2_1/C.cpp.tk                            |  67
code/saffah_0_1/t.cpp.tk                            |  8
code/saffah_1_1/t.cpp.tk                            |  10
code/saffah_2_1/t.cpp.tk                            |  35
code/SamanSami_0_1/A.cpp.tk                         |  101
code/SamanSami_1_1/B.cpp.tk                         |  7760
code/SamanSami_2_1/C.cpp.tk                         |  3
code/Savlik_0_1/code.cpp.tk                         |  33
code/Savlik_1_1/code.cpp.tk                         |  12
code/Savlik_2_1/code.cpp.tk                         |  41
code/shik_0_1/pa.cpp.tk                             |  30
code/shik_1_1/pb.cpp.tk                             |  35
code/shik_2_1/pc.cpp.tk                             |  55
code/simsa.st_0_1/A.cpp.tk                          |  10
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  30
code/SovietUnion_0_1/A.cpp.tk                       |  52
code/SovietUnion_1_1/B.cpp.tk                       |  71
code/SovietUnion_2_1/C.cpp.tk                       |  42
code/tailed_0_1/A.cpp.tk                            |  53
code/tailed_1_1/B.cpp.tk                            |  175
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  109
code/TheNatural_1_1/B.cpp.tk                        |  188
code/TheNatural_2_1/C.cpp.tk                        |  75
code/TrueBamboo_0_1/test.cpp.tk                     |  25
code/TrueBamboo_1_1/test.cpp.tk                     |  53
code/TrueBamboo_2_1/test.cpp.tk                     |  41
code/tur.turczyn_0_1/A.cpp.tk                       |  15
code/tur.turczyn_1_1/B.cpp.tk                       |  22
code/tur.turczyn_2_1/C.cpp.tk                       |  24
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  18
code/Tyg3R_2_1/C.cpp.tk                             |  19
code/UminchuR_0_1/main.cpp.tk                       |  17
code/UminchuR_1_1/main.cpp.tk                       |  22
code/UminchuR_2_1/main.cpp.tk                       |  44
code/wo..._0_1/a.cpp.tk                             |  85
code/wo..._1_1/b.cpp.tk                             |  127
code/wo..._2_1/c.cpp.tk                             |  151
code/yswtt_0_1/A.cpp.tk                             |  54
code/yswtt_1_1/B.cpp.tk                             |  82
code/yswtt_2_1/C.cpp.tk                             |  72
code/ZhSh_0_1/a.cpp.tk                              |  57
code/ZhSh_1_1/b.cpp.tk                              |  118
code/ZhSh_2_1/c.cpp.tk                              |  76
