Begin
Comparing:  code/kevinsogo_2_1/c.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  10
code/551100kk_1_1/B.cpp.tk                          |  17
code/551100kk_2_1/C.cpp.tk                          |  37
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  17
code/achan1058_2_1/source.cpp.tk                    |  35
code/alanubi_0_1/a.cpp.tk                           |  8
code/alanubi_1_1/b.cpp.tk                           |  16
code/alanubi_2_1/c.cpp.tk                           |  48
code/AntiForest_0_1/q1.cpp.tk                       |  18
code/AntiForest_1_1/q2.cpp.tk                       |  7
code/AntiForest_2_1/q3.cpp.tk                       |  55
code/apiad_0_1/A.cpp.tk                             |  12
code/apiad_1_1/B.cpp.tk                             |  18
code/apiad_2_1/C.cpp.tk                             |  50
code/azaky_0_1/A.cpp.tk                             |  15
code/azaky_1_1/B.cpp.tk                             |  20
code/azaky_2_1/C.cpp.tk                             |  54
code/azariamuh_0_1/standing.cpp.tk                  |  10
code/azariamuh_1_1/pancake.cpp.tk                   |  57
code/azariamuh_2_1/dijkstra.cpp.tk                  |  20
code/bmerry_0_1/a.cpp.tk                            |  32
code/bmerry_1_1/b.cpp.tk                            |  37
code/bmerry_2_1/c.cpp.tk                            |  64
code/climpet_0_1/A.cpp.tk                           |  15
code/climpet_1_1/B.cpp.tk                           |  18
code/climpet_2_1/C.cpp.tk                           |  45
code/ctzsm_0_1/A.cpp.tk                             |  11
code/ctzsm_1_1/B.cpp.tk                             |  15
code/ctzsm_2_1/C.cpp.tk                             |  80
code/DanilC_0_1/problem.cpp.tk                      |  17
code/DanilC_1_1/problemB.cpp.tk                     |  33
code/DanilC_2_1/problemC.cpp.tk                     |  95
code/DEGwer_0_1/A.cpp.tk                            |  13
code/DEGwer_1_1/B.cpp.tk                            |  13
code/DEGwer_2_1/C.cpp.tk                            |  23
code/dmute_0_1/a.cpp.tk                             |  7
code/dmute_1_1/b.cpp.tk                             |  15
code/dmute_2_1/c2.cpp.tk                            |  70
code/fagu_0_1/A.cpp.tk                              |  5
code/fagu_1_1/B.cpp.tk                              |  5
code/fagu_2_1/C.cpp.tk                              |  52
code/FatalEagle_0_1/main.cpp.tk                     |  11
code/FatalEagle_1_1/main.cpp.tk                     |  15
code/FatalEagle_2_1/main.cpp.tk                     |  286
code/fullpower_0_1/A.cpp.tk                         |  20
code/fullpower_1_1/B.cpp.tk                         |  54
code/fullpower_2_1/C.cpp.tk                         |  96
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  5
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  11
code/ICastro_2_1/Dijkstra.cpp.tk                    |  102
code/ilackthatsuperpower_0_1/a.cpp.tk               |  53
code/ilackthatsuperpower_1_1/b.cpp.tk               |  50
code/ilackthatsuperpower_2_1/c.cpp.tk               |  77
code/iridescent_0_1/A.cpp.tk                        |  6
code/iridescent_1_1/B.cpp.tk                        |  8
code/iridescent_2_1/C.cpp.tk                        |  18
code/ishraq_0_1/main.cpp.tk                         |  10
code/ishraq_1_1/main.cpp.tk                         |  12
code/ishraq_2_1/main.cpp.tk                         |  76
code/JayXon_0_1/A.cpp.tk                            |  5
code/JayXon_1_1/B.cpp.tk                            |  24
code/JayXon_2_1/C.cpp.tk                            |  22
code/Josse_0_1/A.cpp.tk                             |  6
code/Josse_1_1/B.cpp.tk                             |  12
code/Josse_2_1/C.cpp.tk                             |  68
code/kcm1700_0_1/a.cpp.tk                           |  8
code/kcm1700_1_1/b.cpp.tk                           |  12
code/kcm1700_2_1/c.cpp.tk                           |  70
code/kevinsogo_0_1/a.cpp.tk                         |  16
code/kevinsogo_1_1/b.cpp.tk                         |  17
code/kevinsogo_2_1/c.cpp.tk                         |  170835
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  8
code/LazyAnna_0_1/1.cpp.tk                          |  8
code/LazyAnna_1_1/2-1.cpp.tk                        |  10
code/LazyAnna_2_1/3.cpp.tk                          |  26
code/Merkurev_0_1/A.cpp.tk                          |  17
code/Merkurev_1_1/B.cpp.tk                          |  21
code/Merkurev_2_1/C.cpp.tk                          |  49
code/mezei_0_1/main.cpp.tk                          |  13
code/mezei_1_1/main.cpp.tk                          |  11
code/mezei_2_1/main.cpp.tk                          |  39
code/Mister_0_1/a.cpp.tk                            |  9
code/Mister_1_1/b.cpp.tk                            |  12
code/Mister_2_1/c.cpp.tk                            |  44
code/namonakiacc_0_1/cpp.cpp.tk                     |  14
code/namonakiacc_1_1/cpp.cpp.tk                     |  20
code/namonakiacc_2_1/cpp.cpp.tk                     |  113
code/Nicolas16_0_1/main.cpp.tk                      |  4
code/Nicolas16_1_1/main.cpp.tk                      |  4
code/Nicolas16_2_1/main.cpp.tk                      |  53
code/pandamonium_0_1/a.cpp.tk                       |  8
code/pandamonium_1_1/b.cpp.tk                       |  52
code/pandamonium_2_1/c.cpp.tk                       |  47
code/pflueger_0_1/A.cpp.tk                          |  5
code/pflueger_1_1/B.cpp.tk                          |  10
code/pflueger_2_1/C.cpp.tk                          |  45
code/ponyopoppo_0_1/A.cpp.tk                        |  10
code/ponyopoppo_1_1/B.cpp.tk                        |  18
code/ponyopoppo_2_1/C.cpp.tk                        |  85
code/Ragnar_0_1/A.cpp.tk                            |  8
code/Ragnar_1_1/B-2.cpp.tk                          |  14
code/Ragnar_2_1/C.cpp.tk                            |  26
code/saffah_0_1/t.cpp.tk                            |  11
code/saffah_1_1/t.cpp.tk                            |  16
code/saffah_2_1/t.cpp.tk                            |  72
code/SamanSami_0_1/A.cpp.tk                         |  1
code/SamanSami_1_1/B.cpp.tk                         |  8
code/SamanSami_2_1/C.cpp.tk                         |  6
code/Savlik_0_1/code.cpp.tk                         |  6
code/Savlik_1_1/code.cpp.tk                         |  11
code/Savlik_2_1/code.cpp.tk                         |  40
code/shik_0_1/pa.cpp.tk                             |  38
code/shik_1_1/pb.cpp.tk                             |  40
code/shik_2_1/pc.cpp.tk                             |  84
code/simsa.st_0_1/A.cpp.tk                          |  11
code/simsa.st_1_1/B.cpp.tk                          |  15
code/simsa.st_2_1/C.cpp.tk                          |  58
code/SovietUnion_0_1/A.cpp.tk                       |  13
code/SovietUnion_1_1/B.cpp.tk                       |  17
code/SovietUnion_2_1/C.cpp.tk                       |  44
code/tailed_0_1/A.cpp.tk                            |  5
code/tailed_1_1/B.cpp.tk                            |  10
code/tailed_2_1/C.cpp.tk                            |  25
code/TheNatural_0_1/A.cpp.tk                        |  7
code/TheNatural_1_1/B.cpp.tk                        |  9
code/TheNatural_2_1/C.cpp.tk                        |  18
code/TrueBamboo_0_1/test.cpp.tk                     |  10
code/TrueBamboo_1_1/test.cpp.tk                     |  13
code/TrueBamboo_2_1/test.cpp.tk                     |  30
code/tur.turczyn_0_1/A.cpp.tk                       |  7
code/tur.turczyn_1_1/B.cpp.tk                       |  14
code/tur.turczyn_2_1/C.cpp.tk                       |  19
code/Tyg3R_0_1/A.cpp.tk                             |  9
code/Tyg3R_1_1/B.cpp.tk                             |  18
code/Tyg3R_2_1/C.cpp.tk                             |  29
code/UminchuR_0_1/main.cpp.tk                       |  15
code/UminchuR_1_1/main.cpp.tk                       |  24
code/UminchuR_2_1/main.cpp.tk                       |  82
code/wo..._0_1/a.cpp.tk                             |  15
code/wo..._1_1/b.cpp.tk                             |  12
code/wo..._2_1/c.cpp.tk                             |  65
code/yswtt_0_1/A.cpp.tk                             |  3
code/yswtt_1_1/B.cpp.tk                             |  12
code/yswtt_2_1/C.cpp.tk                             |  20
code/ZhSh_0_1/a.cpp.tk                              |  5
code/ZhSh_1_1/b.cpp.tk                              |  39
code/ZhSh_2_1/c.cpp.tk                              |  62
