Begin
Comparing:  code/wo..._1_1/b.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  21
code/551100kk_1_1/B.cpp.tk                          |  48
code/551100kk_2_1/C.cpp.tk                          |  53
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  17
code/achan1058_2_1/source.cpp.tk                    |  36
code/alanubi_0_1/a.cpp.tk                           |  97
code/alanubi_1_1/b.cpp.tk                           |  163
code/alanubi_2_1/c.cpp.tk                           |  210
code/AntiForest_0_1/q1.cpp.tk                       |  19
code/AntiForest_1_1/q2.cpp.tk                       |  9
code/AntiForest_2_1/q3.cpp.tk                       |  55
code/apiad_0_1/A.cpp.tk                             |  17
code/apiad_1_1/B.cpp.tk                             |  29
code/apiad_2_1/C.cpp.tk                             |  28
code/azaky_0_1/A.cpp.tk                             |  17
code/azaky_1_1/B.cpp.tk                             |  25
code/azaky_2_1/C.cpp.tk                             |  44
code/azariamuh_0_1/standing.cpp.tk                  |  17
code/azariamuh_1_1/pancake.cpp.tk                   |  28
code/azariamuh_2_1/dijkstra.cpp.tk                  |  25
code/bmerry_0_1/a.cpp.tk                            |  68
code/bmerry_1_1/b.cpp.tk                            |  99
code/bmerry_2_1/c.cpp.tk                            |  81
code/climpet_0_1/A.cpp.tk                           |  42
code/climpet_1_1/B.cpp.tk                           |  51
code/climpet_2_1/C.cpp.tk                           |  77
code/ctzsm_0_1/A.cpp.tk                             |  55
code/ctzsm_1_1/B.cpp.tk                             |  90
code/ctzsm_2_1/C.cpp.tk                             |  118
code/DanilC_0_1/problem.cpp.tk                      |  54
code/DanilC_1_1/problemB.cpp.tk                     |  87
code/DanilC_2_1/problemC.cpp.tk                     |  87
code/DEGwer_0_1/A.cpp.tk                            |  93
code/DEGwer_1_1/B.cpp.tk                            |  124
code/DEGwer_2_1/C.cpp.tk                            |  84
code/dmute_0_1/a.cpp.tk                             |  95
code/dmute_1_1/b.cpp.tk                             |  208
code/dmute_2_1/c2.cpp.tk                            |  176
code/fagu_0_1/A.cpp.tk                              |  47
code/fagu_1_1/B.cpp.tk                              |  49
code/fagu_2_1/C.cpp.tk                              |  64
code/FatalEagle_0_1/main.cpp.tk                     |  94
code/FatalEagle_1_1/main.cpp.tk                     |  181
code/FatalEagle_2_1/main.cpp.tk                     |  383
code/fullpower_0_1/A.cpp.tk                         |  140
code/fullpower_1_1/B.cpp.tk                         |  209
code/fullpower_2_1/C.cpp.tk                         |  223
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  30
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  56
code/ICastro_2_1/Dijkstra.cpp.tk                    |  75
code/ilackthatsuperpower_0_1/a.cpp.tk               |  102
code/ilackthatsuperpower_1_1/b.cpp.tk               |  93
code/ilackthatsuperpower_2_1/c.cpp.tk               |  98
code/iridescent_0_1/A.cpp.tk                        |  38
code/iridescent_1_1/B.cpp.tk                        |  94
code/iridescent_2_1/C.cpp.tk                        |  82
code/ishraq_0_1/main.cpp.tk                         |  20
code/ishraq_1_1/main.cpp.tk                         |  60
code/ishraq_2_1/main.cpp.tk                         |  59
code/JayXon_0_1/A.cpp.tk                            |  25
code/JayXon_1_1/B.cpp.tk                            |  90
code/JayXon_2_1/C.cpp.tk                            |  28
code/Josse_0_1/A.cpp.tk                             |  66
code/Josse_1_1/B.cpp.tk                             |  107
code/Josse_2_1/C.cpp.tk                             |  146
code/kcm1700_0_1/a.cpp.tk                           |  103
code/kcm1700_1_1/b.cpp.tk                           |  181
code/kcm1700_2_1/c.cpp.tk                           |  173
code/kevinsogo_0_1/a.cpp.tk                         |  21
code/kevinsogo_1_1/b.cpp.tk                         |  32
code/kevinsogo_2_1/c.cpp.tk                         |  48
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  14
code/LazyAnna_0_1/1.cpp.tk                          |  32
code/LazyAnna_1_1/2-1.cpp.tk                        |  62
code/LazyAnna_2_1/3.cpp.tk                          |  35
code/Merkurev_0_1/A.cpp.tk                          |  122
code/Merkurev_1_1/B.cpp.tk                          |  206
code/Merkurev_2_1/C.cpp.tk                          |  158
code/mezei_0_1/main.cpp.tk                          |  116
code/mezei_1_1/main.cpp.tk                          |  106
code/mezei_2_1/main.cpp.tk                          |  180
code/Mister_0_1/a.cpp.tk                            |  67
code/Mister_1_1/b.cpp.tk                            |  103
code/Mister_2_1/c.cpp.tk                            |  83
code/namonakiacc_0_1/cpp.cpp.tk                     |  23
code/namonakiacc_1_1/cpp.cpp.tk                     |  24
code/namonakiacc_2_1/cpp.cpp.tk                     |  46
code/Nicolas16_0_1/main.cpp.tk                      |  60
code/Nicolas16_1_1/main.cpp.tk                      |  55
code/Nicolas16_2_1/main.cpp.tk                      |  186
code/pandamonium_0_1/a.cpp.tk                       |  100
code/pandamonium_1_1/b.cpp.tk                       |  155
code/pandamonium_2_1/c.cpp.tk                       |  132
code/pflueger_0_1/A.cpp.tk                          |  49
code/pflueger_1_1/B.cpp.tk                          |  109
code/pflueger_2_1/C.cpp.tk                          |  139
code/ponyopoppo_0_1/A.cpp.tk                        |  9
code/ponyopoppo_1_1/B.cpp.tk                        |  16
code/ponyopoppo_2_1/C.cpp.tk                        |  64
code/Ragnar_0_1/A.cpp.tk                            |  12
code/Ragnar_1_1/B-2.cpp.tk                          |  38
code/Ragnar_2_1/C.cpp.tk                            |  40
code/saffah_0_1/t.cpp.tk                            |  21
code/saffah_1_1/t.cpp.tk                            |  28
code/saffah_2_1/t.cpp.tk                            |  49
code/SamanSami_0_1/A.cpp.tk                         |  18
code/SamanSami_1_1/B.cpp.tk                         |  105
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  28
code/Savlik_1_1/code.cpp.tk                         |  8
code/Savlik_2_1/code.cpp.tk                         |  44
code/shik_0_1/pa.cpp.tk                             |  39
code/shik_1_1/pb.cpp.tk                             |  39
code/shik_2_1/pc.cpp.tk                             |  68
code/simsa.st_0_1/A.cpp.tk                          |  15
code/simsa.st_1_1/B.cpp.tk                          |  26
code/simsa.st_2_1/C.cpp.tk                          |  53
code/SovietUnion_0_1/A.cpp.tk                       |  65
code/SovietUnion_1_1/B.cpp.tk                       |  84
code/SovietUnion_2_1/C.cpp.tk                       |  45
code/tailed_0_1/A.cpp.tk                            |  30
code/tailed_1_1/B.cpp.tk                            |  62
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  72
code/TheNatural_1_1/B.cpp.tk                        |  116
code/TheNatural_2_1/C.cpp.tk                        |  44
code/TrueBamboo_0_1/test.cpp.tk                     |  36
code/TrueBamboo_1_1/test.cpp.tk                     |  53
code/TrueBamboo_2_1/test.cpp.tk                     |  49
code/tur.turczyn_0_1/A.cpp.tk                       |  10
code/tur.turczyn_1_1/B.cpp.tk                       |  20
code/tur.turczyn_2_1/C.cpp.tk                       |  22
code/Tyg3R_0_1/A.cpp.tk                             |  10
code/Tyg3R_1_1/B.cpp.tk                             |  20
code/Tyg3R_2_1/C.cpp.tk                             |  20
code/UminchuR_0_1/main.cpp.tk                       |  22
code/UminchuR_1_1/main.cpp.tk                       |  32
code/UminchuR_2_1/main.cpp.tk                       |  51
code/wo..._0_1/a.cpp.tk                             |  130
code/wo..._1_1/b.cpp.tk                             |  10684
code/wo..._2_1/c.cpp.tk                             |  252
code/yswtt_0_1/A.cpp.tk                             |  30
code/yswtt_1_1/B.cpp.tk                             |  48
code/yswtt_2_1/C.cpp.tk                             |  54
code/ZhSh_0_1/a.cpp.tk                              |  32
code/ZhSh_1_1/b.cpp.tk                              |  96
code/ZhSh_2_1/c.cpp.tk                              |  65
