Begin
Comparing:  code/ishraq_2_1/main.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  13
code/551100kk_1_1/B.cpp.tk                          |  22
code/551100kk_2_1/C.cpp.tk                          |  45
code/achan1058_0_1/Q-A.cpp.tk                       |  12
code/achan1058_1_1/source.cpp.tk                    |  24
code/achan1058_2_1/source.cpp.tk                    |  59
code/alanubi_0_1/a.cpp.tk                           |  14
code/alanubi_1_1/b.cpp.tk                           |  21
code/alanubi_2_1/c.cpp.tk                           |  60
code/AntiForest_0_1/q1.cpp.tk                       |  29
code/AntiForest_1_1/q2.cpp.tk                       |  11
code/AntiForest_2_1/q3.cpp.tk                       |  64
code/apiad_0_1/A.cpp.tk                             |  18
code/apiad_1_1/B.cpp.tk                             |  28
code/apiad_2_1/C.cpp.tk                             |  32
code/azaky_0_1/A.cpp.tk                             |  22
code/azaky_1_1/B.cpp.tk                             |  27
code/azaky_2_1/C.cpp.tk                             |  65
code/azariamuh_0_1/standing.cpp.tk                  |  15
code/azariamuh_1_1/pancake.cpp.tk                   |  40
code/azariamuh_2_1/dijkstra.cpp.tk                  |  34
code/bmerry_0_1/a.cpp.tk                            |  43
code/bmerry_1_1/b.cpp.tk                            |  51
code/bmerry_2_1/c.cpp.tk                            |  54
code/climpet_0_1/A.cpp.tk                           |  23
code/climpet_1_1/B.cpp.tk                           |  27
code/climpet_2_1/C.cpp.tk                           |  46
code/ctzsm_0_1/A.cpp.tk                             |  14
code/ctzsm_1_1/B.cpp.tk                             |  21
code/ctzsm_2_1/C.cpp.tk                             |  112
code/DanilC_0_1/problem.cpp.tk                      |  24
code/DanilC_1_1/problemB.cpp.tk                     |  39
code/DanilC_2_1/problemC.cpp.tk                     |  106
code/DEGwer_0_1/A.cpp.tk                            |  18
code/DEGwer_1_1/B.cpp.tk                            |  20
code/DEGwer_2_1/C.cpp.tk                            |  37
code/dmute_0_1/a.cpp.tk                             |  8
code/dmute_1_1/b.cpp.tk                             |  17
code/dmute_2_1/c2.cpp.tk                            |  53
code/fagu_0_1/A.cpp.tk                              |  7
code/fagu_1_1/B.cpp.tk                              |  7
code/fagu_2_1/C.cpp.tk                              |  52
code/FatalEagle_0_1/main.cpp.tk                     |  14
code/FatalEagle_1_1/main.cpp.tk                     |  20
code/FatalEagle_2_1/main.cpp.tk                     |  194
code/fullpower_0_1/A.cpp.tk                         |  23
code/fullpower_1_1/B.cpp.tk                         |  29
code/fullpower_2_1/C.cpp.tk                         |  89
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  7
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  14
code/ICastro_2_1/Dijkstra.cpp.tk                    |  109
code/ilackthatsuperpower_0_1/a.cpp.tk               |  73
code/ilackthatsuperpower_1_1/b.cpp.tk               |  74
code/ilackthatsuperpower_2_1/c.cpp.tk               |  104
code/iridescent_0_1/A.cpp.tk                        |  7
code/iridescent_1_1/B.cpp.tk                        |  9
code/iridescent_2_1/C.cpp.tk                        |  17
code/ishraq_0_1/main.cpp.tk                         |  27
code/ishraq_1_1/main.cpp.tk                         |  34
code/ishraq_2_1/main.cpp.tk                         |  119208
code/JayXon_0_1/A.cpp.tk                            |  6
code/JayXon_1_1/B.cpp.tk                            |  22
code/JayXon_2_1/C.cpp.tk                            |  34
code/Josse_0_1/A.cpp.tk                             |  10
code/Josse_1_1/B.cpp.tk                             |  14
code/Josse_2_1/C.cpp.tk                             |  78
code/kcm1700_0_1/a.cpp.tk                           |  11
code/kcm1700_1_1/b.cpp.tk                           |  16
code/kcm1700_2_1/c.cpp.tk                           |  61
code/kevinsogo_0_1/a.cpp.tk                         |  19
code/kevinsogo_1_1/b.cpp.tk                         |  19
code/kevinsogo_2_1/c.cpp.tk                         |  89
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  13
code/LazyAnna_0_1/1.cpp.tk                          |  6
code/LazyAnna_1_1/2-1.cpp.tk                        |  12
code/LazyAnna_2_1/3.cpp.tk                          |  34
code/Merkurev_0_1/A.cpp.tk                          |  18
code/Merkurev_1_1/B.cpp.tk                          |  33
code/Merkurev_2_1/C.cpp.tk                          |  38
code/mezei_0_1/main.cpp.tk                          |  15
code/mezei_1_1/main.cpp.tk                          |  14
code/mezei_2_1/main.cpp.tk                          |  61
code/Mister_0_1/a.cpp.tk                            |  13
code/Mister_1_1/b.cpp.tk                            |  16
code/Mister_2_1/c.cpp.tk                            |  42
code/namonakiacc_0_1/cpp.cpp.tk                     |  24
code/namonakiacc_1_1/cpp.cpp.tk                     |  31
code/namonakiacc_2_1/cpp.cpp.tk                     |  70
code/Nicolas16_0_1/main.cpp.tk                      |  6
code/Nicolas16_1_1/main.cpp.tk                      |  6
code/Nicolas16_2_1/main.cpp.tk                      |  74
code/pandamonium_0_1/a.cpp.tk                       |  9
code/pandamonium_1_1/b.cpp.tk                       |  38
code/pandamonium_2_1/c.cpp.tk                       |  25
code/pflueger_0_1/A.cpp.tk                          |  7
code/pflueger_1_1/B.cpp.tk                          |  17
code/pflueger_2_1/C.cpp.tk                          |  48
code/ponyopoppo_0_1/A.cpp.tk                        |  13
code/ponyopoppo_1_1/B.cpp.tk                        |  27
code/ponyopoppo_2_1/C.cpp.tk                        |  124
code/Ragnar_0_1/A.cpp.tk                            |  11
code/Ragnar_1_1/B-2.cpp.tk                          |  18
code/Ragnar_2_1/C.cpp.tk                            |  34
code/saffah_0_1/t.cpp.tk                            |  18
code/saffah_1_1/t.cpp.tk                            |  26
code/saffah_2_1/t.cpp.tk                            |  88
code/SamanSami_0_1/A.cpp.tk                         |  2
code/SamanSami_1_1/B.cpp.tk                         |  9
code/SamanSami_2_1/C.cpp.tk                         |  11
code/Savlik_0_1/code.cpp.tk                         |  8
code/Savlik_1_1/code.cpp.tk                         |  16
code/Savlik_2_1/code.cpp.tk                         |  59
code/shik_0_1/pa.cpp.tk                             |  52
code/shik_1_1/pb.cpp.tk                             |  57
code/shik_2_1/pc.cpp.tk                             |  105
code/simsa.st_0_1/A.cpp.tk                          |  15
code/simsa.st_1_1/B.cpp.tk                          |  24
code/simsa.st_2_1/C.cpp.tk                          |  89
code/SovietUnion_0_1/A.cpp.tk                       |  15
code/SovietUnion_1_1/B.cpp.tk                       |  18
code/SovietUnion_2_1/C.cpp.tk                       |  60
code/tailed_0_1/A.cpp.tk                            |  8
code/tailed_1_1/B.cpp.tk                            |  13
code/tailed_2_1/C.cpp.tk                            |  35
code/TheNatural_0_1/A.cpp.tk                        |  7
code/TheNatural_1_1/B.cpp.tk                        |  9
code/TheNatural_2_1/C.cpp.tk                        |  21
code/TrueBamboo_0_1/test.cpp.tk                     |  13
code/TrueBamboo_1_1/test.cpp.tk                     |  18
code/TrueBamboo_2_1/test.cpp.tk                     |  44
code/tur.turczyn_0_1/A.cpp.tk                       |  10
code/tur.turczyn_1_1/B.cpp.tk                       |  20
code/tur.turczyn_2_1/C.cpp.tk                       |  26
code/Tyg3R_0_1/A.cpp.tk                             |  16
code/Tyg3R_1_1/B.cpp.tk                             |  23
code/Tyg3R_2_1/C.cpp.tk                             |  27
code/UminchuR_0_1/main.cpp.tk                       |  19
code/UminchuR_1_1/main.cpp.tk                       |  32
code/UminchuR_2_1/main.cpp.tk                       |  62
code/wo..._0_1/a.cpp.tk                             |  16
code/wo..._1_1/b.cpp.tk                             |  19
code/wo..._2_1/c.cpp.tk                             |  79
code/yswtt_0_1/A.cpp.tk                             |  5
code/yswtt_1_1/B.cpp.tk                             |  14
code/yswtt_2_1/C.cpp.tk                             |  28
code/ZhSh_0_1/a.cpp.tk                              |  6
code/ZhSh_1_1/b.cpp.tk                              |  55
code/ZhSh_2_1/c.cpp.tk                              |  97
