Begin
Comparing:  code/wo..._0_1/a.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  25
code/551100kk_1_1/B.cpp.tk                          |  43
code/551100kk_2_1/C.cpp.tk                          |  47
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  12
code/achan1058_2_1/source.cpp.tk                    |  25
code/alanubi_0_1/a.cpp.tk                           |  111
code/alanubi_1_1/b.cpp.tk                           |  192
code/alanubi_2_1/c.cpp.tk                           |  191
code/AntiForest_0_1/q1.cpp.tk                       |  28
code/AntiForest_1_1/q2.cpp.tk                       |  9
code/AntiForest_2_1/q3.cpp.tk                       |  48
code/apiad_0_1/A.cpp.tk                             |  16
code/apiad_1_1/B.cpp.tk                             |  17
code/apiad_2_1/C.cpp.tk                             |  30
code/azaky_0_1/A.cpp.tk                             |  20
code/azaky_1_1/B.cpp.tk                             |  23
code/azaky_2_1/C.cpp.tk                             |  42
code/azariamuh_0_1/standing.cpp.tk                  |  16
code/azariamuh_1_1/pancake.cpp.tk                   |  26
code/azariamuh_2_1/dijkstra.cpp.tk                  |  21
code/bmerry_0_1/a.cpp.tk                            |  67
code/bmerry_1_1/b.cpp.tk                            |  75
code/bmerry_2_1/c.cpp.tk                            |  67
code/climpet_0_1/A.cpp.tk                           |  37
code/climpet_1_1/B.cpp.tk                           |  46
code/climpet_2_1/C.cpp.tk                           |  64
code/ctzsm_0_1/A.cpp.tk                             |  46
code/ctzsm_1_1/B.cpp.tk                             |  66
code/ctzsm_2_1/C.cpp.tk                             |  103
code/DanilC_0_1/problem.cpp.tk                      |  46
code/DanilC_1_1/problemB.cpp.tk                     |  72
code/DanilC_2_1/problemC.cpp.tk                     |  71
code/DEGwer_0_1/A.cpp.tk                            |  106
code/DEGwer_1_1/B.cpp.tk                            |  87
code/DEGwer_2_1/C.cpp.tk                            |  60
code/dmute_0_1/a.cpp.tk                             |  55
code/dmute_1_1/b.cpp.tk                             |  117
code/dmute_2_1/c2.cpp.tk                            |  114
code/fagu_0_1/A.cpp.tk                              |  43
code/fagu_1_1/B.cpp.tk                              |  43
code/fagu_2_1/C.cpp.tk                              |  59
code/FatalEagle_0_1/main.cpp.tk                     |  93
code/FatalEagle_1_1/main.cpp.tk                     |  107
code/FatalEagle_2_1/main.cpp.tk                     |  305
code/fullpower_0_1/A.cpp.tk                         |  122
code/fullpower_1_1/B.cpp.tk                         |  139
code/fullpower_2_1/C.cpp.tk                         |  172
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  28
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  47
code/ICastro_2_1/Dijkstra.cpp.tk                    |  79
code/ilackthatsuperpower_0_1/a.cpp.tk               |  100
code/ilackthatsuperpower_1_1/b.cpp.tk               |  80
code/ilackthatsuperpower_2_1/c.cpp.tk               |  83
code/iridescent_0_1/A.cpp.tk                        |  32
code/iridescent_1_1/B.cpp.tk                        |  81
code/iridescent_2_1/C.cpp.tk                        |  65
code/ishraq_0_1/main.cpp.tk                         |  21
code/ishraq_1_1/main.cpp.tk                         |  42
code/ishraq_2_1/main.cpp.tk                         |  52
code/JayXon_0_1/A.cpp.tk                            |  33
code/JayXon_1_1/B.cpp.tk                            |  62
code/JayXon_2_1/C.cpp.tk                            |  18
code/Josse_0_1/A.cpp.tk                             |  44
code/Josse_1_1/B.cpp.tk                             |  85
code/Josse_2_1/C.cpp.tk                             |  122
code/kcm1700_0_1/a.cpp.tk                           |  86
code/kcm1700_1_1/b.cpp.tk                           |  151
code/kcm1700_2_1/c.cpp.tk                           |  144
code/kevinsogo_0_1/a.cpp.tk                         |  22
code/kevinsogo_1_1/b.cpp.tk                         |  27
code/kevinsogo_2_1/c.cpp.tk                         |  52
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  7
code/LazyAnna_0_1/1.cpp.tk                          |  31
code/LazyAnna_1_1/2-1.cpp.tk                        |  47
code/LazyAnna_2_1/3.cpp.tk                          |  28
code/Merkurev_0_1/A.cpp.tk                          |  124
code/Merkurev_1_1/B.cpp.tk                          |  113
code/Merkurev_2_1/C.cpp.tk                          |  120
code/mezei_0_1/main.cpp.tk                          |  166
code/mezei_1_1/main.cpp.tk                          |  81
code/mezei_2_1/main.cpp.tk                          |  133
code/Mister_0_1/a.cpp.tk                            |  54
code/Mister_1_1/b.cpp.tk                            |  84
code/Mister_2_1/c.cpp.tk                            |  74
code/namonakiacc_0_1/cpp.cpp.tk                     |  24
code/namonakiacc_1_1/cpp.cpp.tk                     |  21
code/namonakiacc_2_1/cpp.cpp.tk                     |  51
code/Nicolas16_0_1/main.cpp.tk                      |  35
code/Nicolas16_1_1/main.cpp.tk                      |  32
code/Nicolas16_2_1/main.cpp.tk                      |  167
code/pandamonium_0_1/a.cpp.tk                       |  57
code/pandamonium_1_1/b.cpp.tk                       |  132
code/pandamonium_2_1/c.cpp.tk                       |  82
code/pflueger_0_1/A.cpp.tk                          |  43
code/pflueger_1_1/B.cpp.tk                          |  76
code/pflueger_2_1/C.cpp.tk                          |  95
code/ponyopoppo_0_1/A.cpp.tk                        |  14
code/ponyopoppo_1_1/B.cpp.tk                        |  11
code/ponyopoppo_2_1/C.cpp.tk                        |  54
code/Ragnar_0_1/A.cpp.tk                            |  10
code/Ragnar_1_1/B-2.cpp.tk                          |  24
code/Ragnar_2_1/C.cpp.tk                            |  35
code/saffah_0_1/t.cpp.tk                            |  21
code/saffah_1_1/t.cpp.tk                            |  21
code/saffah_2_1/t.cpp.tk                            |  48
code/SamanSami_0_1/A.cpp.tk                         |  17
code/SamanSami_1_1/B.cpp.tk                         |  70
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  27
code/Savlik_1_1/code.cpp.tk                         |  6
code/Savlik_2_1/code.cpp.tk                         |  31
code/shik_0_1/pa.cpp.tk                             |  33
code/shik_1_1/pb.cpp.tk                             |  32
code/shik_2_1/pc.cpp.tk                             |  53
code/simsa.st_0_1/A.cpp.tk                          |  15
code/simsa.st_1_1/B.cpp.tk                          |  21
code/simsa.st_2_1/C.cpp.tk                          |  50
code/SovietUnion_0_1/A.cpp.tk                       |  55
code/SovietUnion_1_1/B.cpp.tk                       |  68
code/SovietUnion_2_1/C.cpp.tk                       |  39
code/tailed_0_1/A.cpp.tk                            |  26
code/tailed_1_1/B.cpp.tk                            |  45
code/tailed_2_1/C.cpp.tk                            |  26
code/TheNatural_0_1/A.cpp.tk                        |  69
code/TheNatural_1_1/B.cpp.tk                        |  83
code/TheNatural_2_1/C.cpp.tk                        |  37
code/TrueBamboo_0_1/test.cpp.tk                     |  27
code/TrueBamboo_1_1/test.cpp.tk                     |  30
code/TrueBamboo_2_1/test.cpp.tk                     |  39
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  13
code/tur.turczyn_2_1/C.cpp.tk                       |  17
code/Tyg3R_0_1/A.cpp.tk                             |  8
code/Tyg3R_1_1/B.cpp.tk                             |  17
code/Tyg3R_2_1/C.cpp.tk                             |  20
code/UminchuR_0_1/main.cpp.tk                       |  21
code/UminchuR_1_1/main.cpp.tk                       |  26
code/UminchuR_2_1/main.cpp.tk                       |  53
code/wo..._0_1/a.cpp.tk                             |  11920
code/wo..._1_1/b.cpp.tk                             |  126
code/wo..._2_1/c.cpp.tk                             |  156
code/yswtt_0_1/A.cpp.tk                             |  26
code/yswtt_1_1/B.cpp.tk                             |  42
code/yswtt_2_1/C.cpp.tk                             |  41
code/ZhSh_0_1/a.cpp.tk                              |  30
code/ZhSh_1_1/b.cpp.tk                              |  77
code/ZhSh_2_1/c.cpp.tk                              |  62
