Begin
Comparing:  code/alanubi_0_1/a.cpp.tk
code/00/test.cpp.tk                                 |  44
code/01/test.cpp.tk                                 |  45
code/551100kk_0_1/A.cpp.tk                          |  46
code/551100kk_1_1/B.cpp.tk                          |  69
code/551100kk_2_1/C.cpp.tk                          |  79
code/achan1058_0_1/Q-A.cpp.tk                       |  14
code/achan1058_1_1/source.cpp.tk                    |  28
code/achan1058_2_1/source.cpp.tk                    |  57
code/alanubi_0_1/a.cpp.tk                           |  9032
code/alanubi_1_1/b.cpp.tk                           |  474
code/alanubi_2_1/c.cpp.tk                           |  383
code/AntiForest_0_1/q1.cpp.tk                       |  45
code/AntiForest_1_1/q2.cpp.tk                       |  15
code/AntiForest_2_1/q3.cpp.tk                       |  80
code/apiad_0_1/A.cpp.tk                             |  36
code/apiad_1_1/B.cpp.tk                             |  33
code/apiad_2_1/C.cpp.tk                             |  42
code/azaky_0_1/A.cpp.tk                             |  43
code/azaky_1_1/B.cpp.tk                             |  42
code/azaky_2_1/C.cpp.tk                             |  77
code/azariamuh_0_1/standing.cpp.tk                  |  33
code/azariamuh_1_1/pancake.cpp.tk                   |  39
code/azariamuh_2_1/dijkstra.cpp.tk                  |  33
code/bmerry_0_1/a.cpp.tk                            |  141
code/bmerry_1_1/b.cpp.tk                            |  126
code/bmerry_2_1/c.cpp.tk                            |  114
code/climpet_0_1/A.cpp.tk                           |  89
code/climpet_1_1/B.cpp.tk                           |  73
code/climpet_2_1/C.cpp.tk                           |  109
code/ctzsm_0_1/A.cpp.tk                             |  106
code/ctzsm_1_1/B.cpp.tk                             |  111
code/ctzsm_2_1/C.cpp.tk                             |  162
code/DanilC_0_1/problem.cpp.tk                      |  92
code/DanilC_1_1/problemB.cpp.tk                     |  108
code/DanilC_2_1/problemC.cpp.tk                     |  129
code/DEGwer_0_1/A.cpp.tk                            |  136
code/DEGwer_1_1/B.cpp.tk                            |  135
code/DEGwer_2_1/C.cpp.tk                            |  105
code/dmute_0_1/a.cpp.tk                             |  95
code/dmute_1_1/b.cpp.tk                             |  180
code/dmute_2_1/c2.cpp.tk                            |  184
code/fagu_0_1/A.cpp.tk                              |  74
code/fagu_1_1/B.cpp.tk                              |  75
code/fagu_2_1/C.cpp.tk                              |  107
code/FatalEagle_0_1/main.cpp.tk                     |  128
code/FatalEagle_1_1/main.cpp.tk                     |  214
code/FatalEagle_2_1/main.cpp.tk                     |  442
code/fullpower_0_1/A.cpp.tk                         |  124
code/fullpower_1_1/B.cpp.tk                         |  210
code/fullpower_2_1/C.cpp.tk                         |  254
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  67
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  65
code/ICastro_2_1/Dijkstra.cpp.tk                    |  151
code/ilackthatsuperpower_0_1/a.cpp.tk               |  161
code/ilackthatsuperpower_1_1/b.cpp.tk               |  158
code/ilackthatsuperpower_2_1/c.cpp.tk               |  151
code/iridescent_0_1/A.cpp.tk                        |  61
code/iridescent_1_1/B.cpp.tk                        |  128
code/iridescent_2_1/C.cpp.tk                        |  115
code/ishraq_0_1/main.cpp.tk                         |  57
code/ishraq_1_1/main.cpp.tk                         |  77
code/ishraq_2_1/main.cpp.tk                         |  102
code/JayXon_0_1/A.cpp.tk                            |  41
code/JayXon_1_1/B.cpp.tk                            |  101
code/JayXon_2_1/C.cpp.tk                            |  37
code/Josse_0_1/A.cpp.tk                             |  99
code/Josse_1_1/B.cpp.tk                             |  125
code/Josse_2_1/C.cpp.tk                             |  206
code/kcm1700_0_1/a.cpp.tk                           |  210
code/kcm1700_1_1/b.cpp.tk                           |  264
code/kcm1700_2_1/c.cpp.tk                           |  228
code/kevinsogo_0_1/a.cpp.tk                         |  55
code/kevinsogo_1_1/b.cpp.tk                         |  61
code/kevinsogo_2_1/c.cpp.tk                         |  76
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  18
code/LazyAnna_0_1/1.cpp.tk                          |  65
code/LazyAnna_1_1/2-1.cpp.tk                        |  68
code/LazyAnna_2_1/3.cpp.tk                          |  51
code/Merkurev_0_1/A.cpp.tk                          |  215
code/Merkurev_1_1/B.cpp.tk                          |  209
code/Merkurev_2_1/C.cpp.tk                          |  180
code/mezei_0_1/main.cpp.tk                          |  172
code/mezei_1_1/main.cpp.tk                          |  130
code/mezei_2_1/main.cpp.tk                          |  236
code/Mister_0_1/a.cpp.tk                            |  105
code/Mister_1_1/b.cpp.tk                            |  136
code/Mister_2_1/c.cpp.tk                            |  108
code/namonakiacc_0_1/cpp.cpp.tk                     |  42
code/namonakiacc_1_1/cpp.cpp.tk                     |  40
code/namonakiacc_2_1/cpp.cpp.tk                     |  66
code/Nicolas16_0_1/main.cpp.tk                      |  57
code/Nicolas16_1_1/main.cpp.tk                      |  53
code/Nicolas16_2_1/main.cpp.tk                      |  239
code/pandamonium_0_1/a.cpp.tk                       |  186
code/pandamonium_1_1/b.cpp.tk                       |  213
code/pandamonium_2_1/c.cpp.tk                       |  111
code/pflueger_0_1/A.cpp.tk                          |  118
code/pflueger_1_1/B.cpp.tk                          |  118
code/pflueger_2_1/C.cpp.tk                          |  157
code/ponyopoppo_0_1/A.cpp.tk                        |  21
code/ponyopoppo_1_1/B.cpp.tk                        |  25
code/ponyopoppo_2_1/C.cpp.tk                        |  105
code/Ragnar_0_1/A.cpp.tk                            |  23
code/Ragnar_1_1/B-2.cpp.tk                          |  47
code/Ragnar_2_1/C.cpp.tk                            |  67
code/saffah_0_1/t.cpp.tk                            |  49
code/saffah_1_1/t.cpp.tk                            |  47
code/saffah_2_1/t.cpp.tk                            |  94
code/SamanSami_0_1/A.cpp.tk                         |  29
code/SamanSami_1_1/B.cpp.tk                         |  117
code/SamanSami_2_1/C.cpp.tk                         |  10
code/Savlik_0_1/code.cpp.tk                         |  111
code/Savlik_1_1/code.cpp.tk                         |  14
code/Savlik_2_1/code.cpp.tk                         |  66
code/shik_0_1/pa.cpp.tk                             |  71
code/shik_1_1/pb.cpp.tk                             |  69
code/shik_2_1/pc.cpp.tk                             |  107
code/simsa.st_0_1/A.cpp.tk                          |  33
code/simsa.st_1_1/B.cpp.tk                          |  45
code/simsa.st_2_1/C.cpp.tk                          |  98
code/SovietUnion_0_1/A.cpp.tk                       |  91
code/SovietUnion_1_1/B.cpp.tk                       |  108
code/SovietUnion_2_1/C.cpp.tk                       |  72
code/tailed_0_1/A.cpp.tk                            |  61
code/tailed_1_1/B.cpp.tk                            |  71
code/tailed_2_1/C.cpp.tk                            |  51
code/TheNatural_0_1/A.cpp.tk                        |  134
code/TheNatural_1_1/B.cpp.tk                        |  150
code/TheNatural_2_1/C.cpp.tk                        |  68
code/TrueBamboo_0_1/test.cpp.tk                     |  52
code/TrueBamboo_1_1/test.cpp.tk                     |  55
code/TrueBamboo_2_1/test.cpp.tk                     |  73
code/tur.turczyn_0_1/A.cpp.tk                       |  22
code/tur.turczyn_1_1/B.cpp.tk                       |  30
code/tur.turczyn_2_1/C.cpp.tk                       |  36
code/Tyg3R_0_1/A.cpp.tk                             |  27
code/Tyg3R_1_1/B.cpp.tk                             |  22
code/Tyg3R_2_1/C.cpp.tk                             |  43
code/UminchuR_0_1/main.cpp.tk                       |  55
code/UminchuR_1_1/main.cpp.tk                       |  65
code/UminchuR_2_1/main.cpp.tk                       |  87
code/wo..._0_1/a.cpp.tk                             |  240
code/wo..._1_1/b.cpp.tk                             |  209
code/wo..._2_1/c.cpp.tk                             |  254
code/yswtt_0_1/A.cpp.tk                             |  44
code/yswtt_1_1/B.cpp.tk                             |  59
code/yswtt_2_1/C.cpp.tk                             |  84
code/ZhSh_0_1/a.cpp.tk                              |  79
code/ZhSh_1_1/b.cpp.tk                              |  118
code/ZhSh_2_1/c.cpp.tk                              |  104
