Begin
Comparing:  code/achan1058_2_1/source.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  11
code/551100kk_1_1/B.cpp.tk                          |  17
code/551100kk_2_1/C.cpp.tk                          |  43
code/achan1058_0_1/Q-A.cpp.tk                       |  13
code/achan1058_1_1/source.cpp.tk                    |  627
code/achan1058_2_1/source.cpp.tk                    |  67868
code/alanubi_0_1/a.cpp.tk                           |  9
code/alanubi_1_1/b.cpp.tk                           |  13
code/alanubi_2_1/c.cpp.tk                           |  70
code/AntiForest_0_1/q1.cpp.tk                       |  16
code/AntiForest_1_1/q2.cpp.tk                       |  8
code/AntiForest_2_1/q3.cpp.tk                       |  51
code/apiad_0_1/A.cpp.tk                             |  18
code/apiad_1_1/B.cpp.tk                             |  24
code/apiad_2_1/C.cpp.tk                             |  25
code/azaky_0_1/A.cpp.tk                             |  20
code/azaky_1_1/B.cpp.tk                             |  23
code/azaky_2_1/C.cpp.tk                             |  56
code/azariamuh_0_1/standing.cpp.tk                  |  12
code/azariamuh_1_1/pancake.cpp.tk                   |  26
code/azariamuh_2_1/dijkstra.cpp.tk                  |  23
code/bmerry_0_1/a.cpp.tk                            |  52
code/bmerry_1_1/b.cpp.tk                            |  59
code/bmerry_2_1/c.cpp.tk                            |  60
code/climpet_0_1/A.cpp.tk                           |  32
code/climpet_1_1/B.cpp.tk                           |  35
code/climpet_2_1/C.cpp.tk                           |  51
code/ctzsm_0_1/A.cpp.tk                             |  12
code/ctzsm_1_1/B.cpp.tk                             |  16
code/ctzsm_2_1/C.cpp.tk                             |  62
code/DanilC_0_1/problem.cpp.tk                      |  23
code/DanilC_1_1/problemB.cpp.tk                     |  34
code/DanilC_2_1/problemC.cpp.tk                     |  95
code/DEGwer_0_1/A.cpp.tk                            |  16
code/DEGwer_1_1/B.cpp.tk                            |  17
code/DEGwer_2_1/C.cpp.tk                            |  29
code/dmute_0_1/a.cpp.tk                             |  7
code/dmute_1_1/b.cpp.tk                             |  12
code/dmute_2_1/c2.cpp.tk                            |  35
code/fagu_0_1/A.cpp.tk                              |  17
code/fagu_1_1/B.cpp.tk                              |  17
code/fagu_2_1/C.cpp.tk                              |  43
code/FatalEagle_0_1/main.cpp.tk                     |  10
code/FatalEagle_1_1/main.cpp.tk                     |  16
code/FatalEagle_2_1/main.cpp.tk                     |  119
code/fullpower_0_1/A.cpp.tk                         |  17
code/fullpower_1_1/B.cpp.tk                         |  19
code/fullpower_2_1/C.cpp.tk                         |  54
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  9
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  14
code/ICastro_2_1/Dijkstra.cpp.tk                    |  101
code/ilackthatsuperpower_0_1/a.cpp.tk               |  69
code/ilackthatsuperpower_1_1/b.cpp.tk               |  73
code/ilackthatsuperpower_2_1/c.cpp.tk               |  102
code/iridescent_0_1/A.cpp.tk                        |  7
code/iridescent_1_1/B.cpp.tk                        |  10
code/iridescent_2_1/C.cpp.tk                        |  15
code/ishraq_0_1/main.cpp.tk                         |  9
code/ishraq_1_1/main.cpp.tk                         |  13
code/ishraq_2_1/main.cpp.tk                         |  67
code/JayXon_0_1/A.cpp.tk                            |  5
code/JayXon_1_1/B.cpp.tk                            |  14
code/JayXon_2_1/C.cpp.tk                            |  41
code/Josse_0_1/A.cpp.tk                             |  10
code/Josse_1_1/B.cpp.tk                             |  14
code/Josse_2_1/C.cpp.tk                             |  68
code/kcm1700_0_1/a.cpp.tk                           |  7
code/kcm1700_1_1/b.cpp.tk                           |  11
code/kcm1700_2_1/c.cpp.tk                           |  44
code/kevinsogo_0_1/a.cpp.tk                         |  10
code/kevinsogo_1_1/b.cpp.tk                         |  14
code/kevinsogo_2_1/c.cpp.tk                         |  46
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  32
code/LazyAnna_0_1/1.cpp.tk                          |  7
code/LazyAnna_1_1/2-1.cpp.tk                        |  10
code/LazyAnna_2_1/3.cpp.tk                          |  30
code/Merkurev_0_1/A.cpp.tk                          |  11
code/Merkurev_1_1/B.cpp.tk                          |  26
code/Merkurev_2_1/C.cpp.tk                          |  27
code/mezei_0_1/main.cpp.tk                          |  12
code/mezei_1_1/main.cpp.tk                          |  11
code/mezei_2_1/main.cpp.tk                          |  50
code/Mister_0_1/a.cpp.tk                            |  10
code/Mister_1_1/b.cpp.tk                            |  10
code/Mister_2_1/c.cpp.tk                            |  25
code/namonakiacc_0_1/cpp.cpp.tk                     |  50
code/namonakiacc_1_1/cpp.cpp.tk                     |  54
code/namonakiacc_2_1/cpp.cpp.tk                     |  84
code/Nicolas16_0_1/main.cpp.tk                      |  5
code/Nicolas16_1_1/main.cpp.tk                      |  4
code/Nicolas16_2_1/main.cpp.tk                      |  76
code/pandamonium_0_1/a.cpp.tk                       |  9
code/pandamonium_1_1/b.cpp.tk                       |  28
code/pandamonium_2_1/c.cpp.tk                       |  18
code/pflueger_0_1/A.cpp.tk                          |  8
code/pflueger_1_1/B.cpp.tk                          |  13
code/pflueger_2_1/C.cpp.tk                          |  67
code/ponyopoppo_0_1/A.cpp.tk                        |  11
code/ponyopoppo_1_1/B.cpp.tk                        |  23
code/ponyopoppo_2_1/C.cpp.tk                        |  180
code/Ragnar_0_1/A.cpp.tk                            |  49
code/Ragnar_1_1/B-2.cpp.tk                          |  54
code/Ragnar_2_1/C.cpp.tk                            |  70
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  15
code/saffah_2_1/t.cpp.tk                            |  70
code/SamanSami_0_1/A.cpp.tk                         |  2
code/SamanSami_1_1/B.cpp.tk                         |  10
code/SamanSami_2_1/C.cpp.tk                         |  14
code/Savlik_0_1/code.cpp.tk                         |  9
code/Savlik_1_1/code.cpp.tk                         |  12
code/Savlik_2_1/code.cpp.tk                         |  63
code/shik_0_1/pa.cpp.tk                             |  55
code/shik_1_1/pb.cpp.tk                             |  57
code/shik_2_1/pc.cpp.tk                             |  84
code/simsa.st_0_1/A.cpp.tk                          |  10
code/simsa.st_1_1/B.cpp.tk                          |  14
code/simsa.st_2_1/C.cpp.tk                          |  72
code/SovietUnion_0_1/A.cpp.tk                       |  12
code/SovietUnion_1_1/B.cpp.tk                       |  14
code/SovietUnion_2_1/C.cpp.tk                       |  63
code/tailed_0_1/A.cpp.tk                            |  9
code/tailed_1_1/B.cpp.tk                            |  12
code/tailed_2_1/C.cpp.tk                            |  44
code/TheNatural_0_1/A.cpp.tk                        |  7
code/TheNatural_1_1/B.cpp.tk                        |  10
code/TheNatural_2_1/C.cpp.tk                        |  17
code/TrueBamboo_0_1/test.cpp.tk                     |  12
code/TrueBamboo_1_1/test.cpp.tk                     |  17
code/TrueBamboo_2_1/test.cpp.tk                     |  53
code/tur.turczyn_0_1/A.cpp.tk                       |  43
code/tur.turczyn_1_1/B.cpp.tk                       |  51
code/tur.turczyn_2_1/C.cpp.tk                       |  57
code/Tyg3R_0_1/A.cpp.tk                             |  13
code/Tyg3R_1_1/B.cpp.tk                             |  17
code/Tyg3R_2_1/C.cpp.tk                             |  18
code/UminchuR_0_1/main.cpp.tk                       |  48
code/UminchuR_1_1/main.cpp.tk                       |  53
code/UminchuR_2_1/main.cpp.tk                       |  74
code/wo..._0_1/a.cpp.tk                             |  10
code/wo..._1_1/b.cpp.tk                             |  14
code/wo..._2_1/c.cpp.tk                             |  49
code/yswtt_0_1/A.cpp.tk                             |  7
code/yswtt_1_1/B.cpp.tk                             |  12
code/yswtt_2_1/C.cpp.tk                             |  36
code/ZhSh_0_1/a.cpp.tk                              |  7
code/ZhSh_1_1/b.cpp.tk                              |  61
code/ZhSh_2_1/c.cpp.tk                              |  83
