Begin
Comparing:  code/shik_2_1/pc.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  10
code/551100kk_1_1/B.cpp.tk                          |  17
code/551100kk_2_1/C.cpp.tk                          |  124
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  20
code/achan1058_2_1/source.cpp.tk                    |  43
code/alanubi_0_1/a.cpp.tk                           |  8
code/alanubi_1_1/b.cpp.tk                           |  13
code/alanubi_2_1/c.cpp.tk                           |  56
code/AntiForest_0_1/q1.cpp.tk                       |  16
code/AntiForest_1_1/q2.cpp.tk                       |  7
code/AntiForest_2_1/q3.cpp.tk                       |  188
code/apiad_0_1/A.cpp.tk                             |  14
code/apiad_1_1/B.cpp.tk                             |  20
code/apiad_2_1/C.cpp.tk                             |  33
code/azaky_0_1/A.cpp.tk                             |  19
code/azaky_1_1/B.cpp.tk                             |  22
code/azaky_2_1/C.cpp.tk                             |  66
code/azariamuh_0_1/standing.cpp.tk                  |  12
code/azariamuh_1_1/pancake.cpp.tk                   |  27
code/azariamuh_2_1/dijkstra.cpp.tk                  |  27
code/bmerry_0_1/a.cpp.tk                            |  35
code/bmerry_1_1/b.cpp.tk                            |  40
code/bmerry_2_1/c.cpp.tk                            |  50
code/climpet_0_1/A.cpp.tk                           |  22
code/climpet_1_1/B.cpp.tk                           |  25
code/climpet_2_1/C.cpp.tk                           |  48
code/ctzsm_0_1/A.cpp.tk                             |  11
code/ctzsm_1_1/B.cpp.tk                             |  15
code/ctzsm_2_1/C.cpp.tk                             |  86
code/DanilC_0_1/problem.cpp.tk                      |  22
code/DanilC_1_1/problemB.cpp.tk                     |  34
code/DanilC_2_1/problemC.cpp.tk                     |  83
code/DEGwer_0_1/A.cpp.tk                            |  14
code/DEGwer_1_1/B.cpp.tk                            |  15
code/DEGwer_2_1/C.cpp.tk                            |  164
code/dmute_0_1/a.cpp.tk                             |  7
code/dmute_1_1/b.cpp.tk                             |  12
code/dmute_2_1/c2.cpp.tk                            |  38
code/fagu_0_1/A.cpp.tk                              |  6
code/fagu_1_1/B.cpp.tk                              |  6
code/fagu_2_1/C.cpp.tk                              |  43
code/FatalEagle_0_1/main.cpp.tk                     |  10
code/FatalEagle_1_1/main.cpp.tk                     |  16
code/FatalEagle_2_1/main.cpp.tk                     |  122
code/fullpower_0_1/A.cpp.tk                         |  17
code/fullpower_1_1/B.cpp.tk                         |  22
code/fullpower_2_1/C.cpp.tk                         |  85
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  7
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  12
code/ICastro_2_1/Dijkstra.cpp.tk                    |  78
code/ilackthatsuperpower_0_1/a.cpp.tk               |  89
code/ilackthatsuperpower_1_1/b.cpp.tk               |  90
code/ilackthatsuperpower_2_1/c.cpp.tk               |  120
code/iridescent_0_1/A.cpp.tk                        |  7
code/iridescent_1_1/B.cpp.tk                        |  7
code/iridescent_2_1/C.cpp.tk                        |  25
code/ishraq_0_1/main.cpp.tk                         |  10
code/ishraq_1_1/main.cpp.tk                         |  12
code/ishraq_2_1/main.cpp.tk                         |  64
code/JayXon_0_1/A.cpp.tk                            |  6
code/JayXon_1_1/B.cpp.tk                            |  16
code/JayXon_2_1/C.cpp.tk                            |  31
code/Josse_0_1/A.cpp.tk                             |  8
code/Josse_1_1/B.cpp.tk                             |  11
code/Josse_2_1/C.cpp.tk                             |  66
code/kcm1700_0_1/a.cpp.tk                           |  7
code/kcm1700_1_1/b.cpp.tk                           |  10
code/kcm1700_2_1/c.cpp.tk                           |  42
code/kevinsogo_0_1/a.cpp.tk                         |  11
code/kevinsogo_1_1/b.cpp.tk                         |  12
code/kevinsogo_2_1/c.cpp.tk                         |  60
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  14
code/LazyAnna_0_1/1.cpp.tk                          |  6
code/LazyAnna_1_1/2-1.cpp.tk                        |  9
code/LazyAnna_2_1/3.cpp.tk                          |  35
code/Merkurev_0_1/A.cpp.tk                          |  12
code/Merkurev_1_1/B.cpp.tk                          |  23
code/Merkurev_2_1/C.cpp.tk                          |  26
code/mezei_0_1/main.cpp.tk                          |  12
code/mezei_1_1/main.cpp.tk                          |  11
code/mezei_2_1/main.cpp.tk                          |  49
code/Mister_0_1/a.cpp.tk                            |  8
code/Mister_1_1/b.cpp.tk                            |  10
code/Mister_2_1/c.cpp.tk                            |  136
code/namonakiacc_0_1/cpp.cpp.tk                     |  18
code/namonakiacc_1_1/cpp.cpp.tk                     |  22
code/namonakiacc_2_1/cpp.cpp.tk                     |  52
code/Nicolas16_0_1/main.cpp.tk                      |  4
code/Nicolas16_1_1/main.cpp.tk                      |  4
code/Nicolas16_2_1/main.cpp.tk                      |  51
code/pandamonium_0_1/a.cpp.tk                       |  8
code/pandamonium_1_1/b.cpp.tk                       |  28
code/pandamonium_2_1/c.cpp.tk                       |  19
code/pflueger_0_1/A.cpp.tk                          |  5
code/pflueger_1_1/B.cpp.tk                          |  11
code/pflueger_2_1/C.cpp.tk                          |  41
code/ponyopoppo_0_1/A.cpp.tk                        |  8
code/ponyopoppo_1_1/B.cpp.tk                        |  27
code/ponyopoppo_2_1/C.cpp.tk                        |  107
code/Ragnar_0_1/A.cpp.tk                            |  11
code/Ragnar_1_1/B-2.cpp.tk                          |  16
code/Ragnar_2_1/C.cpp.tk                            |  34
code/saffah_0_1/t.cpp.tk                            |  11
code/saffah_1_1/t.cpp.tk                            |  15
code/saffah_2_1/t.cpp.tk                            |  71
code/SamanSami_0_1/A.cpp.tk                         |  1
code/SamanSami_1_1/B.cpp.tk                         |  8
code/SamanSami_2_1/C.cpp.tk                         |  9
code/Savlik_0_1/code.cpp.tk                         |  7
code/Savlik_1_1/code.cpp.tk                         |  11
code/Savlik_2_1/code.cpp.tk                         |  51
code/shik_0_1/pa.cpp.tk                             |  29537
code/shik_1_1/pb.cpp.tk                             |  29537
code/shik_2_1/pc.cpp.tk                             |  292266
code/simsa.st_0_1/A.cpp.tk                          |  10
code/simsa.st_1_1/B.cpp.tk                          |  14
code/simsa.st_2_1/C.cpp.tk                          |  66
code/SovietUnion_0_1/A.cpp.tk                       |  13
code/SovietUnion_1_1/B.cpp.tk                       |  15
code/SovietUnion_2_1/C.cpp.tk                       |  53
code/tailed_0_1/A.cpp.tk                            |  7
code/tailed_1_1/B.cpp.tk                            |  10
code/tailed_2_1/C.cpp.tk                            |  37
code/TheNatural_0_1/A.cpp.tk                        |  7
code/TheNatural_1_1/B.cpp.tk                        |  9
code/TheNatural_2_1/C.cpp.tk                        |  23
code/TrueBamboo_0_1/test.cpp.tk                     |  10
code/TrueBamboo_1_1/test.cpp.tk                     |  14
code/TrueBamboo_2_1/test.cpp.tk                     |  37
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  16
code/tur.turczyn_2_1/C.cpp.tk                       |  29
code/Tyg3R_0_1/A.cpp.tk                             |  9
code/Tyg3R_1_1/B.cpp.tk                             |  18
code/Tyg3R_2_1/C.cpp.tk                             |  33
code/UminchuR_0_1/main.cpp.tk                       |  17
code/UminchuR_1_1/main.cpp.tk                       |  24
code/UminchuR_2_1/main.cpp.tk                       |  45
code/wo..._0_1/a.cpp.tk                             |  10
code/wo..._1_1/b.cpp.tk                             |  12
code/wo..._2_1/c.cpp.tk                             |  148
code/yswtt_0_1/A.cpp.tk                             |  5
code/yswtt_1_1/B.cpp.tk                             |  12
code/yswtt_2_1/C.cpp.tk                             |  28
code/ZhSh_0_1/a.cpp.tk                              |  5
code/ZhSh_1_1/b.cpp.tk                              |  47
code/ZhSh_2_1/c.cpp.tk                              |  107
