Begin
Comparing:  code/ishraq_0_1/main.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  54
code/551100kk_1_1/B.cpp.tk                          |  29
code/551100kk_2_1/C.cpp.tk                          |  44
code/achan1058_0_1/Q-A.cpp.tk                       |  40
code/achan1058_1_1/source.cpp.tk                    |  24
code/achan1058_2_1/source.cpp.tk                    |  39
code/alanubi_0_1/a.cpp.tk                           |  46
code/alanubi_1_1/b.cpp.tk                           |  45
code/alanubi_2_1/c.cpp.tk                           |  82
code/AntiForest_0_1/q1.cpp.tk                       |  54
code/AntiForest_1_1/q2.cpp.tk                       |  20
code/AntiForest_2_1/q3.cpp.tk                       |  65
code/apiad_0_1/A.cpp.tk                             |  109
code/apiad_1_1/B.cpp.tk                             |  33
code/apiad_2_1/C.cpp.tk                             |  33
code/azaky_0_1/A.cpp.tk                             |  50
code/azaky_1_1/B.cpp.tk                             |  36
code/azaky_2_1/C.cpp.tk                             |  59
code/azariamuh_0_1/standing.cpp.tk                  |  36
code/azariamuh_1_1/pancake.cpp.tk                   |  45
code/azariamuh_2_1/dijkstra.cpp.tk                  |  28
code/bmerry_0_1/a.cpp.tk                            |  45
code/bmerry_1_1/b.cpp.tk                            |  42
code/bmerry_2_1/c.cpp.tk                            |  48
code/climpet_0_1/A.cpp.tk                           |  29
code/climpet_1_1/B.cpp.tk                           |  22
code/climpet_2_1/C.cpp.tk                           |  39
code/ctzsm_0_1/A.cpp.tk                             |  47
code/ctzsm_1_1/B.cpp.tk                             |  28
code/ctzsm_2_1/C.cpp.tk                             |  69
code/DanilC_0_1/problem.cpp.tk                      |  29
code/DanilC_1_1/problemB.cpp.tk                     |  34
code/DanilC_2_1/problemC.cpp.tk                     |  75
code/DEGwer_0_1/A.cpp.tk                            |  28
code/DEGwer_1_1/B.cpp.tk                            |  29
code/DEGwer_2_1/C.cpp.tk                            |  32
code/dmute_0_1/a.cpp.tk                             |  55
code/dmute_1_1/b.cpp.tk                             |  40
code/dmute_2_1/c2.cpp.tk                            |  54
code/fagu_0_1/A.cpp.tk                              |  11
code/fagu_1_1/B.cpp.tk                              |  10
code/fagu_2_1/C.cpp.tk                              |  41
code/FatalEagle_0_1/main.cpp.tk                     |  46
code/FatalEagle_1_1/main.cpp.tk                     |  30
code/FatalEagle_2_1/main.cpp.tk                     |  109
code/fullpower_0_1/A.cpp.tk                         |  32
code/fullpower_1_1/B.cpp.tk                         |  34
code/fullpower_2_1/C.cpp.tk                         |  64
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  13
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  14
code/ICastro_2_1/Dijkstra.cpp.tk                    |  92
code/ilackthatsuperpower_0_1/a.cpp.tk               |  62
code/ilackthatsuperpower_1_1/b.cpp.tk               |  52
code/ilackthatsuperpower_2_1/c.cpp.tk               |  72
code/iridescent_0_1/A.cpp.tk                        |  18
code/iridescent_1_1/B.cpp.tk                        |  16
code/iridescent_2_1/C.cpp.tk                        |  21
code/ishraq_0_1/main.cpp.tk                         |  3457
code/ishraq_1_1/main.cpp.tk                         |  135
code/ishraq_2_1/main.cpp.tk                         |  153
code/JayXon_0_1/A.cpp.tk                            |  16
code/JayXon_1_1/B.cpp.tk                            |  17
code/JayXon_2_1/C.cpp.tk                            |  25
code/Josse_0_1/A.cpp.tk                             |  30
code/Josse_1_1/B.cpp.tk                             |  18
code/Josse_2_1/C.cpp.tk                             |  55
code/kcm1700_0_1/a.cpp.tk                           |  48
code/kcm1700_1_1/b.cpp.tk                           |  41
code/kcm1700_2_1/c.cpp.tk                           |  65
code/kevinsogo_0_1/a.cpp.tk                         |  45
code/kevinsogo_1_1/b.cpp.tk                         |  45
code/kevinsogo_2_1/c.cpp.tk                         |  66
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  14
code/LazyAnna_1_1/2-1.cpp.tk                        |  17
code/LazyAnna_2_1/3.cpp.tk                          |  27
code/Merkurev_0_1/A.cpp.tk                          |  45
code/Merkurev_1_1/B.cpp.tk                          |  40
code/Merkurev_2_1/C.cpp.tk                          |  41
code/mezei_0_1/main.cpp.tk                          |  27
code/mezei_1_1/main.cpp.tk                          |  21
code/mezei_2_1/main.cpp.tk                          |  52
code/Mister_0_1/a.cpp.tk                            |  41
code/Mister_1_1/b.cpp.tk                            |  37
code/Mister_2_1/c.cpp.tk                            |  38
code/namonakiacc_0_1/cpp.cpp.tk                     |  68
code/namonakiacc_1_1/cpp.cpp.tk                     |  65
code/namonakiacc_2_1/cpp.cpp.tk                     |  77
code/Nicolas16_0_1/main.cpp.tk                      |  16
code/Nicolas16_1_1/main.cpp.tk                      |  18
code/Nicolas16_2_1/main.cpp.tk                      |  57
code/pandamonium_0_1/a.cpp.tk                       |  42
code/pandamonium_1_1/b.cpp.tk                       |  37
code/pandamonium_2_1/c.cpp.tk                       |  36
code/pflueger_0_1/A.cpp.tk                          |  17
code/pflueger_1_1/B.cpp.tk                          |  16
code/pflueger_2_1/C.cpp.tk                          |  37
code/ponyopoppo_0_1/A.cpp.tk                        |  17
code/ponyopoppo_1_1/B.cpp.tk                        |  24
code/ponyopoppo_2_1/C.cpp.tk                        |  76
code/Ragnar_0_1/A.cpp.tk                            |  14
code/Ragnar_1_1/B-2.cpp.tk                          |  18
code/Ragnar_2_1/C.cpp.tk                            |  28
code/saffah_0_1/t.cpp.tk                            |  71
code/saffah_1_1/t.cpp.tk                            |  64
code/saffah_2_1/t.cpp.tk                            |  77
code/SamanSami_0_1/A.cpp.tk                         |  5
code/SamanSami_1_1/B.cpp.tk                         |  13
code/SamanSami_2_1/C.cpp.tk                         |  7
code/Savlik_0_1/code.cpp.tk                         |  12
code/Savlik_1_1/code.cpp.tk                         |  13
code/Savlik_2_1/code.cpp.tk                         |  40
code/shik_0_1/pa.cpp.tk                             |  56
code/shik_1_1/pb.cpp.tk                             |  46
code/shik_2_1/pc.cpp.tk                             |  82
code/simsa.st_0_1/A.cpp.tk                          |  38
code/simsa.st_1_1/B.cpp.tk                          |  57
code/simsa.st_2_1/C.cpp.tk                          |  79
code/SovietUnion_0_1/A.cpp.tk                       |  47
code/SovietUnion_1_1/B.cpp.tk                       |  32
code/SovietUnion_2_1/C.cpp.tk                       |  42
code/tailed_0_1/A.cpp.tk                            |  17
code/tailed_1_1/B.cpp.tk                            |  15
code/tailed_2_1/C.cpp.tk                            |  36
code/TheNatural_0_1/A.cpp.tk                        |  13
code/TheNatural_1_1/B.cpp.tk                        |  16
code/TheNatural_2_1/C.cpp.tk                        |  17
code/TrueBamboo_0_1/test.cpp.tk                     |  55
code/TrueBamboo_1_1/test.cpp.tk                     |  20
code/TrueBamboo_2_1/test.cpp.tk                     |  34
code/tur.turczyn_0_1/A.cpp.tk                       |  25
code/tur.turczyn_1_1/B.cpp.tk                       |  19
code/tur.turczyn_2_1/C.cpp.tk                       |  27
code/Tyg3R_0_1/A.cpp.tk                             |  33
code/Tyg3R_1_1/B.cpp.tk                             |  25
code/Tyg3R_2_1/C.cpp.tk                             |  31
code/UminchuR_0_1/main.cpp.tk                       |  39
code/UminchuR_1_1/main.cpp.tk                       |  49
code/UminchuR_2_1/main.cpp.tk                       |  57
code/wo..._0_1/a.cpp.tk                             |  37
code/wo..._1_1/b.cpp.tk                             |  35
code/wo..._2_1/c.cpp.tk                             |  65
code/yswtt_0_1/A.cpp.tk                             |  18
code/yswtt_1_1/B.cpp.tk                             |  15
code/yswtt_2_1/C.cpp.tk                             |  30
code/ZhSh_0_1/a.cpp.tk                              |  28
code/ZhSh_1_1/b.cpp.tk                              |  47
code/ZhSh_2_1/c.cpp.tk                              |  59
