Begin
Comparing:  code/climpet_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  14
code/551100kk_1_1/B.cpp.tk                          |  18
code/551100kk_2_1/C.cpp.tk                          |  29
code/achan1058_0_1/Q-A.cpp.tk                       |  9
code/achan1058_1_1/source.cpp.tk                    |  37
code/achan1058_2_1/source.cpp.tk                    |  60
code/alanubi_0_1/a.cpp.tk                           |  26
code/alanubi_1_1/b.cpp.tk                           |  23
code/alanubi_2_1/c.cpp.tk                           |  83
code/AntiForest_0_1/q1.cpp.tk                       |  16
code/AntiForest_1_1/q2.cpp.tk                       |  7
code/AntiForest_2_1/q3.cpp.tk                       |  42
code/apiad_0_1/A.cpp.tk                             |  21
code/apiad_1_1/B.cpp.tk                             |  23
code/apiad_2_1/C.cpp.tk                             |  24
code/azaky_0_1/A.cpp.tk                             |  22
code/azaky_1_1/B.cpp.tk                             |  23
code/azaky_2_1/C.cpp.tk                             |  50
code/azariamuh_0_1/standing.cpp.tk                  |  17
code/azariamuh_1_1/pancake.cpp.tk                   |  18
code/azariamuh_2_1/dijkstra.cpp.tk                  |  18
code/bmerry_0_1/a.cpp.tk                            |  92
code/bmerry_1_1/b.cpp.tk                            |  63
code/bmerry_2_1/c.cpp.tk                            |  62
code/climpet_0_1/A.cpp.tk                           |  24449
code/climpet_1_1/B.cpp.tk                           |  4549
code/climpet_2_1/C.cpp.tk                           |  3604
code/ctzsm_0_1/A.cpp.tk                             |  42
code/ctzsm_1_1/B.cpp.tk                             |  37
code/ctzsm_2_1/C.cpp.tk                             |  82
code/DanilC_0_1/problem.cpp.tk                      |  72
code/DanilC_1_1/problemB.cpp.tk                     |  65
code/DanilC_2_1/problemC.cpp.tk                     |  103
code/DEGwer_0_1/A.cpp.tk                            |  28
code/DEGwer_1_1/B.cpp.tk                            |  30
code/DEGwer_2_1/C.cpp.tk                            |  26
code/dmute_0_1/a.cpp.tk                             |  20
code/dmute_1_1/b.cpp.tk                             |  32
code/dmute_2_1/c2.cpp.tk                            |  48
code/fagu_0_1/A.cpp.tk                              |  15
code/fagu_1_1/B.cpp.tk                              |  15
code/fagu_2_1/C.cpp.tk                              |  35
code/FatalEagle_0_1/main.cpp.tk                     |  24
code/FatalEagle_1_1/main.cpp.tk                     |  40
code/FatalEagle_2_1/main.cpp.tk                     |  132
code/fullpower_0_1/A.cpp.tk                         |  30
code/fullpower_1_1/B.cpp.tk                         |  47
code/fullpower_2_1/C.cpp.tk                         |  76
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  85
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  30
code/ICastro_2_1/Dijkstra.cpp.tk                    |  85
code/ilackthatsuperpower_0_1/a.cpp.tk               |  113
code/ilackthatsuperpower_1_1/b.cpp.tk               |  99
code/ilackthatsuperpower_2_1/c.cpp.tk               |  119
code/iridescent_0_1/A.cpp.tk                        |  24
code/iridescent_1_1/B.cpp.tk                        |  38
code/iridescent_2_1/C.cpp.tk                        |  32
code/ishraq_0_1/main.cpp.tk                         |  11
code/ishraq_1_1/main.cpp.tk                         |  17
code/ishraq_2_1/main.cpp.tk                         |  49
code/JayXon_0_1/A.cpp.tk                            |  15
code/JayXon_1_1/B.cpp.tk                            |  27
code/JayXon_2_1/C.cpp.tk                            |  31
code/Josse_0_1/A.cpp.tk                             |  28
code/Josse_1_1/B.cpp.tk                             |  26
code/Josse_2_1/C.cpp.tk                             |  80
code/kcm1700_0_1/a.cpp.tk                           |  27
code/kcm1700_1_1/b.cpp.tk                           |  26
code/kcm1700_2_1/c.cpp.tk                           |  52
code/kevinsogo_0_1/a.cpp.tk                         |  10
code/kevinsogo_1_1/b.cpp.tk                         |  14
code/kevinsogo_2_1/c.cpp.tk                         |  39
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  9
code/LazyAnna_0_1/1.cpp.tk                          |  66
code/LazyAnna_1_1/2-1.cpp.tk                        |  42
code/LazyAnna_2_1/3.cpp.tk                          |  42
code/Merkurev_0_1/A.cpp.tk                          |  35
code/Merkurev_1_1/B.cpp.tk                          |  38
code/Merkurev_2_1/C.cpp.tk                          |  42
code/mezei_0_1/main.cpp.tk                          |  33
code/mezei_1_1/main.cpp.tk                          |  23
code/mezei_2_1/main.cpp.tk                          |  56
code/Mister_0_1/a.cpp.tk                            |  35
code/Mister_1_1/b.cpp.tk                            |  30
code/Mister_2_1/c.cpp.tk                            |  55
code/namonakiacc_0_1/cpp.cpp.tk                     |  57
code/namonakiacc_1_1/cpp.cpp.tk                     |  57
code/namonakiacc_2_1/cpp.cpp.tk                     |  69
code/Nicolas16_0_1/main.cpp.tk                      |  10
code/Nicolas16_1_1/main.cpp.tk                      |  9
code/Nicolas16_2_1/main.cpp.tk                      |  65
code/pandamonium_0_1/a.cpp.tk                       |  19
code/pandamonium_1_1/b.cpp.tk                       |  36
code/pandamonium_2_1/c.cpp.tk                       |  24
code/pflueger_0_1/A.cpp.tk                          |  39
code/pflueger_1_1/B.cpp.tk                          |  33
code/pflueger_2_1/C.cpp.tk                          |  57
code/ponyopoppo_0_1/A.cpp.tk                        |  14
code/ponyopoppo_1_1/B.cpp.tk                        |  22
code/ponyopoppo_2_1/C.cpp.tk                        |  92
code/Ragnar_0_1/A.cpp.tk                            |  27
code/Ragnar_1_1/B-2.cpp.tk                          |  32
code/Ragnar_2_1/C.cpp.tk                            |  51
code/saffah_0_1/t.cpp.tk                            |  8
code/saffah_1_1/t.cpp.tk                            |  11
code/saffah_2_1/t.cpp.tk                            |  63
code/SamanSami_0_1/A.cpp.tk                         |  10
code/SamanSami_1_1/B.cpp.tk                         |  33
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  23
code/Savlik_1_1/code.cpp.tk                         |  11
code/Savlik_2_1/code.cpp.tk                         |  53
code/shik_0_1/pa.cpp.tk                             |  59
code/shik_1_1/pb.cpp.tk                             |  61
code/shik_2_1/pc.cpp.tk                             |  81
code/simsa.st_0_1/A.cpp.tk                          |  22
code/simsa.st_1_1/B.cpp.tk                          |  11
code/simsa.st_2_1/C.cpp.tk                          |  58
code/SovietUnion_0_1/A.cpp.tk                       |  49
code/SovietUnion_1_1/B.cpp.tk                       |  71
code/SovietUnion_2_1/C.cpp.tk                       |  69
code/tailed_0_1/A.cpp.tk                            |  39
code/tailed_1_1/B.cpp.tk                            |  27
code/tailed_2_1/C.cpp.tk                            |  31
code/TheNatural_0_1/A.cpp.tk                        |  34
code/TheNatural_1_1/B.cpp.tk                        |  35
code/TheNatural_2_1/C.cpp.tk                        |  27
code/TrueBamboo_0_1/test.cpp.tk                     |  16
code/TrueBamboo_1_1/test.cpp.tk                     |  20
code/TrueBamboo_2_1/test.cpp.tk                     |  37
code/tur.turczyn_0_1/A.cpp.tk                       |  28
code/tur.turczyn_1_1/B.cpp.tk                       |  32
code/tur.turczyn_2_1/C.cpp.tk                       |  35
code/Tyg3R_0_1/A.cpp.tk                             |  13
code/Tyg3R_1_1/B.cpp.tk                             |  13
code/Tyg3R_2_1/C.cpp.tk                             |  22
code/UminchuR_0_1/main.cpp.tk                       |  40
code/UminchuR_1_1/main.cpp.tk                       |  36
code/UminchuR_2_1/main.cpp.tk                       |  54
code/wo..._0_1/a.cpp.tk                             |  26
code/wo..._1_1/b.cpp.tk                             |  29
code/wo..._2_1/c.cpp.tk                             |  60
code/yswtt_0_1/A.cpp.tk                             |  43
code/yswtt_1_1/B.cpp.tk                             |  41
code/yswtt_2_1/C.cpp.tk                             |  61
code/ZhSh_0_1/a.cpp.tk                              |  64
code/ZhSh_1_1/b.cpp.tk                              |  95
code/ZhSh_2_1/c.cpp.tk                              |  99
