Begin
Comparing:  code/DEGwer_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  25
code/551100kk_1_1/B.cpp.tk                          |  38
code/551100kk_2_1/C.cpp.tk                          |  47
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  19
code/achan1058_2_1/source.cpp.tk                    |  38
code/alanubi_0_1/a.cpp.tk                           |  59
code/alanubi_1_1/b.cpp.tk                           |  87
code/alanubi_2_1/c.cpp.tk                           |  146
code/AntiForest_0_1/q1.cpp.tk                       |  22
code/AntiForest_1_1/q2.cpp.tk                       |  12
code/AntiForest_2_1/q3.cpp.tk                       |  53
code/apiad_0_1/A.cpp.tk                             |  18
code/apiad_1_1/B.cpp.tk                             |  25
code/apiad_2_1/C.cpp.tk                             |  31
code/azaky_0_1/A.cpp.tk                             |  22
code/azaky_1_1/B.cpp.tk                             |  31
code/azaky_2_1/C.cpp.tk                             |  52
code/azariamuh_0_1/standing.cpp.tk                  |  21
code/azariamuh_1_1/pancake.cpp.tk                   |  33
code/azariamuh_2_1/dijkstra.cpp.tk                  |  22
code/bmerry_0_1/a.cpp.tk                            |  74
code/bmerry_1_1/b.cpp.tk                            |  82
code/bmerry_2_1/c.cpp.tk                            |  71
code/climpet_0_1/A.cpp.tk                           |  37
code/climpet_1_1/B.cpp.tk                           |  44
code/climpet_2_1/C.cpp.tk                           |  65
code/ctzsm_0_1/A.cpp.tk                             |  39
code/ctzsm_1_1/B.cpp.tk                             |  62
code/ctzsm_2_1/C.cpp.tk                             |  97
code/DanilC_0_1/problem.cpp.tk                      |  46
code/DanilC_1_1/problemB.cpp.tk                     |  66
code/DanilC_2_1/problemC.cpp.tk                     |  90
code/DEGwer_0_1/A.cpp.tk                            |  11701
code/DEGwer_1_1/B.cpp.tk                            |  1042
code/DEGwer_2_1/C.cpp.tk                            |  349
code/dmute_0_1/a.cpp.tk                             |  48
code/dmute_1_1/b.cpp.tk                             |  77
code/dmute_2_1/c2.cpp.tk                            |  95
code/fagu_0_1/A.cpp.tk                              |  38
code/fagu_1_1/B.cpp.tk                              |  38
code/fagu_2_1/C.cpp.tk                              |  58
code/FatalEagle_0_1/main.cpp.tk                     |  108
code/FatalEagle_1_1/main.cpp.tk                     |  99
code/FatalEagle_2_1/main.cpp.tk                     |  262
code/fullpower_0_1/A.cpp.tk                         |  74
code/fullpower_1_1/B.cpp.tk                         |  115
code/fullpower_2_1/C.cpp.tk                         |  141
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  24
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  39
code/ICastro_2_1/Dijkstra.cpp.tk                    |  85
code/ilackthatsuperpower_0_1/a.cpp.tk               |  94
code/ilackthatsuperpower_1_1/b.cpp.tk               |  91
code/ilackthatsuperpower_2_1/c.cpp.tk               |  101
code/iridescent_0_1/A.cpp.tk                        |  31
code/iridescent_1_1/B.cpp.tk                        |  64
code/iridescent_2_1/C.cpp.tk                        |  56
code/ishraq_0_1/main.cpp.tk                         |  16
code/ishraq_1_1/main.cpp.tk                         |  35
code/ishraq_2_1/main.cpp.tk                         |  56
code/JayXon_0_1/A.cpp.tk                            |  25
code/JayXon_1_1/B.cpp.tk                            |  58
code/JayXon_2_1/C.cpp.tk                            |  25
code/Josse_0_1/A.cpp.tk                             |  36
code/Josse_1_1/B.cpp.tk                             |  61
code/Josse_2_1/C.cpp.tk                             |  111
code/kcm1700_0_1/a.cpp.tk                           |  60
code/kcm1700_1_1/b.cpp.tk                           |  89
code/kcm1700_2_1/c.cpp.tk                           |  102
code/kevinsogo_0_1/a.cpp.tk                         |  17
code/kevinsogo_1_1/b.cpp.tk                         |  23
code/kevinsogo_2_1/c.cpp.tk                         |  50
code/ksun48_0_1/A.cpp.tk                            |  7
code/ksun48_1_1/B.cpp.tk                            |  7
code/ksun48_2_1/C.cpp.tk                            |  14
code/LazyAnna_0_1/1.cpp.tk                          |  24
code/LazyAnna_1_1/2-1.cpp.tk                        |  39
code/LazyAnna_2_1/3.cpp.tk                          |  28
code/Merkurev_0_1/A.cpp.tk                          |  79
code/Merkurev_1_1/B.cpp.tk                          |  104
code/Merkurev_2_1/C.cpp.tk                          |  94
code/mezei_0_1/main.cpp.tk                          |  174
code/mezei_1_1/main.cpp.tk                          |  137
code/mezei_2_1/main.cpp.tk                          |  204
code/Mister_0_1/a.cpp.tk                            |  32
code/Mister_1_1/b.cpp.tk                            |  55
code/Mister_2_1/c.cpp.tk                            |  56
code/namonakiacc_0_1/cpp.cpp.tk                     |  28
code/namonakiacc_1_1/cpp.cpp.tk                     |  32
code/namonakiacc_2_1/cpp.cpp.tk                     |  50
code/Nicolas16_0_1/main.cpp.tk                      |  27
code/Nicolas16_1_1/main.cpp.tk                      |  27
code/Nicolas16_2_1/main.cpp.tk                      |  133
code/pandamonium_0_1/a.cpp.tk                       |  51
code/pandamonium_1_1/b.cpp.tk                       |  103
code/pandamonium_2_1/c.cpp.tk                       |  57
code/pflueger_0_1/A.cpp.tk                          |  41
code/pflueger_1_1/B.cpp.tk                          |  58
code/pflueger_2_1/C.cpp.tk                          |  92
code/ponyopoppo_0_1/A.cpp.tk                        |  10
code/ponyopoppo_1_1/B.cpp.tk                        |  17
code/ponyopoppo_2_1/C.cpp.tk                        |  80
code/Ragnar_0_1/A.cpp.tk                            |  14
code/Ragnar_1_1/B-2.cpp.tk                          |  32
code/Ragnar_2_1/C.cpp.tk                            |  39
code/saffah_0_1/t.cpp.tk                            |  15
code/saffah_1_1/t.cpp.tk                            |  22
code/saffah_2_1/t.cpp.tk                            |  57
code/SamanSami_0_1/A.cpp.tk                         |  17
code/SamanSami_1_1/B.cpp.tk                         |  59
code/SamanSami_2_1/C.cpp.tk                         |  7
code/Savlik_0_1/code.cpp.tk                         |  28
code/Savlik_1_1/code.cpp.tk                         |  11
code/Savlik_2_1/code.cpp.tk                         |  46
code/shik_0_1/pa.cpp.tk                             |  44
code/shik_1_1/pb.cpp.tk                             |  45
code/shik_2_1/pc.cpp.tk                             |  71
code/simsa.st_0_1/A.cpp.tk                          |  18
code/simsa.st_1_1/B.cpp.tk                          |  22
code/simsa.st_2_1/C.cpp.tk                          |  58
code/SovietUnion_0_1/A.cpp.tk                       |  48
code/SovietUnion_1_1/B.cpp.tk                       |  60
code/SovietUnion_2_1/C.cpp.tk                       |  54
code/tailed_0_1/A.cpp.tk                            |  21
code/tailed_1_1/B.cpp.tk                            |  35
code/tailed_2_1/C.cpp.tk                            |  29
code/TheNatural_0_1/A.cpp.tk                        |  66
code/TheNatural_1_1/B.cpp.tk                        |  72
code/TheNatural_2_1/C.cpp.tk                        |  33
code/TrueBamboo_0_1/test.cpp.tk                     |  30
code/TrueBamboo_1_1/test.cpp.tk                     |  38
code/TrueBamboo_2_1/test.cpp.tk                     |  50
code/tur.turczyn_0_1/A.cpp.tk                       |  11
code/tur.turczyn_1_1/B.cpp.tk                       |  17
code/tur.turczyn_2_1/C.cpp.tk                       |  20
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  16
code/Tyg3R_2_1/C.cpp.tk                             |  17
code/UminchuR_0_1/main.cpp.tk                       |  24
code/UminchuR_1_1/main.cpp.tk                       |  36
code/UminchuR_2_1/main.cpp.tk                       |  52
code/wo..._0_1/a.cpp.tk                             |  103
code/wo..._1_1/b.cpp.tk                             |  87
code/wo..._2_1/c.cpp.tk                             |  114
code/yswtt_0_1/A.cpp.tk                             |  23
code/yswtt_1_1/B.cpp.tk                             |  37
code/yswtt_2_1/C.cpp.tk                             |  40
code/ZhSh_0_1/a.cpp.tk                              |  25
code/ZhSh_1_1/b.cpp.tk                              |  67
code/ZhSh_2_1/c.cpp.tk                              |  60
