Begin
Comparing:  code/achan1058_1_1/source.cpp.tk
code/00/test.cpp.tk                                 |  23
code/01/test.cpp.tk                                 |  23
code/551100kk_0_1/A.cpp.tk                          |  21
code/551100kk_1_1/B.cpp.tk                          |  40
code/551100kk_2_1/C.cpp.tk                          |  63
code/achan1058_0_1/Q-A.cpp.tk                       |  39
code/achan1058_1_1/source.cpp.tk                    |  17454
code/achan1058_2_1/source.cpp.tk                    |  2344
code/alanubi_0_1/a.cpp.tk                           |  21
code/alanubi_1_1/b.cpp.tk                           |  34
code/alanubi_2_1/c.cpp.tk                           |  152
code/AntiForest_0_1/q1.cpp.tk                       |  43
code/AntiForest_1_1/q2.cpp.tk                       |  23
code/AntiForest_2_1/q3.cpp.tk                       |  106
code/apiad_0_1/A.cpp.tk                             |  46
code/apiad_1_1/B.cpp.tk                             |  68
code/apiad_2_1/C.cpp.tk                             |  64
code/azaky_0_1/A.cpp.tk                             |  52
code/azaky_1_1/B.cpp.tk                             |  60
code/azaky_2_1/C.cpp.tk                             |  118
code/azariamuh_0_1/standing.cpp.tk                  |  33
code/azariamuh_1_1/pancake.cpp.tk                   |  67
code/azariamuh_2_1/dijkstra.cpp.tk                  |  41
code/bmerry_0_1/a.cpp.tk                            |  133
code/bmerry_1_1/b.cpp.tk                            |  169
code/bmerry_2_1/c.cpp.tk                            |  148
code/climpet_0_1/A.cpp.tk                           |  85
code/climpet_1_1/B.cpp.tk                           |  98
code/climpet_2_1/C.cpp.tk                           |  125
code/ctzsm_0_1/A.cpp.tk                             |  22
code/ctzsm_1_1/B.cpp.tk                             |  50
code/ctzsm_2_1/C.cpp.tk                             |  115
code/DanilC_0_1/problem.cpp.tk                      |  54
code/DanilC_1_1/problemB.cpp.tk                     |  78
code/DanilC_2_1/problemC.cpp.tk                     |  192
code/DEGwer_0_1/A.cpp.tk                            |  35
code/DEGwer_1_1/B.cpp.tk                            |  45
code/DEGwer_2_1/C.cpp.tk                            |  49
code/dmute_0_1/a.cpp.tk                             |  15
code/dmute_1_1/b.cpp.tk                             |  28
code/dmute_2_1/c2.cpp.tk                            |  65
code/fagu_0_1/A.cpp.tk                              |  59
code/fagu_1_1/B.cpp.tk                              |  59
code/fagu_2_1/C.cpp.tk                              |  108
code/FatalEagle_0_1/main.cpp.tk                     |  21
code/FatalEagle_1_1/main.cpp.tk                     |  36
code/FatalEagle_2_1/main.cpp.tk                     |  215
code/fullpower_0_1/A.cpp.tk                         |  34
code/fullpower_1_1/B.cpp.tk                         |  45
code/fullpower_2_1/C.cpp.tk                         |  106
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  22
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  36
code/ICastro_2_1/Dijkstra.cpp.tk                    |  172
code/ilackthatsuperpower_0_1/a.cpp.tk               |  154
code/ilackthatsuperpower_1_1/b.cpp.tk               |  161
code/ilackthatsuperpower_2_1/c.cpp.tk               |  208
code/iridescent_0_1/A.cpp.tk                        |  19
code/iridescent_1_1/B.cpp.tk                        |  43
code/iridescent_2_1/C.cpp.tk                        |  34
code/ishraq_0_1/main.cpp.tk                         |  23
code/ishraq_1_1/main.cpp.tk                         |  76
code/ishraq_2_1/main.cpp.tk                         |  126
code/JayXon_0_1/A.cpp.tk                            |  13
code/JayXon_1_1/B.cpp.tk                            |  41
code/JayXon_2_1/C.cpp.tk                            |  58
code/Josse_0_1/A.cpp.tk                             |  27
code/Josse_1_1/B.cpp.tk                             |  36
code/Josse_2_1/C.cpp.tk                             |  140
code/kcm1700_0_1/a.cpp.tk                           |  17
code/kcm1700_1_1/b.cpp.tk                           |  43
code/kcm1700_2_1/c.cpp.tk                           |  95
code/kevinsogo_0_1/a.cpp.tk                         |  30
code/kevinsogo_1_1/b.cpp.tk                         |  36
code/kevinsogo_2_1/c.cpp.tk                         |  101
code/ksun48_0_1/A.cpp.tk                            |  8
code/ksun48_1_1/B.cpp.tk                            |  8
code/ksun48_2_1/C.cpp.tk                            |  22
code/LazyAnna_0_1/1.cpp.tk                          |  17
code/LazyAnna_1_1/2-1.cpp.tk                        |  30
code/LazyAnna_2_1/3.cpp.tk                          |  59
code/Merkurev_0_1/A.cpp.tk                          |  27
code/Merkurev_1_1/B.cpp.tk                          |  54
code/Merkurev_2_1/C.cpp.tk                          |  55
code/mezei_0_1/main.cpp.tk                          |  28
code/mezei_1_1/main.cpp.tk                          |  27
code/mezei_2_1/main.cpp.tk                          |  87
code/Mister_0_1/a.cpp.tk                            |  19
code/Mister_1_1/b.cpp.tk                            |  26
code/Mister_2_1/c.cpp.tk                            |  43
code/namonakiacc_0_1/cpp.cpp.tk                     |  177
code/namonakiacc_1_1/cpp.cpp.tk                     |  189
code/namonakiacc_2_1/cpp.cpp.tk                     |  220
code/Nicolas16_0_1/main.cpp.tk                      |  11
code/Nicolas16_1_1/main.cpp.tk                      |  11
code/Nicolas16_2_1/main.cpp.tk                      |  86
code/pandamonium_0_1/a.cpp.tk                       |  17
code/pandamonium_1_1/b.cpp.tk                       |  55
code/pandamonium_2_1/c.cpp.tk                       |  32
code/pflueger_0_1/A.cpp.tk                          |  22
code/pflueger_1_1/B.cpp.tk                          |  34
code/pflueger_2_1/C.cpp.tk                          |  86
code/ponyopoppo_0_1/A.cpp.tk                        |  33
code/ponyopoppo_1_1/B.cpp.tk                        |  65
code/ponyopoppo_2_1/C.cpp.tk                        |  208
code/Ragnar_0_1/A.cpp.tk                            |  169
code/Ragnar_1_1/B-2.cpp.tk                          |  207
code/Ragnar_2_1/C.cpp.tk                            |  206
code/saffah_0_1/t.cpp.tk                            |  26
code/saffah_1_1/t.cpp.tk                            |  42
code/saffah_2_1/t.cpp.tk                            |  137
code/SamanSami_0_1/A.cpp.tk                         |  8
code/SamanSami_1_1/B.cpp.tk                         |  34
code/SamanSami_2_1/C.cpp.tk                         |  19
code/Savlik_0_1/code.cpp.tk                         |  22
code/Savlik_1_1/code.cpp.tk                         |  31
code/Savlik_2_1/code.cpp.tk                         |  112
code/shik_0_1/pa.cpp.tk                             |  122
code/shik_1_1/pb.cpp.tk                             |  126
code/shik_2_1/pc.cpp.tk                             |  174
code/simsa.st_0_1/A.cpp.tk                          |  25
code/simsa.st_1_1/B.cpp.tk                          |  37
code/simsa.st_2_1/C.cpp.tk                          |  129
code/SovietUnion_0_1/A.cpp.tk                       |  24
code/SovietUnion_1_1/B.cpp.tk                       |  30
code/SovietUnion_2_1/C.cpp.tk                       |  108
code/tailed_0_1/A.cpp.tk                            |  24
code/tailed_1_1/B.cpp.tk                            |  56
code/tailed_2_1/C.cpp.tk                            |  66
code/TheNatural_0_1/A.cpp.tk                        |  23
code/TheNatural_1_1/B.cpp.tk                        |  30
code/TheNatural_2_1/C.cpp.tk                        |  38
code/TrueBamboo_0_1/test.cpp.tk                     |  27
code/TrueBamboo_1_1/test.cpp.tk                     |  56
code/TrueBamboo_2_1/test.cpp.tk                     |  74
code/tur.turczyn_0_1/A.cpp.tk                       |  152
code/tur.turczyn_1_1/B.cpp.tk                       |  184
code/tur.turczyn_2_1/C.cpp.tk                       |  176
code/Tyg3R_0_1/A.cpp.tk                             |  31
code/Tyg3R_1_1/B.cpp.tk                             |  50
code/Tyg3R_2_1/C.cpp.tk                             |  48
code/UminchuR_0_1/main.cpp.tk                       |  149
code/UminchuR_1_1/main.cpp.tk                       |  173
code/UminchuR_2_1/main.cpp.tk                       |  201
code/wo..._0_1/a.cpp.tk                             |  23
code/wo..._1_1/b.cpp.tk                             |  30
code/wo..._2_1/c.cpp.tk                             |  85
code/yswtt_0_1/A.cpp.tk                             |  18
code/yswtt_1_1/B.cpp.tk                             |  36
code/yswtt_2_1/C.cpp.tk                             |  57
code/ZhSh_0_1/a.cpp.tk                              |  21
code/ZhSh_1_1/b.cpp.tk                              |  158
code/ZhSh_2_1/c.cpp.tk                              |  169
