Begin
Comparing:  code/alanubi_0_1/a.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  28
code/551100kk_1_1/B.cpp.tk                          |  42
code/551100kk_2_1/C.cpp.tk                          |  47
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  16
code/achan1058_2_1/source.cpp.tk                    |  32
code/alanubi_0_1/a.cpp.tk                           |  5998
code/alanubi_1_1/b.cpp.tk                           |  308
code/alanubi_2_1/c.cpp.tk                           |  239
code/AntiForest_0_1/q1.cpp.tk                       |  27
code/AntiForest_1_1/q2.cpp.tk                       |  9
code/AntiForest_2_1/q3.cpp.tk                       |  45
code/apiad_0_1/A.cpp.tk                             |  21
code/apiad_1_1/B.cpp.tk                             |  19
code/apiad_2_1/C.cpp.tk                             |  24
code/azaky_0_1/A.cpp.tk                             |  25
code/azaky_1_1/B.cpp.tk                             |  24
code/azaky_2_1/C.cpp.tk                             |  43
code/azariamuh_0_1/standing.cpp.tk                  |  20
code/azariamuh_1_1/pancake.cpp.tk                   |  22
code/azariamuh_2_1/dijkstra.cpp.tk                  |  19
code/bmerry_0_1/a.cpp.tk                            |  87
code/bmerry_1_1/b.cpp.tk                            |  76
code/bmerry_2_1/c.cpp.tk                            |  67
code/climpet_0_1/A.cpp.tk                           |  54
code/climpet_1_1/B.cpp.tk                           |  43
code/climpet_2_1/C.cpp.tk                           |  64
code/ctzsm_0_1/A.cpp.tk                             |  66
code/ctzsm_1_1/B.cpp.tk                             |  69
code/ctzsm_2_1/C.cpp.tk                             |  96
code/DanilC_0_1/problem.cpp.tk                      |  56
code/DanilC_1_1/problemB.cpp.tk                     |  64
code/DanilC_2_1/problemC.cpp.tk                     |  73
code/DEGwer_0_1/A.cpp.tk                            |  85
code/DEGwer_1_1/B.cpp.tk                            |  85
code/DEGwer_2_1/C.cpp.tk                            |  65
code/dmute_0_1/a.cpp.tk                             |  60
code/dmute_1_1/b.cpp.tk                             |  114
code/dmute_2_1/c2.cpp.tk                            |  113
code/fagu_0_1/A.cpp.tk                              |  47
code/fagu_1_1/B.cpp.tk                              |  47
code/fagu_2_1/C.cpp.tk                              |  65
code/FatalEagle_0_1/main.cpp.tk                     |  81
code/FatalEagle_1_1/main.cpp.tk                     |  136
code/FatalEagle_2_1/main.cpp.tk                     |  270
code/fullpower_0_1/A.cpp.tk                         |  78
code/fullpower_1_1/B.cpp.tk                         |  132
code/fullpower_2_1/C.cpp.tk                         |  155
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  42
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  40
code/ICastro_2_1/Dijkstra.cpp.tk                    |  84
code/ilackthatsuperpower_0_1/a.cpp.tk               |  96
code/ilackthatsuperpower_1_1/b.cpp.tk               |  94
code/ilackthatsuperpower_2_1/c.cpp.tk               |  86
code/iridescent_0_1/A.cpp.tk                        |  38
code/iridescent_1_1/B.cpp.tk                        |  81
code/iridescent_2_1/C.cpp.tk                        |  71
code/ishraq_0_1/main.cpp.tk                         |  35
code/ishraq_1_1/main.cpp.tk                         |  48
code/ishraq_2_1/main.cpp.tk                         |  59
code/JayXon_0_1/A.cpp.tk                            |  25
code/JayXon_1_1/B.cpp.tk                            |  63
code/JayXon_2_1/C.cpp.tk                            |  20
code/Josse_0_1/A.cpp.tk                             |  62
code/Josse_1_1/B.cpp.tk                             |  79
code/Josse_2_1/C.cpp.tk                             |  124
code/kcm1700_0_1/a.cpp.tk                           |  136
code/kcm1700_1_1/b.cpp.tk                           |  170
code/kcm1700_2_1/c.cpp.tk                           |  141
code/kevinsogo_0_1/a.cpp.tk                         |  34
code/kevinsogo_1_1/b.cpp.tk                         |  37
code/kevinsogo_2_1/c.cpp.tk                         |  43
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  9
code/LazyAnna_0_1/1.cpp.tk                          |  41
code/LazyAnna_1_1/2-1.cpp.tk                        |  42
code/LazyAnna_2_1/3.cpp.tk                          |  29
code/Merkurev_0_1/A.cpp.tk                          |  137
code/Merkurev_1_1/B.cpp.tk                          |  132
code/Merkurev_2_1/C.cpp.tk                          |  112
code/mezei_0_1/main.cpp.tk                          |  109
code/mezei_1_1/main.cpp.tk                          |  82
code/mezei_2_1/main.cpp.tk                          |  146
code/Mister_0_1/a.cpp.tk                            |  67
code/Mister_1_1/b.cpp.tk                            |  87
code/Mister_2_1/c.cpp.tk                            |  66
code/namonakiacc_0_1/cpp.cpp.tk                     |  24
code/namonakiacc_1_1/cpp.cpp.tk                     |  23
code/namonakiacc_2_1/cpp.cpp.tk                     |  37
code/Nicolas16_0_1/main.cpp.tk                      |  36
code/Nicolas16_1_1/main.cpp.tk                      |  33
code/Nicolas16_2_1/main.cpp.tk                      |  148
code/pandamonium_0_1/a.cpp.tk                       |  120
code/pandamonium_1_1/b.cpp.tk                       |  135
code/pandamonium_2_1/c.cpp.tk                       |  69
code/pflueger_0_1/A.cpp.tk                          |  76
code/pflueger_1_1/B.cpp.tk                          |  74
code/pflueger_2_1/C.cpp.tk                          |  95
code/ponyopoppo_0_1/A.cpp.tk                        |  12
code/ponyopoppo_1_1/B.cpp.tk                        |  14
code/ponyopoppo_2_1/C.cpp.tk                        |  57
code/Ragnar_0_1/A.cpp.tk                            |  13
code/Ragnar_1_1/B-2.cpp.tk                          |  28
code/Ragnar_2_1/C.cpp.tk                            |  39
code/saffah_0_1/t.cpp.tk                            |  30
code/saffah_1_1/t.cpp.tk                            |  29
code/saffah_2_1/t.cpp.tk                            |  52
code/SamanSami_0_1/A.cpp.tk                         |  18
code/SamanSami_1_1/B.cpp.tk                         |  74
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  71
code/Savlik_1_1/code.cpp.tk                         |  7
code/Savlik_2_1/code.cpp.tk                         |  36
code/shik_0_1/pa.cpp.tk                             |  40
code/shik_1_1/pb.cpp.tk                             |  39
code/shik_2_1/pc.cpp.tk                             |  60
code/simsa.st_0_1/A.cpp.tk                          |  20
code/simsa.st_1_1/B.cpp.tk                          |  27
code/simsa.st_2_1/C.cpp.tk                          |  56
code/SovietUnion_0_1/A.cpp.tk                       |  57
code/SovietUnion_1_1/B.cpp.tk                       |  67
code/SovietUnion_2_1/C.cpp.tk                       |  40
code/tailed_0_1/A.cpp.tk                            |  38
code/tailed_1_1/B.cpp.tk                            |  44
code/tailed_2_1/C.cpp.tk                            |  29
code/TheNatural_0_1/A.cpp.tk                        |  85
code/TheNatural_1_1/B.cpp.tk                        |  95
code/TheNatural_2_1/C.cpp.tk                        |  41
code/TrueBamboo_0_1/test.cpp.tk                     |  31
code/TrueBamboo_1_1/test.cpp.tk                     |  33
code/TrueBamboo_2_1/test.cpp.tk                     |  42
code/tur.turczyn_0_1/A.cpp.tk                       |  13
code/tur.turczyn_1_1/B.cpp.tk                       |  17
code/tur.turczyn_2_1/C.cpp.tk                       |  20
code/Tyg3R_0_1/A.cpp.tk                             |  16
code/Tyg3R_1_1/B.cpp.tk                             |  13
code/Tyg3R_2_1/C.cpp.tk                             |  25
code/UminchuR_0_1/main.cpp.tk                       |  33
code/UminchuR_1_1/main.cpp.tk                       |  39
code/UminchuR_2_1/main.cpp.tk                       |  50
code/wo..._0_1/a.cpp.tk                             |  154
code/wo..._1_1/b.cpp.tk                             |  133
code/wo..._2_1/c.cpp.tk                             |  158
code/yswtt_0_1/A.cpp.tk                             |  27
code/yswtt_1_1/B.cpp.tk                             |  36
code/yswtt_2_1/C.cpp.tk                             |  50
code/ZhSh_0_1/a.cpp.tk                              |  50
code/ZhSh_1_1/b.cpp.tk                              |  70
code/ZhSh_2_1/c.cpp.tk                              |  59
