Begin
Comparing:  code/ishraq_1_1/main.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  21
code/551100kk_1_1/B.cpp.tk                          |  44
code/551100kk_2_1/C.cpp.tk                          |  48
code/achan1058_0_1/Q-A.cpp.tk                       |  15
code/achan1058_1_1/source.cpp.tk                    |  77
code/achan1058_2_1/source.cpp.tk                    |  51
code/alanubi_0_1/a.cpp.tk                           |  48
code/alanubi_1_1/b.cpp.tk                           |  71
code/alanubi_2_1/c.cpp.tk                           |  111
code/AntiForest_0_1/q1.cpp.tk                       |  42
code/AntiForest_1_1/q2.cpp.tk                       |  22
code/AntiForest_2_1/q3.cpp.tk                       |  77
code/apiad_0_1/A.cpp.tk                             |  23
code/apiad_1_1/B.cpp.tk                             |  43
code/apiad_2_1/C.cpp.tk                             |  33
code/azaky_0_1/A.cpp.tk                             |  32
code/azaky_1_1/B.cpp.tk                             |  45
code/azaky_2_1/C.cpp.tk                             |  67
code/azariamuh_0_1/standing.cpp.tk                  |  31
code/azariamuh_1_1/pancake.cpp.tk                   |  68
code/azariamuh_2_1/dijkstra.cpp.tk                  |  32
code/bmerry_0_1/a.cpp.tk                            |  50
code/bmerry_1_1/b.cpp.tk                            |  68
code/bmerry_2_1/c.cpp.tk                            |  60
code/climpet_0_1/A.cpp.tk                           |  36
code/climpet_1_1/B.cpp.tk                           |  38
code/climpet_2_1/C.cpp.tk                           |  65
code/ctzsm_0_1/A.cpp.tk                             |  34
code/ctzsm_1_1/B.cpp.tk                             |  69
code/ctzsm_2_1/C.cpp.tk                             |  94
code/DanilC_0_1/problem.cpp.tk                      |  42
code/DanilC_1_1/problemB.cpp.tk                     |  59
code/DanilC_2_1/problemC.cpp.tk                     |  97
code/DEGwer_0_1/A.cpp.tk                            |  53
code/DEGwer_1_1/B.cpp.tk                            |  118
code/DEGwer_2_1/C.cpp.tk                            |  42
code/dmute_0_1/a.cpp.tk                             |  26
code/dmute_1_1/b.cpp.tk                             |  82
code/dmute_2_1/c2.cpp.tk                            |  73
code/fagu_0_1/A.cpp.tk                              |  15
code/fagu_1_1/B.cpp.tk                              |  15
code/fagu_2_1/C.cpp.tk                              |  46
code/FatalEagle_0_1/main.cpp.tk                     |  40
code/FatalEagle_1_1/main.cpp.tk                     |  80
code/FatalEagle_2_1/main.cpp.tk                     |  206
code/fullpower_0_1/A.cpp.tk                         |  43
code/fullpower_1_1/B.cpp.tk                         |  83
code/fullpower_2_1/C.cpp.tk                         |  113
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  20
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  39
code/ICastro_2_1/Dijkstra.cpp.tk                    |  106
code/ilackthatsuperpower_0_1/a.cpp.tk               |  87
code/ilackthatsuperpower_1_1/b.cpp.tk               |  81
code/ilackthatsuperpower_2_1/c.cpp.tk               |  101
code/iridescent_0_1/A.cpp.tk                        |  24
code/iridescent_1_1/B.cpp.tk                        |  119
code/iridescent_2_1/C.cpp.tk                        |  38
code/ishraq_0_1/main.cpp.tk                         |  116
code/ishraq_1_1/main.cpp.tk                         |  4992
code/ishraq_2_1/main.cpp.tk                         |  162
code/JayXon_0_1/A.cpp.tk                            |  11
code/JayXon_1_1/B.cpp.tk                            |  34
code/JayXon_2_1/C.cpp.tk                            |  30
code/Josse_0_1/A.cpp.tk                             |  27
code/Josse_1_1/B.cpp.tk                             |  65
code/Josse_2_1/C.cpp.tk                             |  82
code/kcm1700_0_1/a.cpp.tk                           |  53
code/kcm1700_1_1/b.cpp.tk                           |  89
code/kcm1700_2_1/c.cpp.tk                           |  113
code/kevinsogo_0_1/a.cpp.tk                         |  47
code/kevinsogo_1_1/b.cpp.tk                         |  53
code/kevinsogo_2_1/c.cpp.tk                         |  70
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  23
code/LazyAnna_1_1/2-1.cpp.tk                        |  36
code/LazyAnna_2_1/3.cpp.tk                          |  33
code/Merkurev_0_1/A.cpp.tk                          |  61
code/Merkurev_1_1/B.cpp.tk                          |  70
code/Merkurev_2_1/C.cpp.tk                          |  68
code/mezei_0_1/main.cpp.tk                          |  47
code/mezei_1_1/main.cpp.tk                          |  64
code/mezei_2_1/main.cpp.tk                          |  76
code/Mister_0_1/a.cpp.tk                            |  41
code/Mister_1_1/b.cpp.tk                            |  61
code/Mister_2_1/c.cpp.tk                            |  52
code/namonakiacc_0_1/cpp.cpp.tk                     |  51
code/namonakiacc_1_1/cpp.cpp.tk                     |  62
code/namonakiacc_2_1/cpp.cpp.tk                     |  71
code/Nicolas16_0_1/main.cpp.tk                      |  21
code/Nicolas16_1_1/main.cpp.tk                      |  19
code/Nicolas16_2_1/main.cpp.tk                      |  88
code/pandamonium_0_1/a.cpp.tk                       |  28
code/pandamonium_1_1/b.cpp.tk                       |  65
code/pandamonium_2_1/c.cpp.tk                       |  49
code/pflueger_0_1/A.cpp.tk                          |  26
code/pflueger_1_1/B.cpp.tk                          |  67
code/pflueger_2_1/C.cpp.tk                          |  65
code/ponyopoppo_0_1/A.cpp.tk                        |  15
code/ponyopoppo_1_1/B.cpp.tk                        |  31
code/ponyopoppo_2_1/C.cpp.tk                        |  96
code/Ragnar_0_1/A.cpp.tk                            |  16
code/Ragnar_1_1/B-2.cpp.tk                          |  43
code/Ragnar_2_1/C.cpp.tk                            |  37
code/saffah_0_1/t.cpp.tk                            |  56
code/saffah_1_1/t.cpp.tk                            |  71
code/saffah_2_1/t.cpp.tk                            |  86
code/SamanSami_0_1/A.cpp.tk                         |  8
code/SamanSami_1_1/B.cpp.tk                         |  105
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  19
code/Savlik_1_1/code.cpp.tk                         |  17
code/Savlik_2_1/code.cpp.tk                         |  59
code/shik_0_1/pa.cpp.tk                             |  64
code/shik_1_1/pb.cpp.tk                             |  60
code/shik_2_1/pc.cpp.tk                             |  94
code/simsa.st_0_1/A.cpp.tk                          |  28
code/simsa.st_1_1/B.cpp.tk                          |  60
code/simsa.st_2_1/C.cpp.tk                          |  93
code/SovietUnion_0_1/A.cpp.tk                       |  38
code/SovietUnion_1_1/B.cpp.tk                       |  55
code/SovietUnion_2_1/C.cpp.tk                       |  55
code/tailed_0_1/A.cpp.tk                            |  16
code/tailed_1_1/B.cpp.tk                            |  99
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  28
code/TheNatural_1_1/B.cpp.tk                        |  49
code/TheNatural_2_1/C.cpp.tk                        |  22
code/TrueBamboo_0_1/test.cpp.tk                     |  19
code/TrueBamboo_1_1/test.cpp.tk                     |  44
code/TrueBamboo_2_1/test.cpp.tk                     |  41
code/tur.turczyn_0_1/A.cpp.tk                       |  14
code/tur.turczyn_1_1/B.cpp.tk                       |  23
code/tur.turczyn_2_1/C.cpp.tk                       |  24
code/Tyg3R_0_1/A.cpp.tk                             |  23
code/Tyg3R_1_1/B.cpp.tk                             |  34
code/Tyg3R_2_1/C.cpp.tk                             |  27
code/UminchuR_0_1/main.cpp.tk                       |  32
code/UminchuR_1_1/main.cpp.tk                       |  57
code/UminchuR_2_1/main.cpp.tk                       |  64
code/wo..._0_1/a.cpp.tk                             |  63
code/wo..._1_1/b.cpp.tk                             |  88
code/wo..._2_1/c.cpp.tk                             |  95
code/yswtt_0_1/A.cpp.tk                             |  23
code/yswtt_1_1/B.cpp.tk                             |  33
code/yswtt_2_1/C.cpp.tk                             |  42
code/ZhSh_0_1/a.cpp.tk                              |  25
code/ZhSh_1_1/b.cpp.tk                              |  86
code/ZhSh_2_1/c.cpp.tk                              |  68
