Begin
Comparing:  code/apiad_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  18
code/551100kk_1_1/B.cpp.tk                          |  32
code/551100kk_2_1/C.cpp.tk                          |  44
code/achan1058_0_1/Q-A.cpp.tk                       |  12
code/achan1058_1_1/source.cpp.tk                    |  43
code/achan1058_2_1/source.cpp.tk                    |  69
code/alanubi_0_1/a.cpp.tk                           |  15
code/alanubi_1_1/b.cpp.tk                           |  26
code/alanubi_2_1/c.cpp.tk                           |  91
code/AntiForest_0_1/q1.cpp.tk                       |  31
code/AntiForest_1_1/q2.cpp.tk                       |  20
code/AntiForest_2_1/q3.cpp.tk                       |  71
code/apiad_0_1/A.cpp.tk                             |  962
code/apiad_1_1/B.cpp.tk                             |  12067
code/apiad_2_1/C.cpp.tk                             |  847
code/azaky_0_1/A.cpp.tk                             |  37
code/azaky_1_1/B.cpp.tk                             |  47
code/azaky_2_1/C.cpp.tk                             |  82
code/azariamuh_0_1/standing.cpp.tk                  |  26
code/azariamuh_1_1/pancake.cpp.tk                   |  48
code/azariamuh_2_1/dijkstra.cpp.tk                  |  33
code/bmerry_0_1/a.cpp.tk                            |  54
code/bmerry_1_1/b.cpp.tk                            |  68
code/bmerry_2_1/c.cpp.tk                            |  63
code/climpet_0_1/A.cpp.tk                           |  34
code/climpet_1_1/B.cpp.tk                           |  43
code/climpet_2_1/C.cpp.tk                           |  57
code/ctzsm_0_1/A.cpp.tk                             |  18
code/ctzsm_1_1/B.cpp.tk                             |  34
code/ctzsm_2_1/C.cpp.tk                             |  84
code/DanilC_0_1/problem.cpp.tk                      |  28
code/DanilC_1_1/problemB.cpp.tk                     |  45
code/DanilC_2_1/problemC.cpp.tk                     |  120
code/DEGwer_0_1/A.cpp.tk                            |  28
code/DEGwer_1_1/B.cpp.tk                            |  34
code/DEGwer_2_1/C.cpp.tk                            |  36
code/dmute_0_1/a.cpp.tk                             |  13
code/dmute_1_1/b.cpp.tk                             |  19
code/dmute_2_1/c2.cpp.tk                            |  46
code/fagu_0_1/A.cpp.tk                              |  18
code/fagu_1_1/B.cpp.tk                              |  18
code/fagu_2_1/C.cpp.tk                              |  54
code/FatalEagle_0_1/main.cpp.tk                     |  20
code/FatalEagle_1_1/main.cpp.tk                     |  28
code/FatalEagle_2_1/main.cpp.tk                     |  135
code/fullpower_0_1/A.cpp.tk                         |  30
code/fullpower_1_1/B.cpp.tk                         |  33
code/fullpower_2_1/C.cpp.tk                         |  71
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  9
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  21
code/ICastro_2_1/Dijkstra.cpp.tk                    |  106
code/ilackthatsuperpower_0_1/a.cpp.tk               |  77
code/ilackthatsuperpower_1_1/b.cpp.tk               |  82
code/ilackthatsuperpower_2_1/c.cpp.tk               |  110
code/iridescent_0_1/A.cpp.tk                        |  8
code/iridescent_1_1/B.cpp.tk                        |  16
code/iridescent_2_1/C.cpp.tk                        |  17
code/ishraq_0_1/main.cpp.tk                         |  19
code/ishraq_1_1/main.cpp.tk                         |  28
code/ishraq_2_1/main.cpp.tk                         |  91
code/JayXon_0_1/A.cpp.tk                            |  8
code/JayXon_1_1/B.cpp.tk                            |  20
code/JayXon_2_1/C.cpp.tk                            |  35
code/Josse_0_1/A.cpp.tk                             |  14
code/Josse_1_1/B.cpp.tk                             |  21
code/Josse_2_1/C.cpp.tk                             |  85
code/kcm1700_0_1/a.cpp.tk                           |  13
code/kcm1700_1_1/b.cpp.tk                           |  24
code/kcm1700_2_1/c.cpp.tk                           |  60
code/kevinsogo_0_1/a.cpp.tk                         |  20
code/kevinsogo_1_1/b.cpp.tk                         |  25
code/kevinsogo_2_1/c.cpp.tk                         |  68
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  14
code/LazyAnna_0_1/1.cpp.tk                          |  7
code/LazyAnna_1_1/2-1.cpp.tk                        |  12
code/LazyAnna_2_1/3.cpp.tk                          |  37
code/Merkurev_0_1/A.cpp.tk                          |  21
code/Merkurev_1_1/B.cpp.tk                          |  43
code/Merkurev_2_1/C.cpp.tk                          |  36
code/mezei_0_1/main.cpp.tk                          |  26
code/mezei_1_1/main.cpp.tk                          |  24
code/mezei_2_1/main.cpp.tk                          |  64
code/Mister_0_1/a.cpp.tk                            |  15
code/Mister_1_1/b.cpp.tk                            |  21
code/Mister_2_1/c.cpp.tk                            |  34
code/namonakiacc_0_1/cpp.cpp.tk                     |  46
code/namonakiacc_1_1/cpp.cpp.tk                     |  57
code/namonakiacc_2_1/cpp.cpp.tk                     |  80
code/Nicolas16_0_1/main.cpp.tk                      |  9
code/Nicolas16_1_1/main.cpp.tk                      |  8
code/Nicolas16_2_1/main.cpp.tk                      |  63
code/pandamonium_0_1/a.cpp.tk                       |  14
code/pandamonium_1_1/b.cpp.tk                       |  41
code/pandamonium_2_1/c.cpp.tk                       |  24
code/pflueger_0_1/A.cpp.tk                          |  9
code/pflueger_1_1/B.cpp.tk                          |  20
code/pflueger_2_1/C.cpp.tk                          |  51
code/ponyopoppo_0_1/A.cpp.tk                        |  13
code/ponyopoppo_1_1/B.cpp.tk                        |  35
code/ponyopoppo_2_1/C.cpp.tk                        |  125
code/Ragnar_0_1/A.cpp.tk                            |  22
code/Ragnar_1_1/B-2.cpp.tk                          |  36
code/Ragnar_2_1/C.cpp.tk                            |  45
code/saffah_0_1/t.cpp.tk                            |  21
code/saffah_1_1/t.cpp.tk                            |  90
code/saffah_2_1/t.cpp.tk                            |  99
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  12
code/SamanSami_2_1/C.cpp.tk                         |  11
code/Savlik_0_1/code.cpp.tk                         |  12
code/Savlik_1_1/code.cpp.tk                         |  22
code/Savlik_2_1/code.cpp.tk                         |  71
code/shik_0_1/pa.cpp.tk                             |  78
code/shik_1_1/pb.cpp.tk                             |  84
code/shik_2_1/pc.cpp.tk                             |  108
code/simsa.st_0_1/A.cpp.tk                          |  21
code/simsa.st_1_1/B.cpp.tk                          |  40
code/simsa.st_2_1/C.cpp.tk                          |  91
code/SovietUnion_0_1/A.cpp.tk                       |  18
code/SovietUnion_1_1/B.cpp.tk                       |  27
code/SovietUnion_2_1/C.cpp.tk                       |  66
code/tailed_0_1/A.cpp.tk                            |  10
code/tailed_1_1/B.cpp.tk                            |  20
code/tailed_2_1/C.cpp.tk                            |  36
code/TheNatural_0_1/A.cpp.tk                        |  10
code/TheNatural_1_1/B.cpp.tk                        |  16
code/TheNatural_2_1/C.cpp.tk                        |  22
code/TrueBamboo_0_1/test.cpp.tk                     |  17
code/TrueBamboo_1_1/test.cpp.tk                     |  29
code/TrueBamboo_2_1/test.cpp.tk                     |  48
code/tur.turczyn_0_1/A.cpp.tk                       |  22
code/tur.turczyn_1_1/B.cpp.tk                       |  37
code/tur.turczyn_2_1/C.cpp.tk                       |  38
code/Tyg3R_0_1/A.cpp.tk                             |  16
code/Tyg3R_1_1/B.cpp.tk                             |  24
code/Tyg3R_2_1/C.cpp.tk                             |  25
code/UminchuR_0_1/main.cpp.tk                       |  33
code/UminchuR_1_1/main.cpp.tk                       |  57
code/UminchuR_2_1/main.cpp.tk                       |  69
code/wo..._0_1/a.cpp.tk                             |  18
code/wo..._1_1/b.cpp.tk                             |  29
code/wo..._2_1/c.cpp.tk                             |  59
code/yswtt_0_1/A.cpp.tk                             |  7
code/yswtt_1_1/B.cpp.tk                             |  21
code/yswtt_2_1/C.cpp.tk                             |  33
code/ZhSh_0_1/a.cpp.tk                              |  9
code/ZhSh_1_1/b.cpp.tk                              |  68
code/ZhSh_2_1/c.cpp.tk                              |  83
