Begin
Comparing:  code/achan1058_1_1/source.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  12
code/551100kk_1_1/B.cpp.tk                          |  23
code/551100kk_2_1/C.cpp.tk                          |  35
code/achan1058_0_1/Q-A.cpp.tk                       |  24
code/achan1058_1_1/source.cpp.tk                    |  11605
code/achan1058_2_1/source.cpp.tk                    |  1546
code/alanubi_0_1/a.cpp.tk                           |  12
code/alanubi_1_1/b.cpp.tk                           |  20
code/alanubi_2_1/c.cpp.tk                           |  85
code/AntiForest_0_1/q1.cpp.tk                       |  25
code/AntiForest_1_1/q2.cpp.tk                       |  14
code/AntiForest_2_1/q3.cpp.tk                       |  62
code/apiad_0_1/A.cpp.tk                             |  27
code/apiad_1_1/B.cpp.tk                             |  41
code/apiad_2_1/C.cpp.tk                             |  37
code/azaky_0_1/A.cpp.tk                             |  30
code/azaky_1_1/B.cpp.tk                             |  35
code/azaky_2_1/C.cpp.tk                             |  67
code/azariamuh_0_1/standing.cpp.tk                  |  20
code/azariamuh_1_1/pancake.cpp.tk                   |  40
code/azariamuh_2_1/dijkstra.cpp.tk                  |  23
code/bmerry_0_1/a.cpp.tk                            |  79
code/bmerry_1_1/b.cpp.tk                            |  101
code/bmerry_2_1/c.cpp.tk                            |  87
code/climpet_0_1/A.cpp.tk                           |  50
code/climpet_1_1/B.cpp.tk                           |  57
code/climpet_2_1/C.cpp.tk                           |  73
code/ctzsm_0_1/A.cpp.tk                             |  12
code/ctzsm_1_1/B.cpp.tk                             |  29
code/ctzsm_2_1/C.cpp.tk                             |  64
code/DanilC_0_1/problem.cpp.tk                      |  30
code/DanilC_1_1/problemB.cpp.tk                     |  44
code/DanilC_2_1/problemC.cpp.tk                     |  110
code/DEGwer_0_1/A.cpp.tk                            |  20
code/DEGwer_1_1/B.cpp.tk                            |  26
code/DEGwer_2_1/C.cpp.tk                            |  28
code/dmute_0_1/a.cpp.tk                             |  8
code/dmute_1_1/b.cpp.tk                             |  15
code/dmute_2_1/c2.cpp.tk                            |  36
code/fagu_0_1/A.cpp.tk                              |  37
code/fagu_1_1/B.cpp.tk                              |  37
code/fagu_2_1/C.cpp.tk                              |  65
code/FatalEagle_0_1/main.cpp.tk                     |  12
code/FatalEagle_1_1/main.cpp.tk                     |  20
code/FatalEagle_2_1/main.cpp.tk                     |  122
code/fullpower_0_1/A.cpp.tk                         |  19
code/fullpower_1_1/B.cpp.tk                         |  25
code/fullpower_2_1/C.cpp.tk                         |  59
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  12
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  20
code/ICastro_2_1/Dijkstra.cpp.tk                    |  94
code/ilackthatsuperpower_0_1/a.cpp.tk               |  88
code/ilackthatsuperpower_1_1/b.cpp.tk               |  92
code/ilackthatsuperpower_2_1/c.cpp.tk               |  118
code/iridescent_0_1/A.cpp.tk                        |  11
code/iridescent_1_1/B.cpp.tk                        |  26
code/iridescent_2_1/C.cpp.tk                        |  19
code/ishraq_0_1/main.cpp.tk                         |  13
code/ishraq_1_1/main.cpp.tk                         |  48
code/ishraq_2_1/main.cpp.tk                         |  73
code/JayXon_0_1/A.cpp.tk                            |  7
code/JayXon_1_1/B.cpp.tk                            |  23
code/JayXon_2_1/C.cpp.tk                            |  32
code/Josse_0_1/A.cpp.tk                             |  15
code/Josse_1_1/B.cpp.tk                             |  20
code/Josse_2_1/C.cpp.tk                             |  79
code/kcm1700_0_1/a.cpp.tk                           |  9
code/kcm1700_1_1/b.cpp.tk                           |  26
code/kcm1700_2_1/c.cpp.tk                           |  56
code/kevinsogo_0_1/a.cpp.tk                         |  18
code/kevinsogo_1_1/b.cpp.tk                         |  21
code/kevinsogo_2_1/c.cpp.tk                         |  58
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  9
code/LazyAnna_1_1/2-1.cpp.tk                        |  17
code/LazyAnna_2_1/3.cpp.tk                          |  33
code/Merkurev_0_1/A.cpp.tk                          |  15
code/Merkurev_1_1/B.cpp.tk                          |  31
code/Merkurev_2_1/C.cpp.tk                          |  31
code/mezei_0_1/main.cpp.tk                          |  15
code/mezei_1_1/main.cpp.tk                          |  15
code/mezei_2_1/main.cpp.tk                          |  48
code/Mister_0_1/a.cpp.tk                            |  11
code/Mister_1_1/b.cpp.tk                            |  14
code/Mister_2_1/c.cpp.tk                            |  23
code/namonakiacc_0_1/cpp.cpp.tk                     |  108
code/namonakiacc_1_1/cpp.cpp.tk                     |  115
code/namonakiacc_2_1/cpp.cpp.tk                     |  132
code/Nicolas16_0_1/main.cpp.tk                      |  6
code/Nicolas16_1_1/main.cpp.tk                      |  6
code/Nicolas16_2_1/main.cpp.tk                      |  48
code/pandamonium_0_1/a.cpp.tk                       |  9
code/pandamonium_1_1/b.cpp.tk                       |  31
code/pandamonium_2_1/c.cpp.tk                       |  18
code/pflueger_0_1/A.cpp.tk                          |  13
code/pflueger_1_1/B.cpp.tk                          |  19
code/pflueger_2_1/C.cpp.tk                          |  48
code/ponyopoppo_0_1/A.cpp.tk                        |  19
code/ponyopoppo_1_1/B.cpp.tk                        |  39
code/ponyopoppo_2_1/C.cpp.tk                        |  119
code/Ragnar_0_1/A.cpp.tk                            |  107
code/Ragnar_1_1/B-2.cpp.tk                          |  131
code/Ragnar_2_1/C.cpp.tk                            |  128
code/saffah_0_1/t.cpp.tk                            |  15
code/saffah_1_1/t.cpp.tk                            |  25
code/saffah_2_1/t.cpp.tk                            |  77
code/SamanSami_0_1/A.cpp.tk                         |  4
code/SamanSami_1_1/B.cpp.tk                         |  20
code/SamanSami_2_1/C.cpp.tk                         |  10
code/Savlik_0_1/code.cpp.tk                         |  13
code/Savlik_1_1/code.cpp.tk                         |  18
code/Savlik_2_1/code.cpp.tk                         |  63
code/shik_0_1/pa.cpp.tk                             |  71
code/shik_1_1/pb.cpp.tk                             |  73
code/shik_2_1/pc.cpp.tk                             |  100
code/simsa.st_0_1/A.cpp.tk                          |  14
code/simsa.st_1_1/B.cpp.tk                          |  22
code/simsa.st_2_1/C.cpp.tk                          |  73
code/SovietUnion_0_1/A.cpp.tk                       |  13
code/SovietUnion_1_1/B.cpp.tk                       |  17
code/SovietUnion_2_1/C.cpp.tk                       |  61
code/tailed_0_1/A.cpp.tk                            |  14
code/tailed_1_1/B.cpp.tk                            |  34
code/tailed_2_1/C.cpp.tk                            |  38
code/TheNatural_0_1/A.cpp.tk                        |  13
code/TheNatural_1_1/B.cpp.tk                        |  17
code/TheNatural_2_1/C.cpp.tk                        |  21
code/TrueBamboo_0_1/test.cpp.tk                     |  15
code/TrueBamboo_1_1/test.cpp.tk                     |  33
code/TrueBamboo_2_1/test.cpp.tk                     |  42
code/tur.turczyn_0_1/A.cpp.tk                       |  96
code/tur.turczyn_1_1/B.cpp.tk                       |  115
code/tur.turczyn_2_1/C.cpp.tk                       |  110
code/Tyg3R_0_1/A.cpp.tk                             |  19
code/Tyg3R_1_1/B.cpp.tk                             |  30
code/Tyg3R_2_1/C.cpp.tk                             |  28
code/UminchuR_0_1/main.cpp.tk                       |  93
code/UminchuR_1_1/main.cpp.tk                       |  108
code/UminchuR_2_1/main.cpp.tk                       |  123
code/wo..._0_1/a.cpp.tk                             |  13
code/wo..._1_1/b.cpp.tk                             |  17
code/wo..._2_1/c.cpp.tk                             |  48
code/yswtt_0_1/A.cpp.tk                             |  10
code/yswtt_1_1/B.cpp.tk                             |  21
code/yswtt_2_1/C.cpp.tk                             |  32
code/ZhSh_0_1/a.cpp.tk                              |  12
code/ZhSh_1_1/b.cpp.tk                              |  94
code/ZhSh_2_1/c.cpp.tk                              |  98
