Begin
Comparing:  code/FatalEagle_1_1/main.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  46
code/551100kk_1_1/B.cpp.tk                          |  82
code/551100kk_2_1/C.cpp.tk                          |  70
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  19
code/achan1058_2_1/source.cpp.tk                    |  40
code/alanubi_0_1/a.cpp.tk                           |  85
code/alanubi_1_1/b.cpp.tk                           |  103
code/alanubi_2_1/c.cpp.tk                           |  191
code/AntiForest_0_1/q1.cpp.tk                       |  35
code/AntiForest_1_1/q2.cpp.tk                       |  23
code/AntiForest_2_1/q3.cpp.tk                       |  79
code/apiad_0_1/A.cpp.tk                             |  17
code/apiad_1_1/B.cpp.tk                             |  24
code/apiad_2_1/C.cpp.tk                             |  28
code/azaky_0_1/A.cpp.tk                             |  21
code/azaky_1_1/B.cpp.tk                             |  29
code/azaky_2_1/C.cpp.tk                             |  52
code/azariamuh_0_1/standing.cpp.tk                  |  18
code/azariamuh_1_1/pancake.cpp.tk                   |  30
code/azariamuh_2_1/dijkstra.cpp.tk                  |  25
code/bmerry_0_1/a.cpp.tk                            |  82
code/bmerry_1_1/b.cpp.tk                            |  145
code/bmerry_2_1/c.cpp.tk                            |  79
code/climpet_0_1/A.cpp.tk                           |  49
code/climpet_1_1/B.cpp.tk                           |  57
code/climpet_2_1/C.cpp.tk                           |  84
code/ctzsm_0_1/A.cpp.tk                             |  103
code/ctzsm_1_1/B.cpp.tk                             |  123
code/ctzsm_2_1/C.cpp.tk                             |  149
code/DanilC_0_1/problem.cpp.tk                      |  63
code/DanilC_1_1/problemB.cpp.tk                     |  86
code/DanilC_2_1/problemC.cpp.tk                     |  110
code/DEGwer_0_1/A.cpp.tk                            |  91
code/DEGwer_1_1/B.cpp.tk                            |  89
code/DEGwer_2_1/C.cpp.tk                            |  63
code/dmute_0_1/a.cpp.tk                             |  90
code/dmute_1_1/b.cpp.tk                             |  155
code/dmute_2_1/c2.cpp.tk                            |  182
code/fagu_0_1/A.cpp.tk                              |  31
code/fagu_1_1/B.cpp.tk                              |  32
code/fagu_2_1/C.cpp.tk                              |  53
code/FatalEagle_0_1/main.cpp.tk                     |  410
code/FatalEagle_1_1/main.cpp.tk                     |  13889
code/FatalEagle_2_1/main.cpp.tk                     |  382
code/fullpower_0_1/A.cpp.tk                         |  147
code/fullpower_1_1/B.cpp.tk                         |  249
code/fullpower_2_1/C.cpp.tk                         |  270
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  33
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  54
code/ICastro_2_1/Dijkstra.cpp.tk                    |  102
code/ilackthatsuperpower_0_1/a.cpp.tk               |  123
code/ilackthatsuperpower_1_1/b.cpp.tk               |  163
code/ilackthatsuperpower_2_1/c.cpp.tk               |  118
code/iridescent_0_1/A.cpp.tk                        |  49
code/iridescent_1_1/B.cpp.tk                        |  115
code/iridescent_2_1/C.cpp.tk                        |  92
code/ishraq_0_1/main.cpp.tk                         |  15
code/ishraq_1_1/main.cpp.tk                         |  46
code/ishraq_2_1/main.cpp.tk                         |  57
code/JayXon_0_1/A.cpp.tk                            |  34
code/JayXon_1_1/B.cpp.tk                            |  82
code/JayXon_2_1/C.cpp.tk                            |  32
code/Josse_0_1/A.cpp.tk                             |  52
code/Josse_1_1/B.cpp.tk                             |  94
code/Josse_2_1/C.cpp.tk                             |  151
code/kcm1700_0_1/a.cpp.tk                           |  100
code/kcm1700_1_1/b.cpp.tk                           |  176
code/kcm1700_2_1/c.cpp.tk                           |  144
code/kevinsogo_0_1/a.cpp.tk                         |  15
code/kevinsogo_1_1/b.cpp.tk                         |  30
code/kevinsogo_2_1/c.cpp.tk                         |  53
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  36
code/LazyAnna_1_1/2-1.cpp.tk                        |  56
code/LazyAnna_2_1/3.cpp.tk                          |  35
code/Merkurev_0_1/A.cpp.tk                          |  304
code/Merkurev_1_1/B.cpp.tk                          |  448
code/Merkurev_2_1/C.cpp.tk                          |  341
code/mezei_0_1/main.cpp.tk                          |  144
code/mezei_1_1/main.cpp.tk                          |  117
code/mezei_2_1/main.cpp.tk                          |  161
code/Mister_0_1/a.cpp.tk                            |  49
code/Mister_1_1/b.cpp.tk                            |  112
code/Mister_2_1/c.cpp.tk                            |  81
code/namonakiacc_0_1/cpp.cpp.tk                     |  24
code/namonakiacc_1_1/cpp.cpp.tk                     |  38
code/namonakiacc_2_1/cpp.cpp.tk                     |  42
code/Nicolas16_0_1/main.cpp.tk                      |  65
code/Nicolas16_1_1/main.cpp.tk                      |  61
code/Nicolas16_2_1/main.cpp.tk                      |  217
code/pandamonium_0_1/a.cpp.tk                       |  101
code/pandamonium_1_1/b.cpp.tk                       |  164
code/pandamonium_2_1/c.cpp.tk                       |  104
code/pflueger_0_1/A.cpp.tk                          |  75
code/pflueger_1_1/B.cpp.tk                          |  109
code/pflueger_2_1/C.cpp.tk                          |  131
code/ponyopoppo_0_1/A.cpp.tk                        |  8
code/ponyopoppo_1_1/B.cpp.tk                        |  20
code/ponyopoppo_2_1/C.cpp.tk                        |  85
code/Ragnar_0_1/A.cpp.tk                            |  13
code/Ragnar_1_1/B-2.cpp.tk                          |  34
code/Ragnar_2_1/C.cpp.tk                            |  55
code/saffah_0_1/t.cpp.tk                            |  15
code/saffah_1_1/t.cpp.tk                            |  21
code/saffah_2_1/t.cpp.tk                            |  65
code/SamanSami_0_1/A.cpp.tk                         |  30
code/SamanSami_1_1/B.cpp.tk                         |  111
code/SamanSami_2_1/C.cpp.tk                         |  7
code/Savlik_0_1/code.cpp.tk                         |  42
code/Savlik_1_1/code.cpp.tk                         |  19
code/Savlik_2_1/code.cpp.tk                         |  49
code/shik_0_1/pa.cpp.tk                             |  45
code/shik_1_1/pb.cpp.tk                             |  57
code/shik_2_1/pc.cpp.tk                             |  77
code/simsa.st_0_1/A.cpp.tk                          |  17
code/simsa.st_1_1/B.cpp.tk                          |  22
code/simsa.st_2_1/C.cpp.tk                          |  60
code/SovietUnion_0_1/A.cpp.tk                       |  79
code/SovietUnion_1_1/B.cpp.tk                       |  101
code/SovietUnion_2_1/C.cpp.tk                       |  71
code/tailed_0_1/A.cpp.tk                            |  39
code/tailed_1_1/B.cpp.tk                            |  60
code/tailed_2_1/C.cpp.tk                            |  43
code/TheNatural_0_1/A.cpp.tk                        |  108
code/TheNatural_1_1/B.cpp.tk                        |  147
code/TheNatural_2_1/C.cpp.tk                        |  54
code/TrueBamboo_0_1/test.cpp.tk                     |  47
code/TrueBamboo_1_1/test.cpp.tk                     |  69
code/TrueBamboo_2_1/test.cpp.tk                     |  62
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  16
code/tur.turczyn_2_1/C.cpp.tk                       |  21
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  18
code/Tyg3R_2_1/C.cpp.tk                             |  19
code/UminchuR_0_1/main.cpp.tk                       |  137
code/UminchuR_1_1/main.cpp.tk                       |  151
code/UminchuR_2_1/main.cpp.tk                       |  90
code/wo..._0_1/a.cpp.tk                             |  96
code/wo..._1_1/b.cpp.tk                             |  157
code/wo..._2_1/c.cpp.tk                             |  191
code/yswtt_0_1/A.cpp.tk                             |  33
code/yswtt_1_1/B.cpp.tk                             |  56
code/yswtt_2_1/C.cpp.tk                             |  55
code/ZhSh_0_1/a.cpp.tk                              |  35
code/ZhSh_1_1/b.cpp.tk                              |  89
code/ZhSh_2_1/c.cpp.tk                              |  70
