Begin
Comparing:  code/UminchuR_0_1/main.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  31
code/551100kk_1_1/B.cpp.tk                          |  34
code/551100kk_2_1/C.cpp.tk                          |  48
code/achan1058_0_1/Q-A.cpp.tk                       |  13
code/achan1058_1_1/source.cpp.tk                    |  84
code/achan1058_2_1/source.cpp.tk                    |  107
code/alanubi_0_1/a.cpp.tk                           |  20
code/alanubi_1_1/b.cpp.tk                           |  24
code/alanubi_2_1/c.cpp.tk                           |  80
code/AntiForest_0_1/q1.cpp.tk                       |  33
code/AntiForest_1_1/q2.cpp.tk                       |  23
code/AntiForest_2_1/q3.cpp.tk                       |  59
code/apiad_0_1/A.cpp.tk                             |  26
code/apiad_1_1/B.cpp.tk                             |  27
code/apiad_2_1/C.cpp.tk                             |  31
code/azaky_0_1/A.cpp.tk                             |  29
code/azaky_1_1/B.cpp.tk                             |  34
code/azaky_2_1/C.cpp.tk                             |  59
code/azariamuh_0_1/standing.cpp.tk                  |  17
code/azariamuh_1_1/pancake.cpp.tk                   |  22
code/azariamuh_2_1/dijkstra.cpp.tk                  |  21
code/bmerry_0_1/a.cpp.tk                            |  65
code/bmerry_1_1/b.cpp.tk                            |  62
code/bmerry_2_1/c.cpp.tk                            |  63
code/climpet_0_1/A.cpp.tk                           |  46
code/climpet_1_1/B.cpp.tk                           |  41
code/climpet_2_1/C.cpp.tk                           |  57
code/ctzsm_0_1/A.cpp.tk                             |  61
code/ctzsm_1_1/B.cpp.tk                             |  61
code/ctzsm_2_1/C.cpp.tk                             |  74
code/DanilC_0_1/problem.cpp.tk                      |  23
code/DanilC_1_1/problemB.cpp.tk                     |  32
code/DanilC_2_1/problemC.cpp.tk                     |  80
code/DEGwer_0_1/A.cpp.tk                            |  20
code/DEGwer_1_1/B.cpp.tk                            |  21
code/DEGwer_2_1/C.cpp.tk                            |  27
code/dmute_0_1/a.cpp.tk                             |  12
code/dmute_1_1/b.cpp.tk                             |  16
code/dmute_2_1/c2.cpp.tk                            |  34
code/fagu_0_1/A.cpp.tk                              |  23
code/fagu_1_1/B.cpp.tk                              |  23
code/fagu_2_1/C.cpp.tk                              |  43
code/FatalEagle_0_1/main.cpp.tk                     |  116
code/FatalEagle_1_1/main.cpp.tk                     |  114
code/FatalEagle_2_1/main.cpp.tk                     |  102
code/fullpower_0_1/A.cpp.tk                         |  37
code/fullpower_1_1/B.cpp.tk                         |  34
code/fullpower_2_1/C.cpp.tk                         |  65
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  20
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  15
code/ICastro_2_1/Dijkstra.cpp.tk                    |  87
code/ilackthatsuperpower_0_1/a.cpp.tk               |  69
code/ilackthatsuperpower_1_1/b.cpp.tk               |  69
code/ilackthatsuperpower_2_1/c.cpp.tk               |  91
code/iridescent_0_1/A.cpp.tk                        |  26
code/iridescent_1_1/B.cpp.tk                        |  11
code/iridescent_2_1/C.cpp.tk                        |  15
code/ishraq_0_1/main.cpp.tk                         |  18
code/ishraq_1_1/main.cpp.tk                         |  17
code/ishraq_2_1/main.cpp.tk                         |  52
code/JayXon_0_1/A.cpp.tk                            |  11
code/JayXon_1_1/B.cpp.tk                            |  14
code/JayXon_2_1/C.cpp.tk                            |  29
code/Josse_0_1/A.cpp.tk                             |  19
code/Josse_1_1/B.cpp.tk                             |  14
code/Josse_2_1/C.cpp.tk                             |  63
code/kcm1700_0_1/a.cpp.tk                           |  18
code/kcm1700_1_1/b.cpp.tk                           |  18
code/kcm1700_2_1/c.cpp.tk                           |  38
code/kevinsogo_0_1/a.cpp.tk                         |  18
code/kevinsogo_1_1/b.cpp.tk                         |  22
code/kevinsogo_2_1/c.cpp.tk                         |  47
code/ksun48_0_1/A.cpp.tk                            |  5
code/ksun48_1_1/B.cpp.tk                            |  5
code/ksun48_2_1/C.cpp.tk                            |  15
code/LazyAnna_0_1/1.cpp.tk                          |  9
code/LazyAnna_1_1/2-1.cpp.tk                        |  11
code/LazyAnna_2_1/3.cpp.tk                          |  27
code/Merkurev_0_1/A.cpp.tk                          |  76
code/Merkurev_1_1/B.cpp.tk                          |  139
code/Merkurev_2_1/C.cpp.tk                          |  91
code/mezei_0_1/main.cpp.tk                          |  16
code/mezei_1_1/main.cpp.tk                          |  14
code/mezei_2_1/main.cpp.tk                          |  47
code/Mister_0_1/a.cpp.tk                            |  15
code/Mister_1_1/b.cpp.tk                            |  15
code/Mister_2_1/c.cpp.tk                            |  24
code/namonakiacc_0_1/cpp.cpp.tk                     |  85
code/namonakiacc_1_1/cpp.cpp.tk                     |  87
code/namonakiacc_2_1/cpp.cpp.tk                     |  102
code/Nicolas16_0_1/main.cpp.tk                      |  8
code/Nicolas16_1_1/main.cpp.tk                      |  7
code/Nicolas16_2_1/main.cpp.tk                      |  48
code/pandamonium_0_1/a.cpp.tk                       |  14
code/pandamonium_1_1/b.cpp.tk                       |  25
code/pandamonium_2_1/c.cpp.tk                       |  17
code/pflueger_0_1/A.cpp.tk                          |  11
code/pflueger_1_1/B.cpp.tk                          |  13
code/pflueger_2_1/C.cpp.tk                          |  46
code/ponyopoppo_0_1/A.cpp.tk                        |  17
code/ponyopoppo_1_1/B.cpp.tk                        |  22
code/ponyopoppo_2_1/C.cpp.tk                        |  95
code/Ragnar_0_1/A.cpp.tk                            |  46
code/Ragnar_1_1/B-2.cpp.tk                          |  49
code/Ragnar_2_1/C.cpp.tk                            |  63
code/saffah_0_1/t.cpp.tk                            |  17
code/saffah_1_1/t.cpp.tk                            |  16
code/saffah_2_1/t.cpp.tk                            |  67
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  11
code/SamanSami_2_1/C.cpp.tk                         |  9
code/Savlik_0_1/code.cpp.tk                         |  12
code/Savlik_1_1/code.cpp.tk                         |  13
code/Savlik_2_1/code.cpp.tk                         |  50
code/shik_0_1/pa.cpp.tk                             |  59
code/shik_1_1/pb.cpp.tk                             |  58
code/shik_2_1/pc.cpp.tk                             |  75
code/simsa.st_0_1/A.cpp.tk                          |  16
code/simsa.st_1_1/B.cpp.tk                          |  19
code/simsa.st_2_1/C.cpp.tk                          |  65
code/SovietUnion_0_1/A.cpp.tk                       |  26
code/SovietUnion_1_1/B.cpp.tk                       |  29
code/SovietUnion_2_1/C.cpp.tk                       |  63
code/tailed_0_1/A.cpp.tk                            |  32
code/tailed_1_1/B.cpp.tk                            |  15
code/tailed_2_1/C.cpp.tk                            |  31
code/TheNatural_0_1/A.cpp.tk                        |  10
code/TheNatural_1_1/B.cpp.tk                        |  13
code/TheNatural_2_1/C.cpp.tk                        |  19
code/TrueBamboo_0_1/test.cpp.tk                     |  16
code/TrueBamboo_1_1/test.cpp.tk                     |  20
code/TrueBamboo_2_1/test.cpp.tk                     |  42
code/tur.turczyn_0_1/A.cpp.tk                       |  50
code/tur.turczyn_1_1/B.cpp.tk                       |  53
code/tur.turczyn_2_1/C.cpp.tk                       |  59
code/Tyg3R_0_1/A.cpp.tk                             |  12
code/Tyg3R_1_1/B.cpp.tk                             |  13
code/Tyg3R_2_1/C.cpp.tk                             |  18
code/UminchuR_0_1/main.cpp.tk                       |  15772
code/UminchuR_1_1/main.cpp.tk                       |  2703
code/UminchuR_2_1/main.cpp.tk                       |  2219
code/wo..._0_1/a.cpp.tk                             |  17
code/wo..._1_1/b.cpp.tk                             |  17
code/wo..._2_1/c.cpp.tk                             |  45
code/yswtt_0_1/A.cpp.tk                             |  10
code/yswtt_1_1/B.cpp.tk                             |  11
code/yswtt_2_1/C.cpp.tk                             |  29
code/ZhSh_0_1/a.cpp.tk                              |  12
code/ZhSh_1_1/b.cpp.tk                              |  64
code/ZhSh_2_1/c.cpp.tk                              |  75
