Begin
Comparing:  code/FatalEagle_2_1/main.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  16
code/551100kk_1_1/B.cpp.tk                          |  32
code/551100kk_2_1/C.cpp.tk                          |  55
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  18
code/achan1058_2_1/source.cpp.tk                    |  47
code/alanubi_0_1/a.cpp.tk                           |  27
code/alanubi_1_1/b.cpp.tk                           |  54
code/alanubi_2_1/c.cpp.tk                           |  113
code/AntiForest_0_1/q1.cpp.tk                       |  17
code/AntiForest_1_1/q2.cpp.tk                       |  7
code/AntiForest_2_1/q3.cpp.tk                       |  64
code/apiad_0_1/A.cpp.tk                             |  12
code/apiad_1_1/B.cpp.tk                             |  19
code/apiad_2_1/C.cpp.tk                             |  43
code/azaky_0_1/A.cpp.tk                             |  15
code/azaky_1_1/B.cpp.tk                             |  21
code/azaky_2_1/C.cpp.tk                             |  54
code/azariamuh_0_1/standing.cpp.tk                  |  10
code/azariamuh_1_1/pancake.cpp.tk                   |  44
code/azariamuh_2_1/dijkstra.cpp.tk                  |  21
code/bmerry_0_1/a.cpp.tk                            |  50
code/bmerry_1_1/b.cpp.tk                            |  76
code/bmerry_2_1/c.cpp.tk                            |  81
code/climpet_0_1/A.cpp.tk                           |  27
code/climpet_1_1/B.cpp.tk                           |  37
code/climpet_2_1/C.cpp.tk                           |  65
code/ctzsm_0_1/A.cpp.tk                             |  21
code/ctzsm_1_1/B.cpp.tk                             |  34
code/ctzsm_2_1/C.cpp.tk                             |  111
code/DanilC_0_1/problem.cpp.tk                      |  32
code/DanilC_1_1/problemB.cpp.tk                     |  59
code/DanilC_2_1/problemC.cpp.tk                     |  109
code/DEGwer_0_1/A.cpp.tk                            |  38
code/DEGwer_1_1/B.cpp.tk                            |  48
code/DEGwer_2_1/C.cpp.tk                            |  46
code/dmute_0_1/a.cpp.tk                             |  20
code/dmute_1_1/b.cpp.tk                             |  39
code/dmute_2_1/c2.cpp.tk                            |  95
code/fagu_0_1/A.cpp.tk                              |  17
code/fagu_1_1/B.cpp.tk                              |  17
code/fagu_2_1/C.cpp.tk                              |  54
code/FatalEagle_0_1/main.cpp.tk                     |  26
code/FatalEagle_1_1/main.cpp.tk                     |  58
code/FatalEagle_2_1/main.cpp.tk                     |  574869
code/fullpower_0_1/A.cpp.tk                         |  41
code/fullpower_1_1/B.cpp.tk                         |  101
code/fullpower_2_1/C.cpp.tk                         |  154
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  15
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  30
code/ICastro_2_1/Dijkstra.cpp.tk                    |  98
code/ilackthatsuperpower_0_1/a.cpp.tk               |  85
code/ilackthatsuperpower_1_1/b.cpp.tk               |  86
code/ilackthatsuperpower_2_1/c.cpp.tk               |  112
code/iridescent_0_1/A.cpp.tk                        |  16
code/iridescent_1_1/B.cpp.tk                        |  30
code/iridescent_2_1/C.cpp.tk                        |  49
code/ishraq_0_1/main.cpp.tk                         |  8
code/ishraq_1_1/main.cpp.tk                         |  19
code/ishraq_2_1/main.cpp.tk                         |  87
code/JayXon_0_1/A.cpp.tk                            |  11
code/JayXon_1_1/B.cpp.tk                            |  52
code/JayXon_2_1/C.cpp.tk                            |  31
code/Josse_0_1/A.cpp.tk                             |  30
code/Josse_1_1/B.cpp.tk                             |  52
code/Josse_2_1/C.cpp.tk                             |  126
code/kcm1700_0_1/a.cpp.tk                           |  20
code/kcm1700_1_1/b.cpp.tk                           |  48
code/kcm1700_2_1/c.cpp.tk                           |  105
code/kevinsogo_0_1/a.cpp.tk                         |  12
code/kevinsogo_1_1/b.cpp.tk                         |  16
code/kevinsogo_2_1/c.cpp.tk                         |  159
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  14
code/LazyAnna_1_1/2-1.cpp.tk                        |  28
code/LazyAnna_2_1/3.cpp.tk                          |  31
code/Merkurev_0_1/A.cpp.tk                          |  38
code/Merkurev_1_1/B.cpp.tk                          |  71
code/Merkurev_2_1/C.cpp.tk                          |  99
code/mezei_0_1/main.cpp.tk                          |  32
code/mezei_1_1/main.cpp.tk                          |  46
code/mezei_2_1/main.cpp.tk                          |  89
code/Mister_0_1/a.cpp.tk                            |  19
code/Mister_1_1/b.cpp.tk                            |  31
code/Mister_2_1/c.cpp.tk                            |  56
code/namonakiacc_0_1/cpp.cpp.tk                     |  15
code/namonakiacc_1_1/cpp.cpp.tk                     |  19
code/namonakiacc_2_1/cpp.cpp.tk                     |  80
code/Nicolas16_0_1/main.cpp.tk                      |  13
code/Nicolas16_1_1/main.cpp.tk                      |  13
code/Nicolas16_2_1/main.cpp.tk                      |  98
code/pandamonium_0_1/a.cpp.tk                       |  21
code/pandamonium_1_1/b.cpp.tk                       |  92
code/pandamonium_2_1/c.cpp.tk                       |  56
code/pflueger_0_1/A.cpp.tk                          |  16
code/pflueger_1_1/B.cpp.tk                          |  45
code/pflueger_2_1/C.cpp.tk                          |  92
code/ponyopoppo_0_1/A.cpp.tk                        |  10
code/ponyopoppo_1_1/B.cpp.tk                        |  20
code/ponyopoppo_2_1/C.cpp.tk                        |  108
code/Ragnar_0_1/A.cpp.tk                            |  10
code/Ragnar_1_1/B-2.cpp.tk                          |  26
code/Ragnar_2_1/C.cpp.tk                            |  34
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  13
code/saffah_2_1/t.cpp.tk                            |  69
code/SamanSami_0_1/A.cpp.tk                         |  6
code/SamanSami_1_1/B.cpp.tk                         |  43
code/SamanSami_2_1/C.cpp.tk                         |  9
code/Savlik_0_1/code.cpp.tk                         |  13
code/Savlik_1_1/code.cpp.tk                         |  13
code/Savlik_2_1/code.cpp.tk                         |  54
code/shik_0_1/pa.cpp.tk                             |  44
code/shik_1_1/pb.cpp.tk                             |  49
code/shik_2_1/pc.cpp.tk                             |  89
code/simsa.st_0_1/A.cpp.tk                          |  11
code/simsa.st_1_1/B.cpp.tk                          |  14
code/simsa.st_2_1/C.cpp.tk                          |  68
code/SovietUnion_0_1/A.cpp.tk                       |  27
code/SovietUnion_1_1/B.cpp.tk                       |  34
code/SovietUnion_2_1/C.cpp.tk                       |  58
code/tailed_0_1/A.cpp.tk                            |  12
code/tailed_1_1/B.cpp.tk                            |  23
code/tailed_2_1/C.cpp.tk                            |  29
code/TheNatural_0_1/A.cpp.tk                        |  23
code/TheNatural_1_1/B.cpp.tk                        |  42
code/TheNatural_2_1/C.cpp.tk                        |  28
code/TrueBamboo_0_1/test.cpp.tk                     |  17
code/TrueBamboo_1_1/test.cpp.tk                     |  30
code/TrueBamboo_2_1/test.cpp.tk                     |  44
code/tur.turczyn_0_1/A.cpp.tk                       |  8
code/tur.turczyn_1_1/B.cpp.tk                       |  15
code/tur.turczyn_2_1/C.cpp.tk                       |  20
code/Tyg3R_0_1/A.cpp.tk                             |  9
code/Tyg3R_1_1/B.cpp.tk                             |  17
code/Tyg3R_2_1/C.cpp.tk                             |  22
code/UminchuR_0_1/main.cpp.tk                       |  17
code/UminchuR_1_1/main.cpp.tk                       |  26
code/UminchuR_2_1/main.cpp.tk                       |  64
code/wo..._0_1/a.cpp.tk                             |  43
code/wo..._1_1/b.cpp.tk                             |  51
code/wo..._2_1/c.cpp.tk                             |  144
code/yswtt_0_1/A.cpp.tk                             |  11
code/yswtt_1_1/B.cpp.tk                             |  29
code/yswtt_2_1/C.cpp.tk                             |  34
code/ZhSh_0_1/a.cpp.tk                              |  13
code/ZhSh_1_1/b.cpp.tk                              |  64
code/ZhSh_2_1/c.cpp.tk                              |  70
