Begin
Comparing:  code/ksun48_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  21
code/551100kk_1_1/B.cpp.tk                          |  30
code/551100kk_2_1/C.cpp.tk                          |  43
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  33
code/achan1058_2_1/source.cpp.tk                    |  47
code/alanubi_0_1/a.cpp.tk                           |  14
code/alanubi_1_1/b.cpp.tk                           |  19
code/alanubi_2_1/c.cpp.tk                           |  100
code/AntiForest_0_1/q1.cpp.tk                       |  29
code/AntiForest_1_1/q2.cpp.tk                       |  21
code/AntiForest_2_1/q3.cpp.tk                       |  64
code/apiad_0_1/A.cpp.tk                             |  21
code/apiad_1_1/B.cpp.tk                             |  28
code/apiad_2_1/C.cpp.tk                             |  36
code/azaky_0_1/A.cpp.tk                             |  33
code/azaky_1_1/B.cpp.tk                             |  35
code/azaky_2_1/C.cpp.tk                             |  71
code/azariamuh_0_1/standing.cpp.tk                  |  13
code/azariamuh_1_1/pancake.cpp.tk                   |  20
code/azariamuh_2_1/dijkstra.cpp.tk                  |  21
code/bmerry_0_1/a.cpp.tk                            |  40
code/bmerry_1_1/b.cpp.tk                            |  46
code/bmerry_2_1/c.cpp.tk                            |  47
code/climpet_0_1/A.cpp.tk                           |  28
code/climpet_1_1/B.cpp.tk                           |  33
code/climpet_2_1/C.cpp.tk                           |  44
code/ctzsm_0_1/A.cpp.tk                             |  26
code/ctzsm_1_1/B.cpp.tk                             |  30
code/ctzsm_2_1/C.cpp.tk                             |  73
code/DanilC_0_1/problem.cpp.tk                      |  22
code/DanilC_1_1/problemB.cpp.tk                     |  31
code/DanilC_2_1/problemC.cpp.tk                     |  81
code/DEGwer_0_1/A.cpp.tk                            |  48
code/DEGwer_1_1/B.cpp.tk                            |  49
code/DEGwer_2_1/C.cpp.tk                            |  53
code/dmute_0_1/a.cpp.tk                             |  9
code/dmute_1_1/b.cpp.tk                             |  13
code/dmute_2_1/c2.cpp.tk                            |  35
code/fagu_0_1/A.cpp.tk                              |  15
code/fagu_1_1/B.cpp.tk                              |  15
code/fagu_2_1/C.cpp.tk                              |  34
code/FatalEagle_0_1/main.cpp.tk                     |  27
code/FatalEagle_1_1/main.cpp.tk                     |  30
code/FatalEagle_2_1/main.cpp.tk                     |  98
code/fullpower_0_1/A.cpp.tk                         |  34
code/fullpower_1_1/B.cpp.tk                         |  32
code/fullpower_2_1/C.cpp.tk                         |  66
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  11
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  15
code/ICastro_2_1/Dijkstra.cpp.tk                    |  107
code/ilackthatsuperpower_0_1/a.cpp.tk               |  68
code/ilackthatsuperpower_1_1/b.cpp.tk               |  70
code/ilackthatsuperpower_2_1/c.cpp.tk               |  93
code/iridescent_0_1/A.cpp.tk                        |  7
code/iridescent_1_1/B.cpp.tk                        |  9
code/iridescent_2_1/C.cpp.tk                        |  14
code/ishraq_0_1/main.cpp.tk                         |  11
code/ishraq_1_1/main.cpp.tk                         |  15
code/ishraq_2_1/main.cpp.tk                         |  55
code/JayXon_0_1/A.cpp.tk                            |  7
code/JayXon_1_1/B.cpp.tk                            |  13
code/JayXon_2_1/C.cpp.tk                            |  25
code/Josse_0_1/A.cpp.tk                             |  11
code/Josse_1_1/B.cpp.tk                             |  13
code/Josse_2_1/C.cpp.tk                             |  77
code/kcm1700_0_1/a.cpp.tk                           |  12
code/kcm1700_1_1/b.cpp.tk                           |  15
code/kcm1700_2_1/c.cpp.tk                           |  38
code/kevinsogo_0_1/a.cpp.tk                         |  12
code/kevinsogo_1_1/b.cpp.tk                         |  13
code/kevinsogo_2_1/c.cpp.tk                         |  39
code/ksun48_0_1/A.cpp.tk                            |  214
code/ksun48_1_1/B.cpp.tk                            |  214
code/ksun48_2_1/C.cpp.tk                            |  85
code/LazyAnna_0_1/1.cpp.tk                          |  7
code/LazyAnna_1_1/2-1.cpp.tk                        |  10
code/LazyAnna_2_1/3.cpp.tk                          |  35
code/Merkurev_0_1/A.cpp.tk                          |  29
code/Merkurev_1_1/B.cpp.tk                          |  40
code/Merkurev_2_1/C.cpp.tk                          |  44
code/mezei_0_1/main.cpp.tk                          |  37
code/mezei_1_1/main.cpp.tk                          |  35
code/mezei_2_1/main.cpp.tk                          |  79
code/Mister_0_1/a.cpp.tk                            |  12
code/Mister_1_1/b.cpp.tk                            |  14
code/Mister_2_1/c.cpp.tk                            |  24
code/namonakiacc_0_1/cpp.cpp.tk                     |  35
code/namonakiacc_1_1/cpp.cpp.tk                     |  39
code/namonakiacc_2_1/cpp.cpp.tk                     |  50
code/Nicolas16_0_1/main.cpp.tk                      |  11
code/Nicolas16_1_1/main.cpp.tk                      |  10
code/Nicolas16_2_1/main.cpp.tk                      |  53
code/pandamonium_0_1/a.cpp.tk                       |  8
code/pandamonium_1_1/b.cpp.tk                       |  23
code/pandamonium_2_1/c.cpp.tk                       |  14
code/pflueger_0_1/A.cpp.tk                          |  8
code/pflueger_1_1/B.cpp.tk                          |  11
code/pflueger_2_1/C.cpp.tk                          |  41
code/ponyopoppo_0_1/A.cpp.tk                        |  17
code/ponyopoppo_1_1/B.cpp.tk                        |  27
code/ponyopoppo_2_1/C.cpp.tk                        |  105
code/Ragnar_0_1/A.cpp.tk                            |  17
code/Ragnar_1_1/B-2.cpp.tk                          |  23
code/Ragnar_2_1/C.cpp.tk                            |  37
code/saffah_0_1/t.cpp.tk                            |  9
code/saffah_1_1/t.cpp.tk                            |  13
code/saffah_2_1/t.cpp.tk                            |  76
code/SamanSami_0_1/A.cpp.tk                         |  4
code/SamanSami_1_1/B.cpp.tk                         |  10
code/SamanSami_2_1/C.cpp.tk                         |  16
code/Savlik_0_1/code.cpp.tk                         |  12
code/Savlik_1_1/code.cpp.tk                         |  17
code/Savlik_2_1/code.cpp.tk                         |  69
code/shik_0_1/pa.cpp.tk                             |  53
code/shik_1_1/pb.cpp.tk                             |  55
code/shik_2_1/pc.cpp.tk                             |  74
code/simsa.st_0_1/A.cpp.tk                          |  11
code/simsa.st_1_1/B.cpp.tk                          |  16
code/simsa.st_2_1/C.cpp.tk                          |  90
code/SovietUnion_0_1/A.cpp.tk                       |  22
code/SovietUnion_1_1/B.cpp.tk                       |  24
code/SovietUnion_2_1/C.cpp.tk                       |  77
code/tailed_0_1/A.cpp.tk                            |  15
code/tailed_1_1/B.cpp.tk                            |  16
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  9
code/TheNatural_1_1/B.cpp.tk                        |  11
code/TheNatural_2_1/C.cpp.tk                        |  23
code/TrueBamboo_0_1/test.cpp.tk                     |  49
code/TrueBamboo_1_1/test.cpp.tk                     |  55
code/TrueBamboo_2_1/test.cpp.tk                     |  85
code/tur.turczyn_0_1/A.cpp.tk                       |  25
code/tur.turczyn_1_1/B.cpp.tk                       |  32
code/tur.turczyn_2_1/C.cpp.tk                       |  35
code/Tyg3R_0_1/A.cpp.tk                             |  10
code/Tyg3R_1_1/B.cpp.tk                             |  13
code/Tyg3R_2_1/C.cpp.tk                             |  16
code/UminchuR_0_1/main.cpp.tk                       |  41
code/UminchuR_1_1/main.cpp.tk                       |  49
code/UminchuR_2_1/main.cpp.tk                       |  59
code/wo..._0_1/a.cpp.tk                             |  18
code/wo..._1_1/b.cpp.tk                             |  14
code/wo..._2_1/c.cpp.tk                             |  46
code/yswtt_0_1/A.cpp.tk                             |  6
code/yswtt_1_1/B.cpp.tk                             |  11
code/yswtt_2_1/C.cpp.tk                             |  27
code/ZhSh_0_1/a.cpp.tk                              |  8
code/ZhSh_1_1/b.cpp.tk                              |  48
code/ZhSh_2_1/c.cpp.tk                              |  62
