Begin
Comparing:  code/iridescent_1_1/B.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  27
code/551100kk_1_1/B.cpp.tk                          |  82
code/551100kk_2_1/C.cpp.tk                          |  32
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  39
code/achan1058_2_1/source.cpp.tk                    |  35
code/alanubi_0_1/a.cpp.tk                           |  74
code/alanubi_1_1/b.cpp.tk                           |  66
code/alanubi_2_1/c.cpp.tk                           |  139
code/AntiForest_0_1/q1.cpp.tk                       |  13
code/AntiForest_1_1/q2.cpp.tk                       |  5
code/AntiForest_2_1/q3.cpp.tk                       |  43
code/apiad_0_1/A.cpp.tk                             |  15
code/apiad_1_1/B.cpp.tk                             |  21
code/apiad_2_1/C.cpp.tk                             |  23
code/azaky_0_1/A.cpp.tk                             |  10
code/azaky_1_1/B.cpp.tk                             |  23
code/azaky_2_1/C.cpp.tk                             |  33
code/azariamuh_0_1/standing.cpp.tk                  |  12
code/azariamuh_1_1/pancake.cpp.tk                   |  28
code/azariamuh_2_1/dijkstra.cpp.tk                  |  17
code/bmerry_0_1/a.cpp.tk                            |  98
code/bmerry_1_1/b.cpp.tk                            |  143
code/bmerry_2_1/c.cpp.tk                            |  88
code/climpet_0_1/A.cpp.tk                           |  75
code/climpet_1_1/B.cpp.tk                           |  81
code/climpet_2_1/C.cpp.tk                           |  106
code/ctzsm_0_1/A.cpp.tk                             |  51
code/ctzsm_1_1/B.cpp.tk                             |  108
code/ctzsm_2_1/C.cpp.tk                             |  102
code/DanilC_0_1/problem.cpp.tk                      |  88
code/DanilC_1_1/problemB.cpp.tk                     |  99
code/DanilC_2_1/problemC.cpp.tk                     |  97
code/DEGwer_0_1/A.cpp.tk                            |  92
code/DEGwer_1_1/B.cpp.tk                            |  165
code/DEGwer_2_1/C.cpp.tk                            |  42
code/dmute_0_1/a.cpp.tk                             |  94
code/dmute_1_1/b.cpp.tk                             |  178
code/dmute_2_1/c2.cpp.tk                            |  151
code/fagu_0_1/A.cpp.tk                              |  16
code/fagu_1_1/B.cpp.tk                              |  19
code/fagu_2_1/C.cpp.tk                              |  28
code/FatalEagle_0_1/main.cpp.tk                     |  93
code/FatalEagle_1_1/main.cpp.tk                     |  172
code/FatalEagle_2_1/main.cpp.tk                     |  299
code/fullpower_0_1/A.cpp.tk                         |  128
code/fullpower_1_1/B.cpp.tk                         |  244
code/fullpower_2_1/C.cpp.tk                         |  295
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  61
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  91
code/ICastro_2_1/Dijkstra.cpp.tk                    |  76
code/ilackthatsuperpower_0_1/a.cpp.tk               |  127
code/ilackthatsuperpower_1_1/b.cpp.tk               |  114
code/ilackthatsuperpower_2_1/c.cpp.tk               |  84
code/iridescent_0_1/A.cpp.tk                        |  153
code/iridescent_1_1/B.cpp.tk                        |  6220
code/iridescent_2_1/C.cpp.tk                        |  256
code/ishraq_0_1/main.cpp.tk                         |  11
code/ishraq_1_1/main.cpp.tk                         |  112
code/ishraq_2_1/main.cpp.tk                         |  38
code/JayXon_0_1/A.cpp.tk                            |  44
code/JayXon_1_1/B.cpp.tk                            |  90
code/JayXon_2_1/C.cpp.tk                            |  22
code/Josse_0_1/A.cpp.tk                             |  45
code/Josse_1_1/B.cpp.tk                             |  139
code/Josse_2_1/C.cpp.tk                             |  108
code/kcm1700_0_1/a.cpp.tk                           |  107
code/kcm1700_1_1/b.cpp.tk                           |  224
code/kcm1700_2_1/c.cpp.tk                           |  146
code/kevinsogo_0_1/a.cpp.tk                         |  13
code/kevinsogo_1_1/b.cpp.tk                         |  32
code/kevinsogo_2_1/c.cpp.tk                         |  41
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  8
code/LazyAnna_0_1/1.cpp.tk                          |  64
code/LazyAnna_1_1/2-1.cpp.tk                        |  89
code/LazyAnna_2_1/3.cpp.tk                          |  44
code/Merkurev_0_1/A.cpp.tk                          |  138
code/Merkurev_1_1/B.cpp.tk                          |  100
code/Merkurev_2_1/C.cpp.tk                          |  142
code/mezei_0_1/main.cpp.tk                          |  142
code/mezei_1_1/main.cpp.tk                          |  119
code/mezei_2_1/main.cpp.tk                          |  111
code/Mister_0_1/a.cpp.tk                            |  47
code/Mister_1_1/b.cpp.tk                            |  74
code/Mister_2_1/c.cpp.tk                            |  76
code/namonakiacc_0_1/cpp.cpp.tk                     |  22
code/namonakiacc_1_1/cpp.cpp.tk                     |  24
code/namonakiacc_2_1/cpp.cpp.tk                     |  39
code/Nicolas16_0_1/main.cpp.tk                      |  43
code/Nicolas16_1_1/main.cpp.tk                      |  42
code/Nicolas16_2_1/main.cpp.tk                      |  199
code/pandamonium_0_1/a.cpp.tk                       |  96
code/pandamonium_1_1/b.cpp.tk                       |  105
code/pandamonium_2_1/c.cpp.tk                       |  92
code/pflueger_0_1/A.cpp.tk                          |  230
code/pflueger_1_1/B.cpp.tk                          |  325
code/pflueger_2_1/C.cpp.tk                          |  165
code/ponyopoppo_0_1/A.cpp.tk                        |  24
code/ponyopoppo_1_1/B.cpp.tk                        |  46
code/ponyopoppo_2_1/C.cpp.tk                        |  55
code/Ragnar_0_1/A.cpp.tk                            |  22
code/Ragnar_1_1/B-2.cpp.tk                          |  85
code/Ragnar_2_1/C.cpp.tk                            |  127
code/saffah_0_1/t.cpp.tk                            |  15
code/saffah_1_1/t.cpp.tk                            |  20
code/saffah_2_1/t.cpp.tk                            |  33
code/SamanSami_0_1/A.cpp.tk                         |  75
code/SamanSami_1_1/B.cpp.tk                         |  489
code/SamanSami_2_1/C.cpp.tk                         |  3
code/Savlik_0_1/code.cpp.tk                         |  55
code/Savlik_1_1/code.cpp.tk                         |  8
code/Savlik_2_1/code.cpp.tk                         |  42
code/shik_0_1/pa.cpp.tk                             |  30
code/shik_1_1/pb.cpp.tk                             |  31
code/shik_2_1/pc.cpp.tk                             |  54
code/simsa.st_0_1/A.cpp.tk                          |  9
code/simsa.st_1_1/B.cpp.tk                          |  17
code/simsa.st_2_1/C.cpp.tk                          |  30
code/SovietUnion_0_1/A.cpp.tk                       |  69
code/SovietUnion_1_1/B.cpp.tk                       |  105
code/SovietUnion_2_1/C.cpp.tk                       |  48
code/tailed_0_1/A.cpp.tk                            |  100
code/tailed_1_1/B.cpp.tk                            |  277
code/tailed_2_1/C.cpp.tk                            |  48
code/TheNatural_0_1/A.cpp.tk                        |  175
code/TheNatural_1_1/B.cpp.tk                        |  204
code/TheNatural_2_1/C.cpp.tk                        |  93
code/TrueBamboo_0_1/test.cpp.tk                     |  43
code/TrueBamboo_1_1/test.cpp.tk                     |  123
code/TrueBamboo_2_1/test.cpp.tk                     |  45
code/tur.turczyn_0_1/A.cpp.tk                       |  22
code/tur.turczyn_1_1/B.cpp.tk                       |  28
code/tur.turczyn_2_1/C.cpp.tk                       |  30
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  25
code/Tyg3R_2_1/C.cpp.tk                             |  22
code/UminchuR_0_1/main.cpp.tk                       |  17
code/UminchuR_1_1/main.cpp.tk                       |  44
code/UminchuR_2_1/main.cpp.tk                       |  47
code/wo..._0_1/a.cpp.tk                             |  107
code/wo..._1_1/b.cpp.tk                             |  125
code/wo..._2_1/c.cpp.tk                             |  142
code/yswtt_0_1/A.cpp.tk                             |  94
code/yswtt_1_1/B.cpp.tk                             |  185
code/yswtt_2_1/C.cpp.tk                             |  129
code/ZhSh_0_1/a.cpp.tk                              |  98
code/ZhSh_1_1/b.cpp.tk                              |  154
code/ZhSh_2_1/c.cpp.tk                              |  99
