Begin
Comparing:  code/Ragnar_1_1/B-2.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  12
code/551100kk_1_1/B.cpp.tk                          |  40
code/551100kk_2_1/C.cpp.tk                          |  39
code/achan1058_0_1/Q-A.cpp.tk                       |  11
code/achan1058_1_1/source.cpp.tk                    |  138
code/achan1058_2_1/source.cpp.tk                    |  147
code/alanubi_0_1/a.cpp.tk                           |  20
code/alanubi_1_1/b.cpp.tk                           |  44
code/alanubi_2_1/c.cpp.tk                           |  107
code/AntiForest_0_1/q1.cpp.tk                       |  19
code/AntiForest_1_1/q2.cpp.tk                       |  10
code/AntiForest_2_1/q3.cpp.tk                       |  50
code/apiad_0_1/A.cpp.tk                             |  23
code/apiad_1_1/B.cpp.tk                             |  36
code/apiad_2_1/C.cpp.tk                             |  31
code/azaky_0_1/A.cpp.tk                             |  22
code/azaky_1_1/B.cpp.tk                             |  34
code/azaky_2_1/C.cpp.tk                             |  56
code/azariamuh_0_1/standing.cpp.tk                  |  13
code/azariamuh_1_1/pancake.cpp.tk                   |  30
code/azariamuh_2_1/dijkstra.cpp.tk                  |  19
code/bmerry_0_1/a.cpp.tk                            |  75
code/bmerry_1_1/b.cpp.tk                            |  114
code/bmerry_2_1/c.cpp.tk                            |  84
code/climpet_0_1/A.cpp.tk                           |  45
code/climpet_1_1/B.cpp.tk                           |  63
code/climpet_2_1/C.cpp.tk                           |  70
code/ctzsm_0_1/A.cpp.tk                             |  14
code/ctzsm_1_1/B.cpp.tk                             |  60
code/ctzsm_2_1/C.cpp.tk                             |  68
code/DanilC_0_1/problem.cpp.tk                      |  32
code/DanilC_1_1/problemB.cpp.tk                     |  56
code/DanilC_2_1/problemC.cpp.tk                     |  115
code/DEGwer_0_1/A.cpp.tk                            |  34
code/DEGwer_1_1/B.cpp.tk                            |  54
code/DEGwer_2_1/C.cpp.tk                            |  42
code/dmute_0_1/a.cpp.tk                             |  11
code/dmute_1_1/b.cpp.tk                             |  21
code/dmute_2_1/c2.cpp.tk                            |  46
code/fagu_0_1/A.cpp.tk                              |  49
code/fagu_1_1/B.cpp.tk                              |  49
code/fagu_2_1/C.cpp.tk                              |  73
code/FatalEagle_0_1/main.cpp.tk                     |  15
code/FatalEagle_1_1/main.cpp.tk                     |  37
code/FatalEagle_2_1/main.cpp.tk                     |  190
code/fullpower_0_1/A.cpp.tk                         |  24
code/fullpower_1_1/B.cpp.tk                         |  41
code/fullpower_2_1/C.cpp.tk                         |  69
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  16
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  35
code/ICastro_2_1/Dijkstra.cpp.tk                    |  93
code/ilackthatsuperpower_0_1/a.cpp.tk               |  94
code/ilackthatsuperpower_1_1/b.cpp.tk               |  101
code/ilackthatsuperpower_2_1/c.cpp.tk               |  121
code/iridescent_0_1/A.cpp.tk                        |  16
code/iridescent_1_1/B.cpp.tk                        |  57
code/iridescent_2_1/C.cpp.tk                        |  31
code/ishraq_0_1/main.cpp.tk                         |  10
code/ishraq_1_1/main.cpp.tk                         |  28
code/ishraq_2_1/main.cpp.tk                         |  61
code/JayXon_0_1/A.cpp.tk                            |  9
code/JayXon_1_1/B.cpp.tk                            |  43
code/JayXon_2_1/C.cpp.tk                            |  31
code/Josse_0_1/A.cpp.tk                             |  28
code/Josse_1_1/B.cpp.tk                             |  49
code/Josse_2_1/C.cpp.tk                             |  111
code/kcm1700_0_1/a.cpp.tk                           |  12
code/kcm1700_1_1/b.cpp.tk                           |  67
code/kcm1700_2_1/c.cpp.tk                           |  67
code/kevinsogo_0_1/a.cpp.tk                         |  15
code/kevinsogo_1_1/b.cpp.tk                         |  28
code/kevinsogo_2_1/c.cpp.tk                         |  54
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  10
code/LazyAnna_0_1/1.cpp.tk                          |  11
code/LazyAnna_1_1/2-1.cpp.tk                        |  22
code/LazyAnna_2_1/3.cpp.tk                          |  33
code/Merkurev_0_1/A.cpp.tk                          |  20
code/Merkurev_1_1/B.cpp.tk                          |  53
code/Merkurev_2_1/C.cpp.tk                          |  46
code/mezei_0_1/main.cpp.tk                          |  21
code/mezei_1_1/main.cpp.tk                          |  36
code/mezei_2_1/main.cpp.tk                          |  69
code/Mister_0_1/a.cpp.tk                            |  13
code/Mister_1_1/b.cpp.tk                            |  22
code/Mister_2_1/c.cpp.tk                            |  28
code/namonakiacc_0_1/cpp.cpp.tk                     |  69
code/namonakiacc_1_1/cpp.cpp.tk                     |  78
code/namonakiacc_2_1/cpp.cpp.tk                     |  90
code/Nicolas16_0_1/main.cpp.tk                      |  7
code/Nicolas16_1_1/main.cpp.tk                      |  7
code/Nicolas16_2_1/main.cpp.tk                      |  62
code/pandamonium_0_1/a.cpp.tk                       |  13
code/pandamonium_1_1/b.cpp.tk                       |  60
code/pandamonium_2_1/c.cpp.tk                       |  28
code/pflueger_0_1/A.cpp.tk                          |  18
code/pflueger_1_1/B.cpp.tk                          |  36
code/pflueger_2_1/C.cpp.tk                          |  70
code/ponyopoppo_0_1/A.cpp.tk                        |  35
code/ponyopoppo_1_1/B.cpp.tk                        |  78
code/ponyopoppo_2_1/C.cpp.tk                        |  117
code/Ragnar_0_1/A.cpp.tk                            |  2415
code/Ragnar_1_1/B-2.cpp.tk                          |  12749
code/Ragnar_2_1/C.cpp.tk                            |  989
code/saffah_0_1/t.cpp.tk                            |  11
code/saffah_1_1/t.cpp.tk                            |  21
code/saffah_2_1/t.cpp.tk                            |  64
code/SamanSami_0_1/A.cpp.tk                         |  9
code/SamanSami_1_1/B.cpp.tk                         |  42
code/SamanSami_2_1/C.cpp.tk                         |  9
code/Savlik_0_1/code.cpp.tk                         |  15
code/Savlik_1_1/code.cpp.tk                         |  20
code/Savlik_2_1/code.cpp.tk                         |  62
code/shik_0_1/pa.cpp.tk                             |  58
code/shik_1_1/pb.cpp.tk                             |  66
code/shik_2_1/pc.cpp.tk                             |  85
code/simsa.st_0_1/A.cpp.tk                          |  12
code/simsa.st_1_1/B.cpp.tk                          |  21
code/simsa.st_2_1/C.cpp.tk                          |  66
code/SovietUnion_0_1/A.cpp.tk                       |  18
code/SovietUnion_1_1/B.cpp.tk                       |  28
code/SovietUnion_2_1/C.cpp.tk                       |  57
code/tailed_0_1/A.cpp.tk                            |  14
code/tailed_1_1/B.cpp.tk                            |  145
code/tailed_2_1/C.cpp.tk                            |  35
code/TheNatural_0_1/A.cpp.tk                        |  18
code/TheNatural_1_1/B.cpp.tk                        |  40
code/TheNatural_2_1/C.cpp.tk                        |  25
code/TrueBamboo_0_1/test.cpp.tk                     |  15
code/TrueBamboo_1_1/test.cpp.tk                     |  58
code/TrueBamboo_2_1/test.cpp.tk                     |  42
code/tur.turczyn_0_1/A.cpp.tk                       |  61
code/tur.turczyn_1_1/B.cpp.tk                       |  89
code/tur.turczyn_2_1/C.cpp.tk                       |  76
code/Tyg3R_0_1/A.cpp.tk                             |  14
code/Tyg3R_1_1/B.cpp.tk                             |  21
code/Tyg3R_2_1/C.cpp.tk                             |  18
code/UminchuR_0_1/main.cpp.tk                       |  63
code/UminchuR_1_1/main.cpp.tk                       |  99
code/UminchuR_2_1/main.cpp.tk                       |  91
code/wo..._0_1/a.cpp.tk                             |  25
code/wo..._1_1/b.cpp.tk                             |  36
code/wo..._2_1/c.cpp.tk                             |  67
code/yswtt_0_1/A.cpp.tk                             |  14
code/yswtt_1_1/B.cpp.tk                             |  42
code/yswtt_2_1/C.cpp.tk                             |  33
code/ZhSh_0_1/a.cpp.tk                              |  17
code/ZhSh_1_1/b.cpp.tk                              |  94
code/ZhSh_2_1/c.cpp.tk                              |  82
