Begin
Comparing:  code/apiad_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  48
code/551100kk_1_1/B.cpp.tk                          |  23
code/551100kk_2_1/C.cpp.tk                          |  38
code/achan1058_0_1/Q-A.cpp.tk                       |  22
code/achan1058_1_1/source.cpp.tk                    |  30
code/achan1058_2_1/source.cpp.tk                    |  50
code/alanubi_0_1/a.cpp.tk                           |  17
code/alanubi_1_1/b.cpp.tk                           |  18
code/alanubi_2_1/c.cpp.tk                           |  87
code/AntiForest_0_1/q1.cpp.tk                       |  38
code/AntiForest_1_1/q2.cpp.tk                       |  12
code/AntiForest_2_1/q3.cpp.tk                       |  51
code/apiad_0_1/A.cpp.tk                             |  9859
code/apiad_1_1/B.cpp.tk                             |  1055
code/apiad_2_1/C.cpp.tk                             |  924
code/azaky_0_1/A.cpp.tk                             |  38
code/azaky_1_1/B.cpp.tk                             |  28
code/azaky_2_1/C.cpp.tk                             |  60
code/azariamuh_0_1/standing.cpp.tk                  |  21
code/azariamuh_1_1/pancake.cpp.tk                   |  30
code/azariamuh_2_1/dijkstra.cpp.tk                  |  19
code/bmerry_0_1/a.cpp.tk                            |  48
code/bmerry_1_1/b.cpp.tk                            |  47
code/bmerry_2_1/c.cpp.tk                            |  52
code/climpet_0_1/A.cpp.tk                           |  32
code/climpet_1_1/B.cpp.tk                           |  32
code/climpet_2_1/C.cpp.tk                           |  49
code/ctzsm_0_1/A.cpp.tk                             |  32
code/ctzsm_1_1/B.cpp.tk                             |  19
code/ctzsm_2_1/C.cpp.tk                             |  65
code/DanilC_0_1/problem.cpp.tk                      |  24
code/DanilC_1_1/problemB.cpp.tk                     |  33
code/DanilC_2_1/problemC.cpp.tk                     |  82
code/DEGwer_0_1/A.cpp.tk                            |  22
code/DEGwer_1_1/B.cpp.tk                            |  22
code/DEGwer_2_1/C.cpp.tk                            |  28
code/dmute_0_1/a.cpp.tk                             |  45
code/dmute_1_1/b.cpp.tk                             |  20
code/dmute_2_1/c2.cpp.tk                            |  41
code/fagu_0_1/A.cpp.tk                              |  21
code/fagu_1_1/B.cpp.tk                              |  18
code/fagu_2_1/C.cpp.tk                              |  38
code/FatalEagle_0_1/main.cpp.tk                     |  27
code/FatalEagle_1_1/main.cpp.tk                     |  21
code/FatalEagle_2_1/main.cpp.tk                     |  102
code/fullpower_0_1/A.cpp.tk                         |  23
code/fullpower_1_1/B.cpp.tk                         |  28
code/fullpower_2_1/C.cpp.tk                         |  58
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  11
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  14
code/ICastro_2_1/Dijkstra.cpp.tk                    |  78
code/ilackthatsuperpower_0_1/a.cpp.tk               |  59
code/ilackthatsuperpower_1_1/b.cpp.tk               |  57
code/ilackthatsuperpower_2_1/c.cpp.tk               |  81
code/iridescent_0_1/A.cpp.tk                        |  11
code/iridescent_1_1/B.cpp.tk                        |  12
code/iridescent_2_1/C.cpp.tk                        |  18
code/ishraq_0_1/main.cpp.tk                         |  59
code/ishraq_1_1/main.cpp.tk                         |  17
code/ishraq_2_1/main.cpp.tk                         |  63
code/JayXon_0_1/A.cpp.tk                            |  13
code/JayXon_1_1/B.cpp.tk                            |  15
code/JayXon_2_1/C.cpp.tk                            |  28
code/Josse_0_1/A.cpp.tk                             |  15
code/Josse_1_1/B.cpp.tk                             |  15
code/Josse_2_1/C.cpp.tk                             |  63
code/kcm1700_0_1/a.cpp.tk                           |  19
code/kcm1700_1_1/b.cpp.tk                           |  17
code/kcm1700_2_1/c.cpp.tk                           |  42
code/kevinsogo_0_1/a.cpp.tk                         |  15
code/kevinsogo_1_1/b.cpp.tk                         |  16
code/kevinsogo_2_1/c.cpp.tk                         |  48
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  8
code/LazyAnna_1_1/2-1.cpp.tk                        |  11
code/LazyAnna_2_1/3.cpp.tk                          |  27
code/Merkurev_0_1/A.cpp.tk                          |  20
code/Merkurev_1_1/B.cpp.tk                          |  28
code/Merkurev_2_1/C.cpp.tk                          |  30
code/mezei_0_1/main.cpp.tk                          |  23
code/mezei_1_1/main.cpp.tk                          |  18
code/mezei_2_1/main.cpp.tk                          |  52
code/Mister_0_1/a.cpp.tk                            |  17
code/Mister_1_1/b.cpp.tk                            |  16
code/Mister_2_1/c.cpp.tk                            |  30
code/namonakiacc_0_1/cpp.cpp.tk                     |  53
code/namonakiacc_1_1/cpp.cpp.tk                     |  44
code/namonakiacc_2_1/cpp.cpp.tk                     |  67
code/Nicolas16_0_1/main.cpp.tk                      |  7
code/Nicolas16_1_1/main.cpp.tk                      |  6
code/Nicolas16_2_1/main.cpp.tk                      |  52
code/pandamonium_0_1/a.cpp.tk                       |  37
code/pandamonium_1_1/b.cpp.tk                       |  28
code/pandamonium_2_1/c.cpp.tk                       |  31
code/pflueger_0_1/A.cpp.tk                          |  9
code/pflueger_1_1/B.cpp.tk                          |  14
code/pflueger_2_1/C.cpp.tk                          |  40
code/ponyopoppo_0_1/A.cpp.tk                        |  14
code/ponyopoppo_1_1/B.cpp.tk                        |  19
code/ponyopoppo_2_1/C.cpp.tk                        |  86
code/Ragnar_0_1/A.cpp.tk                            |  21
code/Ragnar_1_1/B-2.cpp.tk                          |  23
code/Ragnar_2_1/C.cpp.tk                            |  36
code/saffah_0_1/t.cpp.tk                            |  22
code/saffah_1_1/t.cpp.tk                            |  17
code/saffah_2_1/t.cpp.tk                            |  70
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  12
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  12
code/Savlik_1_1/code.cpp.tk                         |  11
code/Savlik_2_1/code.cpp.tk                         |  53
code/shik_0_1/pa.cpp.tk                             |  58
code/shik_1_1/pb.cpp.tk                             |  52
code/shik_2_1/pc.cpp.tk                             |  81
code/simsa.st_0_1/A.cpp.tk                          |  19
code/simsa.st_1_1/B.cpp.tk                          |  15
code/simsa.st_2_1/C.cpp.tk                          |  61
code/SovietUnion_0_1/A.cpp.tk                       |  42
code/SovietUnion_1_1/B.cpp.tk                       |  23
code/SovietUnion_2_1/C.cpp.tk                       |  55
code/tailed_0_1/A.cpp.tk                            |  12
code/tailed_1_1/B.cpp.tk                            |  12
code/tailed_2_1/C.cpp.tk                            |  31
code/TheNatural_0_1/A.cpp.tk                        |  13
code/TheNatural_1_1/B.cpp.tk                        |  14
code/TheNatural_2_1/C.cpp.tk                        |  19
code/TrueBamboo_0_1/test.cpp.tk                     |  20
code/TrueBamboo_1_1/test.cpp.tk                     |  18
code/TrueBamboo_2_1/test.cpp.tk                     |  39
code/tur.turczyn_0_1/A.cpp.tk                       |  29
code/tur.turczyn_1_1/B.cpp.tk                       |  28
code/tur.turczyn_2_1/C.cpp.tk                       |  33
code/Tyg3R_0_1/A.cpp.tk                             |  13
code/Tyg3R_1_1/B.cpp.tk                             |  20
code/Tyg3R_2_1/C.cpp.tk                             |  21
code/UminchuR_0_1/main.cpp.tk                       |  34
code/UminchuR_1_1/main.cpp.tk                       |  36
code/UminchuR_2_1/main.cpp.tk                       |  57
code/wo..._0_1/a.cpp.tk                             |  18
code/wo..._1_1/b.cpp.tk                             |  19
code/wo..._2_1/c.cpp.tk                             |  49
code/yswtt_0_1/A.cpp.tk                             |  10
code/yswtt_1_1/B.cpp.tk                             |  13
code/yswtt_2_1/C.cpp.tk                             |  30
code/ZhSh_0_1/a.cpp.tk                              |  11
code/ZhSh_1_1/b.cpp.tk                              |  50
code/ZhSh_2_1/c.cpp.tk                              |  60
