Begin
Comparing:  code/dmute_1_1/b.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  29
code/551100kk_1_1/B.cpp.tk                          |  48
code/551100kk_2_1/C.cpp.tk                          |  46
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  15
code/achan1058_2_1/source.cpp.tk                    |  33
code/alanubi_0_1/a.cpp.tk                           |  75
code/alanubi_1_1/b.cpp.tk                           |  83
code/alanubi_2_1/c.cpp.tk                           |  133
code/AntiForest_0_1/q1.cpp.tk                       |  27
code/AntiForest_1_1/q2.cpp.tk                       |  8
code/AntiForest_2_1/q3.cpp.tk                       |  50
code/apiad_0_1/A.cpp.tk                             |  18
code/apiad_1_1/B.cpp.tk                             |  18
code/apiad_2_1/C.cpp.tk                             |  28
code/azaky_0_1/A.cpp.tk                             |  16
code/azaky_1_1/B.cpp.tk                             |  23
code/azaky_2_1/C.cpp.tk                             |  40
code/azariamuh_0_1/standing.cpp.tk                  |  16
code/azariamuh_1_1/pancake.cpp.tk                   |  30
code/azariamuh_2_1/dijkstra.cpp.tk                  |  20
code/bmerry_0_1/a.cpp.tk                            |  67
code/bmerry_1_1/b.cpp.tk                            |  60
code/bmerry_2_1/c.cpp.tk                            |  59
code/climpet_0_1/A.cpp.tk                           |  46
code/climpet_1_1/B.cpp.tk                           |  44
code/climpet_2_1/C.cpp.tk                           |  73
code/ctzsm_0_1/A.cpp.tk                             |  54
code/ctzsm_1_1/B.cpp.tk                             |  63
code/ctzsm_2_1/C.cpp.tk                             |  104
code/DanilC_0_1/problem.cpp.tk                      |  59
code/DanilC_1_1/problemB.cpp.tk                     |  69
code/DanilC_2_1/problemC.cpp.tk                     |  85
code/DEGwer_0_1/A.cpp.tk                            |  74
code/DEGwer_1_1/B.cpp.tk                            |  74
code/DEGwer_2_1/C.cpp.tk                            |  41
code/dmute_0_1/a.cpp.tk                             |  114
code/dmute_1_1/b.cpp.tk                             |  12990
code/dmute_2_1/c2.cpp.tk                            |  170
code/fagu_0_1/A.cpp.tk                              |  21
code/fagu_1_1/B.cpp.tk                              |  22
code/fagu_2_1/C.cpp.tk                              |  36
code/FatalEagle_0_1/main.cpp.tk                     |  115
code/FatalEagle_1_1/main.cpp.tk                     |  159
code/FatalEagle_2_1/main.cpp.tk                     |  276
code/fullpower_0_1/A.cpp.tk                         |  149
code/fullpower_1_1/B.cpp.tk                         |  232
code/fullpower_2_1/C.cpp.tk                         |  270
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  31
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  43
code/ICastro_2_1/Dijkstra.cpp.tk                    |  70
code/ilackthatsuperpower_0_1/a.cpp.tk               |  100
code/ilackthatsuperpower_1_1/b.cpp.tk               |  86
code/ilackthatsuperpower_2_1/c.cpp.tk               |  80
code/iridescent_0_1/A.cpp.tk                        |  46
code/iridescent_1_1/B.cpp.tk                        |  125
code/iridescent_2_1/C.cpp.tk                        |  74
code/ishraq_0_1/main.cpp.tk                         |  21
code/ishraq_1_1/main.cpp.tk                         |  51
code/ishraq_2_1/main.cpp.tk                         |  49
code/JayXon_0_1/A.cpp.tk                            |  35
code/JayXon_1_1/B.cpp.tk                            |  60
code/JayXon_2_1/C.cpp.tk                            |  28
code/Josse_0_1/A.cpp.tk                             |  33
code/Josse_1_1/B.cpp.tk                             |  69
code/Josse_2_1/C.cpp.tk                             |  90
code/kcm1700_0_1/a.cpp.tk                           |  148
code/kcm1700_1_1/b.cpp.tk                           |  189
code/kcm1700_2_1/c.cpp.tk                           |  140
code/kevinsogo_0_1/a.cpp.tk                         |  30
code/kevinsogo_1_1/b.cpp.tk                         |  39
code/kevinsogo_2_1/c.cpp.tk                         |  53
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  38
code/LazyAnna_1_1/2-1.cpp.tk                        |  51
code/LazyAnna_2_1/3.cpp.tk                          |  33
code/Merkurev_0_1/A.cpp.tk                          |  151
code/Merkurev_1_1/B.cpp.tk                          |  132
code/Merkurev_2_1/C.cpp.tk                          |  154
code/mezei_0_1/main.cpp.tk                          |  139
code/mezei_1_1/main.cpp.tk                          |  87
code/mezei_2_1/main.cpp.tk                          |  116
code/Mister_0_1/a.cpp.tk                            |  85
code/Mister_1_1/b.cpp.tk                            |  116
code/Mister_2_1/c.cpp.tk                            |  81
code/namonakiacc_0_1/cpp.cpp.tk                     |  22
code/namonakiacc_1_1/cpp.cpp.tk                     |  24
code/namonakiacc_2_1/cpp.cpp.tk                     |  53
code/Nicolas16_0_1/main.cpp.tk                      |  64
code/Nicolas16_1_1/main.cpp.tk                      |  59
code/Nicolas16_2_1/main.cpp.tk                      |  205
code/pandamonium_0_1/a.cpp.tk                       |  117
code/pandamonium_1_1/b.cpp.tk                       |  107
code/pandamonium_2_1/c.cpp.tk                       |  124
code/pflueger_0_1/A.cpp.tk                          |  74
code/pflueger_1_1/B.cpp.tk                          |  81
code/pflueger_2_1/C.cpp.tk                          |  103
code/ponyopoppo_0_1/A.cpp.tk                        |  9
code/ponyopoppo_1_1/B.cpp.tk                        |  14
code/ponyopoppo_2_1/C.cpp.tk                        |  68
code/Ragnar_0_1/A.cpp.tk                            |  11
code/Ragnar_1_1/B-2.cpp.tk                          |  21
code/Ragnar_2_1/C.cpp.tk                            |  52
code/saffah_0_1/t.cpp.tk                            |  28
code/saffah_1_1/t.cpp.tk                            |  30
code/saffah_2_1/t.cpp.tk                            |  45
code/SamanSami_0_1/A.cpp.tk                         |  29
code/SamanSami_1_1/B.cpp.tk                         |  81
code/SamanSami_2_1/C.cpp.tk                         |  5
code/Savlik_0_1/code.cpp.tk                         |  43
code/Savlik_1_1/code.cpp.tk                         |  7
code/Savlik_2_1/code.cpp.tk                         |  40
code/shik_0_1/pa.cpp.tk                             |  34
code/shik_1_1/pb.cpp.tk                             |  33
code/shik_2_1/pc.cpp.tk                             |  61
code/simsa.st_0_1/A.cpp.tk                          |  15
code/simsa.st_1_1/B.cpp.tk                          |  23
code/simsa.st_2_1/C.cpp.tk                          |  48
code/SovietUnion_0_1/A.cpp.tk                       |  68
code/SovietUnion_1_1/B.cpp.tk                       |  88
code/SovietUnion_2_1/C.cpp.tk                       |  48
code/tailed_0_1/A.cpp.tk                            |  41
code/tailed_1_1/B.cpp.tk                            |  67
code/tailed_2_1/C.cpp.tk                            |  38
code/TheNatural_0_1/A.cpp.tk                        |  107
code/TheNatural_1_1/B.cpp.tk                        |  101
code/TheNatural_2_1/C.cpp.tk                        |  50
code/TrueBamboo_0_1/test.cpp.tk                     |  49
code/TrueBamboo_1_1/test.cpp.tk                     |  40
code/TrueBamboo_2_1/test.cpp.tk                     |  48
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  13
code/tur.turczyn_2_1/C.cpp.tk                       |  18
code/Tyg3R_0_1/A.cpp.tk                             |  9
code/Tyg3R_1_1/B.cpp.tk                             |  19
code/Tyg3R_2_1/C.cpp.tk                             |  21
code/UminchuR_0_1/main.cpp.tk                       |  19
code/UminchuR_1_1/main.cpp.tk                       |  26
code/UminchuR_2_1/main.cpp.tk                       |  52
code/wo..._0_1/a.cpp.tk                             |  109
code/wo..._1_1/b.cpp.tk                             |  183
code/wo..._2_1/c.cpp.tk                             |  199
code/yswtt_0_1/A.cpp.tk                             |  37
code/yswtt_1_1/B.cpp.tk                             |  47
code/yswtt_2_1/C.cpp.tk                             |  56
code/ZhSh_0_1/a.cpp.tk                              |  38
code/ZhSh_1_1/b.cpp.tk                              |  85
code/ZhSh_2_1/c.cpp.tk                              |  61
