Begin
Comparing:  code/SamanSami_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  10
code/551100kk_1_1/B.cpp.tk                          |  13
code/551100kk_2_1/C.cpp.tk                          |  36
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  16
code/achan1058_2_1/source.cpp.tk                    |  57
code/alanubi_0_1/a.cpp.tk                           |  6
code/alanubi_1_1/b.cpp.tk                           |  9
code/alanubi_2_1/c.cpp.tk                           |  57
code/AntiForest_0_1/q1.cpp.tk                       |  12
code/AntiForest_1_1/q2.cpp.tk                       |  6
code/AntiForest_2_1/q3.cpp.tk                       |  43
code/apiad_0_1/A.cpp.tk                             |  12
code/apiad_1_1/B.cpp.tk                             |  15
code/apiad_2_1/C.cpp.tk                             |  23
code/azaky_0_1/A.cpp.tk                             |  17
code/azaky_1_1/B.cpp.tk                             |  18
code/azaky_2_1/C.cpp.tk                             |  47
code/azariamuh_0_1/standing.cpp.tk                  |  8
code/azariamuh_1_1/pancake.cpp.tk                   |  16
code/azariamuh_2_1/dijkstra.cpp.tk                  |  37
code/bmerry_0_1/a.cpp.tk                            |  37
code/bmerry_1_1/b.cpp.tk                            |  41
code/bmerry_2_1/c.cpp.tk                            |  44
code/climpet_0_1/A.cpp.tk                           |  17
code/climpet_1_1/B.cpp.tk                           |  20
code/climpet_2_1/C.cpp.tk                           |  34
code/ctzsm_0_1/A.cpp.tk                             |  10
code/ctzsm_1_1/B.cpp.tk                             |  13
code/ctzsm_2_1/C.cpp.tk                             |  62
code/DanilC_0_1/problem.cpp.tk                      |  18
code/DanilC_1_1/problemB.cpp.tk                     |  25
code/DanilC_2_1/problemC.cpp.tk                     |  79
code/DEGwer_0_1/A.cpp.tk                            |  12
code/DEGwer_1_1/B.cpp.tk                            |  11
code/DEGwer_2_1/C.cpp.tk                            |  32
code/dmute_0_1/a.cpp.tk                             |  5
code/dmute_1_1/b.cpp.tk                             |  7
code/dmute_2_1/c2.cpp.tk                            |  47
code/fagu_0_1/A.cpp.tk                              |  5
code/fagu_1_1/B.cpp.tk                              |  5
code/fagu_2_1/C.cpp.tk                              |  28
code/FatalEagle_0_1/main.cpp.tk                     |  10
code/FatalEagle_1_1/main.cpp.tk                     |  12
code/FatalEagle_2_1/main.cpp.tk                     |  98
code/fullpower_0_1/A.cpp.tk                         |  14
code/fullpower_1_1/B.cpp.tk                         |  14
code/fullpower_2_1/C.cpp.tk                         |  68
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  5
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  10
code/ICastro_2_1/Dijkstra.cpp.tk                    |  118
code/ilackthatsuperpower_0_1/a.cpp.tk               |  63
code/ilackthatsuperpower_1_1/b.cpp.tk               |  66
code/ilackthatsuperpower_2_1/c.cpp.tk               |  152
code/iridescent_0_1/A.cpp.tk                        |  4
code/iridescent_1_1/B.cpp.tk                        |  4
code/iridescent_2_1/C.cpp.tk                        |  9
code/ishraq_0_1/main.cpp.tk                         |  6
code/ishraq_1_1/main.cpp.tk                         |  8
code/ishraq_2_1/main.cpp.tk                         |  55
code/JayXon_0_1/A.cpp.tk                            |  4
code/JayXon_1_1/B.cpp.tk                            |  10
code/JayXon_2_1/C.cpp.tk                            |  58
code/Josse_0_1/A.cpp.tk                             |  5
code/Josse_1_1/B.cpp.tk                             |  6
code/Josse_2_1/C.cpp.tk                             |  63
code/kcm1700_0_1/a.cpp.tk                           |  5
code/kcm1700_1_1/b.cpp.tk                           |  7
code/kcm1700_2_1/c.cpp.tk                           |  29
code/kevinsogo_0_1/a.cpp.tk                         |  8
code/kevinsogo_1_1/b.cpp.tk                         |  8
code/kevinsogo_2_1/c.cpp.tk                         |  36
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  23
code/LazyAnna_0_1/1.cpp.tk                          |  4
code/LazyAnna_1_1/2-1.cpp.tk                        |  6
code/LazyAnna_2_1/3.cpp.tk                          |  24
code/Merkurev_0_1/A.cpp.tk                          |  9
code/Merkurev_1_1/B.cpp.tk                          |  20
code/Merkurev_2_1/C.cpp.tk                          |  22
code/mezei_0_1/main.cpp.tk                          |  8
code/mezei_1_1/main.cpp.tk                          |  9
code/mezei_2_1/main.cpp.tk                          |  76
code/Mister_0_1/a.cpp.tk                            |  7
code/Mister_1_1/b.cpp.tk                            |  7
code/Mister_2_1/c.cpp.tk                            |  18
code/namonakiacc_0_1/cpp.cpp.tk                     |  14
code/namonakiacc_1_1/cpp.cpp.tk                     |  16
code/namonakiacc_2_1/cpp.cpp.tk                     |  38
code/Nicolas16_0_1/main.cpp.tk                      |  3
code/Nicolas16_1_1/main.cpp.tk                      |  3
code/Nicolas16_2_1/main.cpp.tk                      |  69
code/pandamonium_0_1/a.cpp.tk                       |  6
code/pandamonium_1_1/b.cpp.tk                       |  21
code/pandamonium_2_1/c.cpp.tk                       |  12
code/pflueger_0_1/A.cpp.tk                          |  4
code/pflueger_1_1/B.cpp.tk                          |  8
code/pflueger_2_1/C.cpp.tk                          |  59
code/ponyopoppo_0_1/A.cpp.tk                        |  8
code/ponyopoppo_1_1/B.cpp.tk                        |  16
code/ponyopoppo_2_1/C.cpp.tk                        |  213
code/Ragnar_0_1/A.cpp.tk                            |  8
code/Ragnar_1_1/B-2.cpp.tk                          |  12
code/Ragnar_2_1/C.cpp.tk                            |  30
code/saffah_0_1/t.cpp.tk                            |  6
code/saffah_1_1/t.cpp.tk                            |  9
code/saffah_2_1/t.cpp.tk                            |  89
code/SamanSami_0_1/A.cpp.tk                         |  2
code/SamanSami_1_1/B.cpp.tk                         |  5
code/SamanSami_2_1/C.cpp.tk                         |  4316
code/Savlik_0_1/code.cpp.tk                         |  7
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  75
code/shik_0_1/pa.cpp.tk                             |  51
code/shik_1_1/pb.cpp.tk                             |  52
code/shik_2_1/pc.cpp.tk                             |  74
code/simsa.st_0_1/A.cpp.tk                          |  8
code/simsa.st_1_1/B.cpp.tk                          |  10
code/simsa.st_2_1/C.cpp.tk                          |  109
code/SovietUnion_0_1/A.cpp.tk                       |  10
code/SovietUnion_1_1/B.cpp.tk                       |  11
code/SovietUnion_2_1/C.cpp.tk                       |  99
code/tailed_0_1/A.cpp.tk                            |  6
code/tailed_1_1/B.cpp.tk                            |  8
code/tailed_2_1/C.cpp.tk                            |  30
code/TheNatural_0_1/A.cpp.tk                        |  4
code/TheNatural_1_1/B.cpp.tk                        |  4
code/TheNatural_2_1/C.cpp.tk                        |  23
code/TrueBamboo_0_1/test.cpp.tk                     |  9
code/TrueBamboo_1_1/test.cpp.tk                     |  12
code/TrueBamboo_2_1/test.cpp.tk                     |  66
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  14
code/tur.turczyn_2_1/C.cpp.tk                       |  22
code/Tyg3R_0_1/A.cpp.tk                             |  8
code/Tyg3R_1_1/B.cpp.tk                             |  13
code/Tyg3R_2_1/C.cpp.tk                             |  14
code/UminchuR_0_1/main.cpp.tk                       |  17
code/UminchuR_1_1/main.cpp.tk                       |  21
code/UminchuR_2_1/main.cpp.tk                       |  40
code/wo..._0_1/a.cpp.tk                             |  8
code/wo..._1_1/b.cpp.tk                             |  8
code/wo..._2_1/c.cpp.tk                             |  44
code/yswtt_0_1/A.cpp.tk                             |  4
code/yswtt_1_1/B.cpp.tk                             |  8
code/yswtt_2_1/C.cpp.tk                             |  36
code/ZhSh_0_1/a.cpp.tk                              |  3
code/ZhSh_1_1/b.cpp.tk                              |  40
code/ZhSh_2_1/c.cpp.tk                              |  81
