Begin
Comparing:  code/551100kk_2_1/C.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  58
code/551100kk_1_1/B.cpp.tk                          |  73
code/551100kk_2_1/C.cpp.tk                          |  46562
code/achan1058_0_1/Q-A.cpp.tk                       |  9
code/achan1058_1_1/source.cpp.tk                    |  18
code/achan1058_2_1/source.cpp.tk                    |  57
code/alanubi_0_1/a.cpp.tk                           |  16
code/alanubi_1_1/b.cpp.tk                           |  30
code/alanubi_2_1/c.cpp.tk                           |  87
code/AntiForest_0_1/q1.cpp.tk                       |  26
code/AntiForest_1_1/q2.cpp.tk                       |  15
code/AntiForest_2_1/q3.cpp.tk                       |  319
code/apiad_0_1/A.cpp.tk                             |  17
code/apiad_1_1/B.cpp.tk                             |  21
code/apiad_2_1/C.cpp.tk                             |  58
code/azaky_0_1/A.cpp.tk                             |  18
code/azaky_1_1/B.cpp.tk                             |  23
code/azaky_2_1/C.cpp.tk                             |  88
code/azariamuh_0_1/standing.cpp.tk                  |  13
code/azariamuh_1_1/pancake.cpp.tk                   |  32
code/azariamuh_2_1/dijkstra.cpp.tk                  |  44
code/bmerry_0_1/a.cpp.tk                            |  44
code/bmerry_1_1/b.cpp.tk                            |  53
code/bmerry_2_1/c.cpp.tk                            |  72
code/climpet_0_1/A.cpp.tk                           |  21
code/climpet_1_1/B.cpp.tk                           |  24
code/climpet_2_1/C.cpp.tk                           |  66
code/ctzsm_0_1/A.cpp.tk                             |  23
code/ctzsm_1_1/B.cpp.tk                             |  26
code/ctzsm_2_1/C.cpp.tk                             |  119
code/DanilC_0_1/problem.cpp.tk                      |  22
code/DanilC_1_1/problemB.cpp.tk                     |  38
code/DanilC_2_1/problemC.cpp.tk                     |  101
code/DEGwer_0_1/A.cpp.tk                            |  23
code/DEGwer_1_1/B.cpp.tk                            |  29
code/DEGwer_2_1/C.cpp.tk                            |  283
code/dmute_0_1/a.cpp.tk                             |  12
code/dmute_1_1/b.cpp.tk                             |  21
code/dmute_2_1/c2.cpp.tk                            |  59
code/fagu_0_1/A.cpp.tk                              |  11
code/fagu_1_1/B.cpp.tk                              |  11
code/fagu_2_1/C.cpp.tk                              |  71
code/FatalEagle_0_1/main.cpp.tk                     |  26
code/FatalEagle_1_1/main.cpp.tk                     |  34
code/FatalEagle_2_1/main.cpp.tk                     |  185
code/fullpower_0_1/A.cpp.tk                         |  31
code/fullpower_1_1/B.cpp.tk                         |  40
code/fullpower_2_1/C.cpp.tk                         |  83
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  7
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  15
code/ICastro_2_1/Dijkstra.cpp.tk                    |  106
code/ilackthatsuperpower_0_1/a.cpp.tk               |  71
code/ilackthatsuperpower_1_1/b.cpp.tk               |  74
code/ilackthatsuperpower_2_1/c.cpp.tk               |  118
code/iridescent_0_1/A.cpp.tk                        |  13
code/iridescent_1_1/B.cpp.tk                        |  11
code/iridescent_2_1/C.cpp.tk                        |  59
code/ishraq_0_1/main.cpp.tk                         |  13
code/ishraq_1_1/main.cpp.tk                         |  15
code/ishraq_2_1/main.cpp.tk                         |  72
code/JayXon_0_1/A.cpp.tk                            |  8
code/JayXon_1_1/B.cpp.tk                            |  22
code/JayXon_2_1/C.cpp.tk                            |  41
code/Josse_0_1/A.cpp.tk                             |  14
code/Josse_1_1/B.cpp.tk                             |  23
code/Josse_2_1/C.cpp.tk                             |  91
code/kcm1700_0_1/a.cpp.tk                           |  13
code/kcm1700_1_1/b.cpp.tk                           |  21
code/kcm1700_2_1/c.cpp.tk                           |  73
code/kevinsogo_0_1/a.cpp.tk                         |  13
code/kevinsogo_1_1/b.cpp.tk                         |  16
code/kevinsogo_2_1/c.cpp.tk                         |  67
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  41
code/LazyAnna_0_1/1.cpp.tk                          |  7
code/LazyAnna_1_1/2-1.cpp.tk                        |  12
code/LazyAnna_2_1/3.cpp.tk                          |  51
code/Merkurev_0_1/A.cpp.tk                          |  29
code/Merkurev_1_1/B.cpp.tk                          |  47
code/Merkurev_2_1/C.cpp.tk                          |  53
code/mezei_0_1/main.cpp.tk                          |  17
code/mezei_1_1/main.cpp.tk                          |  22
code/mezei_2_1/main.cpp.tk                          |  78
code/Mister_0_1/a.cpp.tk                            |  14
code/Mister_1_1/b.cpp.tk                            |  14
code/Mister_2_1/c.cpp.tk                            |  323
code/namonakiacc_0_1/cpp.cpp.tk                     |  16
code/namonakiacc_1_1/cpp.cpp.tk                     |  21
code/namonakiacc_2_1/cpp.cpp.tk                     |  96
code/Nicolas16_0_1/main.cpp.tk                      |  7
code/Nicolas16_1_1/main.cpp.tk                      |  7
code/Nicolas16_2_1/main.cpp.tk                      |  86
code/pandamonium_0_1/a.cpp.tk                       |  14
code/pandamonium_1_1/b.cpp.tk                       |  43
code/pandamonium_2_1/c.cpp.tk                       |  40
code/pflueger_0_1/A.cpp.tk                          |  8
code/pflueger_1_1/B.cpp.tk                          |  18
code/pflueger_2_1/C.cpp.tk                          |  78
code/ponyopoppo_0_1/A.cpp.tk                        |  8
code/ponyopoppo_1_1/B.cpp.tk                        |  19
code/ponyopoppo_2_1/C.cpp.tk                        |  128
code/Ragnar_0_1/A.cpp.tk                            |  11
code/Ragnar_1_1/B-2.cpp.tk                          |  19
code/Ragnar_2_1/C.cpp.tk                            |  43
code/saffah_0_1/t.cpp.tk                            |  13
code/saffah_1_1/t.cpp.tk                            |  16
code/saffah_2_1/t.cpp.tk                            |  84
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  15
code/SamanSami_2_1/C.cpp.tk                         |  12
code/Savlik_0_1/code.cpp.tk                         |  9
code/Savlik_1_1/code.cpp.tk                         |  13
code/Savlik_2_1/code.cpp.tk                         |  56
code/shik_0_1/pa.cpp.tk                             |  51
code/shik_1_1/pb.cpp.tk                             |  52
code/shik_2_1/pc.cpp.tk                             |  304
code/simsa.st_0_1/A.cpp.tk                          |  13
code/simsa.st_1_1/B.cpp.tk                          |  15
code/simsa.st_2_1/C.cpp.tk                          |  78
code/SovietUnion_0_1/A.cpp.tk                       |  25
code/SovietUnion_1_1/B.cpp.tk                       |  30
code/SovietUnion_2_1/C.cpp.tk                       |  80
code/tailed_0_1/A.cpp.tk                            |  7
code/tailed_1_1/B.cpp.tk                            |  12
code/tailed_2_1/C.cpp.tk                            |  58
code/TheNatural_0_1/A.cpp.tk                        |  10
code/TheNatural_1_1/B.cpp.tk                        |  16
code/TheNatural_2_1/C.cpp.tk                        |  42
code/TrueBamboo_0_1/test.cpp.tk                     |  21
code/TrueBamboo_1_1/test.cpp.tk                     |  35
code/TrueBamboo_2_1/test.cpp.tk                     |  65
code/tur.turczyn_0_1/A.cpp.tk                       |  9
code/tur.turczyn_1_1/B.cpp.tk                       |  15
code/tur.turczyn_2_1/C.cpp.tk                       |  42
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  19
code/Tyg3R_2_1/C.cpp.tk                             |  57
code/UminchuR_0_1/main.cpp.tk                       |  28
code/UminchuR_1_1/main.cpp.tk                       |  33
code/UminchuR_2_1/main.cpp.tk                       |  76
code/wo..._0_1/a.cpp.tk                             |  21
code/wo..._1_1/b.cpp.tk                             |  24
code/wo..._2_1/c.cpp.tk                             |  324
code/yswtt_0_1/A.cpp.tk                             |  7
code/yswtt_1_1/B.cpp.tk                             |  15
code/yswtt_2_1/C.cpp.tk                             |  38
code/ZhSh_0_1/a.cpp.tk                              |  6
code/ZhSh_1_1/b.cpp.tk                              |  47
code/ZhSh_2_1/c.cpp.tk                              |  164
