Begin
Comparing:  code/FatalEagle_0_1/main.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  64
code/551100kk_1_1/B.cpp.tk                          |  62
code/551100kk_2_1/C.cpp.tk                          |  66
code/achan1058_0_1/Q-A.cpp.tk                       |  9
code/achan1058_1_1/source.cpp.tk                    |  13
code/achan1058_2_1/source.cpp.tk                    |  29
code/alanubi_0_1/a.cpp.tk                           |  69
code/alanubi_1_1/b.cpp.tk                           |  69
code/alanubi_2_1/c.cpp.tk                           |  101
code/AntiForest_0_1/q1.cpp.tk                       |  46
code/AntiForest_1_1/q2.cpp.tk                       |  29
code/AntiForest_2_1/q3.cpp.tk                       |  67
code/apiad_0_1/A.cpp.tk                             |  27
code/apiad_1_1/B.cpp.tk                             |  21
code/apiad_2_1/C.cpp.tk                             |  30
code/azaky_0_1/A.cpp.tk                             |  32
code/azaky_1_1/B.cpp.tk                             |  30
code/azaky_2_1/C.cpp.tk                             |  51
code/azariamuh_0_1/standing.cpp.tk                  |  25
code/azariamuh_1_1/pancake.cpp.tk                   |  29
code/azariamuh_2_1/dijkstra.cpp.tk                  |  24
code/bmerry_0_1/a.cpp.tk                            |  75
code/bmerry_1_1/b.cpp.tk                            |  50
code/bmerry_2_1/c.cpp.tk                            |  49
code/climpet_0_1/A.cpp.tk                           |  42
code/climpet_1_1/B.cpp.tk                           |  36
code/climpet_2_1/C.cpp.tk                           |  55
code/ctzsm_0_1/A.cpp.tk                             |  141
code/ctzsm_1_1/B.cpp.tk                             |  129
code/ctzsm_2_1/C.cpp.tk                             |  136
code/DanilC_0_1/problem.cpp.tk                      |  46
code/DanilC_1_1/problemB.cpp.tk                     |  52
code/DanilC_2_1/problemC.cpp.tk                     |  73
code/DEGwer_0_1/A.cpp.tk                            |  127
code/DEGwer_1_1/B.cpp.tk                            |  50
code/DEGwer_2_1/C.cpp.tk                            |  39
code/dmute_0_1/a.cpp.tk                             |  118
code/dmute_1_1/b.cpp.tk                             |  138
code/dmute_2_1/c2.cpp.tk                            |  133
code/fagu_0_1/A.cpp.tk                              |  24
code/fagu_1_1/B.cpp.tk                              |  23
code/fagu_2_1/C.cpp.tk                              |  44
code/FatalEagle_0_1/main.cpp.tk                     |  8721
code/FatalEagle_1_1/main.cpp.tk                     |  526
code/FatalEagle_2_1/main.cpp.tk                     |  220
code/fullpower_0_1/A.cpp.tk                         |  154
code/fullpower_1_1/B.cpp.tk                         |  178
code/fullpower_2_1/C.cpp.tk                         |  221
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  26
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  28
code/ICastro_2_1/Dijkstra.cpp.tk                    |  100
code/ilackthatsuperpower_0_1/a.cpp.tk               |  90
code/ilackthatsuperpower_1_1/b.cpp.tk               |  79
code/ilackthatsuperpower_2_1/c.cpp.tk               |  79
code/iridescent_0_1/A.cpp.tk                        |  42
code/iridescent_1_1/B.cpp.tk                        |  79
code/iridescent_2_1/C.cpp.tk                        |  49
code/ishraq_0_1/main.cpp.tk                         |  27
code/ishraq_1_1/main.cpp.tk                         |  29
code/ishraq_2_1/main.cpp.tk                         |  50
code/JayXon_0_1/A.cpp.tk                            |  43
code/JayXon_1_1/B.cpp.tk                            |  42
code/JayXon_2_1/C.cpp.tk                            |  23
code/Josse_0_1/A.cpp.tk                             |  26
code/Josse_1_1/B.cpp.tk                             |  34
code/Josse_2_1/C.cpp.tk                             |  72
code/kcm1700_0_1/a.cpp.tk                           |  121
code/kcm1700_1_1/b.cpp.tk                           |  119
code/kcm1700_2_1/c.cpp.tk                           |  100
code/kevinsogo_0_1/a.cpp.tk                         |  19
code/kevinsogo_1_1/b.cpp.tk                         |  21
code/kevinsogo_2_1/c.cpp.tk                         |  48
code/ksun48_0_1/A.cpp.tk                            |  5
code/ksun48_1_1/B.cpp.tk                            |  5
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  27
code/LazyAnna_1_1/2-1.cpp.tk                        |  32
code/LazyAnna_2_1/3.cpp.tk                          |  27
code/Merkurev_0_1/A.cpp.tk                          |  363
code/Merkurev_1_1/B.cpp.tk                          |  471
code/Merkurev_2_1/C.cpp.tk                          |  362
code/mezei_0_1/main.cpp.tk                          |  155
code/mezei_1_1/main.cpp.tk                          |  68
code/mezei_2_1/main.cpp.tk                          |  110
code/Mister_0_1/a.cpp.tk                            |  51
code/Mister_1_1/b.cpp.tk                            |  63
code/Mister_2_1/c.cpp.tk                            |  72
code/namonakiacc_0_1/cpp.cpp.tk                     |  33
code/namonakiacc_1_1/cpp.cpp.tk                     |  27
code/namonakiacc_2_1/cpp.cpp.tk                     |  43
code/Nicolas16_0_1/main.cpp.tk                      |  65
code/Nicolas16_1_1/main.cpp.tk                      |  60
code/Nicolas16_2_1/main.cpp.tk                      |  176
code/pandamonium_0_1/a.cpp.tk                       |  121
code/pandamonium_1_1/b.cpp.tk                       |  94
code/pandamonium_2_1/c.cpp.tk                       |  97
code/pflueger_0_1/A.cpp.tk                          |  58
code/pflueger_1_1/B.cpp.tk                          |  48
code/pflueger_2_1/C.cpp.tk                          |  78
code/ponyopoppo_0_1/A.cpp.tk                        |  10
code/ponyopoppo_1_1/B.cpp.tk                        |  12
code/ponyopoppo_2_1/C.cpp.tk                        |  65
code/Ragnar_0_1/A.cpp.tk                            |  11
code/Ragnar_1_1/B-2.cpp.tk                          |  17
code/Ragnar_2_1/C.cpp.tk                            |  44
code/saffah_0_1/t.cpp.tk                            |  21
code/saffah_1_1/t.cpp.tk                            |  20
code/saffah_2_1/t.cpp.tk                            |  64
code/SamanSami_0_1/A.cpp.tk                         |  24
code/SamanSami_1_1/B.cpp.tk                         |  49
code/SamanSami_2_1/C.cpp.tk                         |  7
code/Savlik_0_1/code.cpp.tk                         |  36
code/Savlik_1_1/code.cpp.tk                         |  8
code/Savlik_2_1/code.cpp.tk                         |  36
code/shik_0_1/pa.cpp.tk                             |  45
code/shik_1_1/pb.cpp.tk                             |  41
code/shik_2_1/pc.cpp.tk                             |  61
code/simsa.st_0_1/A.cpp.tk                          |  27
code/simsa.st_1_1/B.cpp.tk                          |  21
code/simsa.st_2_1/C.cpp.tk                          |  58
code/SovietUnion_0_1/A.cpp.tk                       |  97
code/SovietUnion_1_1/B.cpp.tk                       |  107
code/SovietUnion_2_1/C.cpp.tk                       |  66
code/tailed_0_1/A.cpp.tk                            |  35
code/tailed_1_1/B.cpp.tk                            |  41
code/tailed_2_1/C.cpp.tk                            |  32
code/TheNatural_0_1/A.cpp.tk                        |  94
code/TheNatural_1_1/B.cpp.tk                        |  72
code/TheNatural_2_1/C.cpp.tk                        |  39
code/TrueBamboo_0_1/test.cpp.tk                     |  49
code/TrueBamboo_1_1/test.cpp.tk                     |  36
code/TrueBamboo_2_1/test.cpp.tk                     |  49
code/tur.turczyn_0_1/A.cpp.tk                       |  14
code/tur.turczyn_1_1/B.cpp.tk                       |  12
code/tur.turczyn_2_1/C.cpp.tk                       |  17
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  14
code/Tyg3R_2_1/C.cpp.tk                             |  17
code/UminchuR_0_1/main.cpp.tk                       |  180
code/UminchuR_1_1/main.cpp.tk                       |  183
code/UminchuR_2_1/main.cpp.tk                       |  97
code/wo..._0_1/a.cpp.tk                             |  106
code/wo..._1_1/b.cpp.tk                             |  102
code/wo..._2_1/c.cpp.tk                             |  134
code/yswtt_0_1/A.cpp.tk                             |  38
code/yswtt_1_1/B.cpp.tk                             |  26
code/yswtt_2_1/C.cpp.tk                             |  37
code/ZhSh_0_1/a.cpp.tk                              |  32
code/ZhSh_1_1/b.cpp.tk                              |  63
code/ZhSh_2_1/c.cpp.tk                              |  57
