Begin
Comparing:  code/TrueBamboo_0_1/test.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  51
code/551100kk_1_1/B.cpp.tk                          |  61
code/551100kk_2_1/C.cpp.tk                          |  59
code/achan1058_0_1/Q-A.cpp.tk                       |  12
code/achan1058_1_1/source.cpp.tk                    |  25
code/achan1058_2_1/source.cpp.tk                    |  51
code/alanubi_0_1/a.cpp.tk                           |  31
code/alanubi_1_1/b.cpp.tk                           |  28
code/alanubi_2_1/c.cpp.tk                           |  91
code/AntiForest_0_1/q1.cpp.tk                       |  27
code/AntiForest_1_1/q2.cpp.tk                       |  12
code/AntiForest_2_1/q3.cpp.tk                       |  56
code/apiad_0_1/A.cpp.tk                             |  27
code/apiad_1_1/B.cpp.tk                             |  25
code/apiad_2_1/C.cpp.tk                             |  31
code/azaky_0_1/A.cpp.tk                             |  27
code/azaky_1_1/B.cpp.tk                             |  25
code/azaky_2_1/C.cpp.tk                             |  56
code/azariamuh_0_1/standing.cpp.tk                  |  16
code/azariamuh_1_1/pancake.cpp.tk                   |  28
code/azariamuh_2_1/dijkstra.cpp.tk                  |  20
code/bmerry_0_1/a.cpp.tk                            |  52
code/bmerry_1_1/b.cpp.tk                            |  51
code/bmerry_2_1/c.cpp.tk                            |  53
code/climpet_0_1/A.cpp.tk                           |  35
code/climpet_1_1/B.cpp.tk                           |  33
code/climpet_2_1/C.cpp.tk                           |  52
code/ctzsm_0_1/A.cpp.tk                             |  28
code/ctzsm_1_1/B.cpp.tk                             |  30
code/ctzsm_2_1/C.cpp.tk                             |  79
code/DanilC_0_1/problem.cpp.tk                      |  34
code/DanilC_1_1/problemB.cpp.tk                     |  38
code/DanilC_2_1/problemC.cpp.tk                     |  112
code/DEGwer_0_1/A.cpp.tk                            |  42
code/DEGwer_1_1/B.cpp.tk                            |  37
code/DEGwer_2_1/C.cpp.tk                            |  38
code/dmute_0_1/a.cpp.tk                             |  59
code/dmute_1_1/b.cpp.tk                             |  67
code/dmute_2_1/c2.cpp.tk                            |  86
code/fagu_0_1/A.cpp.tk                              |  11
code/fagu_1_1/B.cpp.tk                              |  10
code/fagu_2_1/C.cpp.tk                              |  38
code/FatalEagle_0_1/main.cpp.tk                     |  56
code/FatalEagle_1_1/main.cpp.tk                     |  68
code/FatalEagle_2_1/main.cpp.tk                     |  170
code/fullpower_0_1/A.cpp.tk                         |  74
code/fullpower_1_1/B.cpp.tk                         |  101
code/fullpower_2_1/C.cpp.tk                         |  133
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  14
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  17
code/ICastro_2_1/Dijkstra.cpp.tk                    |  119
code/ilackthatsuperpower_0_1/a.cpp.tk               |  86
code/ilackthatsuperpower_1_1/b.cpp.tk               |  86
code/ilackthatsuperpower_2_1/c.cpp.tk               |  101
code/iridescent_0_1/A.cpp.tk                        |  20
code/iridescent_1_1/B.cpp.tk                        |  42
code/iridescent_2_1/C.cpp.tk                        |  32
code/ishraq_0_1/main.cpp.tk                         |  34
code/ishraq_1_1/main.cpp.tk                         |  17
code/ishraq_2_1/main.cpp.tk                         |  62
code/JayXon_0_1/A.cpp.tk                            |  24
code/JayXon_1_1/B.cpp.tk                            |  31
code/JayXon_2_1/C.cpp.tk                            |  34
code/Josse_0_1/A.cpp.tk                             |  21
code/Josse_1_1/B.cpp.tk                             |  24
code/Josse_2_1/C.cpp.tk                             |  88
code/kcm1700_0_1/a.cpp.tk                           |  36
code/kcm1700_1_1/b.cpp.tk                           |  43
code/kcm1700_2_1/c.cpp.tk                           |  70
code/kevinsogo_0_1/a.cpp.tk                         |  17
code/kevinsogo_1_1/b.cpp.tk                         |  20
code/kevinsogo_2_1/c.cpp.tk                         |  55
code/ksun48_0_1/A.cpp.tk                            |  11
code/ksun48_1_1/B.cpp.tk                            |  11
code/ksun48_2_1/C.cpp.tk                            |  19
code/LazyAnna_0_1/1.cpp.tk                          |  15
code/LazyAnna_1_1/2-1.cpp.tk                        |  22
code/LazyAnna_2_1/3.cpp.tk                          |  37
code/Merkurev_0_1/A.cpp.tk                          |  56
code/Merkurev_1_1/B.cpp.tk                          |  61
code/Merkurev_2_1/C.cpp.tk                          |  67
code/mezei_0_1/main.cpp.tk                          |  57
code/mezei_1_1/main.cpp.tk                          |  36
code/mezei_2_1/main.cpp.tk                          |  83
code/Mister_0_1/a.cpp.tk                            |  24
code/Mister_1_1/b.cpp.tk                            |  19
code/Mister_2_1/c.cpp.tk                            |  33
code/namonakiacc_0_1/cpp.cpp.tk                     |  26
code/namonakiacc_1_1/cpp.cpp.tk                     |  27
code/namonakiacc_2_1/cpp.cpp.tk                     |  49
code/Nicolas16_0_1/main.cpp.tk                      |  22
code/Nicolas16_1_1/main.cpp.tk                      |  22
code/Nicolas16_2_1/main.cpp.tk                      |  106
code/pandamonium_0_1/a.cpp.tk                       |  59
code/pandamonium_1_1/b.cpp.tk                       |  52
code/pandamonium_2_1/c.cpp.tk                       |  53
code/pflueger_0_1/A.cpp.tk                          |  40
code/pflueger_1_1/B.cpp.tk                          |  30
code/pflueger_2_1/C.cpp.tk                          |  65
code/ponyopoppo_0_1/A.cpp.tk                        |  15
code/ponyopoppo_1_1/B.cpp.tk                        |  27
code/ponyopoppo_2_1/C.cpp.tk                        |  117
code/Ragnar_0_1/A.cpp.tk                            |  15
code/Ragnar_1_1/B-2.cpp.tk                          |  24
code/Ragnar_2_1/C.cpp.tk                            |  48
code/saffah_0_1/t.cpp.tk                            |  12
code/saffah_1_1/t.cpp.tk                            |  16
code/saffah_2_1/t.cpp.tk                            |  72
code/SamanSami_0_1/A.cpp.tk                         |  14
code/SamanSami_1_1/B.cpp.tk                         |  27
code/SamanSami_2_1/C.cpp.tk                         |  9
code/Savlik_0_1/code.cpp.tk                         |  21
code/Savlik_1_1/code.cpp.tk                         |  15
code/Savlik_2_1/code.cpp.tk                         |  65
code/shik_0_1/pa.cpp.tk                             |  50
code/shik_1_1/pb.cpp.tk                             |  55
code/shik_2_1/pc.cpp.tk                             |  79
code/simsa.st_0_1/A.cpp.tk                          |  22
code/simsa.st_1_1/B.cpp.tk                          |  18
code/simsa.st_2_1/C.cpp.tk                          |  70
code/SovietUnion_0_1/A.cpp.tk                       |  31
code/SovietUnion_1_1/B.cpp.tk                       |  34
code/SovietUnion_2_1/C.cpp.tk                       |  73
code/tailed_0_1/A.cpp.tk                            |  24
code/tailed_1_1/B.cpp.tk                            |  30
code/tailed_2_1/C.cpp.tk                            |  66
code/TheNatural_0_1/A.cpp.tk                        |  47
code/TheNatural_1_1/B.cpp.tk                        |  40
code/TheNatural_2_1/C.cpp.tk                        |  32
code/TrueBamboo_0_1/test.cpp.tk                     |  5785
code/TrueBamboo_1_1/test.cpp.tk                     |  303
code/TrueBamboo_2_1/test.cpp.tk                     |  149
code/tur.turczyn_0_1/A.cpp.tk                       |  17
code/tur.turczyn_1_1/B.cpp.tk                       |  23
code/tur.turczyn_2_1/C.cpp.tk                       |  27
code/Tyg3R_0_1/A.cpp.tk                             |  14
code/Tyg3R_1_1/B.cpp.tk                             |  16
code/Tyg3R_2_1/C.cpp.tk                             |  21
code/UminchuR_0_1/main.cpp.tk                       |  27
code/UminchuR_1_1/main.cpp.tk                       |  37
code/UminchuR_2_1/main.cpp.tk                       |  60
code/wo..._0_1/a.cpp.tk                             |  37
code/wo..._1_1/b.cpp.tk                             |  47
code/wo..._2_1/c.cpp.tk                             |  83
code/yswtt_0_1/A.cpp.tk                             |  13
code/yswtt_1_1/B.cpp.tk                             |  20
code/yswtt_2_1/C.cpp.tk                             |  36
code/ZhSh_0_1/a.cpp.tk                              |  21
code/ZhSh_1_1/b.cpp.tk                              |  58
code/ZhSh_2_1/c.cpp.tk                              |  66
