Begin
Comparing:  code/ICastro_2_1/Dijkstra.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  9
code/551100kk_1_1/B.cpp.tk                          |  12
code/551100kk_2_1/C.cpp.tk                          |  25
code/achan1058_0_1/Q-A.cpp.tk                       |  6
code/achan1058_1_1/source.cpp.tk                    |  12
code/achan1058_2_1/source.cpp.tk                    |  30
code/alanubi_0_1/a.cpp.tk                           |  7
code/alanubi_1_1/b.cpp.tk                           |  10
code/alanubi_2_1/c.cpp.tk                           |  33
code/AntiForest_0_1/q1.cpp.tk                       |  12
code/AntiForest_1_1/q2.cpp.tk                       |  6
code/AntiForest_2_1/q3.cpp.tk                       |  34
code/apiad_0_1/A.cpp.tk                             |  8
code/apiad_1_1/B.cpp.tk                             |  12
code/apiad_2_1/C.cpp.tk                             |  20
code/azaky_0_1/A.cpp.tk                             |  13
code/azaky_1_1/B.cpp.tk                             |  13
code/azaky_2_1/C.cpp.tk                             |  37
code/azariamuh_0_1/standing.cpp.tk                  |  7
code/azariamuh_1_1/pancake.cpp.tk                   |  16
code/azariamuh_2_1/dijkstra.cpp.tk                  |  13
code/bmerry_0_1/a.cpp.tk                            |  28
code/bmerry_1_1/b.cpp.tk                            |  32
code/bmerry_2_1/c.cpp.tk                            |  36
code/climpet_0_1/A.cpp.tk                           |  14
code/climpet_1_1/B.cpp.tk                           |  19
code/climpet_2_1/C.cpp.tk                           |  29
code/ctzsm_0_1/A.cpp.tk                             |  11
code/ctzsm_1_1/B.cpp.tk                             |  15
code/ctzsm_2_1/C.cpp.tk                             |  54
code/DanilC_0_1/problem.cpp.tk                      |  14
code/DanilC_1_1/problemB.cpp.tk                     |  25
code/DanilC_2_1/problemC.cpp.tk                     |  73
code/DEGwer_0_1/A.cpp.tk                            |  11
code/DEGwer_1_1/B.cpp.tk                            |  12
code/DEGwer_2_1/C.cpp.tk                            |  22
code/dmute_0_1/a.cpp.tk                             |  5
code/dmute_1_1/b.cpp.tk                             |  8
code/dmute_2_1/c2.cpp.tk                            |  31
code/fagu_0_1/A.cpp.tk                              |  5
code/fagu_1_1/B.cpp.tk                              |  5
code/fagu_2_1/C.cpp.tk                              |  27
code/FatalEagle_0_1/main.cpp.tk                     |  11
code/FatalEagle_1_1/main.cpp.tk                     |  13
code/FatalEagle_2_1/main.cpp.tk                     |  82
code/fullpower_0_1/A.cpp.tk                         |  15
code/fullpower_1_1/B.cpp.tk                         |  18
code/fullpower_2_1/C.cpp.tk                         |  53
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  19
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  25
code/ICastro_2_1/Dijkstra.cpp.tk                    |  577609
code/ilackthatsuperpower_0_1/a.cpp.tk               |  42
code/ilackthatsuperpower_1_1/b.cpp.tk               |  45
code/ilackthatsuperpower_2_1/c.cpp.tk               |  71
code/iridescent_0_1/A.cpp.tk                        |  5
code/iridescent_1_1/B.cpp.tk                        |  7
code/iridescent_2_1/C.cpp.tk                        |  13
code/ishraq_0_1/main.cpp.tk                         |  6
code/ishraq_1_1/main.cpp.tk                         |  8
code/ishraq_2_1/main.cpp.tk                         |  40
code/JayXon_0_1/A.cpp.tk                            |  4
code/JayXon_1_1/B.cpp.tk                            |  11
code/JayXon_2_1/C.cpp.tk                            |  21
code/Josse_0_1/A.cpp.tk                             |  6
code/Josse_1_1/B.cpp.tk                             |  8
code/Josse_2_1/C.cpp.tk                             |  47
code/kcm1700_0_1/a.cpp.tk                           |  6
code/kcm1700_1_1/b.cpp.tk                           |  8
code/kcm1700_2_1/c.cpp.tk                           |  33
code/kevinsogo_0_1/a.cpp.tk                         |  7
code/kevinsogo_1_1/b.cpp.tk                         |  7
code/kevinsogo_2_1/c.cpp.tk                         |  49
code/ksun48_0_1/A.cpp.tk                            |  2
code/ksun48_1_1/B.cpp.tk                            |  2
code/ksun48_2_1/C.cpp.tk                            |  8
code/LazyAnna_0_1/1.cpp.tk                          |  4
code/LazyAnna_1_1/2-1.cpp.tk                        |  10
code/LazyAnna_2_1/3.cpp.tk                          |  18
code/Merkurev_0_1/A.cpp.tk                          |  11
code/Merkurev_1_1/B.cpp.tk                          |  19
code/Merkurev_2_1/C.cpp.tk                          |  24
code/mezei_0_1/main.cpp.tk                          |  9
code/mezei_1_1/main.cpp.tk                          |  8
code/mezei_2_1/main.cpp.tk                          |  28
code/Mister_0_1/a.cpp.tk                            |  7
code/Mister_1_1/b.cpp.tk                            |  9
code/Mister_2_1/c.cpp.tk                            |  34
code/namonakiacc_0_1/cpp.cpp.tk                     |  11
code/namonakiacc_1_1/cpp.cpp.tk                     |  13
code/namonakiacc_2_1/cpp.cpp.tk                     |  39
code/Nicolas16_0_1/main.cpp.tk                      |  4
code/Nicolas16_1_1/main.cpp.tk                      |  4
code/Nicolas16_2_1/main.cpp.tk                      |  32
code/pandamonium_0_1/a.cpp.tk                       |  6
code/pandamonium_1_1/b.cpp.tk                       |  18
code/pandamonium_2_1/c.cpp.tk                       |  23
code/pflueger_0_1/A.cpp.tk                          |  6
code/pflueger_1_1/B.cpp.tk                          |  9
code/pflueger_2_1/C.cpp.tk                          |  32
code/ponyopoppo_0_1/A.cpp.tk                        |  6
code/ponyopoppo_1_1/B.cpp.tk                        |  11
code/ponyopoppo_2_1/C.cpp.tk                        |  81
code/Ragnar_0_1/A.cpp.tk                            |  7
code/Ragnar_1_1/B-2.cpp.tk                          |  11
code/Ragnar_2_1/C.cpp.tk                            |  23
code/saffah_0_1/t.cpp.tk                            |  5
code/saffah_1_1/t.cpp.tk                            |  8
code/saffah_2_1/t.cpp.tk                            |  271
code/SamanSami_0_1/A.cpp.tk                         |  2
code/SamanSami_1_1/B.cpp.tk                         |  9
code/SamanSami_2_1/C.cpp.tk                         |  9
code/Savlik_0_1/code.cpp.tk                         |  5
code/Savlik_1_1/code.cpp.tk                         |  7
code/Savlik_2_1/code.cpp.tk                         |  33
code/shik_0_1/pa.cpp.tk                             |  28
code/shik_1_1/pb.cpp.tk                             |  29
code/shik_2_1/pc.cpp.tk                             |  49
code/simsa.st_0_1/A.cpp.tk                          |  7
code/simsa.st_1_1/B.cpp.tk                          |  8
code/simsa.st_2_1/C.cpp.tk                          |  52
code/SovietUnion_0_1/A.cpp.tk                       |  11
code/SovietUnion_1_1/B.cpp.tk                       |  12
code/SovietUnion_2_1/C.cpp.tk                       |  45
code/tailed_0_1/A.cpp.tk                            |  4
code/tailed_1_1/B.cpp.tk                            |  6
code/tailed_2_1/C.cpp.tk                            |  20
code/TheNatural_0_1/A.cpp.tk                        |  6
code/TheNatural_1_1/B.cpp.tk                        |  7
code/TheNatural_2_1/C.cpp.tk                        |  12
code/TrueBamboo_0_1/test.cpp.tk                     |  10
code/TrueBamboo_1_1/test.cpp.tk                     |  12
code/TrueBamboo_2_1/test.cpp.tk                     |  33
code/tur.turczyn_0_1/A.cpp.tk                       |  6
code/tur.turczyn_1_1/B.cpp.tk                       |  9
code/tur.turczyn_2_1/C.cpp.tk                       |  13
code/Tyg3R_0_1/A.cpp.tk                             |  7
code/Tyg3R_1_1/B.cpp.tk                             |  10
code/Tyg3R_2_1/C.cpp.tk                             |  19
code/UminchuR_0_1/main.cpp.tk                       |  13
code/UminchuR_1_1/main.cpp.tk                       |  18
code/UminchuR_2_1/main.cpp.tk                       |  40
code/wo..._0_1/a.cpp.tk                             |  9
code/wo..._1_1/b.cpp.tk                             |  9
code/wo..._2_1/c.cpp.tk                             |  34
code/yswtt_0_1/A.cpp.tk                             |  4
code/yswtt_1_1/B.cpp.tk                             |  12
code/yswtt_2_1/C.cpp.tk                             |  19
code/ZhSh_0_1/a.cpp.tk                              |  6
code/ZhSh_1_1/b.cpp.tk                              |  27
code/ZhSh_2_1/c.cpp.tk                              |  51
