Begin
Comparing:  code/Nicolas16_1_1/main.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  31
code/551100kk_1_1/B.cpp.tk                          |  52
code/551100kk_2_1/C.cpp.tk                          |  48
code/achan1058_0_1/Q-A.cpp.tk                       |  8
code/achan1058_1_1/source.cpp.tk                    |  20
code/achan1058_2_1/source.cpp.tk                    |  39
code/alanubi_0_1/a.cpp.tk                           |  76
code/alanubi_1_1/b.cpp.tk                           |  90
code/alanubi_2_1/c.cpp.tk                           |  126
code/AntiForest_0_1/q1.cpp.tk                       |  29
code/AntiForest_1_1/q2.cpp.tk                       |  18
code/AntiForest_2_1/q3.cpp.tk                       |  58
code/apiad_0_1/A.cpp.tk                             |  17
code/apiad_1_1/B.cpp.tk                             |  26
code/apiad_2_1/C.cpp.tk                             |  29
code/azaky_0_1/A.cpp.tk                             |  24
code/azaky_1_1/B.cpp.tk                             |  32
code/azaky_2_1/C.cpp.tk                             |  59
code/azariamuh_0_1/standing.cpp.tk                  |  23
code/azariamuh_1_1/pancake.cpp.tk                   |  34
code/azariamuh_2_1/dijkstra.cpp.tk                  |  30
code/bmerry_0_1/a.cpp.tk                            |  67
code/bmerry_1_1/b.cpp.tk                            |  63
code/bmerry_2_1/c.cpp.tk                            |  58
code/climpet_0_1/A.cpp.tk                           |  45
code/climpet_1_1/B.cpp.tk                           |  49
code/climpet_2_1/C.cpp.tk                           |  63
code/ctzsm_0_1/A.cpp.tk                             |  86
code/ctzsm_1_1/B.cpp.tk                             |  101
code/ctzsm_2_1/C.cpp.tk                             |  124
code/DanilC_0_1/problem.cpp.tk                      |  53
code/DanilC_1_1/problemB.cpp.tk                     |  63
code/DanilC_2_1/problemC.cpp.tk                     |  95
code/DEGwer_0_1/A.cpp.tk                            |  81
code/DEGwer_1_1/B.cpp.tk                            |  66
code/DEGwer_2_1/C.cpp.tk                            |  53
code/dmute_0_1/a.cpp.tk                             |  133
code/dmute_1_1/b.cpp.tk                             |  192
code/dmute_2_1/c2.cpp.tk                            |  205
code/fagu_0_1/A.cpp.tk                              |  44
code/fagu_1_1/B.cpp.tk                              |  46
code/fagu_2_1/C.cpp.tk                              |  65
code/FatalEagle_0_1/main.cpp.tk                     |  160
code/FatalEagle_1_1/main.cpp.tk                     |  197
code/FatalEagle_2_1/main.cpp.tk                     |  292
code/fullpower_0_1/A.cpp.tk                         |  192
code/fullpower_1_1/B.cpp.tk                         |  236
code/fullpower_2_1/C.cpp.tk                         |  281
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  24
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  33
code/ICastro_2_1/Dijkstra.cpp.tk                    |  107
code/ilackthatsuperpower_0_1/a.cpp.tk               |  104
code/ilackthatsuperpower_1_1/b.cpp.tk               |  99
code/ilackthatsuperpower_2_1/c.cpp.tk               |  90
code/iridescent_0_1/A.cpp.tk                        |  49
code/iridescent_1_1/B.cpp.tk                        |  97
code/iridescent_2_1/C.cpp.tk                        |  61
code/ishraq_0_1/main.cpp.tk                         |  31
code/ishraq_1_1/main.cpp.tk                         |  39
code/ishraq_2_1/main.cpp.tk                         |  63
code/JayXon_0_1/A.cpp.tk                            |  39
code/JayXon_1_1/B.cpp.tk                            |  55
code/JayXon_2_1/C.cpp.tk                            |  23
code/Josse_0_1/A.cpp.tk                             |  33
code/Josse_1_1/B.cpp.tk                             |  47
code/Josse_2_1/C.cpp.tk                             |  94
code/kcm1700_0_1/a.cpp.tk                           |  135
code/kcm1700_1_1/b.cpp.tk                           |  181
code/kcm1700_2_1/c.cpp.tk                           |  137
code/kevinsogo_0_1/a.cpp.tk                         |  22
code/kevinsogo_1_1/b.cpp.tk                         |  26
code/kevinsogo_2_1/c.cpp.tk                         |  53
code/ksun48_0_1/A.cpp.tk                            |  4
code/ksun48_1_1/B.cpp.tk                            |  4
code/ksun48_2_1/C.cpp.tk                            |  13
code/LazyAnna_0_1/1.cpp.tk                          |  52
code/LazyAnna_1_1/2-1.cpp.tk                        |  64
code/LazyAnna_2_1/3.cpp.tk                          |  40
code/Merkurev_0_1/A.cpp.tk                          |  198
code/Merkurev_1_1/B.cpp.tk                          |  178
code/Merkurev_2_1/C.cpp.tk                          |  191
code/mezei_0_1/main.cpp.tk                          |  255
code/mezei_1_1/main.cpp.tk                          |  115
code/mezei_2_1/main.cpp.tk                          |  173
code/Mister_0_1/a.cpp.tk                            |  73
code/Mister_1_1/b.cpp.tk                            |  103
code/Mister_2_1/c.cpp.tk                            |  88
code/namonakiacc_0_1/cpp.cpp.tk                     |  31
code/namonakiacc_1_1/cpp.cpp.tk                     |  41
code/namonakiacc_2_1/cpp.cpp.tk                     |  51
code/Nicolas16_0_1/main.cpp.tk                      |  275
code/Nicolas16_1_1/main.cpp.tk                      |  1076
code/Nicolas16_2_1/main.cpp.tk                      |  494
code/pandamonium_0_1/a.cpp.tk                       |  135
code/pandamonium_1_1/b.cpp.tk                       |  157
code/pandamonium_2_1/c.cpp.tk                       |  147
code/pflueger_0_1/A.cpp.tk                          |  77
code/pflueger_1_1/B.cpp.tk                          |  63
code/pflueger_2_1/C.cpp.tk                          |  98
code/ponyopoppo_0_1/A.cpp.tk                        |  14
code/ponyopoppo_1_1/B.cpp.tk                        |  17
code/ponyopoppo_2_1/C.cpp.tk                        |  80
code/Ragnar_0_1/A.cpp.tk                            |  14
code/Ragnar_1_1/B-2.cpp.tk                          |  23
code/Ragnar_2_1/C.cpp.tk                            |  61
code/saffah_0_1/t.cpp.tk                            |  19
code/saffah_1_1/t.cpp.tk                            |  26
code/saffah_2_1/t.cpp.tk                            |  65
code/SamanSami_0_1/A.cpp.tk                         |  34
code/SamanSami_1_1/B.cpp.tk                         |  57
code/SamanSami_2_1/C.cpp.tk                         |  7
code/Savlik_0_1/code.cpp.tk                         |  39
code/Savlik_1_1/code.cpp.tk                         |  13
code/Savlik_2_1/code.cpp.tk                         |  43
code/shik_0_1/pa.cpp.tk                             |  46
code/shik_1_1/pb.cpp.tk                             |  47
code/shik_2_1/pc.cpp.tk                             |  67
code/simsa.st_0_1/A.cpp.tk                          |  21
code/simsa.st_1_1/B.cpp.tk                          |  28
code/simsa.st_2_1/C.cpp.tk                          |  67
code/SovietUnion_0_1/A.cpp.tk                       |  86
code/SovietUnion_1_1/B.cpp.tk                       |  95
code/SovietUnion_2_1/C.cpp.tk                       |  59
code/tailed_0_1/A.cpp.tk                            |  45
code/tailed_1_1/B.cpp.tk                            |  55
code/tailed_2_1/C.cpp.tk                            |  41
code/TheNatural_0_1/A.cpp.tk                        |  107
code/TheNatural_1_1/B.cpp.tk                        |  85
code/TheNatural_2_1/C.cpp.tk                        |  52
code/TrueBamboo_0_1/test.cpp.tk                     |  51
code/TrueBamboo_1_1/test.cpp.tk                     |  41
code/TrueBamboo_2_1/test.cpp.tk                     |  57
code/tur.turczyn_0_1/A.cpp.tk                       |  14
code/tur.turczyn_1_1/B.cpp.tk                       |  21
code/tur.turczyn_2_1/C.cpp.tk                       |  22
code/Tyg3R_0_1/A.cpp.tk                             |  12
code/Tyg3R_1_1/B.cpp.tk                             |  17
code/Tyg3R_2_1/C.cpp.tk                             |  22
code/UminchuR_0_1/main.cpp.tk                       |  28
code/UminchuR_1_1/main.cpp.tk                       |  51
code/UminchuR_2_1/main.cpp.tk                       |  56
code/wo..._0_1/a.cpp.tk                             |  99
code/wo..._1_1/b.cpp.tk                             |  155
code/wo..._2_1/c.cpp.tk                             |  186
code/yswtt_0_1/A.cpp.tk                             |  35
code/yswtt_1_1/B.cpp.tk                             |  38
code/yswtt_2_1/C.cpp.tk                             |  43
code/ZhSh_0_1/a.cpp.tk                              |  37
code/ZhSh_1_1/b.cpp.tk                              |  71
code/ZhSh_2_1/c.cpp.tk                              |  66
