Begin
Comparing:  code/mezei_0_1/main.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  35
code/551100kk_1_1/B.cpp.tk                          |  44
code/551100kk_2_1/C.cpp.tk                          |  40
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  17
code/achan1058_2_1/source.cpp.tk                    |  33
code/alanubi_0_1/a.cpp.tk                           |  84
code/alanubi_1_1/b.cpp.tk                           |  69
code/alanubi_2_1/c.cpp.tk                           |  120
code/AntiForest_0_1/q1.cpp.tk                       |  27
code/AntiForest_1_1/q2.cpp.tk                       |  11
code/AntiForest_2_1/q3.cpp.tk                       |  52
code/apiad_0_1/A.cpp.tk                             |  20
code/apiad_1_1/B.cpp.tk                             |  25
code/apiad_2_1/C.cpp.tk                             |  33
code/azaky_0_1/A.cpp.tk                             |  24
code/azaky_1_1/B.cpp.tk                             |  30
code/azaky_2_1/C.cpp.tk                             |  49
code/azariamuh_0_1/standing.cpp.tk                  |  24
code/azariamuh_1_1/pancake.cpp.tk                   |  34
code/azariamuh_2_1/dijkstra.cpp.tk                  |  22
code/bmerry_0_1/a.cpp.tk                            |  94
code/bmerry_1_1/b.cpp.tk                            |  59
code/bmerry_2_1/c.cpp.tk                            |  57
code/climpet_0_1/A.cpp.tk                           |  51
code/climpet_1_1/B.cpp.tk                           |  44
code/climpet_2_1/C.cpp.tk                           |  65
code/ctzsm_0_1/A.cpp.tk                             |  63
code/ctzsm_1_1/B.cpp.tk                             |  82
code/ctzsm_2_1/C.cpp.tk                             |  109
code/DanilC_0_1/problem.cpp.tk                      |  64
code/DanilC_1_1/problemB.cpp.tk                     |  66
code/DanilC_2_1/problemC.cpp.tk                     |  88
code/DEGwer_0_1/A.cpp.tk                            |  187
code/DEGwer_1_1/B.cpp.tk                            |  142
code/DEGwer_2_1/C.cpp.tk                            |  111
code/dmute_0_1/a.cpp.tk                             |  116
code/dmute_1_1/b.cpp.tk                             |  160
code/dmute_2_1/c2.cpp.tk                            |  155
code/fagu_0_1/A.cpp.tk                              |  32
code/fagu_1_1/B.cpp.tk                              |  33
code/fagu_2_1/C.cpp.tk                              |  51
code/FatalEagle_0_1/main.cpp.tk                     |  147
code/FatalEagle_1_1/main.cpp.tk                     |  170
code/FatalEagle_2_1/main.cpp.tk                     |  256
code/fullpower_0_1/A.cpp.tk                         |  147
code/fullpower_1_1/B.cpp.tk                         |  218
code/fullpower_2_1/C.cpp.tk                         |  247
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  35
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  36
code/ICastro_2_1/Dijkstra.cpp.tk                    |  82
code/ilackthatsuperpower_0_1/a.cpp.tk               |  105
code/ilackthatsuperpower_1_1/b.cpp.tk               |  96
code/ilackthatsuperpower_2_1/c.cpp.tk               |  85
code/iridescent_0_1/A.cpp.tk                        |  49
code/iridescent_1_1/B.cpp.tk                        |  111
code/iridescent_2_1/C.cpp.tk                        |  69
code/ishraq_0_1/main.cpp.tk                         |  17
code/ishraq_1_1/main.cpp.tk                         |  35
code/ishraq_2_1/main.cpp.tk                         |  53
code/JayXon_0_1/A.cpp.tk                            |  46
code/JayXon_1_1/B.cpp.tk                            |  57
code/JayXon_2_1/C.cpp.tk                            |  21
code/Josse_0_1/A.cpp.tk                             |  32
code/Josse_1_1/B.cpp.tk                             |  45
code/Josse_2_1/C.cpp.tk                             |  85
code/kcm1700_0_1/a.cpp.tk                           |  145
code/kcm1700_1_1/b.cpp.tk                           |  152
code/kcm1700_2_1/c.cpp.tk                           |  118
code/kevinsogo_0_1/a.cpp.tk                         |  20
code/kevinsogo_1_1/b.cpp.tk                         |  23
code/kevinsogo_2_1/c.cpp.tk                         |  53
code/ksun48_0_1/A.cpp.tk                            |  6
code/ksun48_1_1/B.cpp.tk                            |  6
code/ksun48_2_1/C.cpp.tk                            |  12
code/LazyAnna_0_1/1.cpp.tk                          |  43
code/LazyAnna_1_1/2-1.cpp.tk                        |  45
code/LazyAnna_2_1/3.cpp.tk                          |  32
code/Merkurev_0_1/A.cpp.tk                          |  180
code/Merkurev_1_1/B.cpp.tk                          |  136
code/Merkurev_2_1/C.cpp.tk                          |  149
code/mezei_0_1/main.cpp.tk                          |  10445
code/mezei_1_1/main.cpp.tk                          |  322
code/mezei_2_1/main.cpp.tk                          |  357
code/Mister_0_1/a.cpp.tk                            |  54
code/Mister_1_1/b.cpp.tk                            |  76
code/Mister_2_1/c.cpp.tk                            |  76
code/namonakiacc_0_1/cpp.cpp.tk                     |  28
code/namonakiacc_1_1/cpp.cpp.tk                     |  30
code/namonakiacc_2_1/cpp.cpp.tk                     |  48
code/Nicolas16_0_1/main.cpp.tk                      |  94
code/Nicolas16_1_1/main.cpp.tk                      |  94
code/Nicolas16_2_1/main.cpp.tk                      |  238
code/pandamonium_0_1/a.cpp.tk                       |  124
code/pandamonium_1_1/b.cpp.tk                       |  129
code/pandamonium_2_1/c.cpp.tk                       |  104
code/pflueger_0_1/A.cpp.tk                          |  90
code/pflueger_1_1/B.cpp.tk                          |  69
code/pflueger_2_1/C.cpp.tk                          |  93
code/ponyopoppo_0_1/A.cpp.tk                        |  11
code/ponyopoppo_1_1/B.cpp.tk                        |  14
code/ponyopoppo_2_1/C.cpp.tk                        |  63
code/Ragnar_0_1/A.cpp.tk                            |  14
code/Ragnar_1_1/B-2.cpp.tk                          |  21
code/Ragnar_2_1/C.cpp.tk                            |  53
code/saffah_0_1/t.cpp.tk                            |  16
code/saffah_1_1/t.cpp.tk                            |  21
code/saffah_2_1/t.cpp.tk                            |  54
code/SamanSami_0_1/A.cpp.tk                         |  32
code/SamanSami_1_1/B.cpp.tk                         |  71
code/SamanSami_2_1/C.cpp.tk                         |  6
code/Savlik_0_1/code.cpp.tk                         |  57
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  40
code/shik_0_1/pa.cpp.tk                             |  42
code/shik_1_1/pb.cpp.tk                             |  39
code/shik_2_1/pc.cpp.tk                             |  64
code/simsa.st_0_1/A.cpp.tk                          |  19
code/simsa.st_1_1/B.cpp.tk                          |  21
code/simsa.st_2_1/C.cpp.tk                          |  49
code/SovietUnion_0_1/A.cpp.tk                       |  75
code/SovietUnion_1_1/B.cpp.tk                       |  89
code/SovietUnion_2_1/C.cpp.tk                       |  50
code/tailed_0_1/A.cpp.tk                            |  42
code/tailed_1_1/B.cpp.tk                            |  53
code/tailed_2_1/C.cpp.tk                            |  35
code/TheNatural_0_1/A.cpp.tk                        |  145
code/TheNatural_1_1/B.cpp.tk                        |  97
code/TheNatural_2_1/C.cpp.tk                        |  49
code/TrueBamboo_0_1/test.cpp.tk                     |  45
code/TrueBamboo_1_1/test.cpp.tk                     |  39
code/TrueBamboo_2_1/test.cpp.tk                     |  48
code/tur.turczyn_0_1/A.cpp.tk                       |  10
code/tur.turczyn_1_1/B.cpp.tk                       |  15
code/tur.turczyn_2_1/C.cpp.tk                       |  18
code/Tyg3R_0_1/A.cpp.tk                             |  12
code/Tyg3R_1_1/B.cpp.tk                             |  16
code/Tyg3R_2_1/C.cpp.tk                             |  22
code/UminchuR_0_1/main.cpp.tk                       |  22
code/UminchuR_1_1/main.cpp.tk                       |  32
code/UminchuR_2_1/main.cpp.tk                       |  51
code/wo..._0_1/a.cpp.tk                             |  178
code/wo..._1_1/b.cpp.tk                             |  120
code/wo..._2_1/c.cpp.tk                             |  152
code/yswtt_0_1/A.cpp.tk                             |  34
code/yswtt_1_1/B.cpp.tk                             |  35
code/yswtt_2_1/C.cpp.tk                             |  47
code/ZhSh_0_1/a.cpp.tk                              |  41
code/ZhSh_1_1/b.cpp.tk                              |  74
code/ZhSh_2_1/c.cpp.tk                              |  61
