Begin
Comparing:  code/yswtt_0_1/A.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  48
code/551100kk_1_1/B.cpp.tk                          |  18
code/551100kk_2_1/C.cpp.tk                          |  27
code/achan1058_0_1/Q-A.cpp.tk                       |  18
code/achan1058_1_1/source.cpp.tk                    |  20
code/achan1058_2_1/source.cpp.tk                    |  32
code/alanubi_0_1/a.cpp.tk                           |  34
code/alanubi_1_1/b.cpp.tk                           |  33
code/alanubi_2_1/c.cpp.tk                           |  103
code/AntiForest_0_1/q1.cpp.tk                       |  41
code/AntiForest_1_1/q2.cpp.tk                       |  3
code/AntiForest_2_1/q3.cpp.tk                       |  32
code/apiad_0_1/A.cpp.tk                             |  17
code/apiad_1_1/B.cpp.tk                             |  12
code/apiad_2_1/C.cpp.tk                             |  19
code/azaky_0_1/A.cpp.tk                             |  44
code/azaky_1_1/B.cpp.tk                             |  13
code/azaky_2_1/C.cpp.tk                             |  30
code/azariamuh_0_1/standing.cpp.tk                  |  16
code/azariamuh_1_1/pancake.cpp.tk                   |  13
code/azariamuh_2_1/dijkstra.cpp.tk                  |  14
code/bmerry_0_1/a.cpp.tk                            |  83
code/bmerry_1_1/b.cpp.tk                            |  68
code/bmerry_2_1/c.cpp.tk                            |  62
code/climpet_0_1/A.cpp.tk                           |  119
code/climpet_1_1/B.cpp.tk                           |  96
code/climpet_2_1/C.cpp.tk                           |  115
code/ctzsm_0_1/A.cpp.tk                             |  160
code/ctzsm_1_1/B.cpp.tk                             |  62
code/ctzsm_2_1/C.cpp.tk                             |  102
code/DanilC_0_1/problem.cpp.tk                      |  126
code/DanilC_1_1/problemB.cpp.tk                     |  103
code/DanilC_2_1/problemC.cpp.tk                     |  105
code/DEGwer_0_1/A.cpp.tk                            |  45
code/DEGwer_1_1/B.cpp.tk                            |  45
code/DEGwer_2_1/C.cpp.tk                            |  30
code/dmute_0_1/a.cpp.tk                             |  55
code/dmute_1_1/b.cpp.tk                             |  67
code/dmute_2_1/c2.cpp.tk                            |  78
code/fagu_0_1/A.cpp.tk                              |  10
code/fagu_1_1/B.cpp.tk                              |  10
code/fagu_2_1/C.cpp.tk                              |  20
code/FatalEagle_0_1/main.cpp.tk                     |  59
code/FatalEagle_1_1/main.cpp.tk                     |  67
code/FatalEagle_2_1/main.cpp.tk                     |  149
code/fullpower_0_1/A.cpp.tk                         |  50
code/fullpower_1_1/B.cpp.tk                         |  90
code/fullpower_2_1/C.cpp.tk                         |  120
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  79
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  69
code/ICastro_2_1/Dijkstra.cpp.tk                    |  63
code/ilackthatsuperpower_0_1/a.cpp.tk               |  112
code/ilackthatsuperpower_1_1/b.cpp.tk               |  76
code/ilackthatsuperpower_2_1/c.cpp.tk               |  80
code/iridescent_0_1/A.cpp.tk                        |  105
code/iridescent_1_1/B.cpp.tk                        |  123
code/iridescent_2_1/C.cpp.tk                        |  87
code/ishraq_0_1/main.cpp.tk                         |  18
code/ishraq_1_1/main.cpp.tk                         |  27
code/ishraq_2_1/main.cpp.tk                         |  29
code/JayXon_0_1/A.cpp.tk                            |  54
code/JayXon_1_1/B.cpp.tk                            |  40
code/JayXon_2_1/C.cpp.tk                            |  22
code/Josse_0_1/A.cpp.tk                             |  39
code/Josse_1_1/B.cpp.tk                             |  58
code/Josse_2_1/C.cpp.tk                             |  74
code/kcm1700_0_1/a.cpp.tk                           |  42
code/kcm1700_1_1/b.cpp.tk                           |  50
code/kcm1700_2_1/c.cpp.tk                           |  70
code/kevinsogo_0_1/a.cpp.tk                         |  41
code/kevinsogo_1_1/b.cpp.tk                         |  15
code/kevinsogo_2_1/c.cpp.tk                         |  27
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  11
code/LazyAnna_0_1/1.cpp.tk                          |  126
code/LazyAnna_1_1/2-1.cpp.tk                        |  112
code/LazyAnna_2_1/3.cpp.tk                          |  74
code/Merkurev_0_1/A.cpp.tk                          |  56
code/Merkurev_1_1/B.cpp.tk                          |  51
code/Merkurev_2_1/C.cpp.tk                          |  63
code/mezei_0_1/main.cpp.tk                          |  59
code/mezei_1_1/main.cpp.tk                          |  43
code/mezei_2_1/main.cpp.tk                          |  62
code/Mister_0_1/a.cpp.tk                            |  88
code/Mister_1_1/b.cpp.tk                            |  70
code/Mister_2_1/c.cpp.tk                            |  109
code/namonakiacc_0_1/cpp.cpp.tk                     |  18
code/namonakiacc_1_1/cpp.cpp.tk                     |  17
code/namonakiacc_2_1/cpp.cpp.tk                     |  29
code/Nicolas16_0_1/main.cpp.tk                      |  20
code/Nicolas16_1_1/main.cpp.tk                      |  20
code/Nicolas16_2_1/main.cpp.tk                      |  100
code/pandamonium_0_1/a.cpp.tk                       |  55
code/pandamonium_1_1/b.cpp.tk                       |  48
code/pandamonium_2_1/c.cpp.tk                       |  53
code/pflueger_0_1/A.cpp.tk                          |  103
code/pflueger_1_1/B.cpp.tk                          |  91
code/pflueger_2_1/C.cpp.tk                          |  89
code/ponyopoppo_0_1/A.cpp.tk                        |  46
code/ponyopoppo_1_1/B.cpp.tk                        |  24
code/ponyopoppo_2_1/C.cpp.tk                        |  58
code/Ragnar_0_1/A.cpp.tk                            |  45
code/Ragnar_1_1/B-2.cpp.tk                          |  28
code/Ragnar_2_1/C.cpp.tk                            |  76
code/saffah_0_1/t.cpp.tk                            |  35
code/saffah_1_1/t.cpp.tk                            |  11
code/saffah_2_1/t.cpp.tk                            |  33
code/SamanSami_0_1/A.cpp.tk                         |  32
code/SamanSami_1_1/B.cpp.tk                         |  79
code/SamanSami_2_1/C.cpp.tk                         |  4
code/Savlik_0_1/code.cpp.tk                         |  65
code/Savlik_1_1/code.cpp.tk                         |  7
code/Savlik_2_1/code.cpp.tk                         |  34
code/shik_0_1/pa.cpp.tk                             |  65
code/shik_1_1/pb.cpp.tk                             |  29
code/shik_2_1/pc.cpp.tk                             |  48
code/simsa.st_0_1/A.cpp.tk                          |  8
code/simsa.st_1_1/B.cpp.tk                          |  10
code/simsa.st_2_1/C.cpp.tk                          |  28
code/SovietUnion_0_1/A.cpp.tk                       |  137
code/SovietUnion_1_1/B.cpp.tk                       |  195
code/SovietUnion_2_1/C.cpp.tk                       |  81
code/tailed_0_1/A.cpp.tk                            |  91
code/tailed_1_1/B.cpp.tk                            |  70
code/tailed_2_1/C.cpp.tk                            |  38
code/TheNatural_0_1/A.cpp.tk                        |  104
code/TheNatural_1_1/B.cpp.tk                        |  75
code/TheNatural_2_1/C.cpp.tk                        |  45
code/TrueBamboo_0_1/test.cpp.tk                     |  18
code/TrueBamboo_1_1/test.cpp.tk                     |  23
code/TrueBamboo_2_1/test.cpp.tk                     |  30
code/tur.turczyn_0_1/A.cpp.tk                       |  26
code/tur.turczyn_1_1/B.cpp.tk                       |  27
code/tur.turczyn_2_1/C.cpp.tk                       |  32
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  11
code/Tyg3R_2_1/C.cpp.tk                             |  19
code/UminchuR_0_1/main.cpp.tk                       |  23
code/UminchuR_1_1/main.cpp.tk                       |  18
code/UminchuR_2_1/main.cpp.tk                       |  35
code/wo..._0_1/a.cpp.tk                             |  46
code/wo..._1_1/b.cpp.tk                             |  51
code/wo..._2_1/c.cpp.tk                             |  79
code/yswtt_0_1/A.cpp.tk                             |  3463
code/yswtt_1_1/B.cpp.tk                             |  149
code/yswtt_2_1/C.cpp.tk                             |  136
code/ZhSh_0_1/a.cpp.tk                              |  278
code/ZhSh_1_1/b.cpp.tk                              |  215
code/ZhSh_2_1/c.cpp.tk                              |  132
