Begin
Comparing:  code/UminchuR_1_1/main.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  30
code/551100kk_1_1/B.cpp.tk                          |  63
code/551100kk_2_1/C.cpp.tk                          |  52
code/achan1058_0_1/Q-A.cpp.tk                       |  10
code/achan1058_1_1/source.cpp.tk                    |  87
code/achan1058_2_1/source.cpp.tk                    |  111
code/alanubi_0_1/a.cpp.tk                           |  21
code/alanubi_1_1/b.cpp.tk                           |  34
code/alanubi_2_1/c.cpp.tk                           |  85
code/AntiForest_0_1/q1.cpp.tk                       |  38
code/AntiForest_1_1/q2.cpp.tk                       |  27
code/AntiForest_2_1/q3.cpp.tk                       |  71
code/apiad_0_1/A.cpp.tk                             |  24
code/apiad_1_1/B.cpp.tk                             |  43
code/apiad_2_1/C.cpp.tk                             |  34
code/azaky_0_1/A.cpp.tk                             |  31
code/azaky_1_1/B.cpp.tk                             |  47
code/azaky_2_1/C.cpp.tk                             |  73
code/azariamuh_0_1/standing.cpp.tk                  |  19
code/azariamuh_1_1/pancake.cpp.tk                   |  36
code/azariamuh_2_1/dijkstra.cpp.tk                  |  27
code/bmerry_0_1/a.cpp.tk                            |  62
code/bmerry_1_1/b.cpp.tk                            |  91
code/bmerry_2_1/c.cpp.tk                            |  69
code/climpet_0_1/A.cpp.tk                           |  39
code/climpet_1_1/B.cpp.tk                           |  48
code/climpet_2_1/C.cpp.tk                           |  60
code/ctzsm_0_1/A.cpp.tk                             |  56
code/ctzsm_1_1/B.cpp.tk                             |  87
code/ctzsm_2_1/C.cpp.tk                             |  92
code/DanilC_0_1/problem.cpp.tk                      |  27
code/DanilC_1_1/problemB.cpp.tk                     |  42
code/DanilC_2_1/problemC.cpp.tk                     |  113
code/DEGwer_0_1/A.cpp.tk                            |  26
code/DEGwer_1_1/B.cpp.tk                            |  33
code/DEGwer_2_1/C.cpp.tk                            |  30
code/dmute_0_1/a.cpp.tk                             |  11
code/dmute_1_1/b.cpp.tk                             |  20
code/dmute_2_1/c2.cpp.tk                            |  41
code/fagu_0_1/A.cpp.tk                              |  23
code/fagu_1_1/B.cpp.tk                              |  23
code/fagu_2_1/C.cpp.tk                              |  52
code/FatalEagle_0_1/main.cpp.tk                     |  105
code/FatalEagle_1_1/main.cpp.tk                     |  113
code/FatalEagle_2_1/main.cpp.tk                     |  140
code/fullpower_0_1/A.cpp.tk                         |  42
code/fullpower_1_1/B.cpp.tk                         |  42
code/fullpower_2_1/C.cpp.tk                         |  77
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  10
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  21
code/ICastro_2_1/Dijkstra.cpp.tk                    |  110
code/ilackthatsuperpower_0_1/a.cpp.tk               |  84
code/ilackthatsuperpower_1_1/b.cpp.tk               |  91
code/ilackthatsuperpower_2_1/c.cpp.tk               |  117
code/iridescent_0_1/A.cpp.tk                        |  8
code/iridescent_1_1/B.cpp.tk                        |  23
code/iridescent_2_1/C.cpp.tk                        |  13
code/ishraq_0_1/main.cpp.tk                         |  20
code/ishraq_1_1/main.cpp.tk                         |  28
code/ishraq_2_1/main.cpp.tk                         |  78
code/JayXon_0_1/A.cpp.tk                            |  6
code/JayXon_1_1/B.cpp.tk                            |  20
code/JayXon_2_1/C.cpp.tk                            |  33
code/Josse_0_1/A.cpp.tk                             |  11
code/Josse_1_1/B.cpp.tk                             |  18
code/Josse_2_1/C.cpp.tk                             |  81
code/kcm1700_0_1/a.cpp.tk                           |  17
code/kcm1700_1_1/b.cpp.tk                           |  35
code/kcm1700_2_1/c.cpp.tk                           |  50
code/kevinsogo_0_1/a.cpp.tk                         |  25
code/kevinsogo_1_1/b.cpp.tk                         |  36
code/kevinsogo_2_1/c.cpp.tk                         |  68
code/ksun48_0_1/A.cpp.tk                            |  6
code/ksun48_1_1/B.cpp.tk                            |  6
code/ksun48_2_1/C.cpp.tk                            |  13
code/LazyAnna_0_1/1.cpp.tk                          |  7
code/LazyAnna_1_1/2-1.cpp.tk                        |  13
code/LazyAnna_2_1/3.cpp.tk                          |  32
code/Merkurev_0_1/A.cpp.tk                          |  72
code/Merkurev_1_1/B.cpp.tk                          |  143
code/Merkurev_2_1/C.cpp.tk                          |  92
code/mezei_0_1/main.cpp.tk                          |  21
code/mezei_1_1/main.cpp.tk                          |  21
code/mezei_2_1/main.cpp.tk                          |  57
code/Mister_0_1/a.cpp.tk                            |  15
code/Mister_1_1/b.cpp.tk                            |  23
code/Mister_2_1/c.cpp.tk                            |  30
code/namonakiacc_0_1/cpp.cpp.tk                     |  80
code/namonakiacc_1_1/cpp.cpp.tk                     |  104
code/namonakiacc_2_1/cpp.cpp.tk                     |  110
code/Nicolas16_0_1/main.cpp.tk                      |  10
code/Nicolas16_1_1/main.cpp.tk                      |  12
code/Nicolas16_2_1/main.cpp.tk                      |  59
code/pandamonium_0_1/a.cpp.tk                       |  12
code/pandamonium_1_1/b.cpp.tk                       |  38
code/pandamonium_2_1/c.cpp.tk                       |  20
code/pflueger_0_1/A.cpp.tk                          |  9
code/pflueger_1_1/B.cpp.tk                          |  15
code/pflueger_2_1/C.cpp.tk                          |  45
code/ponyopoppo_0_1/A.cpp.tk                        |  16
code/ponyopoppo_1_1/B.cpp.tk                        |  69
code/ponyopoppo_2_1/C.cpp.tk                        |  126
code/Ragnar_0_1/A.cpp.tk                            |  42
code/Ragnar_1_1/B-2.cpp.tk                          |  72
code/Ragnar_2_1/C.cpp.tk                            |  65
code/saffah_0_1/t.cpp.tk                            |  19
code/saffah_1_1/t.cpp.tk                            |  36
code/saffah_2_1/t.cpp.tk                            |  86
code/SamanSami_0_1/A.cpp.tk                         |  3
code/SamanSami_1_1/B.cpp.tk                         |  13
code/SamanSami_2_1/C.cpp.tk                         |  11
code/Savlik_0_1/code.cpp.tk                         |  13
code/Savlik_1_1/code.cpp.tk                         |  22
code/Savlik_2_1/code.cpp.tk                         |  66
code/shik_0_1/pa.cpp.tk                             |  71
code/shik_1_1/pb.cpp.tk                             |  82
code/shik_2_1/pc.cpp.tk                             |  96
code/simsa.st_0_1/A.cpp.tk                          |  18
code/simsa.st_1_1/B.cpp.tk                          |  45
code/simsa.st_2_1/C.cpp.tk                          |  87
code/SovietUnion_0_1/A.cpp.tk                       |  28
code/SovietUnion_1_1/B.cpp.tk                       |  37
code/SovietUnion_2_1/C.cpp.tk                       |  73
code/tailed_0_1/A.cpp.tk                            |  12
code/tailed_1_1/B.cpp.tk                            |  37
code/tailed_2_1/C.cpp.tk                            |  33
code/TheNatural_0_1/A.cpp.tk                        |  9
code/TheNatural_1_1/B.cpp.tk                        |  16
code/TheNatural_2_1/C.cpp.tk                        |  19
code/TrueBamboo_0_1/test.cpp.tk                     |  18
code/TrueBamboo_1_1/test.cpp.tk                     |  45
code/TrueBamboo_2_1/test.cpp.tk                     |  46
code/tur.turczyn_0_1/A.cpp.tk                       |  43
code/tur.turczyn_1_1/B.cpp.tk                       |  56
code/tur.turczyn_2_1/C.cpp.tk                       |  56
code/Tyg3R_0_1/A.cpp.tk                             |  13
code/Tyg3R_1_1/B.cpp.tk                             |  20
code/Tyg3R_2_1/C.cpp.tk                             |  19
code/UminchuR_0_1/main.cpp.tk                       |  2409
code/UminchuR_1_1/main.cpp.tk                       |  20100
code/UminchuR_2_1/main.cpp.tk                       |  1995
code/wo..._0_1/a.cpp.tk                             |  19
code/wo..._1_1/b.cpp.tk                             |  24
code/wo..._2_1/c.cpp.tk                             |  55
code/yswtt_0_1/A.cpp.tk                             |  7
code/yswtt_1_1/B.cpp.tk                             |  36
code/yswtt_2_1/C.cpp.tk                             |  26
code/ZhSh_0_1/a.cpp.tk                              |  8
code/ZhSh_1_1/b.cpp.tk                              |  78
code/ZhSh_2_1/c.cpp.tk                              |  83
