Begin
Comparing:  code/kcm1700_2_1/c.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  14
code/551100kk_1_1/B.cpp.tk                          |  25
code/551100kk_2_1/C.cpp.tk                          |  58
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  20
code/achan1058_2_1/source.cpp.tk                    |  42
code/alanubi_0_1/a.cpp.tk                           |  34
code/alanubi_1_1/b.cpp.tk                           |  47
code/alanubi_2_1/c.cpp.tk                           |  125
code/AntiForest_0_1/q1.cpp.tk                       |  17
code/AntiForest_1_1/q2.cpp.tk                       |  7
code/AntiForest_2_1/q3.cpp.tk                       |  65
code/apiad_0_1/A.cpp.tk                             |  13
code/apiad_1_1/B.cpp.tk                             |  21
code/apiad_2_1/C.cpp.tk                             |  48
code/azaky_0_1/A.cpp.tk                             |  16
code/azaky_1_1/B.cpp.tk                             |  21
code/azaky_2_1/C.cpp.tk                             |  64
code/azariamuh_0_1/standing.cpp.tk                  |  13
code/azariamuh_1_1/pancake.cpp.tk                   |  41
code/azariamuh_2_1/dijkstra.cpp.tk                  |  28
code/bmerry_0_1/a.cpp.tk                            |  43
code/bmerry_1_1/b.cpp.tk                            |  57
code/bmerry_2_1/c.cpp.tk                            |  100
code/climpet_0_1/A.cpp.tk                           |  25
code/climpet_1_1/B.cpp.tk                           |  32
code/climpet_2_1/C.cpp.tk                           |  76
code/ctzsm_0_1/A.cpp.tk                             |  23
code/ctzsm_1_1/B.cpp.tk                             |  33
code/ctzsm_2_1/C.cpp.tk                             |  107
code/DanilC_0_1/problem.cpp.tk                      |  31
code/DanilC_1_1/problemB.cpp.tk                     |  53
code/DanilC_2_1/problemC.cpp.tk                     |  85
code/DEGwer_0_1/A.cpp.tk                            |  34
code/DEGwer_1_1/B.cpp.tk                            |  41
code/DEGwer_2_1/C.cpp.tk                            |  49
code/dmute_0_1/a.cpp.tk                             |  21
code/dmute_1_1/b.cpp.tk                             |  47
code/dmute_2_1/c2.cpp.tk                            |  108
code/fagu_0_1/A.cpp.tk                              |  12
code/fagu_1_1/B.cpp.tk                              |  13
code/fagu_2_1/C.cpp.tk                              |  68
code/FatalEagle_0_1/main.cpp.tk                     |  28
code/FatalEagle_1_1/main.cpp.tk                     |  50
code/FatalEagle_2_1/main.cpp.tk                     |  250
code/fullpower_0_1/A.cpp.tk                         |  39
code/fullpower_1_1/B.cpp.tk                         |  74
code/fullpower_2_1/C.cpp.tk                         |  147
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  14
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  25
code/ICastro_2_1/Dijkstra.cpp.tk                    |  97
code/ilackthatsuperpower_0_1/a.cpp.tk               |  70
code/ilackthatsuperpower_1_1/b.cpp.tk               |  72
code/ilackthatsuperpower_2_1/c.cpp.tk               |  89
code/iridescent_0_1/A.cpp.tk                        |  17
code/iridescent_1_1/B.cpp.tk                        |  34
code/iridescent_2_1/C.cpp.tk                        |  57
code/ishraq_0_1/main.cpp.tk                         |  12
code/ishraq_1_1/main.cpp.tk                         |  24
code/ishraq_2_1/main.cpp.tk                         |  67
code/JayXon_0_1/A.cpp.tk                            |  12
code/JayXon_1_1/B.cpp.tk                            |  43
code/JayXon_2_1/C.cpp.tk                            |  26
code/Josse_0_1/A.cpp.tk                             |  20
code/Josse_1_1/B.cpp.tk                             |  38
code/Josse_2_1/C.cpp.tk                             |  88
code/kcm1700_0_1/a.cpp.tk                           |  30
code/kcm1700_1_1/b.cpp.tk                           |  47
code/kcm1700_2_1/c.cpp.tk                           |  97056
code/kevinsogo_0_1/a.cpp.tk                         |  15
code/kevinsogo_1_1/b.cpp.tk                         |  18
code/kevinsogo_2_1/c.cpp.tk                         |  93
code/ksun48_0_1/A.cpp.tk                            |  1
code/ksun48_1_1/B.cpp.tk                            |  1
code/ksun48_2_1/C.cpp.tk                            |  21
code/LazyAnna_0_1/1.cpp.tk                          |  14
code/LazyAnna_1_1/2-1.cpp.tk                        |  25
code/LazyAnna_2_1/3.cpp.tk                          |  40
code/Merkurev_0_1/A.cpp.tk                          |  39
code/Merkurev_1_1/B.cpp.tk                          |  53
code/Merkurev_2_1/C.cpp.tk                          |  97
code/mezei_0_1/main.cpp.tk                          |  35
code/mezei_1_1/main.cpp.tk                          |  38
code/mezei_2_1/main.cpp.tk                          |  70
code/Mister_0_1/a.cpp.tk                            |  25
code/Mister_1_1/b.cpp.tk                            |  37
code/Mister_2_1/c.cpp.tk                            |  60
code/namonakiacc_0_1/cpp.cpp.tk                     |  15
code/namonakiacc_1_1/cpp.cpp.tk                     |  19
code/namonakiacc_2_1/cpp.cpp.tk                     |  89
code/Nicolas16_0_1/main.cpp.tk                      |  15
code/Nicolas16_1_1/main.cpp.tk                      |  14
code/Nicolas16_2_1/main.cpp.tk                      |  93
code/pandamonium_0_1/a.cpp.tk                       |  25
code/pandamonium_1_1/b.cpp.tk                       |  69
code/pandamonium_2_1/c.cpp.tk                       |  72
code/pflueger_0_1/A.cpp.tk                          |  19
code/pflueger_1_1/B.cpp.tk                          |  37
code/pflueger_2_1/C.cpp.tk                          |  93
code/ponyopoppo_0_1/A.cpp.tk                        |  8
code/ponyopoppo_1_1/B.cpp.tk                        |  17
code/ponyopoppo_2_1/C.cpp.tk                        |  82
code/Ragnar_0_1/A.cpp.tk                            |  9
code/Ragnar_1_1/B-2.cpp.tk                          |  22
code/Ragnar_2_1/C.cpp.tk                            |  41
code/saffah_0_1/t.cpp.tk                            |  13
code/saffah_1_1/t.cpp.tk                            |  18
code/saffah_2_1/t.cpp.tk                            |  59
code/SamanSami_0_1/A.cpp.tk                         |  7
code/SamanSami_1_1/B.cpp.tk                         |  33
code/SamanSami_2_1/C.cpp.tk                         |  7
code/Savlik_0_1/code.cpp.tk                         |  13
code/Savlik_1_1/code.cpp.tk                         |  11
code/Savlik_2_1/code.cpp.tk                         |  42
code/shik_0_1/pa.cpp.tk                             |  39
code/shik_1_1/pb.cpp.tk                             |  41
code/shik_2_1/pc.cpp.tk                             |  82
code/simsa.st_0_1/A.cpp.tk                          |  11
code/simsa.st_1_1/B.cpp.tk                          |  16
code/simsa.st_2_1/C.cpp.tk                          |  58
code/SovietUnion_0_1/A.cpp.tk                       |  27
code/SovietUnion_1_1/B.cpp.tk                       |  34
code/SovietUnion_2_1/C.cpp.tk                       |  45
code/tailed_0_1/A.cpp.tk                            |  13
code/tailed_1_1/B.cpp.tk                            |  24
code/tailed_2_1/C.cpp.tk                            |  34
code/TheNatural_0_1/A.cpp.tk                        |  26
code/TheNatural_1_1/B.cpp.tk                        |  33
code/TheNatural_2_1/C.cpp.tk                        |  38
code/TrueBamboo_0_1/test.cpp.tk                     |  16
code/TrueBamboo_1_1/test.cpp.tk                     |  22
code/TrueBamboo_2_1/test.cpp.tk                     |  38
code/tur.turczyn_0_1/A.cpp.tk                       |  8
code/tur.turczyn_1_1/B.cpp.tk                       |  14
code/tur.turczyn_2_1/C.cpp.tk                       |  25
code/Tyg3R_0_1/A.cpp.tk                             |  11
code/Tyg3R_1_1/B.cpp.tk                             |  18
code/Tyg3R_2_1/C.cpp.tk                             |  42
code/UminchuR_0_1/main.cpp.tk                       |  15
code/UminchuR_1_1/main.cpp.tk                       |  23
code/UminchuR_2_1/main.cpp.tk                       |  82
code/wo..._0_1/a.cpp.tk                             |  47
code/wo..._1_1/b.cpp.tk                             |  53
code/wo..._2_1/c.cpp.tk                             |  110
code/yswtt_0_1/A.cpp.tk                             |  12
code/yswtt_1_1/B.cpp.tk                             |  26
code/yswtt_2_1/C.cpp.tk                             |  36
code/ZhSh_0_1/a.cpp.tk                              |  14
code/ZhSh_1_1/b.cpp.tk                              |  57
code/ZhSh_2_1/c.cpp.tk                              |  202
