Begin
Comparing:  code/alanubi_2_1/c.cpp.tk
code/551100kk_0_1/A.cpp.tk                          |  11
code/551100kk_1_1/B.cpp.tk                          |  24
code/551100kk_2_1/C.cpp.tk                          |  41
code/achan1058_0_1/Q-A.cpp.tk                       |  7
code/achan1058_1_1/source.cpp.tk                    |  23
code/achan1058_2_1/source.cpp.tk                    |  43
code/alanubi_0_1/a.cpp.tk                           |  35
code/alanubi_1_1/b.cpp.tk                           |  60
code/alanubi_2_1/c.cpp.tk                           |  213328
code/AntiForest_0_1/q1.cpp.tk                       |  11
code/AntiForest_1_1/q2.cpp.tk                       |  5
code/AntiForest_2_1/q3.cpp.tk                       |  44
code/apiad_0_1/A.cpp.tk                             |  18
code/apiad_1_1/B.cpp.tk                             |  20
code/apiad_2_1/C.cpp.tk                             |  27
code/azaky_0_1/A.cpp.tk                             |  16
code/azaky_1_1/B.cpp.tk                             |  16
code/azaky_2_1/C.cpp.tk                             |  48
code/azariamuh_0_1/standing.cpp.tk                  |  10
code/azariamuh_1_1/pancake.cpp.tk                   |  16
code/azariamuh_2_1/dijkstra.cpp.tk                  |  16
code/bmerry_0_1/a.cpp.tk                            |  43
code/bmerry_1_1/b.cpp.tk                            |  60
code/bmerry_2_1/c.cpp.tk                            |  57
code/climpet_0_1/A.cpp.tk                           |  27
code/climpet_1_1/B.cpp.tk                           |  35
code/climpet_2_1/C.cpp.tk                           |  55
code/ctzsm_0_1/A.cpp.tk                             |  16
code/ctzsm_1_1/B.cpp.tk                             |  23
code/ctzsm_2_1/C.cpp.tk                             |  70
code/DanilC_0_1/problem.cpp.tk                      |  28
code/DanilC_1_1/problemB.cpp.tk                     |  45
code/DanilC_2_1/problemC.cpp.tk                     |  108
code/DEGwer_0_1/A.cpp.tk                            |  32
code/DEGwer_1_1/B.cpp.tk                            |  39
code/DEGwer_2_1/C.cpp.tk                            |  39
code/dmute_0_1/a.cpp.tk                             |  15
code/dmute_1_1/b.cpp.tk                             |  28
code/dmute_2_1/c2.cpp.tk                            |  65
code/fagu_0_1/A.cpp.tk                              |  20
code/fagu_1_1/B.cpp.tk                              |  20
code/fagu_2_1/C.cpp.tk                              |  35
code/FatalEagle_0_1/main.cpp.tk                     |  18
code/FatalEagle_1_1/main.cpp.tk                     |  43
code/FatalEagle_2_1/main.cpp.tk                     |  172
code/fullpower_0_1/A.cpp.tk                         |  25
code/fullpower_1_1/B.cpp.tk                         |  43
code/fullpower_2_1/C.cpp.tk                         |  80
code/ICastro_0_1/Standing_Ovation.cpp.tk            |  14
code/ICastro_1_1/Infinite_House_of_Pancakes.cpp.tk  |  24
code/ICastro_2_1/Dijkstra.cpp.tk                    |  62
code/ilackthatsuperpower_0_1/a.cpp.tk               |  71
code/ilackthatsuperpower_1_1/b.cpp.tk               |  72
code/ilackthatsuperpower_2_1/c.cpp.tk               |  93
code/iridescent_0_1/A.cpp.tk                        |  13
code/iridescent_1_1/B.cpp.tk                        |  21
code/iridescent_2_1/C.cpp.tk                        |  32
code/ishraq_0_1/main.cpp.tk                         |  10
code/ishraq_1_1/main.cpp.tk                         |  15
code/ishraq_2_1/main.cpp.tk                         |  42
code/JayXon_0_1/A.cpp.tk                            |  10
code/JayXon_1_1/B.cpp.tk                            |  31
code/JayXon_2_1/C.cpp.tk                            |  26
code/Josse_0_1/A.cpp.tk                             |  27
code/Josse_1_1/B.cpp.tk                             |  44
code/Josse_2_1/C.cpp.tk                             |  119
code/kcm1700_0_1/a.cpp.tk                           |  18
code/kcm1700_1_1/b.cpp.tk                           |  42
code/kcm1700_2_1/c.cpp.tk                           |  78
code/kevinsogo_0_1/a.cpp.tk                         |  10
code/kevinsogo_1_1/b.cpp.tk                         |  14
code/kevinsogo_2_1/c.cpp.tk                         |  41
code/ksun48_0_1/A.cpp.tk                            |  3
code/ksun48_1_1/B.cpp.tk                            |  3
code/ksun48_2_1/C.cpp.tk                            |  14
code/LazyAnna_0_1/1.cpp.tk                          |  11
code/LazyAnna_1_1/2-1.cpp.tk                        |  21
code/LazyAnna_2_1/3.cpp.tk                          |  29
code/Merkurev_0_1/A.cpp.tk                          |  24
code/Merkurev_1_1/B.cpp.tk                          |  56
code/Merkurev_2_1/C.cpp.tk                          |  52
code/mezei_0_1/main.cpp.tk                          |  23
code/mezei_1_1/main.cpp.tk                          |  38
code/mezei_2_1/main.cpp.tk                          |  82
code/Mister_0_1/a.cpp.tk                            |  16
code/Mister_1_1/b.cpp.tk                            |  26
code/Mister_2_1/c.cpp.tk                            |  35
code/namonakiacc_0_1/cpp.cpp.tk                     |  27
code/namonakiacc_1_1/cpp.cpp.tk                     |  30
code/namonakiacc_2_1/cpp.cpp.tk                     |  46
code/Nicolas16_0_1/main.cpp.tk                      |  9
code/Nicolas16_1_1/main.cpp.tk                      |  8
code/Nicolas16_2_1/main.cpp.tk                      |  76
code/pandamonium_0_1/a.cpp.tk                       |  15
code/pandamonium_1_1/b.cpp.tk                       |  57
code/pandamonium_2_1/c.cpp.tk                       |  31
code/pflueger_0_1/A.cpp.tk                          |  14
code/pflueger_1_1/B.cpp.tk                          |  34
code/pflueger_2_1/C.cpp.tk                          |  68
code/ponyopoppo_0_1/A.cpp.tk                        |  10
code/ponyopoppo_1_1/B.cpp.tk                        |  17
code/ponyopoppo_2_1/C.cpp.tk                        |  90
code/Ragnar_0_1/A.cpp.tk                            |  16
code/Ragnar_1_1/B-2.cpp.tk                          |  25
code/Ragnar_2_1/C.cpp.tk                            |  36
code/saffah_0_1/t.cpp.tk                            |  10
code/saffah_1_1/t.cpp.tk                            |  12
code/saffah_2_1/t.cpp.tk                            |  56
code/SamanSami_0_1/A.cpp.tk                         |  5
code/SamanSami_1_1/B.cpp.tk                         |  29
code/SamanSami_2_1/C.cpp.tk                         |  8
code/Savlik_0_1/code.cpp.tk                         |  12
code/Savlik_1_1/code.cpp.tk                         |  10
code/Savlik_2_1/code.cpp.tk                         |  52
code/shik_0_1/pa.cpp.tk                             |  41
code/shik_1_1/pb.cpp.tk                             |  43
code/shik_2_1/pc.cpp.tk                             |  65
code/simsa.st_0_1/A.cpp.tk                          |  8
code/simsa.st_1_1/B.cpp.tk                          |  13
code/simsa.st_2_1/C.cpp.tk                          |  55
code/SovietUnion_0_1/A.cpp.tk                       |  19
code/SovietUnion_1_1/B.cpp.tk                       |  23
code/SovietUnion_2_1/C.cpp.tk                       |  52
code/tailed_0_1/A.cpp.tk                            |  13
code/tailed_1_1/B.cpp.tk                            |  17
code/tailed_2_1/C.cpp.tk                            |  30
code/TheNatural_0_1/A.cpp.tk                        |  19
code/TheNatural_1_1/B.cpp.tk                        |  35
code/TheNatural_2_1/C.cpp.tk                        |  26
code/TrueBamboo_0_1/test.cpp.tk                     |  15
code/TrueBamboo_1_1/test.cpp.tk                     |  23
code/TrueBamboo_2_1/test.cpp.tk                     |  43
code/tur.turczyn_0_1/A.cpp.tk                       |  17
code/tur.turczyn_1_1/B.cpp.tk                       |  22
code/tur.turczyn_2_1/C.cpp.tk                       |  27
code/Tyg3R_0_1/A.cpp.tk                             |  7
code/Tyg3R_1_1/B.cpp.tk                             |  11
code/Tyg3R_2_1/C.cpp.tk                             |  16
code/UminchuR_0_1/main.cpp.tk                       |  22
code/UminchuR_1_1/main.cpp.tk                       |  26
code/UminchuR_2_1/main.cpp.tk                       |  42
code/wo..._0_1/a.cpp.tk                             |  39
code/wo..._1_1/b.cpp.tk                             |  40
code/wo..._2_1/c.cpp.tk                             |  84
code/yswtt_0_1/A.cpp.tk                             |  12
code/yswtt_1_1/B.cpp.tk                             |  21
code/yswtt_2_1/C.cpp.tk                             |  35
code/ZhSh_0_1/a.cpp.tk                              |  12
code/ZhSh_1_1/b.cpp.tk                              |  50
code/ZhSh_2_1/c.cpp.tk                              |  58
